DeepNet: tools::PCRERegex Class Reference
tools::PCRERegex Class Reference
wrapper class for perl compatible regexes.
#include <PCRERegex.h>
Public Member Functions
PCRERegex (const std::string &regexExp, const bool caseInsensitive=false, const bool multiLine=false, const bool utf8Mode=false)
construct a regular expression.
virtual ~PCRERegex ()
bool Match (const std::string &target)
check if regex matches a string.
bool Match (const std::string &target, std::vector< std::string > &groups)
check if regex matches a string.
PCRERegexResult MatchEx (const char *target, const int offSet, const int nMaxMatches)
check if regex matches a string returning detailed information.
Static Public Member Functions
static bool Match (const std::string &regexExp, const std::string &target, std::vector< std::string > &groups, const bool caseInsensitive=false, const bool multiLine=false, const bool utf8Mode=false)
check if regex matches a string.
Private Member Functions
PCRERegex (const PCRERegex &)
PCRERegex & operator= (const PCRERegex &)
Static Private Member Functions
static bool Compile (const std::string &regexExp, const bool caseInsensitive, const bool multiLine, const bool utf8Mode, pcre **regex, pcre_extra **extraData, int **subStringPos, int *subStringCount)
static void FreeRegex (pcre **regex, pcre_extra **extra_data, int **subStringPos)
static bool Match (const pcre *regex, const pcre_extra *extra_data, const int subStringCount, int *subStringPos, const std::string &target, std::vector< std::string > &groups)
static PCRERegexResult MatchEx (const pcre *regex, const pcre_extra *extra_data, const int subStringCount, int *subStringPos, const char *target, const int offSet, const int nMaxMatches)
Private Attributes
pcre * regex
pcre_extra * extra_data
int subStringCount
int * subStringPos
Detailed Description
wrapper class for perl compatible regexes.
Definition at line 23 of file PCRERegex.h.
Constructor & Destructor Documentation
tools::PCRERegex::PCRERegex (const std::string & regexExp, const bool caseInsensitive = false, const bool multiLine = false, const bool utf8Mode = false)
construct a regular expression.
Parameters:
regexExp expression string.
caseInsensitive true if expression is case insensitive.
multiLine true if expression is multiline.
utf8Mode true if expression is for UTF8.
Definition at line 16 of file PCRERegex.cpp.
References Compile(), extra_data, regex, subStringCount, and subStringPos.
tools::PCRERegex::~PCRERegex () [virtual]
Definition at line 29 of file PCRERegex.cpp.
References extra_data, FreeRegex(), regex, and subStringPos.
tools::PCRERegex::PCRERegex (const PCRERegex &) [inline, private]
Definition at line 41 of file PCRERegex.h.
References THROW_EXCEPTION.
Member Function Documentation
PCRERegex& tools::PCRERegex::operator= (const PCRERegex &) [inline, private]
Definition at line 45 of file PCRERegex.h.
References THROW_EXCEPTION.
bool tools::PCRERegex::Match (const std::string & target)
check if regex matches a string.
Parameters:
target string to check.
Returns:
false if not a match, true if match.
Definition at line 112 of file PCRERegex.cpp.
Referenced by tools::FileTools::ListDirectory(), caching::RobotTxt::Load(), indexing::DataminingCriteria::Match(), Match(), indexing::IndexerEx::Parse(), toolbot::UnitTestPCRERegex::ParseExpectedGroups(), indexing::IndexerEx::ParseMeta(), toolbot::UnitTestPCRERegex::ParseTestFile(), and toolbot::UnitTestPCRERegex::Run().
bool tools::PCRERegex::Match (const std::string & target, std::vector< std::string > & groups)
check if regex matches a string.
Parameters:
target string to check.
groups result groups.
Returns:
false if not a match, true if match.
Definition at line 118 of file PCRERegex.cpp.
References extra_data, Match(), regex, subStringCount, and subStringPos.
PCRERegexResult tools::PCRERegex::MatchEx (const char * target, const int offSet, const int nMaxMatches)
check if regex matches a string returning detailed information.
Parameters:
target string to check.
offSet offset for regex.
nMaxMatches maximum number of matches.
Returns:
result
Definition at line 154 of file PCRERegex.cpp.
References extra_data, regex, subStringCount, and subStringPos.
bool tools::PCRERegex::Match (const std::string & regexExp, const std::string & target, std::vector< std::string > & groups, const bool caseInsensitive = false, const bool multiLine = false, const bool utf8Mode = false) [static]
check if regex matches a string.
Parameters:
regexExp expression string.
target string to check.
groups gets filled groups.
caseInsensitive true if expression is case insensitive.
multiLine true if expression is multiline.
utf8Mode true if expression is for UTF8.
Definition at line 125 of file PCRERegex.cpp.
References Compile(), extra_data, FreeRegex(), Match(), regex, subStringCount, and subStringPos.
bool tools::PCRERegex::Compile (const std::string & regexExp, const bool caseInsensitive, const bool multiLine, const bool utf8Mode, pcre ** regex, pcre_extra ** extraData, int ** subStringPos, int * subStringCount) [static, private]
Definition at line 34 of file PCRERegex.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, and subStringCount.
Referenced by Match(), and PCRERegex().
void tools::PCRERegex::FreeRegex (pcre ** regex, pcre_extra ** extra_data, int ** subStringPos) [static, private]
Definition at line 140 of file PCRERegex.cpp.
References subStringPos.
Referenced by Match(), and ~PCRERegex().
bool tools::PCRERegex::Match (const pcre * regex, const pcre_extra * extra_data, const int subStringCount, int * subStringPos, const std::string & target, std::vector< std::string > & groups) [static, private]
Definition at line 76 of file PCRERegex.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
PCRERegexResult tools::PCRERegex::MatchEx (const pcre * regex, const pcre_extra * extra_data, const int subStringCount, int * subStringPos, const char * target, const int offSet, const int nMaxMatches) [static, private]
Definition at line 159 of file PCRERegex.cpp.
References tools::PCRERegexGroup::begin, tools::PCRERegexResult::begin, tools::PCRERegexGroup::end, tools::PCRERegexResult::end, tools::PCRERegexResult::groups, tools::PCRERegexGroup::groupValue, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, and tools::PCRERegexResult::success.
Member Data Documentation
pcre* tools::PCRERegex::regex [private]
Definition at line 132 of file PCRERegex.h.
Referenced by Match(), MatchEx(), PCRERegex(), and ~PCRERegex().
pcre_extra* tools::PCRERegex::extra_data [private]
Definition at line 133 of file PCRERegex.h.
Referenced by Match(), MatchEx(), PCRERegex(), and ~PCRERegex().
int tools::PCRERegex::subStringCount [private]
Definition at line 134 of file PCRERegex.h.
Referenced by Compile(), Match(), MatchEx(), and PCRERegex().
int* tools::PCRERegex::subStringPos [private]
Definition at line 135 of file PCRERegex.h.
Referenced by FreeRegex(), Match(), MatchEx(), PCRERegex(), and ~PCRERegex().
The documentation for this class was generated from the following files:
Tools/src/PCRERegex.h
Tools/src/PCRERegex.cpp