DeepNet: toolbot::CommerceSearchTools Class Reference
toolbot::CommerceSearchTools Class Reference
#include <CommerceSearchTools.h>
Public Member Functions
virtual ~CommerceSearchTools ()
Static Public Member Functions
static bool AddCustomer (database::DatabaseConnection *db, const std::string &username, const std::string &password, const std::string &domain, const long long revisitInterval)
Private Member Functions
CommerceSearchTools ()
Detailed Description
Definition at line 19 of file CommerceSearchTools.h.
Constructor & Destructor Documentation
toolbot::CommerceSearchTools::CommerceSearchTools () [private]
Definition at line 16 of file CommerceSearchTools.cpp.
toolbot::CommerceSearchTools::~CommerceSearchTools () [virtual]
Definition at line 20 of file CommerceSearchTools.cpp.
Member Function Documentation
bool toolbot::CommerceSearchTools::AddCustomer (database::DatabaseConnection * db, const std::string & username, const std::string & password, const std::string & domain, const long long revisitInterval) [static]
Definition at line 23 of file CommerceSearchTools.cpp.
References tools::HashTools::GetSHA512(), database::TableBase::Insert(), database::DatabaseConnection::LastInsertID(), tools::TimeTools::NowUTC(), database::customersynccrawlerTableBase::Set_CRAWLERSESSION_ID(), database::customerdomainsTableBase::Set_CUSTOMER_ID(), database::customersynccrawlerTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerdomainsTableBase::Set_domain(), database::customerdomainsTableBase::Set_isDomainRegex(), database::customersTableBase::Set_login(), database::customersTableBase::Set_password(), database::customerdomainsTableBase::Set_revisitInterval(), database::customersynccrawlerTableBase::Set_scheduled(), database::DatabaseConnection::TransactionCommit(), database::DatabaseConnection::TransactionRollback(), and database::DatabaseConnection::TransactionStart().
Referenced by toolbot::DeepNetToolBot::OnRun().
The documentation for this class was generated from the following files:
DeepNetTool/src/CommerceSearchTools.h
DeepNetTool/src/CommerceSearchTools.cpp