DeepNet: caching::CacheSecondLevelDomain Class Reference
caching::CacheSecondLevelDomain Class Reference
cache for secondlevel domains.
#include <CacheSecondLevelDomain.h>
Public Member Functions
virtual ~CacheSecondLevelDomain ()
Static Public Member Functions
static void GetSecondLevelIDByDomain (database::DatabaseConnection *connection, const std::string &secondleveldomain, long long &secondleveldomainID)
gets secondlevel domain id by string.
static void GetDomainBySecondLevelID (database::DatabaseConnection *connection, const long long &secondleveldomainID, std::string &secondleveldomain)
gets secondlevel domain by it's id.
static void Clear (void)
removes all items from cache.
static void SetCapacity (const size_t capacity)
set current limit of cache.
static size_t GetSize ()
gets current number of entries in cache.
static size_t GetMatches ()
get current match count of cache, clearing internal match counter.
static size_t GetMisses ()
get current miss count of cache, clearing internal miss counter.
Private Member Functions
CacheSecondLevelDomain (size_t limit=0)
Private Attributes
Cache< long long, std::string > idSecondLevelDomain
Static Private Attributes
static CacheSecondLevelDomain cacheInstance
Detailed Description
cache for secondlevel domains.
Definition at line 24 of file CacheSecondLevelDomain.h.
Constructor & Destructor Documentation
caching::CacheSecondLevelDomain::CacheSecondLevelDomain (size_t limit = 0) [private]
Definition at line 18 of file CacheSecondLevelDomain.cpp.
caching::CacheSecondLevelDomain::~CacheSecondLevelDomain () [virtual]
Definition at line 23 of file CacheSecondLevelDomain.cpp.
Member Function Documentation
void caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain (database::DatabaseConnection * connection, const std::string & secondleveldomain, long long & secondleveldomainID) [static]
gets secondlevel domain id by string.
this function may add secondlevel domains to database.
Parameters:
connection database connection.
secondleveldomain secondlevel domain.
secondleveldomainID gets filled with corresponding secondlevel domain id.
Definition at line 27 of file CacheSecondLevelDomain.cpp.
References caching::Cache< T, V >::AddItem(), cacheInstance, caching::Cache< T, V >::GetByValue(), idSecondLevelDomain, database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), and database::secondleveldomainsTableBase::Set_domain().
Referenced by htmlparser::DatabaseUrl::InitByHttpUrl(), and parser::GenericWebHtmlParserThread::InsertImages().
void caching::CacheSecondLevelDomain::GetDomainBySecondLevelID (database::DatabaseConnection * connection, const long long & secondleveldomainID, std::string & secondleveldomain) [static]
gets secondlevel domain by it's id.
Parameters:
connection database connection.
secondleveldomainID secondlevel domain id.
secondleveldomain gets filled with corresponding secondlevel domain.
Definition at line 45 of file CacheSecondLevelDomain.cpp.
References caching::Cache< T, V >::AddItem(), cacheInstance, database::secondleveldomainsTableBase::Get_domain(), database::secondleveldomainsTableBase::GetBy_ID(), caching::Cache< T, V >::GetItem(), tools::PointerContainer< T >::GetIter(), idSecondLevelDomain, tools::PointerContainer< T >::ResetIter(), tools::PointerContainer< T >::Size(), and THROW_EXCEPTION.
Referenced by htmlparser::DatabaseUrl::InitByIDs().
void caching::CacheSecondLevelDomain::Clear (void) [static]
removes all items from cache.
Definition at line 72 of file CacheSecondLevelDomain.cpp.
References cacheInstance, caching::Cache< T, V >::ClearItems(), and idSecondLevelDomain.
void caching::CacheSecondLevelDomain::SetCapacity (const size_t capacity) [static]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 67 of file CacheSecondLevelDomain.cpp.
References cacheInstance, idSecondLevelDomain, and caching::Cache< T, V >::SetLimit().
Referenced by bot::Bot::InitCacheConfigParams().
static size_t caching::CacheSecondLevelDomain::GetSize () [inline, static]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 69 of file CacheSecondLevelDomain.h.
References cacheInstance, caching::Cache< T, V >::GetSize(), and idSecondLevelDomain.
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheSecondLevelDomain::GetMatches () [inline, static]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 75 of file CacheSecondLevelDomain.h.
References cacheInstance, caching::Cache< T, V >::GetMatches(), and idSecondLevelDomain.
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheSecondLevelDomain::GetMisses () [inline, static]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 81 of file CacheSecondLevelDomain.h.
References cacheInstance, caching::Cache< T, V >::GetMisses(), and idSecondLevelDomain.
Referenced by bot::Bot::WatchDog().
Member Data Documentation
CacheSecondLevelDomain caching::CacheSecondLevelDomain::cacheInstance [static, private]
Definition at line 84 of file CacheSecondLevelDomain.h.
Referenced by Clear(), GetDomainBySecondLevelID(), GetMatches(), GetMisses(), GetSecondLevelIDByDomain(), GetSize(), and SetCapacity().
Cache<long long,std::string> caching::CacheSecondLevelDomain::idSecondLevelDomain [private]
Definition at line 87 of file CacheSecondLevelDomain.h.
Referenced by Clear(), GetDomainBySecondLevelID(), GetMatches(), GetMisses(), GetSecondLevelIDByDomain(), GetSize(), and SetCapacity().
The documentation for this class was generated from the following files:
Caching/src/CacheSecondLevelDomain.h
Caching/src/CacheSecondLevelDomain.cpp