DeepNet: network::IPv4Tools Class Reference
network::IPv4Tools Class Reference
implements IPv4 functionality
#include <IPv4Tools.h>
Public Member Functions
virtual ~IPv4Tools ()
Static Public Member Functions
static std::string ToString (const struct in_addr &ip)
converts ip to string.
static std::string ToString (const struct sockaddr_in &ip)
converts ip endpoint to string.
static bool ResolveHost (const std::string &hostname, struct in_addr &addr)
resolves hostname to ip (dns forward lookup).
Private Member Functions
IPv4Tools ()
Detailed Description
implements IPv4 functionality
Definition at line 17 of file IPv4Tools.h.
Constructor & Destructor Documentation
network::IPv4Tools::IPv4Tools () [private]
Definition at line 17 of file IPv4Tools.cpp.
network::IPv4Tools::~IPv4Tools () [virtual]
Definition at line 20 of file IPv4Tools.cpp.
Member Function Documentation
std::string network::IPv4Tools::ToString (const struct in_addr & ip) [static]
converts ip to string.
Parameters:
ip ip to converted.
Returns:
ip as string.
Definition at line 28 of file IPv4Tools.cpp.
Referenced by ToString().
std::string network::IPv4Tools::ToString (const struct sockaddr_in & ip) [static]
converts ip endpoint to string.
Parameters:
ip endpoint
Returns:
endpoint as string.
Definition at line 23 of file IPv4Tools.cpp.
References ToString(), and tools::StringTools::TransformString().
bool network::IPv4Tools::ResolveHost (const std::string & hostname, struct in_addr & addr) [static]
resolves hostname to ip (dns forward lookup).
Parameters:
hostname hostname
addr output ip.
Returns:
false on error, true on success.
Definition at line 41 of file IPv4Tools.cpp.
The documentation for this class was generated from the following files:
Networking/src/IPv4Tools.h
Networking/src/IPv4Tools.cpp