DeepNet: fastcgiserver::FastCGIResponse Class Reference
fastcgiserver::FastCGIResponse Class Reference
container for a fastcgi server response.
#include <FastCGIResponse.h>
Public Member Functions
FastCGIResponse (FastCGIRequest *fcgiRequest)
constructs response.
virtual ~FastCGIResponse ()
virtual bool Process (FCGX_Request &request)
processes fastcgi client request.
std::string ToString ()
converts request to string
Protected Attributes
FastCGIRequest * fcgiRequest
corresponding request.
HttpHeader header
response header.
std::string content
content of response.
Detailed Description
container for a fastcgi server response.
Definition at line 17 of file FastCGIResponse.h.
Constructor & Destructor Documentation
fastcgiserver::FastCGIResponse::FastCGIResponse (FastCGIRequest * fcgiRequest)
constructs response.
Parameters:
fcgiRequest corresponding request.
Definition at line 13 of file FastCGIResponse.cpp.
fastcgiserver::FastCGIResponse::~FastCGIResponse () [virtual]
Definition at line 18 of file FastCGIResponse.cpp.
Member Function Documentation
bool fastcgiserver::FastCGIResponse::Process (FCGX_Request & request) [virtual]
processes fastcgi client request.
Parameters:
request corresponding request.
Returns:
false on error, true on success.
Reimplemented in queryserver::XMLQueryResponse, inspectorserver::InspectorServerResponse, and suggestserver::SuggestServerResponse.
Definition at line 21 of file FastCGIResponse.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, and ToString().
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
std::string fastcgiserver::FastCGIResponse::ToString (void) [inline]
converts request to string
Returns:
request string.
Definition at line 38 of file FastCGIResponse.h.
References content, header, and fastcgiserver::HttpHeader::ToString().
Referenced by Process().
Member Data Documentation
FastCGIRequest* fastcgiserver::FastCGIResponse::fcgiRequest [protected]
corresponding request.
Definition at line 44 of file FastCGIResponse.h.
HttpHeader fastcgiserver::FastCGIResponse::header [protected]
response header.
Definition at line 49 of file FastCGIResponse.h.
Referenced by ToString().
std::string fastcgiserver::FastCGIResponse::content [protected]
content of response.
Definition at line 54 of file FastCGIResponse.h.
Referenced by queryserver::XMLQueryResponse::OutputResults(), suggestserver::SuggestServerResponse::Process(), inspectorserver::InspectorServerResponse::Process(), and ToString().
The documentation for this class was generated from the following files:
FastCGIServer/src/FastCGIResponse.h
FastCGIServer/src/FastCGIResponse.cpp