DeepNet: database::TableColumnContainer Class Reference
database::TableColumnContainer Class Reference
container for a single TableColumn pointer.
#include <TableColumnContainer.h>
Public Member Functions
TableColumnContainer (TableColumn *pCol)
construct by existing column.
virtual ~TableColumnContainer ()
const TableColumn * GetConstColumn () const
gets const table column.
TableColumn * GetColumn ()
gets table column.
Private Member Functions
TableColumnContainer (const TableColumnContainer &container)
void CleanUp ()
Private Attributes
TableColumn * pCol
Detailed Description
container for a single TableColumn pointer.
manages memory of a single TableColumnContainer.
Definition at line 16 of file TableColumnContainer.h.
Constructor & Destructor Documentation
database::TableColumnContainer::TableColumnContainer (const TableColumnContainer & container) [private]
Definition at line 19 of file TableColumnContainer.cpp.
References THROW_EXCEPTION.
database::TableColumnContainer::TableColumnContainer (TableColumn * pCol)
construct by existing column.
Parameters:
pCol existing column.
Definition at line 15 of file TableColumnContainer.cpp.
database::TableColumnContainer::~TableColumnContainer () [virtual]
Definition at line 25 of file TableColumnContainer.cpp.
References CleanUp().
Member Function Documentation
const TableColumn* database::TableColumnContainer::GetConstColumn () const [inline]
gets const table column.
Returns:
table column;
Definition at line 34 of file TableColumnContainer.h.
References pCol.
Referenced by database::WhereConditionTableColumn::ToString().
TableColumn* database::TableColumnContainer::GetColumn () [inline]
gets table column.
Returns:
table column;
Definition at line 40 of file TableColumnContainer.h.
References pCol.
void database::TableColumnContainer::CleanUp () [private]
Definition at line 30 of file TableColumnContainer.cpp.
References pCol.
Referenced by ~TableColumnContainer().
Member Data Documentation
TableColumn* database::TableColumnContainer::pCol [private]
Definition at line 46 of file TableColumnContainer.h.
Referenced by CleanUp(), GetColumn(), and GetConstColumn().
The documentation for this class was generated from the following files:
Database/src/TableColumnContainer.h
Database/src/TableColumnContainer.cpp