DeepNet: caching::CacheHtml Class Reference
caching::CacheHtml Class Reference
cache for network::HtmlData and corresponding data.
#include <CacheHtml.h>
Public Member Functions
virtual ~CacheHtml ()
Static Public Member Functions
static void Add (const long long &ID, const htmlparser::DatabaseUrl &url, const network::HtmlData &html, const long long urlStageID)
add a new element to cache.
static bool Get (std::map< long long, CacheHtmlEntry > &entries, const int count)
get elements by count.
static void SetCapacity (const size_t capacity)
set current limit of cache.
static size_t GetSize ()
gets current number of entries in cache.
static size_t GetMatches ()
get current match count of cache, clearing internal match counter.
static size_t GetMisses ()
get current miss count of cache, clearing internal miss counter.
Private Member Functions
CacheHtml (size_t limit=0)
Private Attributes
Cache< long long, CacheHtmlEntry > cacheHtmlCode
Static Private Attributes
static CacheHtml cacheInstance
Detailed Description
cache for network::HtmlData and corresponding data.
Definition at line 29 of file CacheHtml.h.
Constructor & Destructor Documentation
caching::CacheHtml::CacheHtml (size_t limit = 0) [private]
Definition at line 16 of file CacheHtml.cpp.
caching::CacheHtml::~CacheHtml () [virtual]
Definition at line 21 of file CacheHtml.cpp.
Member Function Documentation
void caching::CacheHtml::Add (const long long & ID, const htmlparser::DatabaseUrl & url, const network::HtmlData & html, const long long urlStageID) [static]
add a new element to cache.
Parameters:
ID url-id.
url parsed url.
html html code.
urlStageID urlstage-id.
Definition at line 25 of file CacheHtml.cpp.
References caching::Cache< T, V >::AddItem(), cacheHtmlCode, and cacheInstance.
Referenced by crawler::UrlFetcherThread::CommitPages().
bool caching::CacheHtml::Get (std::map< long long, CacheHtmlEntry > & entries, const int count) [static]
get elements by count.
Parameters:
entries gets filled with elements.
count maximum number of elements to get.
Returns:
false if cache is empty, true on success.
Definition at line 30 of file CacheHtml.cpp.
References cacheHtmlCode, cacheInstance, and caching::Cache< T, V >::GetItem().
Referenced by parser::HtmlParserThread::GetNextPages().
static void caching::CacheHtml::SetCapacity (const size_t capacity) [inline, static]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 65 of file CacheHtml.h.
References cacheHtmlCode, cacheInstance, and caching::Cache< T, V >::SetLimit().
Referenced by bot::Bot::InitCacheConfigParams().
static size_t caching::CacheHtml::GetSize () [inline, static]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 71 of file CacheHtml.h.
References cacheHtmlCode, cacheInstance, and caching::Cache< T, V >::GetSize().
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheHtml::GetMatches () [inline, static]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 77 of file CacheHtml.h.
References cacheHtmlCode, cacheInstance, and caching::Cache< T, V >::GetMatches().
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheHtml::GetMisses () [inline, static]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 83 of file CacheHtml.h.
References cacheHtmlCode, cacheInstance, and caching::Cache< T, V >::GetMisses().
Referenced by bot::Bot::WatchDog().
Member Data Documentation
CacheHtml caching::CacheHtml::cacheInstance [static, private]
Definition at line 86 of file CacheHtml.h.
Referenced by Add(), Get(), GetMatches(), GetMisses(), GetSize(), and SetCapacity().
Cache<long long, CacheHtmlEntry> caching::CacheHtml::cacheHtmlCode [private]
Definition at line 89 of file CacheHtml.h.
Referenced by Add(), Get(), GetMatches(), GetMisses(), GetSize(), and SetCapacity().
The documentation for this class was generated from the following files:
Caching/src/CacheHtml.h
Caching/src/CacheHtml.cpp