DeepNet: database::OrderByClause Class Reference
database::OrderByClause Class Reference
implements generic sql "ORDER BY" parts.
#include <OrderByClause.h>
Public Member Functions
OrderByClause ()
virtual ~OrderByClause ()
bool AddColumn (TableColumnDefinition *colDef, const OrderByClauseDirection &dir)
add column to order by.
bool AddColumn (TableColumnDefinition *colDef, const OrderByClauseDirection &dir, const std::string &tableAlias, const std::string &columnAlias)
add column to order by using aliases.
std::string ToString (database::DatabaseConnection *db) const
gets sql equivalent of this order by part.
Private Attributes
std::vector< OrderByColumn > orderByFields
Detailed Description
implements generic sql "ORDER BY" parts.
implements generic sql "ORDER BY" parts for sql statements.
Definition at line 50 of file OrderByClause.h.
Constructor & Destructor Documentation
database::OrderByClause::OrderByClause ()
Definition at line 15 of file OrderByClause.cpp.
database::OrderByClause::~OrderByClause () [virtual]
Definition at line 18 of file OrderByClause.cpp.
References orderByFields.
Member Function Documentation
bool database::OrderByClause::AddColumn (TableColumnDefinition * colDef, const OrderByClauseDirection & dir)
add column to order by.
Parameters:
colDef column to order by.
dir ascending/descending order.
Returns:
false on error, true on success.
Definition at line 26 of file OrderByClause.cpp.
References database::OrderByColumn::colDef, database::OrderByColumn::columnAlias, database::OrderByColumn::dir, orderByFields, and database::OrderByColumn::tableAlias.
Referenced by queryserver::XMLQueryResponse::GetKeywordIDs(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::ProcessExistQuery(), and database::UpdateStatement::UpdateStatement().
bool database::OrderByClause::AddColumn (TableColumnDefinition * colDef, const OrderByClauseDirection & dir, const std::string & tableAlias, const std::string & columnAlias)
add column to order by using aliases.
Parameters:
colDef column to order by.
dir ascending/descending order.
tableAlias table name alias.
columnAlias column name alias.
Returns:
false on error, true on success.
Definition at line 37 of file OrderByClause.cpp.
References database::OrderByColumn::colDef, database::OrderByColumn::columnAlias, database::OrderByColumn::dir, orderByFields, and database::OrderByColumn::tableAlias.
std::string database::OrderByClause::ToString (database::DatabaseConnection * db) const
gets sql equivalent of this order by part.
Parameters:
db database connection.
Returns:
sql string.
Definition at line 52 of file OrderByClause.cpp.
References database::ASCENDING, database::DESCENDING, orderByFields, and THROW_EXCEPTION.
Referenced by database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
Member Data Documentation
std::vector<OrderByColumn> database::OrderByClause::orderByFields [private]
Definition at line 87 of file OrderByClause.h.
Referenced by AddColumn(), ToString(), and ~OrderByClause().
The documentation for this class was generated from the following files:
Database/src/OrderByClause.h
Database/src/OrderByClause.cpp