DeepNet: domparser::DocumentFactory Class Reference
domparser::DocumentFactory Class Reference
factory class for html documents
#include <DocumentFactory.h>
Public Member Functions
virtual ~DocumentFactory ()
Static Public Member Functions
static Document * FromHtmlData (const network::HttpUrl &url, const network::HtmlData &data)
creates an HtmlDocument from data string
Protected Types
enum InsertionMode {
initial, before_html, before_head, in_head,
in_head_noscript, after_head, in_body, text,
in_table, in_table_text, in_caption, in_column_group,
in_table_body, in_row, in_cell, in_select,
in_select_in_table, after_body, in_frameset, after_frameset,
after_after_body, after_after_frameset
}
Protected Member Functions
DocumentFactory (const network::HttpUrl &url)
constructs a DocumentFactory object
bool ParseFromString (const char *content, const size_t &size)
virtual bool OnToken (const domparser::generic::Token &token)
virtual void SwitchMode (const InsertionMode &newInsertionMode)
void ParseError () const
bool OnInsertion (const domparser::generic::Token &token, InsertionMode mode)
bool OnForeignContent (const domparser::generic::Token &token)
bool AppendComment (const domparser::generic::CommentToken &token)
bool AppendDocType (const domparser::generic::DocTypeToken &token)
bool AppendGenericRCDATA (const domparser::generic::TagToken &token)
bool AppendGenericRawText (const domparser::generic::TagToken &token)
bool AppendGenericRCDATAOrRawText (const domparser::generic::TagToken &token, bool isRCData)
bool InsertCharacter (const domparser::generic::CharacterToken &token)
bool OnInitialInsertion (const domparser::generic::Token &token)
bool OnBeforeHtmlInsertion (const domparser::generic::Token &token)
bool OnBeforeHeadInsertion (const domparser::generic::Token &token)
bool OnInHeadInsertion (const domparser::generic::Token &token)
bool OnInHeadNoscriptInsertion (const domparser::generic::Token &token)
bool OnAfterHeadInsertion (const domparser::generic::Token &token)
bool OnInBodyInsertion (const domparser::generic::Token &token)
bool OnTextInsertion (const domparser::generic::Token &token)
bool OnInTableInsertion (const domparser::generic::Token &token)
bool OnInTableTextInsertion (const domparser::generic::Token &token)
bool OnInCaptionInsertion (const domparser::generic::Token &token)
bool OnInColumnGroupInsertion (const domparser::generic::Token &token)
bool OnInTableBodyInsertion (const domparser::generic::Token &token)
bool OnInRowInsertion (const domparser::generic::Token &token)
bool OnInCellInsertion (const domparser::generic::Token &token)
bool OnInSelectInsertion (const domparser::generic::Token &token)
bool OnInSelectInTableInsertion (const domparser::generic::Token &token)
bool OnAfterBodyInsertion (const domparser::generic::Token &token)
bool OnInFramesetInsertion (const domparser::generic::Token &token)
bool OnAfterFramesetInsertion (const domparser::generic::Token &token)
bool OnAfterAfterBodyInsertion (const domparser::generic::Token &token)
bool OnAfterAfterFramesetInsertion (const domparser::generic::Token &token)
bool OnInBodyStartTagInsertion (const domparser::generic::TagToken &tagToken)
bool OnInBodyEndTagInsertion (const domparser::generic::TagToken &tagToken)
Static Protected Member Functions
static std::string InsertionModeToString (const InsertionMode &insertMode)
Protected Attributes
const network::HttpUrl & url
Document * curDoc
html5::Tokeniser * tokeniser
InsertionMode insertionMode
InsertionMode orgInsertionMode
tools::Stack< Node * > openElementStack
HTMLHeadElement * headElement
HTMLFormElement * formElement
Private Member Functions
HTMLElement * InsertHtmlElement (const domparser::generic::TagToken &token)
void ReconstructActiveFormatElements ()
void ResetInsertionMode ()
bool OnInitialInsertion_DOCTYPE (const domparser::generic::DocTypeToken &token)
bool IgnoreHtmlWhiteSpace (const domparser::generic::CharacterToken &token)
Private Attributes
bool scriptingFlag
bool framesetOk
Friends
class html5::Tokeniser
Detailed Description
factory class for html documents
See also:
domparser::Document
toolbot::UnitTestDocumentFactory
Definition at line 51 of file DocumentFactory.h.
Member Enumeration Documentation
enum domparser::DocumentFactory::InsertionMode [protected]
Enumerator:
initial
before_html
before_head
in_head
in_head_noscript
after_head
in_body
text
in_table
in_table_text
in_caption
in_column_group
in_table_body
in_row
in_cell
in_select
in_select_in_table
after_body
in_frameset
after_frameset
after_after_body
after_after_frameset
Definition at line 56 of file DocumentFactory.h.
Constructor & Destructor Documentation
domparser::DocumentFactory::DocumentFactory (const network::HttpUrl & url) [protected]
constructs a DocumentFactory object
Parameters:
url url of the document
See also:
domparser::DocumentFactory::FromHtmlData
Definition at line 31 of file DocumentFactory.cpp.
domparser::DocumentFactory::~DocumentFactory () [virtual]
Definition at line 43 of file DocumentFactory.cpp.
Member Function Documentation
Document * domparser::DocumentFactory::FromHtmlData (const network::HttpUrl & url, const network::HtmlData & data) [static]
creates an HtmlDocument from data string
Parameters:
url url of document.
data html data.
Returns:
NULL on error, document on success.
Definition at line 46 of file DocumentFactory.cpp.
References curDoc, network::HtmlData::GetBuffer(), network::HtmlData::GetBufferSize(), network::HtmlData::GetContentType(), domparser::html5::Tokeniser::Parse(), and tokeniser.
Referenced by domparser::DOMParser::Parse().
bool domparser::DocumentFactory::ParseFromString (const char * content, const size_t & size) [protected]
bool domparser::DocumentFactory::OnToken (const domparser::generic::Token & token) [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlDocumentFactory.
Definition at line 188 of file DocumentFactory.cpp.
References insertionMode, OnForeignContent(), and OnInsertion().
Referenced by domparser::html5::Tokeniser::EmitCharacter(), domparser::html5::Tokeniser::EmitComment(), domparser::html5::Tokeniser::EmitDocType(), domparser::html5::Tokeniser::EmitTag(), OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyEndTagInsertion(), OnInBodyStartTagInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), and OnInitialInsertion().
void domparser::DocumentFactory::SwitchMode (const InsertionMode & newInsertionMode) [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlDocumentFactory.
Definition at line 184 of file DocumentFactory.cpp.
References insertionMode.
Referenced by OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyEndTagInsertion(), OnInBodyStartTagInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), OnInitialInsertion(), OnInitialInsertion_DOCTYPE(), and OnTextInsertion().
void domparser::DocumentFactory::ParseError () const [protected]
Definition at line 56 of file DocumentFactory.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), log::Logging::LogInfo(), and tokeniser.
Referenced by OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyEndTagInsertion(), OnInBodyInsertion(), OnInBodyStartTagInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), OnInitialInsertion(), OnInitialInsertion_DOCTYPE(), and domparser::html5::Tokeniser::ParseError().
bool domparser::DocumentFactory::OnInsertion (const domparser::generic::Token & token, InsertionMode mode) [protected]
Definition at line 200 of file DocumentFactory.cpp.
References after_after_body, after_after_frameset, after_body, after_frameset, after_head, before_head, before_html, in_body, in_caption, in_cell, in_column_group, in_frameset, in_head, in_head_noscript, in_row, in_select, in_select_in_table, in_table, in_table_body, in_table_text, initial, OnAfterAfterBodyInsertion(), OnAfterAfterFramesetInsertion(), OnAfterBodyInsertion(), OnAfterFramesetInsertion(), OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyInsertion(), OnInCaptionInsertion(), OnInCellInsertion(), OnInColumnGroupInsertion(), OnInFramesetInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), OnInitialInsertion(), OnInRowInsertion(), OnInSelectInsertion(), OnInSelectInTableInsertion(), OnInTableBodyInsertion(), OnInTableInsertion(), OnInTableTextInsertion(), OnTextInsertion(), and text.
Referenced by OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnInBodyStartTagInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), and OnToken().
bool domparser::DocumentFactory::OnForeignContent (const domparser::generic::Token & token) [protected]
Definition at line 276 of file DocumentFactory.cpp.
Referenced by OnToken().
bool domparser::DocumentFactory::AppendComment (const domparser::generic::CommentToken & token) [protected]
Definition at line 63 of file DocumentFactory.cpp.
References domparser::Node::appendChild(), curDoc, and domparser::NodeFactory::FromToken().
Referenced by OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyInsertion(), OnInHeadInsertion(), and OnInitialInsertion().
bool domparser::DocumentFactory::AppendDocType (const domparser::generic::DocTypeToken & token) [protected]
Definition at line 79 of file DocumentFactory.cpp.
References domparser::Node::appendChild(), domparser::DOMImplementation::createDocumentType(), curDoc, domparser::Document::implementation, domparser::generic::DocTypeToken::name, domparser::generic::DocTypeToken::public_identifier, and domparser::generic::DocTypeToken::system_identifier.
Referenced by OnInitialInsertion_DOCTYPE().
bool domparser::DocumentFactory::AppendGenericRCDATA (const domparser::generic::TagToken & token) [protected]
Definition at line 69 of file DocumentFactory.cpp.
References AppendGenericRCDATAOrRawText().
Referenced by OnInHeadInsertion().
bool domparser::DocumentFactory::AppendGenericRawText (const domparser::generic::TagToken & token) [protected]
Definition at line 74 of file DocumentFactory.cpp.
References AppendGenericRCDATAOrRawText().
Referenced by OnInHeadInsertion().
bool domparser::DocumentFactory::AppendGenericRCDATAOrRawText (const domparser::generic::TagToken & token, bool isRCData) [protected]
Definition at line 99 of file DocumentFactory.cpp.
References InsertHtmlElement(), insertionMode, orgInsertionMode, domparser::html5::RAWTEXT_state, domparser::html5::RCDATA_state, domparser::html5::Tokeniser::SwitchState(), text, and tokeniser.
Referenced by AppendGenericRawText(), and AppendGenericRCDATA().
bool domparser::DocumentFactory::InsertCharacter (const domparser::generic::CharacterToken & token) [protected]
Definition at line 1039 of file DocumentFactory.cpp.
Referenced by OnAfterHeadInsertion(), OnInBodyInsertion(), OnInHeadInsertion(), and OnTextInsertion().
HTMLElement * domparser::DocumentFactory::InsertHtmlElement (const domparser::generic::TagToken & token) [private]
Definition at line 86 of file DocumentFactory.cpp.
References domparser::Node::appendChild(), curDoc, domparser::NodeFactory::FromToken(), openElementStack, and tools::Stack< T >::Push().
Referenced by AppendGenericRCDATAOrRawText(), OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyStartTagInsertion(), and OnInHeadInsertion().
void domparser::DocumentFactory::ReconstructActiveFormatElements () [private]
Definition at line 1054 of file DocumentFactory.cpp.
Referenced by OnInBodyInsertion().
void domparser::DocumentFactory::ResetInsertionMode () [private]
Definition at line 1047 of file DocumentFactory.cpp.
bool domparser::DocumentFactory::OnInitialInsertion (const domparser::generic::Token & token) [protected]
Definition at line 283 of file DocumentFactory.cpp.
References AppendComment(), before_html, domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, IgnoreHtmlWhiteSpace(), OnInitialInsertion_DOCTYPE(), OnToken(), ParseError(), SwitchMode(), domparser::generic::Token::TAG, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnBeforeHtmlInsertion (const domparser::generic::Token & token) [protected]
Definition at line 349 of file DocumentFactory.cpp.
References AppendComment(), before_head, domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, domparser::head_body_html_br, IgnoreHtmlWhiteSpace(), InsertHtmlElement(), tools::StringTools::IsOneOf(), domparser::generic::TagToken::name, OnToken(), ParseError(), domparser::generic::TagToken::START_TAG, SwitchMode(), domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnBeforeHeadInsertion (const domparser::generic::Token & token) [protected]
Definition at line 398 of file DocumentFactory.cpp.
References AppendComment(), domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, domparser::head_body_html_br, headElement, IgnoreHtmlWhiteSpace(), in_body, in_head, InsertHtmlElement(), tools::StringTools::IsOneOf(), domparser::generic::TagToken::name, OnInsertion(), OnToken(), ParseError(), domparser::generic::TagToken::START_TAG, SwitchMode(), domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInHeadInsertion (const domparser::generic::Token & token) [protected]
Definition at line 447 of file DocumentFactory.cpp.
References after_head, domparser::Node::appendChild(), AppendComment(), AppendGenericRawText(), AppendGenericRCDATA(), domparser::HTMLScriptElement::async, domparser::base_basefont_bgsound_link, domparser::body_html_br, domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, curDoc, domparser::HTMLScriptElement::defer, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, domparser::NodeFactory::FromToken(), IgnoreHtmlWhiteSpace(), in_body, in_head_noscript, InsertCharacter(), InsertHtmlElement(), insertionMode, tools::StringTools::IsOneOf(), domparser::generic::TagToken::name, domparser::noframes_style, OnInsertion(), OnToken(), openElementStack, orgInsertionMode, ParseError(), tools::Stack< T >::Pop(), tools::Stack< T >::Push(), domparser::html5::Script_data_state, scriptingFlag, domparser::generic::TagToken::selfClosingFlag, domparser::generic::TagToken::START_TAG, SwitchMode(), domparser::html5::Tokeniser::SwitchState(), domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, text, tokeniser, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInHeadNoscriptInsertion (const domparser::generic::Token & token) [protected]
Definition at line 554 of file DocumentFactory.cpp.
References domparser::basefont_bgsound_link_meta_noframes_style, domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, domparser::head_noscript, IgnoreHtmlWhiteSpace(), in_body, in_head, tools::StringTools::IsOneOf(), domparser::generic::TagToken::name, OnInsertion(), OnToken(), openElementStack, ParseError(), tools::Stack< T >::Pop(), domparser::generic::TagToken::START_TAG, SwitchMode(), domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnAfterHeadInsertion (const domparser::generic::Token & token) [protected]
Definition at line 597 of file DocumentFactory.cpp.
References AppendComment(), domparser::base_basefont_bgsound_link_meta_noframes_script_style_title, domparser::body_html_br, domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, framesetOk, headElement, IgnoreHtmlWhiteSpace(), in_body, in_frameset, in_head, InsertCharacter(), InsertHtmlElement(), tools::StringTools::IsOneOf(), domparser::generic::TagToken::name, OnInsertion(), OnToken(), openElementStack, ParseError(), tools::Stack< T >::Pop(), tools::Stack< T >::Push(), domparser::generic::TagToken::START_TAG, SwitchMode(), domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInBodyInsertion (const domparser::generic::Token & token) [protected]
Definition at line 665 of file DocumentFactory.cpp.
References AppendComment(), domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, framesetOk, IgnoreHtmlWhiteSpace(), InsertCharacter(), domparser::generic::TagToken::INVALID_TYPE, OnInBodyEndTagInsertion(), OnInBodyStartTagInsertion(), ParseError(), ReconstructActiveFormatElements(), domparser::generic::TagToken::START_TAG, domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnTextInsertion (const domparser::generic::Token & token) [protected]
Definition at line 1061 of file DocumentFactory.cpp.
References domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, domparser::generic::Token::DOCTYPE, domparser::generic::TagToken::END_TAG, InsertCharacter(), domparser::generic::TagToken::name, openElementStack, orgInsertionMode, tools::Stack< T >::Pop(), SwitchMode(), domparser::generic::Token::TAG, domparser::generic::TagToken::tagType, and domparser::generic::Token::type.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInTableInsertion (const domparser::generic::Token & token) [protected]
Definition at line 703 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInTableTextInsertion (const domparser::generic::Token & token) [protected]
Definition at line 727 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInCaptionInsertion (const domparser::generic::Token & token) [protected]
Definition at line 751 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInColumnGroupInsertion (const domparser::generic::Token & token) [protected]
Definition at line 775 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInTableBodyInsertion (const domparser::generic::Token & token) [protected]
Definition at line 799 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInRowInsertion (const domparser::generic::Token & token) [protected]
Definition at line 823 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInCellInsertion (const domparser::generic::Token & token) [protected]
Definition at line 847 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInSelectInsertion (const domparser::generic::Token & token) [protected]
Definition at line 871 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInSelectInTableInsertion (const domparser::generic::Token & token) [protected]
Definition at line 895 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnAfterBodyInsertion (const domparser::generic::Token & token) [protected]
Definition at line 919 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInFramesetInsertion (const domparser::generic::Token & token) [protected]
Definition at line 943 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnAfterFramesetInsertion (const domparser::generic::Token & token) [protected]
Definition at line 967 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnAfterAfterBodyInsertion (const domparser::generic::Token & token) [protected]
Definition at line 991 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnAfterAfterFramesetInsertion (const domparser::generic::Token & token) [protected]
Definition at line 1015 of file DocumentFactory.cpp.
Referenced by OnInsertion().
bool domparser::DocumentFactory::OnInBodyStartTagInsertion (const domparser::generic::TagToken & tagToken) [protected]
Definition at line 1100 of file DocumentFactory.cpp.
References domparser::address_article_aside_blockquote_center_details_dialog_dir_div_dl_fieldset_figcaption_figure_footer_header_hgroup_main_menu_nav_ol_p_section_summary_ul, domparser::applet_marquee_object, domparser::area_br_embed_img_keygen_wbr, domparser::generic::TagToken::attributes, domparser::b_big_code_em_font_i_s_small_strike_strong_tt_u, domparser::base_basefont_bgsound_link_menuitem_meta_noframes_script_style_title, domparser::HTMLElement::bodyTag, domparser::caption_col_colgroup_frame_head_tbody_td_tfoot_th_thead_tr, tools::Stack< T >::ConstPeek(), domparser::dd_dt, framesetOk, domparser::HTMLElement::GetHtmlTagType(), domparser::Node::GetParentNode(), domparser::Element::hasAttribute(), domparser::hTags, domparser::HTMLElement::htmlTag, in_frameset, in_head, InsertHtmlElement(), tools::StringTools::IsOneOf(), domparser::generic::TagToken::name, OnInsertion(), OnToken(), openElementStack, domparser::optgroup_option, domparser::param_source_track, ParseError(), tools::Stack< T >::Peek(), tools::Stack< T >::Pop(), domparser::pre_listing, domparser::Node::removeChild(), domparser::rp_rt, scriptingFlag, domparser::Element::setAttribute(), tools::Stack< T >::Size(), and SwitchMode().
Referenced by OnInBodyInsertion().
bool domparser::DocumentFactory::OnInBodyEndTagInsertion (const domparser::generic::TagToken & tagToken) [protected]
Definition at line 1278 of file DocumentFactory.cpp.
References domparser::a_b_big_code_em_font_i_nobr_s_small_strike_strong_tt_u, domparser::address_article_aside_blockquote_button_center_details_dialog_dir_div_dl_fieldset_figcaption_figure_footer_header_hgroup_listing_main_menu_nav_ol_pre_section_summary_ul, after_body, domparser::applet_marquee_object, domparser::HTMLElement::aTag, domparser::HTMLElement::bodyTag, tools::Stack< T >::ConstPeek(), domparser::dd_dt, domparser::HTMLElement::ddTag, domparser::generic::TagToken::END_TAG, domparser::HTMLElement::GetHtmlTagType(), domparser::hTags, domparser::HTMLElement::htmlTag, tools::StringTools::IsOneOf(), domparser::HTMLElement::liTag, domparser::generic::TagToken::name, OnToken(), openElementStack, domparser::HTMLElement::optgroupTag, domparser::HTMLElement::optionTag, ParseError(), domparser::HTMLElement::pTag, domparser::HTMLElement::rpTag, domparser::HTMLElement::rtTag, tools::Stack< T >::Size(), domparser::generic::TagToken::START_TAG, SwitchMode(), domparser::generic::TagToken::tagType, domparser::HTMLElement::tbodyTag, domparser::HTMLElement::tdTag, domparser::HTMLElement::tfootTag, domparser::HTMLElement::theadTag, domparser::HTMLElement::thTag, and domparser::HTMLElement::trTag.
Referenced by OnInBodyInsertion().
std::string domparser::DocumentFactory::InsertionModeToString (const InsertionMode & insertMode) [static, protected]
Definition at line 132 of file DocumentFactory.cpp.
References after_after_body, after_after_frameset, after_body, after_frameset, after_head, before_head, before_html, in_body, in_caption, in_cell, in_column_group, in_frameset, in_head, in_head_noscript, in_row, in_select, in_select_in_table, in_table, in_table_body, in_table_text, initial, and text.
Referenced by toolbot::UnitTestHtmlDocumentFactory::SwitchMode().
bool domparser::DocumentFactory::OnInitialInsertion_DOCTYPE (const domparser::generic::DocTypeToken & token) [private]
Definition at line 310 of file DocumentFactory.cpp.
References AppendDocType(), before_html, domparser::generic::DocTypeToken::name, ParseError(), domparser::generic::DocTypeToken::pPublicIdentifier, domparser::generic::DocTypeToken::pSystemIdentifier, domparser::generic::DocTypeToken::public_identifier, domparser::public_identifier_html_40, domparser::public_identifier_html_401, domparser::public_identifier_xhtml_10, domparser::public_identifier_xhtml_11, SwitchMode(), domparser::generic::DocTypeToken::system_identifier, domparser::system_identifier_html_strict_40, domparser::system_identifier_html_strict_401, domparser::system_identifier_xhtml_strict_10, and domparser::system_identifier_xhtml_strict_11.
Referenced by OnInitialInsertion().
bool domparser::DocumentFactory::IgnoreHtmlWhiteSpace (const domparser::generic::CharacterToken & token) [private]
Definition at line 114 of file DocumentFactory.cpp.
References domparser::generic::CharacterToken::text.
Referenced by OnAfterHeadInsertion(), OnBeforeHeadInsertion(), OnBeforeHtmlInsertion(), OnInBodyInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), and OnInitialInsertion().
Friends And Related Function Documentation
friend class html5::Tokeniser [friend]
Definition at line 53 of file DocumentFactory.h.
Member Data Documentation
const network::HttpUrl& domparser::DocumentFactory::url [protected]
Reimplemented in toolbot::UnitTestHtmlDocumentFactory.
Definition at line 165 of file DocumentFactory.h.
Document* domparser::DocumentFactory::curDoc [protected]
Definition at line 166 of file DocumentFactory.h.
Referenced by AppendComment(), AppendDocType(), FromHtmlData(), InsertHtmlElement(), OnInHeadInsertion(), and toolbot::UnitTestHtmlDocumentFactory::Run().
html5::Tokeniser* domparser::DocumentFactory::tokeniser [protected]
Definition at line 167 of file DocumentFactory.h.
Referenced by AppendGenericRCDATAOrRawText(), FromHtmlData(), OnInHeadInsertion(), toolbot::UnitTestHtmlDocumentFactory::OnToken(), ParseError(), toolbot::UnitTestHtmlDocumentFactory::Run(), and toolbot::UnitTestHtmlDocumentFactory::SwitchMode().
InsertionMode domparser::DocumentFactory::insertionMode [protected]
Definition at line 169 of file DocumentFactory.h.
Referenced by AppendGenericRCDATAOrRawText(), OnInHeadInsertion(), toolbot::UnitTestHtmlDocumentFactory::OnToken(), OnToken(), toolbot::UnitTestHtmlDocumentFactory::SwitchMode(), and SwitchMode().
InsertionMode domparser::DocumentFactory::orgInsertionMode [protected]
Definition at line 170 of file DocumentFactory.h.
Referenced by AppendGenericRCDATAOrRawText(), OnInHeadInsertion(), and OnTextInsertion().
tools::Stack<Node*> domparser::DocumentFactory::openElementStack [protected]
Definition at line 172 of file DocumentFactory.h.
Referenced by InsertHtmlElement(), OnAfterHeadInsertion(), OnInBodyEndTagInsertion(), OnInBodyStartTagInsertion(), OnInHeadInsertion(), OnInHeadNoscriptInsertion(), and OnTextInsertion().
HTMLHeadElement* domparser::DocumentFactory::headElement [protected]
Definition at line 174 of file DocumentFactory.h.
Referenced by OnAfterHeadInsertion(), and OnBeforeHeadInsertion().
HTMLFormElement* domparser::DocumentFactory::formElement [protected]
Definition at line 175 of file DocumentFactory.h.
bool domparser::DocumentFactory::scriptingFlag [private]
Definition at line 178 of file DocumentFactory.h.
Referenced by OnInBodyStartTagInsertion(), and OnInHeadInsertion().
bool domparser::DocumentFactory::framesetOk [private]
Definition at line 179 of file DocumentFactory.h.
Referenced by OnAfterHeadInsertion(), OnInBodyInsertion(), and OnInBodyStartTagInsertion().
The documentation for this class was generated from the following files:
DOMParser/src/DocumentFactory.h
DOMParser/src/DocumentFactory.cpp