DeepNet: network::HtmlData Class Reference
network::HtmlData Class Reference
container for HTML data which uses tools::MemoryContainer
#include <HtmlData.h>
Public Member Functions
HtmlData ()
virtual ~HtmlData ()
bool ConvertToHostCharset ()
converts complete content to charset/encoding of the current host
const char * GetBuffer () const
gets current buffer
size_t GetBufferSize () const
gets current buffer size
void SetContentType (const std::string &contentType)
sets the content type for this HTML data
const std::string & GetContentType () const
gets content type of this HTML data
operator const char * () const
char * Allocate (const size_t newElementCount, const bool zeroNewMemory)
allocates new memory.
void Release ()
releases allocated memory.
void Swap (const MemoryContainer< char > &own)
take ownership of another container.
void Swap (char *own, const size_t elementCount)
take ownership of raw memory.
char * Append (const MemoryContainer< char > &append)
appends complete container.
char * Append (const size_t appendAt, const MemoryContainer< char > &append)
appends container at a given position.
char * Append (const char *append, const size_t &appendCount)
appends certain number of elements from an array.
char * Append (const size_t appendAt, const char *append, const size_t appendCount)
appends certain number of elements at a certain position.
char * Append (const size_t appendAt, const char *append, const size_t appendStart, const size_t appendCount)
appends certain number of elements from a certain start position at a certain position.
bool EnsureSize (const size_t ensureElementCount, const bool zeroNewMemory)
ensure buffer size
void ZeroAllElements ()
zeros all elements.
char * GetElements ()
gets first element.
const char * GetConstElements () const
gets const first element.
char * GetElementAt (const size_t &elementNr)
gets elements at position.
const char * GetConstElementAt (const size_t &elementNr) const
gets const elements at position.
const size_t & GetCount () const
gets number of entries.
Private Member Functions
bool DetectCharset (const std::string &charsetHint, int &confidence, std::string &detectedEncoding, bool &hintCorrect)
Private Attributes
std::string contentType
encode all characters that have a HTML Character Reference
Static Private Attributes
static const char emptyBuffer = 0
Detailed Description
container for HTML data which uses tools::MemoryContainer
Definition at line 18 of file HtmlData.h.
Constructor & Destructor Documentation
network::HtmlData::HtmlData () [inline]
Definition at line 21 of file HtmlData.h.
virtual network::HtmlData::~HtmlData () [inline, virtual]
Definition at line 22 of file HtmlData.h.
Member Function Documentation
bool network::HtmlData::ConvertToHostCharset ()
converts complete content to charset/encoding of the current host
Returns:
true if successful, false if unsuccessful
Definition at line 29 of file HtmlData.cpp.
References tools::MemoryContainer< char >::Append(), contentType, tools::CharsetEncoder::Convert(), DetectCharset(), GetBuffer(), GetBufferSize(), tools::MemoryContainer< char >::GetCount(), log::Logging::IsLogLevelTrace(), tools::CharsetEncoder::IsValidEncodingName(), log::Logging::LogTrace(), tools::MimeType::ParseMimeString(), and tools::MemoryContainer< char >::Release().
Referenced by network::HttpClientCURL::Get().
const char * network::HtmlData::GetBuffer () const
gets current buffer
Returns:
current buffer
Definition at line 20 of file HtmlData.cpp.
References emptyBuffer, tools::MemoryContainer< char >::GetConstElements(), and tools::MemoryContainer< char >::GetCount().
Referenced by ConvertToHostCharset(), DetectCharset(), caching::CacheRobotsTxt::DownloadRobotsTxt(), domparser::DocumentFactory::FromHtmlData(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), libxmlparser::HtmlSAX2Parser::Parse(), and inspectorserver::InspectorServerResponse::Process().
size_t network::HtmlData::GetBufferSize () const
gets current buffer size
Returns:
current buffer
Definition at line 24 of file HtmlData.cpp.
References tools::MemoryContainer< char >::GetCount().
Referenced by ConvertToHostCharset(), DetectCharset(), domparser::DocumentFactory::FromHtmlData(), and libxmlparser::HtmlSAX2Parser::Parse().
void network::HtmlData::SetContentType (const std::string & contentType)
sets the content type for this HTML data
Parameters:
contentType Content-Type, may include charset, i.e. text/html;charset=UTF8
Definition at line 148 of file HtmlData.cpp.
References contentType.
Referenced by network::HttpClientCURL::Get(), and toolbot::UnitTestSAX2HtmlParser::Test().
const std::string & network::HtmlData::GetContentType () const
gets content type of this HTML data
Returns:
Content-Type, may include charset, i.e. text/html;charset=UTF8
Definition at line 144 of file HtmlData.cpp.
References contentType.
Referenced by domparser::DocumentFactory::FromHtmlData(), and crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
bool network::HtmlData::DetectCharset (const std::string & charsetHint, int & confidence, std::string & detectedEncoding, bool & hintCorrect) [private]
Definition at line 130 of file HtmlData.cpp.
References tools::CharsetEncoder::Detect(), tools::CharsetEncoder::DetectMatch::encodingConfidence, tools::CharsetEncoder::DetectMatch::encodingHintCorrect, tools::CharsetEncoder::DetectMatch::encodingName, GetBuffer(), GetBufferSize(), log::Logging::IsLogLevelTrace(), log::Logging::Log(), and log::Logging::LOGLEVEL_TRACE.
Referenced by ConvertToHostCharset().
tools::MemoryContainer< char >::operator const char * () const [inline, inherited]
Definition at line 49 of file MemoryContainer.h.
char * tools::MemoryContainer< char >::Allocate (const size_t newElementCount, const bool zeroNewMemory) [inline, inherited]
allocates new memory.
Parameters:
newElementCount number of new elements.
zeroNewMemory true to zero-initialized memory.
Returns:
allocated typed memory.
Definition at line 60 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element, and tools::MemoryContainer< T >::elementCount.
void tools::MemoryContainer< char >::Release () [inline, inherited]
releases allocated memory.
Definition at line 83 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element, tools::MemoryContainer< T >::elementCount, and tools::MemoryContainer< T >::releaseOnDestruct.
Referenced by ConvertToHostCharset().
void tools::MemoryContainer< char >::Swap (const MemoryContainer< char > & own) [inline, inherited]
take ownership of another container.
Parameters:
own container to take ownership of.
Definition at line 96 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element, tools::MemoryContainer< T >::elementCount, tools::MemoryContainer< T >::Release(), and tools::MemoryContainer< T >::releaseOnDestruct.
void tools::MemoryContainer< char >::Swap (char * own, const size_t elementCount) [inline, inherited]
take ownership of raw memory.
Parameters:
own memory to take ownership of.
elementCount size of memory.
Definition at line 110 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element, tools::MemoryContainer< T >::elementCount, and tools::MemoryContainer< T >::Release().
char * tools::MemoryContainer< char >::Append (const MemoryContainer< char > & append) [inline, inherited]
appends complete container.
Parameters:
append container to append.
Returns:
first element.
Definition at line 123 of file MemoryContainer.h.
References tools::MemoryContainer< T >::Append(), tools::MemoryContainer< T >::elementCount, and tools::MemoryContainer< T >::GetCount().
Referenced by ConvertToHostCharset().
char * tools::MemoryContainer< char >::Append (const size_t appendAt, const MemoryContainer< char > & append) [inline, inherited]
appends container at a given position.
Parameters:
appendAt position to insert at.
append container to add.
Returns:
first element.
Definition at line 133 of file MemoryContainer.h.
References tools::MemoryContainer< T >::Append(), and tools::MemoryContainer< T >::GetCount().
char * tools::MemoryContainer< char >::Append (const char * append, const size_t & appendCount) [inline, inherited]
appends certain number of elements from an array.
Parameters:
append array to append.
appendCount number of elements to append.
Returns:
first element.
Definition at line 143 of file MemoryContainer.h.
References tools::MemoryContainer< T >::Append(), and tools::MemoryContainer< T >::elementCount.
char * tools::MemoryContainer< char >::Append (const size_t appendAt, const char * append, const size_t appendCount) [inline, inherited]
appends certain number of elements at a certain position.
Parameters:
appendAt position to insert at.
append elements to append.
appendCount number of elements to append.
Returns:
first element.
Definition at line 154 of file MemoryContainer.h.
References tools::MemoryContainer< T >::Append().
char * tools::MemoryContainer< char >::Append (const size_t appendAt, const char * append, const size_t appendStart, const size_t appendCount) [inline, inherited]
appends certain number of elements from a certain start position at a certain position.
Parameters:
appendAt position to insert at.
append elements to append.
appendStart start position in append.
appendCount number of elements to append.
Returns:
first element.
Definition at line 166 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element, and tools::MemoryContainer< T >::EnsureSize().
bool tools::MemoryContainer< char >::EnsureSize (const size_t ensureElementCount, const bool zeroNewMemory) [inline, inherited]
ensure buffer size
Parameters:
ensureElementCount mimimum size of buffer.
zeroNewMemory true to initialize newly allocated memory.
Returns:
first element.
Definition at line 181 of file MemoryContainer.h.
References tools::MemoryContainer< T >::Allocate(), and tools::MemoryContainer< T >::elementCount.
void tools::MemoryContainer< char >::ZeroAllElements () [inline, inherited]
zeros all elements.
Definition at line 191 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element, and tools::MemoryContainer< T >::elementCount.
char * tools::MemoryContainer< char >::GetElements () [inline, inherited]
gets first element.
Returns:
first element.
Definition at line 200 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element.
const char * tools::MemoryContainer< char >::GetConstElements () const [inline, inherited]
gets const first element.
Returns:
first element.
Definition at line 206 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element.
Referenced by GetBuffer().
char * tools::MemoryContainer< char >::GetElementAt (const size_t & elementNr) [inline, inherited]
gets elements at position.
Parameters:
elementNr position.
Returns:
element.
Definition at line 213 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element.
const char * tools::MemoryContainer< char >::GetConstElementAt (const size_t & elementNr) const [inline, inherited]
gets const elements at position.
Parameters:
elementNr position.
Returns:
element.
Definition at line 220 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element.
const size_t& tools::MemoryContainer< char >::GetCount () const [inline, inherited]
gets number of entries.
Returns:
number of entries.
Definition at line 226 of file MemoryContainer.h.
References tools::MemoryContainer< T >::elementCount.
Referenced by ConvertToHostCharset(), GetBuffer(), and GetBufferSize().
Member Data Documentation
std::string network::HtmlData::contentType [private]
encode all characters that have a HTML Character Reference
Returns:
true if successful, false if unsuccessful
Definition at line 64 of file HtmlData.h.
Referenced by ConvertToHostCharset(), GetContentType(), and SetContentType().
const char network::HtmlData::emptyBuffer = 0 [static, private]
Definition at line 65 of file HtmlData.h.
Referenced by GetBuffer().
The documentation for this class was generated from the following files:
Networking/src/HtmlData.h
Networking/src/HtmlData.cpp