DeepNet: domparser::Document Class Reference
domparser::Document Class Reference
implements a DOM compatible document
#include <Document.h>
Public Types
enum NodeType {
INVALID_NODE_TYPE, ELEMENT_NODE = 1, TEXT_NODE = 3, PROCESSING_INSTRUCTION_NODE = 7,
COMMENT_NODE = 8, DOCUMENT_NODE = 9, DOCUMENT_TYPE_NODE = 10, DOCUMENT_FRAGMENT_NODE = 11
}
specific type node
enum DocumentPosition {
DOCUMENT_POSITION_EQUAL = 0x00, DOCUMENT_POSITION_DISCONNECTED = 0x01, DOCUMENT_POSITION_PRECEDING = 0x02, DOCUMENT_POSITION_FOLLOWING = 0x04,
DOCUMENT_POSITION_CONTAINS = 0x08, DOCUMENT_POSITION_CONTAINED_BY = 0x10, DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC = 0x20
}
describes relationship of two nodes
Public Member Functions
virtual ~Document ()
HTMLCollection getElementsByTagName (const DOMString &localName)
HTMLCollection getElementsByTagNameNS (const DOMString &nameSpace, const DOMString &localName)
returns a collection of all tags with a certain name and namespace
HTMLCollection getElementsByClassName (const DOMString &className)
returns a collection of all tags with a certain class
Element * getElementById (const DOMString &elementId)
gets an element by it's id
Element * createElement (const DOMString &localName)
Element * createElementNS (const DOMString *nameSpace, const DOMString &qualifiedName)
creates an elements by a name and it's namespace
DocumentFragment * createDocumentFragment ()
creates an empty document fragment
Text * createTextNode (const DOMString &data)
creates a text node containing data
Comment * createComment (const DOMString &data)
creates comment containing data
ProcessingInstruction * createProcessingInstruction (const DOMString &target, const DOMString &data)
creates an processing instruction
Node * importNode (Node *node, bool deep=true)
imports/copies node from another document optionally containing all child nodes
Node * adoptNode (Node *node)
adopts/swaps a node from a foreign document and removes it there
Event * createEvent (const DOMString &interface)
creates a named event
Range * createRange ()
creates range, all ranges are updated instantly when the document changes
NodeIterator createNodeIterator (Node *root, NodeFilter::Type whatToShow=NodeFilter::SHOW_ALL, NodeFilter *filter=0)
creates node iterator
TreeWalker createTreeWalker (Node *root, NodeFilter::Type whatToShow=NodeFilter::SHOW_ALL, NodeFilter *filter=0)
creates tree walker
bool hasChildNodes () const
checks if this node has child nodes
Node * insertBefore (Node *node, Node *child)
insert a node before another
Node * appendChild (Node *node)
appends node as a child to a certain node
Node * replaceChild (Node *node, Node *child)
replace a child node with another
Node * removeChild (Node *child)
removes a child node
void normalize ()
normalize DOM tree
Node * cloneNode (bool deep=true)
clones this node, optionally including all children
bool isEqualNode (Node *node)
compare two nodes for equality
DocumentPosition compareDocumentPosition (Node *other)
compares position of two DOM nodes
bool contains (Node *other)
checks if a node is a child node of this node
DOMStringPtr lookupPrefix (const DOMString &nameSpace)
DOMStringPtr lookupNamespaceURI (const DOMString &prefix)
bool isDefaultNamespace (const DOMString &nameSpace)
Node::NodeType GetNodeType () const
gets node type
DOMString GetNodeName () const
gets node name
NodeList & GetChildNodes ()
gets a list of child nodes
Node * GetParentNode ()
gets the parent node
Node * GetFirstChild ()
gets first child of this node
Node * GetLastChild ()
gets last child of this node
Node * GetPreviousSibling ()
gets previous sibling
Node * GetNextSibling ()
gets next sibling
Document * GetOwnerDocument ()
gets owning/parent document for this node
const DOMString * GetNodeValue () const
gets node (text)-value
DOMStringPtr GetTextContent () const
gets text content of this node
void SetNodeValue (const DOMString &value)
set node value
void SetTextContent (const DOMString &value)
sets text content of this node
void RegisterObserver (const MutationObserver &observer)
registers observer with this node
void addEventListener (const DOMString &type, EventListener callback, bool capture=false)
void removeEventListener (const DOMString &type, EventListener callback, bool capture=false)
bool dispatchEvent (Event &event)
Static Public Member Functions
static void QueueMutationRecord (const MutationRecord &record)
queues a mutation record for all nodes
Protected Member Functions
Node * doPreInsert (Node *node, Node *child)
Node * doInsert (Node *node, Node *child, bool supressObservers=false)
Node * doPreRemoveChild (Node *child)
Node * doRemoveChild (Node *child, bool supressObservers=false)
bool doGetChildIdx (Node *node, size_t &pos)
Protected Attributes
Document * ownerDocument
Private Member Functions
Document (const network::HttpUrl &url, const char *characterSet="utf-8", const char *contentType="application/xml")
Node * doAdoptNode (Node *node)
Private Attributes
network::HttpUrl dbUrl
DOMImplementation implementation
DOMString documentURI
DOMString URL
DOMString compatMode
DOMString characterSet
DOMString contentType
DocumentType * doctype
Element * documentElement
Friends
class DocumentFactory
class NodeFactory
class toolbot::UnitTestHtmlDocumentFactory
Detailed Description
implements a DOM compatible document
See also:
domparser::DocumentFactory and domparser::NodeFactory
Definition at line 46 of file Document.h.
Member Enumeration Documentation
enum domparser::Node::NodeType [inherited]
specific type node
Enumerator:
INVALID_NODE_TYPE
ELEMENT_NODE
TEXT_NODE
PROCESSING_INSTRUCTION_NODE
COMMENT_NODE
DOCUMENT_NODE
DOCUMENT_TYPE_NODE
DOCUMENT_FRAGMENT_NODE
Definition at line 36 of file Node.h.
enum domparser::Node::DocumentPosition [inherited]
describes relationship of two nodes
Enumerator:
DOCUMENT_POSITION_EQUAL
DOCUMENT_POSITION_DISCONNECTED
DOCUMENT_POSITION_PRECEDING
DOCUMENT_POSITION_FOLLOWING
DOCUMENT_POSITION_CONTAINS
DOCUMENT_POSITION_CONTAINED_BY
DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC
Definition at line 56 of file Node.h.
Constructor & Destructor Documentation
domparser::Document::Document (const network::HttpUrl & url, const char * characterSet = "utf-8", const char * contentType = "application/xml") [private]
Definition at line 26 of file Document.cpp.
domparser::Document::~Document () [virtual]
Definition at line 34 of file Document.cpp.
Member Function Documentation
HTMLCollection domparser::Document::getElementsByTagName (const DOMString & localName)
See also:
domparser::Document::getElementsByTagNameNS
Definition at line 37 of file Document.cpp.
HTMLCollection domparser::Document::getElementsByTagNameNS (const DOMString & nameSpace, const DOMString & localName)
returns a collection of all tags with a certain name and namespace
Parameters:
nameSpace namespace of the html tag to look for
localName name of html tag to look for
Returns:
collection of all elements
Definition at line 41 of file Document.cpp.
HTMLCollection domparser::Document::getElementsByClassName (const DOMString & className)
returns a collection of all tags with a certain class
Parameters:
className name of the class to look for
Returns:
collection of all elements of a certain class
Definition at line 45 of file Document.cpp.
Element * domparser::Document::getElementById (const DOMString & elementId)
gets an element by it's id
Parameters:
elementId id of the element
Returns:
element or NULL if not found
Definition at line 49 of file Document.cpp.
Element * domparser::Document::createElement (const DOMString & localName)
See also:
domparser::Document::createElementNS
Definition at line 53 of file Document.cpp.
References domparser::ElementFactory::FromName().
Referenced by domparser::NodeFactory::CreateElement().
Element * domparser::Document::createElementNS (const DOMString * nameSpace, const DOMString & qualifiedName)
creates an elements by a name and it's namespace
Returns:
created element
Definition at line 57 of file Document.cpp.
References domparser::ElementFactory::FromName().
DocumentFragment * domparser::Document::createDocumentFragment ()
creates an empty document fragment
Returns:
created document fragment
Definition at line 61 of file Document.cpp.
Text * domparser::Document::createTextNode (const DOMString & data)
creates a text node containing data
Parameters:
data initial data
Returns:
created text node
Definition at line 65 of file Document.cpp.
References domparser::CharacterData::appendData().
Comment * domparser::Document::createComment (const DOMString & data)
creates comment containing data
Parameters:
data initial data
Returns:
created comment
Definition at line 73 of file Document.cpp.
References domparser::CharacterData::appendData().
Referenced by domparser::NodeFactory::CreateComment().
ProcessingInstruction * domparser::Document::createProcessingInstruction (const DOMString & target, const DOMString & data)
creates an processing instruction
See also:
DOM5 specification
Returns:
created processing instruction
Definition at line 81 of file Document.cpp.
References domparser::CharacterData::appendData().
Node * domparser::Document::importNode (Node * node, bool deep = true)
imports/copies node from another document optionally containing all child nodes
Parameters:
node node to import/copy
deep copy child nodes too
Definition at line 89 of file Document.cpp.
Node * domparser::Document::adoptNode (Node * node)
adopts/swaps a node from a foreign document and removes it there
Parameters:
node node to adopt
Returns:
adopted node
Definition at line 93 of file Document.cpp.
References doAdoptNode(), domparser::Node::DOCUMENT_NODE, and domparser::Node::GetNodeType().
Referenced by domparser::Node::doPreInsert().
Event * domparser::Document::createEvent (const DOMString & interface)
creates a named event
Parameters:
interface name of newly created event
Returns:
created event
Definition at line 103 of file Document.cpp.
Range * domparser::Document::createRange ()
creates range, all ranges are updated instantly when the document changes
Returns:
created range
Definition at line 107 of file Document.cpp.
NodeIterator domparser::Document::createNodeIterator (Node * root, NodeFilter::Type whatToShow = NodeFilter::SHOW_ALL, NodeFilter * filter = 0)
creates node iterator
Parameters:
root where to start iterating
whatToShow type of nodes to consider
filter predefined node filter
Returns:
created iterator
Definition at line 113 of file Document.cpp.
Referenced by domparser::Node::compareDocumentPosition(), and domparser::TreeWalker::NextNodeSubstep().
TreeWalker domparser::Document::createTreeWalker (Node * root, NodeFilter::Type whatToShow = NodeFilter::SHOW_ALL, NodeFilter * filter = 0)
creates tree walker
Parameters:
root where to start walking
whatToShow type of nodes to consider
filter predefined node filter
Returns:
created treewalker
Definition at line 117 of file Document.cpp.
Node * domparser::Document::doAdoptNode (Node * node) [private]
Definition at line 121 of file Document.cpp.
References domparser::Node::GetParentNode(), domparser::Node::ownerDocument, and domparser::Node::removeChild().
Referenced by adoptNode().
bool domparser::Node::hasChildNodes () const [inline, inherited]
checks if this node has child nodes
Returns:
true if it has, false if not
Definition at line 83 of file Node.h.
References domparser::Node::childNodes, and domparser::ListImpl< T >::GetLength().
Node * domparser::Node::insertBefore (Node * node, Node * child) [inherited]
insert a node before another
Parameters:
node node to insert before
child new node to insert
Returns:
inserted node
Definition at line 320 of file Node.cpp.
References domparser::Node::doPreInsert().
Node * domparser::Node::appendChild (Node * node) [inherited]
appends node as a child to a certain node
Parameters:
node node to append
Returns:
inserted node
Definition at line 324 of file Node.cpp.
Referenced by domparser::DocumentFactory::AppendComment(), domparser::DocumentFactory::AppendDocType(), domparser::DocumentFactory::InsertHtmlElement(), and domparser::DocumentFactory::OnInHeadInsertion().
Node * domparser::Node::replaceChild (Node * node, Node * child) [inherited]
replace a child node with another
Parameters:
node node to insert
child node to replace
Returns:
replaced node
Definition at line 328 of file Node.cpp.
Node * domparser::Node::removeChild (Node * child) [inherited]
removes a child node
Parameters:
child node to remove
Returns:
remove node
Definition at line 332 of file Node.cpp.
References domparser::Node::doPreRemoveChild().
Referenced by doAdoptNode(), and domparser::DocumentFactory::OnInBodyStartTagInsertion().
void domparser::Node::normalize () [inherited]
normalize DOM tree
Definition at line 336 of file Node.cpp.
Node * domparser::Node::cloneNode (bool deep = true) [inherited]
clones this node, optionally including all children
Parameters:
deep if set to true, all children are cloned also
Returns:
cloned node
Definition at line 339 of file Node.cpp.
bool domparser::Node::isEqualNode (Node * node) [inherited]
compare two nodes for equality
Parameters:
node node to compare to
Returns:
true if node is equal
Definition at line 343 of file Node.cpp.
Node::DocumentPosition domparser::Node::compareDocumentPosition (Node * other) [inherited]
compares position of two DOM nodes
Parameters:
other node to compare to
Returns:
relationship of two nodes
Definition at line 282 of file Node.cpp.
References createNodeIterator(), domparser::Node::DOCUMENT_POSITION_CONTAINS, domparser::Node::DOCUMENT_POSITION_DISCONNECTED, domparser::Node::DOCUMENT_POSITION_EQUAL, domparser::Node::DOCUMENT_POSITION_FOLLOWING, domparser::Node::DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC, domparser::Node::DOCUMENT_POSITION_PRECEDING, domparser::Node::GetOwnerDocument(), domparser::Node::GetParentNode(), domparser::NodeIterator::nextNode(), and domparser::NodeFilter::SHOW_ALL.
Referenced by domparser::FollowFilter::acceptNode(), domparser::FollowNodeNotFollowRootFilter::acceptNode(), and domparser::Range::ComparePoints().
bool domparser::Node::contains (Node * other) [inherited]
checks if a node is a child node of this node
Parameters:
other node to check for
Returns:
true if it is child, false if not
Definition at line 347 of file Node.cpp.
Referenced by domparser::Range::ComparePoints(), domparser::Node::doPreInsert(), domparser::Node::doRemoveChild(), and domparser::Range::GetCommonAncestorContainer().
DOMStringPtr domparser::Node::lookupPrefix (const DOMString & nameSpace) [inherited]
Definition at line 351 of file Node.cpp.
References DOMStringPtr.
DOMStringPtr domparser::Node::lookupNamespaceURI (const DOMString & prefix) [inherited]
Definition at line 355 of file Node.cpp.
References DOMStringPtr.
bool domparser::Node::isDefaultNamespace (const DOMString & nameSpace) [inherited]
Definition at line 359 of file Node.cpp.
Node::NodeType domparser::Node::GetNodeType () const [inline, inherited]
gets node type
Returns:
node type
Definition at line 158 of file Node.h.
References domparser::Node::nodeType.
Referenced by adoptNode(), domparser::Range::comparePoint(), domparser::Node::doInsert(), domparser::Node::doPreInsert(), domparser::Traverser::FilterNode(), domparser::Node::GetNodeName(), domparser::Node::GetNodeValue(), domparser::Node::GetOwnerDocument(), domparser::Range::selectNodeContents(), and domparser::Range::SetBoundaryPoint().
DOMString domparser::Node::GetNodeName () const [inherited]
gets node name
Returns:
node name
Definition at line 39 of file Node.cpp.
References domparser::Node::COMMENT_NODE, domparser::Node::DOCUMENT_FRAGMENT_NODE, domparser::Node::DOCUMENT_NODE, domparser::Node::DOCUMENT_TYPE_NODE, domparser::Node::ELEMENT_NODE, domparser::Node::GetNodeType(), domparser::Node::PROCESSING_INSTRUCTION_NODE, and domparser::Node::TEXT_NODE.
NodeList& domparser::Node::GetChildNodes () [inline, inherited]
gets a list of child nodes
Returns:
list of child nodes
Definition at line 170 of file Node.h.
References domparser::Node::childNodes.
Referenced by domparser::Range::comparePoint(), domparser::Range::ComparePoints(), domparser::Node::doGetChildIdx(), domparser::Node::doInsert(), domparser::TreeWalker::NextNodeSubstep(), domparser::TreeWalker::previousNode(), domparser::Range::selectNode(), domparser::Range::selectNodeContents(), domparser::Range::SetBoundaryPoint(), domparser::Range::setEndAfter(), domparser::Range::setEndBefore(), domparser::Range::setStartAfter(), domparser::Range::setStartBefore(), and domparser::TreeWalker::TraverseChildrenSubstep().
Node* domparser::Node::GetParentNode () [inline, inherited]
gets the parent node
Returns:
parent node
Definition at line 176 of file Node.h.
Referenced by domparser::Node::compareDocumentPosition(), domparser::Range::ComparePoints(), doAdoptNode(), domparser::Node::doPreRemoveChild(), domparser::Node::doRemoveChild(), domparser::Range::GetCommonAncestorContainer(), domparser::DocumentFactory::OnInBodyStartTagInsertion(), domparser::TreeWalker::parentNode(), domparser::TreeWalker::previousNode(), domparser::Range::selectNode(), domparser::Range::setEndAfter(), domparser::Range::setEndBefore(), domparser::Range::setStartAfter(), domparser::Range::setStartBefore(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), and domparser::TreeWalker::TraverseSiblingsSubstep().
Node* domparser::Node::GetFirstChild () [inline, inherited]
gets first child of this node
Returns:
first child or null
Definition at line 182 of file Node.h.
Referenced by domparser::TreeWalker::NextNodeSubstep(), and domparser::TreeWalker::TraverseSiblingsInnerSubstep().
Node* domparser::Node::GetLastChild () [inline, inherited]
gets last child of this node
Returns:
last child or null
Definition at line 188 of file Node.h.
Referenced by domparser::TreeWalker::previousNode(), and domparser::TreeWalker::TraverseSiblingsInnerSubstep().
Node* domparser::Node::GetPreviousSibling () [inline, inherited]
gets previous sibling
Returns:
previous sibling or null
Definition at line 194 of file Node.h.
Referenced by domparser::Node::doRemoveChild(), domparser::TreeWalker::previousNode(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), domparser::TreeWalker::TraverseSiblingsInnerSubstep(), and domparser::TreeWalker::TraverseSiblingsSubstep().
Node* domparser::Node::GetNextSibling () [inline, inherited]
gets next sibling
Returns:
next sibling or null
Definition at line 200 of file Node.h.
Referenced by domparser::Node::doPreInsert(), domparser::Node::doRemoveChild(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), domparser::TreeWalker::TraverseSiblingsInnerSubstep(), and domparser::TreeWalker::TraverseSiblingsSubstep().
Document * domparser::Node::GetOwnerDocument () [inherited]
gets owning/parent document for this node
Returns:
parent document
Definition at line 32 of file Node.cpp.
References domparser::Node::DOCUMENT_NODE, domparser::Node::GetNodeType(), and domparser::Node::ownerDocument.
Referenced by domparser::Range::compareBoundaryPoints(), domparser::Node::compareDocumentPosition(), domparser::Range::comparePoint(), domparser::TreeWalker::NextNodeSubstep(), and domparser::Text::splitText().
const DOMString * domparser::Node::GetNodeValue () const [inherited]
gets node (text)-value
Returns:
character data or null
Definition at line 72 of file Node.cpp.
References domparser::Node::COMMENT_NODE, domparser::Node::GetNodeType(), domparser::Node::PROCESSING_INSTRUCTION_NODE, and domparser::Node::TEXT_NODE.
DOMStringPtr domparser::Node::GetTextContent () const [inherited]
gets text content of this node
Returns:
text content or null
Definition at line 85 of file Node.cpp.
References DOMStringPtr.
void domparser::Node::SetNodeValue (const DOMString & value) [inherited]
set node value
Parameters:
value new value of this node
Definition at line 89 of file Node.cpp.
void domparser::Node::SetTextContent (const DOMString & value) [inherited]
sets text content of this node
Parameters:
value value of this node
Definition at line 92 of file Node.cpp.
void domparser::Node::RegisterObserver (const MutationObserver & observer) [inherited]
registers observer with this node
Parameters:
observer observer to register with this node
Definition at line 363 of file Node.cpp.
References domparser::Node::registeredObservers.
void domparser::Node::QueueMutationRecord (const MutationRecord & record) [static, inherited]
queues a mutation record for all nodes
Parameters:
record mutation record to queue
Definition at line 367 of file Node.cpp.
Referenced by domparser::Node::doRemoveChild().
Node * domparser::Node::doPreInsert (Node * node, Node * child) [protected, inherited]
Definition at line 107 of file Node.cpp.
References adoptNode(), domparser::Node::COMMENT_NODE, domparser::Node::contains(), domparser::Node::DOCUMENT_FRAGMENT_NODE, domparser::Node::DOCUMENT_NODE, domparser::Node::DOCUMENT_TYPE_NODE, domparser::Node::doInsert(), domparser::Node::ELEMENT_NODE, domparser::Node::GetNextSibling(), domparser::Node::GetNodeType(), domparser::Node::nodeType, domparser::Node::ownerDocument, domparser::Node::PROCESSING_INSTRUCTION_NODE, and domparser::Node::TEXT_NODE.
Referenced by domparser::Node::insertBefore().
Node * domparser::Node::doInsert (Node * node, Node * child, bool supressObservers = false) [protected, inherited]
Definition at line 178 of file Node.cpp.
References domparser::Node::DOCUMENT_FRAGMENT_NODE, domparser::Node::doGetChildIdx(), domparser::Node::GetChildNodes(), domparser::Range::GetEndContainer(), domparser::Range::GetEndOffset(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetNodeType(), domparser::Range::GetRanges(), domparser::Range::GetStartContainer(), domparser::Range::GetStartOffset(), domparser::Range::setEnd(), and domparser::Range::setStart().
Referenced by domparser::Node::doPreInsert().
Node * domparser::Node::doPreRemoveChild (Node * child) [protected, inherited]
Definition at line 220 of file Node.cpp.
References domparser::Node::doRemoveChild(), and domparser::Node::GetParentNode().
Referenced by domparser::Node::removeChild().
Node * domparser::Node::doRemoveChild (Node * child, bool supressObservers = false) [protected, inherited]
Definition at line 230 of file Node.cpp.
References domparser::MutationRecord::addedNodes, domparser::ListImpl< T >::AppendItem(), domparser::Node::childNodes, domparser::Node::contains(), domparser::Node::doGetChildIdx(), domparser::Range::GetEndContainer(), domparser::Range::GetEndOffset(), domparser::Node::GetNextSibling(), domparser::Node::GetParentNode(), domparser::Node::GetPreviousSibling(), domparser::Range::GetRanges(), domparser::Range::GetStartContainer(), domparser::Range::GetStartOffset(), domparser::MutationRecord::nextSibling, domparser::Node::OnNodeRemoved(), domparser::MutationRecord::previousSibling, domparser::Node::QueueMutationRecord(), domparser::ListImpl< T >::RemoveItem(), domparser::Range::setEnd(), domparser::Range::setStart(), domparser::MutationRecord::target, and domparser::MutationRecord::type.
Referenced by domparser::Node::doPreRemoveChild().
bool domparser::Node::doGetChildIdx (Node * node, size_t & pos) [protected, inherited]
Definition at line 96 of file Node.cpp.
References domparser::Node::GetChildNodes(), and domparser::ListImpl< T >::GetLength().
Referenced by domparser::Node::doInsert(), and domparser::Node::doRemoveChild().
void domparser::EventTarget::addEventListener (const DOMString & type, EventListener callback, bool capture = false) [inherited]
Definition at line 21 of file EventTarget.cpp.
References domparser::EventTarget::listenEvents.
void domparser::EventTarget::removeEventListener (const DOMString & type, EventListener callback, bool capture = false) [inherited]
Definition at line 26 of file EventTarget.cpp.
References domparser::EventTarget::listenEvents.
bool domparser::EventTarget::dispatchEvent (Event & event) [inherited]
Definition at line 31 of file EventTarget.cpp.
Friends And Related Function Documentation
friend class DocumentFactory [friend]
Definition at line 48 of file Document.h.
friend class NodeFactory [friend]
Reimplemented from domparser::Node.
Definition at line 49 of file Document.h.
friend class toolbot::UnitTestHtmlDocumentFactory [friend]
Definition at line 51 of file Document.h.
Member Data Documentation
network::HttpUrl domparser::Document::dbUrl [private]
Definition at line 176 of file Document.h.
DOMImplementation domparser::Document::implementation [private]
Definition at line 178 of file Document.h.
Referenced by domparser::DocumentFactory::AppendDocType(), and domparser::NodeFactory::CreateDoctype().
DOMString domparser::Document::documentURI [private]
Definition at line 179 of file Document.h.
DOMString domparser::Document::URL [private]
Definition at line 180 of file Document.h.
DOMString domparser::Document::compatMode [private]
Definition at line 182 of file Document.h.
DOMString domparser::Document::characterSet [private]
Definition at line 183 of file Document.h.
DOMString domparser::Document::contentType [private]
Definition at line 184 of file Document.h.
DocumentType* domparser::Document::doctype [private]
Definition at line 186 of file Document.h.
Element* domparser::Document::documentElement [private]
Definition at line 187 of file Document.h.
Document* domparser::Node::ownerDocument [protected, inherited]
Definition at line 260 of file Node.h.
Referenced by doAdoptNode(), domparser::Node::doPreInsert(), and domparser::Node::GetOwnerDocument().
The documentation for this class was generated from the following files:
DOMParser/src/Document.h
DOMParser/src/Document.cpp