DeepNet: tools::Regex Class Reference
tools::Regex Class Reference
wrapper class for (extended) posix compatible regular expressions.
#include <Regex.h>
Public Member Functions
Regex (const std::string &regexExp, const bool caseInsensitive=false)
constructs a regular expression with a precompiled regex.
virtual ~Regex ()
bool Match (const std::string &target, std::vector< std::string > &groups)
matches a target string against a precompiled regex.
Static Public Member Functions
static bool Match (const std::string &regexExp, const std::string &target, std::vector< std::string > &groups, const bool caseInsensitive=false)
matches a target string against a regex.
Static Private Member Functions
static bool Match (const regex_t &regex, const std::string &target, std::vector< std::string > &groups)
static bool Compile (const std::string &regexExp, const bool caseInsensitive, regex_t &regex)
static void FreeRegex (regex_t &regex)
Private Attributes
regex_t regex
bool isInitialized
Detailed Description
wrapper class for (extended) posix compatible regular expressions.
Definition at line 20 of file Regex.h.
Constructor & Destructor Documentation
tools::Regex::Regex (const std::string & regexExp, const bool caseInsensitive = false)
constructs a regular expression with a precompiled regex.
Parameters:
regexExp the regex.
caseInsensitive true if regex is case insensitive.
Definition at line 16 of file Regex.cpp.
References Compile(), isInitialized, and regex.
tools::Regex::~Regex () [virtual]
Definition at line 21 of file Regex.cpp.
References FreeRegex(), isInitialized, and regex.
Member Function Documentation
bool tools::Regex::Match (const std::string & target, std::vector< std::string > & groups)
matches a target string against a precompiled regex.
Parameters:
target target string.
groups result groups.
Returns:
true if match, false if not match.
Definition at line 111 of file Regex.cpp.
References isInitialized, and regex.
Referenced by network::HttpCookie::FromString(), Match(), toolbot::UnitTestUrl::ReadInvalidURLFile(), htmlparser::UrlInserter::ReadURLFile(), and toolbot::UnitTestUrl::ReadValidURLFile().
bool tools::Regex::Match (const std::string & regexExp, const std::string & target, std::vector< std::string > & groups, const bool caseInsensitive = false) [static]
matches a target string against a regex.
Parameters:
regexExp the regex.
target target string.
groups result groups.
caseInsensitive true if regex is case insensitive.
Returns:
true if match, false if not match.
Definition at line 94 of file Regex.cpp.
References Compile(), FreeRegex(), Match(), and regex.
bool tools::Regex::Match (const regex_t & regex, const std::string & target, std::vector< std::string > & groups) [static, private]
Definition at line 43 of file Regex.cpp.
bool tools::Regex::Compile (const std::string & regexExp, const bool caseInsensitive, regex_t & regex) [static, private]
Definition at line 28 of file Regex.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by Match(), and Regex().
void tools::Regex::FreeRegex (regex_t & regex) [static, private]
Definition at line 106 of file Regex.cpp.
Referenced by Match(), and ~Regex().
Member Data Documentation
regex_t tools::Regex::regex [private]
Definition at line 56 of file Regex.h.
Referenced by Match(), Regex(), and ~Regex().
bool tools::Regex::isInitialized [private]
Definition at line 57 of file Regex.h.
Referenced by Match(), Regex(), and ~Regex().
The documentation for this class was generated from the following files:
Tools/src/Regex.h
Tools/src/Regex.cpp