DeepNet: parser::HtmlParserBase Class Reference
parser::HtmlParserBase Class Reference
#include <HtmlParserBase.h>
Public Member Functions
virtual ~HtmlParserBase ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
HtmlParserBase (const HtmlParserParam *parserParam)
void SetThreadFunction (ThreadFunction pFunction)
Protected Attributes
const HtmlParserParam * parserParam
std::map< HtmlParserThread
*, HtmlParserParam * > htmlParserThreads
Private Member Functions
virtual bool StartParser ()=0
bool StopParser ()
bool WatchDog ()
Static Private Member Functions
static void * HtmlParserThreadFunc (threading::Thread::THREAD_PARAM *threadParam)
Detailed Description
Definition at line 18 of file HtmlParserBase.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
parser::HtmlParserBase::HtmlParserBase (const HtmlParserParam * parserParam) [protected]
Definition at line 19 of file HtmlParserBase.cpp.
parser::HtmlParserBase::~HtmlParserBase () [virtual]
Definition at line 26 of file HtmlParserBase.cpp.
Member Function Documentation
void * parser::HtmlParserBase::HtmlParserThreadFunc (threading::Thread::THREAD_PARAM * threadParam) [static, private]
Definition at line 29 of file HtmlParserBase.cpp.
References threading::Thread::THREAD_PARAM::instance, log::Logging::RegisterThreadID(), threading::Thread::ShallEnd(), StartParser(), StopParser(), and WatchDog().
virtual bool parser::HtmlParserBase::StartParser () [private, pure virtual]
Implemented in parser::CommerceSearchParser, and parser::GenericWebHtmlParser.
Referenced by HtmlParserThreadFunc().
bool parser::HtmlParserBase::StopParser () [private]
Definition at line 51 of file HtmlParserBase.cpp.
References htmlParserThreads.
Referenced by HtmlParserThreadFunc().
bool parser::HtmlParserBase::WatchDog () [private]
Definition at line 71 of file HtmlParserBase.cpp.
References htmlParserThreads.
Referenced by HtmlParserThreadFunc().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
const HtmlParserParam* parser::HtmlParserBase::parserParam [protected]
Definition at line 35 of file HtmlParserBase.h.
Referenced by parser::CommerceSearchParser::StartParser(), and parser::GenericWebHtmlParser::StartParser().
std::map<HtmlParserThread*, HtmlParserParam*> parser::HtmlParserBase::htmlParserThreads [protected]
Definition at line 36 of file HtmlParserBase.h.
Referenced by parser::CommerceSearchParser::StartParser(), parser::GenericWebHtmlParser::StartParser(), StopParser(), and WatchDog().
The documentation for this class was generated from the following files:
Parser/src/HtmlParserBase.h
Parser/src/HtmlParserBase.cpp