DeepNet: parser::HtmlParserThread Class Reference
parser::HtmlParserThread Class Reference
#include <HtmlParserThread.h>
Public Member Functions
HtmlParserThread ()
virtual ~HtmlParserThread ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
database::DatabaseHelper & DB ()
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
virtual bool ParsePage (const HtmlParserEntry &entry, tools::Pointer< htmlparser::IHtmlParserResult > &result)=0
virtual void InitParserThread ()
bool ParsePages (const std::vector< HtmlParserEntry > &entries)
bool GetNextPages (std::vector< HtmlParserEntry > &entries)
void OnIdle ()
Static Private Member Functions
static void * HtmlParserThreadFunction (THREAD_PARAM *threadParam)
Private Attributes
database::DatabaseHelper databaseHelper
HtmlParserParam * parserParam
Detailed Description
Definition at line 29 of file HtmlParserThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
parser::HtmlParserThread::HtmlParserThread ()
Definition at line 30 of file HtmlParserThread.cpp.
parser::HtmlParserThread::~HtmlParserThread () [virtual]
Definition at line 34 of file HtmlParserThread.cpp.
Member Function Documentation
database::DatabaseHelper& parser::HtmlParserThread::DB () [inline, protected]
Definition at line 35 of file HtmlParserThread.h.
References databaseHelper.
Referenced by HtmlParserThreadFunction(), parser::CommerceSearchParserThread::InitParserThread(), parser::CommerceSearchParserThread::MatchMetaCriteria(), parser::CommerceSearchParserThread::MatchUrlCriteria(), and parser::GenericWebHtmlParserThread::ParsePage().
void * parser::HtmlParserThread::HtmlParserThreadFunction (THREAD_PARAM * threadParam) [static, private]
Definition at line 37 of file HtmlParserThread.cpp.
References database::DatabaseHelper::CreateConnection(), parser::HtmlParserParam::databaseConfig, DB(), database::DatabaseHelper::DestroyConnection(), GetNextPages(), InitParserThread(), threading::Thread::THREAD_PARAM::instance, ParsePages(), parserParam, PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, threading::Thread::THREAD_PARAM::pParam, log::Logging::RegisterThreadID(), and threading::Thread::ShallEnd().
virtual bool parser::HtmlParserThread::ParsePage (const HtmlParserEntry & entry, tools::Pointer< htmlparser::IHtmlParserResult > & result) [private, pure virtual]
Implemented in parser::GenericWebHtmlParserThread.
Referenced by ParsePages().
virtual void parser::HtmlParserThread::InitParserThread () [inline, private, virtual]
Reimplemented in parser::CommerceSearchParserThread.
Definition at line 42 of file HtmlParserThread.h.
Referenced by HtmlParserThreadFunction().
bool parser::HtmlParserThread::ParsePages (const std::vector< HtmlParserEntry > & entries) [private]
Definition at line 99 of file HtmlParserThread.cpp.
References htmlparser::HtmlParserFactory::CreateInstance(), tools::Pointer< T >::Get(), htmlparser::HtmlParserFactory::LIBXML, log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, htmlparser::IHtmlParser::Parse(), ParsePage(), PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by HtmlParserThreadFunction().
bool parser::HtmlParserThread::GetNextPages (std::vector< HtmlParserEntry > & entries) [private]
Definition at line 73 of file HtmlParserThread.cpp.
References caching::CacheHtml::Get(), parser::HtmlParserParam::maxPerSelect, OnIdle(), parserParam, PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by HtmlParserThreadFunction().
void parser::HtmlParserThread::OnIdle () [private]
Definition at line 128 of file HtmlParserThread.cpp.
References parserParam, threading::Thread::ShallEnd(), and parser::HtmlParserParam::waitOnIdle.
Referenced by GetNextPages().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
database::DatabaseHelper parser::HtmlParserThread::databaseHelper [private]
Definition at line 50 of file HtmlParserThread.h.
Referenced by DB().
HtmlParserParam* parser::HtmlParserThread::parserParam [private]
Definition at line 51 of file HtmlParserThread.h.
Referenced by GetNextPages(), HtmlParserThreadFunction(), and OnIdle().
The documentation for this class was generated from the following files:
Parser/src/HtmlParserThread.h
Parser/src/HtmlParserThread.cpp