DeepNet: domparser::Traverser Class Reference
domparser::Traverser Class Reference
#include <Traverser.h>
Public Member Functions
virtual ~Traverser ()
Node * GetRoot ()
NodeFilter::Type GetWhatToShow () const
const NodeFilter * GetFilter () const
Protected Member Functions
Traverser (Node *root, NodeFilter::Type whatToShow, NodeFilter *filter)
NodeFilter::Result FilterNode (Node *node)
Protected Attributes
Node * root
NodeFilter::Type whatToShow
tools::Pointer< NodeFilter > filter
bool activeFlag
Private Member Functions
Traverser ()
Detailed Description
Definition at line 18 of file Traverser.h.
Constructor & Destructor Documentation
domparser::Traverser::Traverser () [inline, private]
Definition at line 21 of file Traverser.h.
domparser::Traverser::Traverser (Node * root, NodeFilter::Type whatToShow, NodeFilter * filter) [protected]
Definition at line 19 of file Traverser.cpp.
domparser::Traverser::~Traverser () [virtual]
Definition at line 26 of file Traverser.cpp.
Member Function Documentation
Node* domparser::Traverser::GetRoot () [inline]
Definition at line 31 of file Traverser.h.
References root.
Referenced by domparser::TreeWalker::parentNode(), domparser::TreeWalker::previousNode(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), domparser::TreeWalker::TraverseSiblings(), and domparser::TreeWalker::TraverseSiblingsSubstep().
NodeFilter::Type domparser::Traverser::GetWhatToShow () const [inline]
Definition at line 32 of file Traverser.h.
References whatToShow.
const NodeFilter* domparser::Traverser::GetFilter () const [inline]
Definition at line 33 of file Traverser.h.
References filter.
NodeFilter::Result domparser::Traverser::FilterNode (Node * node) [protected]
Definition at line 29 of file Traverser.cpp.
References activeFlag, filter, domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_SKIP, domparser::Node::GetNodeType(), tools::Pointer< T >::IsNull(), and whatToShow.
Referenced by domparser::TreeWalker::NextNodeSubstep(), domparser::TreeWalker::parentNode(), domparser::TreeWalker::previousNode(), domparser::TreeWalker::TraverseChildrenSubstep(), domparser::TreeWalker::TraverseSiblingsInnerSubstep(), domparser::TreeWalker::TraverseSiblingsSubstep(), and domparser::NodeIterator::TraverseSubstep().
Member Data Documentation
Node* domparser::Traverser::root [protected]
Definition at line 39 of file Traverser.h.
Referenced by GetRoot(), and domparser::TreeWalker::NextNodeSubstep().
NodeFilter::Type domparser::Traverser::whatToShow [protected]
Definition at line 40 of file Traverser.h.
Referenced by FilterNode(), and GetWhatToShow().
tools::Pointer<NodeFilter> domparser::Traverser::filter [protected]
Definition at line 41 of file Traverser.h.
Referenced by FilterNode(), and GetFilter().
bool domparser::Traverser::activeFlag [protected]
Definition at line 42 of file Traverser.h.
Referenced by FilterNode().
The documentation for this class was generated from the following files:
DOMParser/src/Traverser.h
DOMParser/src/Traverser.cpp