DeepNet: bot::DatabaseRepair Class Reference
bot::DatabaseRepair Class Reference
class for database consistency checks and fixing them if possible
#include <DatabaseRepair.h>
Public Member Functions
virtual ~DatabaseRepair ()
Static Public Member Functions
static bool ValidateSyncTables (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs=std::vector< long long >())
validates all sync tables and checks for inconsistencies
static bool FixUncleanShutdown (database::DatabaseConnection *db, const bool validateBeforeFix=true, const std::vector< long long > &oldCrawlerSessionIDs=std::vector< long long >())
validates and fixes all sync tables and checks for inconsistencies
Private Member Functions
DatabaseRepair ()
Static Private Member Functions
static bool ValidateSyncUrlTable (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs)
static bool ValidateSecondLevelLockTable (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs)
static bool ValidateCrawlerSessionTable (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs)
static bool FixSyncUrlTable (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs)
static bool FixSecondLevelLockTable (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs)
static bool FixCrawlerSessionTable (database::DatabaseConnection *db, const std::vector< long long > &oldCrawlerSessionIDs)
Detailed Description
class for database consistency checks and fixing them if possible
Definition at line 22 of file DatabaseRepair.h.
Constructor & Destructor Documentation
bot::DatabaseRepair::DatabaseRepair () [private]
Definition at line 22 of file DatabaseRepair.cpp.
bot::DatabaseRepair::~DatabaseRepair () [virtual]
Definition at line 25 of file DatabaseRepair.cpp.
Member Function Documentation
bool bot::DatabaseRepair::ValidateSyncTables (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs = std::vector<long long>()) [static]
validates all sync tables and checks for inconsistencies
Parameters:
db database connection
oldCrawlerSessionIDs list of crawler sessions to check for consistency (empty list assumes that no instances use the database at the time of the call)
Returns:
true if database is consistent, false if inconsistent
Definition at line 187 of file DatabaseRepair.cpp.
References log::Logging::LogWarn(), ValidateCrawlerSessionTable(), ValidateSecondLevelLockTable(), and ValidateSyncUrlTable().
bool bot::DatabaseRepair::FixUncleanShutdown (database::DatabaseConnection * db, const bool validateBeforeFix = true, const std::vector< long long > & oldCrawlerSessionIDs = std::vector<long long>()) [static]
validates and fixes all sync tables and checks for inconsistencies
Parameters:
db database connection
validateBeforeFix set true if table should be validated before fixing algorithms are applied
oldCrawlerSessionIDs list of crawler sessions to check for consistency (empty list assumes that no instances use the database at the time of the call)
Returns:
true if database is consistent, false if inconsistent
Definition at line 199 of file DatabaseRepair.cpp.
References FixCrawlerSessionTable(), FixSecondLevelLockTable(), FixSyncUrlTable(), log::Logging::LogWarn(), ValidateCrawlerSessionTable(), ValidateSecondLevelLockTable(), and ValidateSyncUrlTable().
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), and toolbot::DeepNetToolBot::OnRun().
bool bot::DatabaseRepair::ValidateSyncUrlTable (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs) [static, private]
Definition at line 134 of file DatabaseRepair.cpp.
References database::WhereCondition::AddColumns(), database::syncurlsTableBase::CreateTableDefinition(), database::WhereCondition::Equals(), database::TableColumn::Get(), database::TableBase::GetConstColumnByName(), database::syncurlsTableBase::GetDefinition_CRAWLERSESSION_ID(), tools::PointerContainer< T >::GetIter(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::LogError(), log::Logging::LogTrace(), tools::PointerContainer< T >::Next(), database::WhereCondition::NotEquals(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAddCountColumn(), tools::PointerContainer< T >::Size(), and database::SelectStatement::Where().
Referenced by FixUncleanShutdown(), and ValidateSyncTables().
bool bot::DatabaseRepair::ValidateSecondLevelLockTable (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs) [static, private]
Definition at line 81 of file DatabaseRepair.cpp.
References database::WhereCondition::AddColumns(), database::locksecondleveldomainTableBase::CreateTableDefinition(), database::WhereCondition::Equals(), database::TableColumn::Get(), database::TableBase::GetConstColumnByName(), database::locksecondleveldomainTableBase::GetDefinition_CRAWLERSESSION_ID(), tools::PointerContainer< T >::GetIter(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::LogError(), log::Logging::LogTrace(), tools::PointerContainer< T >::Next(), database::WhereCondition::NotEquals(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAddCountColumn(), tools::PointerContainer< T >::Size(), and database::SelectStatement::Where().
Referenced by FixUncleanShutdown(), and ValidateSyncTables().
bool bot::DatabaseRepair::ValidateCrawlerSessionTable (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs) [static, private]
Definition at line 28 of file DatabaseRepair.cpp.
References database::WhereCondition::AddColumns(), database::crawlersessionsTableBase::CreateTableDefinition(), database::WhereCondition::Equals(), database::TableColumn::Get(), database::TableBase::GetConstColumnByName(), database::crawlersessionsTableBase::GetDefinition_ID(), tools::PointerContainer< T >::GetIter(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::LogError(), log::Logging::LogTrace(), tools::PointerContainer< T >::Next(), database::WhereCondition::NotEquals(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAddCountColumn(), tools::PointerContainer< T >::Size(), and database::SelectStatement::Where().
Referenced by FixUncleanShutdown(), and ValidateSyncTables().
bool bot::DatabaseRepair::FixSyncUrlTable (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs) [static, private]
Definition at line 219 of file DatabaseRepair.cpp.
References database::WhereCondition::Equals(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::WhereCondition::InitialComp(), database::WhereCondition::NotEquals(), tools::TimeTools::NowUTC(), database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_schedule(), and database::DatabaseConnection::Update().
Referenced by FixUncleanShutdown().
bool bot::DatabaseRepair::FixSecondLevelLockTable (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs) [static, private]
Definition at line 249 of file DatabaseRepair.cpp.
References database::WhereCondition::Equals(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::WhereCondition::InitialComp(), database::WhereCondition::NotEquals(), tools::TimeTools::NowUTC(), database::locksecondleveldomainTableBase::Set_CRAWLERSESSION_ID(), database::locksecondleveldomainTableBase::Set_schedule(), and database::DatabaseConnection::Update().
Referenced by FixUncleanShutdown().
bool bot::DatabaseRepair::FixCrawlerSessionTable (database::DatabaseConnection * db, const std::vector< long long > & oldCrawlerSessionIDs) [static, private]
Definition at line 279 of file DatabaseRepair.cpp.
References database::WhereCondition::AddColumns(), database::crawlersessionsTableBase::CreateTableDefinition(), database::DatabaseConnection::Delete(), database::WhereCondition::Equals(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), and database::DeleteStatement::Where().
Referenced by FixUncleanShutdown().
The documentation for this class was generated from the following files:
Bot/src/DatabaseRepair.h
Bot/src/DatabaseRepair.cpp