<div class="wrapper_centered">
  <div class="outer_centered">
    <div class="inner_centered">
      <p style="text-align: center;">
      Haben Sie Fragen zu unserem Angebot oder Dienstleistungen?
      </p>
      <p style="text-align: left;">
      Z&ouml;gern Sie nicht mit uns in Kontakt zu treten. 
      Nutzen Sie dazu untenstehendes Formular. 
      </p>
      <p style="text-align: left;">
      Wir melden uns umgehend bei Ihnen. Vielen Dank f&uuml;r Ihr Interesse.
      </p>
    </div>
  </div>
</div>
 <div style="clear: both; height: 0px;"></div>
