<div class="wrapper_centered">
  <div class="outer_centered">
    <div class="inner_centered">

<h3>&Uuml;ber SIRIDIA</h3>
<p style="width: 50%; text-align: left; padding-left: 25%;">
SIRIDIA ist ein junges und dynamisches Unternehmen, dass es sich zum Ziel gesetzt hat eine unabh&auml;ngige und eigenst&auml;ndige Suchmaschine zu
betreiben. Zudem unterst&uuml;tzt SIRIDIA E-Commerce Unternehmen im Bereich SEO und optimiert deren Sichtbarkeit und Relevanz.
</p>
<p style="width: 50%; text-align: left; padding-left: 25%;">
Wir von SIRIDIA sind der Meinung, dass werbegetriebene Gesch&auml;ftskonzepte f&uuml;r Suchmaschinen der Fairness und Gleichberechtigung auf dem
Markt schaden und diametral dem gesellschaftlichen Ziel gegen&uuml;berstehen objektive und qualitativ hochwertige Suchergebnisse zur Verf&uuml;gung zu haben, 
deshalb geht SIRIDIA einen v&ouml;llig anderen und neuartigen Weg.
</p>

<h3>SEO-Consulting</h3>
<p style="width: 50%; text-align: left; padding-left: 25%;">
Wir bieten ein breites Spektrum an SEO Dienstleistungen. Dieses umfasst SEO-Analysen f&uuml;r die eigene Webseite,
aber auch weitergehende, kundenspezifische Analysen und techn. Beratung bei der Umsetzung SEO-spezifischer Ma&szlig;nahmen. Zudem bieten wir
erweiterte Analysen, wie z.B. Vergleichsanalysen von verschiedenen Webseiten und einer Volltext-Analyse zur Bestimmung
der Relevanz. Au&szlig;erdem bieten wir Monitoring Dienstleistungen die Probleme und Fehler im Bezug auf SEO fr&uuml;hzeitig
erkennen und verhindern das wertvolle Pl&auml;tze z.B. auf Google verloren werden.
</p>
<p>
<a class="undecorated_link" href="/seo_services/">=&gt; &Uuml;bersicht &uuml;ber unsere SEO-Consulting Dienstleistungen &lt;=</a>
</p>

<h3>Commerce Search/Eigene Webseitensuche</h3>
<p style="width: 50%; text-align: left; padding-left: 25%;">
SIRIDIA bietet eine Webseitensuche an, die auf verschiedene Weisen genutzt werden kann. Ihre Webseite wird eigenst&auml;ndig von unseren Crawlern indiziert
und ben&ouml;tigt deshalb weder eine Anpassung Ihrer Webseite noch besteht die Notwendigkeit uns Ihre Inhalte vorab zuliefern. Nat&uuml;rlich gibt es zudem die M&ouml;glichkeit
zus&auml;tzlich eigene Inhalte mit einzupflegen und durchsuchbar zu machen.
</p>
<p>
<a class="undecorated_link" href="/website_services/">=&gt; &Uuml;bersicht &uuml;ber unsere Webseiten-Suche &lt;=</a>
</p>

<h3>Weitere Dienstleistungen</h3>
<p style="width: 50%; text-align: left; padding-left: 25%;">
SIRIDIA bietet au&szlig;erdem speziell auf Kundenbed&uuml;rftnisse zugeschnittene Dienstleistung. Dazu geh&ouml;ren Performance Monitoring der Webseite
aber auch die umfassende Indexierung spezieller Keywords und/oder Webseiten im Internet. Diese Daten k&ouml;nnen zur Marktforschung/Analyse, zum Vergleichen
mit Wettbewerben genutzt werden oder f&uuml;r IP und Copyright Owner. 
</p>
<p>
<a class="undecorated_link" href="/information_services/">=&gt; &Uuml;bersicht &uuml;ber unsere Informations-Dienstleistungen &lt;=</a>
</p>


    </div>
  </div>
</div>
 <div style="clear: both; height: 0px;"></div>
