DeepNet: domparser::Range Class Reference
domparser::Range Class Reference
#include <Range.h>
Classes
struct BoundaryPoint
Public Types
enum RangeType { START_TO_START = 0, START_TO_END = 1, END_TO_END = 2, END_TO_START = 3 }
enum BoundaryPointPosition { BEFORE = -1, EQUAL = 0, AFTER = 1 }
Public Member Functions
Range (Node *context, unsigned long offset)
virtual ~Range ()
void setStart (Node *refNode, unsigned long offset)
void setEnd (Node *refNode, unsigned long offset)
void setStartBefore (Node *refNode)
void setStartAfter (Node *refNode)
void setEndBefore (Node *refNode)
void setEndAfter (Node *refNode)
void selectNode (Node *refNode)
void selectNodeContents (Node *refNode)
void collapse (bool toStart)
BoundaryPointPosition compareBoundaryPoints (RangeType how, Range *sourceRange)
BoundaryPointPosition comparePoint (Node *node, unsigned long offset)
Node * GetStartContainer ()
unsigned long GetStartOffset () const
Node * GetEndContainer ()
unsigned long GetEndOffset () const
bool GetCollapsed ()
Node * GetCommonAncestorContainer ()
Static Public Member Functions
static std::list< Range * > & GetRanges ()
Private Types
enum RangePos { START, END }
Private Member Functions
void RegisterRange ()
void UnregisterRange ()
void SetBoundaryPoint (const RangePos pos, Node *node, unsigned long offset)
Static Private Member Functions
static BoundaryPointPosition ComparePoints (BoundaryPoint &a, BoundaryPoint &b)
static BoundaryPointPosition ComparePoints (Node *nodeA, unsigned long offsetA, Node *nodeB, unsigned long offsetB)
Private Attributes
BoundaryPoint start
BoundaryPoint end
Static Private Attributes
static std::list< Range * > ranges
Detailed Description
Definition at line 19 of file Range.h.
Member Enumeration Documentation
enum domparser::Range::RangeType
Enumerator:
START_TO_START
START_TO_END
END_TO_END
END_TO_START
Definition at line 21 of file Range.h.
enum domparser::Range::BoundaryPointPosition
Enumerator:
BEFORE
EQUAL
AFTER
Definition at line 28 of file Range.h.
enum domparser::Range::RangePos [private]
Enumerator:
START
END
Definition at line 59 of file Range.h.
Constructor & Destructor Documentation
domparser::Range::Range (Node * context, unsigned long offset)
Definition at line 24 of file Range.cpp.
References RegisterRange().
domparser::Range::~Range () [virtual]
Definition at line 30 of file Range.cpp.
References UnregisterRange().
Member Function Documentation
void domparser::Range::setStart (Node * refNode, unsigned long offset) [inline]
Definition at line 69 of file Range.h.
References SetBoundaryPoint(), and START.
Referenced by collapse(), domparser::Node::doInsert(), domparser::Node::doRemoveChild(), selectNode(), selectNodeContents(), setStartAfter(), and setStartBefore().
void domparser::Range::setEnd (Node * refNode, unsigned long offset) [inline]
Definition at line 70 of file Range.h.
References END, and SetBoundaryPoint().
Referenced by collapse(), domparser::Node::doInsert(), domparser::Node::doRemoveChild(), selectNode(), selectNodeContents(), setEndAfter(), and setEndBefore().
void domparser::Range::setStartBefore (Node * refNode)
Definition at line 170 of file Range.cpp.
References domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetParentNode(), and setStart().
void domparser::Range::setStartAfter (Node * refNode)
Definition at line 187 of file Range.cpp.
References domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetParentNode(), and setStart().
void domparser::Range::setEndBefore (Node * refNode)
Definition at line 204 of file Range.cpp.
References domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetParentNode(), and setEnd().
void domparser::Range::setEndAfter (Node * refNode)
Definition at line 221 of file Range.cpp.
References domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetParentNode(), and setEnd().
void domparser::Range::selectNode (Node * refNode)
Definition at line 238 of file Range.cpp.
References domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetParentNode(), setEnd(), and setStart().
void domparser::Range::selectNodeContents (Node * refNode)
Definition at line 256 of file Range.cpp.
References domparser::Node::DOCUMENT_TYPE_NODE, domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetNodeType(), setEnd(), and setStart().
void domparser::Range::collapse (bool toStart)
Definition at line 267 of file Range.cpp.
References domparser::Range::BoundaryPoint::container, end, domparser::Range::BoundaryPoint::offset, setEnd(), setStart(), and start.
Range::BoundaryPointPosition domparser::Range::compareBoundaryPoints (RangeType how, Range * sourceRange)
Definition at line 136 of file Range.cpp.
References ComparePoints(), domparser::Range::BoundaryPoint::container, end, END_TO_END, END_TO_START, domparser::Node::GetOwnerDocument(), start, START_TO_END, and START_TO_START.
Referenced by GetCollapsed().
Range::BoundaryPointPosition domparser::Range::comparePoint (Node * node, unsigned long offset)
Definition at line 116 of file Range.cpp.
References ComparePoints(), domparser::Range::BoundaryPoint::container, domparser::Node::DOCUMENT_TYPE_NODE, domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetNodeType(), domparser::Node::GetOwnerDocument(), domparser::Range::BoundaryPoint::offset, and start.
Node* domparser::Range::GetStartContainer () [inline]
Definition at line 96 of file Range.h.
References domparser::Range::BoundaryPoint::container, and start.
Referenced by domparser::Node::doInsert(), and domparser::Node::doRemoveChild().
unsigned long domparser::Range::GetStartOffset () const [inline]
Definition at line 97 of file Range.h.
References domparser::Range::BoundaryPoint::offset, and start.
Referenced by domparser::Node::doInsert(), and domparser::Node::doRemoveChild().
Node* domparser::Range::GetEndContainer () [inline]
Definition at line 98 of file Range.h.
References domparser::Range::BoundaryPoint::container, and end.
Referenced by domparser::Node::doInsert(), and domparser::Node::doRemoveChild().
unsigned long domparser::Range::GetEndOffset () const [inline]
Definition at line 99 of file Range.h.
References end, and domparser::Range::BoundaryPoint::offset.
Referenced by domparser::Node::doInsert(), and domparser::Node::doRemoveChild().
bool domparser::Range::GetCollapsed () [inline]
Definition at line 100 of file Range.h.
References compareBoundaryPoints(), EQUAL, and START_TO_END.
Node * domparser::Range::GetCommonAncestorContainer ()
Definition at line 274 of file Range.cpp.
References domparser::Range::BoundaryPoint::container, domparser::Node::contains(), end, domparser::Node::GetParentNode(), and start.
static std::list<Range*>& domparser::Range::GetRanges () [inline, static]
Definition at line 104 of file Range.h.
References ranges.
Referenced by domparser::Node::doInsert(), and domparser::Node::doRemoveChild().
void domparser::Range::RegisterRange () [private]
Definition at line 34 of file Range.cpp.
References ranges.
Referenced by Range().
void domparser::Range::UnregisterRange () [private]
Definition at line 38 of file Range.cpp.
References ranges.
Referenced by ~Range().
void domparser::Range::SetBoundaryPoint (const RangePos pos, Node * node, unsigned long offset) [private]
Definition at line 89 of file Range.cpp.
References domparser::Node::DOCUMENT_TYPE_NODE, END, domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetNodeType(), and START.
Referenced by setEnd(), and setStart().
Range::BoundaryPointPosition domparser::Range::ComparePoints (BoundaryPoint & a, BoundaryPoint & b) [static, private]
Definition at line 44 of file Range.cpp.
References domparser::Range::BoundaryPoint::container, and domparser::Range::BoundaryPoint::offset.
Referenced by compareBoundaryPoints(), comparePoint(), and ComparePoints().
Range::BoundaryPointPosition domparser::Range::ComparePoints (Node * nodeA, unsigned long offsetA, Node * nodeB, unsigned long offsetB) [static, private]
Definition at line 48 of file Range.cpp.
References AFTER, BEFORE, domparser::Node::compareDocumentPosition(), ComparePoints(), domparser::Node::contains(), domparser::Node::DOCUMENT_POSITION_FOLLOWING, EQUAL, domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), and domparser::Node::GetParentNode().
Member Data Documentation
BoundaryPoint domparser::Range::start [private]
Definition at line 113 of file Range.h.
Referenced by collapse(), compareBoundaryPoints(), comparePoint(), GetCommonAncestorContainer(), GetStartContainer(), and GetStartOffset().
BoundaryPoint domparser::Range::end [private]
Definition at line 114 of file Range.h.
Referenced by collapse(), compareBoundaryPoints(), GetCommonAncestorContainer(), GetEndContainer(), and GetEndOffset().
std::list< Range * > domparser::Range::ranges [static, private]
Definition at line 121 of file Range.h.
Referenced by GetRanges(), RegisterRange(), and UnregisterRange().
The documentation for this class was generated from the following files:
DOMParser/src/Range.h
DOMParser/src/Range.cpp