DeepNet: parser::CommerceSearchProduct Class Reference
parser::CommerceSearchProduct Class Reference
#include <CommerceSearchProduct.h>
Public Member Functions
CommerceSearchProduct ()
virtual ~CommerceSearchProduct ()
void Store (database::DatabaseConnection *db)
Public Attributes
std::string productID
std::string productName
std::string productBrand
std::string productImage
std::string productDescription
std::string productURL
Detailed Description
Definition at line 18 of file CommerceSearchProduct.h.
Constructor & Destructor Documentation
parser::CommerceSearchProduct::CommerceSearchProduct ()
Definition at line 15 of file CommerceSearchProduct.cpp.
parser::CommerceSearchProduct::~CommerceSearchProduct () [virtual]
Definition at line 18 of file CommerceSearchProduct.cpp.
Member Function Documentation
void parser::CommerceSearchProduct::Store (database::DatabaseConnection * db)
Definition at line 21 of file CommerceSearchProduct.cpp.
References database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), productBrand, productID, productName, database::customerproductsTableBase::Set_productBrand(), database::customerproductsTableBase::Set_productName(), and database::customerproductsTableBase::Set_productNo().
Referenced by parser::CommerceSearchMatchCriteria::Match().
Member Data Documentation
std::string parser::CommerceSearchProduct::productID
Definition at line 27 of file CommerceSearchProduct.h.
Referenced by parser::CommerceSearchMatchCriteria::Match(), and Store().
std::string parser::CommerceSearchProduct::productName
Definition at line 28 of file CommerceSearchProduct.h.
Referenced by parser::CommerceSearchMatchCriteria::Match(), and Store().
std::string parser::CommerceSearchProduct::productBrand
Definition at line 29 of file CommerceSearchProduct.h.
Referenced by Store().
std::string parser::CommerceSearchProduct::productImage
Definition at line 30 of file CommerceSearchProduct.h.
Referenced by parser::CommerceSearchMatchCriteria::Match().
std::string parser::CommerceSearchProduct::productDescription
Definition at line 31 of file CommerceSearchProduct.h.
Referenced by parser::CommerceSearchMatchCriteria::Match().
std::string parser::CommerceSearchProduct::productURL
Definition at line 33 of file CommerceSearchProduct.h.
Referenced by parser::CommerceSearchMatchCriteria::Match().
The documentation for this class was generated from the following files:
Parser/src/CommerceSearchProduct.h
Parser/src/CommerceSearchProduct.cpp