DeepNet: bot::Bot Class Reference
bot::Bot Class Reference
base class for all (commandline-) applications.
#include <Bot.h>
Public Member Functions
virtual ~Bot ()
bool Run (int argc, char **argv)
this function starts the application.
virtual void OnException (errors::Exception &ex)
this function is called when an uncaught exception derived from errors::Exception occurs.
virtual void OnException ()
this function is called when an uncaught exception occurs.
Protected Member Functions
Bot ()
ConfigManager & Config ()
gets the configuration of this bot::Bot.
database::DatabaseHelper & DB ()
gets the database of this bot::Bot.
Protected Attributes
volatile bool shutdownReceived
true if application shall end.
database::DatabaseConfig * dbConfig
database configuration.
Private Member Functions
virtual bool OnPreInit ()
called after registration of default parameters and before initialization.
virtual bool OnInit ()
called after bot configuration and initialization has completed.
virtual bool OnPostInit ()
called after bot and application specific configuration is initialized and validated.
virtual bool OnRun ()=0
called when all initialization is completed and the applications starts running.
virtual bool OnWatchDog ()
periodically called watchdog function.
virtual bool OnShutdown ()
called before the application is shutting down.
void RegisterDefaultFlags (void)
void RegisterDefaultParams (void)
bool RegisterSignalHandlers ()
void RegisterDatabaseConfigParams (void)
bool InitDatabaseConfigs (void)
void RegisterCacheConfigParams ()
bool InitCacheConfigParams ()
void RegisterPerformanceLoggingParams ()
void InitPerformanceLoggingParams ()
void InitLogging ()
bool InitDefaultParameters ()
bool SwitchUser (const uid_t setUid, const gid_t setGid)
bool Daemonize ()
bool PreInit ()
bool Init (int argc, char **argv)
bool PostInit ()
bool Run ()
bool Shutdown ()
bool WatchDog ()
Static Private Member Functions
static void SignalHandler (int signum, siginfo_t *info, void *ucontext)
Private Attributes
ConfigManager configManager
database::DatabaseHelper databaseHelper
log::Logging * logging
volatile bool restartAfterShutdown
uid_t orig_uid
gid_t orig_gid
uid_t cur_uid
gid_t cur_gid
size_t cacheLogInterval
Static Private Attributes
static Bot * instance = 0
static threading::Mutex signalMutex
Detailed Description
base class for all (commandline-) applications.
All applications derive from this class. It helps processing signals, exceptions, commandline argument handling, logging etc.
Definition at line 35 of file Bot.h.
Constructor & Destructor Documentation
bot::Bot::Bot () [protected]
Definition at line 45 of file Bot.cpp.
References instance.
bot::Bot::~Bot () [virtual]
Definition at line 59 of file Bot.cpp.
References Shutdown().
Member Function Documentation
bool bot::Bot::Run (int argc, char ** argv)
this function starts the application.
it returns when the application exits.
Parameters:
argc number of commandline arguments.
argv array of commandline arguments.
Returns:
false on error, true on success.
Definition at line 213 of file Bot.cpp.
References Init(), errors::Exception::InitializeExceptionHandling(), PostInit(), PreInit(), restartAfterShutdown, Run(), and Shutdown().
Referenced by main().
void bot::Bot::OnException (errors::Exception & ex) [virtual]
this function is called when an uncaught exception derived from errors::Exception occurs.
Parameters:
ex exception caught by application
Definition at line 396 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by main().
void bot::Bot::OnException () [virtual]
this function is called when an uncaught exception occurs.
exceptions derived from errors::Exception are caught separately.
See also:
bot::Bot::OnException(errors::Exception&)
Definition at line 401 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
ConfigManager& bot::Bot::Config () [inline, protected]
gets the configuration of this bot::Bot.
See also:
bot::ConfigManager
Returns:
associated bot::ConfigManager.
Definition at line 75 of file Bot.h.
References configManager.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), Init(), InitCacheConfigParams(), workerbot::WorkerBot::InitCrawlerConfig(), InitDatabaseConfigs(), workerbot::WorkerBot::InitIndexerConfigParams(), InitLogging(), workerbot::WorkerBot::InitModeConfig(), workerbot::WorkerBot::InitParserConfig(), InitPerformanceLoggingParams(), workerbot::WorkerBot::OnPreInit(), toolbot::DeepNetToolBot::OnRun(), PostInit(), toolbot::DeepNetToolBot::ProcessUnitTests(), RegisterCacheConfigParams(), toolbot::DeepNetToolBot::RegisterCommerceSearchParams(), workerbot::WorkerBot::RegisterCrawlerConfigParams(), RegisterDatabaseConfigParams(), toolbot::DeepNetToolBot::RegisterDatabaseRepairParams(), toolbot::DeepNetToolBot::RegisterDataminingParams(), RegisterDefaultFlags(), RegisterDefaultParams(), toolbot::DeepNetToolBot::RegisterHtmlClientCURLParams(), toolbot::DeepNetToolBot::RegisterHtmlDocumentFactoryParams(), toolbot::DeepNetToolBot::RegisterHtmlTestParams(), workerbot::WorkerBot::RegisterIndexerConfigParams(), toolbot::DeepNetToolBot::RegisterIndexerExParams(), workerbot::WorkerBot::RegisterModeSpecificParams(), workerbot::WorkerBot::RegisterParserConfigParams(), toolbot::DeepNetToolBot::RegisterPCRERegexTestParams(), RegisterPerformanceLoggingParams(), toolbot::DeepNetToolBot::RegisterRobotTxtParams(), and toolbot::DeepNetToolBot::RegisterUrlInserterParams().
database::DatabaseHelper& bot::Bot::DB () [inline, protected]
gets the database of this bot::Bot.
See also:
database::DatabaseHelper
Returns:
associated database::DatabaseHelper.
Definition at line 82 of file Bot.h.
References databaseHelper.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), InitCacheConfigParams(), InitDatabaseConfigs(), toolbot::DeepNetToolBot::OnRun(), toolbot::DeepNetToolBot::OnShutdown(), toolbot::DeepNetToolBot::ProcessUnitTests(), Shutdown(), and WatchDog().
virtual bool bot::Bot::OnPreInit (void) [inline, private, virtual]
called after registration of default parameters and before initialization.
usually used to register application specific config parameters.
Returns:
false on error, true on success.
Reimplemented in workerbot::WorkerBot, and toolbot::DeepNetToolBot.
Definition at line 91 of file Bot.h.
Referenced by PreInit().
virtual bool bot::Bot::OnInit () [inline, private, virtual]
called after bot configuration and initialization has completed.
usually used to initialize application specific config parameters.
Returns:
false on error, true on success.
Reimplemented in workerbot::WorkerBot, and toolbot::DeepNetToolBot.
Definition at line 98 of file Bot.h.
Referenced by Init().
virtual bool bot::Bot::OnPostInit () [inline, private, virtual]
called after bot and application specific configuration is initialized and validated.
Returns:
false on error, true on success.
Reimplemented in workerbot::WorkerBot.
Definition at line 104 of file Bot.h.
Referenced by PostInit().
virtual bool bot::Bot::OnRun () [private, pure virtual]
called when all initialization is completed and the applications starts running.
when this function returns, the applications does NOT exit.
Returns:
false on error, true on success.
Implemented in workerbot::WorkerBot, and toolbot::DeepNetToolBot.
Referenced by Run().
virtual bool bot::Bot::OnWatchDog () [inline, private, virtual]
periodically called watchdog function.
call interval is hardcoded in WATCHDOG_TIMER_INTERVAL.
Returns:
false on error, true on success.
Definition at line 118 of file Bot.h.
Referenced by WatchDog().
virtual bool bot::Bot::OnShutdown () [inline, private, virtual]
called before the application is shutting down.
Returns:
false on error, true on success.
Reimplemented in workerbot::WorkerBot, and toolbot::DeepNetToolBot.
Definition at line 124 of file Bot.h.
Referenced by Shutdown().
void bot::Bot::SignalHandler (int signum, siginfo_t * info, void * ucontext) [static, private]
Definition at line 64 of file Bot.cpp.
References tools::DebuggingTools::GetSignalInfos(), tools::DebuggingTools::SignalInfos::infoText, instance, log::Logging::IsLogLevelTrace(), threading::Mutex::Lock(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, log::Logging::LOGLEVEL_TRACE, log::Logging::LogUnlimited(), restartAfterShutdown, shutdownReceived, signalMutex, and threading::Mutex::Unlock().
Referenced by RegisterSignalHandlers().
void bot::Bot::RegisterDefaultFlags (void) [private]
Definition at line 126 of file Bot.cpp.
References Config(), and bot::ConfigManager::RegisterFlag().
Referenced by InitDefaultParameters().
void bot::Bot::RegisterDefaultParams (void) [private]
Definition at line 132 of file Bot.cpp.
References Config(), RegisterCacheConfigParams(), RegisterDatabaseConfigParams(), bot::ConfigManager::RegisterParam(), and RegisterPerformanceLoggingParams().
Referenced by InitDefaultParameters().
bool bot::Bot::RegisterSignalHandlers () [private]
Definition at line 107 of file Bot.cpp.
References bot::catchSignalCount, bot::catchSignals, and SignalHandler().
Referenced by InitDefaultParameters().
void bot::Bot::RegisterDatabaseConfigParams (void) [private]
Definition at line 337 of file Bot.cpp.
References Config(), and bot::ConfigManager::RegisterParam().
Referenced by RegisterDefaultParams().
bool bot::Bot::InitDatabaseConfigs (void) [private]
Definition at line 346 of file Bot.cpp.
References Config(), DB(), dbConfig, log::Logging::LogError(), database::DatabaseConfig::SetDatabaseName(), database::DatabaseConfig::SetHost(), database::DatabaseConfig::SetPass(), database::DatabaseConfig::SetPort(), and database::DatabaseConfig::SetUser().
Referenced by PostInit().
void bot::Bot::RegisterCacheConfigParams () [private]
Definition at line 153 of file Bot.cpp.
References Config(), and bot::ConfigManager::RegisterParam().
Referenced by RegisterDefaultParams().
bool bot::Bot::InitCacheConfigParams () [private]
Definition at line 168 of file Bot.cpp.
References Config(), DB(), htmlparser::TLD::GetTLDStrings(), htmlparser::TLD::InitTLDCache(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, caching::CacheRobotsTxt::SetCapacity(), caching::CacheSecondLevelDomain::SetCapacity(), caching::CacheSubdomain::SetCapacity(), caching::CacheHtml::SetCapacity(), caching::CacheParsed::SetCapacity(), caching::CacheDatabaseUrl::SetCapacity(), and network::HttpUrlParser::SetTopLevelDomains().
Referenced by PostInit().
void bot::Bot::RegisterPerformanceLoggingParams () [private]
Definition at line 371 of file Bot.cpp.
References Config(), and bot::ConfigManager::RegisterParam().
Referenced by RegisterDefaultParams().
void bot::Bot::InitPerformanceLoggingParams () [private]
Definition at line 382 of file Bot.cpp.
References cacheLogInterval, Config(), and tools::PerformanceCounter::EnablePerformanceLog().
Referenced by PostInit().
void bot::Bot::InitLogging () [private]
Definition at line 278 of file Bot.cpp.
References Config(), dbConfig, bot::ConfigManager::GetValue(), logging, log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, log::Logging::LOGLEVEL_TRACE, log::Logging::LOGLEVEL_WARN, log::FileLogging::SetAppend(), log::Logging::SetApplicationName(), log::FileLogging::SetFileName(), log::FileLogging::SetFlush(), and log::Logging::SetLogLevel().
Referenced by PostInit().
bool bot::Bot::InitDefaultParameters () [private]
Definition at line 236 of file Bot.cpp.
References RegisterDefaultFlags(), RegisterDefaultParams(), and RegisterSignalHandlers().
Referenced by Init().
bool bot::Bot::SwitchUser (const uid_t setUid, const gid_t setGid) [private]
Definition at line 261 of file Bot.cpp.
References cur_gid, and cur_uid.
Referenced by PostInit().
bool bot::Bot::Daemonize () [private]
Definition at line 244 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by PostInit().
bool bot::Bot::PreInit () [private]
Definition at line 436 of file Bot.cpp.
References OnPreInit().
Referenced by Run().
bool bot::Bot::Init (int argc, char ** argv) [private]
Definition at line 426 of file Bot.cpp.
References Config(), InitDefaultParameters(), and OnInit().
Referenced by Run().
bool bot::Bot::PostInit () [private]
Definition at line 440 of file Bot.cpp.
References Config(), configManager, Daemonize(), bot::ConfigManager::DumpConfig(), bot::ConfigManager::GetValue(), InitCacheConfigParams(), InitDatabaseConfigs(), InitLogging(), InitPerformanceLoggingParams(), log::Logging::IsLogLevelTrace(), log::Logging::LogTrace(), OnPostInit(), bot::ConfigManager::PrintUsage(), and SwitchUser().
Referenced by Run().
bool bot::Bot::Run () [private]
Definition at line 406 of file Bot.cpp.
References cacheLogInterval, OnRun(), shutdownReceived, and WatchDog().
Referenced by Run().
bool bot::Bot::Shutdown () [private]
Definition at line 546 of file Bot.cpp.
References DB(), dbConfig, database::DatabaseHelper::DestroyConnection(), logging, and OnShutdown().
Referenced by Run(), and ~Bot().
bool bot::Bot::WatchDog () [private]
Definition at line 494 of file Bot.cpp.
References cacheLogInterval, database::DatabaseHelper::Connection(), DB(), caching::CacheRobotsTxt::GetMatches(), caching::CacheSecondLevelDomain::GetMatches(), caching::CacheSubdomain::GetMatches(), caching::CacheHtml::GetMatches(), caching::CacheParsed::GetMatches(), caching::CacheDatabaseUrl::GetMatches(), caching::CacheRobotsTxt::GetMisses(), caching::CacheSecondLevelDomain::GetMisses(), caching::CacheSubdomain::GetMisses(), caching::CacheHtml::GetMisses(), caching::CacheParsed::GetMisses(), caching::CacheDatabaseUrl::GetMisses(), caching::CacheRobotsTxt::GetSize(), caching::CacheSecondLevelDomain::GetSize(), caching::CacheSubdomain::GetSize(), caching::CacheHtml::GetSize(), caching::CacheParsed::GetSize(), caching::CacheDatabaseUrl::GetSize(), database::TableBase::Insert(), tools::TimeTools::NowUTC(), OnWatchDog(), database::cacheurlTableBase::Set_action_time(), database::cachesubdomainTableBase::Set_action_time(), database::cacheparsedTableBase::Set_action_time(), database::cachehtmlTableBase::Set_action_time(), database::cachesecondleveldomainTableBase::Set_action_time(), database::cacherobotsTableBase::Set_action_time(), database::cacheparsedTableBase::Set_matches(), database::cacherobotsTableBase::Set_matches(), database::cachesecondleveldomainTableBase::Set_matches(), database::cacheurlTableBase::Set_matches(), database::cachehtmlTableBase::Set_matches(), database::cachesubdomainTableBase::Set_matches(), database::cachesecondleveldomainTableBase::Set_misses(), database::cacheurlTableBase::Set_misses(), database::cachehtmlTableBase::Set_misses(), database::cachesubdomainTableBase::Set_misses(), database::cacherobotsTableBase::Set_misses(), database::cacheparsedTableBase::Set_misses(), database::cachesubdomainTableBase::Set_size(), database::cacherobotsTableBase::Set_size(), database::cachehtmlTableBase::Set_size(), database::cacheparsedTableBase::Set_size(), database::cachesecondleveldomainTableBase::Set_size(), and database::cacheurlTableBase::Set_size().
Referenced by Run().
Member Data Documentation
bot::Bot * bot::Bot::instance = 0 [static, private]
Definition at line 159 of file Bot.h.
Referenced by Bot(), and SignalHandler().
threading::Mutex bot::Bot::signalMutex [static, private]
Definition at line 160 of file Bot.h.
Referenced by SignalHandler().
volatile bool bot::Bot::shutdownReceived [protected]
true if application shall end.
Definition at line 166 of file Bot.h.
Referenced by toolbot::DeepNetToolBot::OnRun(), Run(), and SignalHandler().
database::DatabaseConfig* bot::Bot::dbConfig [protected]
database configuration.
Definition at line 171 of file Bot.h.
Referenced by InitDatabaseConfigs(), InitLogging(), workerbot::WorkerBot::OnRun(), and Shutdown().
ConfigManager bot::Bot::configManager [private]
Definition at line 174 of file Bot.h.
Referenced by Config(), and PostInit().
database::DatabaseHelper bot::Bot::databaseHelper [private]
Definition at line 175 of file Bot.h.
Referenced by DB().
log::Logging* bot::Bot::logging [private]
Definition at line 177 of file Bot.h.
Referenced by InitLogging(), and Shutdown().
volatile bool bot::Bot::restartAfterShutdown [private]
Definition at line 178 of file Bot.h.
Referenced by Run(), and SignalHandler().
uid_t bot::Bot::orig_uid [private]
Definition at line 180 of file Bot.h.
gid_t bot::Bot::orig_gid [private]
Definition at line 181 of file Bot.h.
uid_t bot::Bot::cur_uid [private]
Definition at line 183 of file Bot.h.
Referenced by SwitchUser().
gid_t bot::Bot::cur_gid [private]
Definition at line 184 of file Bot.h.
Referenced by SwitchUser().
size_t bot::Bot::cacheLogInterval [private]
Definition at line 186 of file Bot.h.
Referenced by InitPerformanceLoggingParams(), Run(), and WatchDog().
The documentation for this class was generated from the following files:
Bot/src/Bot.h
Bot/src/Bot.cpp