DeepNet: queryserver::KeywordEntry Class Reference
queryserver::KeywordEntry Class Reference
#include <KeywordEntry.h>
Public Types
enum KeywordEntryType {
UNKNOWN_KEYWORD_TYPE = 0, TITLE_KEYWORD_TYPE, META_KEYWORD_TYPE, URL_KEYWORD_TYPE,
DOMAIN_KEYWORD_TYPE, CONTENT_KEYWORD_TYPE
}
Public Member Functions
KeywordEntry (const KeywordEntryType &type, const double &relevanceIn, const double &weightIn, const std::string &keywordIn, const long long &dictIDIn, const long long &occurrenceIn)
const KeywordEntryType & GetType () const
const std::string & GetKeyword () const
const long long & DictionaryID () const
const long long & Occurrence () const
bool operator== (const Relevance &rhs) const
bool operator< (const Relevance &rhs) const
Relevance operator+ (const Relevance &rhs) const
Relevance operator* (const Relevance &rhs) const
double GetWeightedRelevance (void) const
const double & GetRelevance (void) const
const double & GetWeight (void) const
void SetRelevance (const double &in)
void SetWeight (const double &in)
Static Private Member Functions
static const double GetWeightByOccurrence (const double &weight, const long long &occurrence)
Private Attributes
KeywordEntryType type
std::string keyword
long long dictID
long long occurrence
Detailed Description
Definition at line 19 of file KeywordEntry.h.
Member Enumeration Documentation
enum queryserver::KeywordEntry::KeywordEntryType
Enumerator:
UNKNOWN_KEYWORD_TYPE
TITLE_KEYWORD_TYPE
META_KEYWORD_TYPE
URL_KEYWORD_TYPE
DOMAIN_KEYWORD_TYPE
CONTENT_KEYWORD_TYPE
Definition at line 22 of file KeywordEntry.h.
Constructor & Destructor Documentation
queryserver::KeywordEntry::KeywordEntry (const KeywordEntryType & type, const double & relevanceIn, const double & weightIn, const std::string & keywordIn, const long long & dictIDIn, const long long & occurrenceIn) [inline]
Definition at line 34 of file KeywordEntry.h.
Member Function Documentation
const KeywordEntryType& queryserver::KeywordEntry::GetType (void) const [inline]
Definition at line 43 of file KeywordEntry.h.
References type.
const std::string& queryserver::KeywordEntry::GetKeyword () const [inline]
Definition at line 44 of file KeywordEntry.h.
References keyword.
const long long& queryserver::KeywordEntry::DictionaryID () const [inline]
Definition at line 45 of file KeywordEntry.h.
References dictID.
const long long& queryserver::KeywordEntry::Occurrence () const [inline]
Definition at line 46 of file KeywordEntry.h.
References occurrence.
static const double queryserver::KeywordEntry::GetWeightByOccurrence (const double & weight, const long long & occurrence) [inline, static, private]
Definition at line 49 of file KeywordEntry.h.
References queryserver::Relevance::weight.
bool queryserver::Relevance::operator== (const Relevance & rhs) const [inline, inherited]
Definition at line 38 of file Relevance.h.
References queryserver::Relevance::GetWeightedRelevance().
bool queryserver::Relevance::operator< (const Relevance & rhs) const [inline, inherited]
Definition at line 39 of file Relevance.h.
References queryserver::Relevance::GetWeightedRelevance().
Relevance queryserver::Relevance::operator+ (const Relevance & rhs) const [inline, inherited]
Definition at line 40 of file Relevance.h.
References queryserver::Relevance::GetWeightedRelevance(), queryserver::Relevance::Relevance(), and queryserver::Relevance::weight.
Relevance queryserver::Relevance::operator* (const Relevance & rhs) const [inline, inherited]
Definition at line 41 of file Relevance.h.
References queryserver::Relevance::Relevance(), queryserver::Relevance::relevance, and queryserver::Relevance::weight.
double queryserver::Relevance::GetWeightedRelevance (void) const [inline, inherited]
Definition at line 44 of file Relevance.h.
References queryserver::Relevance::GetRelevance(), and queryserver::Relevance::GetWeight().
Referenced by queryserver::Relevance::operator+(), queryserver::Relevance::operator<(), and queryserver::Relevance::operator==().
const double& queryserver::Relevance::GetRelevance (void) const [inline, inherited]
Definition at line 47 of file Relevance.h.
References queryserver::Relevance::relevance.
Referenced by queryserver::Relevance::GetWeightedRelevance().
const double& queryserver::Relevance::GetWeight (void) const [inline, inherited]
Definition at line 48 of file Relevance.h.
References queryserver::Relevance::weight.
Referenced by queryserver::Relevance::GetWeightedRelevance().
void queryserver::Relevance::SetRelevance (const double & in) [inline, inherited]
Definition at line 50 of file Relevance.h.
References queryserver::Relevance::relevance.
void queryserver::Relevance::SetWeight (const double & in) [inline, inherited]
Definition at line 51 of file Relevance.h.
References queryserver::Relevance::weight.
Member Data Documentation
KeywordEntryType queryserver::KeywordEntry::type [private]
Definition at line 55 of file KeywordEntry.h.
Referenced by GetType().
std::string queryserver::KeywordEntry::keyword [private]
Definition at line 56 of file KeywordEntry.h.
Referenced by GetKeyword().
long long queryserver::KeywordEntry::dictID [private]
Definition at line 57 of file KeywordEntry.h.
Referenced by DictionaryID().
long long queryserver::KeywordEntry::occurrence [private]
Definition at line 58 of file KeywordEntry.h.
Referenced by Occurrence().
The documentation for this class was generated from the following file:
QueryServer/src/KeywordEntry.h