DeepNet: bot::CommandLine Class Reference
bot::CommandLine Class Reference
class for command line argument processing.
#include <CommandLine.h>
Public Member Functions
CommandLine ()
virtual ~CommandLine ()
bool ParseCommandLine (int argc, char **argv, std::vector< ConfigEntry > &registeredParams)
parsing command line from raw parameters and also validating parameters by their name
const std::string & GetApplicationNamePath () const
gets path and filename of this binary.
const std::string & GetApplicationName () const
gets filename of this binary.
Private Attributes
std::string applicationNamePath
std::string applicationName
Detailed Description
class for command line argument processing.
Definition at line 19 of file CommandLine.h.
Constructor & Destructor Documentation
bot::CommandLine::CommandLine ()
Definition at line 20 of file CommandLine.cpp.
bot::CommandLine::~CommandLine () [virtual]
Definition at line 24 of file CommandLine.cpp.
Member Function Documentation
bool bot::CommandLine::ParseCommandLine (int argc, char ** argv, std::vector< ConfigEntry > & registeredParams)
parsing command line from raw parameters and also validating parameters by their name
Parameters:
argc number of commandline arguments.
argv array of commandline arguments.
registeredParams list of acceptable parameter names, gets filled if matching are found.
Returns:
false on error, true on success.
Definition at line 28 of file CommandLine.cpp.
References applicationName, applicationNamePath, log::Logging::Log(), and log::Logging::LOGLEVEL_WARN.
Referenced by bot::ConfigManager::ProcessCmdLine().
const std::string& bot::CommandLine::GetApplicationNamePath () const [inline]
gets path and filename of this binary.
Returns:
path and name of this binary.
Definition at line 40 of file CommandLine.h.
References applicationNamePath.
const std::string& bot::CommandLine::GetApplicationName () const [inline]
gets filename of this binary.
Returns:
filename of this binary.
Definition at line 46 of file CommandLine.h.
References applicationName.
Referenced by bot::ConfigManager::GetApplicationName(), and bot::ConfigManager::PrintUsage().
Member Data Documentation
std::string bot::CommandLine::applicationNamePath [private]
Definition at line 49 of file CommandLine.h.
Referenced by GetApplicationNamePath(), and ParseCommandLine().
std::string bot::CommandLine::applicationName [private]
Definition at line 50 of file CommandLine.h.
Referenced by GetApplicationName(), and ParseCommandLine().
The documentation for this class was generated from the following files:
Bot/src/CommandLine.h
Bot/src/CommandLine.cpp