DeepNet: fastcgiserver::FastCGIRequest Class Reference
fastcgiserver::FastCGIRequest Class Reference
container for a fastcgi client request.
#include <FastCGIRequest.h>
Public Member Functions
FastCGIRequest (FastCGIServerThread *serverThread)
constructs client request.
virtual ~FastCGIRequest ()
void Handle (FCGX_Request &request)
handles a request.
bool IsComplete () const
checks if request completed.
template<class T >
bool GetParam (FCGX_Request &request, const std::string &key, T &value)
gets converted value from fastcgi request parameters.
bool GetParam (FCGX_Request &request, const std::string &key, std::string &value)
gets parameter from fastcgi request.
std::string GetClientAddress () const
gets connected endpoint as string.
FastCGIServerThread * ServerThread ()
gets originating server thread.
const std::string & UserAgent () const
gets client's user agent.
const std::string & RequestURI () const
gets requested uri.
const std::vector
< network::HttpCookie > & Cookies () const
gets cookies from current request.
Protected Member Functions
int register_namespaces (xmlXPathContextPtr xpathCtx, const xmlChar *nsList)
registers namespaces from nsList in xpathCtx.
bool Xpath (std::list< std::string > &queryparts, const char *filename, const xmlChar *xpathExpr, const xmlChar *nsList=0)
gets xpath from request contents (if contents are XML).
bool Validate (const std::string &xsdString, xmlDocPtr doc)
validates xml document against xsd.
Protected Attributes
char * rawPostData
buffer to raw post data.
char * rawQueryString
buffer to raw get data.
std::vector< std::pair
< std::string, std::string > > postParameters
parsed post parameters.
std::vector< std::pair
< std::string, std::string > > getParameters
parsed get parameters.
Private Member Functions
virtual void OnHandle (FCGX_Request &request)=0
void LogRequest ()
void DumpParameters (std::stringstream &ssIn, const std::vector< std::pair< std::string, std::string > > &params)
bool ReadPostData (FCGX_Request &request)
void ParseCookies (std::string cookieString)
Static Private Member Functions
static void SplitArguments (char *, std::vector< std::pair< std::string, std::string > > &)
static std::string SafeGetEnv (const char *name, FCGX_Request &request)
Private Attributes
bool completed
const unsigned long STDIN_MAX
FastCGIServerThread * serverThread
std::vector< network::HttpCookie > cookies
std::string clientIP
std::string clientPort
std::string requestUri
std::string userAgent
Detailed Description
container for a fastcgi client request.
Definition at line 34 of file FastCGIRequest.h.
Constructor & Destructor Documentation
fastcgiserver::FastCGIRequest::FastCGIRequest (FastCGIServerThread * serverThread)
constructs client request.
Parameters:
serverThread originating server thread.
Definition at line 20 of file FastCGIRequest.cpp.
fastcgiserver::FastCGIRequest::~FastCGIRequest () [virtual]
Definition at line 28 of file FastCGIRequest.cpp.
References rawPostData.
Member Function Documentation
void fastcgiserver::FastCGIRequest::Handle (FCGX_Request & request)
handles a request.
Parameters:
request raw fastcgi request.
Definition at line 33 of file FastCGIRequest.cpp.
References clientIP, clientPort, completed, GetParam(), getParameters, LogRequest(), OnHandle(), postParameters, rawPostData, rawQueryString, ReadPostData(), requestUri, SafeGetEnv(), SplitArguments(), and userAgent.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
bool fastcgiserver::FastCGIRequest::IsComplete () const [inline]
checks if request completed.
Returns:
false if not completed, true if completed.
Definition at line 54 of file FastCGIRequest.h.
References completed.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
template<class T > bool fastcgiserver::FastCGIRequest::GetParam (FCGX_Request & request, const std::string & key, T & value) [inline]
gets converted value from fastcgi request parameters.
Parameters:
request raw fastcgi request.
key keyname of parameter.
value gets filled with value of key.
Returns:
false if key does not exists, true if it does.
Definition at line 65 of file FastCGIRequest.h.
Referenced by Handle().
bool fastcgiserver::FastCGIRequest::GetParam (FCGX_Request & request, const std::string & key, std::string & value) [inline]
gets parameter from fastcgi request.
Parameters:
request raw fastcgi request.
key keyname of parameter.
value gets filled with value of key
Returns:
false if key does not exists, true if it does.
Definition at line 86 of file FastCGIRequest.h.
References tools::StringTools::ToLowerNP().
std::string fastcgiserver::FastCGIRequest::GetClientAddress () const [inline]
gets connected endpoint as string.
Returns:
connected endpoint as string.
Definition at line 101 of file FastCGIRequest.h.
References clientIP, and clientPort.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), and LogRequest().
FastCGIServerThread* fastcgiserver::FastCGIRequest::ServerThread () [inline]
gets originating server thread.
Returns:
originating server thread.
Definition at line 107 of file FastCGIRequest.h.
References serverThread.
Referenced by suggestserver::SuggestServerResponse::Process().
const std::string& fastcgiserver::FastCGIRequest::UserAgent () const [inline]
gets client's user agent.
Returns:
client's user agent.
Definition at line 113 of file FastCGIRequest.h.
References userAgent.
const std::string& fastcgiserver::FastCGIRequest::RequestURI () const [inline]
gets requested uri.
Returns:
requested uri.
Definition at line 119 of file FastCGIRequest.h.
References requestUri.
const std::vector<network::HttpCookie>& fastcgiserver::FastCGIRequest::Cookies () const [inline]
gets cookies from current request.
Returns:
cookies.
Definition at line 125 of file FastCGIRequest.h.
References cookies.
Referenced by queryserver::XMLQueryResponse::LogQuery().
int fastcgiserver::FastCGIRequest::register_namespaces (xmlXPathContextPtr xpathCtx, const xmlChar * nsList) [protected]
registers namespaces from nsList in xpathCtx.
Parameters:
xpathCtx xpathCtx the pointer to an XPath context.
nsList nsList the list of known namespaces in "<prefix1>=<href1> <prefix2>=href2> ..." format.
Returns:
0 on success and a negative value otherwise.
Definition at line 283 of file FastCGIRequest.cpp.
Referenced by Xpath().
bool fastcgiserver::FastCGIRequest::Xpath (std::list< std::string > & queryparts, const char * filename, const xmlChar * xpathExpr, const xmlChar * nsList = 0) [protected]
gets xpath from request contents (if contents are XML).
Parameters:
queryparts gets filled with xpath results.
filename xml content string for xpath.
xpathExpr xpath expression.
nsList list of allowed namespaces(???).
Returns:
false on error, true on success.
Definition at line 330 of file FastCGIRequest.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, and register_namespaces().
Referenced by suggestserver::SuggestServerRequest::OnHandle(), inspectorserver::InspectorServerRequest::OnHandle(), queryserver::XMLQueryRequest::ParseQuery(), queryserver::XMLQueryRequest::ParseQueryCriteria(), queryserver::XMLQueryRequest::ParseQueryGrouping(), and queryserver::XMLQueryRequest::ParseQueryLimitations().
bool fastcgiserver::FastCGIRequest::Validate (const std::string & xsdString, xmlDocPtr doc) [protected]
validates xml document against xsd.
Parameters:
xsdString string containing xsd.
doc xml document to validate.
Returns:
false on error, true on success.
Definition at line 241 of file FastCGIRequest.cpp.
virtual void fastcgiserver::FastCGIRequest::OnHandle (FCGX_Request & request) [private, pure virtual]
Implemented in queryserver::XMLQueryRequest, inspectorserver::InspectorServerRequest, and suggestserver::SuggestServerRequest.
Referenced by Handle().
void fastcgiserver::FastCGIRequest::LogRequest () [private]
Definition at line 54 of file FastCGIRequest.cpp.
References cookies, DumpParameters(), GetClientAddress(), log::Logging::GetLogLevel(), getParameters, log::Logging::Log(), log::Logging::LOGLEVEL_INFO, postParameters, requestUri, and userAgent.
Referenced by Handle().
void fastcgiserver::FastCGIRequest::DumpParameters (std::stringstream & ssIn, const std::vector< std::pair< std::string, std::string > > & params) [private]
Definition at line 78 of file FastCGIRequest.cpp.
Referenced by LogRequest().
bool fastcgiserver::FastCGIRequest::ReadPostData (FCGX_Request & request) [private]
Definition at line 85 of file FastCGIRequest.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_WARN, ParseCookies(), rawPostData, SafeGetEnv(), STDIN_MAX, and tools::StringTools::ToLowerIP().
Referenced by Handle().
void fastcgiserver::FastCGIRequest::ParseCookies (std::string cookieString) [private]
Definition at line 220 of file FastCGIRequest.cpp.
References cookies, network::HttpCookie::FromString(), log::Logging::Log(), log::Logging::LOGLEVEL_WARN, and tools::StringTools::SplitBy().
Referenced by ReadPostData().
void fastcgiserver::FastCGIRequest::SplitArguments (char * pszArguments, std::vector< std::pair< std::string, std::string > > & arguments) [static, private]
Definition at line 165 of file FastCGIRequest.cpp.
References tools::StringTools::ToLowerNP().
Referenced by Handle().
std::string fastcgiserver::FastCGIRequest::SafeGetEnv (const char * name, FCGX_Request & request) [static, private]
Definition at line 210 of file FastCGIRequest.cpp.
Referenced by Handle(), and ReadPostData().
Member Data Documentation
char* fastcgiserver::FastCGIRequest::rawPostData [protected]
buffer to raw post data.
Definition at line 168 of file FastCGIRequest.h.
Referenced by Handle(), suggestserver::SuggestServerRequest::OnHandle(), inspectorserver::InspectorServerRequest::OnHandle(), queryserver::XMLQueryRequest::OnHandle(), ReadPostData(), and ~FastCGIRequest().
char* fastcgiserver::FastCGIRequest::rawQueryString [protected]
buffer to raw get data.
Definition at line 173 of file FastCGIRequest.h.
Referenced by Handle().
std::vector<std::pair<std::string,std::string> > fastcgiserver::FastCGIRequest::postParameters [protected]
parsed post parameters.
Definition at line 178 of file FastCGIRequest.h.
Referenced by Handle(), and LogRequest().
std::vector<std::pair<std::string,std::string> > fastcgiserver::FastCGIRequest::getParameters [protected]
parsed get parameters.
Definition at line 183 of file FastCGIRequest.h.
Referenced by Handle(), and LogRequest().
bool fastcgiserver::FastCGIRequest::completed [private]
Definition at line 186 of file FastCGIRequest.h.
Referenced by Handle(), and IsComplete().
const unsigned long fastcgiserver::FastCGIRequest::STDIN_MAX [private]
Definition at line 187 of file FastCGIRequest.h.
Referenced by ReadPostData().
FastCGIServerThread* fastcgiserver::FastCGIRequest::serverThread [private]
Definition at line 188 of file FastCGIRequest.h.
Referenced by ServerThread().
std::vector<network::HttpCookie> fastcgiserver::FastCGIRequest::cookies [private]
Definition at line 189 of file FastCGIRequest.h.
Referenced by Cookies(), LogRequest(), and ParseCookies().
std::string fastcgiserver::FastCGIRequest::clientIP [private]
Definition at line 191 of file FastCGIRequest.h.
Referenced by GetClientAddress(), and Handle().
std::string fastcgiserver::FastCGIRequest::clientPort [private]
Definition at line 192 of file FastCGIRequest.h.
Referenced by GetClientAddress(), and Handle().
std::string fastcgiserver::FastCGIRequest::requestUri [private]
Definition at line 193 of file FastCGIRequest.h.
Referenced by Handle(), LogRequest(), and RequestURI().
std::string fastcgiserver::FastCGIRequest::userAgent [private]
Definition at line 194 of file FastCGIRequest.h.
Referenced by Handle(), LogRequest(), and UserAgent().
The documentation for this class was generated from the following files:
FastCGIServer/src/FastCGIRequest.h
FastCGIServer/src/FastCGIRequest.cpp