DeepNet: tools::StringTools Class Reference
tools::StringTools Class Reference
string manipulation class
#include <StringTools.h>
Static Public Member Functions
static void ReplaceString (const std::string &oldstr, const std::string &newstr, std::string &target)
replaces occurances of patterns in string
static void RemoveEmptyLines (std::vector< std::string > &fileContent)
removes empty lines from a list of lines.
static void Trim (std::string &s)
trims string in place.
static void LeftTrim (std::string &s)
trims string on left side.
static void RightTrim (std::string &s)
trims string on right side.
static std::string & ToLowerIP (std::string &s)
lowers string in place.
static std::string ToLowerNP (const std::string &s)
lowers string.
static void RemoveComments (std::vector< std::string > &fileContent)
removes comments from a list of lines (lines beginning with #)
static void SplitBy (const std::string &text, const std::string &separators, std::vector< std::string > &words)
splits a string by a separator.
static void FormatVAString (std::string &outString, const char *fmt, va_list &ap)
creates a formated string.
static void FormatString (std::string &outString, const char *fmt,...)
creates a formated string.
static bool IsNumeric (const std::string &in)
checks if a string is numeric.
static int ExecuteCommand (const std::string &cmd, std::string &output, const int maxOutputSize=1024)
executes command saving it's output.
template<class T >
static void VectorToString (const std::vector< T > &vecIn, std::string &out, const char *separator=0)
converts generic vector to a string.
template<class T >
static void VectorToString (const std::vector< T > &vecIn, const std::string &prefix, const std::string &postfix, std::string &out)
converts generic vector to a string.
template<class T >
static bool TransformString (const std::string &in, T &out)
converts string to generic type.
template<class T >
static std::string TransformString (const T &in)
converts generic type to a string.
static bool TransformHexString (const std::string &in, unsigned int &out)
transform a string containing hex values to a numeric value.
template<class T >
static bool TransformHexString (const std::string &in, T &out)
transform a string containing hex values to a generic value.
static std::string TransformHexString (const unsigned int &in)
transform a numeric value to a hex string.
template<class T >
static std::string TransformHexString (const T &in)
transform a generic value to a hex string.
static bool IsOneOf (const std::string &comp, const char **choice)
checks if comp is one of the strings in choice.
template<class T >
static unsigned int LevenshteinDistance (const T &s1, const T &s2)
calculates levenshtein distance of to words
Private Member Functions
StringTools ()
virtual ~StringTools ()
Detailed Description
string manipulation class
Definition at line 20 of file StringTools.h.
Constructor & Destructor Documentation
tools::StringTools::StringTools () [private]
Definition at line 19 of file StringTools.cpp.
tools::StringTools::~StringTools () [private, virtual]
Definition at line 23 of file StringTools.cpp.
Member Function Documentation
void tools::StringTools::ReplaceString (const std::string & oldstr, const std::string & newstr, std::string & target) [static]
replaces occurances of patterns in string
Parameters:
oldstr string to be replaced.
newstr string to be replaced by.
target target string.
Definition at line 27 of file StringTools.cpp.
Referenced by indexing::DataminingNotifierEmail::DataminingNotifierEmail(), tools::MimeType::GetCharsetFromMimeString(), tools::FileTools::ReadFile(), RemoveEmptyLines(), domparser::generic::Token::ToString(), and domparser::generic::Token::ToXML().
void tools::StringTools::RemoveEmptyLines (std::vector< std::string > & fileContent) [static]
removes empty lines from a list of lines.
Parameters:
fileContent list of lines.
Definition at line 35 of file StringTools.cpp.
References ReplaceString().
Referenced by caching::RobotTxt::Load(), and RemoveComments().
void tools::StringTools::Trim (std::string & s) [static]
trims string in place.
Parameters:
s string to trim.
Definition at line 51 of file StringTools.cpp.
References LeftTrim(), and RightTrim().
Referenced by libxmlparser::HtmlSAX2Parser::endElement(), tools::MimeType::GetCharsetFromMimeString(), tools::DebuggingTools::GetFileLineFromModuleAddress(), and tools::MimeType::ParseMimeString().
void tools::StringTools::LeftTrim (std::string & s) [static]
trims string on left side.
Parameters:
s string to trim.
Definition at line 57 of file StringTools.cpp.
Referenced by Trim().
void tools::StringTools::RightTrim (std::string & s) [static]
trims string on right side.
Parameters:
s string to trim.
Definition at line 62 of file StringTools.cpp.
Referenced by Trim().
std::string & tools::StringTools::ToLowerIP (std::string & s) [static]
lowers string in place.
Parameters:
s string to lower.
Returns:
lowercase string.
Definition at line 67 of file StringTools.cpp.
Referenced by workerbot::WorkerBot::InitParserConfig(), caching::RobotTxt::Load(), domparser::html5::Tokeniser::OnAfterDoctypeNameState(), and fastcgiserver::FastCGIRequest::ReadPostData().
std::string tools::StringTools::ToLowerNP (const std::string & s) [static]
lowers string.
Parameters:
s string to lower.
Returns:
lowercase string.
Definition at line 74 of file StringTools.cpp.
Referenced by libxmlparser::HtmlSAX2Parser::endElement(), queryserver::XMLQueryResponse::GetPagesByDomain(), fastcgiserver::FastCGIRequest::GetParam(), indexing::IndexerEx::Parse(), network::HttpUrlParser::ParseDomain(), indexing::IndexerEx::ParseMeta(), tools::MimeType::ParseMimeString(), indexing::IndexerThread::ParsePages(), network::HttpUrlParser::ParseScheme(), fastcgiserver::FastCGIRequest::SplitArguments(), and network::HttpUrlParser::ValidateDomain().
void tools::StringTools::RemoveComments (std::vector< std::string > & fileContent) [static]
removes comments from a list of lines (lines beginning with #)
Parameters:
fileContent list of lines.
Definition at line 81 of file StringTools.cpp.
References RemoveEmptyLines().
Referenced by caching::RobotTxt::Load(), and bot::ConfigFile::ParseConfigFile().
void tools::StringTools::SplitBy (const std::string & text, const std::string & separators, std::vector< std::string > & words) [static]
splits a string by a separator.
Parameters:
text string to split.
separators string to split by.
words list of splitted patterns.
Definition at line 97 of file StringTools.cpp.
Referenced by network::HttpUrl::CalculateDomainPart(), tools::DebuggingTools::GetFileLineFromModuleAddress(), fastcgiserver::FastCGIRequest::ParseCookies(), toolbot::UnitTestPCRERegex::ParseExpectedGroups(), and network::HttpUrlParser::ParseQuery().
void tools::StringTools::FormatVAString (std::string & outString, const char * fmt, va_list & ap) [static]
creates a formated string.
Parameters:
outString gets filled with formated string.
fmt format string.
ap va_list.
Definition at line 118 of file StringTools.cpp.
Referenced by libxmlparser::HtmlSAX2Parser::error(), libxmlparser::HtmlSAX2Parser::fatalError(), FormatString(), libxmlparser::HtmlSAX2Parser::genericErrorFunc(), and libxmlparser::HtmlSAX2Parser::warning().
void tools::StringTools::FormatString (std::string & outString, const char * fmt, ...) [static]
creates a formated string.
Parameters:
outString gets filled with formated string.
fmt format string.
Definition at line 111 of file StringTools.cpp.
References FormatVAString().
bool tools::StringTools::IsNumeric (const std::string & in) [static]
checks if a string is numeric.
Parameters:
in string to check.
Returns:
false if not numeric, true if numeric.
Definition at line 491 of file StringTools.cpp.
Referenced by network::HttpUrlParser::ParseDomain().
int tools::StringTools::ExecuteCommand (const std::string & cmd, std::string & output, const int maxOutputSize = 1024) [static]
executes command saving it's output.
Parameters:
cmd command to execute.
output output of command.
maxOutputSize maximum size of output string.
Returns:
return value of command.
Definition at line 464 of file StringTools.cpp.
Referenced by tools::DebuggingTools::GetFileLineFromModuleAddress(), and indexing::DataminingNotifierEmail::OnNotify().
template<class T > static void tools::StringTools::VectorToString (const std::vector< T > & vecIn, std::string & out, const char * separator = 0) [inline, static]
converts generic vector to a string.
Parameters:
vecIn vector to convert.
out output string.
separator NULL for no separator, otherwise separator to use.
Definition at line 126 of file StringTools.h.
Referenced by indexing::Dictionary::DumpXML(), queryserver::XMLQueryResponse::OutputResults(), and network::HttpUrlParser::ParseURL().
template<class T > static void tools::StringTools::VectorToString (const std::vector< T > & vecIn, const std::string & prefix, const std::string & postfix, std::string & out) [inline, static]
converts generic vector to a string.
Parameters:
vecIn vector to convert.
prefix string to put before every item.
postfix string to put after every item.
out output string.
Definition at line 146 of file StringTools.h.
template<class T > static bool tools::StringTools::TransformString (const std::string & in, T & out) [inline, static]
converts string to generic type.
Parameters:
in string to convert.
out output.
Returns:
false on error, true on success.
Definition at line 163 of file StringTools.h.
Referenced by tools::DebuggingTools::GetFileLineFromModuleAddress(), queryserver::XMLQueryRequest::ParseQueryCriteria(), queryserver::XMLQueryRequest::ParseQueryGrouping(), queryserver::XMLQueryRequest::ParseQueryLimitations(), and network::IPv4Tools::ToString().
template<class T > static std::string tools::StringTools::TransformString (const T & in) [inline, static]
converts generic type to a string.
Parameters:
in string to convert.
Returns:
converted string.
Definition at line 177 of file StringTools.h.
static bool tools::StringTools::TransformHexString (const std::string & in, unsigned int & out) [inline, static]
transform a string containing hex values to a numeric value.
Parameters:
in string to convert.
out converted value.
Returns:
false on error, true on success.
Definition at line 192 of file StringTools.h.
template<class T > static bool tools::StringTools::TransformHexString (const std::string & in, T & out) [inline, static]
transform a string containing hex values to a generic value.
Parameters:
in string to convert.
out converted value.
Returns:
false on error, true on success.
Definition at line 206 of file StringTools.h.
static std::string tools::StringTools::TransformHexString (const unsigned int & in) [inline, static]
transform a numeric value to a hex string.
Parameters:
in value to convert.
Returns:
converted string.
Definition at line 220 of file StringTools.h.
template<class T > static std::string tools::StringTools::TransformHexString (const T & in) [inline, static]
transform a generic value to a hex string.
Parameters:
in value to convert.
Returns:
converted string.
Definition at line 236 of file StringTools.h.
static bool tools::StringTools::IsOneOf (const std::string & comp, const char ** choice) [inline, static]
checks if comp is one of the strings in choice.
use this function only with care.
Parameters:
comp string to compare
choice string to compare to (NEEDS TO BE ZERO TERMINATED)
Returns:
true if in choice, false if not
Definition at line 253 of file StringTools.h.
Referenced by domparser::DocumentFactory::OnAfterHeadInsertion(), domparser::DocumentFactory::OnBeforeHeadInsertion(), domparser::DocumentFactory::OnBeforeHtmlInsertion(), domparser::DocumentFactory::OnInBodyEndTagInsertion(), domparser::DocumentFactory::OnInBodyStartTagInsertion(), domparser::DocumentFactory::OnInHeadInsertion(), and domparser::DocumentFactory::OnInHeadNoscriptInsertion().
template<class T > static unsigned int tools::StringTools::LevenshteinDistance (const T & s1, const T & s2) [inline, static]
calculates levenshtein distance of to words
See also:
http://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#C.2B.2B
Parameters:
s1 string 1
s2 string 2
Returns:
levenshtein distance
Definition at line 278 of file StringTools.h.
The documentation for this class was generated from the following files:
Tools/src/StringTools.h
Tools/src/StringTools.cpp