DeepNet: database::SelectResultContainer< T > Class Template Reference
database::SelectResultContainer< T > Class Template Reference
container for results of SELECT statements.
#include <SelectResultContainer.h>
Public Member Functions
SelectResultContainer ()
virtual ~SelectResultContainer ()
void Add (T *entry)
adds an entry.
void Add (const std::vector< T * > &entries)
adds multiple entries entry.
void ResetIter () const
resets iterator.
bool IsIterEnd () const
checks if iterator is at end.
T * GetIter ()
gets current iterator.
const T *const GetConstIter () const
gets current iterator as const.
void Next () const
increment iterator.
std::vector< T * > & GetVector ()
gets vector of entries.
size_t Size () const
gets current container size.
Private Member Functions
SelectResultContainer (const SelectResultContainer< T > &copy)
Detailed Description
template<class T>
class database::SelectResultContainer< T >
container for results of SELECT statements.
this container normally contains database::TableBase or classes derived from it.
Definition at line 19 of file SelectResultContainer.h.
Constructor & Destructor Documentation
template<class T> database::SelectResultContainer< T >::SelectResultContainer (const SelectResultContainer< T > & copy) [inline, private]
Definition at line 21 of file SelectResultContainer.h.
template<class T> database::SelectResultContainer< T >::SelectResultContainer () [inline]
Definition at line 24 of file SelectResultContainer.h.
template<class T> virtual database::SelectResultContainer< T >::~SelectResultContainer () [inline, virtual]
Definition at line 25 of file SelectResultContainer.h.
Member Function Documentation
template<class T> void tools::PointerContainer< T >::Add (T * entry) [inline, inherited]
adds an entry.
Parameters:
entry entry to add.
Definition at line 39 of file PointerContainer.h.
Referenced by database::WhereCondition::AddColumn(), database::WhereCondition::AddColumns(), database::WhereConditionTableColumn::CreateInstance(), and database::DatabaseConnection::Select().
template<class T> void tools::PointerContainer< T >::Add (const std::vector< T * > & entries) [inline, inherited]
adds multiple entries entry.
Parameters:
entries entries to add.
Definition at line 47 of file PointerContainer.h.
template<class T> void tools::PointerContainer< T >::ResetIter () const [inline, inherited]
resets iterator.
Definition at line 54 of file PointerContainer.h.
Referenced by tools::PointerContainer< WhereConditionTableColumn >::Add(), crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), htmlparser::DatabaseUrl::InitByUrlID(), parser::CommerceSearchParserThread::InitParserThread(), tools::PointerContainer< WhereConditionTableColumn >::PointerContainer(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> bool tools::PointerContainer< T >::IsIterEnd () const [inline, inherited]
checks if iterator is at end.
Returns:
false if not at end, true if at end.
Definition at line 61 of file PointerContainer.h.
Referenced by crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), parser::CommerceSearchParserThread::InitParserThread(), tools::PointerContainer< WhereConditionTableColumn >::Next(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> T* tools::PointerContainer< T >::GetIter () [inline, inherited]
gets current iterator.
Returns:
current iterator
Definition at line 68 of file PointerContainer.h.
Referenced by crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), htmlparser::DatabaseUrl::InitByUrlID(), parser::CommerceSearchParserThread::InitParserThread(), queryserver::XMLQueryResponse::ProcessExistQuery(), toolbot::DataMiningTools::RegisterDataminingAlert(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> const T* const tools::PointerContainer< T >::GetConstIter () const [inline, inherited]
gets current iterator as const.
Returns:
current iterator
Definition at line 75 of file PointerContainer.h.
Referenced by database::WhereConditionTableColumn::ToString(), and database::WhereCondition::ToString().
template<class T> void tools::PointerContainer< T >::Next () const [inline, inherited]
increment iterator.
Definition at line 81 of file PointerContainer.h.
Referenced by crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), parser::CommerceSearchParserThread::InitParserThread(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> std::vector<T*>& tools::PointerContainer< T >::GetVector () [inline, inherited]
gets vector of entries.
Returns:
raw vector of entries.
Definition at line 90 of file PointerContainer.h.
Referenced by parser::CommerceSearchParserThread::OnAfterParsePage().
template<class T> size_t tools::PointerContainer< T >::Size () const [inline, inherited]
gets current container size.
Returns:
current container size.
Definition at line 97 of file PointerContainer.h.
Referenced by caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::DatabaseUrl::InitByUrlID(), queryserver::XMLQueryResponse::ProcessExistQuery(), toolbot::DataMiningTools::RegisterDataminingAlert(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
The documentation for this class was generated from the following file:
Database/src/SelectResultContainer.h