DeepNet: domparser::ListImpl< T > Class Template Reference
domparser::ListImpl< T > Class Template Reference
generic list implementation for DOM parsing subsystem
#include <ListImpl.h>
Public Member Functions
virtual ~ListImpl ()
virtual T * GetItem (unsigned long index)
gets an item by it's index
virtual unsigned long GetLength () const
gets the number of items in this list
void RemoveItem (T *del)
removes an item
void AppendItem (T *append)
appends an item to this list
void AppendItems (const std::vector< T * > &in)
appends multiple items to this list
Protected Member Functions
ListImpl ()
creates an empty typed list
ListImpl (const std::vector< T * > &in)
creates a prefilled list
ListImpl (T *in)
creates a list prefilled with one item
Private Attributes
std::vector< T * > items
Detailed Description
template<class T>
class domparser::ListImpl< T >
generic list implementation for DOM parsing subsystem
Definition at line 22 of file ListImpl.h.
Constructor & Destructor Documentation
template<class T> domparser::ListImpl< T >::ListImpl () [inline, protected]
creates an empty typed list
Definition at line 28 of file ListImpl.h.
template<class T> domparser::ListImpl< T >::ListImpl (const std::vector< T * > & in) [inline, protected]
creates a prefilled list
Parameters:
in list to insert in the beginning
Definition at line 36 of file ListImpl.h.
template<class T> domparser::ListImpl< T >::ListImpl (T * in) [inline, protected]
creates a list prefilled with one item
Parameters:
in item to insert in the beginning
Definition at line 44 of file ListImpl.h.
template<class T> virtual domparser::ListImpl< T >::~ListImpl () [inline, virtual]
Definition at line 49 of file ListImpl.h.
Member Function Documentation
template<class T> virtual T* domparser::ListImpl< T >::GetItem (unsigned long index) [inline, virtual]
gets an item by it's index
Parameters:
index index of the item to get
Returns:
item in list or null
Definition at line 56 of file ListImpl.h.
Referenced by domparser::Range::ComparePoints(), domparser::Range::selectNode(), domparser::Range::setEndAfter(), domparser::Range::setEndBefore(), domparser::Range::setStartAfter(), domparser::Range::setStartBefore(), and domparser::TreeWalker::TraverseChildrenSubstep().
template<class T> virtual unsigned long domparser::ListImpl< T >::GetLength () const [inline, virtual]
gets the number of items in this list
Returns:
number of items
Definition at line 66 of file ListImpl.h.
Referenced by domparser::Range::comparePoint(), domparser::Range::ComparePoints(), domparser::Node::doGetChildIdx(), domparser::Node::doInsert(), domparser::Node::hasChildNodes(), domparser::TreeWalker::NextNodeSubstep(), domparser::TreeWalker::previousNode(), domparser::Range::selectNode(), domparser::Range::selectNodeContents(), domparser::Range::SetBoundaryPoint(), domparser::Range::setEndAfter(), domparser::Range::setEndBefore(), domparser::Range::setStartAfter(), domparser::Range::setStartBefore(), and domparser::TreeWalker::TraverseChildrenSubstep().
template<class T> void domparser::ListImpl< T >::RemoveItem (T * del) [inline]
removes an item
Parameters:
del item to delete
Definition at line 72 of file ListImpl.h.
Referenced by domparser::Node::doRemoveChild().
template<class T> void domparser::ListImpl< T >::AppendItem (T * append) [inline]
appends an item to this list
Parameters:
append item to append
Definition at line 82 of file ListImpl.h.
Referenced by domparser::Node::doRemoveChild().
template<class T> void domparser::ListImpl< T >::AppendItems (const std::vector< T * > & in) [inline]
appends multiple items to this list
Parameters:
in items to append
Definition at line 90 of file ListImpl.h.
Member Data Documentation
template<class T> std::vector<T*> domparser::ListImpl< T >::items [private]
Definition at line 95 of file ListImpl.h.
Referenced by domparser::ListImpl< Element >::AppendItem(), domparser::ListImpl< Element >::AppendItems(), domparser::ListImpl< Element >::GetItem(), domparser::ListImpl< Element >::GetLength(), domparser::ListImpl< Element >::ListImpl(), and domparser::ListImpl< Element >::RemoveItem().
The documentation for this class was generated from the following file:
DOMParser/src/ListImpl.h