DeepNet: database::InnerJoinCondition Class Reference
database::InnerJoinCondition Class Reference
implements generic sql "INNER JOIN" parts.
#include <InnerJoinCondition.h>
Public Member Functions
InnerJoinCondition ()
virtual ~InnerJoinCondition ()
void AddInnerJoin (database::TableDefinition *joinTableDef, database::TableColumnDefinition *joinColumnDef, database::TableDefinition *referencedTableDef, database::TableColumnDefinition *referencedColumnDef)
adds an inner join.
void AddInnerJoin (database::TableDefinition *joinTableDef, database::TableColumnDefinition *joinColumnDef, database::TableDefinition *referencedTableDef, database::TableColumnDefinition *referencedColumnDef, const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnsAlias)
adds an inner join using aliases for both tables.
void AddInnerJoin (const InnerJoinEntry &entry)
adds an inner join.
std::string ToString (DatabaseConnection *db) const
gets sql equivalent of this inner join part containing all added inner join entries.
Private Attributes
std::vector< InnerJoinEntry > entries
Detailed Description
implements generic sql "INNER JOIN" parts.
implements generic sql "INNER JOIN" parts for sql statements.
Definition at line 24 of file InnerJoinCondition.h.
Constructor & Destructor Documentation
database::InnerJoinCondition::InnerJoinCondition ()
Definition at line 16 of file InnerJoinCondition.cpp.
database::InnerJoinCondition::~InnerJoinCondition () [virtual]
Definition at line 20 of file InnerJoinCondition.cpp.
References entries.
Member Function Documentation
void database::InnerJoinCondition::AddInnerJoin (database::TableDefinition * joinTableDef, database::TableColumnDefinition * joinColumnDef, database::TableDefinition * referencedTableDef, database::TableColumnDefinition * referencedColumnDef)
adds an inner join.
i.e. "INNER JOIN joinTableDef ON joinTableDef.joinTableColumn = referencedTableDef.referencedColumnDef"
Parameters:
joinTableDef table definition for table that should be joined.
joinColumnDef column definition for table column that should be joined.
referencedTableDef table definition for table that should be used as reference.
referencedColumnDef column definition for table column that should be used as reference.
Definition at line 30 of file InnerJoinCondition.cpp.
Referenced by database::customersessionsTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::dataminingblacklistTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::fencedsearchTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::customerdomainsTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::customerqueriesTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::AddInnerJoinLeftSideOn_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinLeftSideOn_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinLeftSideOn_DATAMININGCRITERIA_ID(), database::docurlTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::customerproductkeywordsTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::dockeyTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::docmetaTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::dockeyposTableBase::AddInnerJoinLeftSideOn_DOCKEY_ID(), database::imagelinksTableBase::AddInnerJoinLeftSideOn_IMAGE_URL_ID(), database::searchquerykeywordsTableBase::AddInnerJoinLeftSideOn_KEYWORDQUERY_ID(), database::customermatchcriteriaTableBase::AddInnerJoinLeftSideOn_MATCHCRITERIA_ID(), database::customerproducturlsTableBase::AddInnerJoinLeftSideOn_PRODUCT_ID(), database::customerproductimagesTableBase::AddInnerJoinLeftSideOn_PRODUCT_ID(), database::customerproductkeywordsTableBase::AddInnerJoinLeftSideOn_PRODUCT_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_SCHEME_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_SCHEME_ID(), database::searchquerykeywordsTableBase::AddInnerJoinLeftSideOn_SEARCHQUERY_ID(), database::queryresultsTableBase::AddInnerJoinLeftSideOn_SEARCHQUERY_ID(), database::fencedsearchTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), database::imagelinksTableBase::AddInnerJoinLeftSideOn_TARGET_URL_ID(), database::hyperlinksTableBase::AddInnerJoinLeftSideOn_TARGET_URL_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::customersyncurlTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::customerproducturlsTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::docurlTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::syncurlsTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::urlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::documentcodeTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::metainfoTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::hyperlinksTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::dockeyTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::imagelinksTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::docmetaTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::dataminingblacklistTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::customersessionsTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::fencedsearchTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::customerdomainsTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::customerqueriesTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::AddInnerJoinRightSideOn_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinRightSideOn_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinRightSideOn_DATAMININGCRITERIA_ID(), database::docurlTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::customerproductkeywordsTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::dockeyTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::docmetaTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::dockeyposTableBase::AddInnerJoinRightSideOn_DOCKEY_ID(), database::imagelinksTableBase::AddInnerJoinRightSideOn_IMAGE_URL_ID(), database::searchquerykeywordsTableBase::AddInnerJoinRightSideOn_KEYWORDQUERY_ID(), database::customermatchcriteriaTableBase::AddInnerJoinRightSideOn_MATCHCRITERIA_ID(), database::customerproductkeywordsTableBase::AddInnerJoinRightSideOn_PRODUCT_ID(), database::customerproducturlsTableBase::AddInnerJoinRightSideOn_PRODUCT_ID(), database::customerproductimagesTableBase::AddInnerJoinRightSideOn_PRODUCT_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_SCHEME_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_SCHEME_ID(), database::searchquerykeywordsTableBase::AddInnerJoinRightSideOn_SEARCHQUERY_ID(), database::queryresultsTableBase::AddInnerJoinRightSideOn_SEARCHQUERY_ID(), database::fencedsearchTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_SUBDOMAIN_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_SUBDOMAIN_ID(), database::hyperlinksTableBase::AddInnerJoinRightSideOn_TARGET_URL_ID(), database::imagelinksTableBase::AddInnerJoinRightSideOn_TARGET_URL_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), database::latesturlstagesTableBase::AddInnerJoinRightSideOn_URL_ID(), database::customersyncurlTableBase::AddInnerJoinRightSideOn_URL_ID(), database::docurlTableBase::AddInnerJoinRightSideOn_URL_ID(), database::customerproducturlsTableBase::AddInnerJoinRightSideOn_URL_ID(), database::syncurlsTableBase::AddInnerJoinRightSideOn_URL_ID(), database::urlstagesTableBase::AddInnerJoinRightSideOn_URL_ID(), database::documentcodeTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::latesturlstagesTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::metainfoTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::hyperlinksTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::dockeyTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::imagelinksTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), and database::docmetaTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID().
void database::InnerJoinCondition::AddInnerJoin (database::TableDefinition * joinTableDef, database::TableColumnDefinition * joinColumnDef, database::TableDefinition * referencedTableDef, database::TableColumnDefinition * referencedColumnDef, const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnsAlias)
adds an inner join using aliases for both tables.
i.e. "INNER JOIN joinTableDef ON joinTableDef.joinTableColumn = referencedTableDef.referencedColumnDef"
Parameters:
joinTableDef table definition for table that should be joined.
joinColumnDef column definition for table column that should be joined.
referencedTableDef table definition for table that should be used as reference.
referencedColumnDef column definition for table column that should be used as reference.
joinTableAlias alias of joined table.
joinColumnAlias alias of joined table column.
referencedTableAlias alias of referenced table.
referencedColumnsAlias alias of referenced table column.
Definition at line 39 of file InnerJoinCondition.cpp.
References entries, database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
void database::InnerJoinCondition::AddInnerJoin (const InnerJoinEntry & entry) [inline]
adds an inner join.
Parameters:
entry prepared inner join entry.
Definition at line 70 of file InnerJoinCondition.h.
References entries.
std::string database::InnerJoinCondition::ToString (DatabaseConnection * db) const
gets sql equivalent of this inner join part containing all added inner join entries.
Parameters:
db database connection.
Returns:
sql string.
Definition at line 59 of file InnerJoinCondition.cpp.
References entries.
Referenced by database::SelectStatement::ToSQL().
Member Data Documentation
std::vector<InnerJoinEntry> database::InnerJoinCondition::entries [private]
Definition at line 80 of file InnerJoinCondition.h.
Referenced by AddInnerJoin(), ToString(), and ~InnerJoinCondition().
The documentation for this class was generated from the following files:
Database/src/InnerJoinCondition.h
Database/src/InnerJoinCondition.cpp