DeepNet: queryserver::XMLQueryRequest Class Reference
queryserver::XMLQueryRequest Class Reference
#include <XMLQueryRequest.h>
Classes
class QueryRequestParam
Public Types
enum QueryCriteriaFlag {
CRITERIA_UNKNOWN = 0, CRITERIA_ALL = 1, CRITERIA_META = 2, CRITERIA_TITLE = 4,
CRITERIA_DOMAIN = 16, CRITERIA_CONTENT = 32, CRITERIA_LINKS = 64, CRITERIA_PATH = 128,
CRITERIA_MAX = 0xFF
}
enum QueryGroupingFlag {
GROUPING_UNKNOWN = 0, GROUPING_DOMAIN = 1, GROUPING_PATH = 2, GROUPING_FILE = 4,
GROUPING_MAX = 0xFF
}
enum QueryLimitationsFlag {
LIMITATION_UNKNOWN = 0, LIMITATION_DOMAIN = 1, LIMITATION_AGE = 2, LIMITATION_LANG = 4,
LIMITATION_MAX = 0xFF
}
Public Member Functions
XMLQueryRequest (fastcgiserver::FastCGIServerThread *serverThread)
virtual ~XMLQueryRequest ()
virtual void OnHandle (FCGX_Request &request)
const std::list< std::string > & QueryParts ()
const QueryRequestParam & Params () const
QueryRequestParam & Params ()
void Handle (FCGX_Request &request)
handles a request.
bool IsComplete () const
checks if request completed.
template<class T >
bool GetParam (FCGX_Request &request, const std::string &key, T &value)
gets converted value from fastcgi request parameters.
bool GetParam (FCGX_Request &request, const std::string &key, std::string &value)
gets parameter from fastcgi request.
std::string GetClientAddress () const
gets connected endpoint as string.
FastCGIServerThread * ServerThread ()
gets originating server thread.
const std::string & UserAgent () const
gets client's user agent.
const std::string & RequestURI () const
gets requested uri.
const std::vector
< network::HttpCookie > & Cookies () const
gets cookies from current request.
Protected Member Functions
int register_namespaces (xmlXPathContextPtr xpathCtx, const xmlChar *nsList)
registers namespaces from nsList in xpathCtx.
bool Xpath (std::list< std::string > &queryparts, const char *filename, const xmlChar *xpathExpr, const xmlChar *nsList=0)
gets xpath from request contents (if contents are XML).
bool Validate (const std::string &xsdString, xmlDocPtr doc)
validates xml document against xsd.
Protected Attributes
char * rawPostData
buffer to raw post data.
char * rawQueryString
buffer to raw get data.
std::vector< std::pair
< std::string, std::string > > postParameters
parsed post parameters.
std::vector< std::pair
< std::string, std::string > > getParameters
parsed get parameters.
Private Member Functions
bool ParseQuery (const std::string &xmlRequest, QueryRequestParam &out)
bool ParseQueryCriteria (const std::string &xmlRequest, QueryRequestParam &out)
bool ParseQueryGrouping (const std::string &xmlRequest, QueryRequestParam &out)
bool ParseQueryLimitations (const std::string &xmlRequest, QueryRequestParam &out)
Private Attributes
QueryRequestParam queryRequestParam
Detailed Description
Definition at line 14 of file XMLQueryRequest.h.
Member Enumeration Documentation
enum queryserver::XMLQueryRequest::QueryCriteriaFlag
Enumerator:
CRITERIA_UNKNOWN
CRITERIA_ALL
CRITERIA_META
CRITERIA_TITLE
CRITERIA_DOMAIN
CRITERIA_CONTENT
CRITERIA_LINKS
CRITERIA_PATH
CRITERIA_MAX
Definition at line 17 of file XMLQueryRequest.h.
enum queryserver::XMLQueryRequest::QueryGroupingFlag
Enumerator:
GROUPING_UNKNOWN
GROUPING_DOMAIN
GROUPING_PATH
GROUPING_FILE
GROUPING_MAX
Definition at line 32 of file XMLQueryRequest.h.
enum queryserver::XMLQueryRequest::QueryLimitationsFlag
Enumerator:
LIMITATION_UNKNOWN
LIMITATION_DOMAIN
LIMITATION_AGE
LIMITATION_LANG
LIMITATION_MAX
Definition at line 43 of file XMLQueryRequest.h.
Constructor & Destructor Documentation
queryserver::XMLQueryRequest::XMLQueryRequest (fastcgiserver::FastCGIServerThread * serverThread)
Definition at line 15 of file XMLQueryRequest.cpp.
queryserver::XMLQueryRequest::~XMLQueryRequest () [virtual]
Definition at line 20 of file XMLQueryRequest.cpp.
Member Function Documentation
void queryserver::XMLQueryRequest::OnHandle (FCGX_Request & request) [virtual]
Implements fastcgiserver::FastCGIRequest.
Definition at line 24 of file XMLQueryRequest.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_WARN, ParseQuery(), queryRequestParam, and fastcgiserver::FastCGIRequest::rawPostData.
const std::list<std::string>& queryserver::XMLQueryRequest::QueryParts () [inline]
Definition at line 123 of file XMLQueryRequest.h.
References queryserver::XMLQueryRequest::QueryRequestParam::queryParts, and queryRequestParam.
Referenced by queryserver::XMLQueryResponse::Process().
const QueryRequestParam& queryserver::XMLQueryRequest::Params () const [inline]
Definition at line 128 of file XMLQueryRequest.h.
References queryRequestParam.
Referenced by queryserver::XMLQueryResponse::GetPageRelevanceByBacklinks(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetResultsFromDatasources(), queryserver::XMLQueryResponse::GroupResults(), queryserver::XMLQueryResponse::LogQuery(), queryserver::XMLQueryResponse::OutputResults(), queryserver::XMLQueryResponse::ProcessExistQuery(), and queryserver::XMLQueryResponse::SaveResults().
QueryRequestParam& queryserver::XMLQueryRequest::Params () [inline]
Definition at line 129 of file XMLQueryRequest.h.
References queryRequestParam.
bool queryserver::XMLQueryRequest::ParseQuery (const std::string & xmlRequest, QueryRequestParam & out) [private]
Definition at line 202 of file XMLQueryRequest.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::QueryRequestParam::pageNo, ParseQueryCriteria(), ParseQueryGrouping(), ParseQueryLimitations(), queryserver::XMLQueryRequest::QueryRequestParam::queryID, queryserver::XMLQueryRequest::QueryRequestParam::queryParts, and fastcgiserver::FastCGIRequest::Xpath().
Referenced by OnHandle().
bool queryserver::XMLQueryRequest::ParseQueryCriteria (const std::string & xmlRequest, QueryRequestParam & out) [private]
Definition at line 65 of file XMLQueryRequest.cpp.
References CRITERIA_ALL, CRITERIA_CONTENT, CRITERIA_DOMAIN, CRITERIA_LINKS, CRITERIA_META, CRITERIA_PATH, CRITERIA_TITLE, queryserver::XMLQueryRequest::QueryRequestParam::criteriaFlag, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::QueryRequestParam::relevanceBackLinks, queryserver::XMLQueryRequest::QueryRequestParam::relevanceDomain, queryserver::XMLQueryRequest::QueryRequestParam::relevanceFullText, queryserver::XMLQueryRequest::QueryRequestParam::relevanceMeta, queryserver::XMLQueryRequest::QueryRequestParam::relevanceTitle, queryserver::XMLQueryRequest::QueryRequestParam::relevanceUrlPath, tools::StringTools::TransformString(), and fastcgiserver::FastCGIRequest::Xpath().
Referenced by ParseQuery().
bool queryserver::XMLQueryRequest::ParseQueryGrouping (const std::string & xmlRequest, QueryRequestParam & out) [private]
Definition at line 35 of file XMLQueryRequest.cpp.
References queryserver::XMLQueryRequest::QueryRequestParam::groupFlag, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::StringTools::TransformString(), and fastcgiserver::FastCGIRequest::Xpath().
Referenced by ParseQuery().
bool queryserver::XMLQueryRequest::ParseQueryLimitations (const std::string & xmlRequest, QueryRequestParam & out) [private]
Definition at line 150 of file XMLQueryRequest.cpp.
References queryserver::XMLQueryRequest::QueryRequestParam::limitAge, LIMITATION_AGE, LIMITATION_DOMAIN, LIMITATION_LANG, queryserver::XMLQueryRequest::QueryRequestParam::limitDomain, queryserver::XMLQueryRequest::QueryRequestParam::limitFlag, queryserver::XMLQueryRequest::QueryRequestParam::limitLang, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::QueryRequestParam::maxResults, tools::StringTools::TransformString(), and fastcgiserver::FastCGIRequest::Xpath().
Referenced by ParseQuery().
void fastcgiserver::FastCGIRequest::Handle (FCGX_Request & request) [inherited]
handles a request.
Parameters:
request raw fastcgi request.
Definition at line 33 of file FastCGIRequest.cpp.
References fastcgiserver::FastCGIRequest::clientIP, fastcgiserver::FastCGIRequest::clientPort, fastcgiserver::FastCGIRequest::completed, fastcgiserver::FastCGIRequest::GetParam(), fastcgiserver::FastCGIRequest::getParameters, fastcgiserver::FastCGIRequest::LogRequest(), fastcgiserver::FastCGIRequest::OnHandle(), fastcgiserver::FastCGIRequest::postParameters, fastcgiserver::FastCGIRequest::rawPostData, fastcgiserver::FastCGIRequest::rawQueryString, fastcgiserver::FastCGIRequest::ReadPostData(), fastcgiserver::FastCGIRequest::requestUri, fastcgiserver::FastCGIRequest::SafeGetEnv(), fastcgiserver::FastCGIRequest::SplitArguments(), and fastcgiserver::FastCGIRequest::userAgent.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
bool fastcgiserver::FastCGIRequest::IsComplete () const [inline, inherited]
checks if request completed.
Returns:
false if not completed, true if completed.
Definition at line 54 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::completed.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
template<class T > bool fastcgiserver::FastCGIRequest::GetParam (FCGX_Request & request, const std::string & key, T & value) [inline, inherited]
gets converted value from fastcgi request parameters.
Parameters:
request raw fastcgi request.
key keyname of parameter.
value gets filled with value of key.
Returns:
false if key does not exists, true if it does.
Definition at line 65 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle().
bool fastcgiserver::FastCGIRequest::GetParam (FCGX_Request & request, const std::string & key, std::string & value) [inline, inherited]
gets parameter from fastcgi request.
Parameters:
request raw fastcgi request.
key keyname of parameter.
value gets filled with value of key
Returns:
false if key does not exists, true if it does.
Definition at line 86 of file FastCGIRequest.h.
References tools::StringTools::ToLowerNP().
std::string fastcgiserver::FastCGIRequest::GetClientAddress () const [inline, inherited]
gets connected endpoint as string.
Returns:
connected endpoint as string.
Definition at line 101 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::clientIP, and fastcgiserver::FastCGIRequest::clientPort.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), and fastcgiserver::FastCGIRequest::LogRequest().
FastCGIServerThread* fastcgiserver::FastCGIRequest::ServerThread () [inline, inherited]
gets originating server thread.
Returns:
originating server thread.
Definition at line 107 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::serverThread.
Referenced by suggestserver::SuggestServerResponse::Process().
const std::string& fastcgiserver::FastCGIRequest::UserAgent () const [inline, inherited]
gets client's user agent.
Returns:
client's user agent.
Definition at line 113 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::userAgent.
const std::string& fastcgiserver::FastCGIRequest::RequestURI () const [inline, inherited]
gets requested uri.
Returns:
requested uri.
Definition at line 119 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::requestUri.
const std::vector<network::HttpCookie>& fastcgiserver::FastCGIRequest::Cookies () const [inline, inherited]
gets cookies from current request.
Returns:
cookies.
Definition at line 125 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::cookies.
Referenced by queryserver::XMLQueryResponse::LogQuery().
int fastcgiserver::FastCGIRequest::register_namespaces (xmlXPathContextPtr xpathCtx, const xmlChar * nsList) [protected, inherited]
registers namespaces from nsList in xpathCtx.
Parameters:
xpathCtx xpathCtx the pointer to an XPath context.
nsList nsList the list of known namespaces in "<prefix1>=<href1> <prefix2>=href2> ..." format.
Returns:
0 on success and a negative value otherwise.
Definition at line 283 of file FastCGIRequest.cpp.
Referenced by fastcgiserver::FastCGIRequest::Xpath().
bool fastcgiserver::FastCGIRequest::Xpath (std::list< std::string > & queryparts, const char * filename, const xmlChar * xpathExpr, const xmlChar * nsList = 0) [protected, inherited]
gets xpath from request contents (if contents are XML).
Parameters:
queryparts gets filled with xpath results.
filename xml content string for xpath.
xpathExpr xpath expression.
nsList list of allowed namespaces(???).
Returns:
false on error, true on success.
Definition at line 330 of file FastCGIRequest.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, and fastcgiserver::FastCGIRequest::register_namespaces().
Referenced by suggestserver::SuggestServerRequest::OnHandle(), inspectorserver::InspectorServerRequest::OnHandle(), ParseQuery(), ParseQueryCriteria(), ParseQueryGrouping(), and ParseQueryLimitations().
bool fastcgiserver::FastCGIRequest::Validate (const std::string & xsdString, xmlDocPtr doc) [protected, inherited]
validates xml document against xsd.
Parameters:
xsdString string containing xsd.
doc xml document to validate.
Returns:
false on error, true on success.
Definition at line 241 of file FastCGIRequest.cpp.
Member Data Documentation
QueryRequestParam queryserver::XMLQueryRequest::queryRequestParam [private]
Definition at line 138 of file XMLQueryRequest.h.
Referenced by OnHandle(), Params(), and QueryParts().
char* fastcgiserver::FastCGIRequest::rawPostData [protected, inherited]
buffer to raw post data.
Definition at line 168 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle(), suggestserver::SuggestServerRequest::OnHandle(), inspectorserver::InspectorServerRequest::OnHandle(), OnHandle(), fastcgiserver::FastCGIRequest::ReadPostData(), and fastcgiserver::FastCGIRequest::~FastCGIRequest().
char* fastcgiserver::FastCGIRequest::rawQueryString [protected, inherited]
buffer to raw get data.
Definition at line 173 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle().
std::vector<std::pair<std::string,std::string> > fastcgiserver::FastCGIRequest::postParameters [protected, inherited]
parsed post parameters.
Definition at line 178 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle(), and fastcgiserver::FastCGIRequest::LogRequest().
std::vector<std::pair<std::string,std::string> > fastcgiserver::FastCGIRequest::getParameters [protected, inherited]
parsed get parameters.
Definition at line 183 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle(), and fastcgiserver::FastCGIRequest::LogRequest().
The documentation for this class was generated from the following files:
QueryServer/src/XMLQueryRequest.h
QueryServer/src/XMLQueryRequest.cpp