DeepNet: network::HttpClientCURL Class Reference
network::HttpClientCURL Class Reference
#include <HttpClientCURL.h>
Classes
struct _CURLWriterParam
Public Member Functions
virtual ~HttpClientCURL ()
virtual bool Get (const HttpUrl &url, HttpResponse &response)
performs http get request
virtual HttpClientSettings & Settings ()
returns settings of this http client
Private Types
typedef struct
network::HttpClientCURL::_CURLWriterParam CURLWriterParam
Private Member Functions
HttpClientCURL ()
Static Private Member Functions
static int WriterCallback (char *data, size_t size, size_t nmemb, CURLWriterParam *param)
Private Attributes
HttpClientSettings settings
void * curlPtr
char * errorBuffer
Friends
class network::HttpClientFactory
Detailed Description
Definition at line 17 of file HttpClientCURL.h.
Member Typedef Documentation
typedef struct network::HttpClientCURL::_CURLWriterParam network::HttpClientCURL::CURLWriterParam [private]
Constructor & Destructor Documentation
network::HttpClientCURL::HttpClientCURL () [private]
Definition at line 19 of file HttpClientCURL.cpp.
References curlPtr, errorBuffer, and WriterCallback().
network::HttpClientCURL::~HttpClientCURL () [virtual]
Definition at line 32 of file HttpClientCURL.cpp.
References curlPtr.
Member Function Documentation
bool network::HttpClientCURL::Get (const HttpUrl & url, HttpResponse & response) [virtual]
performs http get request
Parameters:
url url to "GET"
response response of http GET
Returns:
true if successful, false if unsuccessful
Implements network::IHttpClient.
Definition at line 39 of file HttpClientCURL.cpp.
References network::HttpResponse::contentLength, network::HtmlData::ConvertToHostCharset(), curlPtr, network::HttpClientSettings::downloadLimitKB, network::HttpResponse::downloadSpeed, errorBuffer, network::HttpResponse::fileTimestamp, tools::MemoryContainer< T >::GetCount(), network::HttpUrl::GetFullUrl(), network::HttpResponse::html, network::HttpResponse::httpResponseCode, log::Logging::IsLogLevelTrace(), log::Logging::LogTrace(), network::HttpResponse::primaryIP, network::HttpResponse::primaryPort, network::HttpResponse::redirectUrls, tools::MemoryContainer< T >::Release(), network::HtmlData::SetContentType(), Settings(), network::HttpResponse::totalTime, network::HttpClientSettings::uploadLimitKB, and network::HttpResponse::uploadSpeed.
virtual HttpClientSettings& network::HttpClientCURL::Settings () [inline, virtual]
returns settings of this http client
Returns:
settings of this http client
Implements network::IHttpClient.
Definition at line 40 of file HttpClientCURL.h.
References settings.
Referenced by Get().
int network::HttpClientCURL::WriterCallback (char * data, size_t size, size_t nmemb, CURLWriterParam * param) [static, private]
Definition at line 106 of file HttpClientCURL.cpp.
References tools::MemoryContainer< T >::Append(), network::HttpResponse::html, and network::HttpClientCURL::_CURLWriterParam::response.
Referenced by HttpClientCURL().
Friends And Related Function Documentation
friend class network::HttpClientFactory [friend]
Definition at line 19 of file HttpClientCURL.h.
Member Data Documentation
HttpClientSettings network::HttpClientCURL::settings [private]
Definition at line 46 of file HttpClientCURL.h.
Referenced by Settings().
void* network::HttpClientCURL::curlPtr [private]
Definition at line 47 of file HttpClientCURL.h.
Referenced by Get(), HttpClientCURL(), and ~HttpClientCURL().
char* network::HttpClientCURL::errorBuffer [private]
Definition at line 48 of file HttpClientCURL.h.
Referenced by Get(), and HttpClientCURL().
The documentation for this class was generated from the following files:
Networking/src/HttpClientCURL.h
Networking/src/HttpClientCURL.cpp