DeepNet: tools::AutoPointer< T > Class Template Reference
tools::AutoPointer< T > Class Template Reference
wrapper class for pointer that cannot be null
#include <Pointer.h>
Public Member Functions
AutoPointer ()
constructs an empty AutoPointer
AutoPointer (const T &copyObj)
construct an instance copying another object
AutoPointer (T *ptr)
constructs a typed object from a already allocated pointer
virtual ~AutoPointer ()
virtual operator T & ()
virtual operator const T * () const
cast this instance to a constant typed pointer
virtual operator T * ()
cast this instance to a non constant pointer
void Set (T *ptr, bool autoDelete)
set this pointer to a new value, deleting all already contained instances
T * Get ()
gets content of this pointer, consider using cast operators for performance reasons
const T *const GetConst () const
gets const content of this pointer, consider using cast operators for performance reasons
void SwapFrom (Pointer< T > &swap)
takes over ownership of a pointer from another instance
void SwapTo (T *&swap)
swaps contents to pointer, disabling memory management
template<class X >
const X * DynCastConst () const
dynamic casts pointer to given type X (and make it const)
template<class X >
X * DynCast ()
dynamic casts pointer to given type X
bool IsNull () const
checks if pointer is null
void Release ()
releases all allocated instances of this pointer
Protected Attributes
T * ptr
bool autoDelete
Detailed Description
template<class T>
class tools::AutoPointer< T >
wrapper class for pointer that cannot be null
See also:
please see tools:Pointer for more reference
Definition at line 171 of file Pointer.h.
Constructor & Destructor Documentation
template<class T > tools::AutoPointer< T >::AutoPointer () [inline]
constructs an empty AutoPointer
Definition at line 177 of file Pointer.h.
template<class T > tools::AutoPointer< T >::AutoPointer (const T & copyObj) [inline]
construct an instance copying another object
Parameters:
copyObj object to be copyied
Definition at line 185 of file Pointer.h.
template<class T > tools::AutoPointer< T >::AutoPointer (T * ptr) [inline]
constructs a typed object from a already allocated pointer
Parameters:
ptr pointer to be managed by this class
Definition at line 193 of file Pointer.h.
template<class T > virtual tools::AutoPointer< T >::~AutoPointer () [inline, virtual]
Definition at line 197 of file Pointer.h.
Member Function Documentation
template<class T > virtual tools::AutoPointer< T >::operator T & () [inline, virtual]
Definition at line 200 of file Pointer.h.
References tools::Pointer< T >::Set().
template<class T> virtual tools::Pointer< T >::operator const T * () const [inline, virtual, inherited]
cast this instance to a constant typed pointer
Definition at line 55 of file Pointer.h.
References tools::Pointer< T >::ptr.
template<class T> virtual tools::Pointer< T >::operator T * () [inline, virtual, inherited]
cast this instance to a non constant pointer
Definition at line 62 of file Pointer.h.
References tools::Pointer< T >::ptr.
template<class T> void tools::Pointer< T >::Set (T * ptr, bool autoDelete) [inline, inherited]
set this pointer to a new value, deleting all already contained instances
Parameters:
ptr new instance
autoDelete true if the instance is bound to this instance
Definition at line 72 of file Pointer.h.
Referenced by network::HttpClientFactory::CreateInstance(), htmlparser::HtmlParserFactory::CreateInstance(), indexing::IIndexerFactory::CreateInstance(), caching::CacheDatabaseUrl::GetByUrl(), caching::CacheDatabaseUrl::GetByUrlID(), workerbot::WorkerBot::InitModeConfig(), workerbot::WorkerBot::OnInit(), tools::AutoPointer< T >::operator T &(), domparser::DOMParser::Parse(), libxmlparser::HtmlSAX2Parser::Parse(), and tools::Pointer< parser::HtmlParserBase >::SwapFrom().
template<class T> T* tools::Pointer< T >::Get () [inline, inherited]
gets content of this pointer, consider using cast operators for performance reasons
Returns:
this instances pointer
Definition at line 84 of file Pointer.h.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), caching::CacheRobotsTxt::DownloadRobotsTxt(), caching::CacheDatabaseUrl::GetByUrl(), caching::CacheDatabaseUrl::GetByUrlID(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), toolbot::UnitTestIndexerEx::HandleSingleFile(), workerbot::WorkerBot::InitCrawlerConfig(), workerbot::WorkerBot::InitIndexerConfigParams(), workerbot::WorkerBot::InitModeConfig(), workerbot::WorkerBot::InitParserConfig(), parser::GenericWebHtmlParserThread::InsertImages(), parser::GenericWebHtmlParserThread::InsertLinks(), htmlparser::UrlInserter::InsertURL(), workerbot::WorkerBot::OnRun(), workerbot::WorkerBot::OnShutdown(), indexing::IndexerTester::Parse(), parser::GenericWebHtmlParserThread::ParsePage(), parser::HtmlParserThread::ParsePages(), indexing::IndexerThread::ParsePages(), inspectorserver::InspectorServerResponse::Process(), toolbot::UnitTestHttpClientCURL::Run(), toolbot::UnitTestSAX2HtmlParser::Run(), tools::Pointer< parser::HtmlParserBase >::SwapFrom(), tools::Pointer< parser::HtmlParserBase >::SwapTo(), toolbot::UnitTestSAX2HtmlParser::Test(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and htmlparser::UrlInserter::ValidateURL().
template<class T> const T* const tools::Pointer< T >::GetConst () const [inline, inherited]
gets const content of this pointer, consider using cast operators for performance reasons
Returns:
this instances pointer
Definition at line 93 of file Pointer.h.
template<class T> void tools::Pointer< T >::SwapFrom (Pointer< T > & swap) [inline, inherited]
takes over ownership of a pointer from another instance
Parameters:
swap instance to be owned
Definition at line 101 of file Pointer.h.
template<class T> void tools::Pointer< T >::SwapTo (T *& swap) [inline, inherited]
swaps contents to pointer, disabling memory management
Parameters:
swap pointer to swap to
Definition at line 110 of file Pointer.h.
template<class T> template<class X > const X* tools::Pointer< T >::DynCastConst () const [inline, inherited]
dynamic casts pointer to given type X (and make it const)
Returns:
const pointer or 0 if not successful
Definition at line 120 of file Pointer.h.
template<class T> template<class X > X* tools::Pointer< T >::DynCast () [inline, inherited]
dynamic casts pointer to given type X
Returns:
pointer or 0 if not successful
Definition at line 131 of file Pointer.h.
template<class T> bool tools::Pointer< T >::IsNull () const [inline, inherited]
checks if pointer is null
Returns:
true if pointer is null
Definition at line 141 of file Pointer.h.
Referenced by domparser::Traverser::FilterNode(), toolbot::UnitTestIndexerEx::HandleSingleFile(), workerbot::WorkerBot::InitCrawlerConfig(), workerbot::WorkerBot::InitIndexerConfigParams(), workerbot::WorkerBot::InitParserConfig(), and domparser::DOMParser::Parse().
template<class T> void tools::Pointer< T >::Release () [inline, inherited]
releases all allocated instances of this pointer
Definition at line 148 of file Pointer.h.
Referenced by tools::Pointer< parser::HtmlParserBase >::Destruct().
Member Data Documentation
template<class T> T* tools::Pointer< T >::ptr [protected, inherited]
Definition at line 162 of file Pointer.h.
Referenced by tools::Pointer< parser::HtmlParserBase >::DynCast(), tools::Pointer< parser::HtmlParserBase >::DynCastConst(), tools::Pointer< parser::HtmlParserBase >::Get(), tools::Pointer< parser::HtmlParserBase >::GetConst(), tools::Pointer< parser::HtmlParserBase >::IsNull(), tools::Pointer< T >::operator const T *(), tools::Pointer< T >::operator T *(), tools::Pointer< parser::HtmlParserBase >::Release(), and tools::Pointer< parser::HtmlParserBase >::Set().
template<class T> bool tools::Pointer< T >::autoDelete [protected, inherited]
Definition at line 163 of file Pointer.h.
Referenced by tools::Pointer< parser::HtmlParserBase >::Destruct(), tools::Pointer< parser::HtmlParserBase >::Release(), tools::Pointer< parser::HtmlParserBase >::Set(), tools::Pointer< parser::HtmlParserBase >::SwapFrom(), and tools::Pointer< parser::HtmlParserBase >::SwapTo().
The documentation for this class was generated from the following file:
Tools/src/Pointer.h