DeepNet: toolbot::UnitTestIndexerEx Class Reference
toolbot::UnitTestIndexerEx Class Reference
#include <UnitTestIndexerEx.h>
Public Member Functions
UnitTestIndexerEx (database::DatabaseConnection *connection, const std::string &testPath)
virtual ~UnitTestIndexerEx ()
virtual bool Run ()
virtual std::string GetName () const
Private Member Functions
bool HandleSingleFile (tools::SpellChecking &spellCheck, const std::string &fileName)
Private Attributes
database::DatabaseConnection * connection
std::string testPath
std::vector< std::string > contentFiles
Detailed Description
Definition at line 26 of file UnitTestIndexerEx.h.
Constructor & Destructor Documentation
toolbot::UnitTestIndexerEx::UnitTestIndexerEx (database::DatabaseConnection * connection, const std::string & testPath)
Definition at line 25 of file UnitTestIndexerEx.cpp.
References contentFiles, and tools::FileTools::ListDirectory().
toolbot::UnitTestIndexerEx::~UnitTestIndexerEx () [virtual]
Definition at line 31 of file UnitTestIndexerEx.cpp.
Member Function Documentation
bool toolbot::UnitTestIndexerEx::Run () [virtual]
Implements toolbot::UnitTest.
Definition at line 34 of file UnitTestIndexerEx.cpp.
References contentFiles, tools::FileTools::DeleteFile(), HandleSingleFile(), tools::SpellChecking::InitSpellChecking(), tools::FileTools::ListDirectory(), log::Logging::LogError(), log::Logging::LogInfo(), and testPath.
virtual std::string toolbot::UnitTestIndexerEx::GetName () const [inline, virtual]
Implements toolbot::UnitTest.
Definition at line 33 of file UnitTestIndexerEx.h.
bool toolbot::UnitTestIndexerEx::HandleSingleFile (tools::SpellChecking & spellCheck, const std::string & fileName) [private]
Definition at line 63 of file UnitTestIndexerEx.cpp.
References tools::FileTools::CompareFiles(), connection, indexing::IIndexerFactory::CreateInstance(), tools::FileTools::DeleteFile(), indexing::Dictionary::DumpXML(), tools::FileTools::FileExists(), tools::Pointer< T >::Get(), indexing::IIndexer::GetDictionary(), tools::Pointer< T >::IsNull(), log::Logging::LogError(), log::Logging::LogInfo(), indexing::IIndexerFactory::OWN_GENERIC, indexing::IIndexer::Parse(), tools::FileTools::ReadFile(), indexing::Dictionary::SetTestMode(), testPath, and tools::FileTools::WriteFile().
Referenced by Run().
Member Data Documentation
database::DatabaseConnection* toolbot::UnitTestIndexerEx::connection [private]
Definition at line 39 of file UnitTestIndexerEx.h.
Referenced by HandleSingleFile().
std::string toolbot::UnitTestIndexerEx::testPath [private]
Definition at line 40 of file UnitTestIndexerEx.h.
Referenced by HandleSingleFile(), and Run().
std::vector<std::string> toolbot::UnitTestIndexerEx::contentFiles [private]
Definition at line 41 of file UnitTestIndexerEx.h.
Referenced by Run(), and UnitTestIndexerEx().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestIndexerEx.h
DeepNetTool/src/UnitTestIndexerEx.cpp