DeepNet: queryserver::Relevance Class Reference
queryserver::Relevance Class Reference
#include <Relevance.h>
Public Member Functions
Relevance (const Relevance &rhs)
Relevance (const double &relevance)
Relevance (const double &relevance, const double &weight)
bool operator== (const Relevance &rhs) const
bool operator< (const Relevance &rhs) const
Relevance operator+ (const Relevance &rhs) const
Relevance operator* (const Relevance &rhs) const
double GetWeightedRelevance (void) const
const double & GetRelevance (void) const
const double & GetWeight (void) const
void SetRelevance (const double &in)
void SetWeight (const double &in)
Private Member Functions
Relevance ()
Private Attributes
double relevance
double weight
Detailed Description
Definition at line 17 of file Relevance.h.
Constructor & Destructor Documentation
queryserver::Relevance::Relevance (const Relevance & rhs) [inline]
Definition at line 20 of file Relevance.h.
queryserver::Relevance::Relevance (const double & relevance) [inline]
Definition at line 24 of file Relevance.h.
queryserver::Relevance::Relevance (const double & relevance, const double & weight) [inline]
Definition at line 28 of file Relevance.h.
queryserver::Relevance::Relevance () [inline, private]
Definition at line 33 of file Relevance.h.
Referenced by operator*(), and operator+().
Member Function Documentation
bool queryserver::Relevance::operator== (const Relevance & rhs) const [inline]
Definition at line 38 of file Relevance.h.
References GetWeightedRelevance().
bool queryserver::Relevance::operator< (const Relevance & rhs) const [inline]
Definition at line 39 of file Relevance.h.
References GetWeightedRelevance().
Relevance queryserver::Relevance::operator+ (const Relevance & rhs) const [inline]
Definition at line 40 of file Relevance.h.
References GetWeightedRelevance(), Relevance(), and weight.
Relevance queryserver::Relevance::operator* (const Relevance & rhs) const [inline]
Definition at line 41 of file Relevance.h.
References Relevance(), relevance, and weight.
double queryserver::Relevance::GetWeightedRelevance (void) const [inline]
Definition at line 44 of file Relevance.h.
References GetRelevance(), and GetWeight().
Referenced by operator+(), operator<(), and operator==().
const double& queryserver::Relevance::GetRelevance (void) const [inline]
Definition at line 47 of file Relevance.h.
References relevance.
Referenced by GetWeightedRelevance().
const double& queryserver::Relevance::GetWeight (void) const [inline]
Definition at line 48 of file Relevance.h.
References weight.
Referenced by GetWeightedRelevance().
void queryserver::Relevance::SetRelevance (const double & in) [inline]
Definition at line 50 of file Relevance.h.
References relevance.
void queryserver::Relevance::SetWeight (const double & in) [inline]
Definition at line 51 of file Relevance.h.
References weight.
Member Data Documentation
double queryserver::Relevance::relevance [private]
Definition at line 54 of file Relevance.h.
Referenced by GetRelevance(), operator*(), and SetRelevance().
double queryserver::Relevance::weight [private]
Definition at line 55 of file Relevance.h.
Referenced by GetWeight(), queryserver::KeywordEntry::GetWeightByOccurrence(), operator*(), operator+(), and SetWeight().
The documentation for this class was generated from the following file:
QueryServer/src/Relevance.h