DeepNet: tools::SpellChecking Class Reference
tools::SpellChecking Class Reference
spell checking and suggestion generator.
#include <SpellChecking.h>
Public Member Functions
SpellChecking ()
virtual ~SpellChecking ()
bool InitSpellChecking (const std::string &dictionaryFile, const std::string &affixFile)
initialize spell checking dictionary.
bool GenerateProposals (const std::string &keyword, bool &spelledCorrectly, std::vector< std::string > &proposals)
generates suggestions based on keyword.
Private Attributes
Hunspell * instanceHunspell
Detailed Description
spell checking and suggestion generator.
Definition at line 18 of file SpellChecking.h.
Constructor & Destructor Documentation
tools::SpellChecking::SpellChecking ()
Definition at line 14 of file SpellChecking.cpp.
tools::SpellChecking::~SpellChecking () [virtual]
Definition at line 19 of file SpellChecking.cpp.
References instanceHunspell.
Member Function Documentation
bool tools::SpellChecking::InitSpellChecking (const std::string & dictionaryFile, const std::string & affixFile)
initialize spell checking dictionary.
Parameters:
dictionaryFile dictionary filename.
affixFile affix filename.
Returns:
false on error, true on success.
Definition at line 26 of file SpellChecking.cpp.
References instanceHunspell.
Referenced by toolbot::UnitTestIndexerEx::Run(), and fastcgiserver::FastCGIServer::StartServer().
bool tools::SpellChecking::GenerateProposals (const std::string & keyword, bool & spelledCorrectly, std::vector< std::string > & proposals)
generates suggestions based on keyword.
Parameters:
keyword keyword.
spelledCorrectly true if spelled correctly.
proposals list of proposals.
Returns:
false on error, true on success.
Definition at line 33 of file SpellChecking.cpp.
References instanceHunspell.
Referenced by indexing::Dictionary::DumpXML(), and suggestserver::SuggestServerResponse::Process().
Member Data Documentation
Hunspell* tools::SpellChecking::instanceHunspell [private]
Definition at line 43 of file SpellChecking.h.
Referenced by GenerateProposals(), InitSpellChecking(), and ~SpellChecking().
The documentation for this class was generated from the following files:
Tools/src/SpellChecking.h
Tools/src/SpellChecking.cpp