DeepNet: caching::CacheDatabaseUrl Class Reference
caching::CacheDatabaseUrl Class Reference
cache for DatabaseUrl.
#include <CacheDatabaseUrl.h>
Public Member Functions
CacheDatabaseUrl (size_t limit=0)
construct cache with size limit.
virtual ~CacheDatabaseUrl ()
Static Public Member Functions
static bool GetByUrlID (database::DatabaseConnection *db, const long long &urlID, tools::Pointer< htmlparser::DatabaseUrl > &urlOut)
gets an url by an url-id and loads them from database if non-existing in cache.
static void GetByUrlID (database::DatabaseConnection *db, const std::vector< long long > &IDs, std::map< long long, htmlparser::DatabaseUrl > &urls)
gets an url by an url-id and inserts if non-existing.
static bool GetByUrl (database::DatabaseConnection *db, const network::HttpUrl &urlIn, tools::Pointer< htmlparser::DatabaseUrl > &urlOut)
gets a database url by a preparsed http url.
static bool GetByUrlString (database::DatabaseConnection *db, const std::string &url, tools::Pointer< htmlparser::DatabaseUrl > &urlOut)
gets an url by a string.
static bool GetByUrlString (database::DatabaseConnection *db, const std::string &url, const std::string &baseUrl, tools::Pointer< htmlparser::DatabaseUrl > &urlOut)
gets an url by a string and it's relative url (also a string).
static bool GetByUrlString (database::DatabaseConnection *db, const std::string &url, const network::HttpUrl &baseUrl, tools::Pointer< htmlparser::DatabaseUrl > &urlOut)
gets an url by a string and it's preparsed relative url.
static bool GetByUrlString (database::DatabaseConnection *db, const std::string &url, const htmlparser::DatabaseUrl &baseUrl, tools::Pointer< htmlparser::DatabaseUrl > &urlOut)
gets an url by a string and it's preparsed relative url.
static void GetBySecondLevelIDSubdomainID (database::DatabaseConnection *db, const long long secondlevelID, const long long subdomainID, const int limitIn, std::vector< htmlparser::DatabaseUrl > &urls)
finds urls with a certain secondlevel/subdomain-id in the cache and in the database.
static void Clear (void)
removes all items from cache.
static void SetCapacity (const int capacity)
set current limit of cache.
static size_t GetSize ()
gets current number of entries in cache.
static size_t GetMatches ()
get current match count of cache, clearing internal match counter.
static size_t GetMisses ()
get current miss count of cache, clearing internal miss counter.
Private Member Functions
void Insert (database::DatabaseConnection *db, network::HttpUrl &url)
void Add (database::DatabaseConnection *db, htmlparser::DatabaseUrl &url)
Private Attributes
Cache< long long,
htmlparser::DatabaseUrl > cacheIDUrl
Static Private Attributes
static CacheDatabaseUrl cacheInstance
Detailed Description
cache for DatabaseUrl.
See also:
DatabaseUrl
Definition at line 33 of file CacheDatabaseUrl.h.
Constructor & Destructor Documentation
caching::CacheDatabaseUrl::CacheDatabaseUrl (size_t limit = 0)
construct cache with size limit.
Parameters:
limit maximum number of items in cache
Definition at line 28 of file CacheDatabaseUrl.cpp.
caching::CacheDatabaseUrl::~CacheDatabaseUrl () [virtual]
Definition at line 32 of file CacheDatabaseUrl.cpp.
Member Function Documentation
bool caching::CacheDatabaseUrl::GetByUrlID (database::DatabaseConnection * db, const long long & urlID, tools::Pointer< htmlparser::DatabaseUrl > & urlOut) [static]
gets an url by an url-id and loads them from database if non-existing in cache.
Parameters:
db database connection.
urlID url-id to search for.
urlOut requested url [out]
Returns:
true if successful, false if unsuccessful.
Definition at line 35 of file CacheDatabaseUrl.cpp.
References caching::Cache< T, V >::AddItem(), cacheIDUrl, cacheInstance, tools::Pointer< T >::Get(), caching::Cache< T, V >::GetItem(), htmlparser::DatabaseUrl::GetUrlID(), and tools::Pointer< T >::Set().
Referenced by GetByUrl(), GetByUrlID(), crawler::UrlFetcherThread::GetUrlsFromDatabase(), queryserver::XMLQueryResponse::ProcessExistQuery(), and toolbot::UnitTestCacheUrl::TestSingleEntry().
void caching::CacheDatabaseUrl::GetByUrlID (database::DatabaseConnection * db, const std::vector< long long > & IDs, std::map< long long, htmlparser::DatabaseUrl > & urls) [static]
gets an url by an url-id and inserts if non-existing.
Parameters:
db database connection.
IDs list of url-ids to get.
urls map gets filled with url-id and url.
Definition at line 48 of file CacheDatabaseUrl.cpp.
References tools::Pointer< T >::Get(), and GetByUrlID().
bool caching::CacheDatabaseUrl::GetByUrl (database::DatabaseConnection * db, const network::HttpUrl & urlIn, tools::Pointer< htmlparser::DatabaseUrl > & urlOut) [static]
gets a database url by a preparsed http url.
this function may insert new urls into the database.
Parameters:
db database connection.
urlIn preparsed http url.
urlOut requested database url [out]
Returns:
true if successful, false if unsuccessful.
Definition at line 59 of file CacheDatabaseUrl.cpp.
References caching::Cache< T, V >::AddItem(), cacheIDUrl, cacheInstance, tools::Pointer< T >::Get(), GetByUrlID(), caching::Cache< T, V >::GetByValue(), htmlparser::DatabaseUrl::GetUrlID(), and tools::Pointer< T >::Set().
Referenced by GetByUrlString(), parser::GenericWebHtmlParserThread::InsertLinks(), and toolbot::UnitTestCacheUrl::TestSingleEntry().
bool caching::CacheDatabaseUrl::GetByUrlString (database::DatabaseConnection * db, const std::string & url, tools::Pointer< htmlparser::DatabaseUrl > & urlOut) [static]
gets an url by a string.
this function may insert new urls into the database.
Parameters:
db database connection.
url url as a string.
urlOut requested database url [out]
Returns:
true if successful, false if unsuccessful.
Definition at line 70 of file CacheDatabaseUrl.cpp.
References GetByUrl(), and network::HttpUrlParser::ParseURL().
Referenced by crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), htmlparser::UrlInserter::InsertURL(), toolbot::UnitTestSAX2HtmlParser::Run(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and htmlparser::UrlInserter::ValidateURL().
bool caching::CacheDatabaseUrl::GetByUrlString (database::DatabaseConnection * db, const std::string & url, const std::string & baseUrl, tools::Pointer< htmlparser::DatabaseUrl > & urlOut) [static]
gets an url by a string and it's relative url (also a string).
this function may insert new urls into the database.
Parameters:
db database connection.
url url as a string.
baseUrl relative url.
urlOut requested database url [out]
Returns:
true if successful, false if unsuccessful.
Definition at line 77 of file CacheDatabaseUrl.cpp.
References GetByUrl(), and network::HttpUrlParser::ParseURL().
bool caching::CacheDatabaseUrl::GetByUrlString (database::DatabaseConnection * db, const std::string & url, const network::HttpUrl & baseUrl, tools::Pointer< htmlparser::DatabaseUrl > & urlOut) [static]
gets an url by a string and it's preparsed relative url.
this function may insert new urls into the database.
Parameters:
db database connection.
url url as a string.
baseUrl relative url.
urlOut requested database url [out]
Returns:
true if successful, false if unsuccessful.
Definition at line 84 of file CacheDatabaseUrl.cpp.
References GetByUrl(), and network::HttpUrlParser::ParseURL().
bool caching::CacheDatabaseUrl::GetByUrlString (database::DatabaseConnection * db, const std::string & url, const htmlparser::DatabaseUrl & baseUrl, tools::Pointer< htmlparser::DatabaseUrl > & urlOut) [static]
gets an url by a string and it's preparsed relative url.
this function may insert new urls into the database.
Parameters:
db database connection.
url url as a string.
baseUrl relative url.
urlOut requested database url [out]
Returns:
true if successful, false if unsuccessful.
Definition at line 91 of file CacheDatabaseUrl.cpp.
References GetByUrl(), and network::HttpUrlParser::ParseURL().
void caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID (database::DatabaseConnection * db, const long long secondlevelID, const long long subdomainID, const int limitIn, std::vector< htmlparser::DatabaseUrl > & urls) [static]
finds urls with a certain secondlevel/subdomain-id in the cache and in the database.
Parameters:
db database connection.
secondlevelID secondlevel domain id to look for.
subdomainID subdomain id to look for,can be -1 if no subdomain.
limitIn maximum number of urls to return.
urls gets filled with urls.
Definition at line 98 of file CacheDatabaseUrl.cpp.
References database::WhereCondition::AddColumns(), caching::Cache< T, V >::AddItem(), database::WhereCondition::And(), cacheIDUrl, cacheInstance, database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), database::urlsTableBase::CreateTableDefinition(), database::WhereCondition::Equals(), database::TableDefinition::GetConstColumnDefinitionByName(), tools::PointerContainer< T >::GetIter(), database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), database::Statement::SetLimit(), database::TableColumn::SetNull(), and database::SelectStatement::Where().
Referenced by crawler::CommerceSearchFetcherThread::ReserveNextUrls().
void caching::CacheDatabaseUrl::Clear (void) [static]
removes all items from cache.
Definition at line 136 of file CacheDatabaseUrl.cpp.
References cacheIDUrl, cacheInstance, and caching::Cache< T, V >::ClearItems().
Referenced by toolbot::UnitTestCacheUrl::Run().
void caching::CacheDatabaseUrl::SetCapacity (const int capacity) [static]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 140 of file CacheDatabaseUrl.cpp.
References cacheIDUrl, cacheInstance, and caching::Cache< T, V >::SetLimit().
Referenced by bot::Bot::InitCacheConfigParams().
size_t caching::CacheDatabaseUrl::GetSize () [static]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 144 of file CacheDatabaseUrl.cpp.
References cacheIDUrl, cacheInstance, and caching::Cache< T, V >::GetSize().
Referenced by bot::Bot::WatchDog().
size_t caching::CacheDatabaseUrl::GetMatches () [static]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 148 of file CacheDatabaseUrl.cpp.
References cacheIDUrl, cacheInstance, and caching::Cache< T, V >::GetMatches().
Referenced by bot::Bot::WatchDog().
size_t caching::CacheDatabaseUrl::GetMisses () [static]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 152 of file CacheDatabaseUrl.cpp.
References cacheIDUrl, cacheInstance, and caching::Cache< T, V >::GetMisses().
Referenced by bot::Bot::WatchDog().
void caching::CacheDatabaseUrl::Insert (database::DatabaseConnection * db, network::HttpUrl & url) [private]
void caching::CacheDatabaseUrl::Add (database::DatabaseConnection * db, htmlparser::DatabaseUrl & url) [private]
Member Data Documentation
CacheDatabaseUrl caching::CacheDatabaseUrl::cacheInstance [static, private]
Definition at line 190 of file CacheDatabaseUrl.h.
Referenced by Clear(), GetBySecondLevelIDSubdomainID(), GetByUrl(), GetByUrlID(), GetMatches(), GetMisses(), GetSize(), and SetCapacity().
Cache<long long, htmlparser::DatabaseUrl> caching::CacheDatabaseUrl::cacheIDUrl [private]
Definition at line 193 of file CacheDatabaseUrl.h.
Referenced by Clear(), GetBySecondLevelIDSubdomainID(), GetByUrl(), GetByUrlID(), GetMatches(), GetMisses(), GetSize(), and SetCapacity().
The documentation for this class was generated from the following files:
Caching/src/CacheDatabaseUrl.h
Caching/src/CacheDatabaseUrl.cpp