DeepNet: network::HttpUrl Class Reference
network::HttpUrl Class Reference
#include <HttpUrl.h>
Public Member Functions
HttpUrl ()
virtual ~HttpUrl ()
bool operator< (HttpUrl const &rhs) const
bool operator== (HttpUrl const &rhs) const
std::string Dump () const
virtual void Dump (std::string &dump) const
bool CalculateFullUrl (const bool forceRecalculate=false)
virtual bool DeepMatchUrl (const HttpUrl &rhs, const bool compareAuth=false) const
const std::string & GetScheme () const
const std::string & GetMD5 () const
const std::string & GetDomain () const
const std::string & GetPort () const
const std::string & GetTLD () const
const std::string & GetSecondLevelDomain () const
const std::string & GetSubdomain () const
const std::string & GetPathPart () const
const std::string & GetDocument () const
const std::string & GetSearchPart () const
const std::string & GetFragmentPart () const
const std::string & GetAuthUser () const
const std::string & GetAuthPass () const
const std::string & GetFullUrl () const
const std::string GetFullDomain () const
const std::string GetFullPathSearch () const
Protected Attributes
std::string fullUrl
std::string domain
std::string scheme
std::string subdomain
std::string secondleveldomain
std::string tld
std::string port
std::string path_part
std::string search_part
std::string fragment_part
std::string auth_user
std::string auth_pass
std::string md5
bool isCalculated
Private Member Functions
void CalculatePortPart ()
void CalculateDomainPart ()
Friends
class HttpUrlParser
Detailed Description
Definition at line 14 of file HttpUrl.h.
Constructor & Destructor Documentation
network::HttpUrl::HttpUrl ()
Definition at line 22 of file HttpUrl.cpp.
network::HttpUrl::~HttpUrl () [virtual]
Definition at line 26 of file HttpUrl.cpp.
Member Function Documentation
bool network::HttpUrl::operator< (HttpUrl const & rhs) const
Definition at line 29 of file HttpUrl.cpp.
References md5.
bool network::HttpUrl::operator== (HttpUrl const & rhs) const
Definition at line 36 of file HttpUrl.cpp.
References md5.
std::string network::HttpUrl::Dump () const
Definition at line 43 of file HttpUrl.cpp.
Referenced by toolbot::UnitTestUrlParser::TestInvalidUrls(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
void network::HttpUrl::Dump (std::string & dump) const [virtual]
Definition at line 50 of file HttpUrl.cpp.
References auth_pass, auth_user, domain, fragment_part, fullUrl, md5, path_part, port, scheme, search_part, secondleveldomain, subdomain, and tld.
bool network::HttpUrl::CalculateFullUrl (const bool forceRecalculate = false)
Definition at line 127 of file HttpUrl.cpp.
References CalculateDomainPart(), CalculatePortPart(), domain, fragment_part, fullUrl, GetMD5(), isCalculated, md5, path_part, port, scheme, search_part, and tld.
Referenced by htmlparser::DatabaseUrl::InitByTable(), network::HttpUrlParser::ParseURL(), htmlparser::DatabaseUrl::Store(), toolbot::UnitTestUrlParser::TestInvalidUrls(), and toolbot::UnitTestUrlParser::TestValidUrls().
bool network::HttpUrl::DeepMatchUrl (const HttpUrl & rhs, const bool compareAuth = false) const [virtual]
Definition at line 219 of file HttpUrl.cpp.
References GetAuthPass(), GetAuthUser(), GetDomain(), GetFragmentPart(), GetFullUrl(), GetMD5(), GetPathPart(), GetPort(), GetScheme(), GetSearchPart(), GetSecondLevelDomain(), GetSubdomain(), and GetTLD().
Referenced by toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
const std::string & network::HttpUrl::GetScheme () const
Definition at line 154 of file HttpUrl.cpp.
References scheme.
Referenced by DeepMatchUrl(), and caching::CacheRobotsTxt::DownloadRobotsTxt().
const std::string & network::HttpUrl::GetMD5 () const
Definition at line 164 of file HttpUrl.cpp.
References md5.
Referenced by CalculateFullUrl(), and DeepMatchUrl().
const std::string & network::HttpUrl::GetDomain () const
Definition at line 169 of file HttpUrl.cpp.
References domain.
Referenced by DeepMatchUrl(), and GetFullDomain().
const std::string & network::HttpUrl::GetPort () const
Definition at line 174 of file HttpUrl.cpp.
References port.
Referenced by DeepMatchUrl().
const std::string & network::HttpUrl::GetTLD () const
Definition at line 179 of file HttpUrl.cpp.
References tld.
Referenced by DeepMatchUrl(), caching::CacheRobotsTxt::DownloadRobotsTxt(), and GetFullDomain().
const std::string & network::HttpUrl::GetSecondLevelDomain () const
Definition at line 184 of file HttpUrl.cpp.
References secondleveldomain.
Referenced by DeepMatchUrl(), and caching::CacheRobotsTxt::DownloadRobotsTxt().
const std::string & network::HttpUrl::GetSubdomain () const
Definition at line 189 of file HttpUrl.cpp.
References subdomain.
Referenced by DeepMatchUrl(), and caching::CacheRobotsTxt::DownloadRobotsTxt().
const std::string & network::HttpUrl::GetPathPart () const
Definition at line 194 of file HttpUrl.cpp.
References path_part.
Referenced by DeepMatchUrl().
const std::string& network::HttpUrl::GetDocument () const
const std::string & network::HttpUrl::GetSearchPart () const
Definition at line 199 of file HttpUrl.cpp.
References search_part.
Referenced by DeepMatchUrl().
const std::string & network::HttpUrl::GetFragmentPart () const
Definition at line 204 of file HttpUrl.cpp.
References fragment_part.
Referenced by DeepMatchUrl().
const std::string & network::HttpUrl::GetAuthUser () const
Definition at line 209 of file HttpUrl.cpp.
References auth_user.
Referenced by DeepMatchUrl().
const std::string & network::HttpUrl::GetAuthPass () const
Definition at line 214 of file HttpUrl.cpp.
References auth_pass.
Referenced by DeepMatchUrl().
const std::string & network::HttpUrl::GetFullUrl () const
Definition at line 159 of file HttpUrl.cpp.
References fullUrl.
Referenced by DeepMatchUrl(), htmlparser::IHtmlParserResult::DumpXML(), libxmlparser::HtmlSAX2Parser::endElement(), network::HttpClientCURL::Get(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), htmlparser::DatabaseUrl::InitByHttpUrl(), htmlparser::DatabaseUrl::InitByIDs(), htmlparser::DatabaseUrl::InitByUrlID(), htmlparser::UrlInserter::InsertURL(), parser::CommerceSearchParserThread::MatchUrlCriteria(), queryserver::XMLQueryResponse::OutputResults(), libxmlparser::HtmlSAX2Parser::Parse(), inspectorserver::InspectorServerResponse::Process(), htmlparser::DatabaseUrl::Store(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
const std::string network::HttpUrl::GetFullDomain () const
Definition at line 243 of file HttpUrl.cpp.
References GetDomain(), and GetTLD().
const std::string network::HttpUrl::GetFullPathSearch () const
Definition at line 247 of file HttpUrl.cpp.
References path_part, and search_part.
Referenced by caching::RobotTxt::IsAllowed().
void network::HttpUrl::CalculatePortPart () [private]
Definition at line 111 of file HttpUrl.cpp.
References port, and scheme.
Referenced by CalculateFullUrl().
void network::HttpUrl::CalculateDomainPart () [private]
Definition at line 69 of file HttpUrl.cpp.
References domain, fullUrl, secondleveldomain, tools::StringTools::SplitBy(), subdomain, THROW_EXCEPTION, and tld.
Referenced by CalculateFullUrl().
Friends And Related Function Documentation
friend class HttpUrlParser [friend]
Definition at line 16 of file HttpUrl.h.
Member Data Documentation
std::string network::HttpUrl::fullUrl [protected]
Definition at line 57 of file HttpUrl.h.
Referenced by CalculateDomainPart(), CalculateFullUrl(), Dump(), GetFullUrl(), network::HttpUrlParser::ParseDomain(), network::HttpUrlParser::ParseFragment(), network::HttpUrlParser::ParseQuery(), network::HttpUrlParser::ParseURL(), and htmlparser::DatabaseUrl::Store().
std::string network::HttpUrl::domain [protected]
Definition at line 59 of file HttpUrl.h.
Referenced by CalculateDomainPart(), CalculateFullUrl(), Dump(), GetDomain(), network::HttpUrlParser::ParseDomain(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::scheme [protected]
Definition at line 60 of file HttpUrl.h.
Referenced by CalculateFullUrl(), CalculatePortPart(), Dump(), GetScheme(), htmlparser::DatabaseUrl::InitByHttpUrl(), htmlparser::DatabaseUrl::InitByIDs(), network::HttpUrlParser::ParseScheme(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::subdomain [protected]
Definition at line 61 of file HttpUrl.h.
Referenced by CalculateDomainPart(), Dump(), GetSubdomain(), htmlparser::DatabaseUrl::InitByHttpUrl(), htmlparser::DatabaseUrl::InitByIDs(), and htmlparser::DatabaseUrl::InitByTable().
std::string network::HttpUrl::secondleveldomain [protected]
Definition at line 62 of file HttpUrl.h.
Referenced by CalculateDomainPart(), Dump(), GetSecondLevelDomain(), htmlparser::DatabaseUrl::InitByHttpUrl(), and htmlparser::DatabaseUrl::InitByIDs().
std::string network::HttpUrl::tld [protected]
Definition at line 63 of file HttpUrl.h.
Referenced by CalculateDomainPart(), CalculateFullUrl(), Dump(), GetTLD(), htmlparser::DatabaseUrl::InitByHttpUrl(), htmlparser::DatabaseUrl::InitByIDs(), network::HttpUrlParser::ParseDomain(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::port [protected]
Definition at line 64 of file HttpUrl.h.
Referenced by CalculateFullUrl(), CalculatePortPart(), Dump(), GetPort(), htmlparser::DatabaseUrl::InitByIDs(), htmlparser::DatabaseUrl::InitByTable(), network::HttpUrlParser::ParseDomain(), network::HttpUrlParser::ParseURL(), and htmlparser::DatabaseUrl::Store().
std::string network::HttpUrl::path_part [protected]
Definition at line 65 of file HttpUrl.h.
Referenced by CalculateFullUrl(), Dump(), GetFullPathSearch(), GetPathPart(), htmlparser::DatabaseUrl::InitByTable(), network::HttpUrlParser::ParsePath(), network::HttpUrlParser::ParseURL(), and htmlparser::DatabaseUrl::Store().
std::string network::HttpUrl::search_part [protected]
Definition at line 66 of file HttpUrl.h.
Referenced by CalculateFullUrl(), Dump(), GetFullPathSearch(), GetSearchPart(), htmlparser::DatabaseUrl::InitByTable(), network::HttpUrlParser::ParseURL(), and htmlparser::DatabaseUrl::Store().
std::string network::HttpUrl::fragment_part [protected]
Definition at line 67 of file HttpUrl.h.
Referenced by CalculateFullUrl(), Dump(), GetFragmentPart(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::auth_user [protected]
Definition at line 69 of file HttpUrl.h.
Referenced by Dump(), GetAuthUser(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::auth_pass [protected]
Definition at line 70 of file HttpUrl.h.
Referenced by Dump(), GetAuthPass(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::md5 [protected]
Definition at line 72 of file HttpUrl.h.
Referenced by CalculateFullUrl(), Dump(), GetMD5(), htmlparser::DatabaseUrl::InitByTable(), operator<(), and operator==().
bool network::HttpUrl::isCalculated [protected]
Definition at line 74 of file HttpUrl.h.
Referenced by CalculateFullUrl(), and htmlparser::DatabaseUrl::Store().
The documentation for this class was generated from the following files:
Networking/src/HttpUrl.h
Networking/src/HttpUrl.cpp