DeepNet: tools::PointerContainer< T > Class Template Reference
tools::PointerContainer< T > Class Template Reference
memory managing container for pointers.
#include <PointerContainer.h>
Public Member Functions
PointerContainer ()
PointerContainer (const std::vector< T * > &container)
virtual ~PointerContainer ()
deletes all entries when destructed.
void Add (T *entry)
adds an entry.
void Add (const std::vector< T * > &entries)
adds multiple entries entry.
void ResetIter () const
resets iterator.
bool IsIterEnd () const
checks if iterator is at end.
T * GetIter ()
gets current iterator.
const T *const GetConstIter () const
gets current iterator as const.
void Next () const
increment iterator.
std::vector< T * > & GetVector ()
gets vector of entries.
size_t Size () const
gets current container size.
Private Member Functions
PointerContainer (const PointerContainer< T > &copy)
void CleanUp ()
Private Attributes
std::vector< T * > container
std::vector< T * >::const_iterator iterContainer
Detailed Description
template<class T>
class tools::PointerContainer< T >
memory managing container for pointers.
use iterator to enumerate over all entries.
See also:
tools::Pointer for more information
Definition at line 20 of file PointerContainer.h.
Constructor & Destructor Documentation
template<class T> tools::PointerContainer< T >::PointerContainer (const PointerContainer< T > & copy) [inline, private]
Definition at line 22 of file PointerContainer.h.
template<class T> tools::PointerContainer< T >::PointerContainer () [inline]
Definition at line 25 of file PointerContainer.h.
template<class T> tools::PointerContainer< T >::PointerContainer (const std::vector< T * > & container) [inline]
Definition at line 26 of file PointerContainer.h.
template<class T> virtual tools::PointerContainer< T >::~PointerContainer () [inline, virtual]
deletes all entries when destructed.
Definition at line 32 of file PointerContainer.h.
Member Function Documentation
template<class T> void tools::PointerContainer< T >::Add (T * entry) [inline]
adds an entry.
Parameters:
entry entry to add.
Definition at line 39 of file PointerContainer.h.
Referenced by database::WhereCondition::AddColumn(), database::WhereCondition::AddColumns(), database::WhereConditionTableColumn::CreateInstance(), and database::DatabaseConnection::Select().
template<class T> void tools::PointerContainer< T >::Add (const std::vector< T * > & entries) [inline]
adds multiple entries entry.
Parameters:
entries entries to add.
Definition at line 47 of file PointerContainer.h.
template<class T> void tools::PointerContainer< T >::ResetIter () const [inline]
resets iterator.
Definition at line 54 of file PointerContainer.h.
Referenced by tools::PointerContainer< WhereConditionTableColumn >::Add(), crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), htmlparser::DatabaseUrl::InitByUrlID(), parser::CommerceSearchParserThread::InitParserThread(), tools::PointerContainer< WhereConditionTableColumn >::PointerContainer(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> bool tools::PointerContainer< T >::IsIterEnd () const [inline]
checks if iterator is at end.
Returns:
false if not at end, true if at end.
Definition at line 61 of file PointerContainer.h.
Referenced by crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), parser::CommerceSearchParserThread::InitParserThread(), tools::PointerContainer< WhereConditionTableColumn >::Next(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> T* tools::PointerContainer< T >::GetIter () [inline]
gets current iterator.
Returns:
current iterator
Definition at line 68 of file PointerContainer.h.
Referenced by crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), htmlparser::DatabaseUrl::InitByUrlID(), parser::CommerceSearchParserThread::InitParserThread(), queryserver::XMLQueryResponse::ProcessExistQuery(), toolbot::DataMiningTools::RegisterDataminingAlert(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> const T* const tools::PointerContainer< T >::GetConstIter () const [inline]
gets current iterator as const.
Returns:
current iterator
Definition at line 75 of file PointerContainer.h.
Referenced by database::WhereConditionTableColumn::ToString(), and database::WhereCondition::ToString().
template<class T> void tools::PointerContainer< T >::Next () const [inline]
increment iterator.
Definition at line 81 of file PointerContainer.h.
Referenced by crawler::GenericWebUrlFetcherThread::CheckSecondLevelDomainTimeout(), parser::CommerceSearchMatchCriteria::GetAll(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::TLD::Init(), parser::CommerceSearchParserThread::InitParserThread(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> std::vector<T*>& tools::PointerContainer< T >::GetVector () [inline]
gets vector of entries.
Returns:
raw vector of entries.
Definition at line 90 of file PointerContainer.h.
Referenced by parser::CommerceSearchParserThread::OnAfterParsePage().
template<class T> size_t tools::PointerContainer< T >::Size () const [inline]
gets current container size.
Returns:
current container size.
Definition at line 97 of file PointerContainer.h.
Referenced by caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), parser::CommerceSearchMatchCriteria::Init(), htmlparser::DatabaseUrl::InitByUrlID(), queryserver::XMLQueryResponse::ProcessExistQuery(), toolbot::DataMiningTools::RegisterDataminingAlert(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::FencedCrawler::StartCrawler(), database::WhereConditionTableColumn::ToString(), database::WhereCondition::ToString(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T> void tools::PointerContainer< T >::CleanUp () [inline, private]
Definition at line 101 of file PointerContainer.h.
Referenced by tools::PointerContainer< WhereConditionTableColumn >::~PointerContainer().
Member Data Documentation
template<class T> std::vector<T*> tools::PointerContainer< T >::container [private]
Definition at line 107 of file PointerContainer.h.
Referenced by tools::PointerContainer< WhereConditionTableColumn >::Add(), tools::PointerContainer< WhereConditionTableColumn >::CleanUp(), tools::PointerContainer< WhereConditionTableColumn >::GetVector(), tools::PointerContainer< WhereConditionTableColumn >::IsIterEnd(), tools::PointerContainer< WhereConditionTableColumn >::ResetIter(), and tools::PointerContainer< WhereConditionTableColumn >::Size().
template<class T> std::vector<T*>::const_iterator tools::PointerContainer< T >::iterContainer [mutable, private]
Definition at line 108 of file PointerContainer.h.
Referenced by tools::PointerContainer< WhereConditionTableColumn >::CleanUp(), tools::PointerContainer< WhereConditionTableColumn >::GetConstIter(), tools::PointerContainer< WhereConditionTableColumn >::GetIter(), tools::PointerContainer< WhereConditionTableColumn >::IsIterEnd(), tools::PointerContainer< WhereConditionTableColumn >::Next(), and tools::PointerContainer< WhereConditionTableColumn >::ResetIter().
The documentation for this class was generated from the following file:
Tools/src/PointerContainer.h