DeepNet: tools::MimeType Class Reference
tools::MimeType Class Reference
mime type parsing class.
#include <MimeType.h>
Public Member Functions
MimeType ()
virtual ~MimeType ()
std::string GetMimeType (const void *pszBuffer, const size_t len)
get mime type from mime string.
std::string GetMimeEncoding (const void *pszBuffer, const size_t len)
get encoding from mime string.
Static Public Member Functions
static bool ParseMimeString (const std::string &mimeString, std::string &mimeType, std::string &mimeEncoding)
parses mime string into type and encoding.
static bool GetCharsetFromMimeString (const std::string &contentType, std::string &encoding)
gets charset from mime string.
Private Attributes
magic_t magicCookie
Detailed Description
mime type parsing class.
Definition at line 17 of file MimeType.h.
Constructor & Destructor Documentation
tools::MimeType::MimeType ()
Definition at line 14 of file MimeType.cpp.
References magicCookie.
tools::MimeType::~MimeType () [virtual]
Definition at line 25 of file MimeType.cpp.
References magicCookie.
Member Function Documentation
std::string tools::MimeType::GetMimeType (const void * pszBuffer, const size_t len)
get mime type from mime string.
Parameters:
pszBuffer buffer.
len size of buffer.
Returns:
mime type.
Definition at line 33 of file MimeType.cpp.
References magicCookie.
std::string tools::MimeType::GetMimeEncoding (const void * pszBuffer, const size_t len)
get encoding from mime string.
Parameters:
pszBuffer buffer.
len size of buffer.
Returns:
mime encoding.
Definition at line 42 of file MimeType.cpp.
References magicCookie.
bool tools::MimeType::ParseMimeString (const std::string & mimeString, std::string & mimeType, std::string & mimeEncoding) [static]
parses mime string into type and encoding.
Parameters:
mimeString mime type string.
mimeType mime type.
mimeEncoding encoding.
Returns:
false on error, true on success.
Definition at line 51 of file MimeType.cpp.
References GetCharsetFromMimeString(), tools::StringTools::ToLowerNP(), and tools::StringTools::Trim().
Referenced by network::HtmlData::ConvertToHostCharset().
bool tools::MimeType::GetCharsetFromMimeString (const std::string & contentType, std::string & encoding) [static]
gets charset from mime string.
Parameters:
contentType mime string.
encoding gets filled with name of encoding.
Returns:
false on error, true on success.
Definition at line 69 of file MimeType.cpp.
References tools::CharsetEncoder::IsValidEncodingName(), tools::StringTools::ReplaceString(), and tools::StringTools::Trim().
Referenced by ParseMimeString().
Member Data Documentation
magic_t tools::MimeType::magicCookie [private]
Definition at line 59 of file MimeType.h.
Referenced by GetMimeEncoding(), GetMimeType(), MimeType(), and ~MimeType().
The documentation for this class was generated from the following files:
Tools/src/MimeType.h
Tools/src/MimeType.cpp