DeepNet: indexing::GenericWebContentIndexer Class Reference
indexing::GenericWebContentIndexer Class Reference
#include <GenericWebContentIndexer.h>
Public Types
enum WordLen { SHORT, MEDIUM, LONG }
enum IndexerType { META_CONTENT, BODY_CONTENT, URL_CONTENT }
Public Member Functions
virtual ~GenericWebContentIndexer ()
virtual Dictionary & GetDictionary ()
gets dictionary of this indexer
virtual void OnCharacterReference (std::string *characterReference)
virtual void OnHtmlEntity (std::string *entity)
virtual void OnWord (std::string *word)
virtual void TerminateWord (void)
virtual void Parse (const std::string &input, const long long paragraph)
parses a text
virtual void ParseMeta (const std::string &input, const Dictionary::MetaInformationType &type)
parses content part of a meta type
int Read (char *buf, int maxSize)
Public Attributes
IndexerCtx * ctx
std::string content
std::string::iterator contentIter
Private Member Functions
GenericWebContentIndexer (database::DatabaseConnection *database, const IndexerBase::IndexerType type)
Private Attributes
GenericWebDictionary dictionary
Friends
class IIndexerFactory
Detailed Description
Definition at line 17 of file GenericWebContentIndexer.h.
Member Enumeration Documentation
enum indexing::IndexerBase::WordLen [inherited]
Enumerator:
SHORT
MEDIUM
LONG
Definition at line 56 of file IndexerBase.h.
enum indexing::IndexerBase::IndexerType [inherited]
Enumerator:
META_CONTENT
BODY_CONTENT
URL_CONTENT
Definition at line 62 of file IndexerBase.h.
Constructor & Destructor Documentation
indexing::GenericWebContentIndexer::GenericWebContentIndexer (database::DatabaseConnection * database, const IndexerBase::IndexerType type) [private]
Definition at line 12 of file GenericWebContentIndexer.cpp.
indexing::GenericWebContentIndexer::~GenericWebContentIndexer () [virtual]
Definition at line 17 of file GenericWebContentIndexer.cpp.
Member Function Documentation
virtual Dictionary& indexing::GenericWebContentIndexer::GetDictionary () [inline, virtual]
gets dictionary of this indexer
Returns:
instance of this indexers dictionary
Implements indexing::IIndexer.
Definition at line 27 of file GenericWebContentIndexer.h.
References dictionary.
void indexing::ContentIndexer::OnCharacterReference (std::string * characterReference) [virtual, inherited]
Definition at line 51 of file ContentIndexer.cpp.
References indexing::ContentIndexer::tmpWord.
void indexing::ContentIndexer::OnHtmlEntity (std::string * entity) [virtual, inherited]
Definition at line 43 of file ContentIndexer.cpp.
References indexing::ContentIndexer::tmpWord.
void indexing::ContentIndexer::OnWord (std::string * word) [virtual, inherited]
Definition at line 35 of file ContentIndexer.cpp.
References indexing::ContentIndexer::tmpWord.
void indexing::ContentIndexer::TerminateWord (void) [virtual, inherited]
Definition at line 59 of file ContentIndexer.cpp.
References indexing::Dictionary::AddContent(), indexing::IIndexer::GetDictionary(), indexing::ContentIndexer::paragraph, indexing::ContentIndexer::posWord, and indexing::ContentIndexer::tmpWord.
Referenced by indexing::ContentIndexer::OnParse().
void indexing::IndexerBase::Parse (const std::string & input, const long long paragraph) [virtual, inherited]
parses a text
Parameters:
input text to parse
paragraph paragraph of this text
Implements indexing::IIndexer.
Definition at line 31 of file IndexerBase.cpp.
References indexing::IndexerBase::content, indexing::IndexerBase::contentIter, input(), and indexing::IndexerBase::OnParse().
void indexing::IndexerBase::ParseMeta (const std::string & input, const Dictionary::MetaInformationType & type) [virtual, inherited]
parses content part of a meta type
Parameters:
input content part to parse
type meta type to set
Implements indexing::IIndexer.
Definition at line 39 of file IndexerBase.cpp.
References indexing::IndexerBase::OnParseMeta().
int indexing::IndexerBase::Read (char * buf, int maxSize) [inherited]
Definition at line 43 of file IndexerBase.cpp.
References indexing::IndexerBase::content, and indexing::IndexerBase::contentIter.
Friends And Related Function Documentation
friend class IIndexerFactory [friend]
Definition at line 19 of file GenericWebContentIndexer.h.
Member Data Documentation
GenericWebDictionary indexing::GenericWebContentIndexer::dictionary [private]
Definition at line 30 of file GenericWebContentIndexer.h.
Referenced by GetDictionary().
IndexerCtx* indexing::IndexerBase::ctx [inherited]
Definition at line 89 of file IndexerBase.h.
Referenced by indexing::ContentIndexer::ContentIndexer(), indexing::MetaIndexer::MetaIndexer(), indexing::MetaIndexer::OnParse(), indexing::ContentIndexer::OnParse(), indexing::ContentIndexer::~ContentIndexer(), indexing::IndexerBase::~IndexerBase(), and indexing::MetaIndexer::~MetaIndexer().
std::string indexing::IndexerBase::content [inherited]
Definition at line 91 of file IndexerBase.h.
Referenced by indexing::IndexerBase::Parse(), and indexing::IndexerBase::Read().
std::string::iterator indexing::IndexerBase::contentIter [inherited]
Definition at line 92 of file IndexerBase.h.
Referenced by indexing::IndexerBase::Parse(), and indexing::IndexerBase::Read().
The documentation for this class was generated from the following files:
Indexer/src/GenericWebContentIndexer.h
Indexer/src/GenericWebContentIndexer.cpp