DeepNet: database::WhereConditionCompositeOperator Class Reference
database::WhereConditionCompositeOperator Class Reference
composite operator container for where conditions.
#include <WhereConditionCompositeOperator.h>
Public Member Functions
WhereConditionCompositeOperator (const WhereConditionCompositeOperatorType &type)
construct from composite operator type.
virtual ~WhereConditionCompositeOperator ()
std::string ToString (void) const
gets sql equivalent of this operator.
WhereConditionCompositeOperatorType GetType (void) const
gets type of this composite operator.
Static Public Member Functions
static std::string OperatorToString (const WhereConditionCompositeOperatorType &op)
converts composite operator type to string
Private Attributes
WhereConditionCompositeOperatorType type
Detailed Description
composite operator container for where conditions.
Definition at line 17 of file WhereConditionCompositeOperator.h.
Constructor & Destructor Documentation
database::WhereConditionCompositeOperator::WhereConditionCompositeOperator (const WhereConditionCompositeOperatorType & type)
construct from composite operator type.
Parameters:
type composite operator type.
Definition at line 13 of file WhereConditionCompositeOperator.cpp.
database::WhereConditionCompositeOperator::~WhereConditionCompositeOperator () [virtual]
Definition at line 17 of file WhereConditionCompositeOperator.cpp.
Member Function Documentation
std::string database::WhereConditionCompositeOperator::ToString (void) const
gets sql equivalent of this operator.
Returns:
sql string.
Definition at line 20 of file WhereConditionCompositeOperator.cpp.
References OperatorToString(), and type.
Referenced by database::WhereConditionTableColumn::ToString().
WhereConditionCompositeOperatorType database::WhereConditionCompositeOperator::GetType (void) const
gets type of this composite operator.
Returns:
composite operator type.
Definition at line 25 of file WhereConditionCompositeOperator.cpp.
References type.
Referenced by database::WhereConditionTableColumn::ToString().
std::string database::WhereConditionCompositeOperator::OperatorToString (const WhereConditionCompositeOperatorType & op) [static]
converts composite operator type to string
Parameters:
op composite operator type.
Returns:
composite operator.
Definition at line 29 of file WhereConditionCompositeOperator.cpp.
References database::AND, database::INITIAL_COMPOSITE_OPERATOR_TYPE, database::OR, and THROW_EXCEPTION.
Referenced by ToString().
Member Data Documentation
WhereConditionCompositeOperatorType database::WhereConditionCompositeOperator::type [private]
Definition at line 49 of file WhereConditionCompositeOperator.h.
Referenced by GetType(), and ToString().
The documentation for this class was generated from the following files:
Database/src/WhereConditionCompositeOperator.h
Database/src/WhereConditionCompositeOperator.cpp