DeepNet: crawler::CommerceSearchFetcherThread Class Reference
crawler::CommerceSearchFetcherThread Class Reference
url fetcher implementation for commerce search.
#include <CommerceSearchFetcherThread.h>
Classes
class CommerceSearchFetcherThreadParam
struct CustomerDomainProperties
Public Member Functions
CommerceSearchFetcherThread ()
virtual ~CommerceSearchFetcherThread ()
long long GetOldCrawlerSessionID () const
gets old crawler session id after this thread ended
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
database::DatabaseHelper & DB ()
gets the database.
bool FetchUrls (std::map< long long, htmlparser::DatabaseUrl > &urls)
fetches urls from cache/database and reserves them for crawling.
bool FetchHtmlCode (const std::map< long long, htmlparser::DatabaseUrl > &urls, std::vector< UrlFetchParam > &fetchParameters)
fetches html from given urls.
bool CommitPages (const std::vector< UrlFetchParam > &fetchParameters)
saves crawled urls and results to database.
void OnIdle ()
called when no urls are available.
virtual void OnExit ()
called when fetcher thread is going to exit.
bool GetNextCrawlerSessionID ()
called when a new crawlersession-id is needed.
bool GetUrlsFromDatabase (const std::vector< long long > &urlIDs, std::map< long long, htmlparser::DatabaseUrl > &urls)
called when url-ids are needed from database.
void RemoveCrawlerSessionID ()
removes active crawlersession-id from database.
void RemoveCrawlerReservation ()
removes pending reservations for url-ids from database.
bool GetHtmlCodeFromUrl (const long long urlID, const htmlparser::DatabaseUrl &url, network::HtmlData &htmlCode, long &httpCode, long long &urlStageID)
helper function for crawler:.UrlFetcherThread::FetchHtmlCode.
void SetThreadFunction (ThreadFunction pFunction)
Protected Attributes
long long crawlerSessionID
current crawlersession-id.
UrlFetcherThreadParam * fetcherThreadParam
parameters attached to this url fetcher thread.
Private Member Functions
virtual bool GetNextSecondLevelDomain ()
called when secondleveldomain id should be changed if possible.
virtual bool ReserveNextUrls (std::vector< long long > &urlIDs)
called when more url-ids are needed and should be reserved
Private Attributes
std::map< long long,
CustomerDomainProperties > mapCustDomIdProperties
std::map< long long, time_t > activeCustomerDomainIds
Detailed Description
url fetcher implementation for commerce search.
See also:
crawler::CommerceSearchCrawler
crawler::UrlFetcherThread this class implements the crawler::UrlFetcherThread for the commerce search.
Definition at line 27 of file CommerceSearchFetcherThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
crawler::CommerceSearchFetcherThread::CommerceSearchFetcherThread ()
Definition at line 29 of file CommerceSearchFetcherThread.cpp.
crawler::CommerceSearchFetcherThread::~CommerceSearchFetcherThread () [virtual]
Definition at line 33 of file CommerceSearchFetcherThread.cpp.
Member Function Documentation
bool crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain () [private, virtual]
called when secondleveldomain id should be changed if possible.
Returns:
false on error, true on success.
Implements crawler::UrlFetcherThread.
Definition at line 37 of file CommerceSearchFetcherThread.cpp.
References activeCustomerDomainIds, database::WhereCondition::And(), database::DatabaseHelper::Connection(), crawler::UrlFetcherThread::crawlerSessionID, database::customerdomainsTableBase::CreateTableDefinition(), crawler::CommerceSearchFetcherThread::CustomerDomainProperties::customerDomainId, crawler::UrlFetcherThread::DB(), database::WhereCondition::Equals(), tools::Pointer< T >::Get(), database::customerdomainsTableBase::Get_CUSTOMER_ID(), database::customersynccrawlerTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerdomainsTableBase::Get_domain(), database::customerdomainsTableBase::Get_ID(), database::customerdomainsTableBase::Get_revisitInterval(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), caching::CacheDatabaseUrl::GetByUrlString(), tools::PointerContainer< T >::GetIter(), htmlparser::DatabaseUrl::GetUrlID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_scheduled(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), database::TableBaseUpdateParam::limit, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, mapCustDomIdProperties, MAX_AGE_MINUTES_SECONDLEVELDOMAIN, MAX_CUSTOMERDOMAINS_PER_THREAD, tools::PointerContainer< T >::Next(), tools::TimeTools::NowUTC(), tools::TimeTools::NowUTCAdd(), crawler::UrlFetcherThread::OnIdle(), database::TableBaseUpdateParam::onlyDirtyColumns, RESCHEDULE_MAX_AGE_DAYS_SECONDLEVELDOMAIN, tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), database::customersynccrawlerTableBase::Set_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Set_scheduled(), tools::PointerContainer< T >::Size(), database::WhereCondition::SmallerOrEqual(), database::TableBase::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by ReserveNextUrls().
bool crawler::CommerceSearchFetcherThread::ReserveNextUrls (std::vector< long long > & urlIDs) [private, virtual]
called when more url-ids are needed and should be reserved
Parameters:
urlIDs gets filled with reserved url ids.
Returns:
false on error, true on success.
Implements crawler::UrlFetcherThread.
Definition at line 152 of file CommerceSearchFetcherThread.cpp.
References activeCustomerDomainIds, crawler::UrlFetcherThread::DB(), crawler::UrlFetcherThread::fetcherThreadParam, caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), GetNextSecondLevelDomain(), database::TableBase::InsertOrUpdate(), mapCustDomIdProperties, crawler::CrawlerParam::maxPerSelect, tools::TimeTools::NowUTCAdd(), crawler::UrlFetcherThread::OnIdle(), RESCHEDULE_MAX_AGE_DAYS_URL, database::customersyncurlTableBase::Set_scheduled(), and database::customersyncurlTableBase::Set_URL_ID().
long long crawler::UrlFetcherThread::GetOldCrawlerSessionID () const [inherited]
gets old crawler session id after this thread ended
Definition at line 442 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::oldCrawlerSessionID.
database::DatabaseHelper& crawler::UrlFetcherThread::DB () [inline, protected, inherited]
gets the database.
Returns:
database helper.
Definition at line 55 of file UrlFetcherThread.h.
References crawler::UrlFetcherThread::databaseHelper.
Referenced by crawler::UrlFetcherThread::FetchHtmlCode(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::UrlFetcherThread::GetNextCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), GetNextSecondLevelDomain(), crawler::UrlFetcherThread::GetUrlsFromDatabase(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::UrlFetcherThread::RemoveCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), ReserveNextUrls(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::FetchUrls (std::map< long long, htmlparser::DatabaseUrl > & urls) [protected, inherited]
fetches urls from cache/database and reserves them for crawling.
Parameters:
urls gets filled with url-ids and urls.
Returns:
false on error, true on success.
Definition at line 107 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::GetUrlsFromDatabase(), and crawler::UrlFetcherThread::ReserveNextUrls().
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::FetchHtmlCode (const std::map< long long, htmlparser::DatabaseUrl > & urls, std::vector< UrlFetchParam > & fetchParameters) [protected, inherited]
fetches html from given urls.
Parameters:
urls map of url-ids and urls to be crawler.
fetchParameters gets filled with info from crawled pages
Returns:
false on error, true on success.
Definition at line 120 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::DB(), crawler::UrlFetcherThread::fetcherThreadParam, crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::UrlFetchParam::html, caching::CacheRobotsTxt::IsUrlAllowed(), crawler::CrawlerParam::respectRobotsTxt, crawler::UrlFetchParam::responseCode, crawler::UrlFetchParam::url, crawler::UrlFetchParam::urlID, crawler::UrlFetchParam::urlStageID, and crawler::CrawlerParam::userAgent.
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::CommitPages (const std::vector< UrlFetchParam > & fetchParameters) [protected, inherited]
saves crawled urls and results to database.
Parameters:
fetchParameters
Returns:
false on error, true on success.
Definition at line 141 of file UrlFetcherThread.cpp.
References caching::CacheHtml::Add(), log::Logging::IsLogLevelTrace(), log::Logging::Log(), and log::Logging::LOGLEVEL_TRACE.
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
void crawler::UrlFetcherThread::OnIdle () [protected, inherited]
called when no urls are available.
Definition at line 234 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::fetcherThreadParam, threading::Thread::ShallEnd(), and crawler::CrawlerParam::waitOnIdle.
Referenced by crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), GetNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and ReserveNextUrls().
virtual void crawler::UrlFetcherThread::OnExit () [inline, protected, virtual, inherited]
called when fetcher thread is going to exit.
Reimplemented in crawler::GenericWebUrlFetcherThread.
Definition at line 103 of file UrlFetcherThread.h.
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::GetNextCrawlerSessionID () [protected, inherited]
called when a new crawlersession-id is needed.
result is written to UrlFetcherThread::crawlerSessionID.
Returns:
false on error, true on success.
Definition at line 164 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::crawlerSessionID, crawler::UrlFetcherThread::DB(), database::TableBase::Insert(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, crawler::UrlFetcherThread::oldCrawlerSessionID, PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::GetUrlsFromDatabase (const std::vector< long long > & urlIDs, std::map< long long, htmlparser::DatabaseUrl > & urls) [protected, inherited]
called when url-ids are needed from database.
Parameters:
urlIDs url-ids to look for.
urls gets filled with url-ids and urls.
Returns:
false on error, true on success.
Definition at line 180 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::DB(), caching::CacheDatabaseUrl::GetByUrlID(), PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by crawler::UrlFetcherThread::FetchUrls().
void crawler::UrlFetcherThread::RemoveCrawlerSessionID () [protected, inherited]
removes active crawlersession-id from database.
Definition at line 210 of file UrlFetcherThread.cpp.
References database::WhereCondition::AddColumns(), database::DatabaseHelper::Connection(), crawler::UrlFetcherThread::crawlerSessionID, database::crawlersessionsTableBase::CreateTableDefinition(), crawler::UrlFetcherThread::DB(), database::DatabaseConnection::Delete(), database::WhereCondition::Equals(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, and database::DeleteStatement::Where().
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
void crawler::UrlFetcherThread::RemoveCrawlerReservation () [protected, inherited]
removes pending reservations for url-ids from database.
Definition at line 188 of file UrlFetcherThread.cpp.
References crawler::UrlFetcherThread::crawlerSessionID, crawler::UrlFetcherThread::DB(), database::WhereCondition::Equals(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::WhereCondition::InitialComp(), database::TableBaseUpdateParam::limit, tools::TimeTools::NowUTC(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_schedule(), database::TableBase::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::GetHtmlCodeFromUrl (const long long urlID, const htmlparser::DatabaseUrl & url, network::HtmlData & htmlCode, long & httpCode, long long & urlStageID) [protected, inherited]
helper function for crawler:.UrlFetcherThread::FetchHtmlCode.
Parameters:
urlID url-id
url parsed url.
htmlCode gets filled with html code.
httpCode returned http status code.
urlStageID urlstage-id.
Returns:
false on error, true on success.
Definition at line 240 of file UrlFetcherThread.cpp.
References crawler::CrawlerParam::clientType, database::DatabaseHelper::Connection(), crawler::CrawlerParam::connectionTimeout, crawler::CrawlerParam::connectTimeout, network::HttpResponse::contentLength, network::HttpClientFactory::CreateInstance(), crawler::UrlFetcherThread::DB(), network::HttpResponse::downloadSpeed, crawler::UrlFetcherThread::fetcherThreadParam, network::HtmlData::GetBuffer(), network::HtmlData::GetContentType(), network::HttpUrl::GetFullUrl(), tools::HashTools::GetMD5(), network::HttpResponse::html, network::HttpResponse::httpResponseCode, tools::TimeTools::InitTm(), database::TableBase::Insert(), database::TableBase::InsertOrUpdate(), log::Logging::IsLogLevelTrace(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, tools::TimeTools::NowUTC(), PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, network::HttpResponse::primaryIP, network::HttpResponse::primaryPort, network::HttpResponse::redirectUrls, tools::MemoryContainer< T >::Release(), database::documentcodeTableBase::Set_code(), database::urlstagesTableBase::Set_content_length(), database::urlstagesTableBase::Set_content_md5(), database::urlstagesTableBase::Set_content_type(), database::urlstagesTableBase::Set_download_speed(), database::urlstagesTableBase::Set_download_time(), database::urlstagesTableBase::Set_found_date(), database::urlstagesTableBase::Set_last_change(), database::urlstagesTableBase::Set_primary_ip(), database::urlstagesTableBase::Set_primary_port(), database::urlstagesTableBase::Set_redirect_count(), database::urlstagesTableBase::Set_response_code(), database::urlstagesTableBase::Set_upload_speed(), database::latesturlstagesTableBase::Set_URL_ID(), database::urlstagesTableBase::Set_URL_ID(), database::documentcodeTableBase::Set_URLSTAGE_ID(), database::latesturlstagesTableBase::Set_URLSTAGE_ID(), crawler::CrawlerParam::speedLimitKB, tools::MemoryContainer< T >::Swap(), network::HttpResponse::totalTime, network::HttpResponse::uploadSpeed, crawler::CrawlerParam::useIPv6, network::HttpClientSettings::userAgent, and crawler::CrawlerParam::userAgent.
Referenced by crawler::UrlFetcherThread::FetchHtmlCode().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
std::map<long long, CustomerDomainProperties > crawler::CommerceSearchFetcherThread::mapCustDomIdProperties [private]
Definition at line 62 of file CommerceSearchFetcherThread.h.
Referenced by GetNextSecondLevelDomain(), and ReserveNextUrls().
std::map<long long,time_t> crawler::CommerceSearchFetcherThread::activeCustomerDomainIds [private]
Definition at line 63 of file CommerceSearchFetcherThread.h.
Referenced by GetNextSecondLevelDomain(), and ReserveNextUrls().
long long crawler::UrlFetcherThread::crawlerSessionID [protected, inherited]
current crawlersession-id.
Definition at line 145 of file UrlFetcherThread.h.
Referenced by crawler::UrlFetcherThread::GetNextCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::UrlFetcherThread::RemoveCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
UrlFetcherThreadParam* crawler::UrlFetcherThread::fetcherThreadParam [protected, inherited]
parameters attached to this url fetcher thread.
Definition at line 150 of file UrlFetcherThread.h.
Referenced by crawler::UrlFetcherThread::FetchHtmlCode(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), crawler::UrlFetcherThread::OnIdle(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), ReserveNextUrls(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
The documentation for this class was generated from the following files:
Crawler/src/CommerceSearchFetcherThread.h
Crawler/src/CommerceSearchFetcherThread.cpp