DeepNet: domparser::html5::Tokeniser Class Reference
domparser::html5::Tokeniser Class Reference
standard compliant html5 tokeniser
#include <Tokeniser.h>
Public Member Functions
virtual ~Tokeniser ()
bool Parse (const char *pData, const size_t &size, const bool logVerbose=false)
parses html document from a string.
uintptr_t MapToOriginalPosition (const uintptr_t &pos) const
gets position in document (before comments etc.
void GetCurLineCol (size_t &line, size_t &col) const
void InitLineVector ()
initializes internal column/line tracking
std::string GetLineColumnString () const
gets preformated column and line string for current position
Protected Member Functions
virtual void EmitCharacter (const char charToEmit)
virtual void EmitComment ()
virtual void EmitTag ()
virtual void EmitDocType ()
virtual void SwitchState (const TokeniserState &newState)
virtual void ParseError () const
Protected Attributes
TokeniserState state
Private Member Functions
Tokeniser (DocumentFactory &factory)
bool OnDataState ()
bool OnCharacterReferenceInDataState ()
bool OnTagOpenState ()
bool OnMarkupDeclarationOpenState ()
bool OnEndTagOpenState ()
bool OnBogusCommentState ()
bool OnTagNameState ()
bool OnCommentStartState ()
bool OnDoctypeState ()
bool OnCDataSectionState ()
bool OnBeforeAttributeNameState ()
bool OnSelfClosingStartTagState ()
bool OnCommentStartDashState ()
bool OnCommentState ()
bool OnBeforeDoctypeNameState ()
bool OnAttributeNameState ()
bool OnCommentEndDashState ()
bool OnDoctypeNameState ()
bool OnAfterAttributeNameState ()
bool OnBeforeAttributeValueState ()
bool OnCommentEndState ()
bool OnAfterDoctypeNameState ()
bool OnAttributeValueDoubleQuotedState ()
bool OnAttributeValueSingleQuotedState ()
bool OnAttributeValueUnquotedState ()
bool OnCommentEndBangState ()
bool OnBogusDoctypeState ()
bool OnAfterDoctypePublicKeywordState ()
bool OnAfterDoctypeSystemKeywordState ()
bool AfterAttributeValueQuotedState ()
bool CharacterReferenceInAttributeValueState ()
bool OnBeforeDoctypePublicIdentifierState ()
bool OnDoctypePublicIdentifierDoubleQuotedState ()
bool OnDoctypePublicIdentifierSingleQuotedState ()
bool OnBeforeDoctypeSystemIdentifierState ()
bool OnDoctypeSystemIdentifierDoubleQuotedState ()
bool OnDoctypeSystemIdentifierSingleQuotedState ()
bool OnAfterDoctypePublicIdentifierState ()
bool OnAfterDoctypeSystemIdentifierState ()
bool OnBetweenDoctypePublicAndSystemIdentifiersState ()
bool OnRCDATAState ()
bool OnCharacterReferenceInRCDATAState ()
bool OnRCDATALessThanSignState ()
bool OnRCDATAEndTagOpenState ()
bool OnRCDATAEndTagNameState ()
bool OnScriptDataState ()
bool OnScriptDataLessThanSignState ()
bool OnScriptDataEndTagOpenState ()
bool OnScriptDataEscapeStartState ()
bool OnScriptDataEndTagNameState ()
bool OnScriptDataEscapeStartDashState ()
bool OnScriptDataEscapedDashDashState ()
bool OnScriptDataEscapedLessThanSignState ()
bool OnScriptDataEscapedState ()
bool OnScriptDataEscapedDashState ()
bool OnScriptDataEscapedEndTagOpenState ()
bool OnScriptDataEscapedEndTagNameState ()
bool OnScriptDataDoubleEscapeStartState ()
bool OnScriptDataDoubleEscapedState ()
bool OnScriptDataDoubleEscapedDashState ()
bool OnScriptDataDoubleEscapedDashDashState ()
bool OnScriptDataDoubleEscapedLessThanSignState ()
bool OnScriptDataDoubleEscapeEndState ()
bool OnRAWTEXTState ()
bool OnRAWTEXTLessThanSignState ()
bool OnRAWTEXTEndTagOpenState ()
bool OnRAWTEXTEndTagNameState ()
bool OnPLAINTEXTState ()
bool ProcessState ()
void EmitCharacter (const char *charToEmit, const size_t size=1)
std::string ConsumeCharacterReference (const char *additionalCharacterAllowed=NULL)
size_t ConsumeNamedCharacterReference (char *tmpCur) const
size_t ConsumeNumericCharacterReference (char *tmpCur) const
bool IsAppropriateEndTag () const
void ResetAllTokens ()
char * Consume (size_t count=1)
Private Attributes
DocumentFactory & factory
char * next
const char * start
const char * end
size_t size
database::DatabaseConnection * db
bool logVerbose
domparser::generic::TagToken tagToken
domparser::generic::CommentToken commentToken
domparser::generic::DocTypeToken doctypeToken
TokeniserState preCharRefInAttribState
char charRefInAttribValAddChar
std::string temporaryBuffer
std::string lastStartTagName
std::vector< std::pair< size_t,
size_t > > lines
Friends
class domparser::DocumentFactory
class toolbot::UnitTestHtmlTokeniser
Detailed Description
standard compliant html5 tokeniser
Definition at line 36 of file Tokeniser.h.
Constructor & Destructor Documentation
domparser::html5::Tokeniser::Tokeniser (DocumentFactory & factory) [private]
Definition at line 22 of file Tokeniser.cpp.
domparser::html5::Tokeniser::~Tokeniser () [virtual]
Definition at line 31 of file Tokeniser.cpp.
Member Function Documentation
bool domparser::html5::Tokeniser::Parse (const char * pData, const size_t & size, const bool logVerbose = false)
parses html document from a string.
Parameters:
pData raw html buffer.
size size of html buffer.
logVerbose true to produce heavily verbose output.
Returns:
false on error, true on success.
Definition at line 1939 of file Tokeniser.cpp.
References domparser::html5::Data_state, db, end, InitLineVector(), logVerbose, next, ProcessState(), ResetAllTokens(), size, start, and SwitchState().
Referenced by domparser::DocumentFactory::FromHtmlData(), and toolbot::UnitTestHtmlDocumentFactory::Run().
uintptr_t domparser::html5::Tokeniser::MapToOriginalPosition (const uintptr_t & pos) const
gets position in document (before comments etc.
where removed)
Parameters:
pos position in "cleaned" document
Returns:
original position
void domparser::html5::Tokeniser::GetCurLineCol (size_t & line, size_t & col) const
Definition at line 2220 of file Tokeniser.cpp.
References lines, next, and start.
Referenced by GetLineColumnString().
void domparser::html5::Tokeniser::InitLineVector ()
initializes internal column/line tracking
Definition at line 2189 of file Tokeniser.cpp.
References end, lines, and start.
Referenced by Parse().
std::string domparser::html5::Tokeniser::GetLineColumnString () const
gets preformated column and line string for current position
Returns:
preformated column and line string
Definition at line 2239 of file Tokeniser.cpp.
References GetCurLineCol().
Referenced by toolbot::UnitTestHtmlTokeniser::EmitCharacter(), toolbot::UnitTestHtmlTokeniser::EmitComment(), toolbot::UnitTestHtmlTokeniser::EmitDocType(), toolbot::UnitTestHtmlTokeniser::EmitTag(), toolbot::UnitTestHtmlDocumentFactory::OnToken(), toolbot::UnitTestHtmlTokeniser::ParseError(), domparser::DocumentFactory::ParseError(), toolbot::UnitTestHtmlDocumentFactory::SwitchMode(), and toolbot::UnitTestHtmlTokeniser::SwitchState().
void domparser::html5::Tokeniser::EmitCharacter (const char charToEmit) [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlTokeniser.
Definition at line 1788 of file Tokeniser.cpp.
Referenced by OnCDataSectionState(), OnCharacterReferenceInDataState(), OnCharacterReferenceInRCDATAState(), OnDataState(), OnPLAINTEXTState(), OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRAWTEXTLessThanSignState(), OnRAWTEXTState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnRCDATALessThanSignState(), OnRCDATAState(), OnScriptDataDoubleEscapedDashDashState(), OnScriptDataDoubleEscapedDashState(), OnScriptDataDoubleEscapedLessThanSignState(), OnScriptDataDoubleEscapedState(), OnScriptDataDoubleEscapeEndState(), OnScriptDataDoubleEscapeStartState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedDashDashState(), OnScriptDataEscapedDashState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnScriptDataEscapedLessThanSignState(), OnScriptDataEscapedState(), OnScriptDataEscapeStartDashState(), OnScriptDataEscapeStartState(), OnScriptDataLessThanSignState(), OnScriptDataState(), and OnTagOpenState().
void domparser::html5::Tokeniser::EmitComment () [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlTokeniser.
Definition at line 1792 of file Tokeniser.cpp.
References commentToken, factory, domparser::DocumentFactory::OnToken(), and domparser::generic::CommentToken::Reset().
Referenced by OnBogusCommentState(), OnCommentEndBangState(), OnCommentStartDashState(), and OnCommentStartState().
void domparser::html5::Tokeniser::EmitTag () [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlTokeniser.
Definition at line 1798 of file Tokeniser.cpp.
References factory, lastStartTagName, domparser::generic::TagToken::name, domparser::DocumentFactory::OnToken(), domparser::generic::TagToken::Reset(), domparser::generic::TagToken::START_TAG, tagToken, and domparser::generic::TagToken::tagType.
Referenced by AfterAttributeValueQuotedState(), OnAttributeValueUnquotedState(), OnBeforeAttributeNameState(), OnBeforeAttributeValueState(), OnSelfClosingStartTagState(), and OnTagNameState().
void domparser::html5::Tokeniser::EmitDocType () [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlTokeniser.
Definition at line 1807 of file Tokeniser.cpp.
References doctypeToken, factory, domparser::DocumentFactory::OnToken(), and domparser::generic::DocTypeToken::Reset().
Referenced by OnAfterDoctypeNameState(), OnAfterDoctypePublicIdentifierState(), OnAfterDoctypePublicKeywordState(), OnAfterDoctypeSystemIdentifierState(), OnAfterDoctypeSystemKeywordState(), OnBeforeDoctypeNameState(), OnBeforeDoctypePublicIdentifierState(), OnBeforeDoctypeSystemIdentifierState(), OnBetweenDoctypePublicAndSystemIdentifiersState(), OnBogusDoctypeState(), OnDoctypeNameState(), OnDoctypePublicIdentifierDoubleQuotedState(), OnDoctypePublicIdentifierSingleQuotedState(), OnDoctypeSystemIdentifierDoubleQuotedState(), and OnDoctypeSystemIdentifierSingleQuotedState().
void domparser::html5::Tokeniser::SwitchState (const TokeniserState & newState) [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlTokeniser.
Definition at line 2185 of file Tokeniser.cpp.
References state.
Referenced by AfterAttributeValueQuotedState(), domparser::DocumentFactory::AppendGenericRCDATAOrRawText(), CharacterReferenceInAttributeValueState(), OnAfterAttributeNameState(), OnAfterDoctypeNameState(), OnAfterDoctypePublicIdentifierState(), OnAfterDoctypePublicKeywordState(), OnAfterDoctypeSystemIdentifierState(), OnAfterDoctypeSystemKeywordState(), OnAttributeNameState(), OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), OnAttributeValueUnquotedState(), OnBeforeAttributeNameState(), OnBeforeAttributeValueState(), OnBeforeDoctypeNameState(), OnBeforeDoctypePublicIdentifierState(), OnBeforeDoctypeSystemIdentifierState(), OnBetweenDoctypePublicAndSystemIdentifiersState(), OnBogusCommentState(), OnBogusDoctypeState(), OnCDataSectionState(), OnCharacterReferenceInDataState(), OnCharacterReferenceInRCDATAState(), OnCommentEndBangState(), OnCommentEndDashState(), OnCommentEndState(), OnCommentStartDashState(), OnCommentStartState(), OnCommentState(), OnDataState(), OnDoctypeNameState(), OnDoctypePublicIdentifierDoubleQuotedState(), OnDoctypePublicIdentifierSingleQuotedState(), OnDoctypeState(), OnDoctypeSystemIdentifierDoubleQuotedState(), OnDoctypeSystemIdentifierSingleQuotedState(), OnEndTagOpenState(), domparser::DocumentFactory::OnInHeadInsertion(), OnMarkupDeclarationOpenState(), OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRAWTEXTLessThanSignState(), OnRAWTEXTState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnRCDATALessThanSignState(), OnRCDATAState(), OnScriptDataDoubleEscapedDashDashState(), OnScriptDataDoubleEscapedDashState(), OnScriptDataDoubleEscapedLessThanSignState(), OnScriptDataDoubleEscapedState(), OnScriptDataDoubleEscapeEndState(), OnScriptDataDoubleEscapeStartState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedDashDashState(), OnScriptDataEscapedDashState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnScriptDataEscapedLessThanSignState(), OnScriptDataEscapedState(), OnScriptDataEscapeStartDashState(), OnScriptDataEscapeStartState(), OnScriptDataLessThanSignState(), OnScriptDataState(), OnSelfClosingStartTagState(), OnTagNameState(), OnTagOpenState(), and Parse().
void domparser::html5::Tokeniser::ParseError () const [protected, virtual]
Reimplemented in toolbot::UnitTestHtmlTokeniser.
Definition at line 34 of file Tokeniser.cpp.
References factory, and domparser::DocumentFactory::ParseError().
Referenced by AfterAttributeValueQuotedState(), ConsumeNamedCharacterReference(), ConsumeNumericCharacterReference(), OnAfterAttributeNameState(), OnAfterDoctypeNameState(), OnAfterDoctypePublicIdentifierState(), OnAfterDoctypePublicKeywordState(), OnAfterDoctypeSystemIdentifierState(), OnAfterDoctypeSystemKeywordState(), OnAttributeNameState(), OnAttributeValueUnquotedState(), OnBeforeAttributeNameState(), OnBeforeAttributeValueState(), OnBeforeDoctypeNameState(), OnBeforeDoctypePublicIdentifierState(), OnBeforeDoctypeSystemIdentifierState(), OnBetweenDoctypePublicAndSystemIdentifiersState(), OnCommentEndState(), OnCommentStartDashState(), OnDoctypePublicIdentifierDoubleQuotedState(), OnDoctypePublicIdentifierSingleQuotedState(), OnDoctypeState(), OnDoctypeSystemIdentifierDoubleQuotedState(), OnDoctypeSystemIdentifierSingleQuotedState(), OnEndTagOpenState(), OnMarkupDeclarationOpenState(), OnSelfClosingStartTagState(), and OnTagOpenState().
bool domparser::html5::Tokeniser::OnDataState () [private]
Definition at line 39 of file Tokeniser.cpp.
References domparser::html5::Character_reference_in_data_state, Consume(), EmitCharacter(), SwitchState(), and domparser::html5::Tag_open_state.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCharacterReferenceInDataState () [private]
Definition at line 57 of file Tokeniser.cpp.
References ConsumeCharacterReference(), domparser::html5::Data_state, EmitCharacter(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnTagOpenState () [private]
Definition at line 70 of file Tokeniser.cpp.
References domparser::html5::Bogus_comment_state, Consume(), domparser::html5::Data_state, EmitCharacter(), domparser::html5::End_tag_open_state, domparser::html5::Markup_declaration_open_state, domparser::generic::TagToken::name, next, ParseError(), domparser::generic::TagToken::START_TAG, SwitchState(), domparser::html5::Tag_name_state, tagToken, and domparser::generic::TagToken::tagType.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnMarkupDeclarationOpenState () [private]
Definition at line 104 of file Tokeniser.cpp.
References domparser::html5::Bogus_comment_state, domparser::html5::CDATA_section_state, domparser::html5::Comment_start_state, Consume(), domparser::html5::DOCTYPE_state, next, ParseError(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnEndTagOpenState () [private]
Definition at line 130 of file Tokeniser.cpp.
References domparser::html5::Bogus_comment_state, Consume(), domparser::html5::Data_state, domparser::generic::TagToken::END_TAG, domparser::generic::TagToken::name, ParseError(), SwitchState(), domparser::html5::Tag_name_state, tagToken, and domparser::generic::TagToken::tagType.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBogusCommentState () [private]
Definition at line 150 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, commentToken, Consume(), domparser::html5::Data_state, EmitComment(), end, next, size, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnTagNameState () [private]
Definition at line 169 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitTag(), domparser::generic::TagToken::name, domparser::html5::Self_closing_start_tag_state, SwitchState(), and tagToken.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCommentStartState () [private]
Definition at line 202 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, domparser::html5::Comment_start_dash_state, domparser::html5::Comment_state, commentToken, Consume(), domparser::html5::Data_state, EmitComment(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnDoctypeState () [private]
Definition at line 224 of file Tokeniser.cpp.
References domparser::html5::Before_DOCTYPE_name_state, Consume(), next, ParseError(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCDataSectionState () [private]
Definition at line 246 of file Tokeniser.cpp.
References Consume(), domparser::html5::Data_state, EmitCharacter(), end, next, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBeforeAttributeNameState () [private]
Definition at line 267 of file Tokeniser.cpp.
References domparser::html5::Attribute_name_state, Consume(), domparser::generic::TagToken::curAttrib, domparser::html5::Data_state, EmitTag(), domparser::generic::AttributeToken::name, ParseError(), domparser::generic::AttributeToken::Reset(), domparser::html5::Self_closing_start_tag_state, SwitchState(), and tagToken.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnSelfClosingStartTagState () [private]
Definition at line 302 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitTag(), next, ParseError(), domparser::generic::TagToken::selfClosingFlag, SwitchState(), and tagToken.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCommentStartDashState () [private]
Definition at line 323 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, domparser::html5::Comment_end_state, domparser::html5::Comment_state, commentToken, Consume(), domparser::html5::Data_state, EmitComment(), ParseError(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCommentState () [private]
Definition at line 348 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, domparser::html5::Comment_end_dash_state, commentToken, Consume(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBeforeDoctypeNameState () [private]
Definition at line 365 of file Tokeniser.cpp.
References Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_name_state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, domparser::generic::DocTypeToken::name, ParseError(), domparser::generic::DocTypeToken::pName, domparser::generic::DocTypeToken::Reset(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAttributeNameState () [private]
Definition at line 401 of file Tokeniser.cpp.
References domparser::html5::After_attribute_name_state, domparser::html5::Before_attribute_value_state, Consume(), domparser::generic::TagToken::curAttrib, domparser::html5::Data_state, domparser::generic::AttributeToken::name, ParseError(), domparser::html5::Self_closing_start_tag_state, SwitchState(), and tagToken.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCommentEndDashState () [private]
Definition at line 441 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, domparser::html5::Comment_end_state, domparser::html5::Comment_state, commentToken, Consume(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnDoctypeNameState () [private]
Definition at line 460 of file Tokeniser.cpp.
References domparser::html5::After_DOCTYPE_name_state, Consume(), domparser::html5::Data_state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::name, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAfterAttributeNameState () [private]
Definition at line 489 of file Tokeniser.cpp.
References domparser::generic::TagToken::attributes, domparser::html5::Before_attribute_value_state, Consume(), domparser::generic::TagToken::curAttrib, domparser::html5::Data_state, domparser::generic::AttributeToken::name, domparser::generic::TagToken::name, ParseError(), domparser::generic::AttributeToken::Reset(), domparser::html5::Self_closing_start_tag_state, SwitchState(), and tagToken.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBeforeAttributeValueState () [private]
Definition at line 533 of file Tokeniser.cpp.
References domparser::html5::Attribute_value__double_quoted__state, domparser::html5::Attribute_value__single_quoted__state, domparser::html5::Attribute_value__unquoted__state, Consume(), domparser::generic::TagToken::curAttrib, domparser::html5::Data_state, EmitTag(), ParseError(), SwitchState(), tagToken, and domparser::generic::AttributeToken::value.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCommentEndState () [private]
Definition at line 572 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, domparser::html5::Comment_end_bang_state, domparser::html5::Comment_state, commentToken, Consume(), domparser::html5::Data_state, ParseError(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAfterDoctypeNameState () [private]
Definition at line 598 of file Tokeniser.cpp.
References domparser::html5::After_DOCTYPE_public_keyword_state, domparser::html5::After_DOCTYPE_system_keyword_state, domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, doctypeToken, EmitDocType(), end, domparser::generic::DocTypeToken::force_quirks, ParseError(), SwitchState(), and tools::StringTools::ToLowerIP().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAttributeValueDoubleQuotedState () [private]
Definition at line 646 of file Tokeniser.cpp.
References domparser::html5::After_attribute_value__quoted__state, domparser::html5::Character_reference_in_attribute_value_state, charRefInAttribValAddChar, Consume(), domparser::generic::TagToken::curAttrib, preCharRefInAttribState, state, SwitchState(), tagToken, and domparser::generic::AttributeToken::value.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAttributeValueSingleQuotedState () [private]
Definition at line 667 of file Tokeniser.cpp.
References domparser::html5::After_attribute_value__quoted__state, domparser::html5::Character_reference_in_attribute_value_state, charRefInAttribValAddChar, Consume(), domparser::generic::TagToken::curAttrib, preCharRefInAttribState, state, SwitchState(), tagToken, and domparser::generic::AttributeToken::value.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAttributeValueUnquotedState () [private]
Definition at line 688 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, domparser::html5::Character_reference_in_attribute_value_state, charRefInAttribValAddChar, Consume(), domparser::generic::TagToken::curAttrib, domparser::html5::Data_state, EmitTag(), ParseError(), preCharRefInAttribState, state, SwitchState(), tagToken, and domparser::generic::AttributeToken::value.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCommentEndBangState () [private]
Definition at line 724 of file Tokeniser.cpp.
References domparser::generic::CommentToken::comment, domparser::html5::Comment_end_dash_state, domparser::html5::Comment_state, commentToken, Consume(), domparser::html5::Data_state, EmitComment(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBogusDoctypeState () [private]
Definition at line 747 of file Tokeniser.cpp.
References Consume(), domparser::html5::Data_state, EmitDocType(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAfterDoctypePublicKeywordState () [private]
Definition at line 762 of file Tokeniser.cpp.
References domparser::html5::Before_DOCTYPE_public_identifier_state, domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_public_identifier__double_quoted__state, domparser::html5::DOCTYPE_public_identifier__single_quoted__state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::pPublicIdentifier, domparser::generic::DocTypeToken::public_identifier, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAfterDoctypeSystemKeywordState () [private]
Definition at line 801 of file Tokeniser.cpp.
References domparser::html5::Before_DOCTYPE_system_identifier_state, domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_system_identifier__double_quoted__state, domparser::html5::DOCTYPE_system_identifier__single_quoted__state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::pSystemIdentifier, SwitchState(), and domparser::generic::DocTypeToken::system_identifier.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::AfterAttributeValueQuotedState () [private]
Definition at line 840 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitTag(), next, ParseError(), domparser::html5::Self_closing_start_tag_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::CharacterReferenceInAttributeValueState () [private]
Definition at line 869 of file Tokeniser.cpp.
References charRefInAttribValAddChar, ConsumeCharacterReference(), domparser::generic::TagToken::curAttrib, preCharRefInAttribState, SwitchState(), tagToken, and domparser::generic::AttributeToken::value.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBeforeDoctypePublicIdentifierState () [private]
Definition at line 881 of file Tokeniser.cpp.
References domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_public_identifier__double_quoted__state, domparser::html5::DOCTYPE_public_identifier__single_quoted__state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::pPublicIdentifier, domparser::generic::DocTypeToken::public_identifier, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnDoctypePublicIdentifierDoubleQuotedState () [private]
Definition at line 919 of file Tokeniser.cpp.
References domparser::html5::After_DOCTYPE_public_identifier_state, Consume(), domparser::html5::Data_state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::public_identifier, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnDoctypePublicIdentifierSingleQuotedState () [private]
Definition at line 941 of file Tokeniser.cpp.
References domparser::html5::After_DOCTYPE_public_identifier_state, Consume(), domparser::html5::Data_state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::public_identifier, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBeforeDoctypeSystemIdentifierState () [private]
Definition at line 963 of file Tokeniser.cpp.
References domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_system_identifier__double_quoted__state, domparser::html5::DOCTYPE_system_identifier__single_quoted__state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::pSystemIdentifier, SwitchState(), and domparser::generic::DocTypeToken::system_identifier.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnDoctypeSystemIdentifierDoubleQuotedState () [private]
Definition at line 1001 of file Tokeniser.cpp.
References domparser::html5::After_DOCTYPE_system_identifier_state, Consume(), domparser::html5::Data_state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), SwitchState(), and domparser::generic::DocTypeToken::system_identifier.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnDoctypeSystemIdentifierSingleQuotedState () [private]
Definition at line 1023 of file Tokeniser.cpp.
References domparser::html5::After_DOCTYPE_system_identifier_state, Consume(), domparser::html5::Data_state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), SwitchState(), and domparser::generic::DocTypeToken::system_identifier.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAfterDoctypePublicIdentifierState () [private]
Definition at line 1045 of file Tokeniser.cpp.
References domparser::html5::Between_DOCTYPE_public_and_system_identifiers_state, domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_system_identifier__double_quoted__state, domparser::html5::DOCTYPE_system_identifier__single_quoted__state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::pSystemIdentifier, SwitchState(), and domparser::generic::DocTypeToken::system_identifier.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnAfterDoctypeSystemIdentifierState () [private]
Definition at line 1082 of file Tokeniser.cpp.
References domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, EmitDocType(), ParseError(), and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnBetweenDoctypePublicAndSystemIdentifiersState () [private]
Definition at line 1105 of file Tokeniser.cpp.
References domparser::html5::Bogus_DOCTYPE_state, Consume(), domparser::html5::Data_state, domparser::html5::DOCTYPE_system_identifier__double_quoted__state, domparser::html5::DOCTYPE_system_identifier__single_quoted__state, doctypeToken, EmitDocType(), domparser::generic::DocTypeToken::force_quirks, ParseError(), domparser::generic::DocTypeToken::pSystemIdentifier, SwitchState(), and domparser::generic::DocTypeToken::system_identifier.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRCDATAState () [private]
Definition at line 1139 of file Tokeniser.cpp.
References domparser::html5::Character_reference_in_RCDATA_state, Consume(), EmitCharacter(), domparser::html5::RCDATA_less_than_sign_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnCharacterReferenceInRCDATAState () [private]
Definition at line 1157 of file Tokeniser.cpp.
References ConsumeCharacterReference(), EmitCharacter(), domparser::html5::RCDATA_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRCDATALessThanSignState () [private]
Definition at line 1170 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::RCDATA_end_tag_open_state, domparser::html5::RCDATA_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRCDATAEndTagOpenState () [private]
Definition at line 1187 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::generic::TagToken::END_TAG, domparser::generic::TagToken::name, next, domparser::html5::RCDATA_end_tag_name_state, domparser::html5::RCDATA_state, domparser::generic::TagToken::Reset(), SwitchState(), tagToken, domparser::generic::TagToken::tagType, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRCDATAEndTagNameState () [private]
Definition at line 1207 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitCharacter(), IsAppropriateEndTag(), domparser::generic::TagToken::name, next, domparser::html5::RCDATA_state, domparser::html5::Self_closing_start_tag_state, SwitchState(), tagToken, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataState () [private]
Definition at line 1253 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_less_than_sign_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataLessThanSignState () [private]
Definition at line 1268 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_end_tag_open_state, domparser::html5::Script_data_escape_start_state, domparser::html5::Script_data_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEndTagOpenState () [private]
Definition at line 1292 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::generic::TagToken::END_TAG, domparser::generic::TagToken::name, next, domparser::generic::TagToken::Reset(), domparser::html5::Script_data_end_tag_name_state, domparser::html5::Script_data_state, SwitchState(), tagToken, domparser::generic::TagToken::tagType, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapeStartState () [private]
Definition at line 1353 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_escape_start_dash_state, domparser::html5::Script_data_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEndTagNameState () [private]
Definition at line 1311 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitCharacter(), IsAppropriateEndTag(), domparser::generic::TagToken::name, next, domparser::html5::Script_data_state, domparser::html5::Self_closing_start_tag_state, SwitchState(), tagToken, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapeStartDashState () [private]
Definition at line 1369 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_escaped_dash_dash_state, domparser::html5::Script_data_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapedDashDashState () [private]
Definition at line 1385 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_escaped_less_than_sign_state, domparser::html5::Script_data_escaped_state, domparser::html5::Script_data_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapedLessThanSignState () [private]
Definition at line 1409 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_double_escape_start_state, domparser::html5::Script_data_escaped_end_tag_open_state, domparser::html5::Script_data_escaped_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapedState () [private]
Definition at line 1438 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_escaped_dash_state, domparser::html5::Script_data_escaped_less_than_sign_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapedDashState () [private]
Definition at line 1456 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_escaped_dash_state, domparser::html5::Script_data_escaped_less_than_sign_state, domparser::html5::Script_data_escaped_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapedEndTagOpenState () [private]
Definition at line 1476 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::generic::TagToken::END_TAG, domparser::generic::TagToken::name, next, domparser::html5::Script_data_end_tag_name_state, domparser::html5::Script_data_state, SwitchState(), tagToken, domparser::generic::TagToken::tagType, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataEscapedEndTagNameState () [private]
Definition at line 1494 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitCharacter(), IsAppropriateEndTag(), domparser::generic::TagToken::name, next, domparser::html5::Script_data_escaped_state, domparser::html5::Self_closing_start_tag_state, SwitchState(), tagToken, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataDoubleEscapeStartState () [private]
Definition at line 1537 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_double_escaped_state, domparser::html5::Script_data_escaped_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataDoubleEscapedState () [private]
Definition at line 1569 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_double_escaped_dash_state, domparser::html5::Script_data_double_escaped_less_than_sign_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataDoubleEscapedDashState () [private]
Definition at line 1589 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_double_escaped_dash_dash_state, domparser::html5::Script_data_double_escaped_less_than_sign_state, domparser::html5::Script_data_double_escaped_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataDoubleEscapedDashDashState () [private]
Definition at line 1610 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::Script_data_double_escaped_less_than_sign_state, domparser::html5::Script_data_double_escaped_state, domparser::html5::Script_data_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataDoubleEscapedLessThanSignState () [private]
Definition at line 1635 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_double_escape_end_state, domparser::html5::Script_data_double_escaped_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnScriptDataDoubleEscapeEndState () [private]
Definition at line 1652 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::Script_data_double_escaped_state, domparser::html5::Script_data_escaped_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRAWTEXTState () [private]
Definition at line 1683 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::html5::RAWTEXT_less_than_sign_state, and SwitchState().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRAWTEXTLessThanSignState () [private]
Definition at line 1697 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), next, domparser::html5::RAWTEXT_end_tag_open_state, domparser::html5::RAWTEXT_state, SwitchState(), and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRAWTEXTEndTagOpenState () [private]
Definition at line 1714 of file Tokeniser.cpp.
References Consume(), EmitCharacter(), domparser::generic::TagToken::END_TAG, domparser::generic::TagToken::name, next, domparser::html5::RAWTEXT_end_tag_name_state, domparser::html5::RAWTEXT_state, SwitchState(), tagToken, domparser::generic::TagToken::tagType, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnRAWTEXTEndTagNameState () [private]
Definition at line 1732 of file Tokeniser.cpp.
References domparser::html5::Before_attribute_name_state, Consume(), domparser::html5::Data_state, EmitCharacter(), IsAppropriateEndTag(), domparser::generic::TagToken::name, next, domparser::html5::RAWTEXT_state, domparser::html5::Self_closing_start_tag_state, SwitchState(), tagToken, and temporaryBuffer.
Referenced by ProcessState().
bool domparser::html5::Tokeniser::OnPLAINTEXTState () [private]
Definition at line 1775 of file Tokeniser.cpp.
References Consume(), and EmitCharacter().
Referenced by ProcessState().
bool domparser::html5::Tokeniser::ProcessState () [private]
Definition at line 1961 of file Tokeniser.cpp.
References domparser::html5::After_attribute_name_state, domparser::html5::After_attribute_value__quoted__state, domparser::html5::After_DOCTYPE_name_state, domparser::html5::After_DOCTYPE_public_identifier_state, domparser::html5::After_DOCTYPE_public_keyword_state, domparser::html5::After_DOCTYPE_system_identifier_state, domparser::html5::After_DOCTYPE_system_keyword_state, AfterAttributeValueQuotedState(), domparser::html5::Attribute_name_state, domparser::html5::Attribute_value__double_quoted__state, domparser::html5::Attribute_value__single_quoted__state, domparser::html5::Attribute_value__unquoted__state, domparser::html5::Before_attribute_name_state, domparser::html5::Before_attribute_value_state, domparser::html5::Before_DOCTYPE_name_state, domparser::html5::Before_DOCTYPE_public_identifier_state, domparser::html5::Before_DOCTYPE_system_identifier_state, domparser::html5::Between_DOCTYPE_public_and_system_identifiers_state, domparser::html5::Bogus_comment_state, domparser::html5::Bogus_DOCTYPE_state, domparser::html5::CDATA_section_state, domparser::html5::Character_reference_in_attribute_value_state, domparser::html5::Character_reference_in_data_state, domparser::html5::Character_reference_in_RCDATA_state, CharacterReferenceInAttributeValueState(), domparser::html5::Comment_end_bang_state, domparser::html5::Comment_end_dash_state, domparser::html5::Comment_end_state, domparser::html5::Comment_start_dash_state, domparser::html5::Comment_start_state, domparser::html5::Comment_state, domparser::html5::Data_state, domparser::html5::DOCTYPE_name_state, domparser::html5::DOCTYPE_public_identifier__double_quoted__state, domparser::html5::DOCTYPE_public_identifier__single_quoted__state, domparser::html5::DOCTYPE_state, domparser::html5::DOCTYPE_system_identifier__double_quoted__state, domparser::html5::DOCTYPE_system_identifier__single_quoted__state, domparser::html5::End_tag_open_state, domparser::html5::Markup_declaration_open_state, OnAfterAttributeNameState(), OnAfterDoctypeNameState(), OnAfterDoctypePublicIdentifierState(), OnAfterDoctypePublicKeywordState(), OnAfterDoctypeSystemIdentifierState(), OnAfterDoctypeSystemKeywordState(), OnAttributeNameState(), OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), OnAttributeValueUnquotedState(), OnBeforeAttributeNameState(), OnBeforeAttributeValueState(), OnBeforeDoctypeNameState(), OnBeforeDoctypePublicIdentifierState(), OnBeforeDoctypeSystemIdentifierState(), OnBetweenDoctypePublicAndSystemIdentifiersState(), OnBogusCommentState(), OnBogusDoctypeState(), OnCDataSectionState(), OnCharacterReferenceInDataState(), OnCharacterReferenceInRCDATAState(), OnCommentEndBangState(), OnCommentEndDashState(), OnCommentEndState(), OnCommentStartDashState(), OnCommentStartState(), OnCommentState(), OnDataState(), OnDoctypeNameState(), OnDoctypePublicIdentifierDoubleQuotedState(), OnDoctypePublicIdentifierSingleQuotedState(), OnDoctypeState(), OnDoctypeSystemIdentifierDoubleQuotedState(), OnDoctypeSystemIdentifierSingleQuotedState(), OnEndTagOpenState(), OnMarkupDeclarationOpenState(), OnPLAINTEXTState(), OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRAWTEXTLessThanSignState(), OnRAWTEXTState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnRCDATALessThanSignState(), OnRCDATAState(), OnScriptDataDoubleEscapedDashDashState(), OnScriptDataDoubleEscapedDashState(), OnScriptDataDoubleEscapedLessThanSignState(), OnScriptDataDoubleEscapedState(), OnScriptDataDoubleEscapeEndState(), OnScriptDataDoubleEscapeStartState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedDashDashState(), OnScriptDataEscapedDashState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnScriptDataEscapedLessThanSignState(), OnScriptDataEscapedState(), OnScriptDataEscapeStartDashState(), OnScriptDataEscapeStartState(), OnScriptDataLessThanSignState(), OnScriptDataState(), OnSelfClosingStartTagState(), OnTagNameState(), OnTagOpenState(), domparser::html5::PLAINTEXT_state, domparser::html5::RAWTEXT_end_tag_name_state, domparser::html5::RAWTEXT_end_tag_open_state, domparser::html5::RAWTEXT_less_than_sign_state, domparser::html5::RAWTEXT_state, domparser::html5::RCDATA_end_tag_name_state, domparser::html5::RCDATA_end_tag_open_state, domparser::html5::RCDATA_less_than_sign_state, domparser::html5::RCDATA_state, domparser::html5::Script_data_double_escape_end_state, domparser::html5::Script_data_double_escape_start_state, domparser::html5::Script_data_double_escaped_dash_dash_state, domparser::html5::Script_data_double_escaped_dash_state, domparser::html5::Script_data_double_escaped_less_than_sign_state, domparser::html5::Script_data_double_escaped_state, domparser::html5::Script_data_end_tag_name_state, domparser::html5::Script_data_end_tag_open_state, domparser::html5::Script_data_escape_start_dash_state, domparser::html5::Script_data_escape_start_state, domparser::html5::Script_data_escaped_dash_dash_state, domparser::html5::Script_data_escaped_dash_state, domparser::html5::Script_data_escaped_end_tag_name_state, domparser::html5::Script_data_escaped_end_tag_open_state, domparser::html5::Script_data_escaped_less_than_sign_state, domparser::html5::Script_data_escaped_state, domparser::html5::Script_data_less_than_sign_state, domparser::html5::Script_data_state, domparser::html5::Self_closing_start_tag_state, state, domparser::html5::Tag_name_state, and domparser::html5::Tag_open_state.
Referenced by Parse().
void domparser::html5::Tokeniser::EmitCharacter (const char * charToEmit, const size_t size = 1) [private]
Definition at line 1780 of file Tokeniser.cpp.
References domparser::generic::CharacterToken::Append(), factory, domparser::DocumentFactory::OnToken(), and size.
std::string domparser::html5::Tokeniser::ConsumeCharacterReference (const char * additionalCharacterAllowed = NULL) [private]
Definition at line 1813 of file Tokeniser.cpp.
References Consume(), ConsumeNamedCharacterReference(), ConsumeNumericCharacterReference(), and next.
Referenced by CharacterReferenceInAttributeValueState(), OnCharacterReferenceInDataState(), and OnCharacterReferenceInRCDATAState().
size_t domparser::html5::Tokeniser::ConsumeNamedCharacterReference (char * tmpCur) const [private]
Definition at line 1851 of file Tokeniser.cpp.
References end, domparser::NamedCharacterReferences::IsRef(), ParseError(), and start.
Referenced by ConsumeCharacterReference().
size_t domparser::html5::Tokeniser::ConsumeNumericCharacterReference (char * tmpCur) const [private]
Definition at line 1879 of file Tokeniser.cpp.
References end, ParseError(), and start.
Referenced by ConsumeCharacterReference().
bool domparser::html5::Tokeniser::IsAppropriateEndTag () const [private]
Definition at line 2248 of file Tokeniser.cpp.
References domparser::generic::TagToken::END_TAG, lastStartTagName, domparser::generic::TagToken::name, tagToken, and domparser::generic::TagToken::tagType.
Referenced by OnRAWTEXTEndTagNameState(), OnRCDATAEndTagNameState(), OnScriptDataEndTagNameState(), and OnScriptDataEscapedEndTagNameState().
void domparser::html5::Tokeniser::ResetAllTokens () [private]
Definition at line 1933 of file Tokeniser.cpp.
References commentToken, doctypeToken, domparser::generic::TagToken::Reset(), domparser::generic::CommentToken::Reset(), domparser::generic::DocTypeToken::Reset(), and tagToken.
Referenced by Parse().
char * domparser::html5::Tokeniser::Consume (size_t count = 1) [private]
Definition at line 2179 of file Tokeniser.cpp.
References next.
Referenced by AfterAttributeValueQuotedState(), ConsumeCharacterReference(), OnAfterAttributeNameState(), OnAfterDoctypeNameState(), OnAfterDoctypePublicIdentifierState(), OnAfterDoctypePublicKeywordState(), OnAfterDoctypeSystemIdentifierState(), OnAfterDoctypeSystemKeywordState(), OnAttributeNameState(), OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), OnAttributeValueUnquotedState(), OnBeforeAttributeNameState(), OnBeforeAttributeValueState(), OnBeforeDoctypeNameState(), OnBeforeDoctypePublicIdentifierState(), OnBeforeDoctypeSystemIdentifierState(), OnBetweenDoctypePublicAndSystemIdentifiersState(), OnBogusCommentState(), OnBogusDoctypeState(), OnCDataSectionState(), OnCommentEndBangState(), OnCommentEndDashState(), OnCommentEndState(), OnCommentStartDashState(), OnCommentStartState(), OnCommentState(), OnDataState(), OnDoctypeNameState(), OnDoctypePublicIdentifierDoubleQuotedState(), OnDoctypePublicIdentifierSingleQuotedState(), OnDoctypeState(), OnDoctypeSystemIdentifierDoubleQuotedState(), OnDoctypeSystemIdentifierSingleQuotedState(), OnEndTagOpenState(), OnMarkupDeclarationOpenState(), OnPLAINTEXTState(), OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRAWTEXTLessThanSignState(), OnRAWTEXTState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnRCDATALessThanSignState(), OnRCDATAState(), OnScriptDataDoubleEscapedDashDashState(), OnScriptDataDoubleEscapedDashState(), OnScriptDataDoubleEscapedLessThanSignState(), OnScriptDataDoubleEscapedState(), OnScriptDataDoubleEscapeEndState(), OnScriptDataDoubleEscapeStartState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedDashDashState(), OnScriptDataEscapedDashState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnScriptDataEscapedLessThanSignState(), OnScriptDataEscapedState(), OnScriptDataEscapeStartDashState(), OnScriptDataEscapeStartState(), OnScriptDataLessThanSignState(), OnScriptDataState(), OnSelfClosingStartTagState(), OnTagNameState(), and OnTagOpenState().
Friends And Related Function Documentation
friend class domparser::DocumentFactory [friend]
Definition at line 38 of file Tokeniser.h.
friend class toolbot::UnitTestHtmlTokeniser [friend]
Definition at line 39 of file Tokeniser.h.
Member Data Documentation
TokeniserState domparser::html5::Tokeniser::state [protected]
Definition at line 172 of file Tokeniser.h.
Referenced by OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), OnAttributeValueUnquotedState(), ProcessState(), toolbot::UnitTestHtmlTokeniser::SwitchState(), and SwitchState().
DocumentFactory& domparser::html5::Tokeniser::factory [private]
Definition at line 175 of file Tokeniser.h.
Referenced by EmitCharacter(), EmitComment(), EmitDocType(), EmitTag(), and ParseError().
char* domparser::html5::Tokeniser::next [private]
Definition at line 176 of file Tokeniser.h.
Referenced by AfterAttributeValueQuotedState(), Consume(), ConsumeCharacterReference(), GetCurLineCol(), OnBogusCommentState(), OnCDataSectionState(), OnDoctypeState(), OnMarkupDeclarationOpenState(), OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRAWTEXTLessThanSignState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnRCDATALessThanSignState(), OnScriptDataDoubleEscapedLessThanSignState(), OnScriptDataDoubleEscapeEndState(), OnScriptDataDoubleEscapeStartState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnScriptDataEscapedLessThanSignState(), OnScriptDataEscapeStartDashState(), OnScriptDataEscapeStartState(), OnScriptDataLessThanSignState(), OnSelfClosingStartTagState(), OnTagOpenState(), and Parse().
const char* domparser::html5::Tokeniser::start [private]
Definition at line 177 of file Tokeniser.h.
Referenced by ConsumeNamedCharacterReference(), ConsumeNumericCharacterReference(), GetCurLineCol(), InitLineVector(), and Parse().
const char* domparser::html5::Tokeniser::end [private]
Definition at line 178 of file Tokeniser.h.
Referenced by ConsumeNamedCharacterReference(), ConsumeNumericCharacterReference(), InitLineVector(), OnAfterDoctypeNameState(), OnBogusCommentState(), OnCDataSectionState(), and Parse().
size_t domparser::html5::Tokeniser::size [private]
Definition at line 179 of file Tokeniser.h.
Referenced by EmitCharacter(), OnBogusCommentState(), and Parse().
database::DatabaseConnection* domparser::html5::Tokeniser::db [private]
Definition at line 180 of file Tokeniser.h.
Referenced by Parse().
bool domparser::html5::Tokeniser::logVerbose [private]
Definition at line 181 of file Tokeniser.h.
Referenced by Parse().
domparser::generic::TagToken domparser::html5::Tokeniser::tagToken [private]
Definition at line 183 of file Tokeniser.h.
Referenced by CharacterReferenceInAttributeValueState(), EmitTag(), IsAppropriateEndTag(), OnAfterAttributeNameState(), OnAttributeNameState(), OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), OnAttributeValueUnquotedState(), OnBeforeAttributeNameState(), OnBeforeAttributeValueState(), OnEndTagOpenState(), OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnSelfClosingStartTagState(), OnTagNameState(), OnTagOpenState(), and ResetAllTokens().
domparser::generic::CommentToken domparser::html5::Tokeniser::commentToken [private]
Definition at line 184 of file Tokeniser.h.
Referenced by EmitComment(), OnBogusCommentState(), OnCommentEndBangState(), OnCommentEndDashState(), OnCommentEndState(), OnCommentStartDashState(), OnCommentStartState(), OnCommentState(), and ResetAllTokens().
domparser::generic::DocTypeToken domparser::html5::Tokeniser::doctypeToken [private]
Definition at line 185 of file Tokeniser.h.
Referenced by EmitDocType(), OnAfterDoctypeNameState(), OnAfterDoctypePublicIdentifierState(), OnAfterDoctypePublicKeywordState(), OnAfterDoctypeSystemKeywordState(), OnBeforeDoctypeNameState(), OnBeforeDoctypePublicIdentifierState(), OnBeforeDoctypeSystemIdentifierState(), OnBetweenDoctypePublicAndSystemIdentifiersState(), OnDoctypeNameState(), OnDoctypePublicIdentifierDoubleQuotedState(), OnDoctypePublicIdentifierSingleQuotedState(), OnDoctypeSystemIdentifierDoubleQuotedState(), OnDoctypeSystemIdentifierSingleQuotedState(), and ResetAllTokens().
TokeniserState domparser::html5::Tokeniser::preCharRefInAttribState [private]
Definition at line 187 of file Tokeniser.h.
Referenced by CharacterReferenceInAttributeValueState(), OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), and OnAttributeValueUnquotedState().
char domparser::html5::Tokeniser::charRefInAttribValAddChar [private]
Definition at line 188 of file Tokeniser.h.
Referenced by CharacterReferenceInAttributeValueState(), OnAttributeValueDoubleQuotedState(), OnAttributeValueSingleQuotedState(), and OnAttributeValueUnquotedState().
std::string domparser::html5::Tokeniser::temporaryBuffer [private]
Definition at line 190 of file Tokeniser.h.
Referenced by OnRAWTEXTEndTagNameState(), OnRAWTEXTEndTagOpenState(), OnRAWTEXTLessThanSignState(), OnRCDATAEndTagNameState(), OnRCDATAEndTagOpenState(), OnRCDATALessThanSignState(), OnScriptDataDoubleEscapedLessThanSignState(), OnScriptDataDoubleEscapeEndState(), OnScriptDataDoubleEscapeStartState(), OnScriptDataEndTagNameState(), OnScriptDataEndTagOpenState(), OnScriptDataEscapedEndTagNameState(), OnScriptDataEscapedEndTagOpenState(), OnScriptDataEscapedLessThanSignState(), and OnScriptDataLessThanSignState().
std::string domparser::html5::Tokeniser::lastStartTagName [private]
Definition at line 191 of file Tokeniser.h.
Referenced by EmitTag(), and IsAppropriateEndTag().
std::vector< std::pair<size_t,size_t> > domparser::html5::Tokeniser::lines [private]
Definition at line 193 of file Tokeniser.h.
Referenced by GetCurLineCol(), and InitLineVector().
The documentation for this class was generated from the following files:
DOMParser/src/html5/Tokeniser.h
DOMParser/src/html5/Tokeniser.cpp