DeepNet: domparser::html5::OpenElementStack Class Reference
domparser::html5::OpenElementStack Class Reference
#include <OpenElementStack.h>
Public Member Functions
OpenElementStack ()
virtual ~OpenElementStack ()
void Push (const domparser::dom3::Node **value)
push value to stack not copying and not deleting.
void Push (const domparser::dom3::Node *&value)
copy and push value to stack.
void TryPop ()
tries to pop value from stack, throws exception if stack is empty.
void Pop ()
pop value from stack.
domparser::dom3::Node * PopDump ()
pop value from stack
domparser::dom3::Node *& Peek ()
peek stack.
domparser::dom3::Node *& Peek (size_t pos)
peek stack at position pos.
const domparser::dom3::Node *& ConstPeek () const
peek top of the stack.
const domparser::dom3::Node *& ConstPeek (size_t pos) const
peek stack at position pos.
size_t Size () const
get stack size.
Detailed Description
Definition at line 21 of file OpenElementStack.h.
Constructor & Destructor Documentation
domparser::html5::OpenElementStack::OpenElementStack ()
Definition at line 15 of file OpenElementStack.cpp.
domparser::html5::OpenElementStack::~OpenElementStack () [virtual]
Definition at line 18 of file OpenElementStack.cpp.
Member Function Documentation
void tools::Stack< domparser::dom3::Node * >::Push (const domparser::dom3::Node * * value) [inline, inherited]
push value to stack not copying and not deleting.
Parameters:
value value.
Definition at line 78 of file Stack.h.
References tools::Stack< T >::items.
void tools::Stack< domparser::dom3::Node * >::Push (const domparser::dom3::Node * & value) [inline, inherited]
copy and push value to stack.
Parameters:
value value.
Definition at line 86 of file Stack.h.
References tools::Stack< T >::items.
void tools::Stack< domparser::dom3::Node * >::TryPop () [inline, inherited]
tries to pop value from stack, throws exception if stack is empty.
Definition at line 93 of file Stack.h.
References tools::Stack< T >::Pop(), tools::Stack< T >::Size(), and THROW_EXCEPTION.
void tools::Stack< domparser::dom3::Node * >::Pop () [inline, inherited]
pop value from stack.
Definition at line 102 of file Stack.h.
References tools::Stack< T >::items, and tools::Stack< T >::Size().
domparser::dom3::Node * tools::Stack< domparser::dom3::Node * >::PopDump () [inline, inherited]
pop value from stack
Returns:
copy of the popped stack value.
Definition at line 115 of file Stack.h.
References tools::Stack< T >::items, tools::Stack< T >::Pop(), tools::Stack< T >::Size(), and THROW_EXCEPTION.
domparser::dom3::Node * & tools::Stack< domparser::dom3::Node * >::Peek () [inline, inherited]
peek stack.
Returns:
top stack value.
Definition at line 127 of file Stack.h.
References tools::Stack< T >::Peek(), and tools::Stack< T >::Size().
domparser::dom3::Node * & tools::Stack< domparser::dom3::Node * >::Peek (size_t pos) [inline, inherited]
peek stack at position pos.
Parameters:
pos position of item
Returns:
stack item.
Definition at line 136 of file Stack.h.
References tools::Stack< T >::items, tools::Stack< T >::Size(), and THROW_EXCEPTION.
const domparser::dom3::Node * & tools::Stack< domparser::dom3::Node * >::ConstPeek () const [inline, inherited]
peek top of the stack.
Returns:
top stack value.
Definition at line 146 of file Stack.h.
References tools::Stack< T >::ConstPeek(), and tools::Stack< T >::Size().
const domparser::dom3::Node * & tools::Stack< domparser::dom3::Node * >::ConstPeek (size_t pos) const [inline, inherited]
peek stack at position pos.
Parameters:
pos position of item
Returns:
stack item.
Definition at line 155 of file Stack.h.
References tools::Stack< T >::items, tools::Stack< T >::Size(), and THROW_EXCEPTION.
size_t tools::Stack< domparser::dom3::Node * >::Size () const [inline, inherited]
get stack size.
Returns:
stack size.
Definition at line 165 of file Stack.h.
References tools::Stack< T >::items.
The documentation for this class was generated from the following files:
DOMParser/src/html5/OpenElementStack.h
DOMParser/src/html5/OpenElementStack.cpp