DeepNet: Indexer/generated/meta_lexer.yy.cpp File Reference
Indexer/generated/meta_lexer.yy.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <string>
#include <iostream>
#include "meta_parser.tab.hpp"
#include "../src/MetaIndexer.h"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Defines
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE metaIndexer_yyrestart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_TYPEDEF_YY_SIZE_T
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER metaIndexer_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer metaIndexer_yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define FLEX_DEBUG
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 4
#define YY_END_OF_BUFFER 5
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_SKIP_YYWRAP
#define YY_DECL extern "C" int metaIndexer_yylex(YYSTYPE * yylval_param ,yyscan_t yyscanner)
#define YYSTYPE std::string*
#define COPY_TO_STD_STRING *metaIndexer_yylval = new std::string(); (*(*metaIndexer_yylval)) = metaIndexer_yytext;
#define YY_INPUT(buf, result, max_size) { int pos = yyextra->indexer->Read(buf,max_size); result = (pos > 0) ? pos : YY_NULL; }
#define INITIAL 0
#define YY_EXTRA_TYPE MetaIndexerCtx*
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void metaIndexer_yyrestart (FILE *input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
void metaIndexer_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
YY_BUFFER_STATE metaIndexer_yy_create_buffer (FILE *file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
void metaIndexer_yy_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
void metaIndexer_yy_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
void metaIndexer_yypush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
void metaIndexer_yypop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
static void metaIndexer_yyensure_buffer_stack (yyscan_t yyscanner)
static void metaIndexer_yy_load_buffer_state (yyscan_t yyscanner)
static void metaIndexer_yy_init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE metaIndexer_yy_scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE metaIndexer_yy_scan_string (yyconst char *yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE metaIndexer_yy_scan_bytes (yyconst char *yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
void * metaIndexer_yyalloc (yy_size_t, yyscan_t yyscanner)
void * metaIndexer_yyrealloc (void *, yy_size_t, yyscan_t yyscanner)
void metaIndexer_yyfree (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
static int metaIndexer_yywrap (yyscan_t)
int metaIndexer_yyerror (MetaIndexerCtx *, const char *)
int metaIndexer_yylex_init_extra (MetaIndexerCtx *yy_user_defined, yyscan_t *ptr_yy_globals)
int metaIndexer_yylex_destroy (yyscan_t ptr_yy_globals)
static int yy_init_globals (yyscan_t yyscanner)
int metaIndexer_yylex_init (yyscan_t *scanner)
int metaIndexer_yylex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
int metaIndexer_yyget_debug (yyscan_t yyscanner)
void metaIndexer_yyset_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE metaIndexer_yyget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
void metaIndexer_yyset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
FILE * metaIndexer_yyget_in (yyscan_t yyscanner)
Get the input stream.
void metaIndexer_yyset_in (FILE *in_str, yyscan_t yyscanner)
Set the input stream.
FILE * metaIndexer_yyget_out (yyscan_t yyscanner)
Get the output stream.
void metaIndexer_yyset_out (FILE *out_str, yyscan_t yyscanner)
int metaIndexer_yyget_leng (yyscan_t yyscanner)
Get the length of the current token.
char * metaIndexer_yyget_text (yyscan_t yyscanner)
Get the current token.
int metaIndexer_yyget_lineno (yyscan_t yyscanner)
Get the current line number.
void metaIndexer_yyset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
YYSTYPE * metaIndexer_yyget_lval (yyscan_t yyscanner)
void metaIndexer_yyset_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
static int input (yyscan_t yyscanner)
if (!yyg->yy_init)
while (1)
int isatty (int)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
int metaIndexer_yyget_column (yyscan_t yyscanner)
Get the current column number.
void metaIndexer_yyset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Variables
static yyconst flex_int16_t yy_nxt [][256]
static yyconst flex_int16_t yy_accept [45]
static yyconst flex_int32_t yy_rule_can_match_eol [5]
static yyconst yy_state_type yy_NUL_trans [45]
static yyconst flex_int16_t yy_rule_linenum [4]
YY_DECL register yy_state_type yy_current_state
The main scanner function which does all the work.
register char * yy_cp
register char * yy_bp
register int yy_act
struct yyguts_t * yyg = (struct yyguts_t*)yyscanner
yylval = yylval_param
Define Documentation
#define YY_INT_ALIGNED short int
Definition at line 5 of file meta_lexer.yy.cpp.
#define FLEX_SCANNER
Definition at line 17 of file meta_lexer.yy.cpp.
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 18 of file meta_lexer.yy.cpp.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 19 of file meta_lexer.yy.cpp.
#define YY_FLEX_SUBMINOR_VERSION 35
Definition at line 20 of file meta_lexer.yy.cpp.
#define FLEX_BETA
Definition at line 22 of file meta_lexer.yy.cpp.
#define FLEXINT_H
Definition at line 54 of file meta_lexer.yy.cpp.
#define INT8_MIN (-128)
Definition at line 84 of file meta_lexer.yy.cpp.
#define INT16_MIN (-32767-1)
Definition at line 87 of file meta_lexer.yy.cpp.
#define INT32_MIN (-2147483647-1)
Definition at line 90 of file meta_lexer.yy.cpp.
#define INT8_MAX (127)
Definition at line 93 of file meta_lexer.yy.cpp.
#define INT16_MAX (32767)
Definition at line 96 of file meta_lexer.yy.cpp.
#define INT32_MAX (2147483647)
Definition at line 99 of file meta_lexer.yy.cpp.
#define UINT8_MAX (255U)
Definition at line 102 of file meta_lexer.yy.cpp.
#define UINT16_MAX (65535U)
Definition at line 105 of file meta_lexer.yy.cpp.
#define UINT32_MAX (4294967295U)
Definition at line 108 of file meta_lexer.yy.cpp.
#define yyconst
Definition at line 138 of file meta_lexer.yy.cpp.
#define YY_NULL 0
Definition at line 144 of file meta_lexer.yy.cpp.
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 154 of file meta_lexer.yy.cpp.
Referenced by while(), and yy_get_previous_state().
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 161 of file meta_lexer.yy.cpp.
#define yyin yyg->yyin_r
Definition at line 167 of file meta_lexer.yy.cpp.
Referenced by if(), input(), metaIndexer_yy_load_buffer_state(), metaIndexer_yyget_in(), metaIndexer_yyrestart(), metaIndexer_yyset_in(), while(), yy_get_next_buffer(), and yy_init_globals().
#define yyout yyg->yyout_r
Definition at line 168 of file meta_lexer.yy.cpp.
Referenced by if(), metaIndexer_yyget_out(), metaIndexer_yyset_out(), and yy_init_globals().
#define yyextra yyg->yyextra_r
Definition at line 169 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yyget_extra(), and metaIndexer_yyset_extra().
#define yyleng yyg->yyleng_r
Definition at line 170 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yyget_leng(), and while().
#define yytext yyg->yytext_r
Definition at line 171 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yyget_text(), and while().
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 172 of file meta_lexer.yy.cpp.
Referenced by input(), metaIndexer_yyget_lineno(), metaIndexer_yyset_lineno(), and while().
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 173 of file meta_lexer.yy.cpp.
Referenced by input(), metaIndexer_yyget_column(), metaIndexer_yyset_column(), and while().
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 174 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yyget_debug(), metaIndexer_yyset_debug(), and while().
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 185 of file meta_lexer.yy.cpp.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 191 of file meta_lexer.yy.cpp.
Referenced by while().
#define YYSTATE YY_START
Definition at line 192 of file meta_lexer.yy.cpp.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 195 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_NEW_FILE metaIndexer_yyrestart(yyin ,yyscanner)
Definition at line 198 of file meta_lexer.yy.cpp.
Referenced by input(), and while().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 200 of file meta_lexer.yy.cpp.
Referenced by input(), metaIndexer_yy_flush_buffer(), metaIndexer_yy_scan_buffer(), metaIndexer_yy_scan_bytes(), and yy_get_next_buffer().
#define YY_BUF_SIZE 16384
Definition at line 211 of file meta_lexer.yy.cpp.
Referenced by if(), and metaIndexer_yyrestart().
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 217 of file meta_lexer.yy.cpp.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 220 of file meta_lexer.yy.cpp.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 232 of file meta_lexer.yy.cpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 233 of file meta_lexer.yy.cpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 234 of file meta_lexer.yy.cpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define YY_LESS_LINENO (n)
Value:
do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
Definition at line 243 of file meta_lexer.yy.cpp.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = yyg->yy_hold_char; \
                YY_RESTORE_YY_MORE_OFFSET \
                yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 3257 of file meta_lexer.yy.cpp.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 265 of file meta_lexer.yy.cpp.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 268 of file meta_lexer.yy.cpp.
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 273 of file meta_lexer.yy.cpp.
#define YY_BUFFER_NEW 0
Definition at line 325 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yy_flush_buffer(), metaIndexer_yy_scan_buffer(), and while().
#define YY_BUFFER_NORMAL 1
Definition at line 326 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 337 of file meta_lexer.yy.cpp.
Referenced by yy_get_next_buffer().
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 357 of file meta_lexer.yy.cpp.
Referenced by if(), metaIndexer_yy_delete_buffer(), metaIndexer_yy_flush_buffer(), metaIndexer_yy_init_buffer(), metaIndexer_yy_switch_to_buffer(), metaIndexer_yyget_column(), metaIndexer_yyget_lineno(), metaIndexer_yylex_destroy(), metaIndexer_yypop_buffer_state(), metaIndexer_yypush_buffer_state(), metaIndexer_yyrestart(), metaIndexer_yyset_column(), metaIndexer_yyset_lineno(), and yy_get_next_buffer().
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 364 of file meta_lexer.yy.cpp.
Referenced by if(), input(), metaIndexer_yy_delete_buffer(), metaIndexer_yy_load_buffer_state(), metaIndexer_yy_switch_to_buffer(), metaIndexer_yylex_destroy(), metaIndexer_yypop_buffer_state(), metaIndexer_yypush_buffer_state(), metaIndexer_yyrestart(), while(), and yy_get_next_buffer().
#define YY_FLUSH_BUFFER metaIndexer_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 387 of file meta_lexer.yy.cpp.
#define yy_new_buffer metaIndexer_yy_create_buffer
Definition at line 399 of file meta_lexer.yy.cpp.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        metaIndexer_yyensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            metaIndexer_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 401 of file meta_lexer.yy.cpp.
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        metaIndexer_yyensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            metaIndexer_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 411 of file meta_lexer.yy.cpp.
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 421 of file meta_lexer.yy.cpp.
#define FLEX_DEBUG
Definition at line 426 of file meta_lexer.yy.cpp.
#define yytext_ptr yytext_r
Definition at line 432 of file meta_lexer.yy.cpp.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
        yyleng = (size_t) (yy_cp - yy_bp); \
        yyg->yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
        yyg->yy_c_buf_p = yy_cp;
Definition at line 1871 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_NUM_RULES 4
Definition at line 1881 of file meta_lexer.yy.cpp.
#define YY_END_OF_BUFFER 5
Definition at line 1882 of file meta_lexer.yy.cpp.
Referenced by while().
#define REJECT reject_used_but_not_detected
Definition at line 1921 of file meta_lexer.yy.cpp.
#define yymore () yymore_used_but_not_detected
Definition at line 1922 of file meta_lexer.yy.cpp.
#define YY_MORE_ADJ 0
Definition at line 1923 of file meta_lexer.yy.cpp.
Referenced by while(), yy_get_next_buffer(), and yy_get_previous_state().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 1924 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_SKIP_YYWRAP
Definition at line 1928 of file meta_lexer.yy.cpp.
#define YY_DECL extern "C" int metaIndexer_yylex(YYSTYPE * yylval_param ,yyscan_t yyscanner)
Definition at line 1929 of file meta_lexer.yy.cpp.
#define YYSTYPE std::string*
Definition at line 1930 of file meta_lexer.yy.cpp.
#define COPY_TO_STD_STRING *metaIndexer_yylval = new std::string(); (*(*metaIndexer_yylval)) = metaIndexer_yytext;
Definition at line 1931 of file meta_lexer.yy.cpp.
#define YY_INPUT (buf, result, max_size) { int pos = yyextra->indexer->Read(buf,max_size); result = (pos > 0) ? pos : YY_NULL; }
Definition at line 1932 of file meta_lexer.yy.cpp.
Referenced by yy_get_next_buffer().
#define INITIAL 0
Definition at line 1949 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_EXTRA_TYPE MetaIndexerCtx*
Definition at line 1963 of file meta_lexer.yy.cpp.
#define yylval yyg->yylval_r
Definition at line 2014 of file meta_lexer.yy.cpp.
#define YY_READ_BUF_SIZE 8192
Definition at line 2111 of file meta_lexer.yy.cpp.
Referenced by yy_get_next_buffer().
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
Definition at line 2121 of file meta_lexer.yy.cpp.
Referenced by while().
#define yyterminate () return YY_NULL
Definition at line 2155 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_START_STACK_INCR 25
Definition at line 2160 of file meta_lexer.yy.cpp.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 2166 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yy_create_buffer(), metaIndexer_yy_scan_buffer(), metaIndexer_yy_scan_bytes(), metaIndexer_yyensure_buffer_stack(), while(), and yy_get_next_buffer().
#define YY_USER_ACTION
Definition at line 2206 of file meta_lexer.yy.cpp.
#define YY_BREAK break;
Definition at line 2211 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 2215 of file meta_lexer.yy.cpp.
Referenced by while().
#define YY_EXIT_FAILURE 2
Definition at line 3241 of file meta_lexer.yy.cpp.
Referenced by yy_fatal_error().
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                yytext[yyleng] = yyg->yy_hold_char; \
                yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
                yyg->yy_hold_char = *yyg->yy_c_buf_p; \
                *yyg->yy_c_buf_p = '\0'; \
                yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
Definition at line 3257 of file meta_lexer.yy.cpp.
#define YYTABLES_NAME "yytables"
Definition at line 3628 of file meta_lexer.yy.cpp.
Typedef Documentation
typedef signed char flex_int8_t
Definition at line 75 of file meta_lexer.yy.cpp.
typedef short int flex_int16_t
Definition at line 76 of file meta_lexer.yy.cpp.
typedef int flex_int32_t
Definition at line 77 of file meta_lexer.yy.cpp.
typedef unsigned char flex_uint8_t
Definition at line 78 of file meta_lexer.yy.cpp.
typedef unsigned short int flex_uint16_t
Definition at line 79 of file meta_lexer.yy.cpp.
typedef unsigned int flex_uint32_t
Definition at line 80 of file meta_lexer.yy.cpp.
typedef void* yyscan_t
Definition at line 162 of file meta_lexer.yy.cpp.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 221 of file meta_lexer.yy.cpp.
typedef size_t yy_size_t
Definition at line 269 of file meta_lexer.yy.cpp.
typedef unsigned char YY_CHAR
Definition at line 428 of file meta_lexer.yy.cpp.
typedef int yy_state_type
Definition at line 430 of file meta_lexer.yy.cpp.
Function Documentation
void metaIndexer_yyrestart (FILE * input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
Parameters:
input_file A readable stream.
yyscanner The scanner object.
Note:
This function does not reset the start condition to INITIAL .
Definition at line 2820 of file meta_lexer.yy.cpp.
References metaIndexer_yy_create_buffer(), metaIndexer_yy_init_buffer(), metaIndexer_yy_load_buffer_state(), metaIndexer_yyensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyin.
Referenced by input(), and yy_get_next_buffer().
void metaIndexer_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
Parameters:
new_buffer The new input buffer.
yyscanner The scanner object.
Definition at line 2842 of file meta_lexer.yy.cpp.
References metaIndexer_yy_load_buffer_state(), metaIndexer_yyensure_buffer_stack(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by metaIndexer_yy_scan_buffer().
YY_BUFFER_STATE metaIndexer_yy_create_buffer (FILE * file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
Parameters:
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
yyscanner The scanner object.
Returns:
the allocated buffer state.
Definition at line 2897 of file meta_lexer.yy.cpp.
References metaIndexer_yy_init_buffer(), metaIndexer_yyalloc(), yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by if(), and metaIndexer_yyrestart().
void metaIndexer_yy_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
Parameters:
b a buffer created with metaIndexer_yy_create_buffer()
yyscanner The scanner object.
Definition at line 2929 of file meta_lexer.yy.cpp.
References metaIndexer_yyfree(), yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_buffer_state::yy_is_our_buffer.
Referenced by metaIndexer_yylex_destroy(), and metaIndexer_yypop_buffer_state().
void metaIndexer_yy_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters:
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 3002 of file meta_lexer.yy.cpp.
References metaIndexer_yy_load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by metaIndexer_yy_init_buffer().
void metaIndexer_yypush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters:
new_buffer The new state.
yyscanner The scanner object.
Definition at line 3037 of file meta_lexer.yy.cpp.
References metaIndexer_yy_load_buffer_state(), metaIndexer_yyensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
void metaIndexer_yypop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Parameters:
yyscanner The scanner object.
Definition at line 3074 of file meta_lexer.yy.cpp.
References metaIndexer_yy_delete_buffer(), metaIndexer_yy_load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by metaIndexer_yylex_destroy().
static void metaIndexer_yyensure_buffer_stack (yyscan_t yyscanner) [static]
Definition at line 3100 of file meta_lexer.yy.cpp.
References metaIndexer_yyalloc(), metaIndexer_yyrealloc(), yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, and YY_FATAL_ERROR.
Referenced by if(), metaIndexer_yy_switch_to_buffer(), metaIndexer_yypush_buffer_state(), and metaIndexer_yyrestart().
static void metaIndexer_yy_load_buffer_state (yyscan_t yyscanner) [static]
Definition at line 2878 of file meta_lexer.yy.cpp.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yyin.
Referenced by if(), metaIndexer_yy_flush_buffer(), metaIndexer_yy_switch_to_buffer(), metaIndexer_yypop_buffer_state(), metaIndexer_yypush_buffer_state(), and metaIndexer_yyrestart().
static void metaIndexer_yy_init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) [static]
Definition at line 2964 of file meta_lexer.yy.cpp.
References isatty(), metaIndexer_yy_flush_buffer(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by metaIndexer_yy_create_buffer(), and metaIndexer_yyrestart().
YY_BUFFER_STATE metaIndexer_yy_scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters:
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 3155 of file meta_lexer.yy.cpp.
References metaIndexer_yy_switch_to_buffer(), metaIndexer_yyalloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by metaIndexer_yy_scan_bytes().
YY_BUFFER_STATE metaIndexer_yy_scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to metaIndexer_yylex() will scan from a copy of str.
Parameters:
yystr a NUL-terminated string to scan
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Note:
If you want to scan bytes that may contain NUL values, then use metaIndexer_yy_scan_bytes() instead.
Definition at line 3194 of file meta_lexer.yy.cpp.
References metaIndexer_yy_scan_bytes().
YY_BUFFER_STATE metaIndexer_yy_scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to metaIndexer_yylex() will scan from a copy of bytes.
Parameters:
yybytes the byte buffer to scan
_yybytes_len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 3209 of file meta_lexer.yy.cpp.
References metaIndexer_yy_scan_buffer(), metaIndexer_yyalloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by metaIndexer_yy_scan_string().
void * metaIndexer_yyalloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 3604 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yy_create_buffer(), metaIndexer_yy_scan_buffer(), metaIndexer_yy_scan_bytes(), metaIndexer_yyensure_buffer_stack(), metaIndexer_yylex_init(), and metaIndexer_yylex_init_extra().
void * metaIndexer_yyrealloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 3609 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yyensure_buffer_stack(), and yy_get_next_buffer().
void metaIndexer_yyfree (void * ptr, yyscan_t yyscanner)
Definition at line 3621 of file meta_lexer.yy.cpp.
Referenced by metaIndexer_yy_delete_buffer(), and metaIndexer_yylex_destroy().
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) [static]
Definition at line 2659 of file meta_lexer.yy.cpp.
References yy_accept, yyguts_t::yy_c_buf_p, yy_cp, yy_current_state, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yy_NUL_trans, yy_nxt, YY_SC_TO_UI, and yyguts_t::yy_start.
Referenced by while().
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) [static]
Definition at line 2696 of file meta_lexer.yy.cpp.
References yy_accept, yyguts_t::yy_c_buf_p, yy_cp, yy_current_state, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, and yy_NUL_trans.
Referenced by while().
static int yy_get_next_buffer (yyscan_t yyscanner) [static]
Definition at line 2518 of file meta_lexer.yy.cpp.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, metaIndexer_yyrealloc(), metaIndexer_yyrestart(), yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, and yyin.
Referenced by input(), and while().
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) [static]
static int metaIndexer_yywrap (yyscan_t) [static]
Definition at line 3642 of file meta_lexer.yy.cpp.
Referenced by input(), and while().
int metaIndexer_yyerror (MetaIndexerCtx * , const char *)
Definition at line 3637 of file meta_lexer.yy.cpp.
int metaIndexer_yylex_init_extra (MetaIndexerCtx * yy_user_defined, yyscan_t * ptr_yy_globals)
int metaIndexer_yylex_destroy (yyscan_t ptr_yy_globals)
Definition at line 3548 of file meta_lexer.yy.cpp.
References metaIndexer_yy_delete_buffer(), metaIndexer_yyfree(), metaIndexer_yypop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
static int yy_init_globals (yyscan_t yyscanner) [static]
Definition at line 3512 of file meta_lexer.yy.cpp.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
Referenced by metaIndexer_yylex_destroy(), metaIndexer_yylex_init(), and metaIndexer_yylex_init_extra().
int metaIndexer_yylex_init (yyscan_t * scanner)
Definition at line 3452 of file meta_lexer.yy.cpp.
References metaIndexer_yyalloc(), and yy_init_globals().
int metaIndexer_yylex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t * scanner)
Definition at line 3481 of file meta_lexer.yy.cpp.
References metaIndexer_yyalloc(), metaIndexer_yyset_extra(), and yy_init_globals().
int metaIndexer_yyget_debug (yyscan_t yyscanner)
Definition at line 3412 of file meta_lexer.yy.cpp.
References yy_flex_debug.
void metaIndexer_yyset_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 3418 of file meta_lexer.yy.cpp.
References yy_flex_debug.
YY_EXTRA_TYPE metaIndexer_yyget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters:
yyscanner The scanner object.
Definition at line 3279 of file meta_lexer.yy.cpp.
References yyextra.
void metaIndexer_yyset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner.
Parameters:
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 3356 of file meta_lexer.yy.cpp.
References yyextra.
Referenced by metaIndexer_yylex_init_extra().
FILE * metaIndexer_yyget_in (yyscan_t yyscanner)
Get the input stream.
Parameters:
yyscanner The scanner object.
Definition at line 3316 of file meta_lexer.yy.cpp.
References yyin.
void metaIndexer_yyset_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer.
Parameters:
in_str A readable stream.
yyscanner The scanner object.
See also:
metaIndexer_yy_switch_to_buffer
Definition at line 3400 of file meta_lexer.yy.cpp.
References yyin.
FILE * metaIndexer_yyget_out (yyscan_t yyscanner)
Get the output stream.
Parameters:
yyscanner The scanner object.
Definition at line 3325 of file meta_lexer.yy.cpp.
References yyout.
void metaIndexer_yyset_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 3406 of file meta_lexer.yy.cpp.
References yyout.
int metaIndexer_yyget_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters:
yyscanner The scanner object.
Definition at line 3334 of file meta_lexer.yy.cpp.
References yyleng.
char * metaIndexer_yyget_text (yyscan_t yyscanner)
Get the current token.
Parameters:
yyscanner The scanner object.
Definition at line 3344 of file meta_lexer.yy.cpp.
References yytext.
int metaIndexer_yyget_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters:
yyscanner The scanner object.
Definition at line 3290 of file meta_lexer.yy.cpp.
References YY_CURRENT_BUFFER, and yylineno.
void metaIndexer_yyset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 3368 of file meta_lexer.yy.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
YYSTYPE * metaIndexer_yyget_lval (yyscan_t yyscanner)
Definition at line 3431 of file meta_lexer.yy.cpp.
References yylval.
void metaIndexer_yyset_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 3437 of file meta_lexer.yy.cpp.
References yylval.
static int input (yyscan_t yyscanner) [static]
Definition at line 2730 of file meta_lexer.yy.cpp.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, if(), metaIndexer_yyrestart(), metaIndexer_yywrap(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, YY_NEW_FILE, yycolumn, yyin, and yylineno.
if (!yyg-> yy_init)
Definition at line 2236 of file meta_lexer.yy.cpp.
References metaIndexer_yy_create_buffer(), metaIndexer_yy_load_buffer_state(), metaIndexer_yyensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_init, yyguts_t::yy_start, yyin, and yyout.
while (1)
Definition at line 2270 of file meta_lexer.yy.cpp.
References ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, FACTFINDER_FLAG, GOOGLEANALYTICS_FLAG, INITIAL, metaIndexer_yywrap(), yy_accept, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, yy_current_state, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_flex_debug, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, yy_rule_can_match_eol, yy_rule_linenum, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yycolumn, yyin, yyleng, yylineno, yyterminate, and yytext.
int isatty (int)
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) [static]
Definition at line 3245 of file meta_lexer.yy.cpp.
References YY_EXIT_FAILURE.
int metaIndexer_yyget_column (yyscan_t yyscanner)
Get the current column number.
Parameters:
yyscanner The scanner object.
Definition at line 3303 of file meta_lexer.yy.cpp.
References YY_CURRENT_BUFFER, and yycolumn.
void metaIndexer_yyset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 3383 of file meta_lexer.yy.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
Variable Documentation
yyconst flex_int16_t yy_nxt[][256] [static]
Definition at line 433 of file meta_lexer.yy.cpp.
Referenced by while(), and yy_get_previous_state().
yyconst flex_int16_t yy_accept[45] [static]
Initial value:
    {   0,
        0,    0,    5,    3,    4,    3,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    1,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    2
    }
Definition at line 1890 of file meta_lexer.yy.cpp.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int32_t yy_rule_can_match_eol[5] [static]
Initial value:
    {   0,
0, 0, 0, 0,     }
Definition at line 1900 of file meta_lexer.yy.cpp.
Referenced by while().
yyconst yy_state_type yy_NUL_trans[45] [static]
Initial value:
    {   0,
        4,    4,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0
    }
Definition at line 1904 of file meta_lexer.yy.cpp.
Referenced by yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int16_t yy_rule_linenum[4] [static]
Initial value:
    {   0,
       31,   32,   33
    }
Definition at line 1913 of file meta_lexer.yy.cpp.
Referenced by while().
YY_DECL register yy_state_type yy_current_state
The main scanner function which does all the work.
Definition at line 2224 of file meta_lexer.yy.cpp.
register char* yy_cp
Definition at line 2225 of file meta_lexer.yy.cpp.
register char * yy_bp
Definition at line 2225 of file meta_lexer.yy.cpp.
register int yy_act
Definition at line 2226 of file meta_lexer.yy.cpp.
struct yyguts_t* yyg = (struct yyguts_t*)yyscanner
Definition at line 2227 of file meta_lexer.yy.cpp.
yylval = yylval_param
Definition at line 2234 of file meta_lexer.yy.cpp.