DeepNet: domparser::dom3::DOMException Class Reference
domparser::dom3::DOMException Class Reference
#include <DOMException.h>
Public Types
enum ExceptionCode {
INDEX_SIZE_ERR = 1, DOMSTRING_SIZE_ERR = 2, HIERARCHY_REQUEST_ERR = 3, WRONG_DOCUMENT_ERR = 4,
INVALID_CHARACTER_ERR = 5, NO_DATA_ALLOWED_ERR = 6, NO_MODIFICATION_ALLOWED_ERR = 7, NOT_FOUND_ERR = 8,
NOT_SUPPORTED_ERR = 9, INUSE_ATTRIBUTE_ERR = 10, INVALID_STATE_ERR = 11, SYNTAX_ERR = 12,
INVALID_MODIFICATION_ERR = 13, NAMESPACE_ERR = 14, INVALID_ACCESS_ERR = 15, VALIDATION_ERR = 16,
TYPE_MISMATCH_ERR = 17
}
Public Member Functions
DOMException (const std::string &file, const int line, const std::string &function, const ExceptionCode &error)
virtual ~DOMException ()
const ExceptionCode & code () const
void Log () const
log this exception.
void DisableLogging ()
prevent exception from being logged.
std::string Dump () const
dumps exception as string.
Static Public Member Functions
static void InitializeExceptionHandling ()
initializes exception handling for current process.
Protected Attributes
std::string file
originating filename
int line
originating source line.
std::string function
originating function.
std::string module
originating module.
std::string exceptionName
name of the exception.
std::string message
exception message.
std::string backtrace
backtrace.
bool logException
log this exception.
Private Attributes
ExceptionCode error
Detailed Description
Definition at line 17 of file DOMException.h.
Member Enumeration Documentation
enum domparser::dom3::DOMException::ExceptionCode
Enumerator:
INDEX_SIZE_ERR
DOMSTRING_SIZE_ERR
HIERARCHY_REQUEST_ERR
WRONG_DOCUMENT_ERR
INVALID_CHARACTER_ERR
NO_DATA_ALLOWED_ERR
NO_MODIFICATION_ALLOWED_ERR
NOT_FOUND_ERR
NOT_SUPPORTED_ERR
INUSE_ATTRIBUTE_ERR
INVALID_STATE_ERR
SYNTAX_ERR
INVALID_MODIFICATION_ERR
NAMESPACE_ERR
INVALID_ACCESS_ERR
VALIDATION_ERR
TYPE_MISMATCH_ERR
Definition at line 20 of file DOMException.h.
Constructor & Destructor Documentation
domparser::dom3::DOMException::DOMException (const std::string & file, const int line, const std::string & function, const ExceptionCode & error)
Definition at line 17 of file DOMException.cpp.
References error, and errors::Exception::message.
domparser::dom3::DOMException::~DOMException () [virtual]
Definition at line 30 of file DOMException.cpp.
Member Function Documentation
const ExceptionCode& domparser::dom3::DOMException::code () const [inline]
Definition at line 49 of file DOMException.h.
References error.
void errors::Exception::InitializeExceptionHandling () [static, inherited]
initializes exception handling for current process.
Definition at line 93 of file Exception.cpp.
References errors::Exception::TerminateHandler().
Referenced by fastcgiserver::FastCGIServer::FastCGIServer(), and bot::Bot::Run().
void errors::Exception::Log () const [inherited]
log this exception.
Definition at line 65 of file Exception.cpp.
References errors::Exception::Dump(), log::Logging::LOGLEVEL_ERROR, and log::Logging::LogUnlimited().
Referenced by errors::Exception::~Exception().
void errors::Exception::DisableLogging () [inherited]
prevent exception from being logged.
Definition at line 70 of file Exception.cpp.
References errors::Exception::logException.
Referenced by domparser::DOMParser::Parse(), toolbot::UnitTestHttpClientCURL::ReadURLFile(), and toolbot::UnitTestUrlParser::TestInvalidUrls().
std::string errors::Exception::Dump () const [inherited]
dumps exception as string.
Returns:
exception as string.
Definition at line 74 of file Exception.cpp.
References errors::Exception::backtrace, errors::Exception::exceptionName, errors::Exception::file, log::Logging::GetTimeString(), errors::Exception::line, errors::Exception::message, and errors::Exception::module.
Referenced by errors::Exception::Log(), toolbot::UnitTestUrlParser::TestInvalidUrls(), and toolbot::UnitTestUrlParser::TestValidUrls().
Member Data Documentation
ExceptionCode domparser::dom3::DOMException::error [private]
Definition at line 52 of file DOMException.h.
Referenced by code(), and DOMException().
std::string errors::Exception::file [protected, inherited]
originating filename
Definition at line 90 of file Exception.h.
Referenced by errors::Exception::Dump().
int errors::Exception::line [protected, inherited]
originating source line.
Definition at line 95 of file Exception.h.
Referenced by errors::Exception::Dump().
std::string errors::Exception::function [protected, inherited]
originating function.
Definition at line 100 of file Exception.h.
std::string errors::Exception::module [protected, inherited]
originating module.
Definition at line 105 of file Exception.h.
Referenced by errors::Exception::Dump().
std::string errors::Exception::exceptionName [protected, inherited]
name of the exception.
Definition at line 110 of file Exception.h.
Referenced by errors::Exception::Dump().
std::string errors::Exception::message [protected, inherited]
exception message.
Definition at line 115 of file Exception.h.
Referenced by DOMException(), and errors::Exception::Dump().
std::string errors::Exception::backtrace [protected, inherited]
backtrace.
Definition at line 120 of file Exception.h.
Referenced by errors::Exception::Dump(), and errors::Exception::TerminateHandler().
bool errors::Exception::logException [protected, inherited]
log this exception.
Definition at line 125 of file Exception.h.
Referenced by errors::Exception::DisableLogging(), and errors::Exception::~Exception().
The documentation for this class was generated from the following files:
DOMParser/src/DOM3/DOMException.h
DOMParser/src/DOM3/DOMException.cpp