DeepNet: caching::CacheParsed Class Reference
caching::CacheParsed Class Reference
cache for parsed html data.
#include <CacheParsed.h>
Classes
struct CacheParsedEntry
container for caching parsed html.
Public Member Functions
virtual ~CacheParsed ()
Static Public Member Functions
static void Add (CacheParsedEntry &entry)
add a new parsed site to cache.
static bool Get (std::map< long long, CacheParsedEntry > &entries, const int count)
gets multiple elements from cache.
static void SetCapacity (const size_t capacity)
set current limit of cache.
static size_t GetSize ()
gets current number of entries in cache.
static size_t GetMatches ()
get current match count of cache, clearing internal match counter.
static size_t GetMisses ()
get current miss count of cache, clearing internal miss counter.
Private Member Functions
CacheParsed (size_t limit=0)
Private Attributes
Cache< long long,
CacheParsedEntry > cacheParsed
Static Private Attributes
static CacheParsed cacheInstance
Detailed Description
cache for parsed html data.
Definition at line 22 of file CacheParsed.h.
Constructor & Destructor Documentation
caching::CacheParsed::CacheParsed (size_t limit = 0) [private]
Definition at line 13 of file CacheParsed.cpp.
caching::CacheParsed::~CacheParsed () [virtual]
Definition at line 18 of file CacheParsed.cpp.
Member Function Documentation
void caching::CacheParsed::Add (CacheParsedEntry & entry) [static]
add a new parsed site to cache.
Parameters:
entry info for parsed site.
Definition at line 22 of file CacheParsed.cpp.
References caching::Cache< T, V >::AddItem(), cacheInstance, cacheParsed, and caching::CacheParsed::CacheParsedEntry::urlID.
Referenced by parser::GenericWebHtmlParserThread::ParsePage().
bool caching::CacheParsed::Get (std::map< long long, CacheParsedEntry > & entries, const int count) [static]
gets multiple elements from cache.
Parameters:
entries gets filled with elements from cache.
count maximum number of elements in cache.
Returns:
false if cache is empty, true on success.
Definition at line 27 of file CacheParsed.cpp.
References cacheInstance, cacheParsed, and caching::Cache< T, V >::GetItem().
Referenced by indexing::IndexerThread::GetNextPages().
static void caching::CacheParsed::SetCapacity (const size_t capacity) [inline, static]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 75 of file CacheParsed.h.
References cacheInstance, cacheParsed, and caching::Cache< T, V >::SetLimit().
Referenced by bot::Bot::InitCacheConfigParams().
static size_t caching::CacheParsed::GetSize () [inline, static]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 81 of file CacheParsed.h.
References cacheInstance, cacheParsed, and caching::Cache< T, V >::GetSize().
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheParsed::GetMatches () [inline, static]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 87 of file CacheParsed.h.
References cacheInstance, cacheParsed, and caching::Cache< T, V >::GetMatches().
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheParsed::GetMisses () [inline, static]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 93 of file CacheParsed.h.
References cacheInstance, cacheParsed, and caching::Cache< T, V >::GetMisses().
Referenced by bot::Bot::WatchDog().
Member Data Documentation
CacheParsed caching::CacheParsed::cacheInstance [static, private]
Definition at line 96 of file CacheParsed.h.
Referenced by Add(), Get(), GetMatches(), GetMisses(), GetSize(), and SetCapacity().
Cache<long long, CacheParsedEntry> caching::CacheParsed::cacheParsed [private]
Definition at line 99 of file CacheParsed.h.
Referenced by Add(), Get(), GetMatches(), GetMisses(), GetSize(), and SetCapacity().
The documentation for this class was generated from the following files:
Caching/src/CacheParsed.h
Caching/src/CacheParsed.cpp