DeepNet: indexing::DataminingDictionary Class Reference
indexing::DataminingDictionary Class Reference
#include <DataminingDictionary.h>
Public Types
enum MetaInformationType {
META_UNKNOWN = 0, META_TITLE = 1, META_DESCRIPTION = 2, META_KEYWORDS = 3,
META_AUTHOR = 4, META_COPYRIGHT = 5, META_TYPE_MAX
}
Public Member Functions
DataminingDictionary (database::DatabaseConnection *database)
virtual ~DataminingDictionary ()
virtual bool CommitMeta (void)
virtual bool CommitContent (void)
bool AddContent (const std::string &word, const std::pair< long long, long long > &paragraphPosition)
bool AddContent (const std::string &word)
bool AddMeta (const std::string &word, const MetaInformationType &type)
void SetUrlID (const long long urlID, const long long urlStageID)
void SetTestMode (const bool testMode)
void Dump (std::string &dictDump) const
void DumpXML (std::string &dictDump, tools::SpellChecking &spellChecker) const
size_t ContentSize (void) const
size_t MetaSize (void) const
Protected Attributes
int limit
database::DatabaseConnection * database
std::set< Word > wordContent
std::map< MetaInformationType,
std::set< Word > > wordMeta
long long urlID
long long urlStageID
bool testMode
Private Member Functions
bool Commit (const std::map< DataminingCriteria *, std::list< DataminingNotifier * > > &mapDictionary)
void InitFromDatabase ()
void CleanUp (std::map< DataminingCriteria *, std::list< DataminingNotifier * > > &map)
Private Attributes
std::map< DataminingCriteria
*, std::list
< DataminingNotifier * > > mapDataMiningContent
std::map< DataminingCriteria
*, std::list
< DataminingNotifier * > > mapDataMiningMeta
Detailed Description
Definition at line 23 of file DataminingDictionary.h.
Member Enumeration Documentation
enum indexing::Dictionary::MetaInformationType [inherited]
Enumerator:
META_UNKNOWN
META_TITLE
META_DESCRIPTION
META_KEYWORDS
META_AUTHOR
META_COPYRIGHT
META_TYPE_MAX
Definition at line 30 of file Dictionary.h.
Constructor & Destructor Documentation
indexing::DataminingDictionary::DataminingDictionary (database::DatabaseConnection * database)
Definition at line 15 of file DataminingDictionary.cpp.
References InitFromDatabase().
indexing::DataminingDictionary::~DataminingDictionary () [virtual]
Definition at line 20 of file DataminingDictionary.cpp.
References CleanUp(), mapDataMiningContent, and mapDataMiningMeta.
Member Function Documentation
bool indexing::DataminingDictionary::CommitMeta (void) [virtual]
Implements indexing::Dictionary.
Definition at line 42 of file DataminingDictionary.cpp.
References indexing::Dictionary::wordMeta.
bool indexing::DataminingDictionary::CommitContent (void) [virtual]
Implements indexing::Dictionary.
Definition at line 48 of file DataminingDictionary.cpp.
References Commit(), and mapDataMiningContent.
bool indexing::DataminingDictionary::Commit (const std::map< DataminingCriteria *, std::list< DataminingNotifier * > > & mapDictionary) [private]
Definition at line 52 of file DataminingDictionary.cpp.
References indexing::Dictionary::testMode, and indexing::Dictionary::wordContent.
Referenced by CommitContent().
void indexing::DataminingDictionary::InitFromDatabase () [private]
Definition at line 38 of file DataminingDictionary.cpp.
Referenced by DataminingDictionary().
void indexing::DataminingDictionary::CleanUp (std::map< DataminingCriteria *, std::list< DataminingNotifier * > > & map) [private]
Definition at line 26 of file DataminingDictionary.cpp.
Referenced by ~DataminingDictionary().
bool indexing::Dictionary::AddContent (const std::string & word, const std::pair< long long, long long > & paragraphPosition) [inherited]
Definition at line 34 of file Dictionary.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::Dictionary::testMode, indexing::Dictionary::urlID, and indexing::Dictionary::wordContent.
Referenced by indexing::IndexerEx::Parse(), and indexing::ContentIndexer::TerminateWord().
bool indexing::Dictionary::AddContent (const std::string & word) [inherited]
Definition at line 51 of file Dictionary.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::Dictionary::testMode, indexing::Dictionary::urlID, and indexing::Dictionary::wordContent.
bool indexing::Dictionary::AddMeta (const std::string & word, const MetaInformationType & type) [inherited]
Definition at line 67 of file Dictionary.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::Dictionary::testMode, indexing::Dictionary::urlID, and indexing::Dictionary::wordMeta.
Referenced by indexing::IndexerEx::ParseMeta().
void indexing::Dictionary::SetUrlID (const long long urlID, const long long urlStageID) [inherited]
Definition at line 85 of file Dictionary.cpp.
References indexing::Dictionary::urlID, indexing::Dictionary::urlStageID, indexing::Dictionary::wordContent, and indexing::Dictionary::wordMeta.
void indexing::Dictionary::SetTestMode (const bool testMode) [inline, inherited]
Definition at line 60 of file Dictionary.h.
References indexing::Dictionary::testMode.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile().
void indexing::Dictionary::Dump (std::string & dictDump) const [inherited]
Definition at line 93 of file Dictionary.cpp.
References indexing::Dictionary::wordContent, and indexing::Dictionary::wordMeta.
void indexing::Dictionary::DumpXML (std::string & dictDump, tools::SpellChecking & spellChecker) const [inherited]
Definition at line 115 of file Dictionary.cpp.
References network::HttpUrlParser::EncodeUrl(), tools::SpellChecking::GenerateProposals(), tools::StringTools::VectorToString(), indexing::Dictionary::wordContent, and indexing::Dictionary::wordMeta.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile().
size_t indexing::Dictionary::ContentSize (void) const [inline, inherited]
Definition at line 63 of file Dictionary.h.
References indexing::Dictionary::wordContent.
size_t indexing::Dictionary::MetaSize (void) const [inline, inherited]
Definition at line 64 of file Dictionary.h.
References indexing::Dictionary::wordMeta.
Member Data Documentation
std::map< DataminingCriteria*, std::list<DataminingNotifier*> > indexing::DataminingDictionary::mapDataMiningContent [private]
Definition at line 38 of file DataminingDictionary.h.
Referenced by CommitContent(), and ~DataminingDictionary().
std::map< DataminingCriteria*, std::list<DataminingNotifier*> > indexing::DataminingDictionary::mapDataMiningMeta [private]
Definition at line 39 of file DataminingDictionary.h.
Referenced by ~DataminingDictionary().
int indexing::Dictionary::limit [protected, inherited]
Definition at line 67 of file Dictionary.h.
database::DatabaseConnection* indexing::Dictionary::database [protected, inherited]
Definition at line 68 of file Dictionary.h.
Referenced by indexing::GenericWebDictionary::CommitContent(), and indexing::GenericWebDictionary::CommitMeta().
std::set<Word> indexing::Dictionary::wordContent [protected, inherited]
Definition at line 69 of file Dictionary.h.
Referenced by indexing::Dictionary::AddContent(), Commit(), indexing::GenericWebDictionary::CommitContent(), indexing::Dictionary::ContentSize(), indexing::Dictionary::Dump(), indexing::Dictionary::DumpXML(), and indexing::Dictionary::SetUrlID().
std::map<MetaInformationType,std::set<Word> > indexing::Dictionary::wordMeta [protected, inherited]
Definition at line 70 of file Dictionary.h.
Referenced by indexing::Dictionary::AddMeta(), indexing::GenericWebDictionary::CommitMeta(), CommitMeta(), indexing::Dictionary::Dump(), indexing::Dictionary::DumpXML(), indexing::Dictionary::MetaSize(), and indexing::Dictionary::SetUrlID().
long long indexing::Dictionary::urlID [protected, inherited]
Definition at line 72 of file Dictionary.h.
Referenced by indexing::Dictionary::AddContent(), indexing::Dictionary::AddMeta(), and indexing::Dictionary::SetUrlID().
long long indexing::Dictionary::urlStageID [protected, inherited]
Definition at line 73 of file Dictionary.h.
Referenced by indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), and indexing::Dictionary::SetUrlID().
bool indexing::Dictionary::testMode [protected, inherited]
Definition at line 75 of file Dictionary.h.
Referenced by indexing::Dictionary::AddContent(), indexing::Dictionary::AddMeta(), Commit(), indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), and indexing::Dictionary::SetTestMode().
The documentation for this class was generated from the following files:
Indexer/src/DataminingDictionary.h
Indexer/src/DataminingDictionary.cpp