DeepNet: database::UpdateStatement Class Reference
database::UpdateStatement Class Reference
implements generic sql update statement.
#include <UpdateStatement.h>
Public Types
enum StatementType {
INSERT_STMT, INSERT_OR_UPDATE_STMT, UPDATE_STMT, SELECT_STMT,
DELETE_STMT
}
type of sql statement.
Public Member Functions
UpdateStatement (TableBase *tableBase, const std::vector< WhereConditionTableColumn * > &whereCols, const std::vector< OrderByColumn > &orderCols, const bool onlyDirty)
construct update statement.
virtual ~UpdateStatement ()
WhereCondition & Where ()
gets where condition.
OrderByClause & OrderBy ()
gets order by clause.
virtual InnerJoinCondition & InnerJoin ()
gets inner join condition for this statement.
virtual std::string ToSQL (database::DatabaseConnection *db) const
gets sql equivalent of this statement.
const std::string & TableAlias (void) const
gets table alias of this statement's table.
const std::string & TableName (void) const
gets table name of this statement's table.
const std::string & DatabaseName (void) const
gets database name of this statement's table.
void SetLimit (unsigned int limit)
sets the LIMIT part of the sql statement
Protected Member Functions
std::string GetFullQualifiedTableName () const
gets the fully qualified name of this statement's table.
Protected Attributes
TableDefinition * tableDefinition
definition of this statement's table.
std::string tableAlias
table alias, empty if disabled.
unsigned int limit
maximum number of rows returned
StatementType typeStmt
type of this statement.
Private Attributes
WhereCondition whereCondition
OrderByClause orderByClause
const TableBase * tableBase
bool onlyDirty
Detailed Description
implements generic sql update statement.
See also:
database::MySQLUpdateStatement
database::DB2UpdateStatement
Definition at line 27 of file UpdateStatement.h.
Member Enumeration Documentation
enum database::Statement::StatementType [inherited]
type of sql statement.
Enumerator:
INSERT_STMT
insert statement.
See also:
database::InsertStatement
INSERT_OR_UPDATE_STMT
insert or update (if duplicate).
See also:
database::InsertOrUpdateStatement
UPDATE_STMT
update statement.
See also:
database::UpdateStatement
SELECT_STMT
select statement.
See also:
database::SelectStatement
DELETE_STMT
delete statement.
See also:
database::DeleteStatement
Definition at line 28 of file Statement.h.
Constructor & Destructor Documentation
database::UpdateStatement::UpdateStatement (TableBase * tableBase, const std::vector< WhereConditionTableColumn * > & whereCols, const std::vector< OrderByColumn > & orderCols, const bool onlyDirty)
construct update statement.
Parameters:
tableBase table for update statement
whereCols where columns and their conditions
orderCols orderby columns
onlyDirty update dirty values only
Definition at line 19 of file UpdateStatement.cpp.
References database::OrderByClause::AddColumn(), database::WhereCondition::AddColumns(), OrderBy(), and Where().
database::UpdateStatement::~UpdateStatement () [virtual]
Definition at line 40 of file UpdateStatement.cpp.
Member Function Documentation
WhereCondition& database::UpdateStatement::Where (void) [inline]
gets where condition.
Returns:
where clause.
Definition at line 48 of file UpdateStatement.h.
References whereCondition.
Referenced by UpdateStatement().
OrderByClause& database::UpdateStatement::OrderBy (void) [inline]
gets order by clause.
Returns:
order by clause.
Definition at line 54 of file UpdateStatement.h.
References orderByClause.
Referenced by UpdateStatement().
InnerJoinCondition & database::UpdateStatement::InnerJoin () [virtual]
gets inner join condition for this statement.
Returns:
inner join condition.
Implements database::Statement.
Definition at line 76 of file UpdateStatement.cpp.
References THROW_EXCEPTION.
std::string database::UpdateStatement::ToSQL (database::DatabaseConnection * db) const [virtual]
gets sql equivalent of this statement.
Parameters:
db database connection.
Returns:
sql string.
Implements database::Statement.
Definition at line 43 of file UpdateStatement.cpp.
References database::TableColumn::GetColumnName(), database::TableBase::GetConstColumns(), database::TableColumn::GetForSQL(), database::Statement::GetFullQualifiedTableName(), database::TableColumn::IsDirty(), database::Statement::limit, onlyDirty, orderByClause, database::Statement::TableAlias(), tableBase, THROW_EXCEPTION, database::WhereCondition::ToString(), database::OrderByClause::ToString(), and whereCondition.
Referenced by database::MySQLUpdateStatement::ToSQL().
const std::string & database::Statement::TableAlias (void) const [inherited]
gets table alias of this statement's table.
Returns:
empty if no alias specified, otherwise alias name for this statement's table.
Definition at line 73 of file Statement.cpp.
References database::Statement::tableAlias.
Referenced by database::SelectStatement::SelectAllColumns(), database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), and ToSQL().
const std::string & database::Statement::TableName (void) const [inherited]
gets table name of this statement's table.
Returns:
table name.
Definition at line 53 of file Statement.cpp.
References database::Statement::tableDefinition, and database::TableDefinition::TableName().
const std::string & database::Statement::DatabaseName (void) const [inherited]
gets database name of this statement's table.
Returns:
database name.
Definition at line 58 of file Statement.cpp.
References database::TableDefinition::DatabaseName(), and database::Statement::tableDefinition.
void database::Statement::SetLimit (unsigned int limit) [inherited]
sets the LIMIT part of the sql statement
Parameters:
limit maximum number of returned rows (0 to disable).
Definition at line 68 of file Statement.cpp.
References database::Statement::limit.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and database::TableBase::Update().
std::string database::Statement::GetFullQualifiedTableName () const [protected, inherited]
gets the fully qualified name of this statement's table.
i.e. database_name.table_name.
Returns:
fully qualified name.
Definition at line 63 of file Statement.cpp.
References database::TableDefinition::GetFullQualifiedTableName(), and database::Statement::tableDefinition.
Referenced by database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), ToSQL(), and database::SelectStatement::ToSQL().
Member Data Documentation
WhereCondition database::UpdateStatement::whereCondition [private]
Definition at line 61 of file UpdateStatement.h.
Referenced by ToSQL(), and Where().
OrderByClause database::UpdateStatement::orderByClause [private]
Definition at line 62 of file UpdateStatement.h.
Referenced by OrderBy(), and ToSQL().
const TableBase* database::UpdateStatement::tableBase [private]
Definition at line 64 of file UpdateStatement.h.
Referenced by ToSQL().
bool database::UpdateStatement::onlyDirty [private]
Definition at line 65 of file UpdateStatement.h.
Referenced by ToSQL().
TableDefinition* database::Statement::tableDefinition [protected, inherited]
definition of this statement's table.
Definition at line 141 of file Statement.h.
Referenced by database::Statement::DatabaseName(), database::Statement::GetFullQualifiedTableName(), database::SelectStatement::SelectAllColumns(), database::Statement::TableName(), and database::Statement::~Statement().
std::string database::Statement::tableAlias [protected, inherited]
table alias, empty if disabled.
Definition at line 146 of file Statement.h.
Referenced by database::SelectStatement::SelectAddColumn(), database::SelectStatement::SelectAddCountColumn(), database::Statement::TableAlias(), and database::SelectStatement::ToSQL().
unsigned int database::Statement::limit [protected, inherited]
maximum number of rows returned
See also:
database::Statement::SetLimit
Definition at line 152 of file Statement.h.
Referenced by database::Statement::SetLimit(), ToSQL(), and database::SelectStatement::ToSQL().
StatementType database::Statement::typeStmt [protected, inherited]
type of this statement.
Definition at line 157 of file Statement.h.
Referenced by database::InsertOrUpdateStatement::InsertOrUpdateStatement().
The documentation for this class was generated from the following files:
Database/src/UpdateStatement.h
Database/src/UpdateStatement.cpp