DeepNet: caching::CacheRobotsTxt Class Reference
caching::CacheRobotsTxt Class Reference
cache for robot.txt's.
#include <CacheRobotsTxt.h>
Public Member Functions
virtual ~CacheRobotsTxt ()
Static Public Member Functions
static bool IsUrlAllowed (database::DatabaseConnection *db, const htmlparser::DatabaseUrl &url, const std::string &useragent)
checks if given url is valid for given useragent.
static void SetCapacity (const size_t capacity)
set current limit of cache.
static size_t GetSize ()
gets current number of entries in cache.
static size_t GetMatches ()
get current match count of cache, clearing internal match counter.
static size_t GetMisses ()
get current miss count of cache, clearing internal miss counter.
Private Member Functions
CacheRobotsTxt (size_t limit=0)
Static Private Member Functions
static bool LoadRobotsFromDatabase (database::DatabaseConnection *db, const CacheRobotsEntry &entry, RobotTxt &robot)
static bool DownloadRobotsTxt (database::DatabaseConnection *db, const htmlparser::DatabaseUrl &url, RobotTxt &robot)
Private Attributes
Cache< CacheRobotsEntry, RobotTxt > cacheRobotsTxts
bool saveRobotsTxt
Static Private Attributes
static CacheRobotsTxt cacheInstance
Detailed Description
cache for robot.txt's.
Definition at line 26 of file CacheRobotsTxt.h.
Constructor & Destructor Documentation
caching::CacheRobotsTxt::CacheRobotsTxt (size_t limit = 0) [private]
Definition at line 19 of file CacheRobotsTxt.cpp.
caching::CacheRobotsTxt::~CacheRobotsTxt () [virtual]
Definition at line 24 of file CacheRobotsTxt.cpp.
Member Function Documentation
bool caching::CacheRobotsTxt::IsUrlAllowed (database::DatabaseConnection * db, const htmlparser::DatabaseUrl & url, const std::string & useragent) [static]
checks if given url is valid for given useragent.
Parameters:
db database connection.
url url to check.
useragent useragent string to check for.
Returns:
false if not allow, true if allowed.
Definition at line 27 of file CacheRobotsTxt.cpp.
References caching::Cache< T, V >::AddItem(), cacheInstance, cacheRobotsTxts, DownloadRobotsTxt(), caching::Cache< T, V >::GetItem(), htmlparser::DatabaseUrl::GetSecondLevelID(), htmlparser::DatabaseUrl::GetSubdomainID(), htmlparser::DatabaseUrl::GetTopLevelID(), and LoadRobotsFromDatabase().
Referenced by crawler::UrlFetcherThread::FetchHtmlCode().
static void caching::CacheRobotsTxt::SetCapacity (const size_t capacity) [inline, static]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 49 of file CacheRobotsTxt.h.
References cacheInstance, cacheRobotsTxts, and caching::Cache< T, V >::SetLimit().
Referenced by bot::Bot::InitCacheConfigParams().
static size_t caching::CacheRobotsTxt::GetSize () [inline, static]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 55 of file CacheRobotsTxt.h.
References cacheInstance, cacheRobotsTxts, and caching::Cache< T, V >::GetSize().
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheRobotsTxt::GetMatches () [inline, static]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 61 of file CacheRobotsTxt.h.
References cacheInstance, cacheRobotsTxts, and caching::Cache< T, V >::GetMatches().
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheRobotsTxt::GetMisses () [inline, static]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 67 of file CacheRobotsTxt.h.
References cacheInstance, cacheRobotsTxts, and caching::Cache< T, V >::GetMisses().
Referenced by bot::Bot::WatchDog().
bool caching::CacheRobotsTxt::LoadRobotsFromDatabase (database::DatabaseConnection * db, const CacheRobotsEntry & entry, RobotTxt & robot) [static, private]
Definition at line 84 of file CacheRobotsTxt.cpp.
References cacheInstance, and saveRobotsTxt.
Referenced by IsUrlAllowed().
bool caching::CacheRobotsTxt::DownloadRobotsTxt (database::DatabaseConnection * db, const htmlparser::DatabaseUrl & url, RobotTxt & robot) [static, private]
Definition at line 46 of file CacheRobotsTxt.cpp.
References cacheInstance, network::HttpClientFactory::CreateInstance(), network::HttpClientFactory::CURL, network::IHttpClient::Get(), tools::Pointer< T >::Get(), network::HtmlData::GetBuffer(), network::HttpUrl::GetScheme(), network::HttpUrl::GetSecondLevelDomain(), network::HttpUrl::GetSubdomain(), network::HttpUrl::GetTLD(), network::HttpResponse::html, caching::RobotTxt::Load(), network::HttpUrlParser::ParseURL(), and saveRobotsTxt.
Referenced by IsUrlAllowed().
Member Data Documentation
CacheRobotsTxt caching::CacheRobotsTxt::cacheInstance [static, private]
Definition at line 74 of file CacheRobotsTxt.h.
Referenced by DownloadRobotsTxt(), GetMatches(), GetMisses(), GetSize(), IsUrlAllowed(), LoadRobotsFromDatabase(), and SetCapacity().
Cache<CacheRobotsEntry,RobotTxt> caching::CacheRobotsTxt::cacheRobotsTxts [private]
Definition at line 77 of file CacheRobotsTxt.h.
Referenced by GetMatches(), GetMisses(), GetSize(), IsUrlAllowed(), and SetCapacity().
bool caching::CacheRobotsTxt::saveRobotsTxt [private]
Definition at line 78 of file CacheRobotsTxt.h.
Referenced by DownloadRobotsTxt(), and LoadRobotsFromDatabase().
The documentation for this class was generated from the following files:
Caching/src/CacheRobotsTxt.h
Caching/src/CacheRobotsTxt.cpp