DeepNet: libxmlparser::HtmlSAX2Parser Class Reference
libxmlparser::HtmlSAX2Parser Class Reference
#include <HtmlSAX2Parser.h>
Public Member Functions
virtual ~HtmlSAX2Parser ()
virtual bool Parse (const htmlparser::DatabaseUrl &url, const network::HtmlData &html, tools::Pointer< htmlparser::IHtmlParserResult > &result)
parses html and generates content result
Private Member Functions
HtmlSAX2Parser ()
Static Private Member Functions
static void startElement (void *ctx, const xmlChar *name, const xmlChar **atts)
static void endElement (void *ctx, const xmlChar *name)
static void warning (void *ctx, const char *msg,...)
static void error (void *ctx, const char *msg,...)
static void fatalError (void *ctx, const char *msg,...)
static void genericErrorFunc (void *ctx, const char *msg,...)
static void characters (void *ctx, const xmlChar *ch, int len)
Private Attributes
htmlSAXHandler saxHandler
HtmlSAX2ParserContext parserContext
htmlParserCtxtPtr parserCtxt
Static Private Attributes
static volatile bool errorFuncInitialized = false
Friends
class htmlparser::HtmlParserFactory
Detailed Description
Definition at line 50 of file HtmlSAX2Parser.h.
Constructor & Destructor Documentation
libxmlparser::HtmlSAX2Parser::HtmlSAX2Parser () [private]
Definition at line 35 of file HtmlSAX2Parser.cpp.
References characters(), endElement(), error(), errorFuncInitialized, fatalError(), genericErrorFunc(), saxHandler, startElement(), and warning().
libxmlparser::HtmlSAX2Parser::~HtmlSAX2Parser () [virtual]
Definition at line 57 of file HtmlSAX2Parser.cpp.
Member Function Documentation
bool libxmlparser::HtmlSAX2Parser::Parse (const htmlparser::DatabaseUrl & url, const network::HtmlData & html, tools::Pointer< htmlparser::IHtmlParserResult > & result) [virtual]
parses html and generates content result
Parameters:
url url of html
html html to parse
result result containing content and info for html documents
Returns:
true if successful, false if unsuccessful
Implements htmlparser::IHtmlParser.
Definition at line 418 of file HtmlSAX2Parser.cpp.
References network::HtmlData::GetBuffer(), network::HtmlData::GetBufferSize(), tools::MemoryContainer< T >::GetCount(), network::HttpUrl::GetFullUrl(), libxmlparser::HtmlSAX2ParserContext::htmlDocument, parserContext, parserCtxt, libxmlparser::HtmlSAX2ParserContext::parserInstance, libxmlparser::HtmlSAX2Document::result, saxHandler, tools::Pointer< T >::Set(), libxmlparser::HtmlSAX2ParserContext::url, and htmlparser::IHtmlParserResult::wellformed.
void libxmlparser::HtmlSAX2Parser::startElement (void * ctx, const xmlChar * name, const xmlChar ** atts) [static, private]
Definition at line 61 of file HtmlSAX2Parser.cpp.
References libxmlparser::HtmlSAX2Element::attribute, libxmlparser::HtmlSAX2Element::attributes, libxmlparser::HtmlSAX2Document::elements, libxmlparser::HtmlSAX2ParserContext::htmlDocument, libxmlparser::HtmlSAX2Attribute::localname, libxmlparser::HtmlSAX2ParserContext::nCurrentElement, and libxmlparser::HtmlSAX2Attribute::value.
Referenced by HtmlSAX2Parser().
void libxmlparser::HtmlSAX2Parser::endElement (void * ctx, const xmlChar * name) [static, private]
Definition at line 87 of file HtmlSAX2Parser.cpp.
References libxmlparser::HtmlSAX2Element::attribute, htmlparser::IHtmlParserResult::content, libxmlparser::HtmlSAX2Document::elements, libxmlparser::HtmlSAX2Element::GetAttributeByName(), network::HttpUrl::GetFullUrl(), libxmlparser::HtmlSAX2ParserContext::htmlDocument, htmlparser::IHtmlParserResult::hyperlinks, htmlparser::IHtmlParserResult::images, log::Logging::IsLogLevelTrace(), libxmlparser::HtmlSAX2Attribute::localname, log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, log::Logging::LogTrace(), htmlparser::IHtmlParserResult::meta, libxmlparser::HtmlSAX2ParserContext::nCurrentElement, network::HttpUrlParser::ParseURL(), libxmlparser::HtmlSAX2Document::result, tools::StringTools::ToLowerNP(), tools::StringTools::Trim(), libxmlparser::HtmlSAX2ParserContext::url, and libxmlparser::HtmlSAX2Attribute::value.
Referenced by HtmlSAX2Parser().
void libxmlparser::HtmlSAX2Parser::warning (void * ctx, const char * msg, ...) [static, private]
Definition at line 373 of file HtmlSAX2Parser.cpp.
References tools::StringTools::FormatVAString(), libxmlparser::HtmlSAX2ParserContext::htmlDocument, libxmlparser::HtmlSAX2Document::result, and htmlparser::IHtmlParserResult::warnings.
Referenced by HtmlSAX2Parser().
void libxmlparser::HtmlSAX2Parser::error (void * ctx, const char * msg, ...) [static, private]
Definition at line 332 of file HtmlSAX2Parser.cpp.
References libxmlparser::HtmlSAX2Element::attribute, libxmlparser::HtmlSAX2Document::elements, htmlparser::IHtmlParserResult::errors, tools::StringTools::FormatVAString(), libxmlparser::HtmlSAX2ParserContext::htmlDocument, libxmlparser::HtmlSAX2Attribute::localname, libxmlparser::HtmlSAX2ParserContext::nCurrentElement, parserCtxt, libxmlparser::HtmlSAX2ParserContext::parserInstance, and libxmlparser::HtmlSAX2Document::result.
Referenced by HtmlSAX2Parser().
void libxmlparser::HtmlSAX2Parser::fatalError (void * ctx, const char * msg, ...) [static, private]
Definition at line 385 of file HtmlSAX2Parser.cpp.
References libxmlparser::HtmlSAX2Document::elements, htmlparser::IHtmlParserResult::fatals, tools::StringTools::FormatVAString(), libxmlparser::HtmlSAX2ParserContext::htmlDocument, log::Logging::IsLogLevelTrace(), log::Logging::LogTrace(), libxmlparser::HtmlSAX2ParserContext::nCurrentElement, and libxmlparser::HtmlSAX2Document::result.
Referenced by HtmlSAX2Parser().
void libxmlparser::HtmlSAX2Parser::genericErrorFunc (void * ctx, const char * msg, ...) [static, private]
Definition at line 403 of file HtmlSAX2Parser.cpp.
References tools::StringTools::FormatVAString(), and log::Logging::LogWarn().
Referenced by HtmlSAX2Parser().
void libxmlparser::HtmlSAX2Parser::characters (void * ctx, const xmlChar * ch, int len) [static, private]
Definition at line 311 of file HtmlSAX2Parser.cpp.
References libxmlparser::HtmlSAX2Element::attribute, libxmlparser::HtmlSAX2Document::elements, libxmlparser::HtmlSAX2ParserContext::htmlDocument, libxmlparser::HtmlSAX2ParserContext::nCurrentElement, and libxmlparser::HtmlSAX2Attribute::value.
Referenced by HtmlSAX2Parser().
Friends And Related Function Documentation
friend class htmlparser::HtmlParserFactory [friend]
Definition at line 52 of file HtmlSAX2Parser.h.
Member Data Documentation
volatile bool libxmlparser::HtmlSAX2Parser::errorFuncInitialized = false [static, private]
Definition at line 74 of file HtmlSAX2Parser.h.
Referenced by HtmlSAX2Parser().
htmlSAXHandler libxmlparser::HtmlSAX2Parser::saxHandler [private]
Definition at line 77 of file HtmlSAX2Parser.h.
Referenced by HtmlSAX2Parser(), and Parse().
HtmlSAX2ParserContext libxmlparser::HtmlSAX2Parser::parserContext [private]
Definition at line 78 of file HtmlSAX2Parser.h.
Referenced by Parse().
htmlParserCtxtPtr libxmlparser::HtmlSAX2Parser::parserCtxt [private]
Definition at line 79 of file HtmlSAX2Parser.h.
Referenced by error(), and Parse().
The documentation for this class was generated from the following files:
LibXMLParser/src/HtmlSAX2Parser.h
LibXMLParser/src/HtmlSAX2Parser.cpp