DeepNet: database::InsertStatement Class Reference
database::InsertStatement Class Reference
implements generic sql insert statement.
#include <InsertStatement.h>
Public Types
enum StatementType {
INSERT_STMT, INSERT_OR_UPDATE_STMT, UPDATE_STMT, SELECT_STMT,
DELETE_STMT
}
type of sql statement.
Public Member Functions
InsertStatement (TableBase *tableBase)
construct with existing table filled with values to insert.
virtual ~InsertStatement ()
virtual InnerJoinCondition & InnerJoin ()
gets inner join condition for this statement.
virtual std::string ToSQL (DatabaseConnection *db) const
gets sql equivalent of this statement.
const TableBase * GetConstTableBase () const
const std::string & TableAlias (void) const
gets table alias of this statement's table.
const std::string & TableName (void) const
gets table name of this statement's table.
const std::string & DatabaseName (void) const
gets database name of this statement's table.
void SetLimit (unsigned int limit)
sets the LIMIT part of the sql statement
Protected Member Functions
std::string GetFullQualifiedTableName () const
gets the fully qualified name of this statement's table.
Protected Attributes
const TableBase * tableBase
TableDefinition * tableDefinition
definition of this statement's table.
std::string tableAlias
table alias, empty if disabled.
unsigned int limit
maximum number of rows returned
StatementType typeStmt
type of this statement.
Detailed Description
implements generic sql insert statement.
See also:
database::MySQLInsertStatement
database::DB2InsertStatement
Definition at line 25 of file InsertStatement.h.
Member Enumeration Documentation
enum database::Statement::StatementType [inherited]
type of sql statement.
Enumerator:
INSERT_STMT
insert statement.
See also:
database::InsertStatement
INSERT_OR_UPDATE_STMT
insert or update (if duplicate).
See also:
database::InsertOrUpdateStatement
UPDATE_STMT
update statement.
See also:
database::UpdateStatement
SELECT_STMT
select statement.
See also:
database::SelectStatement
DELETE_STMT
delete statement.
See also:
database::DeleteStatement
Definition at line 28 of file Statement.h.
Constructor & Destructor Documentation
database::InsertStatement::InsertStatement (TableBase * tableBase)
construct with existing table filled with values to insert.
Parameters:
tableBase existing table.
Definition at line 19 of file InsertStatement.cpp.
database::InsertStatement::~InsertStatement () [virtual]
Definition at line 24 of file InsertStatement.cpp.
Member Function Documentation
InnerJoinCondition & database::InsertStatement::InnerJoin () [virtual]
gets inner join condition for this statement.
Returns:
inner join condition.
Implements database::Statement.
Reimplemented in database::InsertOrUpdateStatement.
Definition at line 57 of file InsertStatement.cpp.
References THROW_EXCEPTION.
std::string database::InsertStatement::ToSQL (DatabaseConnection * db) const [virtual]
gets sql equivalent of this statement.
Parameters:
db database connection.
Returns:
sql string.
Implements database::Statement.
Reimplemented in database::InsertOrUpdateStatement.
Definition at line 27 of file InsertStatement.cpp.
References database::TableBase::GetConstColumns(), database::Statement::GetFullQualifiedTableName(), database::Statement::TableAlias(), tableBase, and THROW_EXCEPTION.
Referenced by database::MySQLInsertStatement::ToSQL().
const TableBase* database::InsertStatement::GetConstTableBase () const [inline]
Definition at line 40 of file InsertStatement.h.
References tableBase.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL().
const std::string & database::Statement::TableAlias (void) const [inherited]
gets table alias of this statement's table.
Returns:
empty if no alias specified, otherwise alias name for this statement's table.
Definition at line 73 of file Statement.cpp.
References database::Statement::tableAlias.
Referenced by database::SelectStatement::SelectAllColumns(), ToSQL(), database::DeleteStatement::ToSQL(), and database::UpdateStatement::ToSQL().
const std::string & database::Statement::TableName (void) const [inherited]
gets table name of this statement's table.
Returns:
table name.
Definition at line 53 of file Statement.cpp.
References database::Statement::tableDefinition, and database::TableDefinition::TableName().
const std::string & database::Statement::DatabaseName (void) const [inherited]
gets database name of this statement's table.
Returns:
database name.
Definition at line 58 of file Statement.cpp.
References database::TableDefinition::DatabaseName(), and database::Statement::tableDefinition.
void database::Statement::SetLimit (unsigned int limit) [inherited]
sets the LIMIT part of the sql statement
Parameters:
limit maximum number of returned rows (0 to disable).
Definition at line 68 of file Statement.cpp.
References database::Statement::limit.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and database::TableBase::Update().
std::string database::Statement::GetFullQualifiedTableName () const [protected, inherited]
gets the fully qualified name of this statement's table.
i.e. database_name.table_name.
Returns:
fully qualified name.
Definition at line 63 of file Statement.cpp.
References database::TableDefinition::GetFullQualifiedTableName(), and database::Statement::tableDefinition.
Referenced by ToSQL(), database::DeleteStatement::ToSQL(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
Member Data Documentation
const TableBase* database::InsertStatement::tableBase [protected]
Definition at line 43 of file InsertStatement.h.
Referenced by GetConstTableBase(), and ToSQL().
TableDefinition* database::Statement::tableDefinition [protected, inherited]
definition of this statement's table.
Definition at line 141 of file Statement.h.
Referenced by database::Statement::DatabaseName(), database::Statement::GetFullQualifiedTableName(), database::SelectStatement::SelectAllColumns(), database::Statement::TableName(), and database::Statement::~Statement().
std::string database::Statement::tableAlias [protected, inherited]
table alias, empty if disabled.
Definition at line 146 of file Statement.h.
Referenced by database::SelectStatement::SelectAddColumn(), database::SelectStatement::SelectAddCountColumn(), database::Statement::TableAlias(), and database::SelectStatement::ToSQL().
unsigned int database::Statement::limit [protected, inherited]
maximum number of rows returned
See also:
database::Statement::SetLimit
Definition at line 152 of file Statement.h.
Referenced by database::Statement::SetLimit(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
StatementType database::Statement::typeStmt [protected, inherited]
type of this statement.
Definition at line 157 of file Statement.h.
Referenced by database::InsertOrUpdateStatement::InsertOrUpdateStatement().
The documentation for this class was generated from the following files:
Database/src/InsertStatement.h
Database/src/InsertStatement.cpp