DeepNet: database::WhereCondition Class Reference
database::WhereCondition Class Reference
container for WHERE conditions of an sql statement.
#include <WhereCondition.h>
Public Member Functions
WhereCondition ()
virtual ~WhereCondition ()
void AddColumn (WhereConditionTableColumn *col)
add a where condition for a column
void AddColumns (const std::vector< WhereConditionTableColumn * > &cols)
add multiple where conditions for multiple columns.
std::string ToString (database::DatabaseConnection *db) const
gets sql equivalent of where conditions for this statement.
Static Public Member Functions
static WhereConditionOperator Equals ()
static WhereConditionOperator NotEquals ()
static WhereConditionOperator Greater ()
static WhereConditionOperator GreaterOrEqual ()
static WhereConditionOperator Smaller ()
static WhereConditionOperator SmallerOrEqual ()
static WhereConditionOperator Like ()
static
WhereConditionCompositeOperator InitialComp ()
static
WhereConditionCompositeOperator And ()
static
WhereConditionCompositeOperator Or ()
Private Member Functions
WhereCondition (const WhereCondition &copy)
Private Attributes
WhereConditionTableColumnContainer columns
Detailed Description
container for WHERE conditions of an sql statement.
Definition at line 25 of file WhereCondition.h.
Constructor & Destructor Documentation
database::WhereCondition::WhereCondition (const WhereCondition & copy) [private]
Definition at line 26 of file WhereCondition.cpp.
References THROW_EXCEPTION.
database::WhereCondition::WhereCondition ()
Definition at line 23 of file WhereCondition.cpp.
database::WhereCondition::~WhereCondition () [virtual]
Definition at line 31 of file WhereCondition.cpp.
Member Function Documentation
static WhereConditionOperator database::WhereCondition::Equals () [inline, static]
Definition at line 34 of file WhereCondition.h.
References database::EQUALS.
Referenced by bot::DatabaseRepair::FixCrawlerSessionTable(), bot::DatabaseRepair::FixSecondLevelLockTable(), bot::DatabaseRepair::FixSyncUrlTable(), database::cachehtmlTableBase::GetBy_action_time(), database::cachesecondleveldomainTableBase::GetBy_action_time(), database::cachesubdomainTableBase::GetBy_action_time(), database::cacheparsedTableBase::GetBy_action_time(), database::cacheurlTableBase::GetBy_action_time(), database::cacherobotsTableBase::GetBy_action_time(), database::logmessagesTableBase::GetBy_actiontime(), database::logmessagesTableBase::GetBy_appName(), database::documentcodeTableBase::GetBy_code(), database::urlstagesTableBase::GetBy_content_length(), database::urlstagesTableBase::GetBy_content_md5(), database::urlstagesTableBase::GetBy_content_type(), database::hyperlinksTableBase::GetBy_count(), database::locksecondleveldomainTableBase::GetBy_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetBy_CRAWLERSESSION_ID(), database::fencedsearchTableBase::GetBy_CUSTOMER_ID(), database::customersessionsTableBase::GetBy_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetBy_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetBy_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetBy_CUSTOMER_ID(), database::customerdomainsTableBase::GetBy_CUSTOMER_ID(), database::customerqueriesTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetBy_DICT_ID(), database::dockeyTableBase::GetBy_DICT_ID(), database::docmetaTableBase::GetBy_DICT_ID(), database::customerproductkeywordsTableBase::GetBy_DICT_ID(), database::dockeyposTableBase::GetBy_DOCKEY_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::dataminingblacklistTableBase::GetBy_domain(), database::customerdomainsTableBase::GetBy_domain(), database::urlstagesTableBase::GetBy_download_speed(), database::urlstagesTableBase::GetBy_download_time(), database::urlstagesTableBase::GetBy_ext_links(), database::imagesTableBase::GetBy_found_date(), database::urlsTableBase::GetBy_found_date(), database::urlstagesTableBase::GetBy_found_date(), database::customermatchcriteriagrouptypeTableBase::GetBy_groupPosition(), database::urlstagesTableBase::GetBy_html_errors(), database::crawlersessionsTableBase::GetBy_ID(), database::keywordqueryTableBase::GetBy_ID(), database::matchcriteriaTableBase::GetBy_ID(), database::schemesTableBase::GetBy_ID(), database::searchqueryTableBase::GetBy_ID(), database::secondleveldomainsTableBase::GetBy_ID(), database::subdomainsTableBase::GetBy_ID(), database::topleveldomainsTableBase::GetBy_ID(), database::documentcodeTableBase::GetBy_ID(), database::customerproductimagesTableBase::GetBy_ID(), database::docurlTableBase::GetBy_ID(), database::fencedsearchTableBase::GetBy_ID(), database::customerproductkeywordsTableBase::GetBy_ID(), database::customerproducturlsTableBase::GetBy_ID(), database::latesturlstagesTableBase::GetBy_ID(), database::customerqueriesTableBase::GetBy_ID(), database::customersessionsTableBase::GetBy_ID(), database::customersTableBase::GetBy_ID(), database::customersyncurlTableBase::GetBy_ID(), database::searchquerykeywordsTableBase::GetBy_ID(), database::dataminingalertsTableBase::GetBy_ID(), database::dataminingblacklistTableBase::GetBy_ID(), database::dataminingcriteriaTableBase::GetBy_ID(), database::dataminingcustomersessionTableBase::GetBy_ID(), database::dataminingcustomerTableBase::GetBy_ID(), database::dictTableBase::GetBy_ID(), database::customermatchcriteriaTableBase::GetBy_ID(), database::hyperlinksTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_ID(), database::customerdomainblacklistTableBase::GetBy_ID(), database::metainfoTableBase::GetBy_ID(), database::customersynccrawlerTableBase::GetBy_ID(), database::dataminingcriteriaalertsTableBase::GetBy_ID(), database::dockeyposTableBase::GetBy_ID(), database::dockeyTableBase::GetBy_ID(), database::docmetaTableBase::GetBy_ID(), database::cachesubdomainTableBase::GetBy_ID(), database::customerproductsTableBase::GetBy_ID(), database::cacheparsedTableBase::GetBy_ID(), database::cacheurlTableBase::GetBy_ID(), database::queryresultsTableBase::GetBy_ID(), database::syncurlsTableBase::GetBy_ID(), database::cacherobotsTableBase::GetBy_ID(), database::customerdomainsTableBase::GetBy_ID(), database::customerkeywordsTableBase::GetBy_ID(), database::cachehtmlTableBase::GetBy_ID(), database::cachesecondleveldomainTableBase::GetBy_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_ID(), database::logmessagesTableBase::GetBy_ID(), database::imagesTableBase::GetBy_ID(), database::urlsTableBase::GetBy_ID(), database::urlstagesTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetBy_imageUrl(), database::urlstagesTableBase::GetBy_int_links(), database::customerdomainsTableBase::GetBy_isDomainRegex(), database::customerkeywordsTableBase::GetBy_isKeywordRegex(), database::customerdomainblacklistTableBase::GetBy_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetBy_isPrimaryKey(), database::dictTableBase::GetBy_keyword(), database::dataminingcriteriaTableBase::GetBy_keyword(), database::customerkeywordsTableBase::GetBy_keyword(), database::searchquerykeywordsTableBase::GetBy_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetBy_last_change(), database::dataminingcustomerTableBase::GetBy_login(), database::customersTableBase::GetBy_login(), database::logmessagesTableBase::GetBy_loglevel(), database::customermatchcriteriaTableBase::GetBy_MATCHCRITERIA_ID(), database::cachesubdomainTableBase::GetBy_matches(), database::cachehtmlTableBase::GetBy_matches(), database::cacheurlTableBase::GetBy_matches(), database::cacheparsedTableBase::GetBy_matches(), database::cacherobotsTableBase::GetBy_matches(), database::cachesecondleveldomainTableBase::GetBy_matches(), database::logmessagesTableBase::GetBy_message(), database::cachehtmlTableBase::GetBy_misses(), database::cachesecondleveldomainTableBase::GetBy_misses(), database::cachesubdomainTableBase::GetBy_misses(), database::cacheurlTableBase::GetBy_misses(), database::cacheparsedTableBase::GetBy_misses(), database::cacherobotsTableBase::GetBy_misses(), database::dictTableBase::GetBy_occurrence(), database::dockeyTableBase::GetBy_occurrence(), database::docmetaTableBase::GetBy_occurrence(), database::queryresultsTableBase::GetBy_order_position(), database::dockeyposTableBase::GetBy_paragraph(), database::dataminingalertsTableBase::GetBy_param(), database::customersTableBase::GetBy_password(), database::dataminingcustomerTableBase::GetBy_password(), database::customerdomainblacklistTableBase::GetBy_path(), database::urlsTableBase::GetBy_path_part(), database::imagesTableBase::GetBy_path_part(), database::logmessagesTableBase::GetBy_pid(), database::urlsTableBase::GetBy_port(), database::imagesTableBase::GetBy_port(), database::dockeyposTableBase::GetBy_position(), database::urlstagesTableBase::GetBy_primary_ip(), database::urlstagesTableBase::GetBy_primary_port(), database::customerproductimagesTableBase::GetBy_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetBy_PRODUCT_ID(), database::customerproducturlsTableBase::GetBy_PRODUCT_ID(), database::customerproductsTableBase::GetBy_productBrand(), database::customerproductsTableBase::GetBy_productName(), database::customerproductsTableBase::GetBy_productNo(), database::customerqueriesTableBase::GetBy_query(), database::keywordqueryTableBase::GetBy_query_part(), database::urlstagesTableBase::GetBy_redirect_count(), database::matchcriteriaTableBase::GetBy_regex(), database::urlstagesTableBase::GetBy_response_code(), database::customerdomainsTableBase::GetBy_revisitInterval(), database::locksecondleveldomainTableBase::GetBy_schedule(), database::syncurlsTableBase::GetBy_schedule(), database::customersyncurlTableBase::GetBy_scheduled(), database::customersynccrawlerTableBase::GetBy_scheduled(), database::schemesTableBase::GetBy_scheme(), database::imagesTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_search_part(), database::imagesTableBase::GetBy_search_part(), database::searchquerykeywordsTableBase::GetBy_SEARCHQUERY_ID(), database::queryresultsTableBase::GetBy_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetBy_session(), database::customersessionsTableBase::GetBy_session(), database::dataminingcustomersessionTableBase::GetBy_session(), database::cachesubdomainTableBase::GetBy_size(), database::cacheparsedTableBase::GetBy_size(), database::cachesecondleveldomainTableBase::GetBy_size(), database::cacherobotsTableBase::GetBy_size(), database::cachehtmlTableBase::GetBy_size(), database::cacheurlTableBase::GetBy_size(), database::subdomainsTableBase::GetBy_subdomain(), database::urlsTableBase::GetBy_SUBDOMAIN_ID(), database::imagesTableBase::GetBy_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_target(), database::hyperlinksTableBase::GetBy_TARGET_URL_ID(), database::imagelinksTableBase::GetBy_TARGET_URL_ID(), database::logmessagesTableBase::GetBy_threadName(), database::logmessagesTableBase::GetBy_tid(), database::topleveldomainsTableBase::GetBy_tld(), database::imagesTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetBy_type(), database::dataminingcriteriaTableBase::GetBy_type(), database::metainfoTableBase::GetBy_type(), database::customermatchcriteriagrouptypeTableBase::GetBy_type(), database::customermatchcriteriaTableBase::GetBy_type(), database::docmetaTableBase::GetBy_type(), database::urlstagesTableBase::GetBy_upload_speed(), database::customersyncurlTableBase::GetBy_URL_ID(), database::latesturlstagesTableBase::GetBy_URL_ID(), database::customerproducturlsTableBase::GetBy_URL_ID(), database::syncurlsTableBase::GetBy_URL_ID(), database::docurlTableBase::GetBy_URL_ID(), database::queryresultsTableBase::GetBy_URL_ID(), database::urlstagesTableBase::GetBy_URL_ID(), database::imagesTableBase::GetBy_url_md5(), database::urlsTableBase::GetBy_url_md5(), database::documentcodeTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_URLSTAGE_ID(), database::latesturlstagesTableBase::GetBy_URLSTAGE_ID(), database::dockeyTableBase::GetBy_URLSTAGE_ID(), database::hyperlinksTableBase::GetBy_URLSTAGE_ID(), database::docmetaTableBase::GetBy_URLSTAGE_ID(), database::imagelinksTableBase::GetBy_URLSTAGE_ID(), database::queryresultsTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_value(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::UrlFetcherThread::RemoveCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
static WhereConditionOperator database::WhereCondition::NotEquals () [inline, static]
Definition at line 35 of file WhereCondition.h.
References database::NOT_EQUALS.
Referenced by bot::DatabaseRepair::FixSecondLevelLockTable(), bot::DatabaseRepair::FixSyncUrlTable(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
static WhereConditionOperator database::WhereCondition::Greater () [inline, static]
Definition at line 36 of file WhereCondition.h.
References database::GREATER.
static WhereConditionOperator database::WhereCondition::GreaterOrEqual () [inline, static]
Definition at line 37 of file WhereCondition.h.
References database::GREATER_EQUAL.
Referenced by queryserver::XMLQueryResponse::ProcessExistQuery().
static WhereConditionOperator database::WhereCondition::Smaller () [inline, static]
Definition at line 38 of file WhereCondition.h.
References database::SMALLER.
static WhereConditionOperator database::WhereCondition::SmallerOrEqual () [inline, static]
Definition at line 39 of file WhereCondition.h.
References database::SMALLER_EQUAL.
Referenced by crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), queryserver::XMLQueryResponse::ProcessExistQuery(), and crawler::GenericWebUrlFetcherThread::ReserveNextUrls().
static WhereConditionOperator database::WhereCondition::Like () [inline, static]
Definition at line 40 of file WhereCondition.h.
References database::LIKE.
Referenced by queryserver::XMLQueryResponse::GetKeywordIDs().
static WhereConditionCompositeOperator database::WhereCondition::InitialComp () [inline, static]
Definition at line 42 of file WhereCondition.h.
References database::INITIAL_COMPOSITE_OPERATOR_TYPE.
Referenced by bot::DatabaseRepair::FixCrawlerSessionTable(), bot::DatabaseRepair::FixSecondLevelLockTable(), bot::DatabaseRepair::FixSyncUrlTable(), database::cachehtmlTableBase::GetBy_action_time(), database::cachesecondleveldomainTableBase::GetBy_action_time(), database::cachesubdomainTableBase::GetBy_action_time(), database::cacheurlTableBase::GetBy_action_time(), database::cacheparsedTableBase::GetBy_action_time(), database::cacherobotsTableBase::GetBy_action_time(), database::logmessagesTableBase::GetBy_actiontime(), database::logmessagesTableBase::GetBy_appName(), database::documentcodeTableBase::GetBy_code(), database::urlstagesTableBase::GetBy_content_length(), database::urlstagesTableBase::GetBy_content_md5(), database::urlstagesTableBase::GetBy_content_type(), database::hyperlinksTableBase::GetBy_count(), database::locksecondleveldomainTableBase::GetBy_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetBy_CRAWLERSESSION_ID(), database::fencedsearchTableBase::GetBy_CUSTOMER_ID(), database::customersessionsTableBase::GetBy_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetBy_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetBy_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetBy_CUSTOMER_ID(), database::customerdomainsTableBase::GetBy_CUSTOMER_ID(), database::customerqueriesTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetBy_DICT_ID(), database::dockeyTableBase::GetBy_DICT_ID(), database::docmetaTableBase::GetBy_DICT_ID(), database::customerproductkeywordsTableBase::GetBy_DICT_ID(), database::dockeyposTableBase::GetBy_DOCKEY_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::dataminingblacklistTableBase::GetBy_domain(), database::customerdomainsTableBase::GetBy_domain(), database::urlstagesTableBase::GetBy_download_speed(), database::urlstagesTableBase::GetBy_download_time(), database::urlstagesTableBase::GetBy_ext_links(), database::imagesTableBase::GetBy_found_date(), database::urlsTableBase::GetBy_found_date(), database::urlstagesTableBase::GetBy_found_date(), database::customermatchcriteriagrouptypeTableBase::GetBy_groupPosition(), database::urlstagesTableBase::GetBy_html_errors(), database::crawlersessionsTableBase::GetBy_ID(), database::keywordqueryTableBase::GetBy_ID(), database::matchcriteriaTableBase::GetBy_ID(), database::schemesTableBase::GetBy_ID(), database::secondleveldomainsTableBase::GetBy_ID(), database::searchqueryTableBase::GetBy_ID(), database::subdomainsTableBase::GetBy_ID(), database::topleveldomainsTableBase::GetBy_ID(), database::documentcodeTableBase::GetBy_ID(), database::docurlTableBase::GetBy_ID(), database::customerproductimagesTableBase::GetBy_ID(), database::fencedsearchTableBase::GetBy_ID(), database::customerproductkeywordsTableBase::GetBy_ID(), database::customerqueriesTableBase::GetBy_ID(), database::latesturlstagesTableBase::GetBy_ID(), database::customerproducturlsTableBase::GetBy_ID(), database::customersessionsTableBase::GetBy_ID(), database::customersTableBase::GetBy_ID(), database::searchquerykeywordsTableBase::GetBy_ID(), database::customersyncurlTableBase::GetBy_ID(), database::dataminingalertsTableBase::GetBy_ID(), database::dataminingblacklistTableBase::GetBy_ID(), database::dataminingcriteriaTableBase::GetBy_ID(), database::dataminingcustomersessionTableBase::GetBy_ID(), database::dataminingcustomerTableBase::GetBy_ID(), database::dictTableBase::GetBy_ID(), database::customermatchcriteriaTableBase::GetBy_ID(), database::hyperlinksTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_ID(), database::metainfoTableBase::GetBy_ID(), database::customersynccrawlerTableBase::GetBy_ID(), database::customerdomainblacklistTableBase::GetBy_ID(), database::dataminingcriteriaalertsTableBase::GetBy_ID(), database::dockeyposTableBase::GetBy_ID(), database::dockeyTableBase::GetBy_ID(), database::docmetaTableBase::GetBy_ID(), database::cachesubdomainTableBase::GetBy_ID(), database::customerproductsTableBase::GetBy_ID(), database::cacheurlTableBase::GetBy_ID(), database::cacheparsedTableBase::GetBy_ID(), database::queryresultsTableBase::GetBy_ID(), database::syncurlsTableBase::GetBy_ID(), database::customerdomainsTableBase::GetBy_ID(), database::cacherobotsTableBase::GetBy_ID(), database::customerkeywordsTableBase::GetBy_ID(), database::cachehtmlTableBase::GetBy_ID(), database::cachesecondleveldomainTableBase::GetBy_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_ID(), database::logmessagesTableBase::GetBy_ID(), database::imagesTableBase::GetBy_ID(), database::urlsTableBase::GetBy_ID(), database::urlstagesTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetBy_imageUrl(), database::urlstagesTableBase::GetBy_int_links(), database::customerdomainsTableBase::GetBy_isDomainRegex(), database::customerkeywordsTableBase::GetBy_isKeywordRegex(), database::customerdomainblacklistTableBase::GetBy_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetBy_isPrimaryKey(), database::dataminingcriteriaTableBase::GetBy_keyword(), database::dictTableBase::GetBy_keyword(), database::customerkeywordsTableBase::GetBy_keyword(), database::searchquerykeywordsTableBase::GetBy_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetBy_last_change(), database::customersTableBase::GetBy_login(), database::dataminingcustomerTableBase::GetBy_login(), database::logmessagesTableBase::GetBy_loglevel(), database::customermatchcriteriaTableBase::GetBy_MATCHCRITERIA_ID(), database::cachesecondleveldomainTableBase::GetBy_matches(), database::cachesubdomainTableBase::GetBy_matches(), database::cachehtmlTableBase::GetBy_matches(), database::cacheurlTableBase::GetBy_matches(), database::cacheparsedTableBase::GetBy_matches(), database::cacherobotsTableBase::GetBy_matches(), database::logmessagesTableBase::GetBy_message(), database::cachesecondleveldomainTableBase::GetBy_misses(), database::cachesubdomainTableBase::GetBy_misses(), database::cachehtmlTableBase::GetBy_misses(), database::cacheurlTableBase::GetBy_misses(), database::cacheparsedTableBase::GetBy_misses(), database::cacherobotsTableBase::GetBy_misses(), database::dictTableBase::GetBy_occurrence(), database::dockeyTableBase::GetBy_occurrence(), database::docmetaTableBase::GetBy_occurrence(), database::queryresultsTableBase::GetBy_order_position(), database::dockeyposTableBase::GetBy_paragraph(), database::dataminingalertsTableBase::GetBy_param(), database::customersTableBase::GetBy_password(), database::dataminingcustomerTableBase::GetBy_password(), database::customerdomainblacklistTableBase::GetBy_path(), database::imagesTableBase::GetBy_path_part(), database::urlsTableBase::GetBy_path_part(), database::logmessagesTableBase::GetBy_pid(), database::imagesTableBase::GetBy_port(), database::urlsTableBase::GetBy_port(), database::dockeyposTableBase::GetBy_position(), database::urlstagesTableBase::GetBy_primary_ip(), database::urlstagesTableBase::GetBy_primary_port(), database::customerproductimagesTableBase::GetBy_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetBy_PRODUCT_ID(), database::customerproducturlsTableBase::GetBy_PRODUCT_ID(), database::customerproductsTableBase::GetBy_productBrand(), database::customerproductsTableBase::GetBy_productName(), database::customerproductsTableBase::GetBy_productNo(), database::customerqueriesTableBase::GetBy_query(), database::keywordqueryTableBase::GetBy_query_part(), database::urlstagesTableBase::GetBy_redirect_count(), database::matchcriteriaTableBase::GetBy_regex(), database::urlstagesTableBase::GetBy_response_code(), database::customerdomainsTableBase::GetBy_revisitInterval(), database::locksecondleveldomainTableBase::GetBy_schedule(), database::syncurlsTableBase::GetBy_schedule(), database::customersyncurlTableBase::GetBy_scheduled(), database::customersynccrawlerTableBase::GetBy_scheduled(), database::schemesTableBase::GetBy_scheme(), database::urlsTableBase::GetBy_SCHEME_ID(), database::imagesTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_search_part(), database::imagesTableBase::GetBy_search_part(), database::searchquerykeywordsTableBase::GetBy_SEARCHQUERY_ID(), database::queryresultsTableBase::GetBy_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetBy_session(), database::customersessionsTableBase::GetBy_session(), database::dataminingcustomersessionTableBase::GetBy_session(), database::cachehtmlTableBase::GetBy_size(), database::cachesubdomainTableBase::GetBy_size(), database::cacherobotsTableBase::GetBy_size(), database::cacheparsedTableBase::GetBy_size(), database::cacheurlTableBase::GetBy_size(), database::cachesecondleveldomainTableBase::GetBy_size(), database::subdomainsTableBase::GetBy_subdomain(), database::urlsTableBase::GetBy_SUBDOMAIN_ID(), database::imagesTableBase::GetBy_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_target(), database::hyperlinksTableBase::GetBy_TARGET_URL_ID(), database::imagelinksTableBase::GetBy_TARGET_URL_ID(), database::logmessagesTableBase::GetBy_threadName(), database::logmessagesTableBase::GetBy_tid(), database::topleveldomainsTableBase::GetBy_tld(), database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetBy_type(), database::dataminingcriteriaTableBase::GetBy_type(), database::metainfoTableBase::GetBy_type(), database::customermatchcriteriagrouptypeTableBase::GetBy_type(), database::customermatchcriteriaTableBase::GetBy_type(), database::docmetaTableBase::GetBy_type(), database::urlstagesTableBase::GetBy_upload_speed(), database::latesturlstagesTableBase::GetBy_URL_ID(), database::customersyncurlTableBase::GetBy_URL_ID(), database::docurlTableBase::GetBy_URL_ID(), database::customerproducturlsTableBase::GetBy_URL_ID(), database::syncurlsTableBase::GetBy_URL_ID(), database::queryresultsTableBase::GetBy_URL_ID(), database::urlstagesTableBase::GetBy_URL_ID(), database::imagesTableBase::GetBy_url_md5(), database::urlsTableBase::GetBy_url_md5(), database::documentcodeTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_URLSTAGE_ID(), database::latesturlstagesTableBase::GetBy_URLSTAGE_ID(), database::dockeyTableBase::GetBy_URLSTAGE_ID(), database::hyperlinksTableBase::GetBy_URLSTAGE_ID(), database::docmetaTableBase::GetBy_URLSTAGE_ID(), database::imagelinksTableBase::GetBy_URLSTAGE_ID(), database::queryresultsTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_value(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::UrlFetcherThread::RemoveCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
static WhereConditionCompositeOperator database::WhereCondition::And () [inline, static]
Definition at line 43 of file WhereCondition.h.
References database::AND.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByMeta(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), and crawler::GenericWebUrlFetcherThread::ReserveNextUrls().
static WhereConditionCompositeOperator database::WhereCondition::Or () [inline, static]
Definition at line 44 of file WhereCondition.h.
References database::OR.
void database::WhereCondition::AddColumn (WhereConditionTableColumn * col) [inline]
add a where condition for a column
Parameters:
col where condition for column.
Definition at line 51 of file WhereCondition.h.
References tools::PointerContainer< T >::Add(), and columns.
void database::WhereCondition::AddColumns (const std::vector< WhereConditionTableColumn * > & cols) [inline]
add multiple where conditions for multiple columns.
Parameters:
cols where conditions columns.
Definition at line 57 of file WhereCondition.h.
References tools::PointerContainer< T >::Add(), and columns.
Referenced by bot::DatabaseRepair::FixCrawlerSessionTable(), database::cachehtmlTableBase::GetBy_action_time(), database::cacheparsedTableBase::GetBy_action_time(), database::cacheurlTableBase::GetBy_action_time(), database::cacherobotsTableBase::GetBy_action_time(), database::cachesecondleveldomainTableBase::GetBy_action_time(), database::cachesubdomainTableBase::GetBy_action_time(), database::logmessagesTableBase::GetBy_actiontime(), database::logmessagesTableBase::GetBy_appName(), database::documentcodeTableBase::GetBy_code(), database::urlstagesTableBase::GetBy_content_length(), database::urlstagesTableBase::GetBy_content_md5(), database::urlstagesTableBase::GetBy_content_type(), database::hyperlinksTableBase::GetBy_count(), database::locksecondleveldomainTableBase::GetBy_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetBy_CRAWLERSESSION_ID(), database::fencedsearchTableBase::GetBy_CUSTOMER_ID(), database::customersessionsTableBase::GetBy_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetBy_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetBy_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetBy_CUSTOMER_ID(), database::customerdomainsTableBase::GetBy_CUSTOMER_ID(), database::customerqueriesTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetBy_DICT_ID(), database::dockeyTableBase::GetBy_DICT_ID(), database::customerproductkeywordsTableBase::GetBy_DICT_ID(), database::docmetaTableBase::GetBy_DICT_ID(), database::dockeyposTableBase::GetBy_DOCKEY_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::dataminingblacklistTableBase::GetBy_domain(), database::customerdomainsTableBase::GetBy_domain(), database::urlstagesTableBase::GetBy_download_speed(), database::urlstagesTableBase::GetBy_download_time(), database::urlstagesTableBase::GetBy_ext_links(), database::imagesTableBase::GetBy_found_date(), database::urlsTableBase::GetBy_found_date(), database::urlstagesTableBase::GetBy_found_date(), database::customermatchcriteriagrouptypeTableBase::GetBy_groupPosition(), database::urlstagesTableBase::GetBy_html_errors(), database::crawlersessionsTableBase::GetBy_ID(), database::keywordqueryTableBase::GetBy_ID(), database::matchcriteriaTableBase::GetBy_ID(), database::schemesTableBase::GetBy_ID(), database::searchqueryTableBase::GetBy_ID(), database::secondleveldomainsTableBase::GetBy_ID(), database::subdomainsTableBase::GetBy_ID(), database::topleveldomainsTableBase::GetBy_ID(), database::docurlTableBase::GetBy_ID(), database::customerproductkeywordsTableBase::GetBy_ID(), database::fencedsearchTableBase::GetBy_ID(), database::customerproducturlsTableBase::GetBy_ID(), database::customerqueriesTableBase::GetBy_ID(), database::latesturlstagesTableBase::GetBy_ID(), database::customersessionsTableBase::GetBy_ID(), database::customersTableBase::GetBy_ID(), database::customersyncurlTableBase::GetBy_ID(), database::dataminingalertsTableBase::GetBy_ID(), database::searchquerykeywordsTableBase::GetBy_ID(), database::dataminingblacklistTableBase::GetBy_ID(), database::dataminingcriteriaTableBase::GetBy_ID(), database::dataminingcustomersessionTableBase::GetBy_ID(), database::dataminingcustomerTableBase::GetBy_ID(), database::dictTableBase::GetBy_ID(), database::customerproductimagesTableBase::GetBy_ID(), database::documentcodeTableBase::GetBy_ID(), database::hyperlinksTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_ID(), database::customerdomainblacklistTableBase::GetBy_ID(), database::customersynccrawlerTableBase::GetBy_ID(), database::metainfoTableBase::GetBy_ID(), database::dataminingcriteriaalertsTableBase::GetBy_ID(), database::dockeyposTableBase::GetBy_ID(), database::dockeyTableBase::GetBy_ID(), database::customermatchcriteriaTableBase::GetBy_ID(), database::cachesubdomainTableBase::GetBy_ID(), database::cacheurlTableBase::GetBy_ID(), database::cacherobotsTableBase::GetBy_ID(), database::customerproductsTableBase::GetBy_ID(), database::syncurlsTableBase::GetBy_ID(), database::customerdomainsTableBase::GetBy_ID(), database::queryresultsTableBase::GetBy_ID(), database::cachesecondleveldomainTableBase::GetBy_ID(), database::customerkeywordsTableBase::GetBy_ID(), database::cachehtmlTableBase::GetBy_ID(), database::cacheparsedTableBase::GetBy_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_ID(), database::docmetaTableBase::GetBy_ID(), database::logmessagesTableBase::GetBy_ID(), database::imagesTableBase::GetBy_ID(), database::urlsTableBase::GetBy_ID(), database::urlstagesTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetBy_imageUrl(), database::urlstagesTableBase::GetBy_int_links(), database::customerdomainsTableBase::GetBy_isDomainRegex(), database::customerkeywordsTableBase::GetBy_isKeywordRegex(), database::customerdomainblacklistTableBase::GetBy_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetBy_isPrimaryKey(), database::dictTableBase::GetBy_keyword(), database::dataminingcriteriaTableBase::GetBy_keyword(), database::customerkeywordsTableBase::GetBy_keyword(), database::searchquerykeywordsTableBase::GetBy_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetBy_last_change(), database::customersTableBase::GetBy_login(), database::dataminingcustomerTableBase::GetBy_login(), database::logmessagesTableBase::GetBy_loglevel(), database::customermatchcriteriaTableBase::GetBy_MATCHCRITERIA_ID(), database::cacheurlTableBase::GetBy_matches(), database::cacherobotsTableBase::GetBy_matches(), database::cachehtmlTableBase::GetBy_matches(), database::cachesecondleveldomainTableBase::GetBy_matches(), database::cachesubdomainTableBase::GetBy_matches(), database::cacheparsedTableBase::GetBy_matches(), database::logmessagesTableBase::GetBy_message(), database::cacheurlTableBase::GetBy_misses(), database::cacherobotsTableBase::GetBy_misses(), database::cachehtmlTableBase::GetBy_misses(), database::cachesecondleveldomainTableBase::GetBy_misses(), database::cachesubdomainTableBase::GetBy_misses(), database::cacheparsedTableBase::GetBy_misses(), database::dictTableBase::GetBy_occurrence(), database::dockeyTableBase::GetBy_occurrence(), database::docmetaTableBase::GetBy_occurrence(), database::queryresultsTableBase::GetBy_order_position(), database::dockeyposTableBase::GetBy_paragraph(), database::dataminingalertsTableBase::GetBy_param(), database::customersTableBase::GetBy_password(), database::dataminingcustomerTableBase::GetBy_password(), database::customerdomainblacklistTableBase::GetBy_path(), database::imagesTableBase::GetBy_path_part(), database::urlsTableBase::GetBy_path_part(), database::logmessagesTableBase::GetBy_pid(), database::imagesTableBase::GetBy_port(), database::urlsTableBase::GetBy_port(), database::dockeyposTableBase::GetBy_position(), database::urlstagesTableBase::GetBy_primary_ip(), database::urlstagesTableBase::GetBy_primary_port(), database::customerproductkeywordsTableBase::GetBy_PRODUCT_ID(), database::customerproducturlsTableBase::GetBy_PRODUCT_ID(), database::customerproductimagesTableBase::GetBy_PRODUCT_ID(), database::customerproductsTableBase::GetBy_productBrand(), database::customerproductsTableBase::GetBy_productName(), database::customerproductsTableBase::GetBy_productNo(), database::customerqueriesTableBase::GetBy_query(), database::keywordqueryTableBase::GetBy_query_part(), database::urlstagesTableBase::GetBy_redirect_count(), database::matchcriteriaTableBase::GetBy_regex(), database::urlstagesTableBase::GetBy_response_code(), database::customerdomainsTableBase::GetBy_revisitInterval(), database::locksecondleveldomainTableBase::GetBy_schedule(), database::syncurlsTableBase::GetBy_schedule(), database::customersyncurlTableBase::GetBy_scheduled(), database::customersynccrawlerTableBase::GetBy_scheduled(), database::schemesTableBase::GetBy_scheme(), database::imagesTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_SCHEME_ID(), database::imagesTableBase::GetBy_search_part(), database::urlsTableBase::GetBy_search_part(), database::queryresultsTableBase::GetBy_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::GetBy_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetBy_session(), database::customersessionsTableBase::GetBy_session(), database::dataminingcustomersessionTableBase::GetBy_session(), database::cacheurlTableBase::GetBy_size(), database::cachehtmlTableBase::GetBy_size(), database::cachesecondleveldomainTableBase::GetBy_size(), database::cacherobotsTableBase::GetBy_size(), database::cachesubdomainTableBase::GetBy_size(), database::cacheparsedTableBase::GetBy_size(), database::subdomainsTableBase::GetBy_subdomain(), database::imagesTableBase::GetBy_SUBDOMAIN_ID(), database::urlsTableBase::GetBy_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_target(), database::imagelinksTableBase::GetBy_TARGET_URL_ID(), database::hyperlinksTableBase::GetBy_TARGET_URL_ID(), database::logmessagesTableBase::GetBy_threadName(), database::logmessagesTableBase::GetBy_tid(), database::topleveldomainsTableBase::GetBy_tld(), database::imagesTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetBy_type(), database::dataminingcriteriaTableBase::GetBy_type(), database::metainfoTableBase::GetBy_type(), database::customermatchcriteriagrouptypeTableBase::GetBy_type(), database::customermatchcriteriaTableBase::GetBy_type(), database::docmetaTableBase::GetBy_type(), database::urlstagesTableBase::GetBy_upload_speed(), database::customersyncurlTableBase::GetBy_URL_ID(), database::latesturlstagesTableBase::GetBy_URL_ID(), database::docurlTableBase::GetBy_URL_ID(), database::customerproducturlsTableBase::GetBy_URL_ID(), database::syncurlsTableBase::GetBy_URL_ID(), database::queryresultsTableBase::GetBy_URL_ID(), database::urlstagesTableBase::GetBy_URL_ID(), database::imagesTableBase::GetBy_url_md5(), database::urlsTableBase::GetBy_url_md5(), database::documentcodeTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_URLSTAGE_ID(), database::latesturlstagesTableBase::GetBy_URLSTAGE_ID(), database::dockeyTableBase::GetBy_URLSTAGE_ID(), database::hyperlinksTableBase::GetBy_URLSTAGE_ID(), database::docmetaTableBase::GetBy_URLSTAGE_ID(), database::imagelinksTableBase::GetBy_URLSTAGE_ID(), database::queryresultsTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_value(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::UrlFetcherThread::RemoveCrawlerSessionID(), database::UpdateStatement::UpdateStatement(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
std::string database::WhereCondition::ToString (database::DatabaseConnection * db) const
gets sql equivalent of where conditions for this statement.
Parameters:
db database connection.
Returns:
sql string.
Definition at line 35 of file WhereCondition.cpp.
References columns, tools::PointerContainer< T >::GetConstIter(), tools::PointerContainer< T >::IsIterEnd(), tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), and tools::PointerContainer< T >::Size().
Referenced by database::DeleteStatement::ToSQL(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
Member Data Documentation
WhereConditionTableColumnContainer database::WhereCondition::columns [private]
Definition at line 67 of file WhereCondition.h.
Referenced by AddColumn(), AddColumns(), and ToString().
The documentation for this class was generated from the following files:
Database/src/WhereCondition.h
Database/src/WhereCondition.cpp