DeepNet: htmlparser::TLD Class Reference
htmlparser::TLD Class Reference
class containing all top level domains available
#include <TLD.h>
Static Public Member Functions
static bool InitTLDCache (database::DatabaseConnection *db)
initializes top level domain cache, this function should be called once per runtime
static const std::string GetTLDByID (const long long tldID)
gets a top level domain by it's id
static const long long GetTLDIDByTLD (const std::string &tld)
gets a top level domain by it's name
static void GetTLDStrings (std::vector< std::string > &tlds)
gets a vector filled with all available top level domains
Private Member Functions
bool Init (database::DatabaseConnection *db)
Static Private Attributes
static TLD tld
static std::map< long long,
std::string > mapIdTld
static std::map< std::string,
long long > mapTldId
static threading::Mutex initMutex
static bool isInitialized = false
Detailed Description
class containing all top level domains available
Definition at line 23 of file TLD.h.
Member Function Documentation
bool htmlparser::TLD::InitTLDCache (database::DatabaseConnection * db) [static]
initializes top level domain cache, this function should be called once per runtime
Parameters:
db database connection
Returns:
true if successful, false if unsuccessful
Definition at line 22 of file TLD.cpp.
References Init(), initMutex, isInitialized, and tld.
Referenced by bot::Bot::InitCacheConfigParams(), and fastcgiserver::FastCGIServer::InitDatabaseConfigs().
const std::string htmlparser::TLD::GetTLDByID (const long long tldID) [static]
gets a top level domain by it's id
Parameters:
tldID id of the toplevel domain
Returns:
top level domain as string
Definition at line 32 of file TLD.cpp.
References mapIdTld.
Referenced by htmlparser::DatabaseUrl::InitByIDs().
const long long htmlparser::TLD::GetTLDIDByTLD (const std::string & tld) [static]
gets a top level domain by it's name
Parameters:
tld top level domain string
Returns:
top level domain id
Definition at line 40 of file TLD.cpp.
References mapTldId, and tld.
Referenced by htmlparser::DatabaseUrl::InitByHttpUrl(), and parser::GenericWebHtmlParserThread::InsertImages().
void htmlparser::TLD::GetTLDStrings (std::vector< std::string > & tlds) [static]
gets a vector filled with all available top level domains
Parameters:
tlds available top level domains
Definition at line 77 of file TLD.cpp.
References tools::ContainerTools::Map1ToVector(), and mapTldId.
Referenced by bot::Bot::InitCacheConfigParams().
bool htmlparser::TLD::Init (database::DatabaseConnection * db) [private]
Definition at line 48 of file TLD.cpp.
References database::topleveldomainsTableBase::CreateTableDefinition(), database::topleveldomainsTableBase::Get_ID(), database::topleveldomainsTableBase::Get_tld(), tools::PointerContainer< T >::GetIter(), isInitialized, tools::PointerContainer< T >::IsIterEnd(), mapIdTld, mapTldId, tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and tld.
Referenced by InitTLDCache().
Member Data Documentation
TLD htmlparser::TLD::tld [static, private]
Definition at line 57 of file TLD.h.
Referenced by GetTLDIDByTLD(), Init(), and InitTLDCache().
std::map< long long, std::string > htmlparser::TLD::mapIdTld [static, private]
Definition at line 59 of file TLD.h.
Referenced by GetTLDByID(), and Init().
std::map< std::string, long long > htmlparser::TLD::mapTldId [static, private]
Definition at line 60 of file TLD.h.
Referenced by GetTLDIDByTLD(), GetTLDStrings(), and Init().
threading::Mutex htmlparser::TLD::initMutex [static, private]
Definition at line 62 of file TLD.h.
Referenced by InitTLDCache().
bool htmlparser::TLD::isInitialized = false [static, private]
Definition at line 63 of file TLD.h.
Referenced by Init(), and InitTLDCache().
The documentation for this class was generated from the following files:
HtmlParser/src/TLD.h
HtmlParser/src/TLD.cpp