DeepNet: queryserver::UrlStageEntry Class Reference
queryserver::UrlStageEntry Class Reference
#include <UrlStageEntry.h>
Public Member Functions
UrlStageEntry (const UrlStageProperties &stageProperties, const std::vector< KeywordEntry > &keywords, const BackLinkEntry &backlinkEntry)
const std::vector< KeywordEntry > & Keywords () const
const BackLinkEntry & BackLinks () const
const UrlStageProperties & UrlStageProperty () const
Relevance GetTotalRelevance () const
Private Attributes
UrlStageProperties stageProperties
std::vector< KeywordEntry > keywords
BackLinkEntry backlinkEntry
Detailed Description
Definition at line 54 of file UrlStageEntry.h.
Constructor & Destructor Documentation
queryserver::UrlStageEntry::UrlStageEntry (const UrlStageProperties & stageProperties, const std::vector< KeywordEntry > & keywords, const BackLinkEntry & backlinkEntry) [inline]
Definition at line 57 of file UrlStageEntry.h.
Member Function Documentation
const std::vector<KeywordEntry>& queryserver::UrlStageEntry::Keywords () const [inline]
Definition at line 63 of file UrlStageEntry.h.
References keywords.
Referenced by GetTotalRelevance().
const BackLinkEntry& queryserver::UrlStageEntry::BackLinks () const [inline]
Definition at line 64 of file UrlStageEntry.h.
References backlinkEntry.
const UrlStageProperties& queryserver::UrlStageEntry::UrlStageProperty () const [inline]
Definition at line 65 of file UrlStageEntry.h.
References stageProperties.
Referenced by queryserver::XMLQueryResponse::GroupResults().
Relevance queryserver::UrlStageEntry::GetTotalRelevance () const
Definition at line 12 of file UrlStageEntry.cpp.
References Keywords(), and keywords.
Referenced by queryserver::XMLQueryResponse::SortResults().
Member Data Documentation
UrlStageProperties queryserver::UrlStageEntry::stageProperties [private]
Definition at line 71 of file UrlStageEntry.h.
Referenced by UrlStageProperty().
std::vector<KeywordEntry> queryserver::UrlStageEntry::keywords [private]
Definition at line 72 of file UrlStageEntry.h.
Referenced by GetTotalRelevance(), and Keywords().
BackLinkEntry queryserver::UrlStageEntry::backlinkEntry [private]
Definition at line 73 of file UrlStageEntry.h.
Referenced by BackLinks().
The documentation for this class was generated from the following files:
QueryServer/src/UrlStageEntry.h
QueryServer/src/UrlStageEntry.cpp