DeepNet: Indexer/generated/content_lexer.yy.cpp File Reference
Indexer/generated/content_lexer.yy.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <string>
#include <iostream>
#include "content_parser.tab.hpp"
#include "../src/ContentIndexer.h"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
struct yyguts_t
Defines
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define YY_TYPEDEF_YY_SCANNER_T
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r
#define BEGIN yyg->yy_start = 1 + 2 *
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE contentIndexer_yyrestart(yyin ,yyscanner)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, yyg->yytext_ptr , yyscanner)
#define YY_TYPEDEF_YY_SIZE_T
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
#define YY_FLUSH_BUFFER contentIndexer_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
#define yy_new_buffer contentIndexer_yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define yytext_ptr yytext_r
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 8
#define YY_END_OF_BUFFER 9
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_SKIP_YYWRAP
#define YY_DECL extern "C" int contentIndexer_yylex(YYSTYPE * yylval_param ,yyscan_t yyscanner)
#define YYSTYPE std::string*
#define COPY_TO_STD_STRING *yylval = new std::string(); (*(*yylval)) = yytext;
#define YY_INPUT(buf, result, max_size) { int pos = yyextra->indexer->Read(buf,max_size); result = (pos > 0) ? pos : YY_NULL; }
#define INITIAL 0
#define YY_EXTRA_TYPE ContentIndexerCtx*
#define yylval yyg->yylval_r
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg , yyscanner)
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef void * yyscan_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void contentIndexer_yyrestart (FILE *input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
void contentIndexer_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
YY_BUFFER_STATE contentIndexer_yy_create_buffer (FILE *file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
void contentIndexer_yy_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
void contentIndexer_yy_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
void contentIndexer_yypush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
void contentIndexer_yypop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
static void contentIndexer_yyensure_buffer_stack (yyscan_t yyscanner)
static void contentIndexer_yy_load_buffer_state (yyscan_t yyscanner)
static void contentIndexer_yy_init_buffer (YY_BUFFER_STATE b, FILE *file, yyscan_t yyscanner)
YY_BUFFER_STATE contentIndexer_yy_scan_buffer (char *base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE contentIndexer_yy_scan_string (yyconst char *yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE contentIndexer_yy_scan_bytes (yyconst char *yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
void * contentIndexer_yyalloc (yy_size_t, yyscan_t yyscanner)
void * contentIndexer_yyrealloc (void *, yy_size_t, yyscan_t yyscanner)
void contentIndexer_yyfree (void *, yyscan_t yyscanner)
static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner)
static int yy_get_next_buffer (yyscan_t yyscanner)
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner)
static int contentIndexer_yywrap (yyscan_t)
int contentIndexer_yylex_init_extra (ContentIndexerCtx *yy_user_defined, yyscan_t *ptr_yy_globals)
int contentIndexer_yylex_destroy (yyscan_t yyscanner)
int contentIndexer_yyerror (ContentIndexerCtx *, const char *)
static int yy_init_globals (yyscan_t yyscanner)
int contentIndexer_yylex_init (yyscan_t *scanner)
int contentIndexer_yylex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t *scanner)
int contentIndexer_yyget_debug (yyscan_t yyscanner)
void contentIndexer_yyset_debug (int debug_flag, yyscan_t yyscanner)
YY_EXTRA_TYPE contentIndexer_yyget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
void contentIndexer_yyset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
FILE * contentIndexer_yyget_in (yyscan_t yyscanner)
Get the input stream.
void contentIndexer_yyset_in (FILE *in_str, yyscan_t yyscanner)
Set the input stream.
FILE * contentIndexer_yyget_out (yyscan_t yyscanner)
Get the output stream.
void contentIndexer_yyset_out (FILE *out_str, yyscan_t yyscanner)
int contentIndexer_yyget_leng (yyscan_t yyscanner)
Get the length of the current token.
char * contentIndexer_yyget_text (yyscan_t yyscanner)
Get the current token.
int contentIndexer_yyget_lineno (yyscan_t yyscanner)
Get the current line number.
void contentIndexer_yyset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
YYSTYPE * contentIndexer_yyget_lval (yyscan_t yyscanner)
void contentIndexer_yyset_lval (YYSTYPE *yylval_param, yyscan_t yyscanner)
static int input (yyscan_t yyscanner)
if (!yyg->yy_init)
while (1)
int isatty (int)
static void yy_fatal_error (yyconst char *msg, yyscan_t yyscanner)
int contentIndexer_yyget_column (yyscan_t yyscanner)
Get the current column number.
void contentIndexer_yyset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Variables
static yyconst flex_int16_t yy_nxt [][256]
static yyconst flex_int16_t yy_accept [29]
static yyconst flex_int32_t yy_rule_can_match_eol [9]
static yyconst yy_state_type yy_NUL_trans [29]
YY_DECL register yy_state_type yy_current_state
The main scanner function which does all the work.
register char * yy_cp
register char * yy_bp
register int yy_act
struct yyguts_t * yyg = (struct yyguts_t*)yyscanner
yylval = yylval_param
Define Documentation
#define YY_INT_ALIGNED short int
Definition at line 5 of file content_lexer.yy.cpp.
#define FLEX_SCANNER
Definition at line 9 of file content_lexer.yy.cpp.
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 10 of file content_lexer.yy.cpp.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 11 of file content_lexer.yy.cpp.
#define YY_FLEX_SUBMINOR_VERSION 35
Definition at line 12 of file content_lexer.yy.cpp.
#define FLEX_BETA
Definition at line 14 of file content_lexer.yy.cpp.
#define FLEXINT_H
Definition at line 30 of file content_lexer.yy.cpp.
#define INT8_MIN (-128)
Definition at line 60 of file content_lexer.yy.cpp.
#define INT16_MIN (-32767-1)
Definition at line 63 of file content_lexer.yy.cpp.
#define INT32_MIN (-2147483647-1)
Definition at line 66 of file content_lexer.yy.cpp.
#define INT8_MAX (127)
Definition at line 69 of file content_lexer.yy.cpp.
#define INT16_MAX (32767)
Definition at line 72 of file content_lexer.yy.cpp.
#define INT32_MAX (2147483647)
Definition at line 75 of file content_lexer.yy.cpp.
#define UINT8_MAX (255U)
Definition at line 78 of file content_lexer.yy.cpp.
#define UINT16_MAX (65535U)
Definition at line 81 of file content_lexer.yy.cpp.
#define UINT32_MAX (4294967295U)
Definition at line 84 of file content_lexer.yy.cpp.
#define yyconst
Definition at line 109 of file content_lexer.yy.cpp.
#define YY_NULL 0
Definition at line 113 of file content_lexer.yy.cpp.
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 120 of file content_lexer.yy.cpp.
Referenced by while(), and yy_get_previous_state().
#define YY_TYPEDEF_YY_SCANNER_T
Definition at line 124 of file content_lexer.yy.cpp.
#define yyin yyg->yyin_r
Definition at line 130 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_load_buffer_state(), contentIndexer_yyget_in(), contentIndexer_yyrestart(), contentIndexer_yyset_in(), if(), input(), while(), yy_get_next_buffer(), and yy_init_globals().
#define yyout yyg->yyout_r
Definition at line 131 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_out(), contentIndexer_yyset_out(), if(), and yy_init_globals().
#define yyextra yyg->yyextra_r
Definition at line 132 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_extra(), and contentIndexer_yyset_extra().
#define yyleng yyg->yyleng_r
Definition at line 133 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_leng(), and while().
#define yytext yyg->yytext_r
Definition at line 134 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_text(), and while().
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
Definition at line 135 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_lineno(), contentIndexer_yyset_lineno(), input(), and while().
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
Definition at line 136 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_column(), contentIndexer_yyset_column(), input(), and while().
#define yy_flex_debug yyg->yy_flex_debug_r
Definition at line 137 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_debug(), and contentIndexer_yyset_debug().
#define BEGIN yyg->yy_start = 1 + 2 *
Definition at line 143 of file content_lexer.yy.cpp.
#define YY_START ((yyg->yy_start - 1) / 2)
Definition at line 149 of file content_lexer.yy.cpp.
Referenced by while().
#define YYSTATE YY_START
Definition at line 150 of file content_lexer.yy.cpp.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 153 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_NEW_FILE contentIndexer_yyrestart(yyin ,yyscanner)
Definition at line 156 of file content_lexer.yy.cpp.
Referenced by input(), and while().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 158 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_flush_buffer(), contentIndexer_yy_scan_buffer(), contentIndexer_yy_scan_bytes(), input(), and yy_get_next_buffer().
#define YY_BUF_SIZE 16384
Definition at line 169 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyrestart(), and if().
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 175 of file content_lexer.yy.cpp.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 178 of file content_lexer.yy.cpp.
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 182 of file content_lexer.yy.cpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_END_OF_FILE 1
Definition at line 183 of file content_lexer.yy.cpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define EOB_ACT_LAST_MATCH 2
Definition at line 184 of file content_lexer.yy.cpp.
Referenced by input(), while(), and yy_get_next_buffer().
#define YY_LESS_LINENO (n)
Value:
do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
Definition at line 193 of file content_lexer.yy.cpp.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = yyg->yy_hold_char; \
                YY_RESTORE_YY_MORE_OFFSET \
                yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 2478 of file content_lexer.yy.cpp.
#define unput (c) yyunput(c, yyg->yytext_ptr , yyscanner)
Definition at line 215 of file content_lexer.yy.cpp.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 218 of file content_lexer.yy.cpp.
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 223 of file content_lexer.yy.cpp.
#define YY_BUFFER_NEW 0
Definition at line 270 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_flush_buffer(), contentIndexer_yy_scan_buffer(), and while().
#define YY_BUFFER_NORMAL 1
Definition at line 271 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 282 of file content_lexer.yy.cpp.
Referenced by yy_get_next_buffer().
#define YY_CURRENT_BUFFER
Value:
(yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
Definition at line 293 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_delete_buffer(), contentIndexer_yy_flush_buffer(), contentIndexer_yy_init_buffer(), contentIndexer_yy_switch_to_buffer(), contentIndexer_yyget_column(), contentIndexer_yyget_lineno(), contentIndexer_yylex_destroy(), contentIndexer_yypop_buffer_state(), contentIndexer_yypush_buffer_state(), contentIndexer_yyrestart(), contentIndexer_yyset_column(), contentIndexer_yyset_lineno(), if(), and yy_get_next_buffer().
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]
Definition at line 300 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_delete_buffer(), contentIndexer_yy_load_buffer_state(), contentIndexer_yy_switch_to_buffer(), contentIndexer_yylex_destroy(), contentIndexer_yypop_buffer_state(), contentIndexer_yypush_buffer_state(), contentIndexer_yyrestart(), if(), input(), while(), and yy_get_next_buffer().
#define YY_FLUSH_BUFFER contentIndexer_yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)
Definition at line 314 of file content_lexer.yy.cpp.
#define yy_new_buffer contentIndexer_yy_create_buffer
Definition at line 324 of file content_lexer.yy.cpp.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        contentIndexer_yyensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            contentIndexer_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 326 of file content_lexer.yy.cpp.
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        contentIndexer_yyensure_buffer_stack (yyscanner); \
                YY_CURRENT_BUFFER_LVALUE =    \
            contentIndexer_yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
        } \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 336 of file content_lexer.yy.cpp.
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 346 of file content_lexer.yy.cpp.
#define yytext_ptr yytext_r
Definition at line 354 of file content_lexer.yy.cpp.
#define YY_DO_BEFORE_ACTION
Value:
yyg->yytext_ptr = yy_bp; \
        yyleng = (size_t) (yy_cp - yy_bp); \
        yyg->yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
        yyg->yy_c_buf_p = yy_cp;
Definition at line 1283 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_NUM_RULES 8
Definition at line 1290 of file content_lexer.yy.cpp.
#define YY_END_OF_BUFFER 9
Definition at line 1291 of file content_lexer.yy.cpp.
Referenced by while().
#define REJECT reject_used_but_not_detected
Definition at line 1321 of file content_lexer.yy.cpp.
#define yymore () yymore_used_but_not_detected
Definition at line 1322 of file content_lexer.yy.cpp.
#define YY_MORE_ADJ 0
Definition at line 1323 of file content_lexer.yy.cpp.
Referenced by while(), yy_get_next_buffer(), and yy_get_previous_state().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 1324 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_SKIP_YYWRAP
Definition at line 1329 of file content_lexer.yy.cpp.
#define YY_DECL extern "C" int contentIndexer_yylex(YYSTYPE * yylval_param ,yyscan_t yyscanner)
Definition at line 1330 of file content_lexer.yy.cpp.
#define YYSTYPE std::string*
Definition at line 1331 of file content_lexer.yy.cpp.
#define COPY_TO_STD_STRING *yylval = new std::string(); (*(*yylval)) = yytext;
Definition at line 1332 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_INPUT (buf, result, max_size) { int pos = yyextra->indexer->Read(buf,max_size); result = (pos > 0) ? pos : YY_NULL; }
Definition at line 1333 of file content_lexer.yy.cpp.
Referenced by yy_get_next_buffer().
#define INITIAL 0
Definition at line 1350 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_EXTRA_TYPE ContentIndexerCtx*
Definition at line 1360 of file content_lexer.yy.cpp.
#define yylval yyg->yylval_r
Definition at line 1402 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyget_lval(), contentIndexer_yyset_lval(), metaIndexer_yyget_lval(), and metaIndexer_yyset_lval().
#define YY_READ_BUF_SIZE 8192
Definition at line 1477 of file content_lexer.yy.cpp.
Referenced by yy_get_next_buffer().
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
Definition at line 1486 of file content_lexer.yy.cpp.
Referenced by while().
#define yyterminate () return YY_NULL
Definition at line 1514 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_START_STACK_INCR 25
Definition at line 1519 of file content_lexer.yy.cpp.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg , yyscanner)
Definition at line 1524 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_create_buffer(), contentIndexer_yy_scan_buffer(), contentIndexer_yy_scan_bytes(), contentIndexer_yyensure_buffer_stack(), while(), and yy_get_next_buffer().
#define YY_USER_ACTION
Definition at line 1546 of file content_lexer.yy.cpp.
#define YY_BREAK break;
Definition at line 1551 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 1554 of file content_lexer.yy.cpp.
Referenced by while().
#define YY_EXIT_FAILURE 2
Definition at line 2466 of file content_lexer.yy.cpp.
Referenced by yy_fatal_error().
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                yytext[yyleng] = yyg->yy_hold_char; \
                yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
                yyg->yy_hold_char = *yyg->yy_c_buf_p; \
                *yyg->yy_c_buf_p = '\0'; \
                yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
Definition at line 2478 of file content_lexer.yy.cpp.
#define YYTABLES_NAME "yytables"
Definition at line 2823 of file content_lexer.yy.cpp.
Typedef Documentation
typedef signed char flex_int8_t
Definition at line 51 of file content_lexer.yy.cpp.
typedef short int flex_int16_t
Definition at line 52 of file content_lexer.yy.cpp.
typedef int flex_int32_t
Definition at line 53 of file content_lexer.yy.cpp.
typedef unsigned char flex_uint8_t
Definition at line 54 of file content_lexer.yy.cpp.
typedef unsigned short int flex_uint16_t
Definition at line 55 of file content_lexer.yy.cpp.
typedef unsigned int flex_uint32_t
Definition at line 56 of file content_lexer.yy.cpp.
typedef void* yyscan_t
Definition at line 125 of file content_lexer.yy.cpp.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 179 of file content_lexer.yy.cpp.
typedef size_t yy_size_t
Definition at line 219 of file content_lexer.yy.cpp.
typedef unsigned char YY_CHAR
Definition at line 350 of file content_lexer.yy.cpp.
typedef int yy_state_type
Definition at line 352 of file content_lexer.yy.cpp.
Function Documentation
void contentIndexer_yyrestart (FILE * input_file, yyscan_t yyscanner)
Immediately switch to a different input stream.
Parameters:
input_file A readable stream.
yyscanner The scanner object.
Note:
This function does not reset the start condition to INITIAL .
Definition at line 2108 of file content_lexer.yy.cpp.
References contentIndexer_yy_create_buffer(), contentIndexer_yy_init_buffer(), contentIndexer_yy_load_buffer_state(), contentIndexer_yyensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyin.
Referenced by input(), and yy_get_next_buffer().
void contentIndexer_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Switch to a different input buffer.
Parameters:
new_buffer The new input buffer.
yyscanner The scanner object.
Definition at line 2126 of file content_lexer.yy.cpp.
References contentIndexer_yy_load_buffer_state(), contentIndexer_yyensure_buffer_stack(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
Referenced by contentIndexer_yy_scan_buffer().
YY_BUFFER_STATE contentIndexer_yy_create_buffer (FILE * file, int size, yyscan_t yyscanner)
Allocate and initialize an input buffer state.
Parameters:
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
yyscanner The scanner object.
Returns:
the allocated buffer state.
Definition at line 2173 of file content_lexer.yy.cpp.
References contentIndexer_yy_init_buffer(), contentIndexer_yyalloc(), yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by contentIndexer_yyrestart(), and if().
void contentIndexer_yy_delete_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Destroy the buffer.
Parameters:
b a buffer created with contentIndexer_yy_create_buffer()
yyscanner The scanner object.
Definition at line 2201 of file content_lexer.yy.cpp.
References contentIndexer_yyfree(), yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_buffer_state::yy_is_our_buffer.
Referenced by contentIndexer_yylex_destroy(), and contentIndexer_yypop_buffer_state().
void contentIndexer_yy_flush_buffer (YY_BUFFER_STATE b, yyscan_t yyscanner)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters:
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
yyscanner The scanner object.
Definition at line 2254 of file content_lexer.yy.cpp.
References contentIndexer_yy_load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by contentIndexer_yy_init_buffer().
void contentIndexer_yypush_buffer_state (YY_BUFFER_STATE new_buffer, yyscan_t yyscanner)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters:
new_buffer The new state.
yyscanner The scanner object.
Definition at line 2284 of file content_lexer.yy.cpp.
References contentIndexer_yy_load_buffer_state(), contentIndexer_yyensure_buffer_stack(), yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, yyguts_t::yy_hold_char, and yyguts_t::yy_n_chars.
void contentIndexer_yypop_buffer_state (yyscan_t yyscanner)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Parameters:
yyscanner The scanner object.
Definition at line 2315 of file content_lexer.yy.cpp.
References contentIndexer_yy_delete_buffer(), contentIndexer_yy_load_buffer_state(), yyguts_t::yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yyguts_t::yy_did_buffer_switch_on_eof.
Referenced by contentIndexer_yylex_destroy().
static void contentIndexer_yyensure_buffer_stack (yyscan_t yyscanner) [static]
Definition at line 2335 of file content_lexer.yy.cpp.
References contentIndexer_yyalloc(), contentIndexer_yyrealloc(), yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, and YY_FATAL_ERROR.
Referenced by contentIndexer_yy_switch_to_buffer(), contentIndexer_yypush_buffer_state(), contentIndexer_yyrestart(), and if().
static void contentIndexer_yy_load_buffer_state (yyscan_t yyscanner) [static]
Definition at line 2158 of file content_lexer.yy.cpp.
References yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, and yyin.
Referenced by contentIndexer_yy_flush_buffer(), contentIndexer_yy_switch_to_buffer(), contentIndexer_yypop_buffer_state(), contentIndexer_yypush_buffer_state(), contentIndexer_yyrestart(), and if().
static void contentIndexer_yy_init_buffer (YY_BUFFER_STATE b, FILE * file, yyscan_t yyscanner) [static]
Definition at line 2225 of file content_lexer.yy.cpp.
References contentIndexer_yy_flush_buffer(), isatty(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by contentIndexer_yy_create_buffer(), and contentIndexer_yyrestart().
YY_BUFFER_STATE contentIndexer_yy_scan_buffer (char * base, yy_size_t size, yyscan_t yyscanner)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters:
base the character buffer
size the size in bytes of the character buffer
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 2385 of file content_lexer.yy.cpp.
References contentIndexer_yy_switch_to_buffer(), contentIndexer_yyalloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by contentIndexer_yy_scan_bytes().
YY_BUFFER_STATE contentIndexer_yy_scan_string (yyconst char * yystr, yyscan_t yyscanner)
Setup the input buffer state to scan a string.
The next call to contentIndexer_yylex() will scan from a copy of str.
Parameters:
yystr a NUL-terminated string to scan
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Note:
If you want to scan bytes that may contain NUL values, then use contentIndexer_yy_scan_bytes() instead.
Definition at line 2422 of file content_lexer.yy.cpp.
References contentIndexer_yy_scan_bytes().
YY_BUFFER_STATE contentIndexer_yy_scan_bytes (yyconst char * yybytes, int _yybytes_len, yyscan_t yyscanner)
Setup the input buffer state to scan the given bytes.
The next call to contentIndexer_yylex() will scan from a copy of bytes.
Parameters:
yybytes the byte buffer to scan
_yybytes_len the number of bytes in the buffer pointed to by bytes.
yyscanner The scanner object.
Returns:
the newly allocated buffer state object.
Definition at line 2435 of file content_lexer.yy.cpp.
References contentIndexer_yy_scan_buffer(), contentIndexer_yyalloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by contentIndexer_yy_scan_string().
void * contentIndexer_yyalloc (yy_size_t size, yyscan_t yyscanner)
Definition at line 2801 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_create_buffer(), contentIndexer_yy_scan_buffer(), contentIndexer_yy_scan_bytes(), contentIndexer_yyensure_buffer_stack(), contentIndexer_yylex_init(), and contentIndexer_yylex_init_extra().
void * contentIndexer_yyrealloc (void * ptr, yy_size_t size, yyscan_t yyscanner)
Definition at line 2806 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yyensure_buffer_stack(), and yy_get_next_buffer().
void contentIndexer_yyfree (void * ptr, yyscan_t yyscanner)
Definition at line 2818 of file content_lexer.yy.cpp.
Referenced by contentIndexer_yy_delete_buffer(), and contentIndexer_yylex_destroy().
static yy_state_type yy_get_previous_state (yyscan_t yyscanner) [static]
Definition at line 1969 of file content_lexer.yy.cpp.
References yy_accept, yyguts_t::yy_c_buf_p, yy_cp, yy_current_state, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yy_NUL_trans, yy_nxt, YY_SC_TO_UI, and yyguts_t::yy_start.
Referenced by while().
static yy_state_type yy_try_NUL_trans (yy_state_type current_state, yyscan_t yyscanner) [static]
Definition at line 2000 of file content_lexer.yy.cpp.
References yy_accept, yyguts_t::yy_c_buf_p, yy_cp, yy_current_state, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, and yy_NUL_trans.
Referenced by while().
static int yy_get_next_buffer (yyscan_t yyscanner) [static]
Definition at line 1834 of file content_lexer.yy.cpp.
References contentIndexer_yyrealloc(), contentIndexer_yyrestart(), EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yyguts_t::yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_READ_BUF_SIZE, and yyin.
Referenced by input(), and while().
static void yy_fatal_error (yyconst char msg[], yyscan_t yyscanner) [static]
Referenced by contentIndexer_yyset_column(), contentIndexer_yyset_lineno(), metaIndexer_yyset_column(), and metaIndexer_yyset_lineno().
static int contentIndexer_yywrap (yyscan_t) [static]
Definition at line 2834 of file content_lexer.yy.cpp.
Referenced by input(), and while().
int contentIndexer_yylex_init_extra (ContentIndexerCtx * yy_user_defined, yyscan_t * ptr_yy_globals)
int contentIndexer_yylex_destroy (yyscan_t yyscanner)
Definition at line 2748 of file content_lexer.yy.cpp.
References contentIndexer_yy_delete_buffer(), contentIndexer_yyfree(), contentIndexer_yypop_buffer_state(), yyguts_t::yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_globals(), and yyguts_t::yy_start_stack.
int contentIndexer_yyerror (ContentIndexerCtx * , const char *)
Definition at line 2829 of file content_lexer.yy.cpp.
static int yy_init_globals (yyscan_t yyscanner) [static]
Definition at line 2714 of file content_lexer.yy.cpp.
References yyguts_t::yy_buffer_stack, yyguts_t::yy_buffer_stack_max, yyguts_t::yy_buffer_stack_top, yyguts_t::yy_c_buf_p, yyguts_t::yy_init, yyguts_t::yy_start, yyguts_t::yy_start_stack, yyguts_t::yy_start_stack_depth, yyguts_t::yy_start_stack_ptr, yyin, and yyout.
Referenced by contentIndexer_yylex_destroy(), contentIndexer_yylex_init(), and contentIndexer_yylex_init_extra().
int contentIndexer_yylex_init (yyscan_t * scanner)
Definition at line 2657 of file content_lexer.yy.cpp.
References contentIndexer_yyalloc(), and yy_init_globals().
int contentIndexer_yylex_init_extra (YY_EXTRA_TYPE user_defined, yyscan_t * scanner)
Definition at line 2686 of file content_lexer.yy.cpp.
References contentIndexer_yyalloc(), contentIndexer_yyset_extra(), and yy_init_globals().
int contentIndexer_yyget_debug (yyscan_t yyscanner)
Definition at line 2624 of file content_lexer.yy.cpp.
References yy_flex_debug.
void contentIndexer_yyset_debug (int debug_flag, yyscan_t yyscanner)
Definition at line 2630 of file content_lexer.yy.cpp.
References yy_flex_debug.
YY_EXTRA_TYPE contentIndexer_yyget_extra (yyscan_t yyscanner)
Get the user-defined data for this scanner.
Parameters:
yyscanner The scanner object.
Definition at line 2497 of file content_lexer.yy.cpp.
References yyextra.
void contentIndexer_yyset_extra (YY_EXTRA_TYPE user_defined, yyscan_t yyscanner)
Set the user-defined data.
This data is never touched by the scanner.
Parameters:
user_defined The data to be associated with this scanner.
yyscanner The scanner object.
Definition at line 2570 of file content_lexer.yy.cpp.
References yyextra.
Referenced by contentIndexer_yylex_init_extra().
FILE * contentIndexer_yyget_in (yyscan_t yyscanner)
Get the input stream.
Parameters:
yyscanner The scanner object.
Definition at line 2532 of file content_lexer.yy.cpp.
References yyin.
void contentIndexer_yyset_in (FILE * in_str, yyscan_t yyscanner)
Set the input stream.
This does not discard the current input buffer.
Parameters:
in_str A readable stream.
yyscanner The scanner object.
See also:
contentIndexer_yy_switch_to_buffer
Definition at line 2612 of file content_lexer.yy.cpp.
References yyin.
FILE * contentIndexer_yyget_out (yyscan_t yyscanner)
Get the output stream.
Parameters:
yyscanner The scanner object.
Definition at line 2541 of file content_lexer.yy.cpp.
References yyout.
void contentIndexer_yyset_out (FILE * out_str, yyscan_t yyscanner)
Definition at line 2618 of file content_lexer.yy.cpp.
References yyout.
int contentIndexer_yyget_leng (yyscan_t yyscanner)
Get the length of the current token.
Parameters:
yyscanner The scanner object.
Definition at line 2550 of file content_lexer.yy.cpp.
References yyleng.
char * contentIndexer_yyget_text (yyscan_t yyscanner)
Get the current token.
Parameters:
yyscanner The scanner object.
Definition at line 2560 of file content_lexer.yy.cpp.
References yytext.
int contentIndexer_yyget_lineno (yyscan_t yyscanner)
Get the current line number.
Parameters:
yyscanner The scanner object.
Definition at line 2506 of file content_lexer.yy.cpp.
References YY_CURRENT_BUFFER, and yylineno.
void contentIndexer_yyset_lineno (int line_number, yyscan_t yyscanner)
Set the current line number.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 2580 of file content_lexer.yy.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yylineno.
YYSTYPE * contentIndexer_yyget_lval (yyscan_t yyscanner)
Definition at line 2638 of file content_lexer.yy.cpp.
References yylval.
void contentIndexer_yyset_lval (YYSTYPE * yylval_param, yyscan_t yyscanner)
Definition at line 2644 of file content_lexer.yy.cpp.
References yylval.
static int input (yyscan_t yyscanner) [static]
Definition at line 2025 of file content_lexer.yy.cpp.
References contentIndexer_yyrestart(), contentIndexer_yywrap(), EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, if(), yyguts_t::yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yyguts_t::yy_hold_char, yyguts_t::yy_n_chars, YY_NEW_FILE, yycolumn, yyin, and yylineno.
Referenced by indexing::IndexerBase::Parse().
if (!yyg-> yy_init)
Definition at line 1572 of file content_lexer.yy.cpp.
References contentIndexer_yy_create_buffer(), contentIndexer_yy_load_buffer_state(), contentIndexer_yyensure_buffer_stack(), YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yyguts_t::yy_init, yyguts_t::yy_start, yyin, and yyout.
Referenced by input().
while (1)
Definition at line 1598 of file content_lexer.yy.cpp.
References CHARACTER_REFERENCE, contentIndexer_yywrap(), COPY_TO_STD_STRING, ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, FLOAT_NUMBER, HTML_ENTITY, INITIAL, INT_NUMBER, TERMINATE_WORD, WORD, yy_accept, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yyguts_t::yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, yy_current_state, yyguts_t::yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yyguts_t::yy_hold_char, yyguts_t::yy_last_accepting_cpos, yyguts_t::yy_last_accepting_state, YY_MORE_ADJ, yyguts_t::yy_n_chars, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, yy_rule_can_match_eol, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yyguts_t::yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yycolumn, yyin, yyleng, yylineno, yyterminate, and yytext.
int isatty (int)
Referenced by contentIndexer_yy_init_buffer(), and metaIndexer_yy_init_buffer().
static void yy_fatal_error (yyconst char * msg, yyscan_t yyscanner) [static]
Definition at line 2469 of file content_lexer.yy.cpp.
References YY_EXIT_FAILURE.
int contentIndexer_yyget_column (yyscan_t yyscanner)
Get the current column number.
Parameters:
yyscanner The scanner object.
Definition at line 2519 of file content_lexer.yy.cpp.
References YY_CURRENT_BUFFER, and yycolumn.
void contentIndexer_yyset_column (int column_no, yyscan_t yyscanner)
Set the current column.
Parameters:
line_number
yyscanner The scanner object.
Definition at line 2595 of file content_lexer.yy.cpp.
References YY_CURRENT_BUFFER, yy_fatal_error(), and yycolumn.
Variable Documentation
yyconst flex_int16_t yy_nxt[][256] [static]
Definition at line 355 of file content_lexer.yy.cpp.
Referenced by while(), and yy_get_previous_state().
yyconst flex_int16_t yy_accept[29] [static]
Initial value:
    {   0,
        3,    3,    9,    7,    8,    7,    3,    3,    0,    0,
        0,    3,    2,    0,    2,    2,    0,    0,    0,    1,
        0,    5,    0,    0,    0,    6,    0,    4
    }
Definition at line 1299 of file content_lexer.yy.cpp.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yyconst flex_int32_t yy_rule_can_match_eol[9] [static]
Initial value:
    {   0,
0, 1, 0, 0, 0, 0, 0, 0,     }
Definition at line 1307 of file content_lexer.yy.cpp.
Referenced by while().
yyconst yy_state_type yy_NUL_trans[29] [static]
Initial value:
    {   0,
        4,    4,    0,    0,    0,    0,    0,   13,    0,    0,
        0,    0,    0,    0,    0,   13,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0
    }
Definition at line 1311 of file content_lexer.yy.cpp.
Referenced by yy_get_previous_state(), and yy_try_NUL_trans().
YY_DECL register yy_state_type yy_current_state
The main scanner function which does all the work.
Definition at line 1561 of file content_lexer.yy.cpp.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char* yy_cp
Definition at line 1562 of file content_lexer.yy.cpp.
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
register char * yy_bp
Definition at line 1562 of file content_lexer.yy.cpp.
register int yy_act
Definition at line 1563 of file content_lexer.yy.cpp.
struct yyguts_t* yyg = (struct yyguts_t*)yyscanner
Definition at line 1564 of file content_lexer.yy.cpp.
yylval = yylval_param
Definition at line 1570 of file content_lexer.yy.cpp.