DeepNet: bot::ConfigManager Class Reference
bot::ConfigManager Class Reference
class for managing configuration file and commandline parameters.
#include <ConfigManager.h>
Public Member Functions
ConfigManager ()
virtual ~ConfigManager ()
bool Init (const int argc, char **argv)
parses command line and if given also the config file.
void RegisterFlag (const std::string &flagName, const std::string &description, const bool defaultValue)
registers a new flag.
void RegisterParam (const std::string &paramName, const std::string &description, const bool isMandatory, const std::string *defaultValue)
registers a new parameter.
const std::string & GetApplicationName () const
gets filename of this binary.
void PrintUsage (void) const
prints to usage to stdout.
bool GetValue (const std::string &key, std::string &value) const
gets parameters by their name as a string.
template<class T >
bool GetValue (const std::string &key, T &value) const
gets parameters by their name and converts it to the given type T.
void DumpConfig (std::string &dump) const
dumps config to a string
Private Member Functions
bool ProcessCmdLine (const int argc, char **argv)
bool ProcessConfigFile ()
bool ValidateConfig () const
Private Attributes
CommandLine cmdLine
ConfigFile configFile
std::string configFileName
std::vector< ConfigEntry > registeredParams
std::map< std::string,
std::string > defaultValues
Detailed Description
class for managing configuration file and commandline parameters.
processes and manages configuration accuired by configfile and commandline.
Definition at line 25 of file ConfigManager.h.
Constructor & Destructor Documentation
bot::ConfigManager::ConfigManager ()
Definition at line 17 of file ConfigManager.cpp.
bot::ConfigManager::~ConfigManager () [virtual]
Definition at line 20 of file ConfigManager.cpp.
Member Function Documentation
bool bot::ConfigManager::Init (const int argc, char ** argv)
parses command line and if given also the config file.
command line args overrule config file parameters. call this function only after ALL parameters have been registered with bot::ConfigManager::RegisterFlag or bot::ConfigManager::RegisterParam
Parameters:
argc number of commandline arguments.
argv array of commandline arguments.
Returns:
false on error, true on success.
Definition at line 23 of file ConfigManager.cpp.
References DumpConfig(), log::Logging::LogError(), PrintUsage(), ProcessCmdLine(), ProcessConfigFile(), and ValidateConfig().
Referenced by fastcgiserver::FastCGIServer::StartServer().
void bot::ConfigManager::RegisterFlag (const std::string & flagName, const std::string & description, const bool defaultValue)
registers a new flag.
this function can only be called before bot::ConfigManager::Init is called.
Parameters:
flagName name of the flag.
description description of the flag.
defaultValue default value of flag
Definition at line 93 of file ConfigManager.cpp.
References defaultValues, and registeredParams.
Referenced by workerbot::WorkerBot::OnPreInit(), workerbot::WorkerBot::RegisterCrawlerConfigParams(), toolbot::DeepNetToolBot::RegisterDatabaseRepairParams(), and bot::Bot::RegisterDefaultFlags().
void bot::ConfigManager::RegisterParam (const std::string & paramName, const std::string & description, const bool isMandatory, const std::string * defaultValue)
registers a new parameter.
this function can only be called before bot::ConfigManager::Init is called.
Parameters:
paramName name of the parameter.
description description of the parameter.
isMandatory is a mandatory parameter.
defaultValue default value of parameter or NULL if no default value.
Definition at line 87 of file ConfigManager.cpp.
References defaultValues, and registeredParams.
Referenced by bot::Bot::RegisterCacheConfigParams(), toolbot::DeepNetToolBot::RegisterCommerceSearchParams(), workerbot::WorkerBot::RegisterCrawlerConfigParams(), fastcgiserver::FastCGIServer::RegisterDatabaseConfigParams(), bot::Bot::RegisterDatabaseConfigParams(), toolbot::DeepNetToolBot::RegisterDataminingParams(), bot::Bot::RegisterDefaultParams(), toolbot::DeepNetToolBot::RegisterHtmlClientCURLParams(), toolbot::DeepNetToolBot::RegisterHtmlDocumentFactoryParams(), toolbot::DeepNetToolBot::RegisterHtmlTestParams(), workerbot::WorkerBot::RegisterIndexerConfigParams(), toolbot::DeepNetToolBot::RegisterIndexerExParams(), fastcgiserver::FastCGIServer::RegisterLoggingParams(), workerbot::WorkerBot::RegisterModeSpecificParams(), workerbot::WorkerBot::RegisterParserConfigParams(), toolbot::DeepNetToolBot::RegisterPCRERegexTestParams(), bot::Bot::RegisterPerformanceLoggingParams(), toolbot::DeepNetToolBot::RegisterRobotTxtParams(), fastcgiserver::FastCGIServer::RegisterSocketConfig(), toolbot::DeepNetToolBot::RegisterUrlInserterParams(), and fastcgiserver::FastCGIServer::StartServer().
const std::string & bot::ConfigManager::GetApplicationName () const
gets filename of this binary.
Returns:
filename of this binary.
Definition at line 144 of file ConfigManager.cpp.
References cmdLine, and bot::CommandLine::GetApplicationName().
void bot::ConfigManager::PrintUsage (void) const
prints to usage to stdout.
Definition at line 39 of file ConfigManager.cpp.
References cmdLine, defaultValues, bot::CommandLine::GetApplicationName(), and registeredParams.
Referenced by Init(), and bot::Bot::PostInit().
bool bot::ConfigManager::GetValue (const std::string & key, std::string & value) const
gets parameters by their name as a string.
Parameters:
key name of the parameter.
value gets filled with value of parameter.
Returns:
false if non-existent, true on success.
Definition at line 131 of file ConfigManager.cpp.
References registeredParams.
Referenced by GetValue(), fastcgiserver::FastCGIServer::InitDatabaseConfigs(), workerbot::WorkerBot::InitIndexerConfigParams(), bot::Bot::InitLogging(), fastcgiserver::FastCGIServer::InitLoggingConfig(), fastcgiserver::FastCGIServer::InitSocketConfig(), toolbot::DeepNetToolBot::OnRun(), bot::Bot::PostInit(), ProcessCmdLine(), and toolbot::DeepNetToolBot::ProcessUnitTests().
template<class T > bool bot::ConfigManager::GetValue (const std::string & key, T & value) const [inline]
gets parameters by their name and converts it to the given type T.
Parameters:
key name of the parameter.
value gets filled with value of parameter.
Returns:
false if non-existent, true on success.
Definition at line 94 of file ConfigManager.h.
References GetValue().
void bot::ConfigManager::DumpConfig (std::string & dump) const
dumps config to a string
Parameters:
dump string to dump to
Definition at line 75 of file ConfigManager.cpp.
References registeredParams.
Referenced by Init(), and bot::Bot::PostInit().
bool bot::ConfigManager::ProcessCmdLine (const int argc, char ** argv) [private]
Definition at line 99 of file ConfigManager.cpp.
References cmdLine, configFileName, GetValue(), bot::CommandLine::ParseCommandLine(), and registeredParams.
Referenced by Init().
bool bot::ConfigManager::ProcessConfigFile () [private]
Definition at line 106 of file ConfigManager.cpp.
References configFile, configFileName, bot::ConfigFile::ParseConfigFile(), and registeredParams.
Referenced by Init().
bool bot::ConfigManager::ValidateConfig () const [private]
Definition at line 114 of file ConfigManager.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, and registeredParams.
Referenced by Init().
Member Data Documentation
CommandLine bot::ConfigManager::cmdLine [private]
Definition at line 117 of file ConfigManager.h.
Referenced by GetApplicationName(), PrintUsage(), and ProcessCmdLine().
ConfigFile bot::ConfigManager::configFile [private]
Definition at line 118 of file ConfigManager.h.
Referenced by ProcessConfigFile().
std::string bot::ConfigManager::configFileName [private]
Definition at line 119 of file ConfigManager.h.
Referenced by ProcessCmdLine(), and ProcessConfigFile().
std::vector<ConfigEntry> bot::ConfigManager::registeredParams [private]
Definition at line 120 of file ConfigManager.h.
Referenced by DumpConfig(), GetValue(), PrintUsage(), ProcessCmdLine(), ProcessConfigFile(), RegisterFlag(), RegisterParam(), and ValidateConfig().
std::map<std::string,std::string> bot::ConfigManager::defaultValues [private]
Definition at line 121 of file ConfigManager.h.
Referenced by PrintUsage(), RegisterFlag(), and RegisterParam().
The documentation for this class was generated from the following files:
Bot/src/ConfigManager.h
Bot/src/ConfigManager.cpp