DeepNet: threading::Thread Class Reference
threading::Thread Class Reference
generic thread class.
#include <Thread.h>
Classes
struct THREAD_PARAM
container for thread's parameters.
Public Member Functions
virtual ~Thread ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
Thread (ThreadFunction pFunction, bool bAutoDelete=false)
construct an instance using user defined thread function.
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
Thread (const Thread &copy)
Thread & operator= (const Thread &rhs)
Private Attributes
THREAD_PARAM threadParam
bool autoDelete
pthread_t thread
pthread_attr_t threadAttr
Detailed Description
generic thread class.
Definition at line 18 of file Thread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
threading::Thread::Thread (Thread::ThreadFunction pFunction, bool bAutoDelete = false) [protected]
construct an instance using user defined thread function.
Parameters:
pFunction user defined thread function.
bAutoDelete if true, instance deletes itself when thread ends.
Definition at line 12 of file Thread.cpp.
References threading::Thread::THREAD_PARAM::pParam, threading::Thread::THREAD_PARAM::threadFunction, and threadParam.
threading::Thread::Thread (const Thread & copy) [inline, private]
Definition at line 65 of file Thread.h.
threading::Thread::~Thread () [virtual]
Definition at line 20 of file Thread.cpp.
References SetShallEnd(), and WaitForThread().
Member Function Documentation
Thread& threading::Thread::operator= (const Thread & rhs) [inline, private]
Definition at line 66 of file Thread.h.
bool threading::Thread::StartThread (void * pParam = NULL)
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References autoDelete, threading::Thread::THREAD_PARAM::instance, IsRunning(), threading::Thread::THREAD_PARAM::pParam, SetShallEnd(), thread, threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threadParam, and WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread ()
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References thread.
Referenced by workerbot::WorkerBot::OnShutdown(), StartThread(), tools::TokenBucket::Stop(), and ~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true)
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), StartThread(), tools::TokenBucket::Stop(), and ~Thread().
bool threading::Thread::ShallEnd () const [inline]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
bool threading::Thread::IsRunning () const [inline]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References thread.
Referenced by tools::TokenBucket::RemoveTokens(), SetThreadFunction(), StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected]
Definition at line 113 of file Thread.h.
References IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threadParam.
Member Data Documentation
THREAD_PARAM threading::Thread::threadParam [private]
Definition at line 116 of file Thread.h.
Referenced by SetShallEnd(), SetThreadFunction(), ShallEnd(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), StartThread(), and Thread().
bool threading::Thread::autoDelete [private]
Definition at line 118 of file Thread.h.
Referenced by StartThread().
pthread_t threading::Thread::thread [private]
Definition at line 119 of file Thread.h.
Referenced by IsRunning(), StartThread(), and WaitForThread().
pthread_attr_t threading::Thread::threadAttr [private]
Definition at line 120 of file Thread.h.
Referenced by StartThread().
The documentation for this class was generated from the following files:
Threading/src/Thread.h
Threading/src/Thread.cpp