DeepNet: domparser::dom3::DOMString Class Reference
domparser::dom3::DOMString Class Reference
#include <DOMString.h>
Public Member Functions
DOMString ()
DOMString (const char *pszAssign)
DOMString (const char *pcAssign, const size_t &size)
DOMString (const std::string &assign)
DOMString (const DOMString &copy)
DOMString & operator= (const DOMString &assign)
bool operator== (const DOMString &rhs) const
bool operator< (const DOMString &rhs) const
virtual ~DOMString ()
void Assign (const char *pszAssign)
void Assign (const char *pcAssign, const size_t &size)
void Assign (const std::string &assign)
void Assign (const DOMString &assign)
void Release ()
bool CompareCaseSensitive (const DOMString &rhs) const
bool CompareCaseInsensitive (const DOMString &rhs) const
Private Attributes
icu::UnicodeString string
Detailed Description
Definition at line 18 of file DOMString.h.
Constructor & Destructor Documentation
domparser::dom3::DOMString::DOMString ()
Definition at line 17 of file DOMString.cpp.
domparser::dom3::DOMString::DOMString (const char * pszAssign)
Definition at line 20 of file DOMString.cpp.
References Assign().
domparser::dom3::DOMString::DOMString (const char * pcAssign, const size_t & size)
Definition at line 24 of file DOMString.cpp.
References Assign().
domparser::dom3::DOMString::DOMString (const std::string & assign)
Definition at line 28 of file DOMString.cpp.
References Assign().
domparser::dom3::DOMString::DOMString (const DOMString & copy)
Definition at line 32 of file DOMString.cpp.
References Assign().
domparser::dom3::DOMString::~DOMString () [virtual]
Definition at line 49 of file DOMString.cpp.
References Release().
Member Function Documentation
DOMString & domparser::dom3::DOMString::operator= (const DOMString & assign)
Definition at line 36 of file DOMString.cpp.
References Assign().
bool domparser::dom3::DOMString::operator== (const DOMString & rhs) const
Definition at line 41 of file DOMString.cpp.
References CompareCaseSensitive().
bool domparser::dom3::DOMString::operator< (const DOMString & rhs) const
Definition at line 45 of file DOMString.cpp.
References string.
void domparser::dom3::DOMString::Assign (const char * pszAssign)
Definition at line 53 of file DOMString.cpp.
Referenced by Assign(), DOMString(), and operator=().
void domparser::dom3::DOMString::Assign (const char * pcAssign, const size_t & size)
Definition at line 57 of file DOMString.cpp.
References Release().
void domparser::dom3::DOMString::Assign (const std::string & assign)
Definition at line 62 of file DOMString.cpp.
References Assign().
void domparser::dom3::DOMString::Assign (const DOMString & assign)
Definition at line 66 of file DOMString.cpp.
References string.
void domparser::dom3::DOMString::Release ()
Definition at line 70 of file DOMString.cpp.
Referenced by Assign(), and ~DOMString().
bool domparser::dom3::DOMString::CompareCaseSensitive (const DOMString & rhs) const
Definition at line 73 of file DOMString.cpp.
References string.
Referenced by operator==().
bool domparser::dom3::DOMString::CompareCaseInsensitive (const DOMString & rhs) const
Definition at line 77 of file DOMString.cpp.
References string.
Member Data Documentation
icu::UnicodeString domparser::dom3::DOMString::string [private]
Definition at line 45 of file DOMString.h.
Referenced by Assign(), CompareCaseInsensitive(), CompareCaseSensitive(), and operator<().
The documentation for this class was generated from the following files:
DOMParser/src/DOM3/DOMString.h
DOMParser/src/DOM3/DOMString.cpp