apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: deepnet
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      restartPolicy: Always
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: db-pv-claim
      containers:
      - image: deepnet/db:latest
        name: db
        imagePullPolicy: "Never"
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
        securityContext:
          allowPrivilegeEscalation: false
status: {}
