---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: deepnet
  name: db-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
