---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: deepnet
  name: db-pv-volume
  labels:
    type: local
    app: db
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql"