DeepNet: network::HttpCookie Class Reference
network::HttpCookie Class Reference
#include <HttpCookie.h>
Public Member Functions
HttpCookie ()
virtual ~HttpCookie ()
bool FromString (const std::string &rawCookieString)
std::string ToString () const
const std::string & GetKey () const
const std::string & GetValue () const
Private Attributes
std::pair< std::string,
std::string > keyValuePair
Detailed Description
Definition at line 15 of file HttpCookie.h.
Constructor & Destructor Documentation
network::HttpCookie::HttpCookie ()
Definition at line 14 of file HttpCookie.cpp.
network::HttpCookie::~HttpCookie () [virtual]
Definition at line 17 of file HttpCookie.cpp.
Member Function Documentation
bool network::HttpCookie::FromString (const std::string & rawCookieString)
Definition at line 20 of file HttpCookie.cpp.
References keyValuePair, log::Logging::Log(), log::Logging::LOGLEVEL_WARN, and tools::Regex::Match().
Referenced by fastcgiserver::FastCGIRequest::ParseCookies().
std::string network::HttpCookie::ToString (void) const [inline]
Definition at line 21 of file HttpCookie.h.
References keyValuePair.
const std::string& network::HttpCookie::GetKey () const [inline]
Definition at line 23 of file HttpCookie.h.
References keyValuePair.
const std::string& network::HttpCookie::GetValue () const [inline]
Definition at line 24 of file HttpCookie.h.
References keyValuePair.
Referenced by queryserver::XMLQueryResponse::LogQuery().
Member Data Documentation
std::pair<std::string,std::string> network::HttpCookie::keyValuePair [private]
Definition at line 27 of file HttpCookie.h.
Referenced by FromString(), GetKey(), GetValue(), and ToString().
The documentation for this class was generated from the following files:
Networking/src/HttpCookie.h
Networking/src/HttpCookie.cpp