DeepNet: domparser::NamedCharacterReferences Class Reference
domparser::NamedCharacterReferences Class Reference
container to deal with named html character references
#include <NamedCharacterReferences.h>
Public Member Functions
virtual ~NamedCharacterReferences ()
Static Public Member Functions
static void InitStaticNamedCharRefs ()
initialize static cache of named character references, this function should be called once per runtime and also prior to any usage of this class
static size_t IsRef (const char *p, const size_t size, bool &isPossibleRef, bool &isCompleteRef)
checks if p is a named character reference
Private Member Functions
NamedCharacterReferences ()
Detailed Description
container to deal with named html character references
Definition at line 18 of file NamedCharacterReferences.h.
Constructor & Destructor Documentation
domparser::NamedCharacterReferences::NamedCharacterReferences () [private]
Definition at line 24 of file NamedCharacterReferences.cpp.
domparser::NamedCharacterReferences::~NamedCharacterReferences () [virtual]
Definition at line 27 of file NamedCharacterReferences.cpp.
Member Function Documentation
void domparser::NamedCharacterReferences::InitStaticNamedCharRefs () [static]
initialize static cache of named character references, this function should be called once per runtime and also prior to any usage of this class
Definition at line 51 of file NamedCharacterReferences.cpp.
References threading::Mutex::Lock(), domparser::lockNamedCharRefs, threading::Mutex::Unlock(), and domparser::vecNamedCharRefs.
Referenced by IsRef().
size_t domparser::NamedCharacterReferences::IsRef (const char * p, const size_t size, bool & isPossibleRef, bool & isCompleteRef) [static]
checks if p is a named character reference
Parameters:
p string to check
size number of characters to check in p
isPossibleRef true if input MAY BE a character reference, but if so it is not complete
isCompleteRef true if input is a complete reference
Definition at line 30 of file NamedCharacterReferences.cpp.
References InitStaticNamedCharRefs(), and domparser::vecNamedCharRefs.
Referenced by domparser::html5::Tokeniser::ConsumeNamedCharacterReference().
The documentation for this class was generated from the following files:
DOMParser/src/NamedCharacterReferences.h
DOMParser/src/NamedCharacterReferences.cpp