DeepNet: parser::CommerceSearchParserThread Class Reference
parser::CommerceSearchParserThread Class Reference
#include <CommerceSearchParserThread.h>
Public Member Functions
CommerceSearchParserThread ()
virtual ~CommerceSearchParserThread ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
database::DatabaseHelper & DB ()
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
virtual void InitParserThread ()
virtual void OnAfterParsePage (const HtmlParserEntry &entry, tools::Pointer< htmlparser::IHtmlParserResult > &result, const std::vector< std::string > &content, const std::vector< htmlparser::DatabaseUrl > &hyperlinks, const std::vector< network::HttpUrl > &images)
void MatchUrlCriteria (const HtmlParserEntry &entry, const std::vector< htmlparser::DatabaseUrl > &hyperLinks, const std::vector< CommerceSearchMatchCriteria * > &criteriaVector)
void MatchMetaCriteria (const HtmlParserEntry &entry, tools::Pointer< htmlparser::IHtmlParserResult > &result, const std::vector< CommerceSearchMatchCriteria * > &criteriaVector)
void MatchImageCriteria (const HtmlParserEntry &entry, const std::vector< network::HttpUrl > &imagesLinks, const std::vector< CommerceSearchMatchCriteria * > &criteriaVector)
Private Attributes
std::vector
< CommerceSearchProduct > products
database::SelectResultContainer
< CommerceSearchMatchCriteria > criterias
std::vector< size_t > urlTypePos
std::vector< size_t > contentTypePos
std::vector< size_t > metaTypePos
std::vector< size_t > titleTypePos
Detailed Description
Definition at line 29 of file CommerceSearchParserThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
parser::CommerceSearchParserThread::CommerceSearchParserThread ()
Definition at line 19 of file CommerceSearchParserThread.cpp.
parser::CommerceSearchParserThread::~CommerceSearchParserThread () [virtual]
Definition at line 23 of file CommerceSearchParserThread.cpp.
Member Function Documentation
void parser::CommerceSearchParserThread::InitParserThread () [private, virtual]
Reimplemented from parser::HtmlParserThread.
Definition at line 26 of file CommerceSearchParserThread.cpp.
References parser::CONTENT_CRITERIA_TYPE, contentTypePos, criterias, parser::HtmlParserThread::DB(), parser::CommerceSearchMatchCriteria::GetAll(), tools::PointerContainer< T >::GetIter(), tools::PointerContainer< T >::IsIterEnd(), parser::META_CRITERIA_TYPE, metaTypePos, tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), THROW_EXCEPTION, parser::TITLE_CRITERIA_TYPE, titleTypePos, parser::URL_CRITERIA_TYPE, and urlTypePos.
void parser::CommerceSearchParserThread::OnAfterParsePage (const HtmlParserEntry & entry, tools::Pointer< htmlparser::IHtmlParserResult > & result, const std::vector< std::string > & content, const std::vector< htmlparser::DatabaseUrl > & hyperlinks, const std::vector< network::HttpUrl > & images) [private, virtual]
Reimplemented from parser::GenericWebHtmlParserThread.
Definition at line 52 of file CommerceSearchParserThread.cpp.
References criterias, tools::PointerContainer< T >::GetVector(), MatchImageCriteria(), MatchMetaCriteria(), and MatchUrlCriteria().
void parser::CommerceSearchParserThread::MatchUrlCriteria (const HtmlParserEntry & entry, const std::vector< htmlparser::DatabaseUrl > & hyperLinks, const std::vector< CommerceSearchMatchCriteria * > & criteriaVector) [private]
Definition at line 96 of file CommerceSearchParserThread.cpp.
References parser::HtmlParserThread::DB(), network::HttpUrl::GetFullUrl(), parser::CommerceSearchMatchCriteria::Match(), parser::HtmlParserEntry::url, and urlTypePos.
Referenced by OnAfterParsePage().
void parser::CommerceSearchParserThread::MatchMetaCriteria (const HtmlParserEntry & entry, tools::Pointer< htmlparser::IHtmlParserResult > & result, const std::vector< CommerceSearchMatchCriteria * > & criteriaVector) [private]
Definition at line 112 of file CommerceSearchParserThread.cpp.
References parser::HtmlParserThread::DB(), parser::CommerceSearchMatchCriteria::Match(), and metaTypePos.
Referenced by OnAfterParsePage().
void parser::CommerceSearchParserThread::MatchImageCriteria (const HtmlParserEntry & entry, const std::vector< network::HttpUrl > & imagesLinks, const std::vector< CommerceSearchMatchCriteria * > & criteriaVector) [private]
Definition at line 140 of file CommerceSearchParserThread.cpp.
Referenced by OnAfterParsePage().
database::DatabaseHelper& parser::HtmlParserThread::DB () [inline, protected, inherited]
Definition at line 35 of file HtmlParserThread.h.
References parser::HtmlParserThread::databaseHelper.
Referenced by parser::HtmlParserThread::HtmlParserThreadFunction(), InitParserThread(), MatchMetaCriteria(), MatchUrlCriteria(), and parser::GenericWebHtmlParserThread::ParsePage().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
std::vector<CommerceSearchProduct> parser::CommerceSearchParserThread::products [private]
Definition at line 44 of file CommerceSearchParserThread.h.
database::SelectResultContainer<CommerceSearchMatchCriteria> parser::CommerceSearchParserThread::criterias [private]
Definition at line 45 of file CommerceSearchParserThread.h.
Referenced by InitParserThread(), and OnAfterParsePage().
std::vector<size_t> parser::CommerceSearchParserThread::urlTypePos [private]
Definition at line 47 of file CommerceSearchParserThread.h.
Referenced by InitParserThread(), and MatchUrlCriteria().
std::vector<size_t> parser::CommerceSearchParserThread::contentTypePos [private]
Definition at line 48 of file CommerceSearchParserThread.h.
Referenced by InitParserThread().
std::vector<size_t> parser::CommerceSearchParserThread::metaTypePos [private]
Definition at line 49 of file CommerceSearchParserThread.h.
Referenced by InitParserThread(), and MatchMetaCriteria().
std::vector<size_t> parser::CommerceSearchParserThread::titleTypePos [private]
Definition at line 50 of file CommerceSearchParserThread.h.
Referenced by InitParserThread().
The documentation for this class was generated from the following files:
Parser/src/CommerceSearchParserThread.h
Parser/src/CommerceSearchParserThread.cpp