DeepNet: toolbot::UnitTestUrlParser Class Reference
toolbot::UnitTestUrlParser Class Reference
#include <UnitTestUrlParser.h>
Public Member Functions
UnitTestUrlParser (database::DatabaseConnection *connection, const std::string &validUrlFileName, const std::string &invalidUrlFileName)
virtual ~UnitTestUrlParser ()
virtual bool Run ()
virtual std::string GetName () const
Private Member Functions
bool TestValidUrls (const std::string &urlFileName)
Static Private Member Functions
static bool TestInvalidUrls (database::DatabaseConnection *connection, const std::string &urlFileName)
static void OnError (const std::string &message, const UnitTestUrl &errorUrl)
Private Attributes
database::DatabaseConnection * connection
const std::string validUrlFileName
const std::string invalidUrlFileName
std::vector< UnitTestUrl > testUrls
Detailed Description
Definition at line 22 of file UnitTestUrlParser.h.
Constructor & Destructor Documentation
toolbot::UnitTestUrlParser::UnitTestUrlParser (database::DatabaseConnection * connection, const std::string & validUrlFileName, const std::string & invalidUrlFileName)
Definition at line 25 of file UnitTestUrlParser.cpp.
toolbot::UnitTestUrlParser::~UnitTestUrlParser () [virtual]
Definition at line 35 of file UnitTestUrlParser.cpp.
Member Function Documentation
bool toolbot::UnitTestUrlParser::Run () [virtual]
Implements toolbot::UnitTest.
Definition at line 38 of file UnitTestUrlParser.cpp.
References connection, invalidUrlFileName, TestInvalidUrls(), TestValidUrls(), and validUrlFileName.
virtual std::string toolbot::UnitTestUrlParser::GetName () const [inline, virtual]
Implements toolbot::UnitTest.
Definition at line 31 of file UnitTestUrlParser.h.
bool toolbot::UnitTestUrlParser::TestInvalidUrls (database::DatabaseConnection * connection, const std::string & urlFileName) [static, private]
Definition at line 149 of file UnitTestUrlParser.cpp.
References toolbot::UnitTestUrl::baseUrl, network::HttpUrl::CalculateFullUrl(), errors::Exception::DisableLogging(), network::HttpUrl::Dump(), errors::Exception::Dump(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, OnError(), network::HttpUrlParser::ParseURL(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, toolbot::UnitTestUrl::ReadInvalidURLFile(), testUrls, and toolbot::UnitTestUrl::theUrl.
Referenced by Run().
bool toolbot::UnitTestUrlParser::TestValidUrls (const std::string & urlFileName) [private]
Definition at line 51 of file UnitTestUrlParser.cpp.
References toolbot::UnitTestUrl::base, toolbot::UnitTestUrl::baseUrl, network::HttpUrl::CalculateFullUrl(), connection, network::HttpUrl::DeepMatchUrl(), network::HttpUrl::Dump(), errors::Exception::Dump(), network::HttpUrl::GetFullUrl(), log::Logging::IsLogLevelTrace(), toolbot::UnitTestUrl::line, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, log::Logging::LOGLEVEL_TRACE, OnError(), network::HttpUrlParser::ParseURL(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, toolbot::UnitTestUrl::ReadValidURLFile(), toolbot::UnitTestUrl::result, toolbot::UnitTestUrl::resultUrl, toolbot::UnitTestUrl::reverse, testUrls, toolbot::UnitTestUrl::theUrl, and toolbot::UnitTestUrl::url.
Referenced by Run().
void toolbot::UnitTestUrlParser::OnError (const std::string & message, const UnitTestUrl & errorUrl) [static, private]
Definition at line 211 of file UnitTestUrlParser.cpp.
References toolbot::UnitTestUrl::baseUrl, toolbot::UnitTestUrl::line, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, toolbot::UnitTestUrl::resultUrl, and toolbot::UnitTestUrl::theUrl.
Referenced by TestInvalidUrls(), and TestValidUrls().
Member Data Documentation
database::DatabaseConnection* toolbot::UnitTestUrlParser::connection [private]
Definition at line 40 of file UnitTestUrlParser.h.
Referenced by Run(), and TestValidUrls().
const std::string toolbot::UnitTestUrlParser::validUrlFileName [private]
Definition at line 41 of file UnitTestUrlParser.h.
Referenced by Run().
const std::string toolbot::UnitTestUrlParser::invalidUrlFileName [private]
Definition at line 42 of file UnitTestUrlParser.h.
Referenced by Run().
std::vector<UnitTestUrl> toolbot::UnitTestUrlParser::testUrls [private]
Definition at line 43 of file UnitTestUrlParser.h.
Referenced by TestInvalidUrls(), and TestValidUrls().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestUrlParser.h
DeepNetTool/src/UnitTestUrlParser.cpp