DeepNet: indexing::MetaIndexer Class Reference
indexing::MetaIndexer Class Reference
#include <MetaIndexer.h>
Public Types
enum WordLen { SHORT, MEDIUM, LONG }
enum IndexerType { META_CONTENT, BODY_CONTENT, URL_CONTENT }
Public Member Functions
virtual ~MetaIndexer ()
void OnFactFinder ()
void OnGoogleAnalytics ()
virtual void Parse (const std::string &input, const long long paragraph)
parses a text
virtual void ParseMeta (const std::string &input, const Dictionary::MetaInformationType &type)
parses content part of a meta type
int Read (char *buf, int maxSize)
virtual Dictionary & GetDictionary ()=0
gets dictionary of this indexer
Static Public Member Functions
static MetaIndexer * CreateIndexer (database::DatabaseConnection *database, const IndexerBase::IndexerType type)
Public Attributes
IndexerCtx * ctx
std::string content
std::string::iterator contentIter
Private Member Functions
MetaIndexer (database::DatabaseConnection *database, const IndexerBase::IndexerType type)
virtual void OnParse (const long long paragraph)
Detailed Description
Definition at line 36 of file MetaIndexer.h.
Member Enumeration Documentation
enum indexing::IndexerBase::WordLen [inherited]
Enumerator:
SHORT
MEDIUM
LONG
Definition at line 56 of file IndexerBase.h.
enum indexing::IndexerBase::IndexerType [inherited]
Enumerator:
META_CONTENT
BODY_CONTENT
URL_CONTENT
Definition at line 62 of file IndexerBase.h.
Constructor & Destructor Documentation
indexing::MetaIndexer::MetaIndexer (database::DatabaseConnection * database, const IndexerBase::IndexerType type) [private]
Definition at line 15 of file MetaIndexer.cpp.
References indexing::IndexerBase::ctx.
indexing::MetaIndexer::~MetaIndexer () [virtual]
Definition at line 21 of file MetaIndexer.cpp.
References indexing::IndexerBase::ctx.
Member Function Documentation
MetaIndexer * indexing::MetaIndexer::CreateIndexer (database::DatabaseConnection * database, const IndexerBase::IndexerType type) [static]
Definition at line 27 of file MetaIndexer.cpp.
void indexing::MetaIndexer::OnFactFinder () [inline]
Definition at line 46 of file MetaIndexer.h.
void indexing::MetaIndexer::OnGoogleAnalytics () [inline]
Definition at line 47 of file MetaIndexer.h.
void indexing::MetaIndexer::OnParse (const long long paragraph) [private, virtual]
Implements indexing::IndexerBase.
Definition at line 33 of file MetaIndexer.cpp.
References indexing::IndexerBase::ctx, and indexing::MetaIndexerHelper::ParseFromContext().
void indexing::IndexerBase::Parse (const std::string & input, const long long paragraph) [virtual, inherited]
parses a text
Parameters:
input text to parse
paragraph paragraph of this text
Implements indexing::IIndexer.
Definition at line 31 of file IndexerBase.cpp.
References indexing::IndexerBase::content, indexing::IndexerBase::contentIter, input(), and indexing::IndexerBase::OnParse().
void indexing::IndexerBase::ParseMeta (const std::string & input, const Dictionary::MetaInformationType & type) [virtual, inherited]
parses content part of a meta type
Parameters:
input content part to parse
type meta type to set
Implements indexing::IIndexer.
Definition at line 39 of file IndexerBase.cpp.
References indexing::IndexerBase::OnParseMeta().
int indexing::IndexerBase::Read (char * buf, int maxSize) [inherited]
Definition at line 43 of file IndexerBase.cpp.
References indexing::IndexerBase::content, and indexing::IndexerBase::contentIter.
virtual Dictionary& indexing::IIndexer::GetDictionary () [pure virtual, inherited]
gets dictionary of this indexer
Returns:
instance of this indexers dictionary
Implemented in indexing::IndexerEx, indexing::GenericWebContentIndexer, and indexing::DataminingContentIndexer.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), and indexing::ContentIndexer::TerminateWord().
Member Data Documentation
IndexerCtx* indexing::IndexerBase::ctx [inherited]
Definition at line 89 of file IndexerBase.h.
Referenced by indexing::ContentIndexer::ContentIndexer(), MetaIndexer(), OnParse(), indexing::ContentIndexer::OnParse(), indexing::ContentIndexer::~ContentIndexer(), indexing::IndexerBase::~IndexerBase(), and ~MetaIndexer().
std::string indexing::IndexerBase::content [inherited]
Definition at line 91 of file IndexerBase.h.
Referenced by indexing::IndexerBase::Parse(), and indexing::IndexerBase::Read().
std::string::iterator indexing::IndexerBase::contentIter [inherited]
Definition at line 92 of file IndexerBase.h.
Referenced by indexing::IndexerBase::Parse(), and indexing::IndexerBase::Read().
The documentation for this class was generated from the following files:
Indexer/src/MetaIndexer.h
Indexer/src/MetaIndexer.cpp