DeepNet: database::DB2Connection Class Reference
database::DB2Connection Class Reference
#include <DB2Connection.h>
Public Member Functions
DB2Connection (const bool logQuery=false)
virtual ~DB2Connection ()
virtual bool Connect (DatabaseConfig *dbConfig)
connects to a database.
virtual bool Disconnect (void)
disconnect from database.
virtual bool Connected (void)
checks if database connection is established.
virtual void Insert (const InsertStatement &stmt)
execute an insert statement.
virtual void InsertOrUpdate (const InsertOrUpdateStatement &stmt)
execute an insert or update statement.
virtual void Update (const UpdateStatement &stmt)
execute an update statement.
virtual void Select (const SelectStatement &stmt, std::vector< TableBase * > &results)
execute select statement.
virtual void Delete (const DeleteStatement &stmt)
execute delete statement.
virtual void TransactionStart (void)
start a transaction.
virtual void TransactionCommit (void)
commits a transaction.
virtual void TransactionRollback (void)
does a transaction rollback.
virtual bool LastInsertID (long long &lastInsertID)
gets last inserted id.
virtual bool AffectedRows (long long &affectedRows)
gets the number of affected rows from last statement.
virtual bool EscapeString (std::string &inEscape)
escapes a sql string in place.
void Select (const SelectStatement &stmt, SelectResultContainer< TableBase > &results)
execute select statements putting results into container.
template<class T >
void Select (const SelectStatement &stmt, SelectResultContainer< T > &results)
execute select statements putting results into container of type T.
virtual void Initialize ()
called for global initialization, once per runtime.
virtual void Shutdown ()
called for global shutdown
const DatabaseType & GetDatabaseType (void) const
gets the database type of this connection.
Protected Member Functions
virtual void Query (const std::string &query, std::vector< TableBase * > &results)
execute an sql query.
virtual void Execute (const std::string &query)
executing an sql statement without fetching results.
Protected Attributes
bool logQuery
Private Attributes
DB2DatabaseConfig * config
Detailed Description
Definition at line 24 of file DB2Connection.h.
Constructor & Destructor Documentation
database::DB2Connection::DB2Connection (const bool logQuery = false)
Definition at line 14 of file DB2Connection.cpp.
database::DB2Connection::~DB2Connection () [virtual]
Definition at line 20 of file DB2Connection.cpp.
Member Function Documentation
bool database::DB2Connection::Connect (DatabaseConfig * config) [virtual]
connects to a database.
Parameters:
config database config.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 24 of file DB2Connection.cpp.
References THROW_EXCEPTION.
bool database::DB2Connection::Disconnect (void) [virtual]
disconnect from database.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 30 of file DB2Connection.cpp.
References THROW_EXCEPTION.
bool database::DB2Connection::Connected (void) [virtual]
checks if database connection is established.
Returns:
false if not established, true if established.
Implements database::DatabaseConnection.
Definition at line 35 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::Query (const std::string & query, std::vector< TableBase * > & results) [protected, virtual]
execute an sql query.
Parameters:
query sql statement.
results gets filled with results.
Implements database::DatabaseConnection.
Definition at line 40 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::Execute (const std::string & query) [protected, virtual]
executing an sql statement without fetching results.
Parameters:
query sql statement.
Implements database::DatabaseConnection.
Definition at line 45 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::Insert (const InsertStatement & stmt) [virtual]
execute an insert statement.
Parameters:
stmt insert statement.
Implements database::DatabaseConnection.
Definition at line 50 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::InsertOrUpdate (const InsertOrUpdateStatement & stmt) [virtual]
execute an insert or update statement.
Parameters:
stmt insert or update statement.
Implements database::DatabaseConnection.
Definition at line 55 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::Update (const UpdateStatement & stmt) [virtual]
execute an update statement.
Parameters:
stmt update statement.
Implements database::DatabaseConnection.
Definition at line 60 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::Select (const SelectStatement & stmt, std::vector< TableBase * > & results) [virtual]
execute select statement.
Parameters:
stmt select statement.
results gets filled with results.
Implements database::DatabaseConnection.
Definition at line 65 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::Delete (const DeleteStatement & stmt) [virtual]
execute delete statement.
Parameters:
stmt delete statement
Implements database::DatabaseConnection.
Definition at line 70 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::TransactionStart (void) [virtual]
start a transaction.
Implements database::DatabaseConnection.
Definition at line 75 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::TransactionCommit (void) [virtual]
commits a transaction.
Implements database::DatabaseConnection.
Definition at line 80 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DB2Connection::TransactionRollback (void) [virtual]
does a transaction rollback.
Implements database::DatabaseConnection.
Definition at line 85 of file DB2Connection.cpp.
References THROW_EXCEPTION.
bool database::DB2Connection::LastInsertID (long long & lastInsertID) [virtual]
gets last inserted id.
Parameters:
lastInsertID gets filled with last inserted id.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 90 of file DB2Connection.cpp.
References THROW_EXCEPTION.
bool database::DB2Connection::AffectedRows (long long & affectedRows) [virtual]
gets the number of affected rows from last statement.
Parameters:
affectedRows number of affected rows.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 95 of file DB2Connection.cpp.
References THROW_EXCEPTION.
bool database::DB2Connection::EscapeString (std::string & inEscape) [virtual]
escapes a sql string in place.
Parameters:
inEscape string to be escaped.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 100 of file DB2Connection.cpp.
References THROW_EXCEPTION.
void database::DatabaseConnection::Select (const SelectStatement & stmt, SelectResultContainer< TableBase > & results) [inline, inherited]
execute select statements putting results into container.
Parameters:
stmt select statement.
results result container.
Definition at line 173 of file DatabaseConnection.h.
References tools::PointerContainer< T >::Add(), and database::DatabaseConnection::Select().
template<class T > void database::DatabaseConnection::Select (const SelectStatement & stmt, SelectResultContainer< T > & results) [inline, inherited]
execute select statements putting results into container of type T.
type T should be derived from database::TableBase.
Parameters:
stmt select statement.
results result container.
Definition at line 190 of file DatabaseConnection.h.
References tools::PointerContainer< T >::Add(), and database::DatabaseConnection::Select().
virtual void database::DatabaseConnection::Initialize () [inline, virtual, inherited]
called for global initialization, once per runtime.
Reimplemented in database::MySQLConnection.
Definition at line 153 of file DatabaseConnection.h.
Referenced by database::DatabaseHelper::CreateConnection().
virtual void database::DatabaseConnection::Shutdown () [inline, virtual, inherited]
called for global shutdown
Reimplemented in database::MySQLConnection.
Definition at line 158 of file DatabaseConnection.h.
Referenced by database::DatabaseHelper::DestroyConnection().
const DatabaseType& database::DatabaseConnection::GetDatabaseType (void) const [inline, inherited]
gets the database type of this connection.
Returns:
database type.
Definition at line 165 of file DatabaseConnection.h.
References database::DatabaseConnection::databaseType.
Member Data Documentation
DB2DatabaseConfig* database::DB2Connection::config [private]
Definition at line 55 of file DB2Connection.h.
bool database::DatabaseConnection::logQuery [protected, inherited]
Definition at line 208 of file DatabaseConnection.h.
Referenced by database::MySQLConnection::Execute().
The documentation for this class was generated from the following files:
Database/DB2/DB2Connection.h
Database/DB2/DB2Connection.cpp