DeepNet: database::WhereConditionTableColumnContainer Class Reference
database::WhereConditionTableColumnContainer Class Reference
container for multiple pointers to database::WhereConditionTableColumn
#include <WhereConditionTableColumnContainer.h>
Public Member Functions
WhereConditionTableColumnContainer ()
virtual ~WhereConditionTableColumnContainer ()
void Add (WhereConditionTableColumn *entry)
adds an entry.
void Add (const std::vector< WhereConditionTableColumn * > &entries)
adds multiple entries entry.
void ResetIter () const
resets iterator.
bool IsIterEnd () const
checks if iterator is at end.
WhereConditionTableColumn * GetIter ()
gets current iterator.
const
WhereConditionTableColumn
*const GetConstIter () const
gets current iterator as const.
void Next () const
increment iterator.
std::vector
< WhereConditionTableColumn * > & GetVector ()
gets vector of entries.
size_t Size () const
gets current container size.
Private Member Functions
WhereConditionTableColumnContainer (const WhereConditionTableColumnContainer &copy)
Detailed Description
container for multiple pointers to database::WhereConditionTableColumn
Definition at line 21 of file WhereConditionTableColumnContainer.h.
Constructor & Destructor Documentation
database::WhereConditionTableColumnContainer::WhereConditionTableColumnContainer () [inline]
Definition at line 23 of file WhereConditionTableColumnContainer.h.
virtual database::WhereConditionTableColumnContainer::~WhereConditionTableColumnContainer () [inline, virtual]
Definition at line 24 of file WhereConditionTableColumnContainer.h.
database::WhereConditionTableColumnContainer::WhereConditionTableColumnContainer (const WhereConditionTableColumnContainer & copy) [private]
Definition at line 14 of file WhereConditionTableColumnContainer.cpp.
References THROW_EXCEPTION.
Member Function Documentation
void tools::PointerContainer< WhereConditionTableColumn >::Add (WhereConditionTableColumn * entry) [inline, inherited]
adds an entry.
Parameters:
entry entry to add.
Definition at line 39 of file PointerContainer.h.
References tools::PointerContainer< T >::container, and tools::PointerContainer< T >::ResetIter().
void tools::PointerContainer< WhereConditionTableColumn >::Add (const std::vector< WhereConditionTableColumn * > & entries) [inline, inherited]
adds multiple entries entry.
Parameters:
entries entries to add.
Definition at line 47 of file PointerContainer.h.
References tools::PointerContainer< T >::container, and tools::PointerContainer< T >::ResetIter().
void tools::PointerContainer< WhereConditionTableColumn >::ResetIter () const [inline, inherited]
resets iterator.
Definition at line 54 of file PointerContainer.h.
References tools::PointerContainer< T >::container, and tools::PointerContainer< T >::iterContainer.
bool tools::PointerContainer< WhereConditionTableColumn >::IsIterEnd () const [inline, inherited]
checks if iterator is at end.
Returns:
false if not at end, true if at end.
Definition at line 61 of file PointerContainer.h.
References tools::PointerContainer< T >::container, and tools::PointerContainer< T >::iterContainer.
WhereConditionTableColumn * tools::PointerContainer< WhereConditionTableColumn >::GetIter () [inline, inherited]
gets current iterator.
Returns:
current iterator
Definition at line 68 of file PointerContainer.h.
References tools::PointerContainer< T >::iterContainer.
const WhereConditionTableColumn * const tools::PointerContainer< WhereConditionTableColumn >::GetConstIter () const [inline, inherited]
gets current iterator as const.
Returns:
current iterator
Definition at line 75 of file PointerContainer.h.
References tools::PointerContainer< T >::iterContainer.
void tools::PointerContainer< WhereConditionTableColumn >::Next () const [inline, inherited]
increment iterator.
Definition at line 81 of file PointerContainer.h.
References tools::PointerContainer< T >::IsIterEnd(), and tools::PointerContainer< T >::iterContainer.
std::vector<WhereConditionTableColumn *>& tools::PointerContainer< WhereConditionTableColumn >::GetVector () [inline, inherited]
gets vector of entries.
Returns:
raw vector of entries.
Definition at line 90 of file PointerContainer.h.
References tools::PointerContainer< T >::container.
size_t tools::PointerContainer< WhereConditionTableColumn >::Size () const [inline, inherited]
gets current container size.
Returns:
current container size.
Definition at line 97 of file PointerContainer.h.
References tools::PointerContainer< T >::container.
The documentation for this class was generated from the following files:
Database/src/WhereConditionTableColumnContainer.h
Database/src/WhereConditionTableColumnContainer.cpp