DeepNet: tools::TimeTools Class Reference
tools::TimeTools Class Reference
class implementing date and time specific functions and formats.
#include <TimeTools.h>
Public Member Functions
virtual ~TimeTools ()
Static Public Member Functions
static struct timeval MilliSecondsToTimeval (const size_t &milliseconds)
converts milliseconds to timeval.
static void MilliSecondsToTimeval (const size_t &milliseconds, struct timeval &out)
converts milliseconds to timeval.
static size_t TimevalToMilliSeconds (const struct timeval &in)
converts timeval to milliseconds.
static bool TimevalSubtract (struct timeval time1, struct timeval time2, struct timeval &result)
subtracts two timevals.
static bool TimevalAddition (struct timeval time1, struct timeval time2, struct timeval &result)
adds two timevals.
static std::string TimevalToString (struct timeval timeVal)
converts timeval to string (containing seconds).
static void NormalizeTimeval (struct timeval &time)
normalize timeval in place.
static bool TryParseDate (const std::string &timeString, struct tm &tmOut)
try to parse date according to ISO112,ISO1036 and ASCII time format.
static bool ParseDate_ISO_1123 (const std::string &timeString, struct tm &tmOut)
parse string according to ISO1123 standard.
static bool ParseDate_ISO_1036 (const std::string &timeString, struct tm &tmOut)
parse string according to ISO1036 standard.
static bool ParseDate_AscTime (const std::string &timeString, struct tm &tmOut)
parse string according to ASCII time format.
static void InitTm (struct tm &init)
zero initialize struct tm.
static void InitTimeval (struct timeval &init)
zero initialize timeval.
static struct timeval InitTimeval ()
zero initialize timeval.
static bool IsZero (const struct timeval &test)
checks if timeval is zero initialized.
static bool IsZero (struct tm test)
checks if struct tm is zero initialized.
static struct tm NowUTC (void)
gets current time in UTC as struct tm.
static void NowUTC (struct tm &tmNow)
gets current time in UTC as struct tm.
static void NowUTCAdd (struct tm &tmFuture, const int nDays)
gets future time in UTC as struct tm adding nDays.
static struct tm NowUTCAdd (const int nDays)
gets future time in UTC as struct tm adding nDays.
Private Member Functions
TimeTools ()
Detailed Description
class implementing date and time specific functions and formats.
Definition at line 17 of file TimeTools.h.
Constructor & Destructor Documentation
tools::TimeTools::TimeTools () [private]
Definition at line 16 of file TimeTools.cpp.
tools::TimeTools::~TimeTools () [virtual]
Definition at line 19 of file TimeTools.cpp.
Member Function Documentation
struct timeval tools::TimeTools::MilliSecondsToTimeval (const size_t & milliseconds) [static, read]
converts milliseconds to timeval.
Parameters:
milliseconds milliseconds.
Returns:
timeval.
Definition at line 22 of file TimeTools.cpp.
void tools::TimeTools::MilliSecondsToTimeval (const size_t & milliseconds, struct timeval & out) [static]
converts milliseconds to timeval.
Parameters:
milliseconds milliseconds.
out timeval.
Definition at line 29 of file TimeTools.cpp.
size_t tools::TimeTools::TimevalToMilliSeconds (const struct timeval & in) [static]
converts timeval to milliseconds.
Parameters:
in timeval
Returns:
milliseconds.
Definition at line 45 of file TimeTools.cpp.
bool tools::TimeTools::TimevalSubtract (struct timeval time1, struct timeval time2, struct timeval & result) [static]
subtracts two timevals.
Parameters:
time1 minuend.
time2 subtrahend.
result result.
Returns:
false on error, true on success.
Definition at line 52 of file TimeTools.cpp.
References NormalizeTimeval().
Referenced by tools::PerformanceCounter::Stop().
bool tools::TimeTools::TimevalAddition (struct timeval time1, struct timeval time2, struct timeval & result) [static]
adds two timevals.
Parameters:
time1 timeval.
time2 timeval.
result result.
Returns:
false on error, true on success.
Definition at line 63 of file TimeTools.cpp.
References NormalizeTimeval().
std::string tools::TimeTools::TimevalToString (struct timeval timeVal) [static]
converts timeval to string (containing seconds).
Parameters:
timeVal timeval.
Returns:
string.
Definition at line 75 of file TimeTools.cpp.
References NormalizeTimeval().
void tools::TimeTools::NormalizeTimeval (struct timeval & time) [static]
normalize timeval in place.
Parameters:
time timeval to normalize.
Definition at line 84 of file TimeTools.cpp.
Referenced by TimevalAddition(), TimevalSubtract(), and TimevalToString().
bool tools::TimeTools::TryParseDate (const std::string & timeString, struct tm & tmOut) [static]
try to parse date according to ISO112,ISO1036 and ASCII time format.
Parameters:
timeString string to parse.
tmOut result.
Returns:
false on error, true on success.
Definition at line 92 of file TimeTools.cpp.
References ParseDate_AscTime(), ParseDate_ISO_1036(), and ParseDate_ISO_1123().
bool tools::TimeTools::ParseDate_ISO_1123 (const std::string & timeString, struct tm & tmOut) [static]
parse string according to ISO1123 standard.
Parameters:
timeString string to parse.
tmOut result.
Returns:
false on error, true on success.
Definition at line 106 of file TimeTools.cpp.
Referenced by TryParseDate().
bool tools::TimeTools::ParseDate_ISO_1036 (const std::string & timeString, struct tm & tmOut) [static]
parse string according to ISO1036 standard.
Parameters:
timeString string to parse.
tmOut result.
Returns:
false on error, true on success.
Definition at line 115 of file TimeTools.cpp.
Referenced by TryParseDate().
bool tools::TimeTools::ParseDate_AscTime (const std::string & timeString, struct tm & tmOut) [static]
parse string according to ASCII time format.
Parameters:
timeString string to parse.
tmOut result.
Returns:
false on error, true on success.
Definition at line 124 of file TimeTools.cpp.
Referenced by TryParseDate().
void tools::TimeTools::InitTm (struct tm & init) [static]
zero initialize struct tm.
Parameters:
init tm to initialize.
Definition at line 135 of file TimeTools.cpp.
References tools::zeroTm.
Referenced by domparser::Event::Event(), and crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void tools::TimeTools::InitTimeval (struct timeval & init) [static]
zero initialize timeval.
Parameters:
init timeval to initialize.
Definition at line 139 of file TimeTools.cpp.
struct timeval tools::TimeTools::InitTimeval () [static, read]
zero initialize timeval.
Returns:
timeval to initialize.
Definition at line 143 of file TimeTools.cpp.
bool tools::TimeTools::IsZero (const struct timeval & test) [static]
checks if timeval is zero initialized.
Parameters:
test timeval to check.
Returns:
false if not zero initialized, true if it is.
Definition at line 149 of file TimeTools.cpp.
bool tools::TimeTools::IsZero (struct tm test) [static]
checks if struct tm is zero initialized.
Parameters:
test struct tm to check.
Returns:
false if not zero initialized, true if it is.
Definition at line 153 of file TimeTools.cpp.
struct tm tools::TimeTools::NowUTC (void) [static, read]
gets current time in UTC as struct tm.
Returns:
current UTC time.
Definition at line 158 of file TimeTools.cpp.
Referenced by toolbot::CommerceSearchTools::AddCustomer(), bot::DatabaseRepair::FixSecondLevelLockTable(), bot::DatabaseRepair::FixSyncUrlTable(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), parser::GenericWebHtmlParserThread::InsertImages(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), log::DatabaseLogging::OnLog(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), htmlparser::DatabaseUrl::Store(), and bot::Bot::WatchDog().
void tools::TimeTools::NowUTC (struct tm & tmNow) [static]
gets current time in UTC as struct tm.
Parameters:
tmNow current UTC time.
Definition at line 165 of file TimeTools.cpp.
void tools::TimeTools::NowUTCAdd (struct tm & tmFuture, const int nDays) [static]
gets future time in UTC as struct tm adding nDays.
Parameters:
tmFuture future UTC time.
nDays days to add to current time.
Definition at line 171 of file TimeTools.cpp.
Referenced by crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), NowUTCAdd(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and crawler::CommerceSearchFetcherThread::ReserveNextUrls().
struct tm tools::TimeTools::NowUTCAdd (const int nDays) [static, read]
gets future time in UTC as struct tm adding nDays.
Parameters:
nDays days to add to current time.
Returns:
future UTC time.
Definition at line 178 of file TimeTools.cpp.
References NowUTCAdd().
The documentation for this class was generated from the following files:
Tools/src/TimeTools.h
Tools/src/TimeTools.cpp