USE `documents`;

DELIMITER |

CREATE TRIGGER `after_insert_urls` AFTER INSERT ON `documents`.`urls`
  FOR EACH ROW
  BEGIN
    INSERT INTO `sync`.`syncurls` (`URL_ID`, `SECONDLEVELDOMAIN_ID`, `CRAWLERSESSION_ID`, `schedule`) 
		VALUES ( NEW.`ID`, NEW.`SECONDLEVELDOMAIN_ID`, 0, UTC_TIMESTAMP() );

    INSERT INTO `sync`.`locksecondleveldomain` (`SECONDLEVELDOMAIN_ID`, `CRAWLERSESSION_ID`, `schedule`) 
		VALUES (NEW.`SECONDLEVELDOMAIN_ID`, 0, UTC_TIMESTAMP() ) ON DUPLICATE KEY UPDATE `SECONDLEVELDOMAIN_ID`=`SECONDLEVELDOMAIN_ID`;
  END;
|

CREATE TRIGGER `before_insert_urlpath_part` BEFORE INSERT ON `documents`.`urlpathparts`
  FOR EACH ROW
  BEGIN
    DECLARE TMP_ID INTEGER;
    SET TMP_ID = (SELECT ID FROM `documents`.`urlpathparts` WHERE PATHPART_ID=NEW.PATHPART_ID AND URLPATHPART_ID_NEXT IS NULL);
    IF NEW.URLPATHPART_ID_NEXT IS NULL AND TMP_ID > 0 THEN
      SET NEW.ID = TMP_ID;
    END IF;
  END;
|

DELIMITER ;
