DeepNet: tools::MemoryContainer< T > Class Template Reference
tools::MemoryContainer< T > Class Template Reference
generic wrapper for managed memory.
#include <MemoryContainer.h>
Public Member Functions
MemoryContainer ()
constructs empty container.
MemoryContainer (const T *element, size_t elementCount)
constructs container and copies initial elements.
MemoryContainer (const MemoryContainer< T > &copyFrom)
copy from another memory container.
virtual ~MemoryContainer ()
void operator= (const MemoryContainer< T > &assign)
operator const T * () const
T * Allocate (const size_t newElementCount, const bool zeroNewMemory)
allocates new memory.
void Release ()
releases allocated memory.
void Swap (const MemoryContainer< T > &own)
take ownership of another container.
void Swap (T *own, const size_t elementCount)
take ownership of raw memory.
T * Append (const MemoryContainer< T > &append)
appends complete container.
T * Append (const size_t appendAt, const MemoryContainer< T > &append)
appends container at a given position.
T * Append (const T *append, const size_t &appendCount)
appends certain number of elements from an array.
T * Append (const size_t appendAt, const T *append, const size_t appendCount)
appends certain number of elements at a certain position.
T * Append (const size_t appendAt, const T *append, const size_t appendStart, const size_t appendCount)
appends certain number of elements from a certain start position at a certain position.
bool EnsureSize (const size_t ensureElementCount, const bool zeroNewMemory)
ensure buffer size
void ZeroAllElements ()
zeros all elements.
T * GetElements ()
gets first element.
const T * GetConstElements () const
gets const first element.
T * GetElementAt (const size_t &elementNr)
gets elements at position.
const T * GetConstElementAt (const size_t &elementNr) const
gets const elements at position.
const size_t & GetCount () const
gets number of entries.
Private Attributes
T * element
size_t elementCount
bool releaseOnDestruct
Detailed Description
template<class T>
class tools::MemoryContainer< T >
generic wrapper for managed memory.
Definition at line 18 of file MemoryContainer.h.
Constructor & Destructor Documentation
template<class T> tools::MemoryContainer< T >::MemoryContainer () [inline]
constructs empty container.
Definition at line 23 of file MemoryContainer.h.
template<class T> tools::MemoryContainer< T >::MemoryContainer (const T * element, size_t elementCount) [inline]
constructs container and copies initial elements.
Parameters:
element initial elements.
elementCount number of initial elements.
Definition at line 30 of file MemoryContainer.h.
template<class T> tools::MemoryContainer< T >::MemoryContainer (const MemoryContainer< T > & copyFrom) [inline]
copy from another memory container.
Parameters:
copyFrom container to copy from.
Definition at line 37 of file MemoryContainer.h.
template<class T> virtual tools::MemoryContainer< T >::~MemoryContainer () [inline, virtual]
Definition at line 40 of file MemoryContainer.h.
Member Function Documentation
template<class T> void tools::MemoryContainer< T >::operator= (const MemoryContainer< T > & assign) [inline]
Definition at line 44 of file MemoryContainer.h.
template<class T> tools::MemoryContainer< T >::operator const T * () const [inline]
Definition at line 49 of file MemoryContainer.h.
References tools::MemoryContainer< T >::element.
template<class T> T* tools::MemoryContainer< T >::Allocate (const size_t newElementCount, const bool zeroNewMemory) [inline]
allocates new memory.
Parameters:
newElementCount number of new elements.
zeroNewMemory true to zero-initialized memory.
Returns:
allocated typed memory.
Definition at line 60 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::EnsureSize().
template<class T> void tools::MemoryContainer< T >::Release () [inline]
releases allocated memory.
Definition at line 83 of file MemoryContainer.h.
Referenced by network::HttpClientCURL::Get(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), tools::MemoryContainer< char >::operator=(), tools::MemoryContainer< char >::Swap(), toolbot::UnitTestSAX2HtmlParser::Test(), and tools::MemoryContainer< char >::~MemoryContainer().
template<class T> void tools::MemoryContainer< T >::Swap (const MemoryContainer< T > & own) [inline]
take ownership of another container.
Parameters:
own container to take ownership of.
Definition at line 96 of file MemoryContainer.h.
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
template<class T> void tools::MemoryContainer< T >::Swap (T * own, const size_t elementCount) [inline]
take ownership of raw memory.
Parameters:
own memory to take ownership of.
elementCount size of memory.
Definition at line 110 of file MemoryContainer.h.
template<class T> T* tools::MemoryContainer< T >::Append (const MemoryContainer< T > & append) [inline]
appends complete container.
Parameters:
append container to append.
Returns:
first element.
Definition at line 123 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::Append(), tools::MemoryContainer< char >::MemoryContainer(), tools::MemoryContainer< char >::operator=(), toolbot::UnitTestSAX2HtmlParser::Test(), and network::HttpClientCURL::WriterCallback().
template<class T> T* tools::MemoryContainer< T >::Append (const size_t appendAt, const MemoryContainer< T > & append) [inline]
appends container at a given position.
Parameters:
appendAt position to insert at.
append container to add.
Returns:
first element.
Definition at line 133 of file MemoryContainer.h.
template<class T> T* tools::MemoryContainer< T >::Append (const T * append, const size_t & appendCount) [inline]
appends certain number of elements from an array.
Parameters:
append array to append.
appendCount number of elements to append.
Returns:
first element.
Definition at line 143 of file MemoryContainer.h.
template<class T> T* tools::MemoryContainer< T >::Append (const size_t appendAt, const T * append, const size_t appendCount) [inline]
appends certain number of elements at a certain position.
Parameters:
appendAt position to insert at.
append elements to append.
appendCount number of elements to append.
Returns:
first element.
Definition at line 154 of file MemoryContainer.h.
template<class T> T* tools::MemoryContainer< T >::Append (const size_t appendAt, const T * append, const size_t appendStart, const size_t appendCount) [inline]
appends certain number of elements from a certain start position at a certain position.
Parameters:
appendAt position to insert at.
append elements to append.
appendStart start position in append.
appendCount number of elements to append.
Returns:
first element.
Definition at line 166 of file MemoryContainer.h.
template<class T> bool tools::MemoryContainer< T >::EnsureSize (const size_t ensureElementCount, const bool zeroNewMemory) [inline]
ensure buffer size
Parameters:
ensureElementCount mimimum size of buffer.
zeroNewMemory true to initialize newly allocated memory.
Returns:
first element.
Definition at line 181 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::Append().
template<class T> void tools::MemoryContainer< T >::ZeroAllElements () [inline]
zeros all elements.
Definition at line 191 of file MemoryContainer.h.
template<class T> T* tools::MemoryContainer< T >::GetElements () [inline]
gets first element.
Returns:
first element.
Definition at line 200 of file MemoryContainer.h.
template<class T> const T* tools::MemoryContainer< T >::GetConstElements () const [inline]
gets const first element.
Returns:
first element.
Definition at line 206 of file MemoryContainer.h.
template<class T> T* tools::MemoryContainer< T >::GetElementAt (const size_t & elementNr) [inline]
gets elements at position.
Parameters:
elementNr position.
Returns:
element.
Definition at line 213 of file MemoryContainer.h.
template<class T> const T* tools::MemoryContainer< T >::GetConstElementAt (const size_t & elementNr) const [inline]
gets const elements at position.
Parameters:
elementNr position.
Returns:
element.
Definition at line 220 of file MemoryContainer.h.
template<class T> const size_t& tools::MemoryContainer< T >::GetCount () const [inline]
gets number of entries.
Returns:
number of entries.
Definition at line 226 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::Append(), network::HttpClientCURL::Get(), and libxmlparser::HtmlSAX2Parser::Parse().
Member Data Documentation
template<class T> T* tools::MemoryContainer< T >::element [private]
Definition at line 229 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::Allocate(), tools::MemoryContainer< char >::Append(), tools::MemoryContainer< char >::GetConstElementAt(), tools::MemoryContainer< char >::GetConstElements(), tools::MemoryContainer< char >::GetElementAt(), tools::MemoryContainer< char >::GetElements(), tools::MemoryContainer< T >::operator const T *(), tools::MemoryContainer< char >::Release(), tools::MemoryContainer< char >::Swap(), and tools::MemoryContainer< char >::ZeroAllElements().
template<class T> size_t tools::MemoryContainer< T >::elementCount [private]
Definition at line 230 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::Allocate(), tools::MemoryContainer< char >::Append(), tools::MemoryContainer< char >::EnsureSize(), tools::MemoryContainer< char >::GetCount(), tools::MemoryContainer< char >::Release(), tools::MemoryContainer< char >::Swap(), and tools::MemoryContainer< char >::ZeroAllElements().
template<class T> bool tools::MemoryContainer< T >::releaseOnDestruct [mutable, private]
Definition at line 231 of file MemoryContainer.h.
Referenced by tools::MemoryContainer< char >::Release(), and tools::MemoryContainer< char >::Swap().
The documentation for this class was generated from the following file:
Tools/src/MemoryContainer.h