DeepNet: tools Namespace Reference
tools Namespace Reference
Classes
class CharsetEncoder
charset specific functions this class is mainly a wrapper for libicu and libiconv.
class CompressionTools
wrapper class for compression algorithms.
class ContainerTools
wrapper class to deal with stl types
class DebuggingTools
wrapper class for debugging functionality.
class FileTools
wrapper class for filesystem functionality.
class HashTools
wrapper class for hashing algorithms.
class MemoryContainer
generic wrapper for managed memory.
class MimeType
mime type parsing class.
class PCRERegex
wrapper class for perl compatible regexes.
class PCRERegexGroup
container for a group of a tools::PCRERegex
class PCRERegexResult
container for a result of a pcre regex.
class PerformanceCounter
precise time measurement class.
class Pointer
template class for generic pointers including null pointers
class AutoPointer
wrapper class for pointer that cannot be null
class PointerContainer
memory managing container for pointers.
class Regex
wrapper class for (extended) posix compatible regular expressions.
class SpellChecking
spell checking and suggestion generator.
class Stack
generic implementation of a stack
class StringTools
string manipulation class
class SynchronizedIDArray
extended semaphore type using IDs this class manages a pool of IDs that can be acuired and released synchroniously
class TimeTools
class implementing date and time specific functions and formats.
class TokenBucket
implements a token bucket pattern.
Functions
void handle_error (const char *file, int lineno, const char *msg)
static void locking_function (int mode, int n, const char *file, int line)
static unsigned long id_function (void)
int thread_setup (void)
int thread_cleanup (void)
Variables
static MUTEX_TYPE * mutex_buf = NULL
static struct tm zeroTm = { 0 }
Function Documentation
void tools::handle_error (const char * file, int lineno, const char * msg)
Definition at line 24 of file OpenSSLThreadLock.cpp.
static void tools::locking_function (int mode, int n, const char * file, int line) [static]
Definition at line 34 of file OpenSSLThreadLock.cpp.
References mutex_buf, MUTEX_LOCK, and MUTEX_UNLOCK.
Referenced by thread_setup().
static unsigned long tools::id_function (void) [static]
Definition at line 42 of file OpenSSLThreadLock.cpp.
References THREAD_ID.
Referenced by thread_setup().
int tools::thread_setup (void)
Definition at line 47 of file OpenSSLThreadLock.cpp.
References id_function(), locking_function(), mutex_buf, MUTEX_SETUP, and MUTEX_TYPE.
Referenced by crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), and crawler::DataminingCrawler::StartCrawler().
int tools::thread_cleanup (void)
Definition at line 61 of file OpenSSLThreadLock.cpp.
References mutex_buf, and MUTEX_CLEANUP.
Referenced by crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), and crawler::DataminingCrawler::StartCrawler().
Variable Documentation
MUTEX_TYPE* tools::mutex_buf = NULL [static]
Definition at line 31 of file OpenSSLThreadLock.cpp.
Referenced by locking_function(), thread_cleanup(), and thread_setup().
struct tm tools::zeroTm = { 0 } [static]
Definition at line 14 of file TimeTools.cpp.
Referenced by tools::TimeTools::InitTm().