DeepNet: toolbot::DataMiningTools Class Reference
toolbot::DataMiningTools Class Reference
#include <DataMiningTools.h>
Public Member Functions
DataMiningTools ()
virtual ~DataMiningTools ()
Static Public Member Functions
static bool RegisterDataminingAlert (database::DatabaseConnection *db, const std::string &username, const std::string &criteria, const std::string &alertType, const std::string &alertParam)
static bool InsertDataminingUser (database::DatabaseConnection *db, const std::string &username, const std::string &password)
Detailed Description
Definition at line 18 of file DataMiningTools.h.
Constructor & Destructor Documentation
toolbot::DataMiningTools::DataMiningTools ()
Definition at line 18 of file DataMiningTools.cpp.
toolbot::DataMiningTools::~DataMiningTools () [virtual]
Definition at line 21 of file DataMiningTools.cpp.
Member Function Documentation
bool toolbot::DataMiningTools::RegisterDataminingAlert (database::DatabaseConnection * db, const std::string & username, const std::string & criteria, const std::string & alertType, const std::string & alertParam) [static]
Definition at line 24 of file DataMiningTools.cpp.
References database::dataminingcustomerTableBase::Get_ID(), database::dataminingcustomerTableBase::GetBy_login(), tools::PointerContainer< T >::GetIter(), database::TableBase::Insert(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::DataminingNotifier::NOTIFY_TYPE_EMAIL, indexing::DataminingNotifier::NOTIFY_TYPE_UNKNOWN, database::dataminingcriteriaalertsTableBase::Set_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGCRITERIA_ID(), database::dataminingcriteriaTableBase::Set_keyword(), database::dataminingalertsTableBase::Set_param(), database::dataminingalertsTableBase::Set_type(), database::dataminingcriteriaTableBase::Set_type(), tools::PointerContainer< T >::Size(), database::DatabaseConnection::TransactionCommit(), database::DatabaseConnection::TransactionRollback(), and database::DatabaseConnection::TransactionStart().
Referenced by toolbot::DeepNetToolBot::OnRun().
bool toolbot::DataMiningTools::InsertDataminingUser (database::DatabaseConnection * db, const std::string & username, const std::string & password) [static]
Definition at line 87 of file DataMiningTools.cpp.
References tools::HashTools::GetSHA512(), database::TableBase::Insert(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_TRACE, database::dataminingcustomerTableBase::Set_login(), and database::dataminingcustomerTableBase::Set_password().
Referenced by toolbot::DeepNetToolBot::OnRun().
The documentation for this class was generated from the following files:
DeepNetTool/src/DataMiningTools.h
DeepNetTool/src/DataMiningTools.cpp