DeepNet: tools::TokenBucket Class Reference
tools::TokenBucket Class Reference
implements a token bucket pattern.
#include <TokenBucket.h>
Public Member Functions
TokenBucket ()
virtual ~TokenBucket ()
void Start (const size_t &maxToken, const size_t &refillToken)
start the token bucket.
void Stop ()
stop the token bucket.
void Reset ()
reset the token bucket.
bool RemoveTokens (size_t tokenCount)
waits till a certain number of tokens have been removed.
size_t TryRemoveTokens (size_t tokenCount)
tries to remove a certain number of tokens.
Private Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Private Member Functions
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
void SetThreadFunction (ThreadFunction pFunction)
Static Private Member Functions
static void * RefillThreadFunc (threading::Thread::THREAD_PARAM *params)
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Private Attributes
size_t curToken
size_t maxToken
size_t refillToken
size_t refillFreq
bool isOverflowing
threading::Mutex lock
Detailed Description
implements a token bucket pattern.
used for bandwidth measuring. for more info check http://en.wikipedia.org/wiki/Token_bucket
Definition at line 20 of file TokenBucket.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
tools::TokenBucket::TokenBucket ()
Definition at line 13 of file TokenBucket.cpp.
tools::TokenBucket::~TokenBucket () [virtual]
Definition at line 22 of file TokenBucket.cpp.
References Stop().
Member Function Documentation
void tools::TokenBucket::Start (const size_t & maxToken, const size_t & refillToken)
start the token bucket.
Parameters:
maxToken maximum items in token bucket.
refillToken items to refill per second.
Definition at line 27 of file TokenBucket.cpp.
References curToken, maxToken, refillToken, Reset(), and threading::Thread::StartThread().
void tools::TokenBucket::Stop (void)
stop the token bucket.
Definition at line 38 of file TokenBucket.cpp.
References curToken, threading::Thread::IsRunning(), maxToken, refillToken, threading::Thread::SetShallEnd(), and threading::Thread::WaitForThread().
Referenced by Reset(), and ~TokenBucket().
void tools::TokenBucket::Reset ()
reset the token bucket.
Definition at line 50 of file TokenBucket.cpp.
References Stop().
Referenced by Start().
bool tools::TokenBucket::RemoveTokens (size_t tokenCount)
waits till a certain number of tokens have been removed.
Parameters:
tokenCount number of tokens to remove.
Returns:
false on error, true on success.
Definition at line 73 of file TokenBucket.cpp.
References isOverflowing, threading::Thread::IsRunning(), maxToken, refillFreq, and TryRemoveTokens().
size_t tools::TokenBucket::TryRemoveTokens (size_t tokenCount)
tries to remove a certain number of tokens.
Parameters:
tokenCount number of tokens to remove.
Returns:
number of tokens actually removed.
Definition at line 97 of file TokenBucket.cpp.
References curToken, threading::Thread::IsRunning(), threading::Mutex::Lock(), lock, and threading::Mutex::Unlock().
Referenced by RemoveTokens().
void * tools::TokenBucket::RefillThreadFunc (threading::Thread::THREAD_PARAM * params) [static, private]
Definition at line 55 of file TokenBucket.cpp.
References curToken, isOverflowing, threading::Mutex::Lock(), lock, maxToken, threading::Thread::THREAD_PARAM::pParam, refillFreq, refillToken, threading::Thread::ShallEnd(), and threading::Mutex::Unlock().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), Stop(), and TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
size_t tools::TokenBucket::curToken [private]
Definition at line 60 of file TokenBucket.h.
Referenced by RefillThreadFunc(), Start(), Stop(), and TryRemoveTokens().
size_t tools::TokenBucket::maxToken [private]
Definition at line 61 of file TokenBucket.h.
Referenced by RefillThreadFunc(), RemoveTokens(), Start(), and Stop().
size_t tools::TokenBucket::refillToken [private]
Definition at line 62 of file TokenBucket.h.
Referenced by RefillThreadFunc(), Start(), and Stop().
size_t tools::TokenBucket::refillFreq [private]
Definition at line 63 of file TokenBucket.h.
Referenced by RefillThreadFunc(), and RemoveTokens().
bool tools::TokenBucket::isOverflowing [private]
Definition at line 65 of file TokenBucket.h.
Referenced by RefillThreadFunc(), and RemoveTokens().
threading::Mutex tools::TokenBucket::lock [private]
Definition at line 67 of file TokenBucket.h.
Referenced by RefillThreadFunc(), and TryRemoveTokens().
The documentation for this class was generated from the following files:
Tools/src/TokenBucket.h
Tools/src/TokenBucket.cpp