DeepNet: log::Logging Class Reference
log::Logging Class Reference
implements generic logging functionality.
#include <Logging.h>
Public Types
enum LogLevel {
LOGLEVEL_ERROR = 0, LOGLEVEL_WARN = 1, LOGLEVEL_INFO = 2, LOGLEVEL_TRACE = 3,
LOGLEVEL_MAX = 10000
}
log level
Public Member Functions
virtual ~Logging ()
Static Public Member Functions
static void LogError (const std::string &msg)
log an error.
static void LogWarn (const std::string &msg)
log a warning.
static void LogInfo (const std::string &msg)
log an information.
static void LogTrace (const std::string &msg)
log a debug information.
static void LogTraceUnlimited (const std::string &msg)
log a debug information not respecting max log length.
static void RegisterThreadID (const std::string &threadName)
register a current thread assigning it a name.
static void SetApplicationName (const std::string &applicationNameIn)
set the name of the application.
static void SetMaxLogLength (size_t maxLogMsgLengthIn)
set the maximum length of a log message.
static size_t GetMaxLogLength ()
get the maximum length of a log message.
static void SetLogLevel (LogLevel logLevelIn)
set the log level.
static void Log (const LogLevel levelMsg, const std::string &msg)
log a message.
static void Log (const LogLevel levelMsg, const char *fmt,...)
log a message.
static void LogUnlimited (const LogLevel levelMsg, const char *fmt,...)
log a message not respecting max log length.
static void LogUnlimited (const LogLevel levelMsg, const std::string &msg)
log a message not respecting max log length.
static LogLevel GetLogLevel ()
get the log level.
static bool IsLogLevelTrace ()
checks if current log level is debug.
static void GetTimeString (std::string &timeString)
creates time string for log output.
Protected Member Functions
Logging ()
Static Protected Member Functions
static void GetLogLevelString (const LogLevel logLevel, std::string &logLevelString)
gets the log level as a string.
static void GetPIDTIDString (const std::string &applicationName, std::string &pidTIDString)
gets process info as a string.
static bool GetThreadNameByTID (const long int &tid, std::string &threadName)
gets a thread's name by it's thread id
Protected Attributes
std::string applicationName
application name.
Private Member Functions
virtual void OnLog (const LogLevel levelMsg, const std::string &msg)=0
void SetMaxLogLength_Intern (size_t maxLogMsgLength)
void SetLogLevel_Intern (LogLevel logLevel)
void SetApplicationName_Intern (const std::string &applicationName)
void Log_Intern (const LogLevel levelMsg, const size_t length, const std::string &msg)
Private Attributes
volatile bool isLocking
volatile LogLevel logLevel
volatile size_t maxLogMsgLength
Static Private Attributes
static threading::Mutex mutex
static Logging * instance = NULL
static threading::ReadWriteLock lockThreadNames
static std::map< long int,
std::string > threadNames
Detailed Description
implements generic logging functionality.
Definition at line 26 of file Logging.h.
Member Enumeration Documentation
enum log::Logging::LogLevel
log level
Enumerator:
LOGLEVEL_ERROR
errors
LOGLEVEL_WARN
warnings
LOGLEVEL_INFO
information
LOGLEVEL_TRACE
debug
LOGLEVEL_MAX
do not use this
Definition at line 33 of file Logging.h.
Constructor & Destructor Documentation
log::Logging::Logging () [protected]
Definition at line 23 of file Logging.cpp.
References instance.
log::Logging::~Logging () [virtual]
Definition at line 31 of file Logging.cpp.
Member Function Documentation
static void log::Logging::LogError (const std::string & msg) [inline, static]
log an error.
Parameters:
msg log message.
Definition at line 71 of file Logging.h.
References Log(), and LOGLEVEL_ERROR.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), crawler::FencedUrlFetcherThread::CheckSecondLevelDomainTimeout(), toolbot::UnitTestIndexerEx::HandleSingleFile(), bot::ConfigManager::Init(), bot::Bot::InitDatabaseConfigs(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), toolbot::DeepNetToolBot::OnRun(), toolbot::UnitTestHttpClientCURL::Run(), toolbot::UnitTestIndexerEx::Run(), crawler::FencedCrawler::StartCrawler(), toolbot::UnitTestSAX2HtmlParser::Test(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
static void log::Logging::LogWarn (const std::string & msg) [inline, static]
log a warning.
Parameters:
msg log message.
Definition at line 77 of file Logging.h.
References Log(), and LOGLEVEL_WARN.
Referenced by database::DatabaseHelper::CreateConnection(), bot::DatabaseRepair::FixUncleanShutdown(), libxmlparser::HtmlSAX2Parser::genericErrorFunc(), and bot::DatabaseRepair::ValidateSyncTables().
static void log::Logging::LogInfo (const std::string & msg) [inline, static]
log an information.
Parameters:
msg log message.
Definition at line 83 of file Logging.h.
References Log(), and LOGLEVEL_INFO.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), toolbot::UnitTestIndexerEx::HandleSingleFile(), parser::GenericWebHtmlParserThread::InsertImages(), toolbot::DeepNetToolBot::OnRun(), domparser::DocumentFactory::ParseError(), toolbot::UnitTestIndexerEx::Run(), and toolbot::UnitTestSAX2HtmlParser::Test().
static void log::Logging::LogTrace (const std::string & msg) [inline, static]
log a debug information.
Parameters:
msg log message.
Definition at line 89 of file Logging.h.
References Log(), and LOGLEVEL_TRACE.
Referenced by network::HtmlData::ConvertToHostCharset(), toolbot::UnitTestHtmlTokeniser::EmitCharacter(), toolbot::UnitTestHtmlTokeniser::EmitComment(), toolbot::UnitTestHtmlTokeniser::EmitDocType(), toolbot::UnitTestHtmlTokeniser::EmitTag(), libxmlparser::HtmlSAX2Parser::endElement(), libxmlparser::HtmlSAX2Parser::fatalError(), network::HttpClientCURL::Get(), database::MySQLConnection::Initialize(), workerbot::WorkerBot::OnShutdown(), toolbot::UnitTestHtmlDocumentFactory::OnToken(), indexing::IndexerEx::Parse(), toolbot::UnitTestHtmlTokeniser::ParseError(), indexing::IndexerEx::ParseMeta(), indexing::IndexerThread::ParsePages(), bot::Bot::PostInit(), toolbot::UnitTestHtmlDocumentFactory::Run(), toolbot::UnitTestHtmlDocumentFactory::SwitchMode(), toolbot::UnitTestHtmlTokeniser::SwitchState(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
static void log::Logging::LogTraceUnlimited (const std::string & msg) [inline, static]
log a debug information not respecting max log length.
Parameters:
msg log message.
Definition at line 95 of file Logging.h.
References LOGLEVEL_TRACE, and LogUnlimited().
void log::Logging::RegisterThreadID (const std::string & threadName) [static]
register a current thread assigning it a name.
Parameters:
threadName thread name.
Definition at line 144 of file Logging.cpp.
References lockThreadNames, threading::ReadWriteLock::ReleaseLock(), threadNames, and threading::ReadWriteLock::WaitForWriteLock().
Referenced by crawler::Crawler::CrawlerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
void log::Logging::SetApplicationName (const std::string & applicationNameIn) [static]
set the name of the application.
Parameters:
applicationNameIn application name.
Definition at line 173 of file Logging.cpp.
References instance, and SetApplicationName_Intern().
Referenced by bot::Bot::InitLogging().
void log::Logging::SetMaxLogLength (size_t maxLogMsgLengthIn) [static]
set the maximum length of a log message.
Parameters:
maxLogMsgLengthIn maximum length.
Definition at line 178 of file Logging.cpp.
References instance, and SetMaxLogLength_Intern().
Referenced by log::ConsoleLogging::ConsoleLogging(), log::FileLogging::FileLogging(), and SignalHandler().
static size_t log::Logging::GetMaxLogLength () [inline, static]
get the maximum length of a log message.
Returns:
maximum length.
Definition at line 119 of file Logging.h.
References instance, and maxLogMsgLength.
Referenced by SignalHandler().
void log::Logging::SetLogLevel (LogLevel logLevelIn) [static]
set the log level.
Parameters:
logLevelIn log level.
Definition at line 183 of file Logging.cpp.
References instance, and SetLogLevel_Intern().
Referenced by bot::Bot::InitLogging(), and fastcgiserver::FastCGIServer::InitLoggingConfig().
void log::Logging::Log (const LogLevel levelMsg, const std::string & msg) [static]
log a message.
Parameters:
levelMsg log level.
msg log message.
Definition at line 151 of file Logging.cpp.
References GetLogLevelString(), GetTimeString(), instance, Log_Intern(), and maxLogMsgLength.
Referenced by indexing::Dictionary::AddContent(), indexing::Dictionary::AddMeta(), indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), crawler::UrlFetcherThread::CommitPages(), tools::Regex::Compile(), tools::PCRERegex::Compile(), database::MySQLConnection::Connect(), bot::Bot::Daemonize(), network::HtmlData::DetectCharset(), database::MySQLConnection::Disconnect(), tools::CharsetEncoder::EncodeHtmlEntities(), libxmlparser::HtmlSAX2Parser::endElement(), database::MySQLConnection::Execute(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), network::HttpCookie::FromString(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::UrlFetcherThread::GetNextCrawlerSessionID(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetResultsFromDatasources(), queryserver::XMLQueryResponse::GroupResults(), indexing::IndexerThread::IndexerThreadFunc(), bot::Bot::InitCacheConfigParams(), workerbot::WorkerBot::InitCrawlerConfig(), fastcgiserver::FastCGIServer::InitDatabaseConfigs(), workerbot::WorkerBot::InitIndexerConfigParams(), workerbot::WorkerBot::InitParserConfig(), toolbot::DataMiningTools::InsertDataminingUser(), parser::GenericWebHtmlParserThread::InsertLinks(), htmlparser::UrlInserter::InsertURL(), htmlparser::UrlInserter::InsertURLFile(), Log(), LogError(), LogInfo(), queryserver::XMLQueryResponse::LogQuery(), fastcgiserver::FastCGIRequest::LogRequest(), LogTrace(), LogWarn(), tools::PCRERegex::Match(), tools::PCRERegex::MatchEx(), toolbot::UnitTestUrlParser::OnError(), toolbot::UnitTestPCRERegex::OnError(), fastcgiserver::FastCGIServer::OnException(), bot::Bot::OnException(), suggestserver::SuggestServerRequest::OnHandle(), inspectorserver::InspectorServerRequest::OnHandle(), queryserver::XMLQueryRequest::OnHandle(), toolbot::DeepNetToolBot::OnRun(), queryserver::XMLQueryResponse::OutputResults(), indexing::IndexerTester::Parse(), bot::CommandLine::ParseCommandLine(), bot::ConfigFile::ParseConfigFile(), fastcgiserver::FastCGIRequest::ParseCookies(), toolbot::UnitTestPCRERegex::ParseExpectedGroups(), bot::ConfigFile::ParseFile(), parser::HtmlParserThread::ParsePages(), queryserver::XMLQueryRequest::ParseQuery(), queryserver::XMLQueryRequest::ParseQueryCriteria(), queryserver::XMLQueryRequest::ParseQueryGrouping(), queryserver::XMLQueryRequest::ParseQueryLimitations(), toolbot::UnitTestPCRERegex::ParseTestFile(), inspectorserver::InspectorServerResponse::Process(), fastcgiserver::FastCGIResponse::Process(), database::MySQLConnection::Query(), fastcgiserver::FastCGIRequest::ReadPostData(), htmlparser::UrlInserter::ReadURLFile(), toolbot::DataMiningTools::RegisterDataminingAlert(), toolbot::UnitTestManager::Run(), toolbot::UnitTestCacheUrl::Run(), queryserver::XMLQueryResponse::SaveResults(), log::FileLogging::SetFileName(), SignalHandler(), bot::Bot::SignalHandler(), toolbot::UnitTestSAX2HtmlParser::Test(), toolbot::UnitTestUrlParser::TestInvalidUrls(), toolbot::UnitTestCacheUrl::TestSingleEntry(), toolbot::UnitTestUrlParser::TestValidUrls(), fastcgiserver::HttpHeader::ToString(), crawler::UrlFetcherThread::UrlFetcherThreadFunction(), bot::ConfigManager::ValidateConfig(), htmlparser::UrlInserter::ValidateURL(), htmlparser::UrlInserter::ValidateURLFile(), and fastcgiserver::FastCGIRequest::Xpath().
void log::Logging::Log (const LogLevel levelMsg, const char * fmt, ...) [static]
log a message.
Parameters:
levelMsg log level.
fmt format string.
Definition at line 56 of file Logging.cpp.
References instance, Log(), Log_Intern(), logLevel, and maxLogMsgLength.
void log::Logging::LogUnlimited (const LogLevel levelMsg, const char * fmt, ...) [static]
log a message not respecting max log length.
Parameters:
levelMsg log level.
fmt format string.
Definition at line 100 of file Logging.cpp.
References instance, Log_Intern(), and logLevel.
Referenced by errors::Exception::Log(), LogTraceUnlimited(), and bot::Bot::SignalHandler().
void log::Logging::LogUnlimited (const LogLevel levelMsg, const std::string & msg) [static]
log a message not respecting max log length.
Parameters:
levelMsg log level.
msg log message.
Definition at line 162 of file Logging.cpp.
References GetLogLevelString(), GetTimeString(), instance, and Log_Intern().
Logging::LogLevel log::Logging::GetLogLevel () [static]
get the log level.
Definition at line 188 of file Logging.cpp.
References instance, logLevel, and LOGLEVEL_MAX.
Referenced by database::MySQLConnection::Execute(), IsLogLevelTrace(), and fastcgiserver::FastCGIRequest::LogRequest().
bool log::Logging::IsLogLevelTrace () [static]
checks if current log level is debug.
Returns:
false if not debug, true if debug (LOGLEVEL_TRACE).
Definition at line 194 of file Logging.cpp.
References GetLogLevel(), and LOGLEVEL_TRACE.
Referenced by crawler::UrlFetcherThread::CommitPages(), network::HtmlData::ConvertToHostCharset(), network::HtmlData::DetectCharset(), libxmlparser::HtmlSAX2Parser::endElement(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), libxmlparser::HtmlSAX2Parser::fatalError(), network::HttpClientCURL::Get(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), database::MySQLConnection::Initialize(), parser::GenericWebHtmlParserThread::InsertLinks(), domparser::DOMParser::Parse(), indexing::IndexerEx::Parse(), indexing::IndexerEx::ParseMeta(), indexing::IndexerThread::ParsePages(), bot::Bot::PostInit(), bot::Bot::SignalHandler(), and toolbot::UnitTestUrlParser::TestValidUrls().
void log::Logging::GetTimeString (std::string & timeString) [static]
creates time string for log output.
Parameters:
timeString time string.
Definition at line 198 of file Logging.cpp.
Referenced by errors::Exception::Dump(), Log(), LogUnlimited(), log::ConsoleLogging::OnLog(), and log::FileLogging::OnLog().
void log::Logging::GetLogLevelString (const LogLevel logLevel, std::string & logLevelString) [static, protected]
gets the log level as a string.
Parameters:
logLevel log level.
logLevelString log level as a string.
Definition at line 210 of file Logging.cpp.
References LOGLEVEL_ERROR, LOGLEVEL_INFO, LOGLEVEL_TRACE, and LOGLEVEL_WARN.
Referenced by Log(), LogUnlimited(), log::ConsoleLogging::OnLog(), and log::FileLogging::OnLog().
void log::Logging::GetPIDTIDString (const std::string & applicationName, std::string & pidTIDString) [static, protected]
gets process info as a string.
Parameters:
applicationName application name.
pidTIDString gets filled with process information.
Definition at line 232 of file Logging.cpp.
References GetThreadNameByTID().
Referenced by log::ConsoleLogging::OnLog(), and log::FileLogging::OnLog().
bool log::Logging::GetThreadNameByTID (const long int & tid, std::string & threadName) [static, protected]
gets a thread's name by it's thread id
Parameters:
tid tid of thread
threadName name of thread
Returns:
true if successful, false if unsuccessful
Definition at line 249 of file Logging.cpp.
References lockThreadNames, threading::ReadWriteLock::ReleaseLock(), threadNames, and threading::ReadWriteLock::WaitForReadLock().
Referenced by GetPIDTIDString(), and log::DatabaseLogging::OnLog().
virtual void log::Logging::OnLog (const LogLevel levelMsg, const std::string & msg) [private, pure virtual]
Implemented in log::FileLogging, log::DatabaseLogging, and log::ConsoleLogging.
Referenced by Log_Intern().
void log::Logging::SetMaxLogLength_Intern (size_t maxLogMsgLength) [private]
Definition at line 258 of file Logging.cpp.
References maxLogMsgLength.
Referenced by SetMaxLogLength().
void log::Logging::SetLogLevel_Intern (LogLevel logLevel) [private]
Definition at line 262 of file Logging.cpp.
References logLevel.
Referenced by SetLogLevel().
void log::Logging::SetApplicationName_Intern (const std::string & applicationName) [private]
Definition at line 266 of file Logging.cpp.
References applicationName.
Referenced by SetApplicationName().
void log::Logging::Log_Intern (const LogLevel levelMsg, const size_t length, const std::string & msg) [private]
Definition at line 35 of file Logging.cpp.
References isLocking, threading::Mutex::Lock(), logLevel, mutex, OnLog(), and threading::Mutex::Unlock().
Referenced by Log(), and LogUnlimited().
Member Data Documentation
std::string log::Logging::applicationName [protected]
application name.
Definition at line 199 of file Logging.h.
Referenced by log::ConsoleLogging::OnLog(), log::DatabaseLogging::OnLog(), log::FileLogging::OnLog(), and SetApplicationName_Intern().
volatile bool log::Logging::isLocking [private]
Definition at line 210 of file Logging.h.
Referenced by Log_Intern().
volatile LogLevel log::Logging::logLevel [private]
Definition at line 211 of file Logging.h.
Referenced by GetLogLevel(), Log(), Log_Intern(), LogUnlimited(), and SetLogLevel_Intern().
volatile size_t log::Logging::maxLogMsgLength [private]
Definition at line 212 of file Logging.h.
Referenced by GetMaxLogLength(), Log(), and SetMaxLogLength_Intern().
threading::Mutex log::Logging::mutex [static, private]
Definition at line 214 of file Logging.h.
Referenced by Log_Intern().
Logging * log::Logging::instance = NULL [static, private]
Definition at line 215 of file Logging.h.
Referenced by GetLogLevel(), GetMaxLogLength(), Log(), Logging(), LogUnlimited(), SetApplicationName(), SetLogLevel(), and SetMaxLogLength().
threading::ReadWriteLock log::Logging::lockThreadNames [static, private]
Definition at line 217 of file Logging.h.
Referenced by GetThreadNameByTID(), and RegisterThreadID().
std::map< long int, std::string > log::Logging::threadNames [static, private]
Definition at line 218 of file Logging.h.
Referenced by GetThreadNameByTID(), and RegisterThreadID().
The documentation for this class was generated from the following files:
Logging/src/Logging.h
Logging/src/Logging.cpp