DeepNet: crawler::FencedCrawler Class Reference
crawler::FencedCrawler Class Reference
#include <FencedCrawler.h>
Public Member Functions
virtual ~FencedCrawler ()
const std::vector< long long > & GetOldCrawlerSessionIDs () const
gets old crawler session ids after crawling threads ended
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
void SetThreadFunction (ThreadFunction pFunction)
Protected Attributes
const CrawlerParam * crawlerParam
crawler parameters associated with this thread.
std::map< UrlFetcherThread
*, UrlFetcherThreadParam * > urlFetcherThreads
map of url fetcher threads and their parameters.
Private Member Functions
FencedCrawler (const CrawlerParam *crawlerParam)
virtual bool StartCrawler ()
starts crawler thread.
Private Attributes
std::vector< long long > boundSecondLevelDomains
Friends
class CrawlerFactory
Detailed Description
Definition at line 20 of file FencedCrawler.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
crawler::FencedCrawler::FencedCrawler (const CrawlerParam * crawlerParam) [private]
Definition at line 19 of file FencedCrawler.cpp.
crawler::FencedCrawler::~FencedCrawler () [virtual]
Definition at line 23 of file FencedCrawler.cpp.
Member Function Documentation
bool crawler::FencedCrawler::StartCrawler () [private, virtual]
starts crawler thread.
Returns:
false on error, true on success.
Implements crawler::Crawler.
Definition at line 26 of file FencedCrawler.cpp.
References boundSecondLevelDomains, crawler::Crawler::crawlerParam, database::DatabaseHelper::CreateConnection(), database::fencedsearchTableBase::CreateTableDefinition(), crawler::CrawlerParam::databaseConfig, database::DatabaseHelper::DestroyConnection(), database::fencedsearchTableBase::Get_SECONDLEVELDOMAIN_ID(), tools::PointerContainer< T >::GetIter(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::LogError(), tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), threading::Thread::StartThread(), tools::thread_cleanup(), tools::thread_setup(), crawler::CrawlerParam::threadCount, and crawler::Crawler::urlFetcherThreads.
const std::vector< long long > & crawler::Crawler::GetOldCrawlerSessionIDs () const [inherited]
gets old crawler session ids after crawling threads ended
Definition at line 87 of file Crawler.cpp.
References crawler::Crawler::oldCrawlerSessionIDs.
Referenced by workerbot::WorkerBot::CheckCleanShutdown().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Friends And Related Function Documentation
friend class CrawlerFactory [friend]
Definition at line 22 of file FencedCrawler.h.
Member Data Documentation
std::vector<long long> crawler::FencedCrawler::boundSecondLevelDomains [private]
Definition at line 33 of file FencedCrawler.h.
Referenced by StartCrawler().
const CrawlerParam* crawler::Crawler::crawlerParam [protected, inherited]
crawler parameters associated with this thread.
Definition at line 60 of file Crawler.h.
Referenced by crawler::Crawler::CrawlerThreadFunc(), StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), and crawler::CommerceSearchCrawler::StartCrawler().
std::map<UrlFetcherThread*,UrlFetcherThreadParam*> crawler::Crawler::urlFetcherThreads [protected, inherited]
map of url fetcher threads and their parameters.
Definition at line 65 of file Crawler.h.
Referenced by StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::Crawler::StopCrawler(), and crawler::Crawler::WatchDog().
The documentation for this class was generated from the following files:
Crawler/src/FencedCrawler.h
Crawler/src/FencedCrawler.cpp