DeepNet: caching::RobotTxt Class Reference
caching::RobotTxt Class Reference
wrapper class for a robots.txt.
#include <RobotTxt.h>
Public Member Functions
RobotTxt (const long long &toplevelID, const long long &secondlevelID, const long long &subdomainID)
constructs object with corresponding domain ids.
virtual ~RobotTxt ()
bool Load (const std::string &robotsTxt)
parse robots.txt from string.
bool AppliesTo (const htmlparser::DatabaseUrl &url) const
check if url is valid for this robots.txt.
bool IsAllowed (const htmlparser::DatabaseUrl &url, const std::string &userAgent)
check if url is allowed.
std::string ToString ()
dump robots.txt as string
Private Member Functions
RobotTxt ()
Private Attributes
long long toplevelID
long long secondlevelID
long long subdomainID
std::map< std::string,
std::vector< std::string > > useragent
Detailed Description
wrapper class for a robots.txt.
Definition at line 28 of file RobotTxt.h.
Constructor & Destructor Documentation
caching::RobotTxt::RobotTxt () [private]
Definition at line 18 of file RobotTxt.cpp.
caching::RobotTxt::RobotTxt (const long long & toplevelID, const long long & secondlevelID, const long long & subdomainID)
constructs object with corresponding domain ids.
Parameters:
toplevelID toplevel domain id.
secondlevelID secondlevel domain id.
subdomainID subdomain id.
Definition at line 24 of file RobotTxt.cpp.
caching::RobotTxt::~RobotTxt () [virtual]
Definition at line 30 of file RobotTxt.cpp.
Member Function Documentation
bool caching::RobotTxt::Load (const std::string & robotsTxt)
parse robots.txt from string.
Parameters:
robotsTxt robots.txt as string.
Returns:
false on error, true on success.
Definition at line 33 of file RobotTxt.cpp.
References tools::PCRERegex::Match(), REGEX_ROBOTS_LINE, tools::StringTools::RemoveComments(), tools::StringTools::RemoveEmptyLines(), tools::StringTools::ToLowerIP(), and useragent.
Referenced by caching::CacheRobotsTxt::DownloadRobotsTxt(), and toolbot::UnitTestRobotTxt::Run().
bool caching::RobotTxt::AppliesTo (const htmlparser::DatabaseUrl & url) const
check if url is valid for this robots.txt.
Parameters:
url url to check.
Returns:
false if not matching, true if matching.
Definition at line 90 of file RobotTxt.cpp.
References htmlparser::DatabaseUrl::GetSecondLevelID(), htmlparser::DatabaseUrl::GetSubdomainID(), htmlparser::DatabaseUrl::GetTopLevelID(), secondlevelID, subdomainID, and toplevelID.
bool caching::RobotTxt::IsAllowed (const htmlparser::DatabaseUrl & url, const std::string & userAgent)
check if url is allowed.
Parameters:
url url to check.
userAgent useragent to check for.
Returns:
Definition at line 99 of file RobotTxt.cpp.
References network::HttpUrl::GetFullPathSearch(), and useragent.
std::string caching::RobotTxt::ToString ()
dump robots.txt as string
Returns:
dumped string.
Definition at line 122 of file RobotTxt.cpp.
References useragent.
Referenced by toolbot::UnitTestRobotTxt::Run().
Member Data Documentation
long long caching::RobotTxt::toplevelID [private]
Definition at line 77 of file RobotTxt.h.
Referenced by AppliesTo().
long long caching::RobotTxt::secondlevelID [private]
Definition at line 78 of file RobotTxt.h.
Referenced by AppliesTo().
long long caching::RobotTxt::subdomainID [private]
Definition at line 79 of file RobotTxt.h.
Referenced by AppliesTo().
std::map<std::string, std::vector<std::string> > caching::RobotTxt::useragent [private]
Definition at line 81 of file RobotTxt.h.
Referenced by IsAllowed(), Load(), and ToString().
The documentation for this class was generated from the following files:
Caching/src/RobotTxt.h
Caching/src/RobotTxt.cpp