DeepNet: indexing::IndexerThread Class Reference
indexing::IndexerThread Class Reference
#include <IndexerThread.h>
Classes
struct IndexerThreadParam
Public Member Functions
virtual ~IndexerThread ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
IndexerThread ()
database::DatabaseHelper & DB ()
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
bool GetNextPages (std::map< long long, caching::CacheParsed::CacheParsedEntry > &entries)
bool ParsePages (std::map< long long, caching::CacheParsed::CacheParsedEntry > &entries)
void OnIdle ()
virtual void OnCreateIndexer (tools::Pointer< IIndexer > &indexerMeta, tools::Pointer< IIndexer > &indexerContent)=0
Static Private Member Functions
static void * IndexerThreadFunc (threading::Thread::THREAD_PARAM *threadParam)
Private Attributes
IndexerThreadParam indexerThreadParam
database::DatabaseHelper databaseHelper
tools::Pointer< IIndexer > indexerMeta
tools::Pointer< IIndexer > indexerContent
Detailed Description
Definition at line 23 of file IndexerThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
indexing::IndexerThread::IndexerThread () [protected]
Definition at line 20 of file IndexerThread.cpp.
indexing::IndexerThread::~IndexerThread () [virtual]
Definition at line 25 of file IndexerThread.cpp.
Member Function Documentation
void * indexing::IndexerThread::IndexerThreadFunc (threading::Thread::THREAD_PARAM * threadParam) [static, private]
Definition at line 29 of file IndexerThread.cpp.
References database::DatabaseHelper::CreateConnection(), indexing::IndexerThread::IndexerThreadParam::databaseConfig, DB(), database::DatabaseHelper::DestroyConnection(), GetNextPages(), indexerContent, indexerMeta, indexerThreadParam, threading::Thread::THREAD_PARAM::instance, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, OnCreateIndexer(), ParsePages(), PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, threading::Thread::THREAD_PARAM::pParam, log::Logging::RegisterThreadID(), and threading::Thread::ShallEnd().
bool indexing::IndexerThread::GetNextPages (std::map< long long, caching::CacheParsed::CacheParsedEntry > & entries) [private]
Definition at line 66 of file IndexerThread.cpp.
References caching::CacheParsed::Get(), indexerThreadParam, indexing::IndexerThread::IndexerThreadParam::maxPerSelect, OnIdle(), PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by IndexerThreadFunc().
bool indexing::IndexerThread::ParsePages (std::map< long long, caching::CacheParsed::CacheParsedEntry > & entries) [private]
Definition at line 78 of file IndexerThread.cpp.
References tools::Pointer< T >::Get(), indexerContent, indexerMeta, log::Logging::IsLogLevelTrace(), log::Logging::LogTrace(), indexing::Dictionary::META_AUTHOR, indexing::Dictionary::META_COPYRIGHT, indexing::Dictionary::META_DESCRIPTION, indexing::Dictionary::META_KEYWORDS, indexing::Dictionary::META_TITLE, indexing::Dictionary::META_UNKNOWN, and tools::StringTools::ToLowerNP().
Referenced by IndexerThreadFunc().
void indexing::IndexerThread::OnIdle () [private]
Definition at line 117 of file IndexerThread.cpp.
References indexerThreadParam, threading::Thread::ShallEnd(), and indexing::IndexerThread::IndexerThreadParam::waitOnIdle.
Referenced by GetNextPages().
virtual void indexing::IndexerThread::OnCreateIndexer (tools::Pointer< IIndexer > & indexerMeta, tools::Pointer< IIndexer > & indexerContent) [private, pure virtual]
Implemented in indexing::DataminingIndexerThread, and indexing::GenericWebIndexerThread.
Referenced by IndexerThreadFunc().
database::DatabaseHelper& indexing::IndexerThread::DB () [inline, protected]
Definition at line 67 of file IndexerThread.h.
References databaseHelper.
Referenced by IndexerThreadFunc(), indexing::DataminingIndexerThread::OnCreateIndexer(), and indexing::GenericWebIndexerThread::OnCreateIndexer().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
IndexerThreadParam indexing::IndexerThread::indexerThreadParam [private]
Definition at line 70 of file IndexerThread.h.
Referenced by GetNextPages(), IndexerThreadFunc(), and OnIdle().
database::DatabaseHelper indexing::IndexerThread::databaseHelper [private]
Definition at line 71 of file IndexerThread.h.
Referenced by DB().
tools::Pointer<IIndexer> indexing::IndexerThread::indexerMeta [private]
Definition at line 72 of file IndexerThread.h.
Referenced by IndexerThreadFunc(), and ParsePages().
tools::Pointer<IIndexer> indexing::IndexerThread::indexerContent [private]
Definition at line 73 of file IndexerThread.h.
Referenced by IndexerThreadFunc(), and ParsePages().
The documentation for this class was generated from the following files:
Indexer/src/IndexerThread.h
Indexer/src/IndexerThread.cpp