DeepNet: database::TableColumn Class Reference
database::TableColumn Class Reference
implements generic table column.
#include <TableColumn.h>
Public Member Functions
virtual ~TableColumn ()
const std::string & GetColumnName () const
gets column name.
const TableColumnDefinition * GetConstColumnDefinition () const
gets const column definition.
TableColumnDefinition * GetColumnDefinition ()
gets column definition.
void CopyValue (const TableColumn *col)
copy value from another column.
bool IsDirty () const
checks if column has changed.
bool IsNull () const
checks if column has NULL value.
void SetNull ()
sets columns value to NULL (undefined value).
void SetDirty ()
sets columns value as dirty.
void SetClean ()
sets column value as non-dirty
void SetColumnAlias (const std::string tableAlias)
sets alias name of column.
const std::string & GetColumnAlias () const
gets alias name of column.
template<class T >
void Set (const T &value)
sets the value of the column.
template<class T >
void Get (T &out) const
gets the value of the column.
template<class T >
T Get () const
gets the value of the column.
std::string GetForSQL (DatabaseConnection *db) const
gets escaped value of the column.
Static Public Member Functions
static TableColumn * CreateInstanceFromValue (const TableColumnDefinition *colDef, const std::string &value)
factory function to create column from string value.
static TableColumn * CreateInstanceFromValue (const TableColumnDefinition *colDef, const struct tm &value)
factory function to create column from struct tm value.
static TableColumn * CreateInstanceFromValue (const TableColumnDefinition *colDef, const long long &value)
factory function to create column from long long (int) value.
static TableColumn * CreateInstanceFromValue (const TableColumnDefinition *colDef, const double &value)
factory function to create column from double (decimal) value.
template<class T >
static std::vector< TableColumn * > CreateInstancesFromValues (const TableColumnDefinition *colDef, const std::vector< T > &values)
factory function to create multiple columns from a list of values.
template<class T >
static std::vector< const
TableColumn * > CreateConstInstancesFromValues (const TableColumnDefinition *colDef, const std::vector< T > &values)
factory function to create multiple const columns from a list of values.
static TableColumn * CreateInstance (TableColumnDefinition *definition)
factory function to create column from a column definition.
Private Member Functions
TableColumn (const TableColumn &copyCol)
TableColumn (TableColumnDefinition *definition)
void CleanUp ()
void InitFromDefinition ()
Private Attributes
TableColumnValue * columnValue
TableColumnDefinition * columnDefinition
std::string columnAlias
bool isNull
bool isDirty
Detailed Description
implements generic table column.
acts as a base class for all columns.
Definition at line 26 of file TableColumn.h.
Constructor & Destructor Documentation
database::TableColumn::TableColumn (const TableColumn & copyCol) [private]
Definition at line 27 of file TableColumn.cpp.
References THROW_EXCEPTION.
Referenced by CreateInstance().
database::TableColumn::TableColumn (TableColumnDefinition * definition) [private]
Definition at line 19 of file TableColumn.cpp.
database::TableColumn::~TableColumn () [virtual]
Definition at line 32 of file TableColumn.cpp.
References CleanUp().
Member Function Documentation
const std::string & database::TableColumn::GetColumnName () const
gets column name.
Returns:
column name.
Definition at line 148 of file TableColumn.cpp.
References database::TableColumnDefinition::GetColumnName(), and GetConstColumnDefinition().
Referenced by database::UpdateStatement::ToSQL(), and database::WhereConditionTableColumn::ToString().
const TableColumnDefinition * database::TableColumn::GetConstColumnDefinition () const
gets const column definition.
Returns:
column definition.
Definition at line 143 of file TableColumn.cpp.
References columnDefinition.
Referenced by GetColumnName(), database::MySQLTableBase::SetColumnValues(), SetNull(), and database::WhereConditionTableColumn::ToString().
TableColumnDefinition* database::TableColumn::GetColumnDefinition () [inline]
gets column definition.
Returns:
column definition.
Definition at line 52 of file TableColumn.h.
References columnDefinition.
void database::TableColumn::CopyValue (const TableColumn * col)
copy value from another column.
Parameters:
col column to copy from.
Definition at line 193 of file TableColumn.cpp.
References columnDefinition, columnValue, database::DB_TYPE_CHAR, database::DB_TYPE_DOUBLE, database::DB_TYPE_INTEGER, database::DB_TYPE_LARGE_TEXT, database::DB_TYPE_TIMESTAMP, database::DB_TYPE_VARCHAR, Get(), database::TableColumnDefinition::GetColumnType(), IsNull(), database::TableColumnValue::Set(), SetNull(), and THROW_EXCEPTION.
Referenced by database::TableBase::CopyColumns().
bool database::TableColumn::IsDirty () const [inline]
checks if column has changed.
Returns:
false if unchanged, true if changed.
Definition at line 64 of file TableColumn.h.
References isDirty.
Referenced by database::UpdateStatement::ToSQL().
bool database::TableColumn::IsNull () const [inline]
checks if column has NULL value.
Returns:
false if non-NULL, true if NULL.
Definition at line 71 of file TableColumn.h.
References isNull.
Referenced by CopyValue(), htmlparser::DatabaseUrl::InitByTable(), and database::WhereConditionTableColumn::ToString().
void database::TableColumn::SetNull ()
sets columns value to NULL (undefined value).
Definition at line 125 of file TableColumn.cpp.
References GetConstColumnDefinition(), isDirty, isNull, and THROW_EXCEPTION.
Referenced by CopyValue(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), InitFromDefinition(), parser::GenericWebHtmlParserThread::InsertImages(), database::MySQLTableBase::SetColumnValues(), and htmlparser::DatabaseUrl::Store().
void database::TableColumn::SetDirty ()
sets columns value as dirty.
Definition at line 133 of file TableColumn.cpp.
References isDirty.
void database::TableColumn::SetClean ()
sets column value as non-dirty
Definition at line 138 of file TableColumn.cpp.
References isDirty.
Referenced by InitFromDefinition().
void database::TableColumn::SetColumnAlias (const std::string tableAlias) [inline]
sets alias name of column.
Parameters:
tableAlias column name alias.
Definition at line 92 of file TableColumn.h.
References columnAlias.
const std::string& database::TableColumn::GetColumnAlias () const [inline]
gets alias name of column.
Returns:
column name alias.
Definition at line 98 of file TableColumn.h.
References columnAlias.
template<class T > void database::TableColumn::Set (const T & value) [inline]
sets the value of the column.
Parameters:
value new value.
Definition at line 105 of file TableColumn.h.
References columnValue, isDirty, isNull, and database::TableColumnValue::Set().
Referenced by CreateInstanceFromValue(), database::cacheparsedTableBase::Set_action_time(), database::cachesecondleveldomainTableBase::Set_action_time(), database::cachehtmlTableBase::Set_action_time(), database::cacherobotsTableBase::Set_action_time(), database::cachesubdomainTableBase::Set_action_time(), database::cacheurlTableBase::Set_action_time(), database::logmessagesTableBase::Set_actiontime(), database::logmessagesTableBase::Set_appName(), database::documentcodeTableBase::Set_code(), database::urlstagesTableBase::Set_content_length(), database::urlstagesTableBase::Set_content_md5(), database::urlstagesTableBase::Set_content_type(), database::hyperlinksTableBase::Set_count(), database::locksecondleveldomainTableBase::Set_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::customerdomainsTableBase::Set_CUSTOMER_ID(), database::customersessionsTableBase::Set_CUSTOMER_ID(), database::dataminingblacklistTableBase::Set_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Set_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Set_CUSTOMER_ID(), database::fencedsearchTableBase::Set_CUSTOMER_ID(), database::customerqueriesTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Set_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Set_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Set_DICT_ID(), database::docmetaTableBase::Set_DICT_ID(), database::docurlTableBase::Set_DICT_ID(), database::customerproductkeywordsTableBase::Set_DICT_ID(), database::dockeyposTableBase::Set_DOCKEY_ID(), database::secondleveldomainsTableBase::Set_domain(), database::customerdomainsTableBase::Set_domain(), database::dataminingblacklistTableBase::Set_domain(), database::urlstagesTableBase::Set_download_speed(), database::urlstagesTableBase::Set_download_time(), database::urlstagesTableBase::Set_ext_links(), database::imagesTableBase::Set_found_date(), database::urlsTableBase::Set_found_date(), database::urlstagesTableBase::Set_found_date(), database::customermatchcriteriagrouptypeTableBase::Set_groupPosition(), database::urlstagesTableBase::Set_html_errors(), database::hyperlinksTableBase::Set_ID(), database::customerdomainblacklistTableBase::Set_ID(), database::customerproducturlsTableBase::Set_ID(), database::imagelinksTableBase::Set_ID(), database::cachesecondleveldomainTableBase::Set_ID(), database::imagesTableBase::Set_ID(), database::customerqueriesTableBase::Set_ID(), database::customerdomainsTableBase::Set_ID(), database::customersessionsTableBase::Set_ID(), database::keywordqueryTableBase::Set_ID(), database::customersTableBase::Set_ID(), database::latesturlstagesTableBase::Set_ID(), database::logmessagesTableBase::Set_ID(), database::customersynccrawlerTableBase::Set_ID(), database::subdomainsTableBase::Set_ID(), database::customerkeywordsTableBase::Set_ID(), database::matchcriteriaTableBase::Set_ID(), database::customersyncurlTableBase::Set_ID(), database::metainfoTableBase::Set_ID(), database::cachehtmlTableBase::Set_ID(), database::cachesubdomainTableBase::Set_ID(), database::queryresultsTableBase::Set_ID(), database::dataminingalertsTableBase::Set_ID(), database::schemesTableBase::Set_ID(), database::topleveldomainsTableBase::Set_ID(), database::dataminingblacklistTableBase::Set_ID(), database::searchquerykeywordsTableBase::Set_ID(), database::searchqueryTableBase::Set_ID(), database::secondleveldomainsTableBase::Set_ID(), database::dataminingcriteriaalertsTableBase::Set_ID(), database::syncurlsTableBase::Set_ID(), database::cacherobotsTableBase::Set_ID(), database::customermatchcriteriagrouptypeTableBase::Set_ID(), database::dataminingcriteriaTableBase::Set_ID(), database::urlsTableBase::Set_ID(), database::dataminingcustomersessionTableBase::Set_ID(), database::customermatchcriteriaTableBase::Set_ID(), database::dataminingcustomerTableBase::Set_ID(), database::urlstagesTableBase::Set_ID(), database::cacheurlTableBase::Set_ID(), database::dictTableBase::Set_ID(), database::customerproductimagesTableBase::Set_ID(), database::dockeyposTableBase::Set_ID(), database::dockeyTableBase::Set_ID(), database::customerproductkeywordsTableBase::Set_ID(), database::docmetaTableBase::Set_ID(), database::documentcodeTableBase::Set_ID(), database::cacheparsedTableBase::Set_ID(), database::customerproductsTableBase::Set_ID(), database::docurlTableBase::Set_ID(), database::crawlersessionsTableBase::Set_ID(), database::fencedsearchTableBase::Set_ID(), database::imagelinksTableBase::Set_IMAGE_URL_ID(), database::customerproductimagesTableBase::Set_imageUrl(), database::urlstagesTableBase::Set_int_links(), database::customerdomainsTableBase::Set_isDomainRegex(), database::customerkeywordsTableBase::Set_isKeywordRegex(), database::customerdomainblacklistTableBase::Set_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Set_isPrimaryKey(), database::dataminingcriteriaTableBase::Set_keyword(), database::dictTableBase::Set_keyword(), database::customerkeywordsTableBase::Set_keyword(), database::searchquerykeywordsTableBase::Set_KEYWORDQUERY_ID(), database::urlstagesTableBase::Set_last_change(), database::customersTableBase::Set_login(), database::dataminingcustomerTableBase::Set_login(), database::logmessagesTableBase::Set_loglevel(), database::customermatchcriteriaTableBase::Set_MATCHCRITERIA_ID(), database::cacherobotsTableBase::Set_matches(), database::cacheparsedTableBase::Set_matches(), database::cachesecondleveldomainTableBase::Set_matches(), database::cachesubdomainTableBase::Set_matches(), database::cachehtmlTableBase::Set_matches(), database::cacheurlTableBase::Set_matches(), database::logmessagesTableBase::Set_message(), database::cacheparsedTableBase::Set_misses(), database::cachesecondleveldomainTableBase::Set_misses(), database::cachehtmlTableBase::Set_misses(), database::cachesubdomainTableBase::Set_misses(), database::cacheurlTableBase::Set_misses(), database::cacherobotsTableBase::Set_misses(), database::dictTableBase::Set_occurrence(), database::dockeyTableBase::Set_occurrence(), database::docmetaTableBase::Set_occurrence(), database::queryresultsTableBase::Set_order_position(), database::dockeyposTableBase::Set_paragraph(), database::dataminingalertsTableBase::Set_param(), database::customersTableBase::Set_password(), database::dataminingcustomerTableBase::Set_password(), database::customerdomainblacklistTableBase::Set_path(), database::imagesTableBase::Set_path_part(), database::urlsTableBase::Set_path_part(), database::logmessagesTableBase::Set_pid(), database::imagesTableBase::Set_port(), database::urlsTableBase::Set_port(), database::dockeyposTableBase::Set_position(), database::urlstagesTableBase::Set_primary_ip(), database::urlstagesTableBase::Set_primary_port(), database::customerproducturlsTableBase::Set_PRODUCT_ID(), database::customerproductimagesTableBase::Set_PRODUCT_ID(), database::customerproductkeywordsTableBase::Set_PRODUCT_ID(), database::customerproductsTableBase::Set_productBrand(), database::customerproductsTableBase::Set_productName(), database::customerproductsTableBase::Set_productNo(), database::customerqueriesTableBase::Set_query(), database::keywordqueryTableBase::Set_query_part(), database::urlstagesTableBase::Set_redirect_count(), database::matchcriteriaTableBase::Set_regex(), database::urlstagesTableBase::Set_response_code(), database::customerdomainsTableBase::Set_revisitInterval(), database::locksecondleveldomainTableBase::Set_schedule(), database::syncurlsTableBase::Set_schedule(), database::customersyncurlTableBase::Set_scheduled(), database::customersynccrawlerTableBase::Set_scheduled(), database::schemesTableBase::Set_scheme(), database::imagesTableBase::Set_SCHEME_ID(), database::urlsTableBase::Set_SCHEME_ID(), database::imagesTableBase::Set_search_part(), database::urlsTableBase::Set_search_part(), database::queryresultsTableBase::Set_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Set_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Set_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Set_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Set_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Set_session(), database::customersessionsTableBase::Set_session(), database::dataminingcustomersessionTableBase::Set_session(), database::cachesubdomainTableBase::Set_size(), database::cachehtmlTableBase::Set_size(), database::cachesecondleveldomainTableBase::Set_size(), database::cacheurlTableBase::Set_size(), database::cacheparsedTableBase::Set_size(), database::cacherobotsTableBase::Set_size(), database::subdomainsTableBase::Set_subdomain(), database::imagesTableBase::Set_SUBDOMAIN_ID(), database::urlsTableBase::Set_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Set_target(), database::imagelinksTableBase::Set_TARGET_URL_ID(), database::hyperlinksTableBase::Set_TARGET_URL_ID(), database::logmessagesTableBase::Set_threadName(), database::logmessagesTableBase::Set_tid(), database::topleveldomainsTableBase::Set_tld(), database::urlsTableBase::Set_TOPLEVELDOMAIN_ID(), database::imagesTableBase::Set_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Set_type(), database::dataminingcriteriaTableBase::Set_type(), database::metainfoTableBase::Set_type(), database::customermatchcriteriagrouptypeTableBase::Set_type(), database::customermatchcriteriaTableBase::Set_type(), database::docmetaTableBase::Set_type(), database::urlstagesTableBase::Set_upload_speed(), database::customersyncurlTableBase::Set_URL_ID(), database::urlstagesTableBase::Set_URL_ID(), database::syncurlsTableBase::Set_URL_ID(), database::latesturlstagesTableBase::Set_URL_ID(), database::docurlTableBase::Set_URL_ID(), database::customerproducturlsTableBase::Set_URL_ID(), database::queryresultsTableBase::Set_URL_ID(), database::imagesTableBase::Set_url_md5(), database::urlsTableBase::Set_url_md5(), database::documentcodeTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_URLSTAGE_ID(), database::latesturlstagesTableBase::Set_URLSTAGE_ID(), database::hyperlinksTableBase::Set_URLSTAGE_ID(), database::docmetaTableBase::Set_URLSTAGE_ID(), database::dockeyTableBase::Set_URLSTAGE_ID(), database::queryresultsTableBase::Set_URLSTAGE_ID(), database::imagelinksTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_value(), and database::MySQLTableBase::SetColumnValues().
template<class T > void database::TableColumn::Get (T & out) const [inline]
gets the value of the column.
Parameters:
out column value.
Definition at line 117 of file TableColumn.h.
References columnValue, and database::TableColumnValue::Get().
Referenced by CopyValue(), database::cacherobotsTableBase::Get_action_time(), database::cacheurlTableBase::Get_action_time(), database::cachesecondleveldomainTableBase::Get_action_time(), database::cachehtmlTableBase::Get_action_time(), database::cacheparsedTableBase::Get_action_time(), database::cachesubdomainTableBase::Get_action_time(), database::logmessagesTableBase::Get_actiontime(), database::logmessagesTableBase::Get_appName(), database::documentcodeTableBase::Get_code(), database::urlstagesTableBase::Get_content_length(), database::urlstagesTableBase::Get_content_md5(), database::urlstagesTableBase::Get_content_type(), database::hyperlinksTableBase::Get_count(), database::locksecondleveldomainTableBase::Get_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Get_CRAWLERSESSION_ID(), database::syncurlsTableBase::Get_CRAWLERSESSION_ID(), database::fencedsearchTableBase::Get_CUSTOMER_ID(), database::customersessionsTableBase::Get_CUSTOMER_ID(), database::customerdomainsTableBase::Get_CUSTOMER_ID(), database::dataminingblacklistTableBase::Get_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Get_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Get_CUSTOMER_ID(), database::customerproductsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerqueriesTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Get_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Get_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Get_DICT_ID(), database::docmetaTableBase::Get_DICT_ID(), database::docurlTableBase::Get_DICT_ID(), database::customerproductkeywordsTableBase::Get_DICT_ID(), database::dockeyposTableBase::Get_DOCKEY_ID(), database::secondleveldomainsTableBase::Get_domain(), database::customerdomainsTableBase::Get_domain(), database::dataminingblacklistTableBase::Get_domain(), database::urlstagesTableBase::Get_download_speed(), database::urlstagesTableBase::Get_download_time(), database::urlstagesTableBase::Get_ext_links(), database::imagesTableBase::Get_found_date(), database::urlsTableBase::Get_found_date(), database::urlstagesTableBase::Get_found_date(), database::customermatchcriteriagrouptypeTableBase::Get_groupPosition(), database::urlstagesTableBase::Get_html_errors(), database::cachehtmlTableBase::Get_ID(), database::fencedsearchTableBase::Get_ID(), database::customerproductsTableBase::Get_ID(), database::hyperlinksTableBase::Get_ID(), database::crawlersessionsTableBase::Get_ID(), database::customerproducturlsTableBase::Get_ID(), database::imagelinksTableBase::Get_ID(), database::customerdomainblacklistTableBase::Get_ID(), database::imagesTableBase::Get_ID(), database::cacheparsedTableBase::Get_ID(), database::customerqueriesTableBase::Get_ID(), database::customersessionsTableBase::Get_ID(), database::keywordqueryTableBase::Get_ID(), database::cachesecondleveldomainTableBase::Get_ID(), database::latesturlstagesTableBase::Get_ID(), database::customerdomainsTableBase::Get_ID(), database::customersTableBase::Get_ID(), database::logmessagesTableBase::Get_ID(), database::customersynccrawlerTableBase::Get_ID(), database::dockeyposTableBase::Get_ID(), database::matchcriteriaTableBase::Get_ID(), database::customersyncurlTableBase::Get_ID(), database::metainfoTableBase::Get_ID(), database::queryresultsTableBase::Get_ID(), database::customerkeywordsTableBase::Get_ID(), database::dataminingalertsTableBase::Get_ID(), database::schemesTableBase::Get_ID(), database::searchquerykeywordsTableBase::Get_ID(), database::dataminingblacklistTableBase::Get_ID(), database::searchqueryTableBase::Get_ID(), database::secondleveldomainsTableBase::Get_ID(), database::subdomainsTableBase::Get_ID(), database::syncurlsTableBase::Get_ID(), database::dataminingcriteriaalertsTableBase::Get_ID(), database::cachesubdomainTableBase::Get_ID(), database::topleveldomainsTableBase::Get_ID(), database::urlsTableBase::Get_ID(), database::dataminingcriteriaTableBase::Get_ID(), database::dataminingcustomersessionTableBase::Get_ID(), database::customermatchcriteriagrouptypeTableBase::Get_ID(), database::urlstagesTableBase::Get_ID(), database::dataminingcustomerTableBase::Get_ID(), database::dictTableBase::Get_ID(), database::customermatchcriteriaTableBase::Get_ID(), database::cacherobotsTableBase::Get_ID(), database::dockeyTableBase::Get_ID(), database::customerproductimagesTableBase::Get_ID(), database::cacheurlTableBase::Get_ID(), database::docmetaTableBase::Get_ID(), database::documentcodeTableBase::Get_ID(), database::customerproductkeywordsTableBase::Get_ID(), database::docurlTableBase::Get_ID(), database::imagelinksTableBase::Get_IMAGE_URL_ID(), database::customerproductimagesTableBase::Get_imageUrl(), database::urlstagesTableBase::Get_int_links(), database::customerdomainsTableBase::Get_isDomainRegex(), database::customerkeywordsTableBase::Get_isKeywordRegex(), database::customerdomainblacklistTableBase::Get_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Get_isPrimaryKey(), database::dataminingcriteriaTableBase::Get_keyword(), database::dictTableBase::Get_keyword(), database::customerkeywordsTableBase::Get_keyword(), database::searchquerykeywordsTableBase::Get_KEYWORDQUERY_ID(), database::urlstagesTableBase::Get_last_change(), database::customersTableBase::Get_login(), database::dataminingcustomerTableBase::Get_login(), database::logmessagesTableBase::Get_loglevel(), database::customermatchcriteriaTableBase::Get_MATCHCRITERIA_ID(), database::cacherobotsTableBase::Get_matches(), database::cachesecondleveldomainTableBase::Get_matches(), database::cacheparsedTableBase::Get_matches(), database::cachehtmlTableBase::Get_matches(), database::cachesubdomainTableBase::Get_matches(), database::cacheurlTableBase::Get_matches(), database::logmessagesTableBase::Get_message(), database::cacheurlTableBase::Get_misses(), database::cacherobotsTableBase::Get_misses(), database::cachesecondleveldomainTableBase::Get_misses(), database::cachesubdomainTableBase::Get_misses(), database::cacheparsedTableBase::Get_misses(), database::cachehtmlTableBase::Get_misses(), database::dictTableBase::Get_occurrence(), database::dockeyTableBase::Get_occurrence(), database::docmetaTableBase::Get_occurrence(), database::queryresultsTableBase::Get_order_position(), database::dockeyposTableBase::Get_paragraph(), database::dataminingalertsTableBase::Get_param(), database::customersTableBase::Get_password(), database::dataminingcustomerTableBase::Get_password(), database::customerdomainblacklistTableBase::Get_path(), database::imagesTableBase::Get_path_part(), database::urlsTableBase::Get_path_part(), database::logmessagesTableBase::Get_pid(), database::imagesTableBase::Get_port(), database::urlsTableBase::Get_port(), database::dockeyposTableBase::Get_position(), database::urlstagesTableBase::Get_primary_ip(), database::urlstagesTableBase::Get_primary_port(), database::customerproducturlsTableBase::Get_PRODUCT_ID(), database::customerproductimagesTableBase::Get_PRODUCT_ID(), database::customerproductkeywordsTableBase::Get_PRODUCT_ID(), database::customerproductsTableBase::Get_productBrand(), database::customerproductsTableBase::Get_productName(), database::customerproductsTableBase::Get_productNo(), database::customerqueriesTableBase::Get_query(), database::keywordqueryTableBase::Get_query_part(), database::urlstagesTableBase::Get_redirect_count(), database::matchcriteriaTableBase::Get_regex(), database::urlstagesTableBase::Get_response_code(), database::customerdomainsTableBase::Get_revisitInterval(), database::locksecondleveldomainTableBase::Get_schedule(), database::syncurlsTableBase::Get_schedule(), database::customersyncurlTableBase::Get_scheduled(), database::customersynccrawlerTableBase::Get_scheduled(), database::schemesTableBase::Get_scheme(), database::imagesTableBase::Get_SCHEME_ID(), database::urlsTableBase::Get_SCHEME_ID(), database::imagesTableBase::Get_search_part(), database::urlsTableBase::Get_search_part(), database::queryresultsTableBase::Get_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Get_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Get_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Get_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Get_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Get_session(), database::customersessionsTableBase::Get_session(), database::dataminingcustomersessionTableBase::Get_session(), database::cachehtmlTableBase::Get_size(), database::cacherobotsTableBase::Get_size(), database::cachesecondleveldomainTableBase::Get_size(), database::cacheparsedTableBase::Get_size(), database::cacheurlTableBase::Get_size(), database::cachesubdomainTableBase::Get_size(), database::subdomainsTableBase::Get_subdomain(), database::imagesTableBase::Get_SUBDOMAIN_ID(), database::urlsTableBase::Get_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Get_target(), database::imagelinksTableBase::Get_TARGET_URL_ID(), database::hyperlinksTableBase::Get_TARGET_URL_ID(), database::logmessagesTableBase::Get_threadName(), database::logmessagesTableBase::Get_tid(), database::topleveldomainsTableBase::Get_tld(), database::imagesTableBase::Get_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Get_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Get_type(), database::customermatchcriteriagrouptypeTableBase::Get_type(), database::dataminingcriteriaTableBase::Get_type(), database::metainfoTableBase::Get_type(), database::customermatchcriteriaTableBase::Get_type(), database::docmetaTableBase::Get_type(), database::urlstagesTableBase::Get_upload_speed(), database::syncurlsTableBase::Get_URL_ID(), database::urlstagesTableBase::Get_URL_ID(), database::latesturlstagesTableBase::Get_URL_ID(), database::customersyncurlTableBase::Get_URL_ID(), database::queryresultsTableBase::Get_URL_ID(), database::docurlTableBase::Get_URL_ID(), database::customerproducturlsTableBase::Get_URL_ID(), database::urlsTableBase::Get_url_md5(), database::imagesTableBase::Get_url_md5(), database::documentcodeTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_URLSTAGE_ID(), database::hyperlinksTableBase::Get_URLSTAGE_ID(), database::docmetaTableBase::Get_URLSTAGE_ID(), database::dockeyTableBase::Get_URLSTAGE_ID(), database::latesturlstagesTableBase::Get_URLSTAGE_ID(), database::queryresultsTableBase::Get_URLSTAGE_ID(), database::imagelinksTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_value(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), queryserver::XMLQueryResponse::ProcessExistQuery(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
template<class T > T database::TableColumn::Get () const [inline]
gets the value of the column.
Returns:
column value.
Definition at line 127 of file TableColumn.h.
References columnValue, and database::TableColumnValue::Get().
std::string database::TableColumn::GetForSQL (DatabaseConnection * db) const
gets escaped value of the column.
Returns:
column value.
Definition at line 153 of file TableColumn.cpp.
References columnValue, database::TableColumnValue::GetForSQL(), and isNull.
Referenced by database::UpdateStatement::ToSQL(), and database::WhereConditionTableColumn::ToString().
TableColumn * database::TableColumn::CreateInstanceFromValue (const TableColumnDefinition * colDef, const std::string & value) [static]
factory function to create column from string value.
Parameters:
colDef column definition.
value value of column.
Returns:
NULL on error, table column on success.
Definition at line 76 of file TableColumn.cpp.
References CreateInstance(), database::DB_TYPE_CHAR, database::DB_TYPE_LARGE_TEXT, database::DB_TYPE_VARCHAR, database::TableColumnDefinition::GetColumnType(), database::TableColumnDefinition::GetConstCreateParam(), Set(), and THROW_EXCEPTION.
Referenced by CreateInstancesFromValues(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), database::cacheparsedTableBase::GetWhereColumnsFor_action_time(), database::cacherobotsTableBase::GetWhereColumnsFor_action_time(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_action_time(), database::cachehtmlTableBase::GetWhereColumnsFor_action_time(), database::cachesubdomainTableBase::GetWhereColumnsFor_action_time(), database::cacheurlTableBase::GetWhereColumnsFor_action_time(), database::logmessagesTableBase::GetWhereColumnsFor_actiontime(), database::logmessagesTableBase::GetWhereColumnsFor_appName(), database::documentcodeTableBase::GetWhereColumnsFor_code(), database::urlstagesTableBase::GetWhereColumnsFor_content_length(), database::urlstagesTableBase::GetWhereColumnsFor_content_md5(), database::urlstagesTableBase::GetWhereColumnsFor_content_type(), database::hyperlinksTableBase::GetWhereColumnsFor_count(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersessionsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::customerdomainsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::customerqueriesTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetWhereColumnsFor_DICT_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_DICT_ID(), database::dockeyTableBase::GetWhereColumnsFor_DICT_ID(), database::docmetaTableBase::GetWhereColumnsFor_DICT_ID(), database::dockeyposTableBase::GetWhereColumnsFor_DOCKEY_ID(), database::secondleveldomainsTableBase::GetWhereColumnsFor_domain(), database::dataminingblacklistTableBase::GetWhereColumnsFor_domain(), database::customerdomainsTableBase::GetWhereColumnsFor_domain(), database::urlstagesTableBase::GetWhereColumnsFor_download_speed(), database::urlstagesTableBase::GetWhereColumnsFor_download_time(), database::urlstagesTableBase::GetWhereColumnsFor_ext_links(), database::imagesTableBase::GetWhereColumnsFor_found_date(), database::urlsTableBase::GetWhereColumnsFor_found_date(), database::urlstagesTableBase::GetWhereColumnsFor_found_date(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_groupPosition(), database::urlstagesTableBase::GetWhereColumnsFor_html_errors(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::keywordqueryTableBase::GetWhereColumnsFor_ID(), database::matchcriteriaTableBase::GetWhereColumnsFor_ID(), database::schemesTableBase::GetWhereColumnsFor_ID(), database::searchqueryTableBase::GetWhereColumnsFor_ID(), database::secondleveldomainsTableBase::GetWhereColumnsFor_ID(), database::subdomainsTableBase::GetWhereColumnsFor_ID(), database::topleveldomainsTableBase::GetWhereColumnsFor_ID(), database::customersTableBase::GetWhereColumnsFor_ID(), database::dataminingalertsTableBase::GetWhereColumnsFor_ID(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_ID(), database::dataminingcustomerTableBase::GetWhereColumnsFor_ID(), database::dictTableBase::GetWhereColumnsFor_ID(), database::customerqueriesTableBase::GetWhereColumnsFor_ID(), database::customersessionsTableBase::GetWhereColumnsFor_ID(), database::customersyncurlTableBase::GetWhereColumnsFor_ID(), database::dataminingblacklistTableBase::GetWhereColumnsFor_ID(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_ID(), database::customerproductimagesTableBase::GetWhereColumnsFor_ID(), database::documentcodeTableBase::GetWhereColumnsFor_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_ID(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_ID(), database::docurlTableBase::GetWhereColumnsFor_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_ID(), database::dockeyposTableBase::GetWhereColumnsFor_ID(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_ID(), database::metainfoTableBase::GetWhereColumnsFor_ID(), database::hyperlinksTableBase::GetWhereColumnsFor_ID(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_ID(), database::dockeyTableBase::GetWhereColumnsFor_ID(), database::imagelinksTableBase::GetWhereColumnsFor_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_ID(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_ID(), database::cacheurlTableBase::GetWhereColumnsFor_ID(), database::cachehtmlTableBase::GetWhereColumnsFor_ID(), database::cachesubdomainTableBase::GetWhereColumnsFor_ID(), database::cacherobotsTableBase::GetWhereColumnsFor_ID(), database::cacheparsedTableBase::GetWhereColumnsFor_ID(), database::customerdomainsTableBase::GetWhereColumnsFor_ID(), database::queryresultsTableBase::GetWhereColumnsFor_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_ID(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_ID(), database::customerproductsTableBase::GetWhereColumnsFor_ID(), database::syncurlsTableBase::GetWhereColumnsFor_ID(), database::docmetaTableBase::GetWhereColumnsFor_ID(), database::logmessagesTableBase::GetWhereColumnsFor_ID(), database::imagesTableBase::GetWhereColumnsFor_ID(), database::urlsTableBase::GetWhereColumnsFor_ID(), database::urlstagesTableBase::GetWhereColumnsFor_ID(), database::imagelinksTableBase::GetWhereColumnsFor_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetWhereColumnsFor_imageUrl(), database::urlstagesTableBase::GetWhereColumnsFor_int_links(), database::customerdomainsTableBase::GetWhereColumnsFor_isDomainRegex(), database::customerkeywordsTableBase::GetWhereColumnsFor_isKeywordRegex(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_isPrimaryKey(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_keyword(), database::dictTableBase::GetWhereColumnsFor_keyword(), database::customerkeywordsTableBase::GetWhereColumnsFor_keyword(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetWhereColumnsFor_last_change(), database::customersTableBase::GetWhereColumnsFor_login(), database::dataminingcustomerTableBase::GetWhereColumnsFor_login(), database::logmessagesTableBase::GetWhereColumnsFor_loglevel(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_MATCHCRITERIA_ID(), database::cachehtmlTableBase::GetWhereColumnsFor_matches(), database::cacheparsedTableBase::GetWhereColumnsFor_matches(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_matches(), database::cachesubdomainTableBase::GetWhereColumnsFor_matches(), database::cacherobotsTableBase::GetWhereColumnsFor_matches(), database::cacheurlTableBase::GetWhereColumnsFor_matches(), database::logmessagesTableBase::GetWhereColumnsFor_message(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_misses(), database::cacheparsedTableBase::GetWhereColumnsFor_misses(), database::cachesubdomainTableBase::GetWhereColumnsFor_misses(), database::cachehtmlTableBase::GetWhereColumnsFor_misses(), database::cacheurlTableBase::GetWhereColumnsFor_misses(), database::cacherobotsTableBase::GetWhereColumnsFor_misses(), database::dictTableBase::GetWhereColumnsFor_occurrence(), database::dockeyTableBase::GetWhereColumnsFor_occurrence(), database::docmetaTableBase::GetWhereColumnsFor_occurrence(), database::queryresultsTableBase::GetWhereColumnsFor_order_position(), database::dockeyposTableBase::GetWhereColumnsFor_paragraph(), database::dataminingalertsTableBase::GetWhereColumnsFor_param(), database::dataminingcustomerTableBase::GetWhereColumnsFor_password(), database::customersTableBase::GetWhereColumnsFor_password(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_path(), database::imagesTableBase::GetWhereColumnsFor_path_part(), database::urlsTableBase::GetWhereColumnsFor_path_part(), database::logmessagesTableBase::GetWhereColumnsFor_pid(), database::imagesTableBase::GetWhereColumnsFor_port(), database::urlsTableBase::GetWhereColumnsFor_port(), database::dockeyposTableBase::GetWhereColumnsFor_position(), database::urlstagesTableBase::GetWhereColumnsFor_primary_ip(), database::urlstagesTableBase::GetWhereColumnsFor_primary_port(), database::customerproductimagesTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproductsTableBase::GetWhereColumnsFor_productBrand(), database::customerproductsTableBase::GetWhereColumnsFor_productName(), database::customerproductsTableBase::GetWhereColumnsFor_productNo(), database::customerqueriesTableBase::GetWhereColumnsFor_query(), database::keywordqueryTableBase::GetWhereColumnsFor_query_part(), database::urlstagesTableBase::GetWhereColumnsFor_redirect_count(), database::matchcriteriaTableBase::GetWhereColumnsFor_regex(), database::urlstagesTableBase::GetWhereColumnsFor_response_code(), database::customerdomainsTableBase::GetWhereColumnsFor_revisitInterval(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_schedule(), database::syncurlsTableBase::GetWhereColumnsFor_schedule(), database::customersyncurlTableBase::GetWhereColumnsFor_scheduled(), database::customersynccrawlerTableBase::GetWhereColumnsFor_scheduled(), database::schemesTableBase::GetWhereColumnsFor_scheme(), database::urlsTableBase::GetWhereColumnsFor_SCHEME_ID(), database::imagesTableBase::GetWhereColumnsFor_SCHEME_ID(), database::imagesTableBase::GetWhereColumnsFor_search_part(), database::urlsTableBase::GetWhereColumnsFor_search_part(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::queryresultsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetWhereColumnsFor_session(), database::customersessionsTableBase::GetWhereColumnsFor_session(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_session(), database::cacheparsedTableBase::GetWhereColumnsFor_size(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_size(), database::cachesubdomainTableBase::GetWhereColumnsFor_size(), database::cachehtmlTableBase::GetWhereColumnsFor_size(), database::cacheurlTableBase::GetWhereColumnsFor_size(), database::cacherobotsTableBase::GetWhereColumnsFor_size(), database::subdomainsTableBase::GetWhereColumnsFor_subdomain(), database::imagesTableBase::GetWhereColumnsFor_SUBDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_target(), database::hyperlinksTableBase::GetWhereColumnsFor_TARGET_URL_ID(), database::imagelinksTableBase::GetWhereColumnsFor_TARGET_URL_ID(), database::logmessagesTableBase::GetWhereColumnsFor_threadName(), database::logmessagesTableBase::GetWhereColumnsFor_tid(), database::topleveldomainsTableBase::GetWhereColumnsFor_tld(), database::imagesTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetWhereColumnsFor_type(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_type(), database::metainfoTableBase::GetWhereColumnsFor_type(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_type(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_type(), database::docmetaTableBase::GetWhereColumnsFor_type(), database::urlstagesTableBase::GetWhereColumnsFor_upload_speed(), database::customersyncurlTableBase::GetWhereColumnsFor_URL_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::docurlTableBase::GetWhereColumnsFor_URL_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_URL_ID(), database::syncurlsTableBase::GetWhereColumnsFor_URL_ID(), database::queryresultsTableBase::GetWhereColumnsFor_URL_ID(), database::urlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::imagesTableBase::GetWhereColumnsFor_url_md5(), database::urlsTableBase::GetWhereColumnsFor_url_md5(), database::documentcodeTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::metainfoTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::hyperlinksTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::dockeyTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::imagelinksTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::docmetaTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::queryresultsTableBase::GetWhereColumnsFor_URLSTAGE_ID(), and database::metainfoTableBase::GetWhereColumnsFor_value().
TableColumn * database::TableColumn::CreateInstanceFromValue (const TableColumnDefinition * colDef, const struct tm & value) [static]
factory function to create column from struct tm value.
Parameters:
colDef column definition.
value value of column.
Returns:
NULL on error, table column on success.
Definition at line 89 of file TableColumn.cpp.
References CreateInstance(), database::DB_TYPE_TIMESTAMP, database::TableColumnDefinition::GetColumnType(), database::TableColumnDefinition::GetConstCreateParam(), Set(), and THROW_EXCEPTION.
TableColumn * database::TableColumn::CreateInstanceFromValue (const TableColumnDefinition * colDef, const long long & value) [static]
factory function to create column from long long (int) value.
Parameters:
colDef column definition.
value value of column.
Returns:
NULL on error, table column on success.
Definition at line 101 of file TableColumn.cpp.
References CreateInstance(), database::DB_TYPE_INTEGER, database::TableColumnDefinition::GetColumnType(), database::TableColumnDefinition::GetConstCreateParam(), Set(), and THROW_EXCEPTION.
TableColumn * database::TableColumn::CreateInstanceFromValue (const TableColumnDefinition * colDef, const double & value) [static]
factory function to create column from double (decimal) value.
Parameters:
colDef column definition.
value value of column.
Returns:
NULL on error, table column on success.
Definition at line 113 of file TableColumn.cpp.
References CreateInstance(), database::DB_TYPE_DOUBLE, database::TableColumnDefinition::GetColumnType(), database::TableColumnDefinition::GetConstCreateParam(), Set(), and THROW_EXCEPTION.
template<class T > static std::vector<TableColumn*> database::TableColumn::CreateInstancesFromValues (const TableColumnDefinition * colDef, const std::vector< T > & values) [inline, static]
factory function to create multiple columns from a list of values.
Parameters:
colDef column definition.
values list of new column values.
Returns:
list of created columns.
Definition at line 180 of file TableColumn.h.
References CreateInstanceFromValue().
Referenced by CreateConstInstancesFromValues(), database::cacheparsedTableBase::GetWhereColumnsFor_action_time(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_action_time(), database::cachehtmlTableBase::GetWhereColumnsFor_action_time(), database::cacherobotsTableBase::GetWhereColumnsFor_action_time(), database::cachesubdomainTableBase::GetWhereColumnsFor_action_time(), database::cacheurlTableBase::GetWhereColumnsFor_action_time(), database::logmessagesTableBase::GetWhereColumnsFor_actiontime(), database::logmessagesTableBase::GetWhereColumnsFor_appName(), database::documentcodeTableBase::GetWhereColumnsFor_code(), database::urlstagesTableBase::GetWhereColumnsFor_content_length(), database::urlstagesTableBase::GetWhereColumnsFor_content_md5(), database::urlstagesTableBase::GetWhereColumnsFor_content_type(), database::hyperlinksTableBase::GetWhereColumnsFor_count(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersessionsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::customerdomainsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::customerqueriesTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetWhereColumnsFor_DICT_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_DICT_ID(), database::dockeyTableBase::GetWhereColumnsFor_DICT_ID(), database::docmetaTableBase::GetWhereColumnsFor_DICT_ID(), database::dockeyposTableBase::GetWhereColumnsFor_DOCKEY_ID(), database::secondleveldomainsTableBase::GetWhereColumnsFor_domain(), database::dataminingblacklistTableBase::GetWhereColumnsFor_domain(), database::customerdomainsTableBase::GetWhereColumnsFor_domain(), database::urlstagesTableBase::GetWhereColumnsFor_download_speed(), database::urlstagesTableBase::GetWhereColumnsFor_download_time(), database::urlstagesTableBase::GetWhereColumnsFor_ext_links(), database::imagesTableBase::GetWhereColumnsFor_found_date(), database::urlsTableBase::GetWhereColumnsFor_found_date(), database::urlstagesTableBase::GetWhereColumnsFor_found_date(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_groupPosition(), database::urlstagesTableBase::GetWhereColumnsFor_html_errors(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::keywordqueryTableBase::GetWhereColumnsFor_ID(), database::matchcriteriaTableBase::GetWhereColumnsFor_ID(), database::schemesTableBase::GetWhereColumnsFor_ID(), database::searchqueryTableBase::GetWhereColumnsFor_ID(), database::secondleveldomainsTableBase::GetWhereColumnsFor_ID(), database::subdomainsTableBase::GetWhereColumnsFor_ID(), database::topleveldomainsTableBase::GetWhereColumnsFor_ID(), database::customersTableBase::GetWhereColumnsFor_ID(), database::dataminingalertsTableBase::GetWhereColumnsFor_ID(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_ID(), database::dataminingcustomerTableBase::GetWhereColumnsFor_ID(), database::dictTableBase::GetWhereColumnsFor_ID(), database::customerqueriesTableBase::GetWhereColumnsFor_ID(), database::customersessionsTableBase::GetWhereColumnsFor_ID(), database::customersyncurlTableBase::GetWhereColumnsFor_ID(), database::dataminingblacklistTableBase::GetWhereColumnsFor_ID(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_ID(), database::customerproductimagesTableBase::GetWhereColumnsFor_ID(), database::documentcodeTableBase::GetWhereColumnsFor_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_ID(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_ID(), database::docurlTableBase::GetWhereColumnsFor_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_ID(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_ID(), database::metainfoTableBase::GetWhereColumnsFor_ID(), database::dockeyposTableBase::GetWhereColumnsFor_ID(), database::hyperlinksTableBase::GetWhereColumnsFor_ID(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_ID(), database::dockeyTableBase::GetWhereColumnsFor_ID(), database::imagelinksTableBase::GetWhereColumnsFor_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_ID(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_ID(), database::cachehtmlTableBase::GetWhereColumnsFor_ID(), database::cachesubdomainTableBase::GetWhereColumnsFor_ID(), database::cacherobotsTableBase::GetWhereColumnsFor_ID(), database::cacheurlTableBase::GetWhereColumnsFor_ID(), database::cacheparsedTableBase::GetWhereColumnsFor_ID(), database::customerdomainsTableBase::GetWhereColumnsFor_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_ID(), database::queryresultsTableBase::GetWhereColumnsFor_ID(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_ID(), database::customerproductsTableBase::GetWhereColumnsFor_ID(), database::syncurlsTableBase::GetWhereColumnsFor_ID(), database::docmetaTableBase::GetWhereColumnsFor_ID(), database::logmessagesTableBase::GetWhereColumnsFor_ID(), database::imagesTableBase::GetWhereColumnsFor_ID(), database::urlsTableBase::GetWhereColumnsFor_ID(), database::urlstagesTableBase::GetWhereColumnsFor_ID(), database::imagelinksTableBase::GetWhereColumnsFor_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetWhereColumnsFor_imageUrl(), database::urlstagesTableBase::GetWhereColumnsFor_int_links(), database::customerdomainsTableBase::GetWhereColumnsFor_isDomainRegex(), database::customerkeywordsTableBase::GetWhereColumnsFor_isKeywordRegex(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_isPrimaryKey(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_keyword(), database::dictTableBase::GetWhereColumnsFor_keyword(), database::customerkeywordsTableBase::GetWhereColumnsFor_keyword(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetWhereColumnsFor_last_change(), database::customersTableBase::GetWhereColumnsFor_login(), database::dataminingcustomerTableBase::GetWhereColumnsFor_login(), database::logmessagesTableBase::GetWhereColumnsFor_loglevel(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_MATCHCRITERIA_ID(), database::cacheparsedTableBase::GetWhereColumnsFor_matches(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_matches(), database::cachehtmlTableBase::GetWhereColumnsFor_matches(), database::cacherobotsTableBase::GetWhereColumnsFor_matches(), database::cachesubdomainTableBase::GetWhereColumnsFor_matches(), database::cacheurlTableBase::GetWhereColumnsFor_matches(), database::logmessagesTableBase::GetWhereColumnsFor_message(), database::cacheparsedTableBase::GetWhereColumnsFor_misses(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_misses(), database::cachesubdomainTableBase::GetWhereColumnsFor_misses(), database::cachehtmlTableBase::GetWhereColumnsFor_misses(), database::cacheurlTableBase::GetWhereColumnsFor_misses(), database::cacherobotsTableBase::GetWhereColumnsFor_misses(), database::dictTableBase::GetWhereColumnsFor_occurrence(), database::dockeyTableBase::GetWhereColumnsFor_occurrence(), database::docmetaTableBase::GetWhereColumnsFor_occurrence(), database::queryresultsTableBase::GetWhereColumnsFor_order_position(), database::dockeyposTableBase::GetWhereColumnsFor_paragraph(), database::dataminingalertsTableBase::GetWhereColumnsFor_param(), database::customersTableBase::GetWhereColumnsFor_password(), database::dataminingcustomerTableBase::GetWhereColumnsFor_password(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_path(), database::imagesTableBase::GetWhereColumnsFor_path_part(), database::urlsTableBase::GetWhereColumnsFor_path_part(), database::logmessagesTableBase::GetWhereColumnsFor_pid(), database::urlsTableBase::GetWhereColumnsFor_port(), database::imagesTableBase::GetWhereColumnsFor_port(), database::dockeyposTableBase::GetWhereColumnsFor_position(), database::urlstagesTableBase::GetWhereColumnsFor_primary_ip(), database::urlstagesTableBase::GetWhereColumnsFor_primary_port(), database::customerproductimagesTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproductsTableBase::GetWhereColumnsFor_productBrand(), database::customerproductsTableBase::GetWhereColumnsFor_productName(), database::customerproductsTableBase::GetWhereColumnsFor_productNo(), database::customerqueriesTableBase::GetWhereColumnsFor_query(), database::keywordqueryTableBase::GetWhereColumnsFor_query_part(), database::urlstagesTableBase::GetWhereColumnsFor_redirect_count(), database::matchcriteriaTableBase::GetWhereColumnsFor_regex(), database::urlstagesTableBase::GetWhereColumnsFor_response_code(), database::customerdomainsTableBase::GetWhereColumnsFor_revisitInterval(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_schedule(), database::syncurlsTableBase::GetWhereColumnsFor_schedule(), database::customersyncurlTableBase::GetWhereColumnsFor_scheduled(), database::customersynccrawlerTableBase::GetWhereColumnsFor_scheduled(), database::schemesTableBase::GetWhereColumnsFor_scheme(), database::imagesTableBase::GetWhereColumnsFor_SCHEME_ID(), database::urlsTableBase::GetWhereColumnsFor_SCHEME_ID(), database::urlsTableBase::GetWhereColumnsFor_search_part(), database::imagesTableBase::GetWhereColumnsFor_search_part(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::queryresultsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetWhereColumnsFor_session(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_session(), database::customersessionsTableBase::GetWhereColumnsFor_session(), database::cacheurlTableBase::GetWhereColumnsFor_size(), database::cachesubdomainTableBase::GetWhereColumnsFor_size(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_size(), database::cachehtmlTableBase::GetWhereColumnsFor_size(), database::cacheparsedTableBase::GetWhereColumnsFor_size(), database::cacherobotsTableBase::GetWhereColumnsFor_size(), database::subdomainsTableBase::GetWhereColumnsFor_subdomain(), database::urlsTableBase::GetWhereColumnsFor_SUBDOMAIN_ID(), database::imagesTableBase::GetWhereColumnsFor_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_target(), database::hyperlinksTableBase::GetWhereColumnsFor_TARGET_URL_ID(), database::imagelinksTableBase::GetWhereColumnsFor_TARGET_URL_ID(), database::logmessagesTableBase::GetWhereColumnsFor_threadName(), database::logmessagesTableBase::GetWhereColumnsFor_tid(), database::topleveldomainsTableBase::GetWhereColumnsFor_tld(), database::imagesTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetWhereColumnsFor_type(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_type(), database::metainfoTableBase::GetWhereColumnsFor_type(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_type(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_type(), database::docmetaTableBase::GetWhereColumnsFor_type(), database::urlstagesTableBase::GetWhereColumnsFor_upload_speed(), database::customersyncurlTableBase::GetWhereColumnsFor_URL_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::docurlTableBase::GetWhereColumnsFor_URL_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_URL_ID(), database::syncurlsTableBase::GetWhereColumnsFor_URL_ID(), database::queryresultsTableBase::GetWhereColumnsFor_URL_ID(), database::urlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::imagesTableBase::GetWhereColumnsFor_url_md5(), database::urlsTableBase::GetWhereColumnsFor_url_md5(), database::documentcodeTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::metainfoTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::dockeyTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::hyperlinksTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::imagelinksTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::docmetaTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::queryresultsTableBase::GetWhereColumnsFor_URLSTAGE_ID(), and database::metainfoTableBase::GetWhereColumnsFor_value().
template<class T > static std::vector<const TableColumn*> database::TableColumn::CreateConstInstancesFromValues (const TableColumnDefinition * colDef, const std::vector< T > & values) [inline, static]
factory function to create multiple const columns from a list of values.
Parameters:
colDef column definition.
values list of new column values.
Returns:
list of created columns.
Definition at line 196 of file TableColumn.h.
References CreateInstancesFromValues(), and tools::ContainerTools::ToConstVector().
TableColumn * database::TableColumn::CreateInstance (TableColumnDefinition * definition) [static]
factory function to create column from a column definition.
Parameters:
definition column definition.
Returns:
NULL on error, table column on success.
Definition at line 69 of file TableColumn.cpp.
References InitFromDefinition(), and TableColumn().
Referenced by database::TableBase::CreateColumns(), and CreateInstanceFromValue().
void database::TableColumn::CleanUp () [private]
Definition at line 36 of file TableColumn.cpp.
References columnDefinition, columnValue, database::DB_TYPE_CHAR, database::DB_TYPE_DOUBLE, database::DB_TYPE_INTEGER, database::DB_TYPE_LARGE_TEXT, database::DB_TYPE_TIMESTAMP, database::DB_TYPE_VARCHAR, database::TableColumnDefinition::GetColumnType(), and THROW_EXCEPTION.
Referenced by ~TableColumn().
void database::TableColumn::InitFromDefinition () [private]
Definition at line 160 of file TableColumn.cpp.
References columnDefinition, columnValue, database::DB_TYPE_CHAR, database::DB_TYPE_DOUBLE, database::DB_TYPE_INTEGER, database::DB_TYPE_LARGE_TEXT, database::DB_TYPE_TIMESTAMP, database::DB_TYPE_VARCHAR, database::TableColumnDefinition::GetColumnType(), database::TableColumnDefinition::IsAutoGenerated(), SetClean(), SetNull(), and THROW_EXCEPTION.
Referenced by CreateInstance().
Member Data Documentation
TableColumnValue* database::TableColumn::columnValue [private]
Definition at line 215 of file TableColumn.h.
Referenced by CleanUp(), CopyValue(), Get(), GetForSQL(), InitFromDefinition(), and Set().
TableColumnDefinition* database::TableColumn::columnDefinition [private]
Definition at line 216 of file TableColumn.h.
Referenced by CleanUp(), CopyValue(), GetColumnDefinition(), GetConstColumnDefinition(), and InitFromDefinition().
std::string database::TableColumn::columnAlias [private]
Definition at line 217 of file TableColumn.h.
Referenced by GetColumnAlias(), and SetColumnAlias().
bool database::TableColumn::isNull [private]
Definition at line 218 of file TableColumn.h.
Referenced by GetForSQL(), IsNull(), Set(), and SetNull().
bool database::TableColumn::isDirty [private]
Definition at line 219 of file TableColumn.h.
Referenced by IsDirty(), Set(), SetClean(), SetDirty(), and SetNull().
The documentation for this class was generated from the following files:
Database/src/TableColumn.h
Database/src/TableColumn.cpp