DeepNet: toolbot::UnitTestManager Class Reference
toolbot::UnitTestManager Class Reference
#include <UnitTestManager.h>
Public Member Functions
UnitTestManager ()
virtual ~UnitTestManager ()
void AddUnitTest (toolbot::UnitTest *unitTest)
bool Run ()
Private Member Functions
void Cleanup ()
Private Attributes
std::vector< toolbot::UnitTest * > tests
std::vector< toolbot::UnitTest * > successTests
std::vector< toolbot::UnitTest * > errorTests
Detailed Description
Definition at line 16 of file UnitTestManager.h.
Constructor & Destructor Documentation
toolbot::UnitTestManager::UnitTestManager ()
Definition at line 16 of file UnitTestManager.cpp.
toolbot::UnitTestManager::~UnitTestManager () [virtual]
Definition at line 19 of file UnitTestManager.cpp.
References Cleanup().
Member Function Documentation
void toolbot::UnitTestManager::AddUnitTest (toolbot::UnitTest * unitTest)
Definition at line 23 of file UnitTestManager.cpp.
References tests.
Referenced by toolbot::DeepNetToolBot::ProcessUnitTests().
bool toolbot::UnitTestManager::Run ()
Definition at line 27 of file UnitTestManager.cpp.
References errorTests, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, successTests, and tests.
Referenced by toolbot::DeepNetToolBot::ProcessUnitTests().
void toolbot::UnitTestManager::Cleanup () [private]
Definition at line 46 of file UnitTestManager.cpp.
References errorTests, successTests, and tests.
Referenced by ~UnitTestManager().
Member Data Documentation
std::vector<toolbot::UnitTest*> toolbot::UnitTestManager::tests [private]
Definition at line 28 of file UnitTestManager.h.
Referenced by AddUnitTest(), Cleanup(), and Run().
std::vector<toolbot::UnitTest*> toolbot::UnitTestManager::successTests [private]
Definition at line 29 of file UnitTestManager.h.
Referenced by Cleanup(), and Run().
std::vector<toolbot::UnitTest*> toolbot::UnitTestManager::errorTests [private]
Definition at line 30 of file UnitTestManager.h.
Referenced by Cleanup(), and Run().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestManager.h
DeepNetTool/src/UnitTestManager.cpp