DeepNet: tools::ContainerTools Class Reference
tools::ContainerTools Class Reference
wrapper class to deal with stl types
#include <ContainerTools.h>
Classes
struct DumpMapFunc
struct DumpVecFunc
struct List2ToVectorFunc
struct Map1ToVectorFunc
struct Map2ToVectorFunc
struct VectorPair1ToVectorFunc
struct VectorPair2ToVectorFunc
Static Public Member Functions
template<class T >
static void MakeUniqueVector (std::vector< T > &toUnique, bool sort=false)
removes duplicate entries from toUnique.
template<class T >
static void MakeUniqueVector (const std::vector< T > &in, std::vector< T > &unique, bool sort=false)
removes duplicate entries from in and copies them to unique.
template<class T >
static void ListToVector (const std::list< T > &in, std::vector< T > &out)
converts std::list to std::vector
template<class T , class V >
static void Map1ToVector (const std::map< T, V > mapIn, std::vector< T > &vecOut)
converts first entry(key) of std::map to std::vector
template<class T , class V >
static void Map2ToVector (const std::map< T, V > mapIn, std::vector< V > &vecOut)
converts second entry(value) of std::map to std::vector
template<class T , class V >
static void VectorPair1ToVector (const std::vector< std::pair< T, V > > &vecIn, std::vector< T > &vecOut)
converts first entry(value) of std::vector< std::pair<> > to std::vector
template<class T , class V >
static void VectorPair2ToVector (const std::vector< std::pair< T, V > > &vecIn, std::vector< V > &vecOut)
converts second entry(value) of std::vector< std::pair<> > to std::vector
template<class T >
static void ToConstVector (const std::vector< T > &vecIn, std::vector< const T > &vecOut)
creates a vector of const entries from another vector.
template<class T >
static void ToConstVector (const std::vector< T * > &vecIn, std::vector< const T * > &vecOut)
creates a vector of const pointers from another vector of pointers.
template<class T >
static void ToNonConstVector (const std::vector< const T > &vecIn, std::vector< T > &vecOut)
creates a vector of non-const entries from another vector.
template<class T >
static void ToNonConstVector (const std::vector< const T * > &vecIn, std::vector< T * > &vecOut)
creates a vector of non-const pointers from another vector of pointers.
template<class T >
static bool CompareVector (const std::vector< T > &comp1, const std::vector< T > &comp2)
compares entries of two vectors.
template<class T >
static void DumpVector (const std::vector< T > &in, std::string &dump)
dumps contents of vector as a string
template<class T , class V >
static void DumpMap (const std::map< T, V > &in, std::string &dump)
dumps contents of map as a string
Private Member Functions
ContainerTools ()
virtual ~ContainerTools ()
Detailed Description
wrapper class to deal with stl types
Definition at line 21 of file ContainerTools.h.
Constructor & Destructor Documentation
tools::ContainerTools::ContainerTools () [private]
Definition at line 11 of file ContainerTools.cpp.
tools::ContainerTools::~ContainerTools () [private, virtual]
Definition at line 14 of file ContainerTools.cpp.
Member Function Documentation
template<class T > static void tools::ContainerTools::MakeUniqueVector (std::vector< T > & toUnique, bool sort = false) [inline, static]
removes duplicate entries from toUnique.
Parameters:
toUnique vector to make unique.
sort true if output should be sorted, false if not.
Definition at line 33 of file ContainerTools.h.
Referenced by parser::GenericWebHtmlParserThread::ParsePage().
template<class T > static void tools::ContainerTools::MakeUniqueVector (const std::vector< T > & in, std::vector< T > & unique, bool sort = false) [inline, static]
removes duplicate entries from in and copies them to unique.
Parameters:
in vector to make unique.
unique vector containing unique items.
sort true if output should be sorted, false if not.
Definition at line 44 of file ContainerTools.h.
template<class T > static void tools::ContainerTools::ListToVector (const std::list< T > & in, std::vector< T > & out) [inline, static]
converts std::list to std::vector
Parameters:
in list to be converted.
out converted vector.
Definition at line 77 of file ContainerTools.h.
Referenced by queryserver::XMLQueryResponse::Process().
template<class T , class V > static void tools::ContainerTools::Map1ToVector (const std::map< T, V > mapIn, std::vector< T > & vecOut) [inline, static]
converts first entry(key) of std::map to std::vector
Parameters:
mapIn map to be converted.
vecOut converted vector.
Definition at line 88 of file ContainerTools.h.
Referenced by queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), htmlparser::TLD::GetTLDStrings(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), and crawler::GenericWebUrlFetcherThread::ReserveNextUrls().
template<class T , class V > static void tools::ContainerTools::Map2ToVector (const std::map< T, V > mapIn, std::vector< V > & vecOut) [inline, static]
converts second entry(value) of std::map to std::vector
Parameters:
mapIn map to be converted.
vecOut converted vector.
Definition at line 99 of file ContainerTools.h.
Referenced by queryserver::XMLQueryResponse::GetPageRelevanceByBacklinks(), queryserver::XMLQueryResponse::GetPagesByDomain(), and queryserver::XMLQueryResponse::ProcessExistQuery().
template<class T , class V > static void tools::ContainerTools::VectorPair1ToVector (const std::vector< std::pair< T, V > > & vecIn, std::vector< T > & vecOut) [inline, static]
converts first entry(value) of std::vector< std::pair<> > to std::vector
Parameters:
vecIn vector to be converted.
vecOut converted vector.
Definition at line 110 of file ContainerTools.h.
template<class T , class V > static void tools::ContainerTools::VectorPair2ToVector (const std::vector< std::pair< T, V > > & vecIn, std::vector< V > & vecOut) [inline, static]
converts second entry(value) of std::vector< std::pair<> > to std::vector
Parameters:
vecIn vector to be converted.
vecOut converted vector.
Definition at line 121 of file ContainerTools.h.
Referenced by parser::GenericWebHtmlParserThread::ParsePage().
template<class T > static void tools::ContainerTools::ToConstVector (const std::vector< T > & vecIn, std::vector< const T > & vecOut) [inline, static]
creates a vector of const entries from another vector.
Parameters:
vecIn vector to be converted.
vecOut converted vector.
Definition at line 132 of file ContainerTools.h.
Referenced by database::TableColumn::CreateConstInstancesFromValues().
template<class T > static void tools::ContainerTools::ToConstVector (const std::vector< T * > & vecIn, std::vector< const T * > & vecOut) [inline, static]
creates a vector of const pointers from another vector of pointers.
Parameters:
vecIn vector to be converted.
vecOut converted vector.
Definition at line 144 of file ContainerTools.h.
template<class T > static void tools::ContainerTools::ToNonConstVector (const std::vector< const T > & vecIn, std::vector< T > & vecOut) [inline, static]
creates a vector of non-const entries from another vector.
Parameters:
vecIn vector to be converted.
vecOut converted vector.
Definition at line 156 of file ContainerTools.h.
template<class T > static void tools::ContainerTools::ToNonConstVector (const std::vector< const T * > & vecIn, std::vector< T * > & vecOut) [inline, static]
creates a vector of non-const pointers from another vector of pointers.
Parameters:
vecIn vector to be converted.
vecOut converted vector.
Definition at line 168 of file ContainerTools.h.
template<class T > static bool tools::ContainerTools::CompareVector (const std::vector< T > & comp1, const std::vector< T > & comp2) [inline, static]
compares entries of two vectors.
Parameters:
comp1 vector to compare.
comp2 vector to compare.
Returns:
true if identical, false if different.
Definition at line 181 of file ContainerTools.h.
Referenced by toolbot::UnitTestPCRERegex::Run().
template<class T > static void tools::ContainerTools::DumpVector (const std::vector< T > & in, std::string & dump) [inline, static]
dumps contents of vector as a string
Parameters:
in vector to be dumped.
dump string containing dumped vector.
Definition at line 201 of file ContainerTools.h.
Referenced by toolbot::UnitTestPCRERegex::OnError().
template<class T , class V > static void tools::ContainerTools::DumpMap (const std::map< T, V > & in, std::string & dump) [inline, static]
dumps contents of map as a string
Parameters:
in map to be dumped.
dump string containing dumped map.
Definition at line 214 of file ContainerTools.h.
The documentation for this class was generated from the following files:
Tools/src/ContainerTools.h
Tools/src/ContainerTools.cpp