DeepNet: crawler::CrawlerFactory Class Reference
crawler::CrawlerFactory Class Reference
#include <CrawlerFactory.h>
Public Member Functions
virtual ~CrawlerFactory ()
Static Public Member Functions
static Crawler * CreateCommerceSearchCrawler (const CrawlerParam *crawlerParam)
static Crawler * CreateDataminingCrawler (const CrawlerParam *crawlerParam)
static Crawler * CreateGenericWebCrawler (const CrawlerParam *crawlerParam)
static Crawler * CreateFencedCrawler (const CrawlerParam *crawlerParam)
Private Member Functions
CrawlerFactory ()
Detailed Description
Definition at line 16 of file CrawlerFactory.h.
Constructor & Destructor Documentation
crawler::CrawlerFactory::CrawlerFactory () [private]
Definition at line 18 of file CrawlerFactory.cpp.
crawler::CrawlerFactory::~CrawlerFactory () [virtual]
Definition at line 21 of file CrawlerFactory.cpp.
Member Function Documentation
Crawler * crawler::CrawlerFactory::CreateCommerceSearchCrawler (const CrawlerParam * crawlerParam) [static]
Definition at line 28 of file CrawlerFactory.cpp.
Referenced by workerbot::WorkerBot::InitModeConfig().
Crawler * crawler::CrawlerFactory::CreateDataminingCrawler (const CrawlerParam * crawlerParam) [static]
Definition at line 32 of file CrawlerFactory.cpp.
Referenced by workerbot::WorkerBot::InitModeConfig().
Crawler * crawler::CrawlerFactory::CreateGenericWebCrawler (const CrawlerParam * crawlerParam) [static]
Definition at line 36 of file CrawlerFactory.cpp.
Referenced by workerbot::WorkerBot::InitModeConfig().
Crawler * crawler::CrawlerFactory::CreateFencedCrawler (const CrawlerParam * crawlerParam) [static]
Definition at line 24 of file CrawlerFactory.cpp.
Referenced by workerbot::WorkerBot::InitModeConfig().
The documentation for this class was generated from the following files:
Crawler/src/CrawlerFactory.h
Crawler/src/CrawlerFactory.cpp