DeepNet: queryserver::XMLQueryRequest::QueryRequestParam Class Reference
queryserver::XMLQueryRequest::QueryRequestParam Class Reference
#include <XMLQueryRequest.h>
Public Member Functions
QueryRequestParam ()
const unsigned long long & CriteriaFlag () const
const unsigned long long & GroupingFlag () const
const unsigned long long & LimitFlag () const
const size_t PageNumber () const
const int & MaxResults () const
const long long QueryID () const
const double & MetaRelevance () const
const double & TitleRelevance () const
const double & DomainRelevance () const
const double & ContentRelevance () const
const double & BackLinkRelevance () const
const double & UrlPathRelevance () const
Public Attributes
std::list< std::string > queryParts
unsigned long long criteriaFlag
unsigned long long groupFlag
unsigned long long limitFlag
double relevanceMeta
double relevanceTitle
double relevanceDomain
double relevanceFullText
double relevanceBackLinks
double relevanceUrlPath
size_t pageNo
int maxResults
std::string limitDomain
std::string limitAge
std::string limitLang
long long queryID
Detailed Description
Definition at line 55 of file XMLQueryRequest.h.
Constructor & Destructor Documentation
queryserver::XMLQueryRequest::QueryRequestParam::QueryRequestParam () [inline]
Definition at line 58 of file XMLQueryRequest.h.
Member Function Documentation
const unsigned long long& queryserver::XMLQueryRequest::QueryRequestParam::CriteriaFlag () const [inline]
Definition at line 75 of file XMLQueryRequest.h.
References criteriaFlag.
Referenced by queryserver::XMLQueryResponse::GetPagesByMeta(), and queryserver::XMLQueryResponse::GetResultsFromDatasources().
const unsigned long long& queryserver::XMLQueryRequest::QueryRequestParam::GroupingFlag () const [inline]
Definition at line 76 of file XMLQueryRequest.h.
References groupFlag.
Referenced by queryserver::XMLQueryResponse::GroupResults().
const unsigned long long& queryserver::XMLQueryRequest::QueryRequestParam::LimitFlag () const [inline]
Definition at line 77 of file XMLQueryRequest.h.
References limitFlag.
const size_t queryserver::XMLQueryRequest::QueryRequestParam::PageNumber () const [inline]
Definition at line 78 of file XMLQueryRequest.h.
References pageNo.
Referenced by queryserver::XMLQueryResponse::OutputResults(), and queryserver::XMLQueryResponse::ProcessExistQuery().
const int& queryserver::XMLQueryRequest::QueryRequestParam::MaxResults () const [inline]
Definition at line 79 of file XMLQueryRequest.h.
References maxResults.
Referenced by queryserver::XMLQueryResponse::ProcessExistQuery().
const long long queryserver::XMLQueryRequest::QueryRequestParam::QueryID () const [inline]
Definition at line 81 of file XMLQueryRequest.h.
References queryID.
Referenced by queryserver::XMLQueryResponse::LogQuery(), queryserver::XMLQueryResponse::OutputResults(), queryserver::XMLQueryResponse::ProcessExistQuery(), and queryserver::XMLQueryResponse::SaveResults().
const double& queryserver::XMLQueryRequest::QueryRequestParam::MetaRelevance () const [inline]
Definition at line 83 of file XMLQueryRequest.h.
References relevanceMeta.
Referenced by queryserver::XMLQueryResponse::GetPagesByMeta().
const double& queryserver::XMLQueryRequest::QueryRequestParam::TitleRelevance () const [inline]
Definition at line 84 of file XMLQueryRequest.h.
References relevanceTitle.
const double& queryserver::XMLQueryRequest::QueryRequestParam::DomainRelevance () const [inline]
Definition at line 85 of file XMLQueryRequest.h.
References relevanceDomain.
Referenced by queryserver::XMLQueryResponse::GetPagesByDomain().
const double& queryserver::XMLQueryRequest::QueryRequestParam::ContentRelevance () const [inline]
Definition at line 86 of file XMLQueryRequest.h.
References relevanceFullText.
Referenced by queryserver::XMLQueryResponse::GetPagesByContent().
const double& queryserver::XMLQueryRequest::QueryRequestParam::BackLinkRelevance () const [inline]
Definition at line 87 of file XMLQueryRequest.h.
References relevanceBackLinks.
Referenced by queryserver::XMLQueryResponse::GetPageRelevanceByBacklinks().
const double& queryserver::XMLQueryRequest::QueryRequestParam::UrlPathRelevance () const [inline]
Definition at line 88 of file XMLQueryRequest.h.
References relevanceUrlPath.
Referenced by queryserver::XMLQueryResponse::GetPagesByUrlPath().
Member Data Documentation
std::list<std::string> queryserver::XMLQueryRequest::QueryRequestParam::queryParts
Definition at line 92 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryRequest::ParseQuery(), and queryserver::XMLQueryRequest::QueryParts().
unsigned long long queryserver::XMLQueryRequest::QueryRequestParam::criteriaFlag
Definition at line 95 of file XMLQueryRequest.h.
Referenced by CriteriaFlag(), and queryserver::XMLQueryRequest::ParseQueryCriteria().
unsigned long long queryserver::XMLQueryRequest::QueryRequestParam::groupFlag
Definition at line 96 of file XMLQueryRequest.h.
Referenced by GroupingFlag(), and queryserver::XMLQueryRequest::ParseQueryGrouping().
unsigned long long queryserver::XMLQueryRequest::QueryRequestParam::limitFlag
Definition at line 97 of file XMLQueryRequest.h.
Referenced by LimitFlag(), and queryserver::XMLQueryRequest::ParseQueryLimitations().
double queryserver::XMLQueryRequest::QueryRequestParam::relevanceMeta
Definition at line 100 of file XMLQueryRequest.h.
Referenced by MetaRelevance(), and queryserver::XMLQueryRequest::ParseQueryCriteria().
double queryserver::XMLQueryRequest::QueryRequestParam::relevanceTitle
Definition at line 101 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryRequest::ParseQueryCriteria(), and TitleRelevance().
double queryserver::XMLQueryRequest::QueryRequestParam::relevanceDomain
Definition at line 102 of file XMLQueryRequest.h.
Referenced by DomainRelevance(), and queryserver::XMLQueryRequest::ParseQueryCriteria().
double queryserver::XMLQueryRequest::QueryRequestParam::relevanceFullText
Definition at line 103 of file XMLQueryRequest.h.
Referenced by ContentRelevance(), and queryserver::XMLQueryRequest::ParseQueryCriteria().
double queryserver::XMLQueryRequest::QueryRequestParam::relevanceBackLinks
Definition at line 104 of file XMLQueryRequest.h.
Referenced by BackLinkRelevance(), and queryserver::XMLQueryRequest::ParseQueryCriteria().
double queryserver::XMLQueryRequest::QueryRequestParam::relevanceUrlPath
Definition at line 105 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryRequest::ParseQueryCriteria(), and UrlPathRelevance().
size_t queryserver::XMLQueryRequest::QueryRequestParam::pageNo
Definition at line 108 of file XMLQueryRequest.h.
Referenced by PageNumber(), and queryserver::XMLQueryRequest::ParseQuery().
int queryserver::XMLQueryRequest::QueryRequestParam::maxResults
Definition at line 109 of file XMLQueryRequest.h.
Referenced by MaxResults(), and queryserver::XMLQueryRequest::ParseQueryLimitations().
std::string queryserver::XMLQueryRequest::QueryRequestParam::limitDomain
Definition at line 110 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryRequest::ParseQueryLimitations().
std::string queryserver::XMLQueryRequest::QueryRequestParam::limitAge
Definition at line 111 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryRequest::ParseQueryLimitations().
std::string queryserver::XMLQueryRequest::QueryRequestParam::limitLang
Definition at line 112 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryRequest::ParseQueryLimitations().
long long queryserver::XMLQueryRequest::QueryRequestParam::queryID
Definition at line 114 of file XMLQueryRequest.h.
Referenced by queryserver::XMLQueryResponse::LogQuery(), queryserver::XMLQueryRequest::ParseQuery(), and QueryID().
The documentation for this class was generated from the following file:
QueryServer/src/XMLQueryRequest.h