DeepNet: database::urlstagesTableBase Class Reference
database::urlstagesTableBase Class Reference
wrapper class for database table urlstages
#include <urlstagesTableBase.h>
Public Member Functions
urlstagesTableBase ()
virtual ~urlstagesTableBase ()
void Get_ID (long long &out) const
gets value of ID.
void Set_ID (const long long &in)
sets value of ID.
void Get_URL_ID (long long &out) const
gets value of URL_ID.
void Set_URL_ID (const long long &in)
sets value of URL_ID.
void Get_response_code (long long &out) const
gets value of response_code.
void Set_response_code (const long long &in)
sets value of response_code.
void Get_content_md5 (std::string &out) const
gets value of content_md5.
void Set_content_md5 (const std::string &in)
sets value of content_md5.
void Get_last_change (struct tm &out) const
gets value of last_change.
void Set_last_change (const struct tm &in)
sets value of last_change.
void Get_redirect_count (long long &out) const
gets value of redirect_count.
void Set_redirect_count (const long long &in)
sets value of redirect_count.
void Get_download_speed (long long &out) const
gets value of download_speed.
void Set_download_speed (const long long &in)
sets value of download_speed.
void Get_upload_speed (long long &out) const
gets value of upload_speed.
void Set_upload_speed (const long long &in)
sets value of upload_speed.
void Get_content_length (long long &out) const
gets value of content_length.
void Set_content_length (const long long &in)
sets value of content_length.
void Get_content_type (std::string &out) const
gets value of content_type.
void Set_content_type (const std::string &in)
sets value of content_type.
void Get_primary_ip (long long &out) const
gets value of primary_ip.
void Set_primary_ip (const long long &in)
sets value of primary_ip.
void Get_primary_port (long long &out) const
gets value of primary_port.
void Set_primary_port (const long long &in)
sets value of primary_port.
void Get_int_links (long long &out) const
gets value of int_links.
void Set_int_links (const long long &in)
sets value of int_links.
void Get_ext_links (long long &out) const
gets value of ext_links.
void Set_ext_links (const long long &in)
sets value of ext_links.
void Get_download_time (long long &out) const
gets value of download_time.
void Set_download_time (const long long &in)
sets value of download_time.
void Get_html_errors (long long &out) const
gets value of html_errors.
void Set_html_errors (const long long &in)
sets value of html_errors.
void Get_found_date (struct tm &out) const
gets value of found_date.
void Set_found_date (const struct tm &in)
sets value of found_date.
const TableDefinition * GetConstTableDefinition () const
gets const table definition.
TableDefinition * GetTableDefinition ()
gets table definition.
const TableColumn * GetConstColumnByName (const std::string &columnName) const
finds column by it's name.
TableColumn * GetColumnByName (const std::string &columnName)
finds column by it's name.
std::vector< TableColumn * > & GetColumns ()
gets list of columns.
const std::vector< TableColumn * > & GetConstColumns () const
gets const list of columns.
void SetTableAlias (const std::string &tableAlias)
sets alias name.
const std::string & GetTableAlias () const
gets alias name.
void Insert (DatabaseConnection *db)
inserts this table.
void InsertOrUpdate (DatabaseConnection *db)
inserts or updates this table.
void InsertOrUpdate (DatabaseConnection *db, TableColumnDefinition *sumColumn)
inserts or updates this table adding SUM()-type columns.
void InsertOrUpdate (DatabaseConnection *db, const std::vector< TableColumnDefinition * > &sumColumn)
inserts or updates this table adding SUM()-type columns.
void Update (DatabaseConnection *db, const TableBaseUpdateParam &param) const
updates this table.
void CopyColumns (const TableBase *base)
copies column definitions and values from another table.
Static Public Member Functions
static TableDefinition * CreateTableDefinition ()
factory function for urlstages's table definition.
static void GetBy_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of ID.
static void GetBy_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of ID.
static void GetBy_URL_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of URL_ID.
static void GetBy_URL_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of URL_ID.
static void GetBy_response_code (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of response_code.
static void GetBy_response_code (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of response_code.
static void GetBy_content_md5 (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of content_md5.
static void GetBy_content_md5 (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of content_md5.
static void GetBy_last_change (DatabaseConnection *db, const struct tm &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of last_change.
static void GetBy_last_change (DatabaseConnection *db, const std::vector< struct tm > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of last_change.
static void GetBy_redirect_count (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of redirect_count.
static void GetBy_redirect_count (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of redirect_count.
static void GetBy_download_speed (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of download_speed.
static void GetBy_download_speed (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of download_speed.
static void GetBy_upload_speed (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of upload_speed.
static void GetBy_upload_speed (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of upload_speed.
static void GetBy_content_length (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of content_length.
static void GetBy_content_length (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of content_length.
static void GetBy_content_type (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of content_type.
static void GetBy_content_type (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of content_type.
static void GetBy_primary_ip (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of primary_ip.
static void GetBy_primary_ip (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of primary_ip.
static void GetBy_primary_port (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of primary_port.
static void GetBy_primary_port (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of primary_port.
static void GetBy_int_links (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of int_links.
static void GetBy_int_links (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of int_links.
static void GetBy_ext_links (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of ext_links.
static void GetBy_ext_links (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of ext_links.
static void GetBy_download_time (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of download_time.
static void GetBy_download_time (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of download_time.
static void GetBy_html_errors (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of html_errors.
static void GetBy_html_errors (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of html_errors.
static void GetBy_found_date (DatabaseConnection *db, const struct tm &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by a value of found_date.
static void GetBy_found_date (DatabaseConnection *db, const std::vector< struct tm > &fieldValue, SelectResultContainer< urlstagesTableBase > &results)
gets rows by multiple values of found_date.
static void AddInnerJoinLeftSideOn_URL_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinLeftSideOn_URL_ID (Statement &stmt)
static void AddInnerJoinRightSideOn_URL_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinRightSideOn_URL_ID (Statement &stmt)
static void GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of ID.
static void GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of ID.
static void GetWhereColumnsFor_URL_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of URL_ID.
static void GetWhereColumnsFor_URL_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of URL_ID.
static void GetWhereColumnsFor_response_code (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of response_code.
static void GetWhereColumnsFor_response_code (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of response_code.
static void GetWhereColumnsFor_content_md5 (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of content_md5.
static void GetWhereColumnsFor_content_md5 (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of content_md5.
static void GetWhereColumnsFor_last_change (const WhereConditionTableColumnCreateParam &createParam, const struct tm &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of last_change.
static void GetWhereColumnsFor_last_change (const WhereConditionTableColumnCreateParam &createParam, const std::vector< struct tm > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of last_change.
static void GetWhereColumnsFor_redirect_count (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of redirect_count.
static void GetWhereColumnsFor_redirect_count (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of redirect_count.
static void GetWhereColumnsFor_download_speed (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of download_speed.
static void GetWhereColumnsFor_download_speed (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of download_speed.
static void GetWhereColumnsFor_upload_speed (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of upload_speed.
static void GetWhereColumnsFor_upload_speed (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of upload_speed.
static void GetWhereColumnsFor_content_length (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of content_length.
static void GetWhereColumnsFor_content_length (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of content_length.
static void GetWhereColumnsFor_content_type (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of content_type.
static void GetWhereColumnsFor_content_type (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of content_type.
static void GetWhereColumnsFor_primary_ip (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of primary_ip.
static void GetWhereColumnsFor_primary_ip (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of primary_ip.
static void GetWhereColumnsFor_primary_port (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of primary_port.
static void GetWhereColumnsFor_primary_port (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of primary_port.
static void GetWhereColumnsFor_int_links (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of int_links.
static void GetWhereColumnsFor_int_links (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of int_links.
static void GetWhereColumnsFor_ext_links (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of ext_links.
static void GetWhereColumnsFor_ext_links (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of ext_links.
static void GetWhereColumnsFor_download_time (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of download_time.
static void GetWhereColumnsFor_download_time (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of download_time.
static void GetWhereColumnsFor_html_errors (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of html_errors.
static void GetWhereColumnsFor_html_errors (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of html_errors.
static void GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam &createParam, const struct tm &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of found_date.
static void GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam &createParam, const std::vector< struct tm > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of found_date.
static TableColumnDefinition * GetDefinition_ID ()
create a column definition for column ID.
static TableColumnDefinition * GetDefinition_URL_ID ()
create a column definition for column URL_ID.
static TableColumnDefinition * GetDefinition_response_code ()
create a column definition for column response_code.
static TableColumnDefinition * GetDefinition_content_md5 ()
create a column definition for column content_md5.
static TableColumnDefinition * GetDefinition_last_change ()
create a column definition for column last_change.
static TableColumnDefinition * GetDefinition_redirect_count ()
create a column definition for column redirect_count.
static TableColumnDefinition * GetDefinition_download_speed ()
create a column definition for column download_speed.
static TableColumnDefinition * GetDefinition_upload_speed ()
create a column definition for column upload_speed.
static TableColumnDefinition * GetDefinition_content_length ()
create a column definition for column content_length.
static TableColumnDefinition * GetDefinition_content_type ()
create a column definition for column content_type.
static TableColumnDefinition * GetDefinition_primary_ip ()
create a column definition for column primary_ip.
static TableColumnDefinition * GetDefinition_primary_port ()
create a column definition for column primary_port.
static TableColumnDefinition * GetDefinition_int_links ()
create a column definition for column int_links.
static TableColumnDefinition * GetDefinition_ext_links ()
create a column definition for column ext_links.
static TableColumnDefinition * GetDefinition_download_time ()
create a column definition for column download_time.
static TableColumnDefinition * GetDefinition_html_errors ()
create a column definition for column html_errors.
static TableColumnDefinition * GetDefinition_found_date ()
create a column definition for column found_date.
static TableBase * CreateInstance (const TableDefinitionCreateParam &param)
factory function for this class.
Protected Member Functions
void CreateColumns ()
creates columns according to database::TableBase::definition.
Private Member Functions
urlstagesTableBase (const TableBase &base)
Detailed Description
wrapper class for database table urlstages
Definition at line 17 of file urlstagesTableBase.h.
Constructor & Destructor Documentation
database::urlstagesTableBase::urlstagesTableBase (const TableBase & base) [private]
Definition at line 30 of file urlstagesTableBase.cpp.
References THROW_EXCEPTION.
database::urlstagesTableBase::urlstagesTableBase ()
Definition at line 26 of file urlstagesTableBase.cpp.
database::urlstagesTableBase::~urlstagesTableBase () [virtual]
Definition at line 34 of file urlstagesTableBase.cpp.
Member Function Documentation
TableDefinition * database::urlstagesTableBase::CreateTableDefinition () [static]
factory function for urlstages's table definition.
Returns:
table definition.
Definition at line 37 of file urlstagesTableBase.cpp.
References database::TableBase::CreateInstance().
Referenced by AddInnerJoinLeftSideOn_URL_ID(), AddInnerJoinRightSideOn_URL_ID(), GetBy_content_length(), GetBy_content_md5(), GetBy_content_type(), GetBy_download_speed(), GetBy_download_time(), GetBy_ext_links(), GetBy_found_date(), GetBy_html_errors(), GetBy_ID(), GetBy_int_links(), GetBy_last_change(), GetBy_primary_ip(), GetBy_primary_port(), GetBy_redirect_count(), GetBy_response_code(), GetBy_upload_speed(), GetBy_URL_ID(), and queryserver::XMLQueryResponse::GetPageUrlStageInfo().
void database::urlstagesTableBase::Get_ID (long long & out) const
gets value of ID.
Parameters:
out value.
Definition at line 44 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_ID (const long long & in)
sets value of ID.
Parameters:
in value.
Definition at line 48 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
void database::urlstagesTableBase::Get_URL_ID (long long & out) const
gets value of URL_ID.
Parameters:
out value.
Definition at line 52 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_URL_ID (const long long & in)
sets value of URL_ID.
Parameters:
in value.
Definition at line 56 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_response_code (long long & out) const
gets value of response_code.
Parameters:
out value.
Definition at line 60 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_response_code (const long long & in)
sets value of response_code.
Parameters:
in value.
Definition at line 64 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_content_md5 (std::string & out) const
gets value of content_md5.
Parameters:
out value.
Definition at line 68 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_content_md5 (const std::string & in)
sets value of content_md5.
Parameters:
in value.
Definition at line 72 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_last_change (struct tm & out) const
gets value of last_change.
Parameters:
out value.
Definition at line 76 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_last_change (const struct tm & in)
sets value of last_change.
Parameters:
in value.
Definition at line 80 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_redirect_count (long long & out) const
gets value of redirect_count.
Parameters:
out value.
Definition at line 84 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_redirect_count (const long long & in)
sets value of redirect_count.
Parameters:
in value.
Definition at line 88 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_download_speed (long long & out) const
gets value of download_speed.
Parameters:
out value.
Definition at line 92 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_download_speed (const long long & in)
sets value of download_speed.
Parameters:
in value.
Definition at line 96 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_upload_speed (long long & out) const
gets value of upload_speed.
Parameters:
out value.
Definition at line 100 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_upload_speed (const long long & in)
sets value of upload_speed.
Parameters:
in value.
Definition at line 104 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_content_length (long long & out) const
gets value of content_length.
Parameters:
out value.
Definition at line 108 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_content_length (const long long & in)
sets value of content_length.
Parameters:
in value.
Definition at line 112 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_content_type (std::string & out) const
gets value of content_type.
Parameters:
out value.
Definition at line 116 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_content_type (const std::string & in)
sets value of content_type.
Parameters:
in value.
Definition at line 120 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_primary_ip (long long & out) const
gets value of primary_ip.
Parameters:
out value.
Definition at line 124 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_primary_ip (const long long & in)
sets value of primary_ip.
Parameters:
in value.
Definition at line 128 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_primary_port (long long & out) const
gets value of primary_port.
Parameters:
out value.
Definition at line 132 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_primary_port (const long long & in)
sets value of primary_port.
Parameters:
in value.
Definition at line 136 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_int_links (long long & out) const
gets value of int_links.
Parameters:
out value.
Definition at line 140 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_int_links (const long long & in)
sets value of int_links.
Parameters:
in value.
Definition at line 144 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by parser::GenericWebHtmlParserThread::UpdateUrlstageInfos().
void database::urlstagesTableBase::Get_ext_links (long long & out) const
gets value of ext_links.
Parameters:
out value.
Definition at line 148 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_ext_links (const long long & in)
sets value of ext_links.
Parameters:
in value.
Definition at line 152 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by parser::GenericWebHtmlParserThread::UpdateUrlstageInfos().
void database::urlstagesTableBase::Get_download_time (long long & out) const
gets value of download_time.
Parameters:
out value.
Definition at line 156 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_download_time (const long long & in)
sets value of download_time.
Parameters:
in value.
Definition at line 160 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::Get_html_errors (long long & out) const
gets value of html_errors.
Parameters:
out value.
Definition at line 164 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_html_errors (const long long & in)
sets value of html_errors.
Parameters:
in value.
Definition at line 168 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
void database::urlstagesTableBase::Get_found_date (struct tm & out) const
gets value of found_date.
Parameters:
out value.
Definition at line 172 of file urlstagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlstagesTableBase::Set_found_date (const struct tm & in)
sets value of found_date.
Parameters:
in value.
Definition at line 176 of file urlstagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl().
void database::urlstagesTableBase::GetBy_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of ID.
Parameters:
db database connection.
fieldValue value of ID.
results contains results.
Definition at line 185 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of ID.
Parameters:
db database connection.
fieldValue values of ID.
results contains results.
Definition at line 202 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_URL_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of URL_ID.
Parameters:
db database connection.
fieldValue value of URL_ID.
results contains results.
Definition at line 219 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_URL_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_URL_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of URL_ID.
Parameters:
db database connection.
fieldValue values of URL_ID.
results contains results.
Definition at line 236 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_URL_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_response_code (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of response_code.
Parameters:
db database connection.
fieldValue value of response_code.
results contains results.
Definition at line 253 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_response_code(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_response_code (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of response_code.
Parameters:
db database connection.
fieldValue values of response_code.
results contains results.
Definition at line 270 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_response_code(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_content_md5 (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of content_md5.
Parameters:
db database connection.
fieldValue value of content_md5.
results contains results.
Definition at line 287 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_content_md5(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_content_md5 (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of content_md5.
Parameters:
db database connection.
fieldValue values of content_md5.
results contains results.
Definition at line 304 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_content_md5(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_last_change (DatabaseConnection * db, const struct tm & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of last_change.
Parameters:
db database connection.
fieldValue value of last_change.
results contains results.
Definition at line 321 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_last_change(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_last_change (DatabaseConnection * db, const std::vector< struct tm > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of last_change.
Parameters:
db database connection.
fieldValue values of last_change.
results contains results.
Definition at line 338 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_last_change(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_redirect_count (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of redirect_count.
Parameters:
db database connection.
fieldValue value of redirect_count.
results contains results.
Definition at line 355 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_redirect_count(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_redirect_count (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of redirect_count.
Parameters:
db database connection.
fieldValue values of redirect_count.
results contains results.
Definition at line 372 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_redirect_count(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_download_speed (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of download_speed.
Parameters:
db database connection.
fieldValue value of download_speed.
results contains results.
Definition at line 389 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_download_speed(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_download_speed (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of download_speed.
Parameters:
db database connection.
fieldValue values of download_speed.
results contains results.
Definition at line 406 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_download_speed(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_upload_speed (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of upload_speed.
Parameters:
db database connection.
fieldValue value of upload_speed.
results contains results.
Definition at line 423 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_upload_speed(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_upload_speed (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of upload_speed.
Parameters:
db database connection.
fieldValue values of upload_speed.
results contains results.
Definition at line 440 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_upload_speed(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_content_length (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of content_length.
Parameters:
db database connection.
fieldValue value of content_length.
results contains results.
Definition at line 457 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_content_length(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_content_length (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of content_length.
Parameters:
db database connection.
fieldValue values of content_length.
results contains results.
Definition at line 474 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_content_length(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_content_type (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of content_type.
Parameters:
db database connection.
fieldValue value of content_type.
results contains results.
Definition at line 491 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_content_type(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_content_type (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of content_type.
Parameters:
db database connection.
fieldValue values of content_type.
results contains results.
Definition at line 508 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_content_type(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_primary_ip (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of primary_ip.
Parameters:
db database connection.
fieldValue value of primary_ip.
results contains results.
Definition at line 525 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_primary_ip(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_primary_ip (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of primary_ip.
Parameters:
db database connection.
fieldValue values of primary_ip.
results contains results.
Definition at line 542 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_primary_ip(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_primary_port (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of primary_port.
Parameters:
db database connection.
fieldValue value of primary_port.
results contains results.
Definition at line 559 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_primary_port(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_primary_port (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of primary_port.
Parameters:
db database connection.
fieldValue values of primary_port.
results contains results.
Definition at line 576 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_primary_port(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_int_links (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of int_links.
Parameters:
db database connection.
fieldValue value of int_links.
results contains results.
Definition at line 593 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_int_links(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_int_links (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of int_links.
Parameters:
db database connection.
fieldValue values of int_links.
results contains results.
Definition at line 610 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_int_links(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_ext_links (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of ext_links.
Parameters:
db database connection.
fieldValue value of ext_links.
results contains results.
Definition at line 627 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ext_links(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_ext_links (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of ext_links.
Parameters:
db database connection.
fieldValue values of ext_links.
results contains results.
Definition at line 644 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ext_links(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_download_time (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of download_time.
Parameters:
db database connection.
fieldValue value of download_time.
results contains results.
Definition at line 661 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_download_time(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_download_time (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of download_time.
Parameters:
db database connection.
fieldValue values of download_time.
results contains results.
Definition at line 678 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_download_time(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_html_errors (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of html_errors.
Parameters:
db database connection.
fieldValue value of html_errors.
results contains results.
Definition at line 695 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_html_errors(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_html_errors (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of html_errors.
Parameters:
db database connection.
fieldValue values of html_errors.
results contains results.
Definition at line 712 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_html_errors(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_found_date (DatabaseConnection * db, const struct tm & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by a value of found_date.
Parameters:
db database connection.
fieldValue value of found_date.
results contains results.
Definition at line 729 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_found_date(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::GetBy_found_date (DatabaseConnection * db, const std::vector< struct tm > & fieldValue, SelectResultContainer< urlstagesTableBase > & results) [static]
gets rows by multiple values of found_date.
Parameters:
db database connection.
fieldValue values of found_date.
results contains results.
Definition at line 746 of file urlstagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_found_date(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 768 of file urlstagesTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_URL_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinLeftSideOn_URL_ID().
void database::urlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID (Statement & stmt) [static]
Definition at line 788 of file urlstagesTableBase.cpp.
References AddInnerJoinLeftSideOn_URL_ID().
void database::urlstagesTableBase::AddInnerJoinRightSideOn_URL_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 793 of file urlstagesTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_URL_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinRightSideOn_URL_ID(), and queryserver::XMLQueryResponse::GetPageUrlStageInfo().
void database::urlstagesTableBase::AddInnerJoinRightSideOn_URL_ID (Statement & stmt) [static]
Definition at line 813 of file urlstagesTableBase.cpp.
References AddInnerJoinRightSideOn_URL_ID().
void database::urlstagesTableBase::GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 822 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_ID().
Referenced by GetBy_ID(), and queryserver::XMLQueryResponse::GetPageUrlStageInfo().
void database::urlstagesTableBase::GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 834 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_ID().
void database::urlstagesTableBase::GetWhereColumnsFor_URL_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of URL_ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 846 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_URL_ID().
Referenced by GetBy_URL_ID(), and parser::GenericWebHtmlParserThread::UpdateUrlstageInfos().
void database::urlstagesTableBase::GetWhereColumnsFor_URL_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of URL_ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 858 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_URL_ID().
void database::urlstagesTableBase::GetWhereColumnsFor_response_code (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of response_code.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 870 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_response_code().
Referenced by GetBy_response_code().
void database::urlstagesTableBase::GetWhereColumnsFor_response_code (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of response_code.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 882 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_response_code().
void database::urlstagesTableBase::GetWhereColumnsFor_content_md5 (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of content_md5.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 894 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_content_md5().
Referenced by GetBy_content_md5().
void database::urlstagesTableBase::GetWhereColumnsFor_content_md5 (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of content_md5.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 906 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_content_md5().
void database::urlstagesTableBase::GetWhereColumnsFor_last_change (const WhereConditionTableColumnCreateParam & createParam, const struct tm & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of last_change.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 918 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_last_change().
Referenced by GetBy_last_change().
void database::urlstagesTableBase::GetWhereColumnsFor_last_change (const WhereConditionTableColumnCreateParam & createParam, const std::vector< struct tm > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of last_change.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 930 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_last_change().
void database::urlstagesTableBase::GetWhereColumnsFor_redirect_count (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of redirect_count.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 942 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_redirect_count().
Referenced by GetBy_redirect_count().
void database::urlstagesTableBase::GetWhereColumnsFor_redirect_count (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of redirect_count.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 954 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_redirect_count().
void database::urlstagesTableBase::GetWhereColumnsFor_download_speed (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of download_speed.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 966 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_download_speed().
Referenced by GetBy_download_speed().
void database::urlstagesTableBase::GetWhereColumnsFor_download_speed (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of download_speed.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 978 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_download_speed().
void database::urlstagesTableBase::GetWhereColumnsFor_upload_speed (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of upload_speed.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 990 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_upload_speed().
Referenced by GetBy_upload_speed().
void database::urlstagesTableBase::GetWhereColumnsFor_upload_speed (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of upload_speed.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1002 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_upload_speed().
void database::urlstagesTableBase::GetWhereColumnsFor_content_length (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of content_length.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1014 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_content_length().
Referenced by GetBy_content_length().
void database::urlstagesTableBase::GetWhereColumnsFor_content_length (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of content_length.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1026 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_content_length().
void database::urlstagesTableBase::GetWhereColumnsFor_content_type (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of content_type.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1038 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_content_type().
Referenced by GetBy_content_type().
void database::urlstagesTableBase::GetWhereColumnsFor_content_type (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of content_type.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1050 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_content_type().
void database::urlstagesTableBase::GetWhereColumnsFor_primary_ip (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of primary_ip.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1062 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_primary_ip().
Referenced by GetBy_primary_ip().
void database::urlstagesTableBase::GetWhereColumnsFor_primary_ip (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of primary_ip.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1074 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_primary_ip().
void database::urlstagesTableBase::GetWhereColumnsFor_primary_port (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of primary_port.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1086 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_primary_port().
Referenced by GetBy_primary_port().
void database::urlstagesTableBase::GetWhereColumnsFor_primary_port (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of primary_port.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1098 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_primary_port().
void database::urlstagesTableBase::GetWhereColumnsFor_int_links (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of int_links.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1110 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_int_links().
Referenced by GetBy_int_links().
void database::urlstagesTableBase::GetWhereColumnsFor_int_links (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of int_links.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1122 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_int_links().
void database::urlstagesTableBase::GetWhereColumnsFor_ext_links (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of ext_links.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1134 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_ext_links().
Referenced by GetBy_ext_links().
void database::urlstagesTableBase::GetWhereColumnsFor_ext_links (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of ext_links.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1146 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_ext_links().
void database::urlstagesTableBase::GetWhereColumnsFor_download_time (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of download_time.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1158 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_download_time().
Referenced by GetBy_download_time().
void database::urlstagesTableBase::GetWhereColumnsFor_download_time (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of download_time.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1170 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_download_time().
void database::urlstagesTableBase::GetWhereColumnsFor_html_errors (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of html_errors.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1182 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_html_errors().
Referenced by GetBy_html_errors().
void database::urlstagesTableBase::GetWhereColumnsFor_html_errors (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of html_errors.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1194 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_html_errors().
void database::urlstagesTableBase::GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam & createParam, const struct tm & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of found_date.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 1206 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_found_date().
Referenced by GetBy_found_date().
void database::urlstagesTableBase::GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam & createParam, const std::vector< struct tm > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of found_date.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 1218 of file urlstagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_found_date().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_ID () [static]
create a column definition for column ID.
Returns:
column definition.
Definition at line 1235 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_URL_ID(), AddInnerJoinRightSideOn_URL_ID(), database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_ID().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_URL_ID () [static]
create a column definition for column URL_ID.
Returns:
column definition.
Definition at line 1251 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_URL_ID(), AddInnerJoinRightSideOn_URL_ID(), database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_URL_ID().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_response_code () [static]
create a column definition for column response_code.
Returns:
column definition.
Definition at line 1267 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_response_code().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_content_md5 () [static]
create a column definition for column content_md5.
Returns:
column definition.
Definition at line 1283 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_CHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_content_md5().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_last_change () [static]
create a column definition for column last_change.
Returns:
column definition.
Definition at line 1299 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_TIMESTAMP, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_last_change().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_redirect_count () [static]
create a column definition for column redirect_count.
Returns:
column definition.
Definition at line 1315 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_redirect_count().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_download_speed () [static]
create a column definition for column download_speed.
Returns:
column definition.
Definition at line 1331 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_download_speed().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_upload_speed () [static]
create a column definition for column upload_speed.
Returns:
column definition.
Definition at line 1347 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_upload_speed().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_content_length () [static]
create a column definition for column content_length.
Returns:
column definition.
Definition at line 1363 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_content_length().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_content_type () [static]
create a column definition for column content_type.
Returns:
column definition.
Definition at line 1379 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_VARCHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_content_type().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_primary_ip () [static]
create a column definition for column primary_ip.
Returns:
column definition.
Definition at line 1395 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_primary_ip().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_primary_port () [static]
create a column definition for column primary_port.
Returns:
column definition.
Definition at line 1411 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_primary_port().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_int_links () [static]
create a column definition for column int_links.
Returns:
column definition.
Definition at line 1427 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_int_links().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_ext_links () [static]
create a column definition for column ext_links.
Returns:
column definition.
Definition at line 1443 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_ext_links().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_download_time () [static]
create a column definition for column download_time.
Returns:
column definition.
Definition at line 1459 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_download_time().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_html_errors () [static]
create a column definition for column html_errors.
Returns:
column definition.
Definition at line 1475 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_html_errors().
TableColumnDefinition * database::urlstagesTableBase::GetDefinition_found_date () [static]
create a column definition for column found_date.
Returns:
column definition.
Definition at line 1491 of file urlstagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_TIMESTAMP, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlstagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_found_date().
const TableDefinition * database::TableBase::GetConstTableDefinition () const [inherited]
gets const table definition.
Returns:
table definition.
Definition at line 81 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::definition.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL().
TableDefinition * database::TableBase::GetTableDefinition () [inherited]
gets table definition.
Returns:
table definition.
Definition at line 87 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::definition.
const TableColumn * database::TableBase::GetConstColumnByName (const std::string & columnName) const [inherited]
finds column by it's name.
Parameters:
columnName column name.
Returns:
NULL if not found, column otherwise.
Definition at line 93 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, and THROW_EXCEPTION.
Referenced by database::TableBase::CopyColumns(), database::cacherobotsTableBase::Get_action_time(), database::cachesecondleveldomainTableBase::Get_action_time(), database::cachehtmlTableBase::Get_action_time(), database::cacheurlTableBase::Get_action_time(), database::cacheparsedTableBase::Get_action_time(), database::cachesubdomainTableBase::Get_action_time(), database::logmessagesTableBase::Get_actiontime(), database::logmessagesTableBase::Get_appName(), database::documentcodeTableBase::Get_code(), Get_content_length(), Get_content_md5(), Get_content_type(), database::hyperlinksTableBase::Get_count(), database::locksecondleveldomainTableBase::Get_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Get_CRAWLERSESSION_ID(), database::syncurlsTableBase::Get_CRAWLERSESSION_ID(), database::fencedsearchTableBase::Get_CUSTOMER_ID(), database::customersessionsTableBase::Get_CUSTOMER_ID(), database::customerdomainsTableBase::Get_CUSTOMER_ID(), database::dataminingblacklistTableBase::Get_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Get_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Get_CUSTOMER_ID(), database::customerproductsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerqueriesTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Get_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Get_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Get_DICT_ID(), database::docmetaTableBase::Get_DICT_ID(), database::docurlTableBase::Get_DICT_ID(), database::customerproductkeywordsTableBase::Get_DICT_ID(), database::dockeyposTableBase::Get_DOCKEY_ID(), database::secondleveldomainsTableBase::Get_domain(), database::customerdomainsTableBase::Get_domain(), database::dataminingblacklistTableBase::Get_domain(), Get_download_speed(), Get_download_time(), Get_ext_links(), database::imagesTableBase::Get_found_date(), database::urlsTableBase::Get_found_date(), Get_found_date(), database::customermatchcriteriagrouptypeTableBase::Get_groupPosition(), Get_html_errors(), database::fencedsearchTableBase::Get_ID(), database::hyperlinksTableBase::Get_ID(), database::crawlersessionsTableBase::Get_ID(), database::imagesTableBase::Get_ID(), database::customerdomainblacklistTableBase::Get_ID(), database::documentcodeTableBase::Get_ID(), database::customerproductkeywordsTableBase::Get_ID(), database::customerqueriesTableBase::Get_ID(), database::cacheparsedTableBase::Get_ID(), database::customersessionsTableBase::Get_ID(), database::dockeyposTableBase::Get_ID(), database::latesturlstagesTableBase::Get_ID(), database::customerproducturlsTableBase::Get_ID(), database::imagelinksTableBase::Get_ID(), database::customersTableBase::Get_ID(), database::customerdomainsTableBase::Get_ID(), database::logmessagesTableBase::Get_ID(), database::customersynccrawlerTableBase::Get_ID(), database::queryresultsTableBase::Get_ID(), database::metainfoTableBase::Get_ID(), database::keywordqueryTableBase::Get_ID(), database::cachesecondleveldomainTableBase::Get_ID(), database::dataminingalertsTableBase::Get_ID(), database::customerkeywordsTableBase::Get_ID(), database::schemesTableBase::Get_ID(), database::secondleveldomainsTableBase::Get_ID(), database::searchqueryTableBase::Get_ID(), database::matchcriteriaTableBase::Get_ID(), database::customersyncurlTableBase::Get_ID(), database::syncurlsTableBase::Get_ID(), database::subdomainsTableBase::Get_ID(), database::dataminingcriteriaalertsTableBase::Get_ID(), database::cachesubdomainTableBase::Get_ID(), database::dataminingcustomersessionTableBase::Get_ID(), database::dataminingcriteriaTableBase::Get_ID(), database::searchquerykeywordsTableBase::Get_ID(), database::dataminingblacklistTableBase::Get_ID(), Get_ID(), database::customermatchcriteriagrouptypeTableBase::Get_ID(), database::dataminingcustomerTableBase::Get_ID(), database::dockeyTableBase::Get_ID(), database::cacherobotsTableBase::Get_ID(), database::topleveldomainsTableBase::Get_ID(), database::urlsTableBase::Get_ID(), database::cacheurlTableBase::Get_ID(), database::customerproductimagesTableBase::Get_ID(), database::docmetaTableBase::Get_ID(), database::cachehtmlTableBase::Get_ID(), database::docurlTableBase::Get_ID(), database::dictTableBase::Get_ID(), database::customermatchcriteriaTableBase::Get_ID(), database::customerproductsTableBase::Get_ID(), database::imagelinksTableBase::Get_IMAGE_URL_ID(), database::customerproductimagesTableBase::Get_imageUrl(), Get_int_links(), database::customerdomainsTableBase::Get_isDomainRegex(), database::customerkeywordsTableBase::Get_isKeywordRegex(), database::customerdomainblacklistTableBase::Get_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Get_isPrimaryKey(), database::dataminingcriteriaTableBase::Get_keyword(), database::dictTableBase::Get_keyword(), database::customerkeywordsTableBase::Get_keyword(), database::searchquerykeywordsTableBase::Get_KEYWORDQUERY_ID(), Get_last_change(), database::customersTableBase::Get_login(), database::dataminingcustomerTableBase::Get_login(), database::logmessagesTableBase::Get_loglevel(), database::customermatchcriteriaTableBase::Get_MATCHCRITERIA_ID(), database::cachesubdomainTableBase::Get_matches(), database::cacherobotsTableBase::Get_matches(), database::cachesecondleveldomainTableBase::Get_matches(), database::cachehtmlTableBase::Get_matches(), database::cacheparsedTableBase::Get_matches(), database::cacheurlTableBase::Get_matches(), database::logmessagesTableBase::Get_message(), database::cacherobotsTableBase::Get_misses(), database::cachesubdomainTableBase::Get_misses(), database::cacheurlTableBase::Get_misses(), database::cachehtmlTableBase::Get_misses(), database::cacheparsedTableBase::Get_misses(), database::cachesecondleveldomainTableBase::Get_misses(), database::dictTableBase::Get_occurrence(), database::dockeyTableBase::Get_occurrence(), database::docmetaTableBase::Get_occurrence(), database::queryresultsTableBase::Get_order_position(), database::dockeyposTableBase::Get_paragraph(), database::dataminingalertsTableBase::Get_param(), database::customersTableBase::Get_password(), database::dataminingcustomerTableBase::Get_password(), database::customerdomainblacklistTableBase::Get_path(), database::imagesTableBase::Get_path_part(), database::urlsTableBase::Get_path_part(), database::logmessagesTableBase::Get_pid(), database::imagesTableBase::Get_port(), database::urlsTableBase::Get_port(), database::dockeyposTableBase::Get_position(), Get_primary_ip(), Get_primary_port(), database::customerproducturlsTableBase::Get_PRODUCT_ID(), database::customerproductimagesTableBase::Get_PRODUCT_ID(), database::customerproductkeywordsTableBase::Get_PRODUCT_ID(), database::customerproductsTableBase::Get_productBrand(), database::customerproductsTableBase::Get_productName(), database::customerproductsTableBase::Get_productNo(), database::customerqueriesTableBase::Get_query(), database::keywordqueryTableBase::Get_query_part(), Get_redirect_count(), database::matchcriteriaTableBase::Get_regex(), Get_response_code(), database::customerdomainsTableBase::Get_revisitInterval(), database::locksecondleveldomainTableBase::Get_schedule(), database::syncurlsTableBase::Get_schedule(), database::customersyncurlTableBase::Get_scheduled(), database::customersynccrawlerTableBase::Get_scheduled(), database::schemesTableBase::Get_scheme(), database::imagesTableBase::Get_SCHEME_ID(), database::urlsTableBase::Get_SCHEME_ID(), database::imagesTableBase::Get_search_part(), database::urlsTableBase::Get_search_part(), database::queryresultsTableBase::Get_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Get_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Get_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Get_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Get_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Get_session(), database::dataminingcustomersessionTableBase::Get_session(), database::customersessionsTableBase::Get_session(), database::cachehtmlTableBase::Get_size(), database::cachesecondleveldomainTableBase::Get_size(), database::cacherobotsTableBase::Get_size(), database::cacheparsedTableBase::Get_size(), database::cachesubdomainTableBase::Get_size(), database::cacheurlTableBase::Get_size(), database::subdomainsTableBase::Get_subdomain(), database::imagesTableBase::Get_SUBDOMAIN_ID(), database::urlsTableBase::Get_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Get_target(), database::hyperlinksTableBase::Get_TARGET_URL_ID(), database::imagelinksTableBase::Get_TARGET_URL_ID(), database::logmessagesTableBase::Get_threadName(), database::logmessagesTableBase::Get_tid(), database::topleveldomainsTableBase::Get_tld(), database::imagesTableBase::Get_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Get_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Get_type(), database::metainfoTableBase::Get_type(), database::customermatchcriteriagrouptypeTableBase::Get_type(), database::dataminingcriteriaTableBase::Get_type(), database::customermatchcriteriaTableBase::Get_type(), database::docmetaTableBase::Get_type(), Get_upload_speed(), database::customersyncurlTableBase::Get_URL_ID(), database::syncurlsTableBase::Get_URL_ID(), Get_URL_ID(), database::latesturlstagesTableBase::Get_URL_ID(), database::docurlTableBase::Get_URL_ID(), database::queryresultsTableBase::Get_URL_ID(), database::customerproducturlsTableBase::Get_URL_ID(), database::imagesTableBase::Get_url_md5(), database::urlsTableBase::Get_url_md5(), database::documentcodeTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_URLSTAGE_ID(), database::hyperlinksTableBase::Get_URLSTAGE_ID(), database::dockeyTableBase::Get_URLSTAGE_ID(), database::docmetaTableBase::Get_URLSTAGE_ID(), database::latesturlstagesTableBase::Get_URLSTAGE_ID(), database::queryresultsTableBase::Get_URLSTAGE_ID(), database::imagelinksTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_value(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), htmlparser::DatabaseUrl::InitByTable(), queryserver::XMLQueryResponse::ProcessExistQuery(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
TableColumn * database::TableBase::GetColumnByName (const std::string & columnName) [inherited]
finds column by it's name.
Parameters:
columnName column name.
Returns:
NULL if not found, column otherwise.
Definition at line 105 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, and THROW_EXCEPTION.
Referenced by parser::GenericWebHtmlParserThread::InsertImages(), database::cacheparsedTableBase::Set_action_time(), database::cachehtmlTableBase::Set_action_time(), database::cacherobotsTableBase::Set_action_time(), database::cachesecondleveldomainTableBase::Set_action_time(), database::cachesubdomainTableBase::Set_action_time(), database::cacheurlTableBase::Set_action_time(), database::logmessagesTableBase::Set_actiontime(), database::logmessagesTableBase::Set_appName(), database::documentcodeTableBase::Set_code(), Set_content_length(), Set_content_md5(), Set_content_type(), database::hyperlinksTableBase::Set_count(), database::locksecondleveldomainTableBase::Set_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::customerdomainsTableBase::Set_CUSTOMER_ID(), database::customersessionsTableBase::Set_CUSTOMER_ID(), database::dataminingblacklistTableBase::Set_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Set_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Set_CUSTOMER_ID(), database::fencedsearchTableBase::Set_CUSTOMER_ID(), database::customerqueriesTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Set_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Set_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Set_DICT_ID(), database::docmetaTableBase::Set_DICT_ID(), database::docurlTableBase::Set_DICT_ID(), database::customerproductkeywordsTableBase::Set_DICT_ID(), database::dockeyposTableBase::Set_DOCKEY_ID(), database::secondleveldomainsTableBase::Set_domain(), database::customerdomainsTableBase::Set_domain(), database::dataminingblacklistTableBase::Set_domain(), Set_download_speed(), Set_download_time(), Set_ext_links(), database::imagesTableBase::Set_found_date(), database::urlsTableBase::Set_found_date(), Set_found_date(), database::customermatchcriteriagrouptypeTableBase::Set_groupPosition(), Set_html_errors(), database::hyperlinksTableBase::Set_ID(), database::customerproducturlsTableBase::Set_ID(), database::imagelinksTableBase::Set_ID(), database::customerdomainsTableBase::Set_ID(), database::customerqueriesTableBase::Set_ID(), database::crawlersessionsTableBase::Set_ID(), database::customerproductimagesTableBase::Set_ID(), database::keywordqueryTableBase::Set_ID(), database::customersessionsTableBase::Set_ID(), database::customersTableBase::Set_ID(), database::customerkeywordsTableBase::Set_ID(), database::customersynccrawlerTableBase::Set_ID(), database::cachesecondleveldomainTableBase::Set_ID(), database::imagesTableBase::Set_ID(), database::customersyncurlTableBase::Set_ID(), database::matchcriteriaTableBase::Set_ID(), database::metainfoTableBase::Set_ID(), database::cachehtmlTableBase::Set_ID(), database::schemesTableBase::Set_ID(), database::dataminingalertsTableBase::Set_ID(), database::latesturlstagesTableBase::Set_ID(), database::logmessagesTableBase::Set_ID(), database::searchquerykeywordsTableBase::Set_ID(), database::dataminingblacklistTableBase::Set_ID(), database::searchqueryTableBase::Set_ID(), database::cacherobotsTableBase::Set_ID(), database::syncurlsTableBase::Set_ID(), database::cachesubdomainTableBase::Set_ID(), database::queryresultsTableBase::Set_ID(), database::dataminingcriteriaTableBase::Set_ID(), database::customermatchcriteriagrouptypeTableBase::Set_ID(), database::urlsTableBase::Set_ID(), database::dataminingcustomersessionTableBase::Set_ID(), database::dictTableBase::Set_ID(), Set_ID(), database::secondleveldomainsTableBase::Set_ID(), database::dataminingcriteriaalertsTableBase::Set_ID(), database::dockeyposTableBase::Set_ID(), database::cacheurlTableBase::Set_ID(), database::dockeyTableBase::Set_ID(), database::cacheparsedTableBase::Set_ID(), database::documentcodeTableBase::Set_ID(), database::customermatchcriteriaTableBase::Set_ID(), database::dataminingcustomerTableBase::Set_ID(), database::docurlTableBase::Set_ID(), database::customerproductsTableBase::Set_ID(), database::topleveldomainsTableBase::Set_ID(), database::subdomainsTableBase::Set_ID(), database::fencedsearchTableBase::Set_ID(), database::customerproductkeywordsTableBase::Set_ID(), database::docmetaTableBase::Set_ID(), database::customerdomainblacklistTableBase::Set_ID(), database::imagelinksTableBase::Set_IMAGE_URL_ID(), database::customerproductimagesTableBase::Set_imageUrl(), Set_int_links(), database::customerdomainsTableBase::Set_isDomainRegex(), database::customerkeywordsTableBase::Set_isKeywordRegex(), database::customerdomainblacklistTableBase::Set_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Set_isPrimaryKey(), database::dataminingcriteriaTableBase::Set_keyword(), database::dictTableBase::Set_keyword(), database::customerkeywordsTableBase::Set_keyword(), database::searchquerykeywordsTableBase::Set_KEYWORDQUERY_ID(), Set_last_change(), database::customersTableBase::Set_login(), database::dataminingcustomerTableBase::Set_login(), database::logmessagesTableBase::Set_loglevel(), database::customermatchcriteriaTableBase::Set_MATCHCRITERIA_ID(), database::cachesubdomainTableBase::Set_matches(), database::cacheparsedTableBase::Set_matches(), database::cachesecondleveldomainTableBase::Set_matches(), database::cachehtmlTableBase::Set_matches(), database::cacherobotsTableBase::Set_matches(), database::cacheurlTableBase::Set_matches(), database::logmessagesTableBase::Set_message(), database::cacheparsedTableBase::Set_misses(), database::cachesecondleveldomainTableBase::Set_misses(), database::cachesubdomainTableBase::Set_misses(), database::cachehtmlTableBase::Set_misses(), database::cacheurlTableBase::Set_misses(), database::cacherobotsTableBase::Set_misses(), database::dictTableBase::Set_occurrence(), database::dockeyTableBase::Set_occurrence(), database::docmetaTableBase::Set_occurrence(), database::queryresultsTableBase::Set_order_position(), database::dockeyposTableBase::Set_paragraph(), database::dataminingalertsTableBase::Set_param(), database::dataminingcustomerTableBase::Set_password(), database::customersTableBase::Set_password(), database::customerdomainblacklistTableBase::Set_path(), database::imagesTableBase::Set_path_part(), database::urlsTableBase::Set_path_part(), database::logmessagesTableBase::Set_pid(), database::imagesTableBase::Set_port(), database::urlsTableBase::Set_port(), database::dockeyposTableBase::Set_position(), Set_primary_ip(), Set_primary_port(), database::customerproducturlsTableBase::Set_PRODUCT_ID(), database::customerproductimagesTableBase::Set_PRODUCT_ID(), database::customerproductkeywordsTableBase::Set_PRODUCT_ID(), database::customerproductsTableBase::Set_productBrand(), database::customerproductsTableBase::Set_productName(), database::customerproductsTableBase::Set_productNo(), database::customerqueriesTableBase::Set_query(), database::keywordqueryTableBase::Set_query_part(), Set_redirect_count(), database::matchcriteriaTableBase::Set_regex(), Set_response_code(), database::customerdomainsTableBase::Set_revisitInterval(), database::locksecondleveldomainTableBase::Set_schedule(), database::syncurlsTableBase::Set_schedule(), database::customersyncurlTableBase::Set_scheduled(), database::customersynccrawlerTableBase::Set_scheduled(), database::schemesTableBase::Set_scheme(), database::imagesTableBase::Set_SCHEME_ID(), database::urlsTableBase::Set_SCHEME_ID(), database::imagesTableBase::Set_search_part(), database::urlsTableBase::Set_search_part(), database::queryresultsTableBase::Set_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Set_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Set_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Set_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Set_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Set_session(), database::customersessionsTableBase::Set_session(), database::dataminingcustomersessionTableBase::Set_session(), database::cacheurlTableBase::Set_size(), database::cachesubdomainTableBase::Set_size(), database::cacheparsedTableBase::Set_size(), database::cachesecondleveldomainTableBase::Set_size(), database::cacherobotsTableBase::Set_size(), database::cachehtmlTableBase::Set_size(), database::subdomainsTableBase::Set_subdomain(), database::imagesTableBase::Set_SUBDOMAIN_ID(), database::urlsTableBase::Set_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Set_target(), database::imagelinksTableBase::Set_TARGET_URL_ID(), database::hyperlinksTableBase::Set_TARGET_URL_ID(), database::logmessagesTableBase::Set_threadName(), database::logmessagesTableBase::Set_tid(), database::topleveldomainsTableBase::Set_tld(), database::imagesTableBase::Set_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Set_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Set_type(), database::metainfoTableBase::Set_type(), database::dataminingcriteriaTableBase::Set_type(), database::customermatchcriteriagrouptypeTableBase::Set_type(), database::customermatchcriteriaTableBase::Set_type(), database::docmetaTableBase::Set_type(), Set_upload_speed(), database::syncurlsTableBase::Set_URL_ID(), database::customersyncurlTableBase::Set_URL_ID(), database::latesturlstagesTableBase::Set_URL_ID(), Set_URL_ID(), database::customerproducturlsTableBase::Set_URL_ID(), database::docurlTableBase::Set_URL_ID(), database::queryresultsTableBase::Set_URL_ID(), database::urlsTableBase::Set_url_md5(), database::imagesTableBase::Set_url_md5(), database::documentcodeTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_URLSTAGE_ID(), database::docmetaTableBase::Set_URLSTAGE_ID(), database::latesturlstagesTableBase::Set_URLSTAGE_ID(), database::hyperlinksTableBase::Set_URLSTAGE_ID(), database::dockeyTableBase::Set_URLSTAGE_ID(), database::queryresultsTableBase::Set_URLSTAGE_ID(), database::imagelinksTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_value(), database::MySQLTableBase::SetColumnValues(), and htmlparser::DatabaseUrl::Store().
std::vector< TableColumn * > & database::TableBase::GetColumns () [inherited]
gets list of columns.
Returns:
list of columns.
Definition at line 69 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::columns.
const std::vector< TableColumn * > & database::TableBase::GetConstColumns () const [inherited]
gets const list of columns.
Returns:
list of columns.
Definition at line 75 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::columns.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL(), database::InsertStatement::ToSQL(), and database::UpdateStatement::ToSQL().
void database::TableBase::SetTableAlias (const std::string & tableAlias) [inline, inherited]
sets alias name.
Parameters:
tableAlias table name alias.
Definition at line 123 of file TableBase.h.
References database::TableBase::tableAlias.
const std::string& database::TableBase::GetTableAlias () const [inline, inherited]
gets alias name.
Returns:
tableAlias table name alias.
Definition at line 129 of file TableBase.h.
References database::TableBase::tableAlias.
void database::TableBase::Insert (DatabaseConnection * db) [inherited]
inserts this table.
Parameters:
db database connection.
Definition at line 161 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::DatabaseConnection::Insert().
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::UrlFetcherThread::GetNextCrawlerSessionID(), toolbot::DataMiningTools::InsertDataminingUser(), parser::GenericWebHtmlParserThread::InsertMeta(), queryserver::XMLQueryResponse::LogQuery(), log::DatabaseLogging::OnLog(), toolbot::DataMiningTools::RegisterDataminingAlert(), queryserver::XMLQueryResponse::SaveResults(), and bot::Bot::WatchDog().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db) [inherited]
inserts or updates this table.
Parameters:
db database connection.
Definition at line 169 of file TableBase.cpp.
Referenced by indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), parser::GenericWebHtmlParserThread::InsertImages(), parser::GenericWebHtmlParserThread::InsertLinks(), queryserver::XMLQueryResponse::LogQuery(), crawler::CommerceSearchFetcherThread::ReserveNextUrls(), parser::CommerceSearchProduct::Store(), and htmlparser::DatabaseUrl::Store().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db, TableColumnDefinition * sumColumn) [inherited]
inserts or updates this table adding SUM()-type columns.
Parameters:
db database connection.
sumColumn columns to replace with sum instead of new value.
Definition at line 174 of file TableBase.cpp.
References database::InsertOrUpdateStatement::AddSumUpColumn(), database::TableBase::CheckInitialization(), and database::DatabaseConnection::InsertOrUpdate().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db, const std::vector< TableColumnDefinition * > & sumColumn) [inherited]
inserts or updates this table adding SUM()-type columns.
Parameters:
db database connection.
sumColumn columns to replace with sum instead of new value.
Definition at line 185 of file TableBase.cpp.
References database::InsertOrUpdateStatement::AddSumUpColumns(), database::TableBase::CheckInitialization(), and database::DatabaseConnection::InsertOrUpdate().
void database::TableBase::Update (DatabaseConnection * db, const TableBaseUpdateParam & param) const [inherited]
updates this table.
Parameters:
db database connection.
param update parameters.
Definition at line 196 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBaseUpdateParam::limit, database::TableBaseUpdateParam::onlyDirtyColumns, database::TableBaseUpdateParam::orderCols, database::Statement::SetLimit(), database::DatabaseConnection::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and parser::GenericWebHtmlParserThread::UpdateUrlstageInfos().
TableBase * database::TableBase::CreateInstance (const TableDefinitionCreateParam & param) [static, inherited]
factory function for this class.
Parameters:
param table definition creation parameter.
Returns:
NULL on error, table base on success.
Definition at line 64 of file TableBase.cpp.
References database::TableDefinition::CreateInstance(), and database::TableBase::TableBase().
Referenced by database::TableBase::CreateColumns(), database::cachehtmlTableBase::CreateTableDefinition(), database::latesturlstagesTableBase::CreateTableDefinition(), database::dataminingcriteriaalertsTableBase::CreateTableDefinition(), database::queryresultsTableBase::CreateTableDefinition(), database::subdomainsTableBase::CreateTableDefinition(), database::customerproducturlsTableBase::CreateTableDefinition(), database::locksecondleveldomainTableBase::CreateTableDefinition(), CreateTableDefinition(), database::customerdomainsTableBase::CreateTableDefinition(), database::dataminingcriteriaTableBase::CreateTableDefinition(), database::customermatchcriteriaTableBase::CreateTableDefinition(), database::documentcodeTableBase::CreateTableDefinition(), database::cachesecondleveldomainTableBase::CreateTableDefinition(), database::hyperlinksTableBase::CreateTableDefinition(), database::syncurlsTableBase::CreateTableDefinition(), database::customerproductsTableBase::CreateTableDefinition(), database::docurlTableBase::CreateTableDefinition(), database::dictTableBase::CreateTableDefinition(), database::imagelinksTableBase::CreateTableDefinition(), database::urlsTableBase::CreateTableDefinition(), database::dataminingcustomerTableBase::CreateTableDefinition(), database::searchqueryTableBase::CreateTableDefinition(), database::keywordqueryTableBase::CreateTableDefinition(), database::matchcriteriaTableBase::CreateTableDefinition(), database::customerkeywordsTableBase::CreateTableDefinition(), database::secondleveldomainsTableBase::CreateTableDefinition(), database::customerdomainblacklistTableBase::CreateTableDefinition(), database::imagesTableBase::CreateTableDefinition(), database::cacherobotsTableBase::CreateTableDefinition(), database::topleveldomainsTableBase::CreateTableDefinition(), database::cacheparsedTableBase::CreateTableDefinition(), database::schemesTableBase::CreateTableDefinition(), database::logmessagesTableBase::CreateTableDefinition(), database::dataminingblacklistTableBase::CreateTableDefinition(), database::dataminingalertsTableBase::CreateTableDefinition(), database::crawlersessionsTableBase::CreateTableDefinition(), database::customerproductimagesTableBase::CreateTableDefinition(), database::dockeyTableBase::CreateTableDefinition(), database::fencedsearchTableBase::CreateTableDefinition(), database::customersynccrawlerTableBase::CreateTableDefinition(), database::customermatchcriteriagrouptypeTableBase::CreateTableDefinition(), database::dockeyposTableBase::CreateTableDefinition(), database::metainfoTableBase::CreateTableDefinition(), database::searchquerykeywordsTableBase::CreateTableDefinition(), database::cachesubdomainTableBase::CreateTableDefinition(), database::customersessionsTableBase::CreateTableDefinition(), database::customerproductkeywordsTableBase::CreateTableDefinition(), database::customersyncurlTableBase::CreateTableDefinition(), database::customerqueriesTableBase::CreateTableDefinition(), database::customersTableBase::CreateTableDefinition(), database::docmetaTableBase::CreateTableDefinition(), database::dataminingcustomersessionTableBase::CreateTableDefinition(), database::cacheurlTableBase::CreateTableDefinition(), database::cacheurlTableBase::GetDefinition_action_time(), database::cacherobotsTableBase::GetDefinition_action_time(), database::cachesecondleveldomainTableBase::GetDefinition_action_time(), database::cacheparsedTableBase::GetDefinition_action_time(), database::cachesubdomainTableBase::GetDefinition_action_time(), database::cachehtmlTableBase::GetDefinition_action_time(), database::logmessagesTableBase::GetDefinition_actiontime(), database::logmessagesTableBase::GetDefinition_appName(), database::documentcodeTableBase::GetDefinition_code(), GetDefinition_content_length(), GetDefinition_content_md5(), GetDefinition_content_type(), database::hyperlinksTableBase::GetDefinition_count(), database::locksecondleveldomainTableBase::GetDefinition_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetDefinition_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetDefinition_CRAWLERSESSION_ID(), database::customersessionsTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetDefinition_CUSTOMER_ID(), database::fencedsearchTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_CUSTOMER_ID(), database::customerdomainsTableBase::GetDefinition_CUSTOMER_ID(), database::customerqueriesTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetDefinition_DICT_ID(), database::customerproductkeywordsTableBase::GetDefinition_DICT_ID(), database::dockeyTableBase::GetDefinition_DICT_ID(), database::docmetaTableBase::GetDefinition_DICT_ID(), database::dockeyposTableBase::GetDefinition_DOCKEY_ID(), database::secondleveldomainsTableBase::GetDefinition_domain(), database::dataminingblacklistTableBase::GetDefinition_domain(), database::customerdomainsTableBase::GetDefinition_domain(), GetDefinition_download_speed(), GetDefinition_download_time(), GetDefinition_ext_links(), database::imagesTableBase::GetDefinition_found_date(), database::urlsTableBase::GetDefinition_found_date(), GetDefinition_found_date(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_groupPosition(), GetDefinition_html_errors(), database::crawlersessionsTableBase::GetDefinition_ID(), database::keywordqueryTableBase::GetDefinition_ID(), database::matchcriteriaTableBase::GetDefinition_ID(), database::schemesTableBase::GetDefinition_ID(), database::searchqueryTableBase::GetDefinition_ID(), database::secondleveldomainsTableBase::GetDefinition_ID(), database::subdomainsTableBase::GetDefinition_ID(), database::topleveldomainsTableBase::GetDefinition_ID(), database::dataminingcustomerTableBase::GetDefinition_ID(), database::dictTableBase::GetDefinition_ID(), database::customersTableBase::GetDefinition_ID(), database::dataminingcriteriaTableBase::GetDefinition_ID(), database::dataminingalertsTableBase::GetDefinition_ID(), database::customerproductimagesTableBase::GetDefinition_ID(), database::documentcodeTableBase::GetDefinition_ID(), database::customerqueriesTableBase::GetDefinition_ID(), database::customersessionsTableBase::GetDefinition_ID(), database::customersyncurlTableBase::GetDefinition_ID(), database::dataminingblacklistTableBase::GetDefinition_ID(), database::dataminingcustomersessionTableBase::GetDefinition_ID(), database::customerproductkeywordsTableBase::GetDefinition_ID(), database::docurlTableBase::GetDefinition_ID(), database::fencedsearchTableBase::GetDefinition_ID(), database::customerproducturlsTableBase::GetDefinition_ID(), database::latesturlstagesTableBase::GetDefinition_ID(), database::searchquerykeywordsTableBase::GetDefinition_ID(), database::dockeyposTableBase::GetDefinition_ID(), database::customerdomainblacklistTableBase::GetDefinition_ID(), database::customersynccrawlerTableBase::GetDefinition_ID(), database::metainfoTableBase::GetDefinition_ID(), database::dockeyTableBase::GetDefinition_ID(), database::hyperlinksTableBase::GetDefinition_ID(), database::customermatchcriteriaTableBase::GetDefinition_ID(), database::imagelinksTableBase::GetDefinition_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_ID(), database::cacheurlTableBase::GetDefinition_ID(), database::cachehtmlTableBase::GetDefinition_ID(), database::cacheparsedTableBase::GetDefinition_ID(), database::cachesecondleveldomainTableBase::GetDefinition_ID(), database::cachesubdomainTableBase::GetDefinition_ID(), database::cacherobotsTableBase::GetDefinition_ID(), database::customerproductsTableBase::GetDefinition_ID(), database::customerdomainsTableBase::GetDefinition_ID(), database::customerkeywordsTableBase::GetDefinition_ID(), database::queryresultsTableBase::GetDefinition_ID(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_ID(), database::docmetaTableBase::GetDefinition_ID(), database::syncurlsTableBase::GetDefinition_ID(), database::logmessagesTableBase::GetDefinition_ID(), database::imagesTableBase::GetDefinition_ID(), database::urlsTableBase::GetDefinition_ID(), GetDefinition_ID(), database::imagelinksTableBase::GetDefinition_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetDefinition_imageUrl(), GetDefinition_int_links(), database::customerdomainsTableBase::GetDefinition_isDomainRegex(), database::customerkeywordsTableBase::GetDefinition_isKeywordRegex(), database::customerdomainblacklistTableBase::GetDefinition_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_isPrimaryKey(), database::dictTableBase::GetDefinition_keyword(), database::dataminingcriteriaTableBase::GetDefinition_keyword(), database::customerkeywordsTableBase::GetDefinition_keyword(), database::searchquerykeywordsTableBase::GetDefinition_KEYWORDQUERY_ID(), GetDefinition_last_change(), database::dataminingcustomerTableBase::GetDefinition_login(), database::customersTableBase::GetDefinition_login(), database::logmessagesTableBase::GetDefinition_loglevel(), database::customermatchcriteriaTableBase::GetDefinition_MATCHCRITERIA_ID(), database::cacherobotsTableBase::GetDefinition_matches(), database::cachehtmlTableBase::GetDefinition_matches(), database::cachesecondleveldomainTableBase::GetDefinition_matches(), database::cachesubdomainTableBase::GetDefinition_matches(), database::cacheurlTableBase::GetDefinition_matches(), database::cacheparsedTableBase::GetDefinition_matches(), database::logmessagesTableBase::GetDefinition_message(), database::cacherobotsTableBase::GetDefinition_misses(), database::cacheurlTableBase::GetDefinition_misses(), database::cachehtmlTableBase::GetDefinition_misses(), database::cacheparsedTableBase::GetDefinition_misses(), database::cachesecondleveldomainTableBase::GetDefinition_misses(), database::cachesubdomainTableBase::GetDefinition_misses(), database::dictTableBase::GetDefinition_occurrence(), database::dockeyTableBase::GetDefinition_occurrence(), database::docmetaTableBase::GetDefinition_occurrence(), database::queryresultsTableBase::GetDefinition_order_position(), database::dockeyposTableBase::GetDefinition_paragraph(), database::dataminingalertsTableBase::GetDefinition_param(), database::dataminingcustomerTableBase::GetDefinition_password(), database::customersTableBase::GetDefinition_password(), database::customerdomainblacklistTableBase::GetDefinition_path(), database::imagesTableBase::GetDefinition_path_part(), database::urlsTableBase::GetDefinition_path_part(), database::logmessagesTableBase::GetDefinition_pid(), database::urlsTableBase::GetDefinition_port(), database::imagesTableBase::GetDefinition_port(), database::dockeyposTableBase::GetDefinition_position(), GetDefinition_primary_ip(), GetDefinition_primary_port(), database::customerproductimagesTableBase::GetDefinition_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetDefinition_PRODUCT_ID(), database::customerproducturlsTableBase::GetDefinition_PRODUCT_ID(), database::customerproductsTableBase::GetDefinition_productBrand(), database::customerproductsTableBase::GetDefinition_productName(), database::customerproductsTableBase::GetDefinition_productNo(), database::customerqueriesTableBase::GetDefinition_query(), database::keywordqueryTableBase::GetDefinition_query_part(), GetDefinition_redirect_count(), database::matchcriteriaTableBase::GetDefinition_regex(), GetDefinition_response_code(), database::customerdomainsTableBase::GetDefinition_revisitInterval(), database::locksecondleveldomainTableBase::GetDefinition_schedule(), database::syncurlsTableBase::GetDefinition_schedule(), database::customersyncurlTableBase::GetDefinition_scheduled(), database::customersynccrawlerTableBase::GetDefinition_scheduled(), database::schemesTableBase::GetDefinition_scheme(), database::imagesTableBase::GetDefinition_SCHEME_ID(), database::urlsTableBase::GetDefinition_SCHEME_ID(), database::imagesTableBase::GetDefinition_search_part(), database::urlsTableBase::GetDefinition_search_part(), database::searchquerykeywordsTableBase::GetDefinition_SEARCHQUERY_ID(), database::queryresultsTableBase::GetDefinition_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetDefinition_session(), database::customersessionsTableBase::GetDefinition_session(), database::dataminingcustomersessionTableBase::GetDefinition_session(), database::cacherobotsTableBase::GetDefinition_size(), database::cachesecondleveldomainTableBase::GetDefinition_size(), database::cacheparsedTableBase::GetDefinition_size(), database::cachesubdomainTableBase::GetDefinition_size(), database::cacheurlTableBase::GetDefinition_size(), database::cachehtmlTableBase::GetDefinition_size(), database::subdomainsTableBase::GetDefinition_subdomain(), database::imagesTableBase::GetDefinition_SUBDOMAIN_ID(), database::urlsTableBase::GetDefinition_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetDefinition_target(), database::hyperlinksTableBase::GetDefinition_TARGET_URL_ID(), database::imagelinksTableBase::GetDefinition_TARGET_URL_ID(), database::logmessagesTableBase::GetDefinition_threadName(), database::logmessagesTableBase::GetDefinition_tid(), database::topleveldomainsTableBase::GetDefinition_tld(), database::urlsTableBase::GetDefinition_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetDefinition_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetDefinition_type(), database::dataminingcriteriaTableBase::GetDefinition_type(), database::metainfoTableBase::GetDefinition_type(), database::customermatchcriteriaTableBase::GetDefinition_type(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_type(), database::docmetaTableBase::GetDefinition_type(), GetDefinition_upload_speed(), database::customersyncurlTableBase::GetDefinition_URL_ID(), database::latesturlstagesTableBase::GetDefinition_URL_ID(), database::docurlTableBase::GetDefinition_URL_ID(), database::customerproducturlsTableBase::GetDefinition_URL_ID(), database::syncurlsTableBase::GetDefinition_URL_ID(), database::queryresultsTableBase::GetDefinition_URL_ID(), GetDefinition_URL_ID(), database::urlsTableBase::GetDefinition_url_md5(), database::imagesTableBase::GetDefinition_url_md5(), database::documentcodeTableBase::GetDefinition_URLSTAGE_ID(), database::latesturlstagesTableBase::GetDefinition_URLSTAGE_ID(), database::metainfoTableBase::GetDefinition_URLSTAGE_ID(), database::hyperlinksTableBase::GetDefinition_URLSTAGE_ID(), database::dockeyTableBase::GetDefinition_URLSTAGE_ID(), database::imagelinksTableBase::GetDefinition_URLSTAGE_ID(), database::docmetaTableBase::GetDefinition_URLSTAGE_ID(), database::queryresultsTableBase::GetDefinition_URLSTAGE_ID(), and database::metainfoTableBase::GetDefinition_value().
void database::TableBase::CopyColumns (const TableBase * base) [inherited]
copies column definitions and values from another table.
Parameters:
base table to copy from.
Definition at line 117 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, database::TableColumn::CopyValue(), and database::TableBase::GetConstColumnByName().
void database::TableBase::CreateColumns () [protected, inherited]
creates columns according to database::TableBase::definition.
Definition at line 55 of file TableBase.cpp.
References database::TableBase::columns, database::TableBase::CreateInstance(), database::TableColumn::CreateInstance(), database::TableBase::definition, and database::TableDefinition::GetColumnDefinitions().
Referenced by database::TableBase::TableBase().
The documentation for this class was generated from the following files:
Database/generated/urlstagesTableBase.h
Database/generated/urlstagesTableBase.cpp