DeepNet: fastcgiserver::FastCGIServerSocketException Class Reference
fastcgiserver::FastCGIServerSocketException Class Reference
#include <FastCGIServerSocketException.h>
Public Member Functions
FastCGIServerSocketException (const std::string &file, const int line, const std::string &function, const std::string &message)
virtual ~FastCGIServerSocketException ()
void Log () const
log this exception.
void DisableLogging ()
prevent exception from being logged.
std::string Dump () const
dumps exception as string.
Static Public Member Functions
static void InitializeExceptionHandling ()
initializes exception handling for current process.
Protected Attributes
std::string file
originating filename
int line
originating source line.
std::string function
originating function.
std::string module
originating module.
std::string exceptionName
name of the exception.
std::string message
exception message.
std::string backtrace
backtrace.
bool logException
log this exception.
Detailed Description
Definition at line 14 of file FastCGIServerSocketException.h.
Constructor & Destructor Documentation
fastcgiserver::FastCGIServerSocketException::FastCGIServerSocketException (const std::string & file, const int line, const std::string & function, const std::string & message)
Definition at line 12 of file FastCGIServerSocketException.cpp.
fastcgiserver::FastCGIServerSocketException::~FastCGIServerSocketException () [virtual]
Definition at line 20 of file FastCGIServerSocketException.cpp.
Member Function Documentation
void errors::Exception::InitializeExceptionHandling () [static, inherited]
initializes exception handling for current process.
Definition at line 93 of file Exception.cpp.
References errors::Exception::TerminateHandler().
Referenced by fastcgiserver::FastCGIServer::FastCGIServer(), and bot::Bot::Run().
void errors::Exception::Log () const [inherited]
log this exception.
Definition at line 65 of file Exception.cpp.
References errors::Exception::Dump(), log::Logging::LOGLEVEL_ERROR, and log::Logging::LogUnlimited().
Referenced by errors::Exception::~Exception().
void errors::Exception::DisableLogging () [inherited]
prevent exception from being logged.
Definition at line 70 of file Exception.cpp.
References errors::Exception::logException.
Referenced by domparser::DOMParser::Parse(), toolbot::UnitTestHttpClientCURL::ReadURLFile(), and toolbot::UnitTestUrlParser::TestInvalidUrls().
std::string errors::Exception::Dump () const [inherited]
dumps exception as string.
Returns:
exception as string.
Definition at line 74 of file Exception.cpp.
References errors::Exception::backtrace, errors::Exception::exceptionName, errors::Exception::file, log::Logging::GetTimeString(), errors::Exception::line, errors::Exception::message, and errors::Exception::module.
Referenced by errors::Exception::Log(), toolbot::UnitTestUrlParser::TestInvalidUrls(), and toolbot::UnitTestUrlParser::TestValidUrls().
Member Data Documentation
std::string errors::Exception::file [protected, inherited]
originating filename
Definition at line 90 of file Exception.h.
Referenced by errors::Exception::Dump().
int errors::Exception::line [protected, inherited]
originating source line.
Definition at line 95 of file Exception.h.
Referenced by errors::Exception::Dump().
std::string errors::Exception::function [protected, inherited]
originating function.
Definition at line 100 of file Exception.h.
std::string errors::Exception::module [protected, inherited]
originating module.
Definition at line 105 of file Exception.h.
Referenced by errors::Exception::Dump().
std::string errors::Exception::exceptionName [protected, inherited]
name of the exception.
Definition at line 110 of file Exception.h.
Referenced by errors::Exception::Dump().
std::string errors::Exception::message [protected, inherited]
exception message.
Definition at line 115 of file Exception.h.
Referenced by domparser::dom3::DOMException::DOMException(), and errors::Exception::Dump().
std::string errors::Exception::backtrace [protected, inherited]
backtrace.
Definition at line 120 of file Exception.h.
Referenced by errors::Exception::Dump(), and errors::Exception::TerminateHandler().
bool errors::Exception::logException [protected, inherited]
log this exception.
Definition at line 125 of file Exception.h.
Referenced by errors::Exception::DisableLogging(), and errors::Exception::~Exception().
The documentation for this class was generated from the following files:
FastCGIServer/src/FastCGIServerSocketException.h
FastCGIServer/src/FastCGIServerSocketException.cpp