DeepNet: fastcgiserver::FastCGISocket Class Reference
fastcgiserver::FastCGISocket Class Reference
#include <FastCGISocket.h>
Public Member Functions
FastCGISocket (const int port, const int backlog=0)
FastCGISocket (const std::string &filename, const int backlog=0)
virtual ~FastCGISocket ()
bool WaitForAccept ()
int Socket () const
Private Member Functions
void SetNonBlocking (bool isNonBlocking=true)
Private Attributes
int socket
int backlog
int port
std::string filename
Detailed Description
Definition at line 14 of file FastCGISocket.h.
Constructor & Destructor Documentation
fastcgiserver::FastCGISocket::FastCGISocket (const int port, const int backlog = 0)
Definition at line 25 of file FastCGISocket.cpp.
References backlog, port, socket, and THROW_EXCEPTION.
fastcgiserver::FastCGISocket::FastCGISocket (const std::string & filename, const int backlog = 0)
Definition at line 37 of file FastCGISocket.cpp.
References socket, and THROW_EXCEPTION.
fastcgiserver::FastCGISocket::~FastCGISocket () [virtual]
Definition at line 47 of file FastCGISocket.cpp.
References socket.
Member Function Documentation
bool fastcgiserver::FastCGISocket::WaitForAccept ()
Definition at line 67 of file FastCGISocket.cpp.
References SetNonBlocking(), and socket.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
int fastcgiserver::FastCGISocket::Socket () const [inline]
Definition at line 24 of file FastCGISocket.h.
References socket.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
void fastcgiserver::FastCGISocket::SetNonBlocking (bool isNonBlocking = true) [private]
Definition at line 54 of file FastCGISocket.cpp.
References socket.
Referenced by WaitForAccept().
Member Data Documentation
int fastcgiserver::FastCGISocket::socket [private]
Definition at line 30 of file FastCGISocket.h.
Referenced by FastCGISocket(), SetNonBlocking(), Socket(), WaitForAccept(), and ~FastCGISocket().
int fastcgiserver::FastCGISocket::backlog [private]
Definition at line 31 of file FastCGISocket.h.
Referenced by FastCGISocket().
int fastcgiserver::FastCGISocket::port [private]
Definition at line 32 of file FastCGISocket.h.
Referenced by FastCGISocket().
std::string fastcgiserver::FastCGISocket::filename [private]
Definition at line 33 of file FastCGISocket.h.
The documentation for this class was generated from the following files:
FastCGIServer/src/FastCGISocket.h
FastCGIServer/src/FastCGISocket.cpp