/**
 * @file TableColumnDefinitionCreateParam.h
 * @author Moritz Wagner
 * @date 10.08.2012
 */

#pragma once

#include <string>
#include "TableColumnType.h"

namespace database {

/**
 * @brief create parameters for column definitions.
 * @see database::TableColumnDefinition
 */
class TableColumnDefinitionCreateParam {
public:
	TableColumnDefinitionCreateParam();
	virtual ~TableColumnDefinitionCreateParam();

	TableColumnType columnType;
	std::string     columnName;
	std::string     tableName;
	std::string     databaseName;

	bool            isPrimaryKey;
	bool            isAutoGenerated;
	bool            isForeignKey;
	bool            isUniqueKey;
	bool            isCombinedUniqueKey;
	bool            isIndex;
	bool            isNullable;

	bool            hasDefaultValue;
};

}
