/**
 * @file TableColumnDefinitionCreateParam.cpp
 * @author Moritz Wagner
 * @date 10.08.2012
 */

#include "TableColumnDefinitionCreateParam.h"

namespace database {

TableColumnDefinitionCreateParam::TableColumnDefinitionCreateParam()
: columnType(DB_TYPE_UNKNOWN)
, columnName("")
, isPrimaryKey(false)
, isAutoGenerated(false)
, isForeignKey(false)
, isUniqueKey(false)
, isIndex(false)
, isNullable(false)
, hasDefaultValue(false)
{
}

TableColumnDefinitionCreateParam::~TableColumnDefinitionCreateParam() {
}

}
