DeepNet: database::DatabaseConnection Class Reference
database::DatabaseConnection Class Reference
generic database connection.
#include <DatabaseConnection.h>
Public Member Functions
virtual ~DatabaseConnection ()
virtual bool Connect (DatabaseConfig *config)=0
connects to a database.
virtual bool Disconnect (void)=0
disconnect from database.
virtual bool Connected (void)=0
checks if database connection is established.
virtual void Insert (const InsertStatement &stmt)=0
execute an insert statement.
virtual void InsertOrUpdate (const InsertOrUpdateStatement &stmt)=0
execute an insert or update statement.
virtual void Update (const UpdateStatement &stmt)=0
execute an update statement.
virtual void Delete (const DeleteStatement &stmt)=0
execute delete statement.
virtual void Select (const SelectStatement &stmt, std::vector< TableBase * > &results)=0
execute select statement.
virtual void TransactionStart (void)=0
start a transaction.
virtual void TransactionCommit (void)=0
commits a transaction.
virtual void TransactionRollback (void)=0
does a transaction rollback.
virtual bool LastInsertID (long long &lastInsertID)=0
gets last inserted id.
virtual bool AffectedRows (long long &affectedRows)=0
gets the number of affected rows from last statement.
virtual bool EscapeString (std::string &inEscape)=0
escapes a sql string in place.
virtual void Initialize ()
called for global initialization, once per runtime.
virtual void Shutdown ()
called for global shutdown
const DatabaseType & GetDatabaseType (void) const
gets the database type of this connection.
void Select (const SelectStatement &stmt, SelectResultContainer< TableBase > &results)
execute select statements putting results into container.
template<class T >
void Select (const SelectStatement &stmt, SelectResultContainer< T > &results)
execute select statements putting results into container of type T.
Protected Member Functions
DatabaseConnection (const DatabaseType &databaseType, const bool logQuery)
construct with a certain database::DatabaseType.
virtual void Query (const std::string &query, std::vector< TableBase * > &results)=0
execute an sql query.
virtual void Execute (const std::string &query)=0
executing an sql statement without fetching results.
Protected Attributes
bool logQuery
Private Attributes
DatabaseType databaseType
Detailed Description
generic database connection.
See also:
database::MySQLDatabaseConnection
database::DB2DatabaseConnectionx generic database connection. this class serves as a base class for a specialized, database-manufacturer related connection class.
Definition at line 35 of file DatabaseConnection.h.
Constructor & Destructor Documentation
database::DatabaseConnection::DatabaseConnection (const DatabaseType & databaseType, const bool logQuery) [protected]
construct with a certain database::DatabaseType.
Parameters:
databaseType database type.
logQuery true if all queries should be logged.
Definition at line 11 of file DatabaseConnection.cpp.
database::DatabaseConnection::~DatabaseConnection () [virtual]
Definition at line 17 of file DatabaseConnection.cpp.
Member Function Documentation
virtual bool database::DatabaseConnection::Connect (DatabaseConfig * config) [pure virtual]
connects to a database.
Parameters:
config database config.
Returns:
false on error, true on success.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by database::DatabaseHelper::CreateConnection().
virtual bool database::DatabaseConnection::Disconnect (void) [pure virtual]
disconnect from database.
Returns:
false on error, true on success.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by database::DatabaseHelper::DestroyConnection().
virtual bool database::DatabaseConnection::Connected (void) [pure virtual]
checks if database connection is established.
Returns:
false if not established, true if established.
Implemented in database::MySQLConnection, and database::DB2Connection.
virtual void database::DatabaseConnection::Query (const std::string & query, std::vector< TableBase * > & results) [protected, pure virtual]
execute an sql query.
Parameters:
query sql statement.
results gets filled with results.
Implemented in database::MySQLConnection, and database::DB2Connection.
virtual void database::DatabaseConnection::Execute (const std::string & query) [protected, pure virtual]
executing an sql statement without fetching results.
Parameters:
query sql statement.
Implemented in database::MySQLConnection, and database::DB2Connection.
virtual void database::DatabaseConnection::Insert (const InsertStatement & stmt) [pure virtual]
execute an insert statement.
Parameters:
stmt insert statement.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by database::TableBase::Insert().
virtual void database::DatabaseConnection::InsertOrUpdate (const InsertOrUpdateStatement & stmt) [pure virtual]
execute an insert or update statement.
Parameters:
stmt insert or update statement.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by database::TableBase::InsertOrUpdate().
virtual void database::DatabaseConnection::Update (const UpdateStatement & stmt) [pure virtual]
execute an update statement.
Parameters:
stmt update statement.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by bot::DatabaseRepair::FixSecondLevelLockTable(), bot::DatabaseRepair::FixSyncUrlTable(), and database::TableBase::Update().
virtual void database::DatabaseConnection::Delete (const DeleteStatement & stmt) [pure virtual]
execute delete statement.
Parameters:
stmt delete statement
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by bot::DatabaseRepair::FixCrawlerSessionTable(), and crawler::UrlFetcherThread::RemoveCrawlerSessionID().
virtual void database::DatabaseConnection::Select (const SelectStatement & stmt, std::vector< TableBase * > & results) [pure virtual]
execute select statement.
Parameters:
stmt select statement.
results gets filled with results.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by parser::CommerceSearchMatchCriteria::GetAll(), database::cacheparsedTableBase::GetBy_action_time(), database::cacheurlTableBase::GetBy_action_time(), database::cacherobotsTableBase::GetBy_action_time(), database::cachehtmlTableBase::GetBy_action_time(), database::cachesecondleveldomainTableBase::GetBy_action_time(), database::cachesubdomainTableBase::GetBy_action_time(), database::logmessagesTableBase::GetBy_actiontime(), database::logmessagesTableBase::GetBy_appName(), database::documentcodeTableBase::GetBy_code(), database::urlstagesTableBase::GetBy_content_length(), database::urlstagesTableBase::GetBy_content_md5(), database::urlstagesTableBase::GetBy_content_type(), database::hyperlinksTableBase::GetBy_count(), database::locksecondleveldomainTableBase::GetBy_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetBy_CRAWLERSESSION_ID(), database::fencedsearchTableBase::GetBy_CUSTOMER_ID(), database::customersessionsTableBase::GetBy_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetBy_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetBy_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetBy_CUSTOMER_ID(), database::customerdomainsTableBase::GetBy_CUSTOMER_ID(), database::customerqueriesTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetBy_DICT_ID(), database::dockeyTableBase::GetBy_DICT_ID(), database::customerproductkeywordsTableBase::GetBy_DICT_ID(), database::docmetaTableBase::GetBy_DICT_ID(), database::dockeyposTableBase::GetBy_DOCKEY_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::dataminingblacklistTableBase::GetBy_domain(), database::customerdomainsTableBase::GetBy_domain(), database::urlstagesTableBase::GetBy_download_speed(), database::urlstagesTableBase::GetBy_download_time(), database::urlstagesTableBase::GetBy_ext_links(), database::imagesTableBase::GetBy_found_date(), database::urlsTableBase::GetBy_found_date(), database::urlstagesTableBase::GetBy_found_date(), database::customermatchcriteriagrouptypeTableBase::GetBy_groupPosition(), database::urlstagesTableBase::GetBy_html_errors(), database::crawlersessionsTableBase::GetBy_ID(), database::keywordqueryTableBase::GetBy_ID(), database::matchcriteriaTableBase::GetBy_ID(), database::schemesTableBase::GetBy_ID(), database::searchqueryTableBase::GetBy_ID(), database::secondleveldomainsTableBase::GetBy_ID(), database::subdomainsTableBase::GetBy_ID(), database::topleveldomainsTableBase::GetBy_ID(), database::docurlTableBase::GetBy_ID(), database::customerproductkeywordsTableBase::GetBy_ID(), database::fencedsearchTableBase::GetBy_ID(), database::customerproducturlsTableBase::GetBy_ID(), database::customerqueriesTableBase::GetBy_ID(), database::latesturlstagesTableBase::GetBy_ID(), database::customersessionsTableBase::GetBy_ID(), database::customersTableBase::GetBy_ID(), database::customersyncurlTableBase::GetBy_ID(), database::dataminingalertsTableBase::GetBy_ID(), database::searchquerykeywordsTableBase::GetBy_ID(), database::dataminingblacklistTableBase::GetBy_ID(), database::dataminingcriteriaTableBase::GetBy_ID(), database::dataminingcustomersessionTableBase::GetBy_ID(), database::dataminingcustomerTableBase::GetBy_ID(), database::dictTableBase::GetBy_ID(), database::customerproductimagesTableBase::GetBy_ID(), database::documentcodeTableBase::GetBy_ID(), database::hyperlinksTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_ID(), database::customerdomainblacklistTableBase::GetBy_ID(), database::customersynccrawlerTableBase::GetBy_ID(), database::metainfoTableBase::GetBy_ID(), database::dataminingcriteriaalertsTableBase::GetBy_ID(), database::dockeyposTableBase::GetBy_ID(), database::dockeyTableBase::GetBy_ID(), database::customermatchcriteriaTableBase::GetBy_ID(), database::cacheurlTableBase::GetBy_ID(), database::cacherobotsTableBase::GetBy_ID(), database::customerproductsTableBase::GetBy_ID(), database::cachehtmlTableBase::GetBy_ID(), database::customerdomainsTableBase::GetBy_ID(), database::queryresultsTableBase::GetBy_ID(), database::cachesecondleveldomainTableBase::GetBy_ID(), database::customerkeywordsTableBase::GetBy_ID(), database::cacheparsedTableBase::GetBy_ID(), database::cachesubdomainTableBase::GetBy_ID(), database::syncurlsTableBase::GetBy_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_ID(), database::docmetaTableBase::GetBy_ID(), database::logmessagesTableBase::GetBy_ID(), database::imagesTableBase::GetBy_ID(), database::urlsTableBase::GetBy_ID(), database::urlstagesTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetBy_imageUrl(), database::urlstagesTableBase::GetBy_int_links(), database::customerdomainsTableBase::GetBy_isDomainRegex(), database::customerkeywordsTableBase::GetBy_isKeywordRegex(), database::customerdomainblacklistTableBase::GetBy_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetBy_isPrimaryKey(), database::dictTableBase::GetBy_keyword(), database::dataminingcriteriaTableBase::GetBy_keyword(), database::customerkeywordsTableBase::GetBy_keyword(), database::searchquerykeywordsTableBase::GetBy_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetBy_last_change(), database::customersTableBase::GetBy_login(), database::dataminingcustomerTableBase::GetBy_login(), database::logmessagesTableBase::GetBy_loglevel(), database::customermatchcriteriaTableBase::GetBy_MATCHCRITERIA_ID(), database::cacheurlTableBase::GetBy_matches(), database::cacherobotsTableBase::GetBy_matches(), database::cachesecondleveldomainTableBase::GetBy_matches(), database::cachehtmlTableBase::GetBy_matches(), database::cachesubdomainTableBase::GetBy_matches(), database::cacheparsedTableBase::GetBy_matches(), database::logmessagesTableBase::GetBy_message(), database::cacheurlTableBase::GetBy_misses(), database::cacherobotsTableBase::GetBy_misses(), database::cachehtmlTableBase::GetBy_misses(), database::cachesecondleveldomainTableBase::GetBy_misses(), database::cachesubdomainTableBase::GetBy_misses(), database::cacheparsedTableBase::GetBy_misses(), database::dictTableBase::GetBy_occurrence(), database::dockeyTableBase::GetBy_occurrence(), database::docmetaTableBase::GetBy_occurrence(), database::queryresultsTableBase::GetBy_order_position(), database::dockeyposTableBase::GetBy_paragraph(), database::dataminingalertsTableBase::GetBy_param(), database::customersTableBase::GetBy_password(), database::dataminingcustomerTableBase::GetBy_password(), database::customerdomainblacklistTableBase::GetBy_path(), database::imagesTableBase::GetBy_path_part(), database::urlsTableBase::GetBy_path_part(), database::logmessagesTableBase::GetBy_pid(), database::imagesTableBase::GetBy_port(), database::urlsTableBase::GetBy_port(), database::dockeyposTableBase::GetBy_position(), database::urlstagesTableBase::GetBy_primary_ip(), database::urlstagesTableBase::GetBy_primary_port(), database::customerproductkeywordsTableBase::GetBy_PRODUCT_ID(), database::customerproducturlsTableBase::GetBy_PRODUCT_ID(), database::customerproductimagesTableBase::GetBy_PRODUCT_ID(), database::customerproductsTableBase::GetBy_productBrand(), database::customerproductsTableBase::GetBy_productName(), database::customerproductsTableBase::GetBy_productNo(), database::customerqueriesTableBase::GetBy_query(), database::keywordqueryTableBase::GetBy_query_part(), database::urlstagesTableBase::GetBy_redirect_count(), database::matchcriteriaTableBase::GetBy_regex(), database::urlstagesTableBase::GetBy_response_code(), database::customerdomainsTableBase::GetBy_revisitInterval(), database::locksecondleveldomainTableBase::GetBy_schedule(), database::syncurlsTableBase::GetBy_schedule(), database::customersyncurlTableBase::GetBy_scheduled(), database::customersynccrawlerTableBase::GetBy_scheduled(), database::schemesTableBase::GetBy_scheme(), database::imagesTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_SCHEME_ID(), database::imagesTableBase::GetBy_search_part(), database::urlsTableBase::GetBy_search_part(), database::queryresultsTableBase::GetBy_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::GetBy_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetBy_session(), database::customersessionsTableBase::GetBy_session(), database::dataminingcustomersessionTableBase::GetBy_session(), database::cacheurlTableBase::GetBy_size(), database::cachehtmlTableBase::GetBy_size(), database::cacherobotsTableBase::GetBy_size(), database::cachesubdomainTableBase::GetBy_size(), database::cachesecondleveldomainTableBase::GetBy_size(), database::cacheparsedTableBase::GetBy_size(), database::subdomainsTableBase::GetBy_subdomain(), database::imagesTableBase::GetBy_SUBDOMAIN_ID(), database::urlsTableBase::GetBy_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_target(), database::hyperlinksTableBase::GetBy_TARGET_URL_ID(), database::imagelinksTableBase::GetBy_TARGET_URL_ID(), database::logmessagesTableBase::GetBy_threadName(), database::logmessagesTableBase::GetBy_tid(), database::topleveldomainsTableBase::GetBy_tld(), database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetBy_type(), database::dataminingcriteriaTableBase::GetBy_type(), database::metainfoTableBase::GetBy_type(), database::customermatchcriteriagrouptypeTableBase::GetBy_type(), database::customermatchcriteriaTableBase::GetBy_type(), database::docmetaTableBase::GetBy_type(), database::urlstagesTableBase::GetBy_upload_speed(), database::latesturlstagesTableBase::GetBy_URL_ID(), database::customersyncurlTableBase::GetBy_URL_ID(), database::docurlTableBase::GetBy_URL_ID(), database::syncurlsTableBase::GetBy_URL_ID(), database::customerproducturlsTableBase::GetBy_URL_ID(), database::queryresultsTableBase::GetBy_URL_ID(), database::urlstagesTableBase::GetBy_URL_ID(), database::imagesTableBase::GetBy_url_md5(), database::urlsTableBase::GetBy_url_md5(), database::documentcodeTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_URLSTAGE_ID(), database::latesturlstagesTableBase::GetBy_URLSTAGE_ID(), database::hyperlinksTableBase::GetBy_URLSTAGE_ID(), database::dockeyTableBase::GetBy_URLSTAGE_ID(), database::docmetaTableBase::GetBy_URLSTAGE_ID(), database::imagelinksTableBase::GetBy_URLSTAGE_ID(), database::queryresultsTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_value(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), htmlparser::TLD::Init(), queryserver::XMLQueryResponse::ProcessExistQuery(), Select(), crawler::FencedCrawler::StartCrawler(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
virtual void database::DatabaseConnection::TransactionStart (void) [pure virtual]
start a transaction.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), toolbot::DataMiningTools::RegisterDataminingAlert(), and database::TableBase::StartTransaction().
virtual void database::DatabaseConnection::TransactionCommit (void) [pure virtual]
commits a transaction.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), database::TableBase::CommitTransaction(), and toolbot::DataMiningTools::RegisterDataminingAlert().
virtual void database::DatabaseConnection::TransactionRollback (void) [pure virtual]
does a transaction rollback.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), toolbot::DataMiningTools::RegisterDataminingAlert(), and database::TableBase::RollbackTransaction().
virtual bool database::DatabaseConnection::LastInsertID (long long & lastInsertID) [pure virtual]
gets last inserted id.
Parameters:
lastInsertID gets filled with last inserted id.
Returns:
false on error, true on success.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), toolbot::DataMiningTools::InsertDataminingUser(), parser::GenericWebHtmlParserThread::InsertImages(), queryserver::XMLQueryResponse::LogQuery(), toolbot::DataMiningTools::RegisterDataminingAlert(), parser::CommerceSearchProduct::Store(), and htmlparser::DatabaseUrl::Store().
virtual bool database::DatabaseConnection::AffectedRows (long long & affectedRows) [pure virtual]
gets the number of affected rows from last statement.
Parameters:
affectedRows number of affected rows.
Returns:
false on error, true on success.
Implemented in database::MySQLConnection, and database::DB2Connection.
virtual bool database::DatabaseConnection::EscapeString (std::string & inEscape) [pure virtual]
escapes a sql string in place.
Parameters:
inEscape string to be escaped.
Returns:
false on error, true on success.
Implemented in database::MySQLConnection, and database::DB2Connection.
Referenced by database::TableColumnValue::GetForSQL().
virtual void database::DatabaseConnection::Initialize () [inline, virtual]
called for global initialization, once per runtime.
Reimplemented in database::MySQLConnection.
Definition at line 153 of file DatabaseConnection.h.
Referenced by database::DatabaseHelper::CreateConnection().
virtual void database::DatabaseConnection::Shutdown () [inline, virtual]
called for global shutdown
Reimplemented in database::MySQLConnection.
Definition at line 158 of file DatabaseConnection.h.
Referenced by database::DatabaseHelper::DestroyConnection().
const DatabaseType& database::DatabaseConnection::GetDatabaseType (void) const [inline]
gets the database type of this connection.
Returns:
database type.
Definition at line 165 of file DatabaseConnection.h.
References databaseType.
void database::DatabaseConnection::Select (const SelectStatement & stmt, SelectResultContainer< TableBase > & results) [inline]
execute select statements putting results into container.
Parameters:
stmt select statement.
results result container.
Definition at line 173 of file DatabaseConnection.h.
References tools::PointerContainer< T >::Add(), and Select().
template<class T > void database::DatabaseConnection::Select (const SelectStatement & stmt, SelectResultContainer< T > & results) [inline]
execute select statements putting results into container of type T.
type T should be derived from database::TableBase.
Parameters:
stmt select statement.
results result container.
Definition at line 190 of file DatabaseConnection.h.
References tools::PointerContainer< T >::Add(), and Select().
Member Data Documentation
DatabaseType database::DatabaseConnection::databaseType [private]
Definition at line 205 of file DatabaseConnection.h.
Referenced by GetDatabaseType().
bool database::DatabaseConnection::logQuery [protected]
Definition at line 208 of file DatabaseConnection.h.
Referenced by database::MySQLConnection::Execute().
The documentation for this class was generated from the following files:
Database/src/DatabaseConnection.h
Database/src/DatabaseConnection.cpp