DeepNet: database::Statement Class Reference
database::Statement Class Reference
implements generic sql statement.
#include <Statement.h>
Public Types
enum StatementType {
INSERT_STMT, INSERT_OR_UPDATE_STMT, UPDATE_STMT, SELECT_STMT,
DELETE_STMT
}
type of sql statement.
Public Member Functions
virtual ~Statement ()
const std::string & TableAlias (void) const
gets table alias of this statement's table.
const std::string & TableName (void) const
gets table name of this statement's table.
const std::string & DatabaseName (void) const
gets database name of this statement's table.
virtual InnerJoinCondition & InnerJoin ()=0
gets inner join condition for this statement.
virtual std::string ToSQL (database::DatabaseConnection *db) const =0
gets sql equivalent of this statement.
void SetLimit (unsigned int limit)
sets the LIMIT part of the sql statement
Protected Member Functions
Statement (const StatementType typeIn, TableDefinition *tableDefinition)
construct by type and table definition.
Statement (const StatementType typeIn, TableDefinition *tableDefinition, const std::string &tableAlias)
construct by type and table definition using an alias name for the table.
Statement (const StatementType typeIn, TableBase *tableBase)
construct by type and using an existing table's table definition.
std::string GetFullQualifiedTableName () const
gets the fully qualified name of this statement's table.
Protected Attributes
TableDefinition * tableDefinition
definition of this statement's table.
std::string tableAlias
table alias, empty if disabled.
unsigned int limit
maximum number of rows returned
StatementType typeStmt
type of this statement.
Private Member Functions
Statement (const Statement &stmt)
Private Attributes
bool deleteDefinition
Detailed Description
implements generic sql statement.
acts as a base class for all sql statements.
Definition at line 22 of file Statement.h.
Member Enumeration Documentation
enum database::Statement::StatementType
type of sql statement.
Enumerator:
INSERT_STMT
insert statement.
See also:
database::InsertStatement
INSERT_OR_UPDATE_STMT
insert or update (if duplicate).
See also:
database::InsertOrUpdateStatement
UPDATE_STMT
update statement.
See also:
database::UpdateStatement
SELECT_STMT
select statement.
See also:
database::SelectStatement
DELETE_STMT
delete statement.
See also:
database::DeleteStatement
Definition at line 28 of file Statement.h.
Constructor & Destructor Documentation
database::Statement::Statement (const Statement & stmt) [private]
Definition at line 42 of file Statement.cpp.
References THROW_EXCEPTION.
database::Statement::Statement (const StatementType typeIn, TableDefinition * tableDefinition) [protected]
construct by type and table definition.
Parameters:
typeIn statement type.
tableDefinition table definition.
Definition at line 24 of file Statement.cpp.
database::Statement::Statement (const StatementType typeIn, TableDefinition * tableDefinition, const std::string & tableAlias) [protected]
construct by type and table definition using an alias name for the table.
Parameters:
typeIn statement type.
tableDefinition table definition.
tableAlias alias name.
Definition at line 33 of file Statement.cpp.
database::Statement::Statement (const StatementType typeIn, TableBase * tableBase) [protected]
construct by type and using an existing table's table definition.
Parameters:
typeIn statement type.
tableBase existing table.
Definition at line 15 of file Statement.cpp.
database::Statement::~Statement () [virtual]
Definition at line 47 of file Statement.cpp.
References deleteDefinition, and tableDefinition.
Member Function Documentation
const std::string & database::Statement::TableAlias (void) const
gets table alias of this statement's table.
Returns:
empty if no alias specified, otherwise alias name for this statement's table.
Definition at line 73 of file Statement.cpp.
References tableAlias.
Referenced by database::SelectStatement::SelectAllColumns(), database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), and database::UpdateStatement::ToSQL().
const std::string & database::Statement::TableName (void) const
gets table name of this statement's table.
Returns:
table name.
Definition at line 53 of file Statement.cpp.
References tableDefinition, and database::TableDefinition::TableName().
const std::string & database::Statement::DatabaseName (void) const
gets database name of this statement's table.
Returns:
database name.
Definition at line 58 of file Statement.cpp.
References database::TableDefinition::DatabaseName(), and tableDefinition.
virtual InnerJoinCondition& database::Statement::InnerJoin () [pure virtual]
gets inner join condition for this statement.
Returns:
inner join condition.
Implemented in database::SelectStatement, database::UpdateStatement, database::InsertOrUpdateStatement, database::DeleteStatement, database::InsertStatement, and database::GenericStatement.
Referenced by database::customersessionsTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::dataminingblacklistTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::fencedsearchTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::customerdomainsTableBase::AddInnerJoinLeftSideOn_CUSTOMER_ID(), database::customerqueriesTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::AddInnerJoinLeftSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::AddInnerJoinLeftSideOn_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinLeftSideOn_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinLeftSideOn_DATAMININGCRITERIA_ID(), database::docurlTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::customerproductkeywordsTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::dockeyTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::docmetaTableBase::AddInnerJoinLeftSideOn_DICT_ID(), database::dockeyposTableBase::AddInnerJoinLeftSideOn_DOCKEY_ID(), database::imagelinksTableBase::AddInnerJoinLeftSideOn_IMAGE_URL_ID(), database::searchquerykeywordsTableBase::AddInnerJoinLeftSideOn_KEYWORDQUERY_ID(), database::customermatchcriteriaTableBase::AddInnerJoinLeftSideOn_MATCHCRITERIA_ID(), database::customerproducturlsTableBase::AddInnerJoinLeftSideOn_PRODUCT_ID(), database::customerproductimagesTableBase::AddInnerJoinLeftSideOn_PRODUCT_ID(), database::customerproductkeywordsTableBase::AddInnerJoinLeftSideOn_PRODUCT_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_SCHEME_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_SCHEME_ID(), database::searchquerykeywordsTableBase::AddInnerJoinLeftSideOn_SEARCHQUERY_ID(), database::queryresultsTableBase::AddInnerJoinLeftSideOn_SEARCHQUERY_ID(), database::fencedsearchTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), database::imagelinksTableBase::AddInnerJoinLeftSideOn_TARGET_URL_ID(), database::hyperlinksTableBase::AddInnerJoinLeftSideOn_TARGET_URL_ID(), database::imagesTableBase::AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), database::urlsTableBase::AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::customersyncurlTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::customerproducturlsTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::docurlTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::syncurlsTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::urlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::documentcodeTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::metainfoTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::hyperlinksTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::dockeyTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::imagelinksTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::docmetaTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::dataminingblacklistTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::customersessionsTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::fencedsearchTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::customerdomainsTableBase::AddInnerJoinRightSideOn_CUSTOMER_ID(), database::customerqueriesTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::AddInnerJoinRightSideOn_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::AddInnerJoinRightSideOn_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinRightSideOn_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::AddInnerJoinRightSideOn_DATAMININGCRITERIA_ID(), database::docurlTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::customerproductkeywordsTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::dockeyTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::docmetaTableBase::AddInnerJoinRightSideOn_DICT_ID(), database::dockeyposTableBase::AddInnerJoinRightSideOn_DOCKEY_ID(), database::imagelinksTableBase::AddInnerJoinRightSideOn_IMAGE_URL_ID(), database::searchquerykeywordsTableBase::AddInnerJoinRightSideOn_KEYWORDQUERY_ID(), database::customermatchcriteriaTableBase::AddInnerJoinRightSideOn_MATCHCRITERIA_ID(), database::customerproductkeywordsTableBase::AddInnerJoinRightSideOn_PRODUCT_ID(), database::customerproducturlsTableBase::AddInnerJoinRightSideOn_PRODUCT_ID(), database::customerproductimagesTableBase::AddInnerJoinRightSideOn_PRODUCT_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_SCHEME_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_SCHEME_ID(), database::searchquerykeywordsTableBase::AddInnerJoinRightSideOn_SEARCHQUERY_ID(), database::queryresultsTableBase::AddInnerJoinRightSideOn_SEARCHQUERY_ID(), database::fencedsearchTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_SUBDOMAIN_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_SUBDOMAIN_ID(), database::hyperlinksTableBase::AddInnerJoinRightSideOn_TARGET_URL_ID(), database::imagelinksTableBase::AddInnerJoinRightSideOn_TARGET_URL_ID(), database::urlsTableBase::AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), database::imagesTableBase::AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), database::latesturlstagesTableBase::AddInnerJoinRightSideOn_URL_ID(), database::customersyncurlTableBase::AddInnerJoinRightSideOn_URL_ID(), database::docurlTableBase::AddInnerJoinRightSideOn_URL_ID(), database::customerproducturlsTableBase::AddInnerJoinRightSideOn_URL_ID(), database::syncurlsTableBase::AddInnerJoinRightSideOn_URL_ID(), database::urlstagesTableBase::AddInnerJoinRightSideOn_URL_ID(), database::documentcodeTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::latesturlstagesTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::metainfoTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::hyperlinksTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::dockeyTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::imagelinksTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), and database::docmetaTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID().
virtual std::string database::Statement::ToSQL (database::DatabaseConnection * db) const [pure virtual]
gets sql equivalent of this statement.
Parameters:
db database connection.
Returns:
sql string.
Implemented in database::SelectStatement, database::UpdateStatement, database::InsertOrUpdateStatement, database::DeleteStatement, database::InsertStatement, and database::GenericStatement.
void database::Statement::SetLimit (unsigned int limit)
sets the LIMIT part of the sql statement
Parameters:
limit maximum number of returned rows (0 to disable).
Definition at line 68 of file Statement.cpp.
References limit.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and database::TableBase::Update().
std::string database::Statement::GetFullQualifiedTableName () const [protected]
gets the fully qualified name of this statement's table.
i.e. database_name.table_name.
Returns:
fully qualified name.
Definition at line 63 of file Statement.cpp.
References database::TableDefinition::GetFullQualifiedTableName(), and tableDefinition.
Referenced by database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
Member Data Documentation
TableDefinition* database::Statement::tableDefinition [protected]
definition of this statement's table.
Definition at line 141 of file Statement.h.
Referenced by DatabaseName(), GetFullQualifiedTableName(), database::SelectStatement::SelectAllColumns(), TableName(), and ~Statement().
std::string database::Statement::tableAlias [protected]
table alias, empty if disabled.
Definition at line 146 of file Statement.h.
Referenced by database::SelectStatement::SelectAddColumn(), database::SelectStatement::SelectAddCountColumn(), TableAlias(), and database::SelectStatement::ToSQL().
unsigned int database::Statement::limit [protected]
maximum number of rows returned
See also:
database::Statement::SetLimit
Definition at line 152 of file Statement.h.
Referenced by SetLimit(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
StatementType database::Statement::typeStmt [protected]
type of this statement.
Definition at line 157 of file Statement.h.
Referenced by database::InsertOrUpdateStatement::InsertOrUpdateStatement().
bool database::Statement::deleteDefinition [private]
Definition at line 160 of file Statement.h.
Referenced by ~Statement().
The documentation for this class was generated from the following files:
Database/src/Statement.h
Database/src/Statement.cpp