DeepNet: database::TableColumnValueTyped< T > Class Template Reference
database::TableColumnValueTyped< T > Class Template Reference
implements typed column value.
#include <TableColumnValueTyped.h>
Public Member Functions
TableColumnValueTyped (const TableColumnType &type)
construct by column type.
virtual ~TableColumnValueTyped ()
void Set (const T &in)
sets column value.
const T & Get () const
gets column value.
void Get (T &out) const
gets column value.
void Set (const std::string &in)
sets column value.
void Set (const struct tm &in)
sets column value.
void Set (const long long &in)
sets column value.
void Set (const double &in)
sets column value.
void Get (std::string &out) const
gets column value.
void Get (struct tm &out) const
gets column value.
void Get (long long &out) const
gets column value.
void Get (double &out) const
gets column value.
std::string GetForSQL (DatabaseConnection *db) const
gets escaped column value as string.
bool IsStringAllowed () const
check if string is valid for column type.
bool IsTimestampAllowed () const
check if timestamp is valid for column type.
bool IsDoubleAllowed () const
check if double is valid for column type.
bool IsLongLongAllowed () const
check if integer is valid for column type.
Protected Attributes
TableColumnType type
column type.
Private Member Functions
TableColumnValueTyped (const TableColumnValueTyped &type)
Private Attributes
T value
Detailed Description
template<class T>
class database::TableColumnValueTyped< T >
implements typed column value.
Definition at line 22 of file TableColumnValueTyped.h.
Constructor & Destructor Documentation
template<class T > database::TableColumnValueTyped< T >::TableColumnValueTyped (const TableColumnValueTyped< T > & type) [inline, private]
Definition at line 24 of file TableColumnValueTyped.h.
References THROW_EXCEPTION.
template<class T > database::TableColumnValueTyped< T >::TableColumnValueTyped (const TableColumnType & type) [inline]
construct by column type.
Parameters:
type column type.
Definition at line 33 of file TableColumnValueTyped.h.
template<class T > virtual database::TableColumnValueTyped< T >::~TableColumnValueTyped () [inline, virtual]
Definition at line 36 of file TableColumnValueTyped.h.
Member Function Documentation
template<class T > void database::TableColumnValueTyped< T >::Set (const T & in) [inline]
sets column value.
Parameters:
in column value.
Definition at line 43 of file TableColumnValueTyped.h.
References database::TableColumnValueTyped< T >::value.
template<class T > const T& database::TableColumnValueTyped< T >::Get () const [inline]
gets column value.
Returns:
column value.
Definition at line 49 of file TableColumnValueTyped.h.
References database::TableColumnValueTyped< T >::value.
template<class T > void database::TableColumnValueTyped< T >::Get (T & out) const [inline]
gets column value.
Parameters:
out column value.
Definition at line 55 of file TableColumnValueTyped.h.
References database::TableColumnValueTyped< T >::value.
void database::TableColumnValue::Set (const std::string & in) [inherited]
sets column value.
Parameters:
in column value.
Definition at line 75 of file TableColumnValue.cpp.
References database::TableColumnValue::IsStringAllowed(), and THROW_EXCEPTION.
Referenced by database::TableColumn::CopyValue(), database::TableColumnValue::Set(), and database::TableColumn::Set().
void database::TableColumnValue::Set (const struct tm & in) [inherited]
sets column value.
Parameters:
in column value.
Definition at line 89 of file TableColumnValue.cpp.
References database::TableColumnValue::IsTimestampAllowed(), database::TableColumnValue::Set(), and THROW_EXCEPTION.
void database::TableColumnValue::Set (const long long & in) [inherited]
sets column value.
Parameters:
in column value.
Definition at line 103 of file TableColumnValue.cpp.
References database::TableColumnValue::IsLongLongAllowed(), database::TableColumnValue::Set(), and THROW_EXCEPTION.
void database::TableColumnValue::Set (const double & in) [inherited]
sets column value.
Parameters:
in column value.
Definition at line 117 of file TableColumnValue.cpp.
References database::TableColumnValue::IsDoubleAllowed(), database::TableColumnValue::Set(), and THROW_EXCEPTION.
void database::TableColumnValue::Get (std::string & out) const [inherited]
gets column value.
Parameters:
out column value.
Definition at line 82 of file TableColumnValue.cpp.
References database::TableColumnValue::IsStringAllowed(), and THROW_EXCEPTION.
Referenced by database::TableColumnValue::Get(), database::TableColumn::Get(), and database::TableColumnValue::GetForSQL().
void database::TableColumnValue::Get (struct tm & out) const [inherited]
gets column value.
Parameters:
out column value.
Definition at line 96 of file TableColumnValue.cpp.
References database::TableColumnValue::Get(), database::TableColumnValue::IsTimestampAllowed(), and THROW_EXCEPTION.
void database::TableColumnValue::Get (long long & out) const [inherited]
gets column value.
Parameters:
out column value.
Definition at line 110 of file TableColumnValue.cpp.
References database::TableColumnValue::Get(), database::TableColumnValue::IsLongLongAllowed(), and THROW_EXCEPTION.
void database::TableColumnValue::Get (double & out) const [inherited]
gets column value.
Parameters:
out column value.
Definition at line 124 of file TableColumnValue.cpp.
References database::TableColumnValue::Get(), database::TableColumnValue::IsDoubleAllowed(), and THROW_EXCEPTION.
std::string database::TableColumnValue::GetForSQL (DatabaseConnection * db) const [inherited]
gets escaped column value as string.
Parameters:
db database connection.
Returns:
escaped column value.
Definition at line 131 of file TableColumnValue.cpp.
References database::DB_TYPE_CHAR, database::DB_TYPE_DOUBLE, database::DB_TYPE_INTEGER, database::DB_TYPE_LARGE_TEXT, database::DB_TYPE_TIMESTAMP, database::DB_TYPE_VARCHAR, database::DatabaseConnection::EscapeString(), database::TableColumnValue::Get(), THROW_EXCEPTION, database::DatabaseHelper::TmToDateTime(), and database::TableColumnValue::type.
Referenced by database::TableColumn::GetForSQL().
bool database::TableColumnValue::IsStringAllowed () const [inherited]
check if string is valid for column type.
Returns:
false if invalid, true if valid.
Definition at line 26 of file TableColumnValue.cpp.
References database::DB_TYPE_CHAR, database::DB_TYPE_LARGE_TEXT, database::DB_TYPE_VARCHAR, and database::TableColumnValue::type.
Referenced by database::TableColumnValue::Get(), and database::TableColumnValue::Set().
bool database::TableColumnValue::IsTimestampAllowed () const [inherited]
check if timestamp is valid for column type.
Returns:
false if invalid, true if valid.
Definition at line 39 of file TableColumnValue.cpp.
References database::DB_TYPE_TIMESTAMP, and database::TableColumnValue::type.
Referenced by database::TableColumnValue::Get(), and database::TableColumnValue::Set().
bool database::TableColumnValue::IsDoubleAllowed () const [inherited]
check if double is valid for column type.
Returns:
false if invalid, true if valid.
Definition at line 51 of file TableColumnValue.cpp.
References database::DB_TYPE_DOUBLE, and database::TableColumnValue::type.
Referenced by database::TableColumnValue::Get(), and database::TableColumnValue::Set().
bool database::TableColumnValue::IsLongLongAllowed () const [inherited]
check if integer is valid for column type.
Returns:
false if invalid, true if valid.
Definition at line 63 of file TableColumnValue.cpp.
References database::DB_TYPE_INTEGER, and database::TableColumnValue::type.
Referenced by database::TableColumnValue::Get(), and database::TableColumnValue::Set().
Member Data Documentation
template<class T > T database::TableColumnValueTyped< T >::value [private]
Definition at line 58 of file TableColumnValueTyped.h.
Referenced by database::TableColumnValueTyped< T >::Get(), and database::TableColumnValueTyped< T >::Set().
TableColumnType database::TableColumnValue::type [protected, inherited]
column type.
Definition at line 116 of file TableColumnValue.h.
Referenced by database::TableColumnValue::GetForSQL(), database::TableColumnValue::IsDoubleAllowed(), database::TableColumnValue::IsLongLongAllowed(), database::TableColumnValue::IsStringAllowed(), and database::TableColumnValue::IsTimestampAllowed().
The documentation for this class was generated from the following file:
Database/src/TableColumnValueTyped.h