DeepNet: toolbot::UnitTestCacheUrl Class Reference
toolbot::UnitTestCacheUrl Class Reference
#include <UnitTestCacheUrl.h>
Public Member Functions
UnitTestCacheUrl (database::DatabaseConnection *connection, const std::string &urlFileName)
virtual ~UnitTestCacheUrl ()
virtual bool Run ()
virtual std::string GetName () const
Static Private Member Functions
static bool TestSingleEntry (database::DatabaseConnection *connection, UnitTestUrl &testUrl)
Private Attributes
database::DatabaseConnection * connection
std::vector< UnitTestUrl > testUrls
Detailed Description
Definition at line 22 of file UnitTestCacheUrl.h.
Constructor & Destructor Documentation
toolbot::UnitTestCacheUrl::UnitTestCacheUrl (database::DatabaseConnection * connection, const std::string & urlFileName)
Definition at line 22 of file UnitTestCacheUrl.cpp.
References toolbot::UnitTestUrl::ReadValidURLFile(), and testUrls.
toolbot::UnitTestCacheUrl::~UnitTestCacheUrl () [virtual]
Definition at line 27 of file UnitTestCacheUrl.cpp.
Member Function Documentation
bool toolbot::UnitTestCacheUrl::Run () [virtual]
Implements toolbot::UnitTest.
Definition at line 30 of file UnitTestCacheUrl.cpp.
References caching::CacheDatabaseUrl::Clear(), connection, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, TestSingleEntry(), and testUrls.
virtual std::string toolbot::UnitTestCacheUrl::GetName () const [inline, virtual]
Implements toolbot::UnitTest.
Definition at line 29 of file UnitTestCacheUrl.h.
bool toolbot::UnitTestCacheUrl::TestSingleEntry (database::DatabaseConnection * connection, UnitTestUrl & testUrl) [static, private]
Definition at line 51 of file UnitTestCacheUrl.cpp.
References toolbot::UnitTestUrl::base, toolbot::UnitTestUrl::baseUrl, network::HttpUrl::DeepMatchUrl(), network::HttpUrl::Dump(), tools::Pointer< T >::Get(), caching::CacheDatabaseUrl::GetByUrl(), caching::CacheDatabaseUrl::GetByUrlID(), caching::CacheDatabaseUrl::GetByUrlString(), network::HttpUrl::GetFullUrl(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, network::HttpUrlParser::ParseURL(), toolbot::UnitTestUrl::result, toolbot::UnitTestUrl::resultUrl, toolbot::UnitTestUrl::theUrl, and toolbot::UnitTestUrl::url.
Referenced by Run().
Member Data Documentation
database::DatabaseConnection* toolbot::UnitTestCacheUrl::connection [private]
Definition at line 35 of file UnitTestCacheUrl.h.
Referenced by Run().
std::vector<UnitTestUrl> toolbot::UnitTestCacheUrl::testUrls [private]
Definition at line 36 of file UnitTestCacheUrl.h.
Referenced by Run(), and UnitTestCacheUrl().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestCacheUrl.h
DeepNetTool/src/UnitTestCacheUrl.cpp