DeepNet: network::HttpClientFactory Class Reference
network::HttpClientFactory Class Reference
factory class for http clients
#include <HttpClientFactory.h>
Public Types
enum HttpClientType { CURL, OWN }
type of http client
Static Public Member Functions
static bool CreateInstance (const HttpClientType &type, tools::Pointer< IHttpClient > &client)
creates an instance of a http client of the specified type
Private Member Functions
HttpClientFactory ()
Detailed Description
factory class for http clients
Definition at line 21 of file HttpClientFactory.h.
Member Enumeration Documentation
enum network::HttpClientFactory::HttpClientType
type of http client
Enumerator:
CURL
use curl based http client
OWN
use own implementation of a http client
Definition at line 31 of file HttpClientFactory.h.
Constructor & Destructor Documentation
network::HttpClientFactory::HttpClientFactory () [inline, private]
Definition at line 24 of file HttpClientFactory.h.
Member Function Documentation
bool network::HttpClientFactory::CreateInstance (const HttpClientType & type, tools::Pointer< IHttpClient > & client) [static]
creates an instance of a http client of the specified type
Parameters:
type type of http client
client create client instance
Returns:
true if successful, false if unsuccesful
Definition at line 16 of file HttpClientFactory.cpp.
References CURL, OWN, and tools::Pointer< T >::Set().
Referenced by caching::CacheRobotsTxt::DownloadRobotsTxt(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), inspectorserver::InspectorServerResponse::Process(), and toolbot::UnitTestHttpClientCURL::Run().
The documentation for this class was generated from the following files:
Networking/src/HttpClientFactory.h
Networking/src/HttpClientFactory.cpp