DeepNet: domparser::NodeFactory Class Reference
domparser::NodeFactory Class Reference
factory class for generic DOM nodes
#include <NodeFactory.h>
Public Member Functions
virtual ~NodeFactory ()
Static Public Member Functions
static Node * FromToken (Document *doc, DatabaseUrl *baseUrl, const domparser::generic::Token &token)
constructs a node from a token
Private Member Functions
NodeFactory (Document *doc, DatabaseUrl *baseUrl, const domparser::generic::Token &token)
constructs a node factory instance
Node * FromToken ()
Node * CreateElement (const domparser::generic::TagToken &tagToken)
Node * CreateComment (const domparser::generic::CommentToken &commentToken)
Node * CreateDoctype (const domparser::generic::DocTypeToken &doctypeToken)
Private Attributes
Document * doc
DatabaseUrl * baseUrl
const domparser::generic::Token & token
Detailed Description
factory class for generic DOM nodes
Definition at line 27 of file NodeFactory.h.
Constructor & Destructor Documentation
domparser::NodeFactory::NodeFactory (Document * doc, DatabaseUrl * baseUrl, const domparser::generic::Token & token) [private]
constructs a node factory instance
Parameters:
doc parent document
baseUrl url for this node
token tag name/token of this node
See also:
domparser::NodeFactory::FromToken
Definition at line 21 of file NodeFactory.cpp.
domparser::NodeFactory::~NodeFactory () [virtual]
Definition at line 27 of file NodeFactory.cpp.
Member Function Documentation
Node * domparser::NodeFactory::FromToken (Document * doc, DatabaseUrl * baseUrl, const domparser::generic::Token & token) [static]
constructs a node from a token
Parameters:
doc parent document
baseUrl base url of this node
token tag token
Returns:
created node
Definition at line 30 of file NodeFactory.cpp.
References FromToken().
Referenced by FromToken().
Node * domparser::NodeFactory::FromToken () [private]
Definition at line 36 of file NodeFactory.cpp.
References domparser::Node::baseURI, baseUrl, domparser::generic::Token::CHAR, domparser::generic::Token::COMMENT, CreateComment(), CreateDoctype(), CreateElement(), domparser::generic::Token::DOCTYPE, domparser::generic::Token::TAG, token, and domparser::generic::Token::type.
Referenced by domparser::DocumentFactory::AppendComment(), domparser::DocumentFactory::InsertHtmlElement(), and domparser::DocumentFactory::OnInHeadInsertion().
Node * domparser::NodeFactory::CreateElement (const domparser::generic::TagToken & tagToken) [private]
Definition at line 65 of file NodeFactory.cpp.
References domparser::generic::TagToken::attributes, domparser::Document::createElement(), doc, domparser::generic::TagToken::name, and domparser::Element::setAttribute().
Referenced by FromToken().
Node * domparser::NodeFactory::CreateComment (const domparser::generic::CommentToken & commentToken) [private]
Definition at line 76 of file NodeFactory.cpp.
References domparser::generic::CommentToken::comment, domparser::Document::createComment(), and doc.
Referenced by FromToken().
Node * domparser::NodeFactory::CreateDoctype (const domparser::generic::DocTypeToken & doctypeToken) [private]
Definition at line 81 of file NodeFactory.cpp.
References domparser::DOMImplementation::createDocumentType(), doc, domparser::Document::implementation, domparser::generic::DocTypeToken::name, domparser::generic::DocTypeToken::public_identifier, and domparser::generic::DocTypeToken::system_identifier.
Referenced by FromToken().
Member Data Documentation
Document* domparser::NodeFactory::doc [private]
Definition at line 56 of file NodeFactory.h.
Referenced by CreateComment(), CreateDoctype(), and CreateElement().
DatabaseUrl* domparser::NodeFactory::baseUrl [private]
Definition at line 57 of file NodeFactory.h.
Referenced by FromToken().
const domparser::generic::Token& domparser::NodeFactory::token [private]
Definition at line 58 of file NodeFactory.h.
Referenced by FromToken().
The documentation for this class was generated from the following files:
DOMParser/src/NodeFactory.h
DOMParser/src/NodeFactory.cpp