DeepNet: database::urlsTableBase Class Reference
database::urlsTableBase Class Reference
wrapper class for database table urls
#include <urlsTableBase.h>
Public Member Functions
urlsTableBase ()
virtual ~urlsTableBase ()
void Get_ID (long long &out) const
gets value of ID.
void Set_ID (const long long &in)
sets value of ID.
void Get_SCHEME_ID (long long &out) const
gets value of SCHEME_ID.
void Set_SCHEME_ID (const long long &in)
sets value of SCHEME_ID.
void Get_TOPLEVELDOMAIN_ID (long long &out) const
gets value of TOPLEVELDOMAIN_ID.
void Set_TOPLEVELDOMAIN_ID (const long long &in)
sets value of TOPLEVELDOMAIN_ID.
void Get_SUBDOMAIN_ID (long long &out) const
gets value of SUBDOMAIN_ID.
void Set_SUBDOMAIN_ID (const long long &in)
sets value of SUBDOMAIN_ID.
void Get_SECONDLEVELDOMAIN_ID (long long &out) const
gets value of SECONDLEVELDOMAIN_ID.
void Set_SECONDLEVELDOMAIN_ID (const long long &in)
sets value of SECONDLEVELDOMAIN_ID.
void Get_port (long long &out) const
gets value of port.
void Set_port (const long long &in)
sets value of port.
void Get_path_part (std::string &out) const
gets value of path_part.
void Set_path_part (const std::string &in)
sets value of path_part.
void Get_search_part (std::string &out) const
gets value of search_part.
void Set_search_part (const std::string &in)
sets value of search_part.
void Get_url_md5 (std::string &out) const
gets value of url_md5.
void Set_url_md5 (const std::string &in)
sets value of url_md5.
void Get_found_date (struct tm &out) const
gets value of found_date.
void Set_found_date (const struct tm &in)
sets value of found_date.
const TableDefinition * GetConstTableDefinition () const
gets const table definition.
TableDefinition * GetTableDefinition ()
gets table definition.
const TableColumn * GetConstColumnByName (const std::string &columnName) const
finds column by it's name.
TableColumn * GetColumnByName (const std::string &columnName)
finds column by it's name.
std::vector< TableColumn * > & GetColumns ()
gets list of columns.
const std::vector< TableColumn * > & GetConstColumns () const
gets const list of columns.
void SetTableAlias (const std::string &tableAlias)
sets alias name.
const std::string & GetTableAlias () const
gets alias name.
void Insert (DatabaseConnection *db)
inserts this table.
void InsertOrUpdate (DatabaseConnection *db)
inserts or updates this table.
void InsertOrUpdate (DatabaseConnection *db, TableColumnDefinition *sumColumn)
inserts or updates this table adding SUM()-type columns.
void InsertOrUpdate (DatabaseConnection *db, const std::vector< TableColumnDefinition * > &sumColumn)
inserts or updates this table adding SUM()-type columns.
void Update (DatabaseConnection *db, const TableBaseUpdateParam &param) const
updates this table.
void CopyColumns (const TableBase *base)
copies column definitions and values from another table.
Static Public Member Functions
static TableDefinition * CreateTableDefinition ()
factory function for urls's table definition.
static void GetBy_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of ID.
static void GetBy_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of ID.
static void GetBy_SCHEME_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of SCHEME_ID.
static void GetBy_SCHEME_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of SCHEME_ID.
static void GetBy_TOPLEVELDOMAIN_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of TOPLEVELDOMAIN_ID.
static void GetBy_TOPLEVELDOMAIN_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of TOPLEVELDOMAIN_ID.
static void GetBy_SUBDOMAIN_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of SUBDOMAIN_ID.
static void GetBy_SUBDOMAIN_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of SUBDOMAIN_ID.
static void GetBy_SECONDLEVELDOMAIN_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of SECONDLEVELDOMAIN_ID.
static void GetBy_SECONDLEVELDOMAIN_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of SECONDLEVELDOMAIN_ID.
static void GetBy_port (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of port.
static void GetBy_port (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of port.
static void GetBy_path_part (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of path_part.
static void GetBy_path_part (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of path_part.
static void GetBy_search_part (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of search_part.
static void GetBy_search_part (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of search_part.
static void GetBy_url_md5 (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of url_md5.
static void GetBy_url_md5 (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of url_md5.
static void GetBy_found_date (DatabaseConnection *db, const struct tm &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by a value of found_date.
static void GetBy_found_date (DatabaseConnection *db, const std::vector< struct tm > &fieldValue, SelectResultContainer< urlsTableBase > &results)
gets rows by multiple values of found_date.
static void AddInnerJoinLeftSideOn_SCHEME_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinLeftSideOn_SCHEME_ID (Statement &stmt)
static void AddInnerJoinRightSideOn_SCHEME_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinRightSideOn_SCHEME_ID (Statement &stmt)
static void AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID (Statement &stmt)
static void AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID (Statement &stmt)
static void AddInnerJoinLeftSideOn_SUBDOMAIN_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinLeftSideOn_SUBDOMAIN_ID (Statement &stmt)
static void AddInnerJoinRightSideOn_SUBDOMAIN_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinRightSideOn_SUBDOMAIN_ID (Statement &stmt)
static void AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID (Statement &stmt)
static void AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID (const std::string &joinTableAlias, const std::string &joinColumnAlias, const std::string &referencedTableAlias, const std::string &referencedColumnAlias, Statement &stmt)
static void AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID (Statement &stmt)
static void GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of ID.
static void GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of ID.
static void GetWhereColumnsFor_SCHEME_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of SCHEME_ID.
static void GetWhereColumnsFor_SCHEME_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of SCHEME_ID.
static void GetWhereColumnsFor_TOPLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of TOPLEVELDOMAIN_ID.
static void GetWhereColumnsFor_TOPLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of TOPLEVELDOMAIN_ID.
static void GetWhereColumnsFor_SUBDOMAIN_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of SUBDOMAIN_ID.
static void GetWhereColumnsFor_SUBDOMAIN_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of SUBDOMAIN_ID.
static void GetWhereColumnsFor_SECONDLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of SECONDLEVELDOMAIN_ID.
static void GetWhereColumnsFor_SECONDLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of SECONDLEVELDOMAIN_ID.
static void GetWhereColumnsFor_port (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of port.
static void GetWhereColumnsFor_port (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of port.
static void GetWhereColumnsFor_path_part (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of path_part.
static void GetWhereColumnsFor_path_part (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of path_part.
static void GetWhereColumnsFor_search_part (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of search_part.
static void GetWhereColumnsFor_search_part (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of search_part.
static void GetWhereColumnsFor_url_md5 (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of url_md5.
static void GetWhereColumnsFor_url_md5 (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of url_md5.
static void GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam &createParam, const struct tm &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of found_date.
static void GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam &createParam, const std::vector< struct tm > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of found_date.
static TableColumnDefinition * GetDefinition_ID ()
create a column definition for column ID.
static TableColumnDefinition * GetDefinition_SCHEME_ID ()
create a column definition for column SCHEME_ID.
static TableColumnDefinition * GetDefinition_TOPLEVELDOMAIN_ID ()
create a column definition for column TOPLEVELDOMAIN_ID.
static TableColumnDefinition * GetDefinition_SUBDOMAIN_ID ()
create a column definition for column SUBDOMAIN_ID.
static TableColumnDefinition * GetDefinition_SECONDLEVELDOMAIN_ID ()
create a column definition for column SECONDLEVELDOMAIN_ID.
static TableColumnDefinition * GetDefinition_port ()
create a column definition for column port.
static TableColumnDefinition * GetDefinition_path_part ()
create a column definition for column path_part.
static TableColumnDefinition * GetDefinition_search_part ()
create a column definition for column search_part.
static TableColumnDefinition * GetDefinition_url_md5 ()
create a column definition for column url_md5.
static TableColumnDefinition * GetDefinition_found_date ()
create a column definition for column found_date.
static TableBase * CreateInstance (const TableDefinitionCreateParam &param)
factory function for this class.
Protected Member Functions
void CreateColumns ()
creates columns according to database::TableBase::definition.
Private Member Functions
urlsTableBase (const TableBase &base)
Detailed Description
wrapper class for database table urls
Definition at line 17 of file urlsTableBase.h.
Constructor & Destructor Documentation
database::urlsTableBase::urlsTableBase (const TableBase & base) [private]
Definition at line 33 of file urlsTableBase.cpp.
References THROW_EXCEPTION.
database::urlsTableBase::urlsTableBase ()
Definition at line 29 of file urlsTableBase.cpp.
database::urlsTableBase::~urlsTableBase () [virtual]
Definition at line 37 of file urlsTableBase.cpp.
Member Function Documentation
TableDefinition * database::urlsTableBase::CreateTableDefinition () [static]
factory function for urls's table definition.
Returns:
table definition.
Definition at line 40 of file urlsTableBase.cpp.
References database::TableBase::CreateInstance().
Referenced by AddInnerJoinLeftSideOn_SCHEME_ID(), AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), AddInnerJoinRightSideOn_SCHEME_ID(), AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), AddInnerJoinRightSideOn_SUBDOMAIN_ID(), AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), GetBy_found_date(), GetBy_ID(), GetBy_path_part(), GetBy_port(), GetBy_SCHEME_ID(), GetBy_search_part(), GetBy_SECONDLEVELDOMAIN_ID(), GetBy_SUBDOMAIN_ID(), GetBy_TOPLEVELDOMAIN_ID(), GetBy_url_md5(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and queryserver::XMLQueryResponse::GetPagesByDomain().
void database::urlsTableBase::Get_ID (long long & out) const
gets value of ID.
Parameters:
out value.
Definition at line 47 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_ID (const long long & in)
sets value of ID.
Parameters:
in value.
Definition at line 51 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
void database::urlsTableBase::Get_SCHEME_ID (long long & out) const
gets value of SCHEME_ID.
Parameters:
out value.
Definition at line 55 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_SCHEME_ID (const long long & in)
sets value of SCHEME_ID.
Parameters:
in value.
Definition at line 59 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_TOPLEVELDOMAIN_ID (long long & out) const
gets value of TOPLEVELDOMAIN_ID.
Parameters:
out value.
Definition at line 63 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_TOPLEVELDOMAIN_ID (const long long & in)
sets value of TOPLEVELDOMAIN_ID.
Parameters:
in value.
Definition at line 67 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_SUBDOMAIN_ID (long long & out) const
gets value of SUBDOMAIN_ID.
Parameters:
out value.
Definition at line 71 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_SUBDOMAIN_ID (const long long & in)
sets value of SUBDOMAIN_ID.
Parameters:
in value.
Definition at line 75 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_SECONDLEVELDOMAIN_ID (long long & out) const
gets value of SECONDLEVELDOMAIN_ID.
Parameters:
out value.
Definition at line 79 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_SECONDLEVELDOMAIN_ID (const long long & in)
sets value of SECONDLEVELDOMAIN_ID.
Parameters:
in value.
Definition at line 83 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_port (long long & out) const
gets value of port.
Parameters:
out value.
Definition at line 87 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_port (const long long & in)
sets value of port.
Parameters:
in value.
Definition at line 91 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_path_part (std::string & out) const
gets value of path_part.
Parameters:
out value.
Definition at line 95 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_path_part (const std::string & in)
sets value of path_part.
Parameters:
in value.
Definition at line 99 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_search_part (std::string & out) const
gets value of search_part.
Parameters:
out value.
Definition at line 103 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_search_part (const std::string & in)
sets value of search_part.
Parameters:
in value.
Definition at line 107 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_url_md5 (std::string & out) const
gets value of url_md5.
Parameters:
out value.
Definition at line 111 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
Referenced by htmlparser::DatabaseUrl::InitByTable().
void database::urlsTableBase::Set_url_md5 (const std::string & in)
sets value of url_md5.
Parameters:
in value.
Definition at line 115 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::Get_found_date (struct tm & out) const
gets value of found_date.
Parameters:
out value.
Definition at line 119 of file urlsTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::urlsTableBase::Set_found_date (const struct tm & in)
sets value of found_date.
Parameters:
in value.
Definition at line 123 of file urlsTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by htmlparser::DatabaseUrl::Store().
void database::urlsTableBase::GetBy_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of ID.
Parameters:
db database connection.
fieldValue value of ID.
results contains results.
Definition at line 132 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
Referenced by htmlparser::DatabaseUrl::InitByUrlID().
void database::urlsTableBase::GetBy_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of ID.
Parameters:
db database connection.
fieldValue values of ID.
results contains results.
Definition at line 149 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_SCHEME_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of SCHEME_ID.
Parameters:
db database connection.
fieldValue value of SCHEME_ID.
results contains results.
Definition at line 166 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_SCHEME_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_SCHEME_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of SCHEME_ID.
Parameters:
db database connection.
fieldValue values of SCHEME_ID.
results contains results.
Definition at line 183 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_SCHEME_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of TOPLEVELDOMAIN_ID.
Parameters:
db database connection.
fieldValue value of TOPLEVELDOMAIN_ID.
results contains results.
Definition at line 200 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of TOPLEVELDOMAIN_ID.
Parameters:
db database connection.
fieldValue values of TOPLEVELDOMAIN_ID.
results contains results.
Definition at line 217 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_SUBDOMAIN_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of SUBDOMAIN_ID.
Parameters:
db database connection.
fieldValue value of SUBDOMAIN_ID.
results contains results.
Definition at line 234 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_SUBDOMAIN_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_SUBDOMAIN_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of SUBDOMAIN_ID.
Parameters:
db database connection.
fieldValue values of SUBDOMAIN_ID.
results contains results.
Definition at line 251 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_SUBDOMAIN_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of SECONDLEVELDOMAIN_ID.
Parameters:
db database connection.
fieldValue value of SECONDLEVELDOMAIN_ID.
results contains results.
Definition at line 268 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of SECONDLEVELDOMAIN_ID.
Parameters:
db database connection.
fieldValue values of SECONDLEVELDOMAIN_ID.
results contains results.
Definition at line 285 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_port (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of port.
Parameters:
db database connection.
fieldValue value of port.
results contains results.
Definition at line 302 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_port(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_port (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of port.
Parameters:
db database connection.
fieldValue values of port.
results contains results.
Definition at line 319 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_port(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_path_part (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of path_part.
Parameters:
db database connection.
fieldValue value of path_part.
results contains results.
Definition at line 336 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_path_part(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_path_part (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of path_part.
Parameters:
db database connection.
fieldValue values of path_part.
results contains results.
Definition at line 353 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_path_part(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_search_part (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of search_part.
Parameters:
db database connection.
fieldValue value of search_part.
results contains results.
Definition at line 370 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_search_part(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_search_part (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of search_part.
Parameters:
db database connection.
fieldValue values of search_part.
results contains results.
Definition at line 387 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_search_part(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_url_md5 (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of url_md5.
Parameters:
db database connection.
fieldValue value of url_md5.
results contains results.
Definition at line 404 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_url_md5(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_url_md5 (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of url_md5.
Parameters:
db database connection.
fieldValue values of url_md5.
results contains results.
Definition at line 421 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_url_md5(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_found_date (DatabaseConnection * db, const struct tm & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by a value of found_date.
Parameters:
db database connection.
fieldValue value of found_date.
results contains results.
Definition at line 438 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_found_date(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::GetBy_found_date (DatabaseConnection * db, const std::vector< struct tm > & fieldValue, SelectResultContainer< urlsTableBase > & results) [static]
gets rows by multiple values of found_date.
Parameters:
db database connection.
fieldValue values of found_date.
results contains results.
Definition at line 455 of file urlsTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_found_date(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::urlsTableBase::AddInnerJoinLeftSideOn_SCHEME_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 477 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_SCHEME_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinLeftSideOn_SCHEME_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_SCHEME_ID (Statement & stmt) [static]
Definition at line 497 of file urlsTableBase.cpp.
References AddInnerJoinLeftSideOn_SCHEME_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_SCHEME_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 502 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_SCHEME_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinRightSideOn_SCHEME_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_SCHEME_ID (Statement & stmt) [static]
Definition at line 522 of file urlsTableBase.cpp.
References AddInnerJoinRightSideOn_SCHEME_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 526 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_TOPLEVELDOMAIN_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID (Statement & stmt) [static]
Definition at line 546 of file urlsTableBase.cpp.
References AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 551 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_TOPLEVELDOMAIN_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID (Statement & stmt) [static]
Definition at line 571 of file urlsTableBase.cpp.
References AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_SUBDOMAIN_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 575 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_SUBDOMAIN_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinLeftSideOn_SUBDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_SUBDOMAIN_ID (Statement & stmt) [static]
Definition at line 595 of file urlsTableBase.cpp.
References AddInnerJoinLeftSideOn_SUBDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_SUBDOMAIN_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 600 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_SUBDOMAIN_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinRightSideOn_SUBDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_SUBDOMAIN_ID (Statement & stmt) [static]
Definition at line 620 of file urlsTableBase.cpp.
References AddInnerJoinRightSideOn_SUBDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 624 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_SECONDLEVELDOMAIN_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID (Statement & stmt) [static]
Definition at line 644 of file urlsTableBase.cpp.
References AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID (const std::string & joinTableAlias, const std::string & joinColumnAlias, const std::string & referencedTableAlias, const std::string & referencedColumnAlias, Statement & stmt) [static]
Definition at line 649 of file urlsTableBase.cpp.
References database::InnerJoinCondition::AddInnerJoin(), CreateTableDefinition(), GetDefinition_ID(), GetDefinition_SECONDLEVELDOMAIN_ID(), database::Statement::InnerJoin(), database::InnerJoinEntry::joinColumnAlias, database::InnerJoinEntry::joinTableAlias, database::InnerJoinEntry::referencedColumnsAlias, and database::InnerJoinEntry::referencedTableAlias.
Referenced by AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID().
void database::urlsTableBase::AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID (Statement & stmt) [static]
Definition at line 669 of file urlsTableBase.cpp.
References AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID().
void database::urlsTableBase::GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 678 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_ID().
Referenced by GetBy_ID().
void database::urlsTableBase::GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 690 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_ID().
void database::urlsTableBase::GetWhereColumnsFor_SCHEME_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of SCHEME_ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 702 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_SCHEME_ID().
Referenced by GetBy_SCHEME_ID().
void database::urlsTableBase::GetWhereColumnsFor_SCHEME_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of SCHEME_ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 714 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_SCHEME_ID().
void database::urlsTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of TOPLEVELDOMAIN_ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 726 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_TOPLEVELDOMAIN_ID().
Referenced by GetBy_TOPLEVELDOMAIN_ID().
void database::urlsTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of TOPLEVELDOMAIN_ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 738 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_TOPLEVELDOMAIN_ID().
void database::urlsTableBase::GetWhereColumnsFor_SUBDOMAIN_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of SUBDOMAIN_ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 750 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_SUBDOMAIN_ID().
Referenced by GetBy_SUBDOMAIN_ID().
void database::urlsTableBase::GetWhereColumnsFor_SUBDOMAIN_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of SUBDOMAIN_ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 762 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_SUBDOMAIN_ID().
void database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of SECONDLEVELDOMAIN_ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 774 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_SECONDLEVELDOMAIN_ID().
Referenced by GetBy_SECONDLEVELDOMAIN_ID(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and queryserver::XMLQueryResponse::GetPagesByDomain().
void database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of SECONDLEVELDOMAIN_ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 786 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_SECONDLEVELDOMAIN_ID().
void database::urlsTableBase::GetWhereColumnsFor_port (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of port.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 798 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_port().
Referenced by GetBy_port().
void database::urlsTableBase::GetWhereColumnsFor_port (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of port.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 810 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_port().
void database::urlsTableBase::GetWhereColumnsFor_path_part (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of path_part.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 822 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_path_part().
Referenced by GetBy_path_part().
void database::urlsTableBase::GetWhereColumnsFor_path_part (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of path_part.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 834 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_path_part().
void database::urlsTableBase::GetWhereColumnsFor_search_part (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of search_part.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 846 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_search_part().
Referenced by GetBy_search_part().
void database::urlsTableBase::GetWhereColumnsFor_search_part (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of search_part.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 858 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_search_part().
void database::urlsTableBase::GetWhereColumnsFor_url_md5 (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of url_md5.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 870 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_url_md5().
Referenced by GetBy_url_md5().
void database::urlsTableBase::GetWhereColumnsFor_url_md5 (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of url_md5.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 882 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_url_md5().
void database::urlsTableBase::GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam & createParam, const struct tm & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of found_date.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 894 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_found_date().
Referenced by GetBy_found_date().
void database::urlsTableBase::GetWhereColumnsFor_found_date (const WhereConditionTableColumnCreateParam & createParam, const std::vector< struct tm > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of found_date.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 906 of file urlsTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_found_date().
TableColumnDefinition * database::urlsTableBase::GetDefinition_ID () [static]
create a column definition for column ID.
Returns:
column definition.
Definition at line 923 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_SCHEME_ID(), AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), AddInnerJoinRightSideOn_SCHEME_ID(), AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), AddInnerJoinRightSideOn_SUBDOMAIN_ID(), AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_ID().
TableColumnDefinition * database::urlsTableBase::GetDefinition_SCHEME_ID () [static]
create a column definition for column SCHEME_ID.
Returns:
column definition.
Definition at line 939 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_SCHEME_ID(), AddInnerJoinRightSideOn_SCHEME_ID(), database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_SCHEME_ID().
TableColumnDefinition * database::urlsTableBase::GetDefinition_TOPLEVELDOMAIN_ID () [static]
create a column definition for column TOPLEVELDOMAIN_ID.
Returns:
column definition.
Definition at line 955 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_TOPLEVELDOMAIN_ID(), AddInnerJoinRightSideOn_TOPLEVELDOMAIN_ID(), database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_TOPLEVELDOMAIN_ID().
TableColumnDefinition * database::urlsTableBase::GetDefinition_SUBDOMAIN_ID () [static]
create a column definition for column SUBDOMAIN_ID.
Returns:
column definition.
Definition at line 971 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_SUBDOMAIN_ID(), AddInnerJoinRightSideOn_SUBDOMAIN_ID(), database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_SUBDOMAIN_ID().
TableColumnDefinition * database::urlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID () [static]
create a column definition for column SECONDLEVELDOMAIN_ID.
Returns:
column definition.
Definition at line 987 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by AddInnerJoinLeftSideOn_SECONDLEVELDOMAIN_ID(), AddInnerJoinRightSideOn_SECONDLEVELDOMAIN_ID(), database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), and GetWhereColumnsFor_SECONDLEVELDOMAIN_ID().
TableColumnDefinition * database::urlsTableBase::GetDefinition_port () [static]
create a column definition for column port.
Returns:
column definition.
Definition at line 1003 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_port().
TableColumnDefinition * database::urlsTableBase::GetDefinition_path_part () [static]
create a column definition for column path_part.
Returns:
column definition.
Definition at line 1019 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_VARCHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_path_part().
TableColumnDefinition * database::urlsTableBase::GetDefinition_search_part () [static]
create a column definition for column search_part.
Returns:
column definition.
Definition at line 1035 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_VARCHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_search_part().
TableColumnDefinition * database::urlsTableBase::GetDefinition_url_md5 () [static]
create a column definition for column url_md5.
Returns:
column definition.
Definition at line 1051 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_CHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_url_md5().
TableColumnDefinition * database::urlsTableBase::GetDefinition_found_date () [static]
create a column definition for column found_date.
Returns:
column definition.
Definition at line 1067 of file urlsTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_TIMESTAMP, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::urlsTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_found_date().
const TableDefinition * database::TableBase::GetConstTableDefinition () const [inherited]
gets const table definition.
Returns:
table definition.
Definition at line 81 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::definition.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL().
TableDefinition * database::TableBase::GetTableDefinition () [inherited]
gets table definition.
Returns:
table definition.
Definition at line 87 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::definition.
const TableColumn * database::TableBase::GetConstColumnByName (const std::string & columnName) const [inherited]
finds column by it's name.
Parameters:
columnName column name.
Returns:
NULL if not found, column otherwise.
Definition at line 93 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, and THROW_EXCEPTION.
Referenced by database::TableBase::CopyColumns(), database::cacherobotsTableBase::Get_action_time(), database::cacheurlTableBase::Get_action_time(), database::cachesecondleveldomainTableBase::Get_action_time(), database::cachehtmlTableBase::Get_action_time(), database::cacheparsedTableBase::Get_action_time(), database::cachesubdomainTableBase::Get_action_time(), database::logmessagesTableBase::Get_actiontime(), database::logmessagesTableBase::Get_appName(), database::documentcodeTableBase::Get_code(), database::urlstagesTableBase::Get_content_length(), database::urlstagesTableBase::Get_content_md5(), database::urlstagesTableBase::Get_content_type(), database::hyperlinksTableBase::Get_count(), database::locksecondleveldomainTableBase::Get_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Get_CRAWLERSESSION_ID(), database::syncurlsTableBase::Get_CRAWLERSESSION_ID(), database::fencedsearchTableBase::Get_CUSTOMER_ID(), database::customersessionsTableBase::Get_CUSTOMER_ID(), database::customerdomainsTableBase::Get_CUSTOMER_ID(), database::dataminingblacklistTableBase::Get_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Get_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Get_CUSTOMER_ID(), database::customerproductsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerqueriesTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Get_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Get_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Get_DICT_ID(), database::docmetaTableBase::Get_DICT_ID(), database::docurlTableBase::Get_DICT_ID(), database::customerproductkeywordsTableBase::Get_DICT_ID(), database::dockeyposTableBase::Get_DOCKEY_ID(), database::secondleveldomainsTableBase::Get_domain(), database::customerdomainsTableBase::Get_domain(), database::dataminingblacklistTableBase::Get_domain(), database::urlstagesTableBase::Get_download_speed(), database::urlstagesTableBase::Get_download_time(), database::urlstagesTableBase::Get_ext_links(), database::imagesTableBase::Get_found_date(), Get_found_date(), database::urlstagesTableBase::Get_found_date(), database::customermatchcriteriagrouptypeTableBase::Get_groupPosition(), database::urlstagesTableBase::Get_html_errors(), database::dataminingcriteriaTableBase::Get_ID(), database::urlstagesTableBase::Get_ID(), database::dataminingcustomerTableBase::Get_ID(), database::dockeyTableBase::Get_ID(), database::cacherobotsTableBase::Get_ID(), database::topleveldomainsTableBase::Get_ID(), Get_ID(), database::cacheurlTableBase::Get_ID(), database::customerproductimagesTableBase::Get_ID(), database::docmetaTableBase::Get_ID(), database::cachehtmlTableBase::Get_ID(), database::docurlTableBase::Get_ID(), database::dictTableBase::Get_ID(), database::customermatchcriteriaTableBase::Get_ID(), database::customerproductsTableBase::Get_ID(), database::fencedsearchTableBase::Get_ID(), database::hyperlinksTableBase::Get_ID(), database::crawlersessionsTableBase::Get_ID(), database::imagesTableBase::Get_ID(), database::customerdomainblacklistTableBase::Get_ID(), database::documentcodeTableBase::Get_ID(), database::customerproductkeywordsTableBase::Get_ID(), database::customerqueriesTableBase::Get_ID(), database::cacheparsedTableBase::Get_ID(), database::customersessionsTableBase::Get_ID(), database::dockeyposTableBase::Get_ID(), database::latesturlstagesTableBase::Get_ID(), database::customerproducturlsTableBase::Get_ID(), database::imagelinksTableBase::Get_ID(), database::customersTableBase::Get_ID(), database::customerdomainsTableBase::Get_ID(), database::logmessagesTableBase::Get_ID(), database::customersynccrawlerTableBase::Get_ID(), database::queryresultsTableBase::Get_ID(), database::metainfoTableBase::Get_ID(), database::keywordqueryTableBase::Get_ID(), database::cachesecondleveldomainTableBase::Get_ID(), database::dataminingalertsTableBase::Get_ID(), database::customerkeywordsTableBase::Get_ID(), database::schemesTableBase::Get_ID(), database::secondleveldomainsTableBase::Get_ID(), database::searchqueryTableBase::Get_ID(), database::matchcriteriaTableBase::Get_ID(), database::customersyncurlTableBase::Get_ID(), database::syncurlsTableBase::Get_ID(), database::subdomainsTableBase::Get_ID(), database::dataminingcriteriaalertsTableBase::Get_ID(), database::cachesubdomainTableBase::Get_ID(), database::dataminingcustomersessionTableBase::Get_ID(), database::searchquerykeywordsTableBase::Get_ID(), database::dataminingblacklistTableBase::Get_ID(), database::customermatchcriteriagrouptypeTableBase::Get_ID(), database::imagelinksTableBase::Get_IMAGE_URL_ID(), database::customerproductimagesTableBase::Get_imageUrl(), database::urlstagesTableBase::Get_int_links(), database::customerdomainsTableBase::Get_isDomainRegex(), database::customerkeywordsTableBase::Get_isKeywordRegex(), database::customerdomainblacklistTableBase::Get_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Get_isPrimaryKey(), database::dataminingcriteriaTableBase::Get_keyword(), database::dictTableBase::Get_keyword(), database::customerkeywordsTableBase::Get_keyword(), database::searchquerykeywordsTableBase::Get_KEYWORDQUERY_ID(), database::urlstagesTableBase::Get_last_change(), database::customersTableBase::Get_login(), database::dataminingcustomerTableBase::Get_login(), database::logmessagesTableBase::Get_loglevel(), database::customermatchcriteriaTableBase::Get_MATCHCRITERIA_ID(), database::cacherobotsTableBase::Get_matches(), database::cachesecondleveldomainTableBase::Get_matches(), database::cachesubdomainTableBase::Get_matches(), database::cachehtmlTableBase::Get_matches(), database::cacheparsedTableBase::Get_matches(), database::cacheurlTableBase::Get_matches(), database::logmessagesTableBase::Get_message(), database::cachehtmlTableBase::Get_misses(), database::cacheparsedTableBase::Get_misses(), database::cachesecondleveldomainTableBase::Get_misses(), database::cacheurlTableBase::Get_misses(), database::cacherobotsTableBase::Get_misses(), database::cachesubdomainTableBase::Get_misses(), database::dictTableBase::Get_occurrence(), database::dockeyTableBase::Get_occurrence(), database::docmetaTableBase::Get_occurrence(), database::queryresultsTableBase::Get_order_position(), database::dockeyposTableBase::Get_paragraph(), database::dataminingalertsTableBase::Get_param(), database::customersTableBase::Get_password(), database::dataminingcustomerTableBase::Get_password(), database::customerdomainblacklistTableBase::Get_path(), Get_path_part(), database::imagesTableBase::Get_path_part(), database::logmessagesTableBase::Get_pid(), database::imagesTableBase::Get_port(), Get_port(), database::dockeyposTableBase::Get_position(), database::urlstagesTableBase::Get_primary_ip(), database::urlstagesTableBase::Get_primary_port(), database::customerproducturlsTableBase::Get_PRODUCT_ID(), database::customerproductimagesTableBase::Get_PRODUCT_ID(), database::customerproductkeywordsTableBase::Get_PRODUCT_ID(), database::customerproductsTableBase::Get_productBrand(), database::customerproductsTableBase::Get_productName(), database::customerproductsTableBase::Get_productNo(), database::customerqueriesTableBase::Get_query(), database::keywordqueryTableBase::Get_query_part(), database::urlstagesTableBase::Get_redirect_count(), database::matchcriteriaTableBase::Get_regex(), database::urlstagesTableBase::Get_response_code(), database::customerdomainsTableBase::Get_revisitInterval(), database::locksecondleveldomainTableBase::Get_schedule(), database::syncurlsTableBase::Get_schedule(), database::customersyncurlTableBase::Get_scheduled(), database::customersynccrawlerTableBase::Get_scheduled(), database::schemesTableBase::Get_scheme(), database::imagesTableBase::Get_SCHEME_ID(), Get_SCHEME_ID(), database::imagesTableBase::Get_search_part(), Get_search_part(), database::queryresultsTableBase::Get_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Get_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Get_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Get_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Get_SECONDLEVELDOMAIN_ID(), Get_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Get_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Get_session(), database::customersessionsTableBase::Get_session(), database::dataminingcustomersessionTableBase::Get_session(), database::cacherobotsTableBase::Get_size(), database::cachehtmlTableBase::Get_size(), database::cachesecondleveldomainTableBase::Get_size(), database::cacheparsedTableBase::Get_size(), database::cachesubdomainTableBase::Get_size(), database::cacheurlTableBase::Get_size(), database::subdomainsTableBase::Get_subdomain(), database::imagesTableBase::Get_SUBDOMAIN_ID(), Get_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Get_target(), database::imagelinksTableBase::Get_TARGET_URL_ID(), database::hyperlinksTableBase::Get_TARGET_URL_ID(), database::logmessagesTableBase::Get_threadName(), database::logmessagesTableBase::Get_tid(), database::topleveldomainsTableBase::Get_tld(), database::imagesTableBase::Get_TOPLEVELDOMAIN_ID(), Get_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Get_type(), database::metainfoTableBase::Get_type(), database::dataminingcriteriaTableBase::Get_type(), database::customermatchcriteriagrouptypeTableBase::Get_type(), database::customermatchcriteriaTableBase::Get_type(), database::docmetaTableBase::Get_type(), database::urlstagesTableBase::Get_upload_speed(), database::urlstagesTableBase::Get_URL_ID(), database::customersyncurlTableBase::Get_URL_ID(), database::syncurlsTableBase::Get_URL_ID(), database::latesturlstagesTableBase::Get_URL_ID(), database::customerproducturlsTableBase::Get_URL_ID(), database::queryresultsTableBase::Get_URL_ID(), database::docurlTableBase::Get_URL_ID(), database::imagesTableBase::Get_url_md5(), Get_url_md5(), database::documentcodeTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_URLSTAGE_ID(), database::dockeyTableBase::Get_URLSTAGE_ID(), database::hyperlinksTableBase::Get_URLSTAGE_ID(), database::docmetaTableBase::Get_URLSTAGE_ID(), database::latesturlstagesTableBase::Get_URLSTAGE_ID(), database::imagelinksTableBase::Get_URLSTAGE_ID(), database::queryresultsTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_value(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), htmlparser::DatabaseUrl::InitByTable(), queryserver::XMLQueryResponse::ProcessExistQuery(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
TableColumn * database::TableBase::GetColumnByName (const std::string & columnName) [inherited]
finds column by it's name.
Parameters:
columnName column name.
Returns:
NULL if not found, column otherwise.
Definition at line 105 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, and THROW_EXCEPTION.
Referenced by parser::GenericWebHtmlParserThread::InsertImages(), database::cacheparsedTableBase::Set_action_time(), database::cachesecondleveldomainTableBase::Set_action_time(), database::cachehtmlTableBase::Set_action_time(), database::cacherobotsTableBase::Set_action_time(), database::cachesubdomainTableBase::Set_action_time(), database::cacheurlTableBase::Set_action_time(), database::logmessagesTableBase::Set_actiontime(), database::logmessagesTableBase::Set_appName(), database::documentcodeTableBase::Set_code(), database::urlstagesTableBase::Set_content_length(), database::urlstagesTableBase::Set_content_md5(), database::urlstagesTableBase::Set_content_type(), database::hyperlinksTableBase::Set_count(), database::locksecondleveldomainTableBase::Set_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::customerdomainsTableBase::Set_CUSTOMER_ID(), database::customersessionsTableBase::Set_CUSTOMER_ID(), database::dataminingblacklistTableBase::Set_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Set_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Set_CUSTOMER_ID(), database::fencedsearchTableBase::Set_CUSTOMER_ID(), database::customerqueriesTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Set_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Set_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Set_DICT_ID(), database::docmetaTableBase::Set_DICT_ID(), database::docurlTableBase::Set_DICT_ID(), database::customerproductkeywordsTableBase::Set_DICT_ID(), database::dockeyposTableBase::Set_DOCKEY_ID(), database::secondleveldomainsTableBase::Set_domain(), database::customerdomainsTableBase::Set_domain(), database::dataminingblacklistTableBase::Set_domain(), database::urlstagesTableBase::Set_download_speed(), database::urlstagesTableBase::Set_download_time(), database::urlstagesTableBase::Set_ext_links(), database::imagesTableBase::Set_found_date(), Set_found_date(), database::urlstagesTableBase::Set_found_date(), database::customermatchcriteriagrouptypeTableBase::Set_groupPosition(), database::urlstagesTableBase::Set_html_errors(), database::urlstagesTableBase::Set_ID(), database::dockeyposTableBase::Set_ID(), database::dockeyTableBase::Set_ID(), database::cacheparsedTableBase::Set_ID(), database::documentcodeTableBase::Set_ID(), database::customermatchcriteriaTableBase::Set_ID(), database::dataminingcustomerTableBase::Set_ID(), database::docurlTableBase::Set_ID(), database::customerproductsTableBase::Set_ID(), database::topleveldomainsTableBase::Set_ID(), database::subdomainsTableBase::Set_ID(), database::fencedsearchTableBase::Set_ID(), database::customerproductkeywordsTableBase::Set_ID(), database::docmetaTableBase::Set_ID(), database::customerdomainblacklistTableBase::Set_ID(), database::hyperlinksTableBase::Set_ID(), database::customerproducturlsTableBase::Set_ID(), database::imagelinksTableBase::Set_ID(), database::customerdomainsTableBase::Set_ID(), database::customerqueriesTableBase::Set_ID(), database::crawlersessionsTableBase::Set_ID(), database::customerproductimagesTableBase::Set_ID(), database::keywordqueryTableBase::Set_ID(), database::customersessionsTableBase::Set_ID(), database::customersTableBase::Set_ID(), database::customerkeywordsTableBase::Set_ID(), database::customersynccrawlerTableBase::Set_ID(), database::cachesecondleveldomainTableBase::Set_ID(), database::imagesTableBase::Set_ID(), database::customersyncurlTableBase::Set_ID(), database::matchcriteriaTableBase::Set_ID(), database::metainfoTableBase::Set_ID(), database::cachehtmlTableBase::Set_ID(), database::schemesTableBase::Set_ID(), database::dataminingalertsTableBase::Set_ID(), database::latesturlstagesTableBase::Set_ID(), database::logmessagesTableBase::Set_ID(), database::searchquerykeywordsTableBase::Set_ID(), database::dataminingblacklistTableBase::Set_ID(), database::searchqueryTableBase::Set_ID(), database::cacherobotsTableBase::Set_ID(), database::syncurlsTableBase::Set_ID(), database::cachesubdomainTableBase::Set_ID(), database::queryresultsTableBase::Set_ID(), database::dataminingcriteriaTableBase::Set_ID(), database::customermatchcriteriagrouptypeTableBase::Set_ID(), Set_ID(), database::dataminingcustomersessionTableBase::Set_ID(), database::dictTableBase::Set_ID(), database::secondleveldomainsTableBase::Set_ID(), database::dataminingcriteriaalertsTableBase::Set_ID(), database::cacheurlTableBase::Set_ID(), database::imagelinksTableBase::Set_IMAGE_URL_ID(), database::customerproductimagesTableBase::Set_imageUrl(), database::urlstagesTableBase::Set_int_links(), database::customerdomainsTableBase::Set_isDomainRegex(), database::customerkeywordsTableBase::Set_isKeywordRegex(), database::customerdomainblacklistTableBase::Set_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Set_isPrimaryKey(), database::dataminingcriteriaTableBase::Set_keyword(), database::dictTableBase::Set_keyword(), database::customerkeywordsTableBase::Set_keyword(), database::searchquerykeywordsTableBase::Set_KEYWORDQUERY_ID(), database::urlstagesTableBase::Set_last_change(), database::customersTableBase::Set_login(), database::dataminingcustomerTableBase::Set_login(), database::logmessagesTableBase::Set_loglevel(), database::customermatchcriteriaTableBase::Set_MATCHCRITERIA_ID(), database::cacheparsedTableBase::Set_matches(), database::cachesecondleveldomainTableBase::Set_matches(), database::cachesubdomainTableBase::Set_matches(), database::cachehtmlTableBase::Set_matches(), database::cacherobotsTableBase::Set_matches(), database::cacheurlTableBase::Set_matches(), database::logmessagesTableBase::Set_message(), database::cacheurlTableBase::Set_misses(), database::cachesubdomainTableBase::Set_misses(), database::cachehtmlTableBase::Set_misses(), database::cacherobotsTableBase::Set_misses(), database::cacheparsedTableBase::Set_misses(), database::cachesecondleveldomainTableBase::Set_misses(), database::dictTableBase::Set_occurrence(), database::dockeyTableBase::Set_occurrence(), database::docmetaTableBase::Set_occurrence(), database::queryresultsTableBase::Set_order_position(), database::dockeyposTableBase::Set_paragraph(), database::dataminingalertsTableBase::Set_param(), database::dataminingcustomerTableBase::Set_password(), database::customersTableBase::Set_password(), database::customerdomainblacklistTableBase::Set_path(), Set_path_part(), database::imagesTableBase::Set_path_part(), database::logmessagesTableBase::Set_pid(), Set_port(), database::imagesTableBase::Set_port(), database::dockeyposTableBase::Set_position(), database::urlstagesTableBase::Set_primary_ip(), database::urlstagesTableBase::Set_primary_port(), database::customerproducturlsTableBase::Set_PRODUCT_ID(), database::customerproductimagesTableBase::Set_PRODUCT_ID(), database::customerproductkeywordsTableBase::Set_PRODUCT_ID(), database::customerproductsTableBase::Set_productBrand(), database::customerproductsTableBase::Set_productName(), database::customerproductsTableBase::Set_productNo(), database::customerqueriesTableBase::Set_query(), database::keywordqueryTableBase::Set_query_part(), database::urlstagesTableBase::Set_redirect_count(), database::matchcriteriaTableBase::Set_regex(), database::urlstagesTableBase::Set_response_code(), database::customerdomainsTableBase::Set_revisitInterval(), database::locksecondleveldomainTableBase::Set_schedule(), database::syncurlsTableBase::Set_schedule(), database::customersyncurlTableBase::Set_scheduled(), database::customersynccrawlerTableBase::Set_scheduled(), database::schemesTableBase::Set_scheme(), Set_SCHEME_ID(), database::imagesTableBase::Set_SCHEME_ID(), Set_search_part(), database::imagesTableBase::Set_search_part(), database::queryresultsTableBase::Set_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Set_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Set_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Set_SECONDLEVELDOMAIN_ID(), Set_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Set_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Set_session(), database::customersessionsTableBase::Set_session(), database::dataminingcustomersessionTableBase::Set_session(), database::cachesubdomainTableBase::Set_size(), database::cacherobotsTableBase::Set_size(), database::cachesecondleveldomainTableBase::Set_size(), database::cacheurlTableBase::Set_size(), database::cacheparsedTableBase::Set_size(), database::cachehtmlTableBase::Set_size(), database::subdomainsTableBase::Set_subdomain(), Set_SUBDOMAIN_ID(), database::imagesTableBase::Set_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Set_target(), database::hyperlinksTableBase::Set_TARGET_URL_ID(), database::imagelinksTableBase::Set_TARGET_URL_ID(), database::logmessagesTableBase::Set_threadName(), database::logmessagesTableBase::Set_tid(), database::topleveldomainsTableBase::Set_tld(), database::imagesTableBase::Set_TOPLEVELDOMAIN_ID(), Set_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Set_type(), database::customermatchcriteriagrouptypeTableBase::Set_type(), database::metainfoTableBase::Set_type(), database::dataminingcriteriaTableBase::Set_type(), database::customermatchcriteriaTableBase::Set_type(), database::docmetaTableBase::Set_type(), database::urlstagesTableBase::Set_upload_speed(), database::syncurlsTableBase::Set_URL_ID(), database::customersyncurlTableBase::Set_URL_ID(), database::latesturlstagesTableBase::Set_URL_ID(), database::urlstagesTableBase::Set_URL_ID(), database::queryresultsTableBase::Set_URL_ID(), database::docurlTableBase::Set_URL_ID(), database::customerproducturlsTableBase::Set_URL_ID(), Set_url_md5(), database::imagesTableBase::Set_url_md5(), database::documentcodeTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_URLSTAGE_ID(), database::latesturlstagesTableBase::Set_URLSTAGE_ID(), database::docmetaTableBase::Set_URLSTAGE_ID(), database::hyperlinksTableBase::Set_URLSTAGE_ID(), database::dockeyTableBase::Set_URLSTAGE_ID(), database::queryresultsTableBase::Set_URLSTAGE_ID(), database::imagelinksTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_value(), database::MySQLTableBase::SetColumnValues(), and htmlparser::DatabaseUrl::Store().
std::vector< TableColumn * > & database::TableBase::GetColumns () [inherited]
gets list of columns.
Returns:
list of columns.
Definition at line 69 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::columns.
const std::vector< TableColumn * > & database::TableBase::GetConstColumns () const [inherited]
gets const list of columns.
Returns:
list of columns.
Definition at line 75 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::columns.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL(), database::InsertStatement::ToSQL(), and database::UpdateStatement::ToSQL().
void database::TableBase::SetTableAlias (const std::string & tableAlias) [inline, inherited]
sets alias name.
Parameters:
tableAlias table name alias.
Definition at line 123 of file TableBase.h.
References database::TableBase::tableAlias.
const std::string& database::TableBase::GetTableAlias () const [inline, inherited]
gets alias name.
Returns:
tableAlias table name alias.
Definition at line 129 of file TableBase.h.
References database::TableBase::tableAlias.
void database::TableBase::Insert (DatabaseConnection * db) [inherited]
inserts this table.
Parameters:
db database connection.
Definition at line 161 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::DatabaseConnection::Insert().
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::UrlFetcherThread::GetNextCrawlerSessionID(), toolbot::DataMiningTools::InsertDataminingUser(), parser::GenericWebHtmlParserThread::InsertMeta(), queryserver::XMLQueryResponse::LogQuery(), log::DatabaseLogging::OnLog(), toolbot::DataMiningTools::RegisterDataminingAlert(), queryserver::XMLQueryResponse::SaveResults(), and bot::Bot::WatchDog().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db) [inherited]
inserts or updates this table.
Parameters:
db database connection.
Definition at line 169 of file TableBase.cpp.
Referenced by indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), parser::GenericWebHtmlParserThread::InsertImages(), parser::GenericWebHtmlParserThread::InsertLinks(), queryserver::XMLQueryResponse::LogQuery(), crawler::CommerceSearchFetcherThread::ReserveNextUrls(), parser::CommerceSearchProduct::Store(), and htmlparser::DatabaseUrl::Store().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db, TableColumnDefinition * sumColumn) [inherited]
inserts or updates this table adding SUM()-type columns.
Parameters:
db database connection.
sumColumn columns to replace with sum instead of new value.
Definition at line 174 of file TableBase.cpp.
References database::InsertOrUpdateStatement::AddSumUpColumn(), database::TableBase::CheckInitialization(), and database::DatabaseConnection::InsertOrUpdate().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db, const std::vector< TableColumnDefinition * > & sumColumn) [inherited]
inserts or updates this table adding SUM()-type columns.
Parameters:
db database connection.
sumColumn columns to replace with sum instead of new value.
Definition at line 185 of file TableBase.cpp.
References database::InsertOrUpdateStatement::AddSumUpColumns(), database::TableBase::CheckInitialization(), and database::DatabaseConnection::InsertOrUpdate().
void database::TableBase::Update (DatabaseConnection * db, const TableBaseUpdateParam & param) const [inherited]
updates this table.
Parameters:
db database connection.
param update parameters.
Definition at line 196 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBaseUpdateParam::limit, database::TableBaseUpdateParam::onlyDirtyColumns, database::TableBaseUpdateParam::orderCols, database::Statement::SetLimit(), database::DatabaseConnection::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and parser::GenericWebHtmlParserThread::UpdateUrlstageInfos().
TableBase * database::TableBase::CreateInstance (const TableDefinitionCreateParam & param) [static, inherited]
factory function for this class.
Parameters:
param table definition creation parameter.
Returns:
NULL on error, table base on success.
Definition at line 64 of file TableBase.cpp.
References database::TableDefinition::CreateInstance(), and database::TableBase::TableBase().
Referenced by database::TableBase::CreateColumns(), database::cachehtmlTableBase::CreateTableDefinition(), database::schemesTableBase::CreateTableDefinition(), database::latesturlstagesTableBase::CreateTableDefinition(), database::docurlTableBase::CreateTableDefinition(), database::logmessagesTableBase::CreateTableDefinition(), database::customerproductkeywordsTableBase::CreateTableDefinition(), database::dataminingcriteriaalertsTableBase::CreateTableDefinition(), database::dataminingcriteriaTableBase::CreateTableDefinition(), database::dictTableBase::CreateTableDefinition(), database::customerkeywordsTableBase::CreateTableDefinition(), database::dataminingblacklistTableBase::CreateTableDefinition(), database::customermatchcriteriagrouptypeTableBase::CreateTableDefinition(), database::customersyncurlTableBase::CreateTableDefinition(), database::docmetaTableBase::CreateTableDefinition(), database::queryresultsTableBase::CreateTableDefinition(), database::locksecondleveldomainTableBase::CreateTableDefinition(), database::customermatchcriteriaTableBase::CreateTableDefinition(), database::hyperlinksTableBase::CreateTableDefinition(), database::imagelinksTableBase::CreateTableDefinition(), database::searchqueryTableBase::CreateTableDefinition(), database::secondleveldomainsTableBase::CreateTableDefinition(), database::cacherobotsTableBase::CreateTableDefinition(), database::dataminingalertsTableBase::CreateTableDefinition(), database::dockeyTableBase::CreateTableDefinition(), database::dockeyposTableBase::CreateTableDefinition(), database::cachesubdomainTableBase::CreateTableDefinition(), database::customerqueriesTableBase::CreateTableDefinition(), database::customersTableBase::CreateTableDefinition(), database::dataminingcustomersessionTableBase::CreateTableDefinition(), database::cacheurlTableBase::CreateTableDefinition(), database::subdomainsTableBase::CreateTableDefinition(), database::customerproducturlsTableBase::CreateTableDefinition(), database::urlstagesTableBase::CreateTableDefinition(), database::customerdomainsTableBase::CreateTableDefinition(), database::documentcodeTableBase::CreateTableDefinition(), database::cachesecondleveldomainTableBase::CreateTableDefinition(), database::syncurlsTableBase::CreateTableDefinition(), database::customerproductsTableBase::CreateTableDefinition(), CreateTableDefinition(), database::dataminingcustomerTableBase::CreateTableDefinition(), database::keywordqueryTableBase::CreateTableDefinition(), database::matchcriteriaTableBase::CreateTableDefinition(), database::customerdomainblacklistTableBase::CreateTableDefinition(), database::imagesTableBase::CreateTableDefinition(), database::topleveldomainsTableBase::CreateTableDefinition(), database::cacheparsedTableBase::CreateTableDefinition(), database::crawlersessionsTableBase::CreateTableDefinition(), database::customerproductimagesTableBase::CreateTableDefinition(), database::fencedsearchTableBase::CreateTableDefinition(), database::customersynccrawlerTableBase::CreateTableDefinition(), database::metainfoTableBase::CreateTableDefinition(), database::searchquerykeywordsTableBase::CreateTableDefinition(), database::customersessionsTableBase::CreateTableDefinition(), database::cacheurlTableBase::GetDefinition_action_time(), database::cacherobotsTableBase::GetDefinition_action_time(), database::cachesecondleveldomainTableBase::GetDefinition_action_time(), database::cacheparsedTableBase::GetDefinition_action_time(), database::cachesubdomainTableBase::GetDefinition_action_time(), database::cachehtmlTableBase::GetDefinition_action_time(), database::logmessagesTableBase::GetDefinition_actiontime(), database::logmessagesTableBase::GetDefinition_appName(), database::documentcodeTableBase::GetDefinition_code(), database::urlstagesTableBase::GetDefinition_content_length(), database::urlstagesTableBase::GetDefinition_content_md5(), database::urlstagesTableBase::GetDefinition_content_type(), database::hyperlinksTableBase::GetDefinition_count(), database::locksecondleveldomainTableBase::GetDefinition_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetDefinition_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetDefinition_CRAWLERSESSION_ID(), database::customersessionsTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetDefinition_CUSTOMER_ID(), database::fencedsearchTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_CUSTOMER_ID(), database::customerdomainsTableBase::GetDefinition_CUSTOMER_ID(), database::customerqueriesTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetDefinition_DICT_ID(), database::customerproductkeywordsTableBase::GetDefinition_DICT_ID(), database::dockeyTableBase::GetDefinition_DICT_ID(), database::docmetaTableBase::GetDefinition_DICT_ID(), database::dockeyposTableBase::GetDefinition_DOCKEY_ID(), database::secondleveldomainsTableBase::GetDefinition_domain(), database::dataminingblacklistTableBase::GetDefinition_domain(), database::customerdomainsTableBase::GetDefinition_domain(), database::urlstagesTableBase::GetDefinition_download_speed(), database::urlstagesTableBase::GetDefinition_download_time(), database::urlstagesTableBase::GetDefinition_ext_links(), database::imagesTableBase::GetDefinition_found_date(), GetDefinition_found_date(), database::urlstagesTableBase::GetDefinition_found_date(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_groupPosition(), database::urlstagesTableBase::GetDefinition_html_errors(), database::crawlersessionsTableBase::GetDefinition_ID(), database::keywordqueryTableBase::GetDefinition_ID(), database::matchcriteriaTableBase::GetDefinition_ID(), database::schemesTableBase::GetDefinition_ID(), database::searchqueryTableBase::GetDefinition_ID(), database::secondleveldomainsTableBase::GetDefinition_ID(), database::subdomainsTableBase::GetDefinition_ID(), database::topleveldomainsTableBase::GetDefinition_ID(), database::dataminingcustomerTableBase::GetDefinition_ID(), database::dictTableBase::GetDefinition_ID(), database::customersTableBase::GetDefinition_ID(), database::dataminingcriteriaTableBase::GetDefinition_ID(), database::dataminingalertsTableBase::GetDefinition_ID(), database::customerproductimagesTableBase::GetDefinition_ID(), database::documentcodeTableBase::GetDefinition_ID(), database::customerqueriesTableBase::GetDefinition_ID(), database::customersessionsTableBase::GetDefinition_ID(), database::customersyncurlTableBase::GetDefinition_ID(), database::dataminingblacklistTableBase::GetDefinition_ID(), database::dataminingcustomersessionTableBase::GetDefinition_ID(), database::customerproductkeywordsTableBase::GetDefinition_ID(), database::docurlTableBase::GetDefinition_ID(), database::fencedsearchTableBase::GetDefinition_ID(), database::customerproducturlsTableBase::GetDefinition_ID(), database::latesturlstagesTableBase::GetDefinition_ID(), database::searchquerykeywordsTableBase::GetDefinition_ID(), database::dockeyposTableBase::GetDefinition_ID(), database::customerdomainblacklistTableBase::GetDefinition_ID(), database::customersynccrawlerTableBase::GetDefinition_ID(), database::metainfoTableBase::GetDefinition_ID(), database::dockeyTableBase::GetDefinition_ID(), database::hyperlinksTableBase::GetDefinition_ID(), database::customermatchcriteriaTableBase::GetDefinition_ID(), database::imagelinksTableBase::GetDefinition_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_ID(), database::cacheurlTableBase::GetDefinition_ID(), database::cachehtmlTableBase::GetDefinition_ID(), database::cacheparsedTableBase::GetDefinition_ID(), database::cachesecondleveldomainTableBase::GetDefinition_ID(), database::cachesubdomainTableBase::GetDefinition_ID(), database::cacherobotsTableBase::GetDefinition_ID(), database::customerproductsTableBase::GetDefinition_ID(), database::customerdomainsTableBase::GetDefinition_ID(), database::customerkeywordsTableBase::GetDefinition_ID(), database::queryresultsTableBase::GetDefinition_ID(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_ID(), database::docmetaTableBase::GetDefinition_ID(), database::syncurlsTableBase::GetDefinition_ID(), database::logmessagesTableBase::GetDefinition_ID(), GetDefinition_ID(), database::imagesTableBase::GetDefinition_ID(), database::urlstagesTableBase::GetDefinition_ID(), database::imagelinksTableBase::GetDefinition_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetDefinition_imageUrl(), database::urlstagesTableBase::GetDefinition_int_links(), database::customerdomainsTableBase::GetDefinition_isDomainRegex(), database::customerkeywordsTableBase::GetDefinition_isKeywordRegex(), database::customerdomainblacklistTableBase::GetDefinition_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_isPrimaryKey(), database::dictTableBase::GetDefinition_keyword(), database::dataminingcriteriaTableBase::GetDefinition_keyword(), database::customerkeywordsTableBase::GetDefinition_keyword(), database::searchquerykeywordsTableBase::GetDefinition_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetDefinition_last_change(), database::dataminingcustomerTableBase::GetDefinition_login(), database::customersTableBase::GetDefinition_login(), database::logmessagesTableBase::GetDefinition_loglevel(), database::customermatchcriteriaTableBase::GetDefinition_MATCHCRITERIA_ID(), database::cacherobotsTableBase::GetDefinition_matches(), database::cacheparsedTableBase::GetDefinition_matches(), database::cachehtmlTableBase::GetDefinition_matches(), database::cachesecondleveldomainTableBase::GetDefinition_matches(), database::cachesubdomainTableBase::GetDefinition_matches(), database::cacheurlTableBase::GetDefinition_matches(), database::logmessagesTableBase::GetDefinition_message(), database::cacherobotsTableBase::GetDefinition_misses(), database::cacheurlTableBase::GetDefinition_misses(), database::cachehtmlTableBase::GetDefinition_misses(), database::cacheparsedTableBase::GetDefinition_misses(), database::cachesecondleveldomainTableBase::GetDefinition_misses(), database::cachesubdomainTableBase::GetDefinition_misses(), database::dictTableBase::GetDefinition_occurrence(), database::dockeyTableBase::GetDefinition_occurrence(), database::docmetaTableBase::GetDefinition_occurrence(), database::queryresultsTableBase::GetDefinition_order_position(), database::dockeyposTableBase::GetDefinition_paragraph(), database::dataminingalertsTableBase::GetDefinition_param(), database::dataminingcustomerTableBase::GetDefinition_password(), database::customersTableBase::GetDefinition_password(), database::customerdomainblacklistTableBase::GetDefinition_path(), database::imagesTableBase::GetDefinition_path_part(), GetDefinition_path_part(), database::logmessagesTableBase::GetDefinition_pid(), database::imagesTableBase::GetDefinition_port(), GetDefinition_port(), database::dockeyposTableBase::GetDefinition_position(), database::urlstagesTableBase::GetDefinition_primary_ip(), database::urlstagesTableBase::GetDefinition_primary_port(), database::customerproductimagesTableBase::GetDefinition_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetDefinition_PRODUCT_ID(), database::customerproducturlsTableBase::GetDefinition_PRODUCT_ID(), database::customerproductsTableBase::GetDefinition_productBrand(), database::customerproductsTableBase::GetDefinition_productName(), database::customerproductsTableBase::GetDefinition_productNo(), database::customerqueriesTableBase::GetDefinition_query(), database::keywordqueryTableBase::GetDefinition_query_part(), database::urlstagesTableBase::GetDefinition_redirect_count(), database::matchcriteriaTableBase::GetDefinition_regex(), database::urlstagesTableBase::GetDefinition_response_code(), database::customerdomainsTableBase::GetDefinition_revisitInterval(), database::locksecondleveldomainTableBase::GetDefinition_schedule(), database::syncurlsTableBase::GetDefinition_schedule(), database::customersyncurlTableBase::GetDefinition_scheduled(), database::customersynccrawlerTableBase::GetDefinition_scheduled(), database::schemesTableBase::GetDefinition_scheme(), GetDefinition_SCHEME_ID(), database::imagesTableBase::GetDefinition_SCHEME_ID(), GetDefinition_search_part(), database::imagesTableBase::GetDefinition_search_part(), database::searchquerykeywordsTableBase::GetDefinition_SEARCHQUERY_ID(), database::queryresultsTableBase::GetDefinition_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), GetDefinition_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetDefinition_session(), database::customersessionsTableBase::GetDefinition_session(), database::dataminingcustomersessionTableBase::GetDefinition_session(), database::cachesubdomainTableBase::GetDefinition_size(), database::cacherobotsTableBase::GetDefinition_size(), database::cachehtmlTableBase::GetDefinition_size(), database::cachesecondleveldomainTableBase::GetDefinition_size(), database::cacheurlTableBase::GetDefinition_size(), database::cacheparsedTableBase::GetDefinition_size(), database::subdomainsTableBase::GetDefinition_subdomain(), GetDefinition_SUBDOMAIN_ID(), database::imagesTableBase::GetDefinition_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetDefinition_target(), database::hyperlinksTableBase::GetDefinition_TARGET_URL_ID(), database::imagelinksTableBase::GetDefinition_TARGET_URL_ID(), database::logmessagesTableBase::GetDefinition_threadName(), database::logmessagesTableBase::GetDefinition_tid(), database::topleveldomainsTableBase::GetDefinition_tld(), GetDefinition_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetDefinition_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetDefinition_type(), database::dataminingcriteriaTableBase::GetDefinition_type(), database::metainfoTableBase::GetDefinition_type(), database::customermatchcriteriaTableBase::GetDefinition_type(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_type(), database::docmetaTableBase::GetDefinition_type(), database::urlstagesTableBase::GetDefinition_upload_speed(), database::customersyncurlTableBase::GetDefinition_URL_ID(), database::latesturlstagesTableBase::GetDefinition_URL_ID(), database::customerproducturlsTableBase::GetDefinition_URL_ID(), database::docurlTableBase::GetDefinition_URL_ID(), database::syncurlsTableBase::GetDefinition_URL_ID(), database::queryresultsTableBase::GetDefinition_URL_ID(), database::urlstagesTableBase::GetDefinition_URL_ID(), database::imagesTableBase::GetDefinition_url_md5(), GetDefinition_url_md5(), database::documentcodeTableBase::GetDefinition_URLSTAGE_ID(), database::latesturlstagesTableBase::GetDefinition_URLSTAGE_ID(), database::metainfoTableBase::GetDefinition_URLSTAGE_ID(), database::dockeyTableBase::GetDefinition_URLSTAGE_ID(), database::hyperlinksTableBase::GetDefinition_URLSTAGE_ID(), database::imagelinksTableBase::GetDefinition_URLSTAGE_ID(), database::docmetaTableBase::GetDefinition_URLSTAGE_ID(), database::queryresultsTableBase::GetDefinition_URLSTAGE_ID(), and database::metainfoTableBase::GetDefinition_value().
void database::TableBase::CopyColumns (const TableBase * base) [inherited]
copies column definitions and values from another table.
Parameters:
base table to copy from.
Definition at line 117 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, database::TableColumn::CopyValue(), and database::TableBase::GetConstColumnByName().
void database::TableBase::CreateColumns () [protected, inherited]
creates columns according to database::TableBase::definition.
Definition at line 55 of file TableBase.cpp.
References database::TableBase::columns, database::TableBase::CreateInstance(), database::TableColumn::CreateInstance(), database::TableBase::definition, and database::TableDefinition::GetColumnDefinitions().
Referenced by database::TableBase::TableBase().
The documentation for this class was generated from the following files:
Database/generated/urlsTableBase.h
Database/generated/urlsTableBase.cpp