DeepNet: database::DB2DatabaseConfig Class Reference
database::DB2DatabaseConfig Class Reference
#include <DB2DatabaseConfig.h>
Public Member Functions
DB2DatabaseConfig ()
virtual ~DB2DatabaseConfig ()
void SetType (const DatabaseType &type)
sets the database type.
void SetHost (const std::string &host)
sets database host.
void SetPort (const int port)
sets database port.
void SetDatabaseName (const std::string &db)
sets database name.
void SetUser (const std::string &user)
sets username for database.
void SetPass (const std::string &pass)
sets password for database.
const DatabaseType & GetType () const
gets database type.
const std::string & GetHost () const
gets database host.
int GetPort () const
gets database port.
const std::string & GetDatabaseName () const
gets name of database.
const std::string & GetUser () const
gets username.
const std::string & GetPass () const
gets password.
Detailed Description
Definition at line 14 of file DB2DatabaseConfig.h.
Constructor & Destructor Documentation
database::DB2DatabaseConfig::DB2DatabaseConfig ()
Definition at line 12 of file DB2DatabaseConfig.cpp.
database::DB2DatabaseConfig::~DB2DatabaseConfig () [virtual]
Definition at line 17 of file DB2DatabaseConfig.cpp.
Member Function Documentation
void database::DatabaseConfig::SetType (const DatabaseType & type) [inline, inherited]
sets the database type.
Parameters:
type database type.
Definition at line 38 of file DatabaseConfig.h.
References database::DatabaseConfig::type.
void database::DatabaseConfig::SetHost (const std::string & host) [inline, inherited]
sets database host.
Parameters:
host hostname of database.
Definition at line 44 of file DatabaseConfig.h.
References database::DatabaseConfig::host.
Referenced by fastcgiserver::FastCGIServer::InitDatabaseConfigs(), and bot::Bot::InitDatabaseConfigs().
void database::DatabaseConfig::SetPort (const int port) [inline, inherited]
sets database port.
Parameters:
port of database.
Definition at line 50 of file DatabaseConfig.h.
References database::DatabaseConfig::port.
Referenced by fastcgiserver::FastCGIServer::InitDatabaseConfigs(), and bot::Bot::InitDatabaseConfigs().
void database::DatabaseConfig::SetDatabaseName (const std::string & db) [inline, inherited]
sets database name.
Parameters:
db of database.
Definition at line 56 of file DatabaseConfig.h.
References database::DatabaseConfig::db.
Referenced by fastcgiserver::FastCGIServer::InitDatabaseConfigs(), and bot::Bot::InitDatabaseConfigs().
void database::DatabaseConfig::SetUser (const std::string & user) [inline, inherited]
sets username for database.
Parameters:
user username.
Definition at line 62 of file DatabaseConfig.h.
References database::DatabaseConfig::user.
Referenced by fastcgiserver::FastCGIServer::InitDatabaseConfigs(), and bot::Bot::InitDatabaseConfigs().
void database::DatabaseConfig::SetPass (const std::string & pass) [inline, inherited]
sets password for database.
Parameters:
pass password.
Definition at line 68 of file DatabaseConfig.h.
References database::DatabaseConfig::pass.
Referenced by fastcgiserver::FastCGIServer::InitDatabaseConfigs(), and bot::Bot::InitDatabaseConfigs().
const DatabaseType& database::DatabaseConfig::GetType () const [inline, inherited]
gets database type.
Returns:
database type
Definition at line 74 of file DatabaseConfig.h.
References database::DatabaseConfig::type.
Referenced by database::DatabaseHelper::CreateConnection().
const std::string& database::DatabaseConfig::GetHost () const [inline, inherited]
gets database host.
Returns:
database host
Definition at line 80 of file DatabaseConfig.h.
References database::DatabaseConfig::host.
Referenced by database::MySQLConnection::Connect().
int database::DatabaseConfig::GetPort () const [inline, inherited]
gets database port.
Returns:
database port
Definition at line 86 of file DatabaseConfig.h.
References database::DatabaseConfig::port.
Referenced by database::MySQLConnection::Connect().
const std::string& database::DatabaseConfig::GetDatabaseName () const [inline, inherited]
gets name of database.
Returns:
database name
Definition at line 92 of file DatabaseConfig.h.
References database::DatabaseConfig::db.
Referenced by database::MySQLConnection::Connect().
const std::string& database::DatabaseConfig::GetUser () const [inline, inherited]
gets username.
Returns:
username
Definition at line 98 of file DatabaseConfig.h.
References database::DatabaseConfig::user.
Referenced by database::MySQLConnection::Connect().
const std::string& database::DatabaseConfig::GetPass () const [inline, inherited]
gets password.
Returns:
password
Definition at line 104 of file DatabaseConfig.h.
References database::DatabaseConfig::pass.
Referenced by database::MySQLConnection::Connect().
The documentation for this class was generated from the following files:
Database/DB2/DB2DatabaseConfig.h
Database/DB2/DB2DatabaseConfig.cpp