SET foreign_key_checks=0;

CREATE DATABASE IF NOT EXISTS `sync`;
DROP DATABASE `sync`;
CREATE DATABASE `sync`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `contents`;
DROP DATABASE `contents`;
CREATE DATABASE `contents`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `lexicon`;
DROP DATABASE `lexicon`;
CREATE DATABASE `lexicon`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `documents`;
DROP DATABASE `documents`;
CREATE DATABASE `documents`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `commercesearch`;
DROP DATABASE `commercesearch`;
CREATE DATABASE `commercesearch`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `datamining`;
DROP DATABASE `datamining`;
CREATE DATABASE `datamining`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `queryserver`;
DROP DATABASE `queryserver`;
CREATE DATABASE `queryserver`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE DATABASE IF NOT EXISTS `logging`;
DROP DATABASE `logging`;
CREATE DATABASE `logging`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
