DeepNet: htmlparser::DatabaseUrl Class Reference
htmlparser::DatabaseUrl Class Reference
class for database related functionality of URLs.
#include <DatabaseUrl.h>
Public Member Functions
virtual ~DatabaseUrl ()
bool operator== (const long long &urlID) const
const long long GetUrlID () const
gets url id.
const long long GetSchemeID () const
gets scheme id.
const long long GetSubdomainID () const
gets subdomain id.
const long long GetSecondLevelID () const
gets secondlevel domain id.
const long long GetTopLevelID () const
gets toplevel domain id.
virtual bool DeepMatchUrl (const DatabaseUrl &rhs, const bool compareAuth=false) const
compares two urls by values not by md5 string
bool operator< (HttpUrl const &rhs) const
bool operator== (HttpUrl const &rhs) const
std::string Dump () const
virtual void Dump (std::string &dump) const
bool CalculateFullUrl (const bool forceRecalculate=false)
virtual bool DeepMatchUrl (const HttpUrl &rhs, const bool compareAuth=false) const
const std::string & GetScheme () const
const std::string & GetMD5 () const
const std::string & GetDomain () const
const std::string & GetPort () const
const std::string & GetTLD () const
const std::string & GetSecondLevelDomain () const
const std::string & GetSubdomain () const
const std::string & GetPathPart () const
const std::string & GetDocument () const
const std::string & GetSearchPart () const
const std::string & GetFragmentPart () const
const std::string & GetAuthUser () const
const std::string & GetAuthPass () const
const std::string & GetFullUrl () const
const std::string GetFullDomain () const
const std::string GetFullPathSearch () const
Static Public Member Functions
static void GetBackLinks (database::DatabaseConnection *db, const long long &urlID, std::map< long long, htmlparser::DatabaseUrl > &mapIDUrls)
gets backlinks for an url.
Protected Attributes
std::string fullUrl
std::string domain
std::string scheme
std::string subdomain
std::string secondleveldomain
std::string tld
std::string port
std::string path_part
std::string search_part
std::string fragment_part
std::string auth_user
std::string auth_pass
std::string md5
bool isCalculated
Private Member Functions
DatabaseUrl ()
DatabaseUrl (database::DatabaseConnection *db, const long long &urlID)
DatabaseUrl (database::DatabaseConnection *db, const network::HttpUrl &url)
DatabaseUrl (database::DatabaseConnection *db, database::urlsTableBase *urlTbl)
void InitByHttpUrl (database::DatabaseConnection *db)
void InitByTable (database::DatabaseConnection *db, database::urlsTableBase *urlTbl)
void InitByUrlID (database::DatabaseConnection *db, const long long &urlID)
void InitByIDs (database::DatabaseConnection *db)
void Store (database::DatabaseConnection *db)
Private Attributes
long long urlID
long long schemeID
long long toplevelID
long long secondlevelID
long long subdomainID
Friends
class caching::CacheDatabaseUrl
Detailed Description
class for database related functionality of URLs.
See also:
caching::CacheDatabaseUrl
network::HttpUrl this class can only be used in conjunction with caching::CacheDatabaseUrl
Definition at line 29 of file DatabaseUrl.h.
Constructor & Destructor Documentation
htmlparser::DatabaseUrl::DatabaseUrl () [inline, private]
Definition at line 34 of file DatabaseUrl.h.
htmlparser::DatabaseUrl::DatabaseUrl (database::DatabaseConnection * db, const long long & urlID) [private]
Definition at line 35 of file DatabaseUrl.cpp.
References InitByUrlID().
htmlparser::DatabaseUrl::DatabaseUrl (database::DatabaseConnection * db, const network::HttpUrl & url) [private]
Definition at line 24 of file DatabaseUrl.cpp.
References InitByHttpUrl().
htmlparser::DatabaseUrl::DatabaseUrl (database::DatabaseConnection * db, database::urlsTableBase * urlTbl) [private]
Definition at line 46 of file DatabaseUrl.cpp.
References InitByTable().
htmlparser::DatabaseUrl::~DatabaseUrl () [virtual]
Definition at line 57 of file DatabaseUrl.cpp.
Member Function Documentation
bool htmlparser::DatabaseUrl::operator== (const long long & urlID) const
Definition at line 60 of file DatabaseUrl.cpp.
const long long htmlparser::DatabaseUrl::GetUrlID () const
gets url id.
Returns:
url id.
Definition at line 67 of file DatabaseUrl.cpp.
References urlID.
Referenced by DeepMatchUrl(), caching::CacheDatabaseUrl::GetByUrl(), caching::CacheDatabaseUrl::GetByUrlID(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), parser::GenericWebHtmlParserThread::InsertImages(), parser::GenericWebHtmlParserThread::InsertLinks(), and htmlparser::UrlInserter::InsertURL().
const long long htmlparser::DatabaseUrl::GetSchemeID () const
gets scheme id.
Returns:
scheme id.
Definition at line 72 of file DatabaseUrl.cpp.
References schemeID.
Referenced by DeepMatchUrl().
const long long htmlparser::DatabaseUrl::GetSubdomainID () const
gets subdomain id.
Returns:
subdomain id.
Definition at line 77 of file DatabaseUrl.cpp.
References subdomainID.
Referenced by caching::RobotTxt::AppliesTo(), DeepMatchUrl(), and caching::CacheRobotsTxt::IsUrlAllowed().
const long long htmlparser::DatabaseUrl::GetSecondLevelID () const
gets secondlevel domain id.
Returns:
secondlevel domain id.
Definition at line 82 of file DatabaseUrl.cpp.
References secondlevelID.
Referenced by caching::RobotTxt::AppliesTo(), DeepMatchUrl(), parser::GenericWebHtmlParserThread::InsertLinks(), and caching::CacheRobotsTxt::IsUrlAllowed().
const long long htmlparser::DatabaseUrl::GetTopLevelID () const
gets toplevel domain id.
Returns:
toplevel domain id.
Definition at line 87 of file DatabaseUrl.cpp.
References toplevelID.
Referenced by caching::RobotTxt::AppliesTo(), DeepMatchUrl(), and caching::CacheRobotsTxt::IsUrlAllowed().
bool htmlparser::DatabaseUrl::DeepMatchUrl (const DatabaseUrl & rhs, const bool compareAuth = false) const [virtual]
compares two urls by values not by md5 string
Parameters:
rhs url to compare to.
compareAuth true if authentication part should be respected in comparison.
Returns:
false if urls do not match, true if urls match.
Definition at line 248 of file DatabaseUrl.cpp.
References GetSchemeID(), GetSecondLevelID(), GetSubdomainID(), GetTopLevelID(), and GetUrlID().
void htmlparser::DatabaseUrl::GetBackLinks (database::DatabaseConnection * db, const long long & urlID, std::map< long long, htmlparser::DatabaseUrl > & mapIDUrls) [static]
gets backlinks for an url.
Parameters:
db database connection.
urlID url id for backlinks.
mapIDUrls result backlinks url ids.
Definition at line 262 of file DatabaseUrl.cpp.
Referenced by queryserver::XMLQueryResponse::GetPageRelevanceByBacklinks().
void htmlparser::DatabaseUrl::InitByHttpUrl (database::DatabaseConnection * db) [private]
Definition at line 92 of file DatabaseUrl.cpp.
References network::HttpUrl::GetFullUrl(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), htmlparser::TLD::GetTLDIDByTLD(), network::HttpUrl::scheme, schemeID, network::HttpUrl::secondleveldomain, secondlevelID, Store(), network::HttpUrl::subdomain, subdomainID, THROW_EXCEPTION, network::HttpUrl::tld, and toplevelID.
Referenced by DatabaseUrl().
void htmlparser::DatabaseUrl::InitByTable (database::DatabaseConnection * db, database::urlsTableBase * urlTbl) [private]
Definition at line 144 of file DatabaseUrl.cpp.
References network::HttpUrl::CalculateFullUrl(), database::urlsTableBase::Get_ID(), database::urlsTableBase::Get_path_part(), database::urlsTableBase::Get_port(), database::urlsTableBase::Get_SCHEME_ID(), database::urlsTableBase::Get_search_part(), database::urlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Get_SUBDOMAIN_ID(), database::urlsTableBase::Get_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Get_url_md5(), database::TableBase::GetConstColumnByName(), InitByIDs(), database::TableColumn::IsNull(), network::HttpUrl::md5, network::HttpUrl::path_part, network::HttpUrl::port, schemeID, network::HttpUrl::search_part, secondlevelID, network::HttpUrl::subdomain, subdomainID, toplevelID, and urlID.
Referenced by DatabaseUrl(), and InitByUrlID().
void htmlparser::DatabaseUrl::InitByUrlID (database::DatabaseConnection * db, const long long & urlID) [private]
Definition at line 129 of file DatabaseUrl.cpp.
References database::urlsTableBase::GetBy_ID(), network::HttpUrl::GetFullUrl(), tools::PointerContainer< T >::GetIter(), InitByTable(), tools::PointerContainer< T >::ResetIter(), tools::PointerContainer< T >::Size(), and THROW_EXCEPTION.
Referenced by DatabaseUrl().
void htmlparser::DatabaseUrl::InitByIDs (database::DatabaseConnection * db) [private]
Definition at line 176 of file DatabaseUrl.cpp.
References caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), network::HttpUrl::GetFullUrl(), htmlparser::TLD::GetTLDByID(), network::HttpUrl::port, network::HttpUrl::scheme, schemeID, network::HttpUrl::secondleveldomain, secondlevelID, network::HttpUrl::subdomain, subdomainID, THROW_EXCEPTION, network::HttpUrl::tld, and toplevelID.
Referenced by InitByTable().
void htmlparser::DatabaseUrl::Store (database::DatabaseConnection * db) [private]
Definition at line 213 of file DatabaseUrl.cpp.
References network::HttpUrl::CalculateFullUrl(), network::HttpUrl::fullUrl, database::TableBase::GetColumnByName(), network::HttpUrl::GetFullUrl(), tools::HashTools::GetMD5(), database::TableBase::InsertOrUpdate(), network::HttpUrl::isCalculated, database::DatabaseConnection::LastInsertID(), tools::TimeTools::NowUTC(), network::HttpUrl::path_part, network::HttpUrl::port, schemeID, network::HttpUrl::search_part, secondlevelID, database::urlsTableBase::Set_found_date(), database::urlsTableBase::Set_path_part(), database::urlsTableBase::Set_port(), database::urlsTableBase::Set_SCHEME_ID(), database::urlsTableBase::Set_search_part(), database::urlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Set_SUBDOMAIN_ID(), database::urlsTableBase::Set_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Set_url_md5(), database::TableColumn::SetNull(), subdomainID, THROW_EXCEPTION, toplevelID, and urlID.
Referenced by InitByHttpUrl().
bool network::HttpUrl::operator< (HttpUrl const & rhs) const [inherited]
Definition at line 29 of file HttpUrl.cpp.
References network::HttpUrl::md5.
bool network::HttpUrl::operator== (HttpUrl const & rhs) const [inherited]
Definition at line 36 of file HttpUrl.cpp.
References network::HttpUrl::md5.
std::string network::HttpUrl::Dump () const [inherited]
Definition at line 43 of file HttpUrl.cpp.
Referenced by toolbot::UnitTestUrlParser::TestInvalidUrls(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
void network::HttpUrl::Dump (std::string & dump) const [virtual, inherited]
Definition at line 50 of file HttpUrl.cpp.
References network::HttpUrl::auth_pass, network::HttpUrl::auth_user, network::HttpUrl::domain, network::HttpUrl::fragment_part, network::HttpUrl::fullUrl, network::HttpUrl::md5, network::HttpUrl::path_part, network::HttpUrl::port, network::HttpUrl::scheme, network::HttpUrl::search_part, network::HttpUrl::secondleveldomain, network::HttpUrl::subdomain, and network::HttpUrl::tld.
bool network::HttpUrl::CalculateFullUrl (const bool forceRecalculate = false) [inherited]
Definition at line 127 of file HttpUrl.cpp.
References network::HttpUrl::CalculateDomainPart(), network::HttpUrl::CalculatePortPart(), network::HttpUrl::domain, network::HttpUrl::fragment_part, network::HttpUrl::fullUrl, network::HttpUrl::GetMD5(), network::HttpUrl::isCalculated, network::HttpUrl::md5, network::HttpUrl::path_part, network::HttpUrl::port, network::HttpUrl::scheme, network::HttpUrl::search_part, and network::HttpUrl::tld.
Referenced by InitByTable(), network::HttpUrlParser::ParseURL(), Store(), toolbot::UnitTestUrlParser::TestInvalidUrls(), and toolbot::UnitTestUrlParser::TestValidUrls().
bool network::HttpUrl::DeepMatchUrl (const HttpUrl & rhs, const bool compareAuth = false) const [virtual, inherited]
Definition at line 219 of file HttpUrl.cpp.
References network::HttpUrl::GetAuthPass(), network::HttpUrl::GetAuthUser(), network::HttpUrl::GetDomain(), network::HttpUrl::GetFragmentPart(), network::HttpUrl::GetFullUrl(), network::HttpUrl::GetMD5(), network::HttpUrl::GetPathPart(), network::HttpUrl::GetPort(), network::HttpUrl::GetScheme(), network::HttpUrl::GetSearchPart(), network::HttpUrl::GetSecondLevelDomain(), network::HttpUrl::GetSubdomain(), and network::HttpUrl::GetTLD().
Referenced by toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
const std::string & network::HttpUrl::GetScheme () const [inherited]
Definition at line 154 of file HttpUrl.cpp.
References network::HttpUrl::scheme.
Referenced by network::HttpUrl::DeepMatchUrl(), and caching::CacheRobotsTxt::DownloadRobotsTxt().
const std::string & network::HttpUrl::GetMD5 () const [inherited]
Definition at line 164 of file HttpUrl.cpp.
References network::HttpUrl::md5.
Referenced by network::HttpUrl::CalculateFullUrl(), and network::HttpUrl::DeepMatchUrl().
const std::string & network::HttpUrl::GetDomain () const [inherited]
Definition at line 169 of file HttpUrl.cpp.
References network::HttpUrl::domain.
Referenced by network::HttpUrl::DeepMatchUrl(), and network::HttpUrl::GetFullDomain().
const std::string & network::HttpUrl::GetPort () const [inherited]
Definition at line 174 of file HttpUrl.cpp.
References network::HttpUrl::port.
Referenced by network::HttpUrl::DeepMatchUrl().
const std::string & network::HttpUrl::GetTLD () const [inherited]
Definition at line 179 of file HttpUrl.cpp.
References network::HttpUrl::tld.
Referenced by network::HttpUrl::DeepMatchUrl(), caching::CacheRobotsTxt::DownloadRobotsTxt(), and network::HttpUrl::GetFullDomain().
const std::string & network::HttpUrl::GetSecondLevelDomain () const [inherited]
Definition at line 184 of file HttpUrl.cpp.
References network::HttpUrl::secondleveldomain.
Referenced by network::HttpUrl::DeepMatchUrl(), and caching::CacheRobotsTxt::DownloadRobotsTxt().
const std::string & network::HttpUrl::GetSubdomain () const [inherited]
Definition at line 189 of file HttpUrl.cpp.
References network::HttpUrl::subdomain.
Referenced by network::HttpUrl::DeepMatchUrl(), and caching::CacheRobotsTxt::DownloadRobotsTxt().
const std::string & network::HttpUrl::GetPathPart () const [inherited]
Definition at line 194 of file HttpUrl.cpp.
References network::HttpUrl::path_part.
Referenced by network::HttpUrl::DeepMatchUrl().
const std::string& network::HttpUrl::GetDocument () const [inherited]
const std::string & network::HttpUrl::GetSearchPart () const [inherited]
Definition at line 199 of file HttpUrl.cpp.
References network::HttpUrl::search_part.
Referenced by network::HttpUrl::DeepMatchUrl().
const std::string & network::HttpUrl::GetFragmentPart () const [inherited]
Definition at line 204 of file HttpUrl.cpp.
References network::HttpUrl::fragment_part.
Referenced by network::HttpUrl::DeepMatchUrl().
const std::string & network::HttpUrl::GetAuthUser () const [inherited]
Definition at line 209 of file HttpUrl.cpp.
References network::HttpUrl::auth_user.
Referenced by network::HttpUrl::DeepMatchUrl().
const std::string & network::HttpUrl::GetAuthPass () const [inherited]
Definition at line 214 of file HttpUrl.cpp.
References network::HttpUrl::auth_pass.
Referenced by network::HttpUrl::DeepMatchUrl().
const std::string & network::HttpUrl::GetFullUrl () const [inherited]
Definition at line 159 of file HttpUrl.cpp.
References network::HttpUrl::fullUrl.
Referenced by network::HttpUrl::DeepMatchUrl(), htmlparser::IHtmlParserResult::DumpXML(), libxmlparser::HtmlSAX2Parser::endElement(), network::HttpClientCURL::Get(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), InitByHttpUrl(), InitByIDs(), InitByUrlID(), htmlparser::UrlInserter::InsertURL(), parser::CommerceSearchParserThread::MatchUrlCriteria(), queryserver::XMLQueryResponse::OutputResults(), libxmlparser::HtmlSAX2Parser::Parse(), inspectorserver::InspectorServerResponse::Process(), Store(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
const std::string network::HttpUrl::GetFullDomain () const [inherited]
Definition at line 243 of file HttpUrl.cpp.
References network::HttpUrl::GetDomain(), and network::HttpUrl::GetTLD().
const std::string network::HttpUrl::GetFullPathSearch () const [inherited]
Definition at line 247 of file HttpUrl.cpp.
References network::HttpUrl::path_part, and network::HttpUrl::search_part.
Referenced by caching::RobotTxt::IsAllowed().
Friends And Related Function Documentation
friend class caching::CacheDatabaseUrl [friend]
Definition at line 31 of file DatabaseUrl.h.
Member Data Documentation
long long htmlparser::DatabaseUrl::urlID [private]
Definition at line 106 of file DatabaseUrl.h.
Referenced by GetUrlID(), InitByTable(), and Store().
long long htmlparser::DatabaseUrl::schemeID [private]
Definition at line 107 of file DatabaseUrl.h.
Referenced by GetSchemeID(), InitByHttpUrl(), InitByIDs(), InitByTable(), and Store().
long long htmlparser::DatabaseUrl::toplevelID [private]
Definition at line 108 of file DatabaseUrl.h.
Referenced by GetTopLevelID(), InitByHttpUrl(), InitByIDs(), InitByTable(), and Store().
long long htmlparser::DatabaseUrl::secondlevelID [private]
Definition at line 109 of file DatabaseUrl.h.
Referenced by GetSecondLevelID(), InitByHttpUrl(), InitByIDs(), InitByTable(), and Store().
long long htmlparser::DatabaseUrl::subdomainID [private]
Definition at line 110 of file DatabaseUrl.h.
Referenced by GetSubdomainID(), InitByHttpUrl(), InitByIDs(), InitByTable(), and Store().
std::string network::HttpUrl::fullUrl [protected, inherited]
Definition at line 57 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateDomainPart(), network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetFullUrl(), network::HttpUrlParser::ParseDomain(), network::HttpUrlParser::ParseFragment(), network::HttpUrlParser::ParseQuery(), network::HttpUrlParser::ParseURL(), and Store().
std::string network::HttpUrl::domain [protected, inherited]
Definition at line 59 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateDomainPart(), network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetDomain(), network::HttpUrlParser::ParseDomain(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::scheme [protected, inherited]
Definition at line 60 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), network::HttpUrl::CalculatePortPart(), network::HttpUrl::Dump(), network::HttpUrl::GetScheme(), InitByHttpUrl(), InitByIDs(), network::HttpUrlParser::ParseScheme(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::subdomain [protected, inherited]
Definition at line 61 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateDomainPart(), network::HttpUrl::Dump(), network::HttpUrl::GetSubdomain(), InitByHttpUrl(), InitByIDs(), and InitByTable().
std::string network::HttpUrl::secondleveldomain [protected, inherited]
Definition at line 62 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateDomainPart(), network::HttpUrl::Dump(), network::HttpUrl::GetSecondLevelDomain(), InitByHttpUrl(), and InitByIDs().
std::string network::HttpUrl::tld [protected, inherited]
Definition at line 63 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateDomainPart(), network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetTLD(), InitByHttpUrl(), InitByIDs(), network::HttpUrlParser::ParseDomain(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::port [protected, inherited]
Definition at line 64 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), network::HttpUrl::CalculatePortPart(), network::HttpUrl::Dump(), network::HttpUrl::GetPort(), InitByIDs(), InitByTable(), network::HttpUrlParser::ParseDomain(), network::HttpUrlParser::ParseURL(), and Store().
std::string network::HttpUrl::path_part [protected, inherited]
Definition at line 65 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetFullPathSearch(), network::HttpUrl::GetPathPart(), InitByTable(), network::HttpUrlParser::ParsePath(), network::HttpUrlParser::ParseURL(), and Store().
std::string network::HttpUrl::search_part [protected, inherited]
Definition at line 66 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetFullPathSearch(), network::HttpUrl::GetSearchPart(), InitByTable(), network::HttpUrlParser::ParseURL(), and Store().
std::string network::HttpUrl::fragment_part [protected, inherited]
Definition at line 67 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetFragmentPart(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::auth_user [protected, inherited]
Definition at line 69 of file HttpUrl.h.
Referenced by network::HttpUrl::Dump(), network::HttpUrl::GetAuthUser(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::auth_pass [protected, inherited]
Definition at line 70 of file HttpUrl.h.
Referenced by network::HttpUrl::Dump(), network::HttpUrl::GetAuthPass(), and network::HttpUrlParser::ParseURL().
std::string network::HttpUrl::md5 [protected, inherited]
Definition at line 72 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), network::HttpUrl::Dump(), network::HttpUrl::GetMD5(), InitByTable(), network::HttpUrl::operator<(), and network::HttpUrl::operator==().
bool network::HttpUrl::isCalculated [protected, inherited]
Definition at line 74 of file HttpUrl.h.
Referenced by network::HttpUrl::CalculateFullUrl(), and Store().
The documentation for this class was generated from the following files:
HtmlParser/src/DatabaseUrl.h
HtmlParser/src/DatabaseUrl.cpp