DeepNet: threading::Mutex Class Reference
threading::Mutex Class Reference
generic mutex class.
#include <Mutex.h>
Public Member Functions
Mutex (const bool isErrorChecked=false)
virtual ~Mutex (void)
bool Lock (void)
waits for and locks mutex.
bool Unlock (void)
unlocks mutex.
bool IsLocked (void) const
checks if mutex is locked.
Private Member Functions
Mutex (const Mutex &)
Mutex & operator= (const Mutex &rhs)
Private Attributes
volatile bool m_bIsLocked
const bool isErrorChecked
volatile long int tid
pthread_mutex_t m_tMutex
Detailed Description
generic mutex class.
Definition at line 17 of file Mutex.h.
Constructor & Destructor Documentation
threading::Mutex::Mutex (const bool isErrorChecked = false)
Definition at line 15 of file Mutex.cpp.
References m_tMutex.
threading::Mutex::~Mutex (void) [virtual]
Definition at line 23 of file Mutex.cpp.
References m_bIsLocked, m_tMutex, and Unlock().
threading::Mutex::Mutex (const Mutex &) [inline, private]
Definition at line 23 of file Mutex.h.
Member Function Documentation
Mutex& threading::Mutex::operator= (const Mutex & rhs) [inline, private]
Definition at line 24 of file Mutex.h.
bool threading::Mutex::Lock (void)
waits for and locks mutex.
Returns:
false on error, true on success.
Definition at line 31 of file Mutex.cpp.
References isErrorChecked, m_bIsLocked, m_tMutex, and tid.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), threading::AutoMutex::AutoMutex(), database::DatabaseHelper::CreateConnection(), caching::Cache< long long, CacheHtmlEntry >::DeleteItem(), database::DatabaseHelper::DestroyConnection(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), tools::SynchronizedIDArray::GetID(), domparser::NamedCharacterReferences::InitStaticNamedCharRefs(), log::Logging::Log_Intern(), tools::TokenBucket::RefillThreadFunc(), threading::Thread::SetShallEnd(), bot::Bot::SignalHandler(), and tools::TokenBucket::TryRemoveTokens().
bool threading::Mutex::Unlock (void)
unlocks mutex.
Returns:
false on error, true on success.
Definition at line 42 of file Mutex.cpp.
References isErrorChecked, m_bIsLocked, m_tMutex, and tid.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), database::DatabaseHelper::CreateConnection(), caching::Cache< long long, CacheHtmlEntry >::DeleteItem(), database::DatabaseHelper::DestroyConnection(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), tools::SynchronizedIDArray::GetID(), domparser::NamedCharacterReferences::InitStaticNamedCharRefs(), log::Logging::Log_Intern(), tools::TokenBucket::RefillThreadFunc(), threading::Thread::SetShallEnd(), bot::Bot::SignalHandler(), tools::TokenBucket::TryRemoveTokens(), threading::AutoMutex::~AutoMutex(), and ~Mutex().
bool threading::Mutex::IsLocked (void) const
checks if mutex is locked.
Returns:
false on non-locked, true if locked.
Definition at line 52 of file Mutex.cpp.
References m_bIsLocked.
Referenced by threading::Thread::SetShallEnd(), and threading::Thread::ShallEnd().
Member Data Documentation
volatile bool threading::Mutex::m_bIsLocked [private]
Definition at line 46 of file Mutex.h.
Referenced by IsLocked(), Lock(), Unlock(), and ~Mutex().
const bool threading::Mutex::isErrorChecked [private]
Definition at line 47 of file Mutex.h.
Referenced by Lock(), and Unlock().
volatile long int threading::Mutex::tid [private]
Definition at line 48 of file Mutex.h.
Referenced by Lock(), and Unlock().
pthread_mutex_t threading::Mutex::m_tMutex [private]
Definition at line 49 of file Mutex.h.
Referenced by Lock(), Mutex(), Unlock(), and ~Mutex().
The documentation for this class was generated from the following files:
Threading/src/Mutex.h
Threading/src/Mutex.cpp