DeepNet: fastcgiserver::FastCGIServerThread Class Reference
fastcgiserver::FastCGIServerThread Class Reference
#include <FastCGIServerThread.h>
Public Member Functions
FastCGIServerThread (database::DatabaseConfig *databaseConfig, threading::Mutex *acceptMutex, const int port, const int backlog=0)
FastCGIServerThread (database::DatabaseConfig *databaseConfig, threading::Mutex *acceptMutex, const std::string &filename, const int backlog=0)
virtual ~FastCGIServerThread ()
database::DatabaseHelper & DB ()
tools::SpellChecking & SpellChecker ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
virtual FastCGIRequest * CreateRequest ()=0
virtual FastCGIResponse * CreateResponse (database::DatabaseHelper &dbHelper, FastCGIRequest *request)=0
Static Private Member Functions
static void * FastCGIServerThreadFunc (threading::Thread::THREAD_PARAM *param)
Private Attributes
tools::SpellChecking spellChecker
database::DatabaseHelper dbHelper
database::DatabaseConfig * databaseConfig
FCGX_Request request
FastCGISocket fcgiSocket
bool isFileSocket
int port
int backlog
std::string filename
threading::Mutex * acceptMutex
Detailed Description
Definition at line 22 of file FastCGIServerThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
fastcgiserver::FastCGIServerThread::FastCGIServerThread (database::DatabaseConfig * databaseConfig, threading::Mutex * acceptMutex, const int port, const int backlog = 0)
Definition at line 19 of file FastCGIServerThread.cpp.
fastcgiserver::FastCGIServerThread::FastCGIServerThread (database::DatabaseConfig * databaseConfig, threading::Mutex * acceptMutex, const std::string & filename, const int backlog = 0)
Definition at line 31 of file FastCGIServerThread.cpp.
fastcgiserver::FastCGIServerThread::~FastCGIServerThread () [virtual]
Definition at line 43 of file FastCGIServerThread.cpp.
Member Function Documentation
database::DatabaseHelper& fastcgiserver::FastCGIServerThread::DB () [inline]
Definition at line 30 of file FastCGIServerThread.h.
References dbHelper.
Referenced by FastCGIServerThreadFunc().
tools::SpellChecking& fastcgiserver::FastCGIServerThread::SpellChecker () [inline]
Definition at line 31 of file FastCGIServerThread.h.
References spellChecker.
Referenced by suggestserver::SuggestServerResponse::Process(), and fastcgiserver::FastCGIServer::StartServer().
virtual FastCGIRequest* fastcgiserver::FastCGIServerThread::CreateRequest () [private, pure virtual]
Implemented in queryserver::XMLQueryServerThread, inspectorserver::InspectorServerThread, and suggestserver::SuggestServerThread.
Referenced by FastCGIServerThreadFunc().
virtual FastCGIResponse* fastcgiserver::FastCGIServerThread::CreateResponse (database::DatabaseHelper & dbHelper, FastCGIRequest * request) [private, pure virtual]
Implemented in queryserver::XMLQueryServerThread, inspectorserver::InspectorServerThread, and suggestserver::SuggestServerThread.
Referenced by FastCGIServerThreadFunc().
void * fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc (threading::Thread::THREAD_PARAM * param) [static, private]
Definition at line 47 of file FastCGIServerThread.cpp.
References acceptMutex, database::DatabaseHelper::CreateConnection(), CreateRequest(), CreateResponse(), databaseConfig, DB(), database::DatabaseHelper::DestroyConnection(), fcgiSocket, fastcgiserver::FastCGIRequest::GetClientAddress(), fastcgiserver::FastCGIRequest::Handle(), threading::Thread::THREAD_PARAM::instance, fastcgiserver::FastCGIRequest::IsComplete(), log::Logging::IsLogLevelTrace(), threading::Mutex::Lock(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_TRACE, fastcgiserver::FastCGIResponse::Process(), request, threading::Thread::ShallEnd(), fastcgiserver::FastCGISocket::Socket(), THROW_EXCEPTION, threading::Mutex::Unlock(), and fastcgiserver::FastCGISocket::WaitForAccept().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
tools::SpellChecking fastcgiserver::FastCGIServerThread::spellChecker [private]
Definition at line 39 of file FastCGIServerThread.h.
Referenced by SpellChecker().
database::DatabaseHelper fastcgiserver::FastCGIServerThread::dbHelper [private]
Definition at line 40 of file FastCGIServerThread.h.
Referenced by DB().
database::DatabaseConfig* fastcgiserver::FastCGIServerThread::databaseConfig [private]
Definition at line 41 of file FastCGIServerThread.h.
Referenced by FastCGIServerThreadFunc().
FCGX_Request fastcgiserver::FastCGIServerThread::request [private]
Definition at line 43 of file FastCGIServerThread.h.
Referenced by FastCGIServerThreadFunc().
FastCGISocket fastcgiserver::FastCGIServerThread::fcgiSocket [private]
Definition at line 44 of file FastCGIServerThread.h.
Referenced by FastCGIServerThreadFunc().
bool fastcgiserver::FastCGIServerThread::isFileSocket [private]
Definition at line 46 of file FastCGIServerThread.h.
int fastcgiserver::FastCGIServerThread::port [private]
Definition at line 47 of file FastCGIServerThread.h.
int fastcgiserver::FastCGIServerThread::backlog [private]
Definition at line 48 of file FastCGIServerThread.h.
std::string fastcgiserver::FastCGIServerThread::filename [private]
Definition at line 49 of file FastCGIServerThread.h.
threading::Mutex* fastcgiserver::FastCGIServerThread::acceptMutex [private]
Definition at line 50 of file FastCGIServerThread.h.
Referenced by FastCGIServerThreadFunc().
The documentation for this class was generated from the following files:
FastCGIServer/src/FastCGIServerThread.h
FastCGIServer/src/FastCGIServerThread.cpp