DeepNet: database::WhereConditionOperator Class Reference
database::WhereConditionOperator Class Reference
operator container for where conditions.
#include <WhereConditionOperator.h>
Public Member Functions
WhereConditionOperator (const WhereConditionOperatorType &type)
constructs operator from type.
bool operator< (const WhereConditionOperator &rhs) const
bool operator== (const WhereConditionOperator &rhs) const
std::string ToString (void) const
gets textual representation.
WhereConditionOperatorType GetType (void) const
gets oeprator type.
Static Public Member Functions
static std::string OperatorToString (const WhereConditionOperatorType &op)
converts operator type to string
Private Attributes
WhereConditionOperatorType type
Detailed Description
operator container for where conditions.
Definition at line 17 of file WhereConditionOperator.h.
Constructor & Destructor Documentation
database::WhereConditionOperator::WhereConditionOperator (const WhereConditionOperatorType & type)
constructs operator from type.
Parameters:
type operator type.
Definition at line 13 of file WhereConditionOperator.cpp.
Member Function Documentation
bool database::WhereConditionOperator::operator< (const WhereConditionOperator & rhs) const
Definition at line 17 of file WhereConditionOperator.cpp.
References type.
bool database::WhereConditionOperator::operator== (const WhereConditionOperator & rhs) const
Definition at line 22 of file WhereConditionOperator.cpp.
References type.
std::string database::WhereConditionOperator::ToString (void) const
gets textual representation.
Returns:
operator as string.
Definition at line 27 of file WhereConditionOperator.cpp.
References OperatorToString(), and type.
Referenced by database::WhereConditionTableColumn::ToString().
WhereConditionOperatorType database::WhereConditionOperator::GetType (void) const
gets oeprator type.
Returns:
operator type.
Definition at line 32 of file WhereConditionOperator.cpp.
References type.
Referenced by database::WhereConditionTableColumn::ToString().
std::string database::WhereConditionOperator::OperatorToString (const WhereConditionOperatorType & op) [static]
converts operator type to string
Parameters:
op operator type
Returns:
operator string.
Definition at line 37 of file WhereConditionOperator.cpp.
References database::EQUALS, database::GREATER, database::GREATER_EQUAL, database::LIKE, database::NOT_EQUALS, database::SMALLER, database::SMALLER_EQUAL, and THROW_EXCEPTION.
Referenced by ToString().
Member Data Documentation
WhereConditionOperatorType database::WhereConditionOperator::type [private]
Definition at line 51 of file WhereConditionOperator.h.
Referenced by GetType(), operator<(), operator==(), and ToString().
The documentation for this class was generated from the following files:
Database/src/WhereConditionOperator.h
Database/src/WhereConditionOperator.cpp