DeepNet: inspectorserver::InspectorServerResponse Class Reference
inspectorserver::InspectorServerResponse Class Reference
#include <InspectorServerResponse.h>
Public Member Functions
InspectorServerResponse (database::DatabaseHelper &dbHelper, InspectorServerRequest *request)
virtual ~InspectorServerResponse ()
virtual bool Process (FCGX_Request &request)
processes fastcgi client request.
std::string ToString ()
converts request to string
Protected Attributes
FastCGIRequest * fcgiRequest
corresponding request.
HttpHeader header
response header.
std::string content
content of response.
Private Member Functions
database::DatabaseHelper & DB ()
Private Attributes
InspectorServerRequest * inspectorRequest
database::DatabaseHelper & dbHelper
Detailed Description
Definition at line 19 of file InspectorServerResponse.h.
Constructor & Destructor Documentation
inspectorserver::InspectorServerResponse::InspectorServerResponse (database::DatabaseHelper & dbHelper, InspectorServerRequest * request)
Definition at line 33 of file InspectorServerResponse.cpp.
inspectorserver::InspectorServerResponse::~InspectorServerResponse () [virtual]
Definition at line 40 of file InspectorServerResponse.cpp.
Member Function Documentation
bool inspectorserver::InspectorServerResponse::Process (FCGX_Request & request) [virtual]
processes fastcgi client request.
Parameters:
request corresponding request.
Returns:
false on error, true on success.
Reimplemented from fastcgiserver::FastCGIResponse.
Definition at line 44 of file InspectorServerResponse.cpp.
References network::HttpClientSettings::allowIPv6, fastcgiserver::FastCGIResponse::content, network::HttpClientFactory::CreateInstance(), network::HttpClientFactory::CURL, network::HttpUrlParser::DecodeUrl(), network::HttpClientSettings::downloadLimitKB, network::IHttpClient::Get(), tools::Pointer< T >::Get(), network::HtmlData::GetBuffer(), network::HttpUrl::GetFullUrl(), network::HttpResponse::html, inspectorserver::InspectorServerRequest::HtmlCodes(), network::HttpResponse::httpResponseCode, inspectorRequest, log::Logging::Log(), log::Logging::LOGLEVEL_WARN, network::HttpUrlParser::ParseURL(), network::HttpClientSettings::secondsTimeoutConnect, network::HttpClientSettings::secondsTimeoutConnection, network::IHttpClient::Settings(), network::HttpClientSettings::uploadLimitKB, and network::HttpClientSettings::userAgent.
database::DatabaseHelper& inspectorserver::InspectorServerResponse::DB () [inline, private]
Definition at line 28 of file InspectorServerResponse.h.
References dbHelper.
std::string fastcgiserver::FastCGIResponse::ToString (void) [inline, inherited]
converts request to string
Returns:
request string.
Definition at line 38 of file FastCGIResponse.h.
References fastcgiserver::FastCGIResponse::content, fastcgiserver::FastCGIResponse::header, and fastcgiserver::HttpHeader::ToString().
Referenced by fastcgiserver::FastCGIResponse::Process().
Member Data Documentation
InspectorServerRequest* inspectorserver::InspectorServerResponse::inspectorRequest [private]
Definition at line 31 of file InspectorServerResponse.h.
Referenced by Process().
database::DatabaseHelper& inspectorserver::InspectorServerResponse::dbHelper [private]
Definition at line 32 of file InspectorServerResponse.h.
Referenced by DB().
FastCGIRequest* fastcgiserver::FastCGIResponse::fcgiRequest [protected, inherited]
corresponding request.
Definition at line 44 of file FastCGIResponse.h.
HttpHeader fastcgiserver::FastCGIResponse::header [protected, inherited]
response header.
Definition at line 49 of file FastCGIResponse.h.
Referenced by fastcgiserver::FastCGIResponse::ToString().
std::string fastcgiserver::FastCGIResponse::content [protected, inherited]
content of response.
Definition at line 54 of file FastCGIResponse.h.
Referenced by queryserver::XMLQueryResponse::OutputResults(), suggestserver::SuggestServerResponse::Process(), Process(), and fastcgiserver::FastCGIResponse::ToString().
The documentation for this class was generated from the following files:
InspectorServer/src/InspectorServerResponse.h
InspectorServer/src/InspectorServerResponse.cpp