DeepNet: toolbot::UnitTestHttpClientCURL Class Reference
toolbot::UnitTestHttpClientCURL Class Reference
#include <UnitTestHttpClientCURL.h>
Public Member Functions
UnitTestHttpClientCURL (const std::string &get, const std::string &post)
virtual ~UnitTestHttpClientCURL ()
virtual bool Run ()
virtual std::string GetName () const
Private Member Functions
bool ReadURLFile (const std::string &urlFileName, std::vector< network::HttpUrl > &testUrls)
Private Attributes
std::string get
std::string post
Detailed Description
Definition at line 22 of file UnitTestHttpClientCURL.h.
Constructor & Destructor Documentation
toolbot::UnitTestHttpClientCURL::UnitTestHttpClientCURL (const std::string & get, const std::string & post)
Definition at line 23 of file UnitTestHttpClientCURL.cpp.
toolbot::UnitTestHttpClientCURL::~UnitTestHttpClientCURL () [virtual]
Definition at line 28 of file UnitTestHttpClientCURL.cpp.
Member Function Documentation
bool toolbot::UnitTestHttpClientCURL::Run () [virtual]
Implements toolbot::UnitTest.
Definition at line 31 of file UnitTestHttpClientCURL.cpp.
References network::HttpClientFactory::CreateInstance(), network::HttpClientFactory::CURL, tools::Pointer< T >::Get(), log::Logging::LogError(), post, and ReadURLFile().
virtual std::string toolbot::UnitTestHttpClientCURL::GetName () const [inline, virtual]
Implements toolbot::UnitTest.
Definition at line 29 of file UnitTestHttpClientCURL.h.
bool toolbot::UnitTestHttpClientCURL::ReadURLFile (const std::string & urlFileName, std::vector< network::HttpUrl > & testUrls) [private]
Definition at line 72 of file UnitTestHttpClientCURL.cpp.
References errors::Exception::DisableLogging(), network::HttpUrlParser::ParseURL(), and tools::FileTools::ReadFile().
Referenced by Run().
Member Data Documentation
std::string toolbot::UnitTestHttpClientCURL::get [private]
Definition at line 35 of file UnitTestHttpClientCURL.h.
std::string toolbot::UnitTestHttpClientCURL::post [private]
Definition at line 36 of file UnitTestHttpClientCURL.h.
Referenced by Run().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestHttpClientCURL.h
DeepNetTool/src/UnitTestHttpClientCURL.cpp