DeepNet: tools::Stack< T > Class Template Reference
tools::Stack< T > Class Template Reference
generic implementation of a stack
#include <Stack.h>
Classes
class StackNode
Public Member Functions
Stack ()
create empty stack.
~Stack ()
Stack (const Stack &rhs)
Stack & operator= (const Stack &rhs)
void Push (const T *value)
push value to stack not copying and not deleting.
void Push (const T &value)
copy and push value to stack.
void TryPop ()
tries to pop value from stack, throws exception if stack is empty.
void Pop ()
pop value from stack.
T PopDump ()
pop value from stack
T & Peek ()
peek stack.
T & Peek (size_t pos)
peek stack at position pos.
const T & ConstPeek () const
peek top of the stack.
const T & ConstPeek (size_t pos) const
peek stack at position pos.
size_t Size () const
get stack size.
Private Attributes
std::vector< StackNode< T > > items
Detailed Description
template<typename T>
class tools::Stack< T >
generic implementation of a stack
Definition at line 20 of file Stack.h.
Constructor & Destructor Documentation
template<typename T> tools::Stack< T >::Stack () [inline]
create empty stack.
Definition at line 39 of file Stack.h.
template<typename T> tools::Stack< T >::~Stack () [inline]
Definition at line 42 of file Stack.h.
template<typename T> tools::Stack< T >::Stack (const Stack< T > & rhs) [inline]
Definition at line 51 of file Stack.h.
Member Function Documentation
template<typename T> Stack& tools::Stack< T >::operator= (const Stack< T > & rhs) [inline]
Definition at line 62 of file Stack.h.
template<typename T> void tools::Stack< T >::Push (const T * value) [inline]
push value to stack not copying and not deleting.
Parameters:
value value.
Definition at line 78 of file Stack.h.
Referenced by domparser::DocumentFactory::InsertHtmlElement(), domparser::DocumentFactory::OnAfterHeadInsertion(), domparser::DocumentFactory::OnInHeadInsertion(), tools::Stack< domparser::dom3::Node * >::operator=(), and tools::Stack< domparser::dom3::Node * >::Stack().
template<typename T> void tools::Stack< T >::Push (const T & value) [inline]
copy and push value to stack.
Parameters:
value value.
Definition at line 86 of file Stack.h.
template<typename T> void tools::Stack< T >::TryPop () [inline]
tries to pop value from stack, throws exception if stack is empty.
Definition at line 93 of file Stack.h.
template<typename T> void tools::Stack< T >::Pop () [inline]
pop value from stack.
Definition at line 102 of file Stack.h.
Referenced by domparser::DocumentFactory::OnAfterHeadInsertion(), domparser::DocumentFactory::OnInBodyStartTagInsertion(), domparser::DocumentFactory::OnInHeadInsertion(), domparser::DocumentFactory::OnInHeadNoscriptInsertion(), domparser::DocumentFactory::OnTextInsertion(), tools::Stack< domparser::dom3::Node * >::PopDump(), and tools::Stack< domparser::dom3::Node * >::TryPop().
template<typename T> T tools::Stack< T >::PopDump () [inline]
pop value from stack
Returns:
copy of the popped stack value.
Definition at line 115 of file Stack.h.
template<typename T> T& tools::Stack< T >::Peek () [inline]
peek stack.
Returns:
top stack value.
Definition at line 127 of file Stack.h.
Referenced by domparser::DocumentFactory::OnInBodyStartTagInsertion(), and tools::Stack< domparser::dom3::Node * >::Peek().
template<typename T> T& tools::Stack< T >::Peek (size_t pos) [inline]
peek stack at position pos.
Parameters:
pos position of item
Returns:
stack item.
Definition at line 136 of file Stack.h.
template<typename T> const T& tools::Stack< T >::ConstPeek () const [inline]
peek top of the stack.
Returns:
top stack value.
Definition at line 146 of file Stack.h.
Referenced by tools::Stack< domparser::dom3::Node * >::ConstPeek(), domparser::DocumentFactory::OnInBodyEndTagInsertion(), and domparser::DocumentFactory::OnInBodyStartTagInsertion().
template<typename T> const T& tools::Stack< T >::ConstPeek (size_t pos) const [inline]
peek stack at position pos.
Parameters:
pos position of item
Returns:
stack item.
Definition at line 155 of file Stack.h.
template<typename T> size_t tools::Stack< T >::Size () const [inline]
get stack size.
Returns:
stack size.
Definition at line 165 of file Stack.h.
Referenced by tools::Stack< domparser::dom3::Node * >::ConstPeek(), domparser::DocumentFactory::OnInBodyEndTagInsertion(), domparser::DocumentFactory::OnInBodyStartTagInsertion(), tools::Stack< domparser::dom3::Node * >::Peek(), tools::Stack< domparser::dom3::Node * >::Pop(), tools::Stack< domparser::dom3::Node * >::PopDump(), and tools::Stack< domparser::dom3::Node * >::TryPop().
Member Data Documentation
template<typename T> std::vector< StackNode<T> > tools::Stack< T >::items [private]
Definition at line 170 of file Stack.h.
Referenced by tools::Stack< domparser::dom3::Node * >::ConstPeek(), tools::Stack< domparser::dom3::Node * >::operator=(), tools::Stack< domparser::dom3::Node * >::Peek(), tools::Stack< domparser::dom3::Node * >::Pop(), tools::Stack< domparser::dom3::Node * >::PopDump(), tools::Stack< domparser::dom3::Node * >::Push(), tools::Stack< domparser::dom3::Node * >::Size(), tools::Stack< domparser::dom3::Node * >::Stack(), and tools::Stack< domparser::dom3::Node * >::~Stack().
The documentation for this class was generated from the following file:
Tools/src/Stack.h