DeepNet: errors::Exception Class Reference
errors::Exception Class Reference
generic wrapper class for exceptions.
#include <Exception.h>
Public Member Functions
Exception (const std::string &file, const int line, const std::string &function, const std::string &module, const std::string &exceptionName, const std::string &message, const bool logException=true)
creates an exception.
Exception (const std::string &file, const int line, const std::string &function, const std::string &module, const std::string &exceptionName, const std::string &message, const std::string &backtrace, const bool logException=true)
creates an exception.
virtual ~Exception ()
void Log () const
log this exception.
void DisableLogging ()
prevent exception from being logged.
std::string Dump () const
dumps exception as string.
Static Public Member Functions
static void InitializeExceptionHandling ()
initializes exception handling for current process.
Protected Attributes
std::string file
originating filename
int line
originating source line.
std::string function
originating function.
std::string module
originating module.
std::string exceptionName
name of the exception.
std::string message
exception message.
std::string backtrace
backtrace.
bool logException
log this exception.
Static Private Member Functions
static void TerminateHandler ()
Static Private Attributes
static volatile bool tryRethrow = true
Detailed Description
generic wrapper class for exceptions.
Definition at line 19 of file Exception.h.
Constructor & Destructor Documentation
errors::Exception::Exception (const std::string & file, const int line, const std::string & function, const std::string & module, const std::string & exceptionName, const std::string & message, const bool logException = true)
creates an exception.
use THROW_EXCEPTION macro to throw an exception.
Parameters:
file originating filename.
line originating sourceline.
function originating function.
module originating module.
exceptionName exception name
message exception message
logException true if exception shall be logged.
Definition at line 22 of file Exception.cpp.
errors::Exception::Exception (const std::string & file, const int line, const std::string & function, const std::string & module, const std::string & exceptionName, const std::string & message, const std::string & backtrace, const bool logException = true)
creates an exception.
use THROW_EXCEPTION macro to throw an exception.
Parameters:
file originating filename.
line originating sourceline.
function originating function.
module originating module.
exceptionName exception name
message exception message
backtrace backstrace.
logException true if exception shall be logged.
Definition at line 40 of file Exception.cpp.
References tryRethrow.
errors::Exception::~Exception () [virtual]
Definition at line 60 of file Exception.cpp.
References Log(), and logException.
Member Function Documentation
void errors::Exception::InitializeExceptionHandling () [static]
initializes exception handling for current process.
Definition at line 93 of file Exception.cpp.
References TerminateHandler().
Referenced by fastcgiserver::FastCGIServer::FastCGIServer(), and bot::Bot::Run().
void errors::Exception::Log () const
log this exception.
Definition at line 65 of file Exception.cpp.
References Dump(), log::Logging::LOGLEVEL_ERROR, and log::Logging::LogUnlimited().
Referenced by ~Exception().
void errors::Exception::DisableLogging ()
prevent exception from being logged.
Definition at line 70 of file Exception.cpp.
References logException.
Referenced by domparser::DOMParser::Parse(), toolbot::UnitTestHttpClientCURL::ReadURLFile(), and toolbot::UnitTestUrlParser::TestInvalidUrls().
std::string errors::Exception::Dump () const
dumps exception as string.
Returns:
exception as string.
Definition at line 74 of file Exception.cpp.
References backtrace, exceptionName, file, log::Logging::GetTimeString(), line, message, and module.
Referenced by Log(), toolbot::UnitTestUrlParser::TestInvalidUrls(), and toolbot::UnitTestUrlParser::TestValidUrls().
void errors::Exception::TerminateHandler () [static, private]
Definition at line 99 of file Exception.cpp.
References backtrace, tools::DebuggingTools::GetBacktrace(), THROW_EXCEPTION, and tryRethrow.
Referenced by InitializeExceptionHandling().
Member Data Documentation
std::string errors::Exception::file [protected]
originating filename
Definition at line 90 of file Exception.h.
Referenced by Dump().
int errors::Exception::line [protected]
originating source line.
Definition at line 95 of file Exception.h.
Referenced by Dump().
std::string errors::Exception::function [protected]
originating function.
Definition at line 100 of file Exception.h.
std::string errors::Exception::module [protected]
originating module.
Definition at line 105 of file Exception.h.
Referenced by Dump().
std::string errors::Exception::exceptionName [protected]
name of the exception.
Definition at line 110 of file Exception.h.
Referenced by Dump().
std::string errors::Exception::message [protected]
exception message.
Definition at line 115 of file Exception.h.
Referenced by domparser::dom3::DOMException::DOMException(), and Dump().
std::string errors::Exception::backtrace [protected]
backtrace.
Definition at line 120 of file Exception.h.
Referenced by Dump(), and TerminateHandler().
bool errors::Exception::logException [protected]
log this exception.
Definition at line 125 of file Exception.h.
Referenced by DisableLogging(), and ~Exception().
volatile bool errors::Exception::tryRethrow = true [static, private]
Definition at line 128 of file Exception.h.
Referenced by Exception(), and TerminateHandler().
The documentation for this class was generated from the following files:
Tools/src/Exception.h
Tools/src/Exception.cpp