DeepNet: database::MySQLInsertOrUpdateStatement Class Reference
database::MySQLInsertOrUpdateStatement Class Reference
implementation of a insert or update statement for MySQL servers
#include <MySQLInsertOrUpdateStatement.h>
Public Member Functions
MySQLInsertOrUpdateStatement (const InsertOrUpdateStatement *stmt)
virtual ~MySQLInsertOrUpdateStatement ()
std::string ToSQL (DatabaseConnection *db) const
gets sql equivalent of this statement.
Private Member Functions
bool IsSumColumn (const std::string &columnName) const
Private Attributes
const InsertOrUpdateStatement * orgStatement
Detailed Description
implementation of a insert or update statement for MySQL servers
Definition at line 20 of file MySQLInsertOrUpdateStatement.h.
Constructor & Destructor Documentation
database::MySQLInsertOrUpdateStatement::MySQLInsertOrUpdateStatement (const InsertOrUpdateStatement * stmt)
Definition at line 23 of file MySQLInsertOrUpdateStatement.cpp.
database::MySQLInsertOrUpdateStatement::~MySQLInsertOrUpdateStatement () [virtual]
Definition at line 27 of file MySQLInsertOrUpdateStatement.cpp.
Member Function Documentation
std::string database::MySQLInsertOrUpdateStatement::ToSQL (DatabaseConnection * db) const
gets sql equivalent of this statement.
Parameters:
db database connection.
Returns:
sql string.
Definition at line 30 of file MySQLInsertOrUpdateStatement.cpp.
References database::TableColumnDefinition::GetColumnName(), database::TableDefinition::GetConstColumnDefinitions(), database::TableBase::GetConstColumns(), database::InsertStatement::GetConstTableBase(), database::TableBase::GetConstTableDefinition(), database::TableDefinition::GetPrimaryKeyColumnDefinition(), IsSumColumn(), orgStatement, database::InsertOrUpdateStatement::sumColumns, and THROW_EXCEPTION.
Referenced by database::MySQLConnection::InsertOrUpdate().
bool database::MySQLInsertOrUpdateStatement::IsSumColumn (const std::string & columnName) const [private]
Definition at line 73 of file MySQLInsertOrUpdateStatement.cpp.
References orgStatement, and database::InsertOrUpdateStatement::sumColumns.
Referenced by ToSQL().
Member Data Documentation
const InsertOrUpdateStatement* database::MySQLInsertOrUpdateStatement::orgStatement [private]
Definition at line 37 of file MySQLInsertOrUpdateStatement.h.
Referenced by IsSumColumn(), and ToSQL().
The documentation for this class was generated from the following files:
Database/MySQL/MySQLInsertOrUpdateStatement.h
Database/MySQL/MySQLInsertOrUpdateStatement.cpp