DeepNet: tools::CompressionTools Class Reference
tools::CompressionTools Class Reference
wrapper class for compression algorithms.
#include <CompressionTools.h>
Public Member Functions
virtual ~CompressionTools ()
Static Public Member Functions
static bool GZip (const char *in, const size_t &in_size, char **out, size_t &out_size)
compress buffer using gzip.
static bool GUnzip (const char *in, const size_t &in_size, char **out, size_t &out_size)
decompress buffer using gzip.
static bool Deflate (const char *in, const size_t &in_size, char **out, size_t &out_size)
compress buffer using deflate.
static bool Inflate (const char *in, const size_t &in_size, char **out, size_t &out_size)
decompress buffer using deflate.
static bool RawDeflate (const char *in, const size_t &in_size, char **out, size_t &out_size)
compress buffer using raw deflate.
static bool RawInflate (const char *in, const size_t &in_size, char **out, size_t &out_size)
decompress buffer using raw deflate.
Private Member Functions
CompressionTools ()
Static Private Member Functions
static bool DeflateZLib (const int windowBits, const char *in, const size_t &in_size, char **out, size_t &out_size)
static bool InflateZLib (const int windowBits, const char *in, const size_t &in_size, char **out, size_t &out_size)
Detailed Description
wrapper class for compression algorithms.
this class wraps all kind of compression functionalities.
Definition at line 17 of file CompressionTools.h.
Constructor & Destructor Documentation
tools::CompressionTools::CompressionTools () [private]
Definition at line 18 of file CompressionTools.cpp.
tools::CompressionTools::~CompressionTools () [virtual]
Definition at line 21 of file CompressionTools.cpp.
Member Function Documentation
bool tools::CompressionTools::GZip (const char * in, const size_t & in_size, char ** out, size_t & out_size) [static]
compress buffer using gzip.
Parameters:
in input buffer.
in_size input buffer size.
out output buffer.
out_size gets filled with size of output buffer.
Returns:
false on error, true on success.
Definition at line 24 of file CompressionTools.cpp.
References DeflateZLib(), and ZLIB_GZIP_MODE.
bool tools::CompressionTools::GUnzip (const char * in, const size_t & in_size, char ** out, size_t & out_size) [static]
decompress buffer using gzip.
Parameters:
in input buffer.
in_size input buffer size.
out output buffer.
out_size gets filled with size of output buffer.
Returns:
false on error, true on success.
Definition at line 29 of file CompressionTools.cpp.
References InflateZLib(), and ZLIB_GZIP_MODE.
bool tools::CompressionTools::Deflate (const char * in, const size_t & in_size, char ** out, size_t & out_size) [static]
compress buffer using deflate.
Parameters:
in input buffer.
in_size input buffer size.
out output buffer.
out_size gets filled with size of output buffer.
Returns:
false on error, true on success.
Definition at line 34 of file CompressionTools.cpp.
References DeflateZLib(), and ZLIB_DEFLATE_MODE.
bool tools::CompressionTools::Inflate (const char * in, const size_t & in_size, char ** out, size_t & out_size) [static]
decompress buffer using deflate.
Parameters:
in input buffer.
in_size input buffer size.
out output buffer.
out_size gets filled with size of output buffer.
Returns:
false on error, true on success.
Definition at line 39 of file CompressionTools.cpp.
References InflateZLib(), and ZLIB_DEFLATE_MODE.
bool tools::CompressionTools::RawDeflate (const char * in, const size_t & in_size, char ** out, size_t & out_size) [static]
compress buffer using raw deflate.
Parameters:
in input buffer.
in_size input buffer size.
out output buffer.
out_size gets filled with size of output buffer.
Returns:
false on error, true on success.
Definition at line 44 of file CompressionTools.cpp.
References DeflateZLib(), and ZLIB_RAW_MODE.
bool tools::CompressionTools::RawInflate (const char * in, const size_t & in_size, char ** out, size_t & out_size) [static]
decompress buffer using raw deflate.
Parameters:
in input buffer.
in_size input buffer size.
out output buffer.
out_size gets filled with size of output buffer.
Returns:
false on error, true on success.
Definition at line 49 of file CompressionTools.cpp.
References InflateZLib(), and ZLIB_RAW_MODE.
bool tools::CompressionTools::DeflateZLib (const int windowBits, const char * in, const size_t & in_size, char ** out, size_t & out_size) [static, private]
Definition at line 54 of file CompressionTools.cpp.
Referenced by Deflate(), GZip(), and RawDeflate().
bool tools::CompressionTools::InflateZLib (const int windowBits, const char * in, const size_t & in_size, char ** out, size_t & out_size) [static, private]
Definition at line 99 of file CompressionTools.cpp.
Referenced by GUnzip(), Inflate(), and RawInflate().
The documentation for this class was generated from the following files:
Tools/src/CompressionTools.h
Tools/src/CompressionTools.cpp