DeepNet: database::DatabaseHelper Class Reference
database::DatabaseHelper Class Reference
helper class for a database connection.
#include <DatabaseHelper.h>
Public Member Functions
DatabaseHelper ()
virtual ~DatabaseHelper ()
DatabaseConnection * CreateConnection (DatabaseConfig *dbConfig, const bool logQuery=false)
create a new database connection.
void DestroyConnection (void)
destroys current database connection.
DatabaseConnection * Connection (void)
gets current database connection.
Static Public Member Functions
static bool TmToDateTime (const struct tm &in, std::string &out)
TODO: document move this function to TimeTools.
static bool DateTimeToTm (const std::string &in, struct tm &out)
TODO: document move this function to TimeTools.
Private Attributes
DatabaseConnection * dbConnection
Static Private Attributes
static threading::Mutex mutexLibraryInit
static volatile bool isLibraryInitialized = false
static volatile size_t libraryRefCount = 0
Detailed Description
helper class for a database connection.
See also:
database::MySQLDatabaseConnection
database::DB2DatabaseConnection helper class for a database connection. use this class for creation and destruction of a connection.
Definition at line 27 of file DatabaseHelper.h.
Constructor & Destructor Documentation
database::DatabaseHelper::DatabaseHelper ()
Definition at line 21 of file DatabaseHelper.cpp.
database::DatabaseHelper::~DatabaseHelper () [virtual]
Definition at line 26 of file DatabaseHelper.cpp.
References DestroyConnection().
Member Function Documentation
DatabaseConnection * database::DatabaseHelper::CreateConnection (DatabaseConfig * dbConfig, const bool logQuery = false)
create a new database connection.
Parameters:
dbConfig database configuration.
logQuery true if all queries should be logged.
Returns:
NULL on error, database connection on success.
Definition at line 31 of file DatabaseHelper.cpp.
References database::DatabaseConnection::Connect(), database::DB_IBM_DB2, database::DB_MYSQL, dbConnection, DestroyConnection(), database::DatabaseConfig::GetType(), database::DatabaseConnection::Initialize(), isLibraryInitialized, libraryRefCount, threading::Mutex::Lock(), log::Logging::LogWarn(), mutexLibraryInit, and threading::Mutex::Unlock().
Referenced by log::DatabaseLogging::DatabaseLogging(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::IndexerThread::IndexerThreadFunc(), fastcgiserver::FastCGIServer::InitDatabaseConfigs(), crawler::FencedCrawler::StartCrawler(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
void database::DatabaseHelper::DestroyConnection (void)
destroys current database connection.
Definition at line 66 of file DatabaseHelper.cpp.
References dbConnection, database::DatabaseConnection::Disconnect(), isLibraryInitialized, libraryRefCount, threading::Mutex::Lock(), mutexLibraryInit, database::DatabaseConnection::Shutdown(), and threading::Mutex::Unlock().
Referenced by CreateConnection(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::IndexerThread::IndexerThreadFunc(), fastcgiserver::FastCGIServer::InitDatabaseConfigs(), toolbot::DeepNetToolBot::OnShutdown(), bot::Bot::Shutdown(), crawler::FencedCrawler::StartCrawler(), crawler::UrlFetcherThread::UrlFetcherThreadFunction(), and ~DatabaseHelper().
DatabaseConnection* database::DatabaseHelper::Connection (void) [inline]
gets current database connection.
Returns:
current database connection.
Definition at line 52 of file DatabaseHelper.h.
References dbConnection.
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPageRelevanceByBacklinks(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), fastcgiserver::FastCGIServer::InitDatabaseConfigs(), queryserver::XMLQueryResponse::LogQuery(), log::DatabaseLogging::OnLog(), queryserver::XMLQueryResponse::ProcessExistQuery(), crawler::UrlFetcherThread::RemoveCrawlerSessionID(), queryserver::XMLQueryResponse::SaveResults(), and bot::Bot::WatchDog().
static bool database::DatabaseHelper::TmToDateTime (const struct tm & in, std::string & out) [inline, static]
TODO: document move this function to TimeTools.
Parameters:
in
out
Returns:
Definition at line 63 of file DatabaseHelper.h.
Referenced by database::TableColumnValue::GetForSQL().
static bool database::DatabaseHelper::DateTimeToTm (const std::string & in, struct tm & out) [inline, static]
TODO: document move this function to TimeTools.
Parameters:
in
out
Returns:
Definition at line 80 of file DatabaseHelper.h.
Referenced by database::MySQLTableBase::SetColumnValues().
Member Data Documentation
DatabaseConnection* database::DatabaseHelper::dbConnection [private]
Definition at line 89 of file DatabaseHelper.h.
Referenced by Connection(), CreateConnection(), and DestroyConnection().
threading::Mutex database::DatabaseHelper::mutexLibraryInit [static, private]
Definition at line 92 of file DatabaseHelper.h.
Referenced by CreateConnection(), and DestroyConnection().
volatile bool database::DatabaseHelper::isLibraryInitialized = false [static, private]
Definition at line 93 of file DatabaseHelper.h.
Referenced by CreateConnection(), and DestroyConnection().
volatile size_t database::DatabaseHelper::libraryRefCount = 0 [static, private]
Definition at line 94 of file DatabaseHelper.h.
Referenced by CreateConnection(), and DestroyConnection().
The documentation for this class was generated from the following files:
Database/src/DatabaseHelper.h
Database/src/DatabaseHelper.cpp