DeepNet: indexing::IIndexer Class Reference
indexing::IIndexer Class Reference
interface class for indexers
#include <IIndexer.h>
Public Member Functions
virtual ~IIndexer ()
virtual void Parse (const std::string &input, const long long paragraph)=0
parses a text
virtual void ParseMeta (const std::string &input, const Dictionary::MetaInformationType &type)=0
parses content part of a meta type
virtual Dictionary & GetDictionary ()=0
gets dictionary of this indexer
Detailed Description
interface class for indexers
Definition at line 20 of file IIndexer.h.
Constructor & Destructor Documentation
virtual indexing::IIndexer::~IIndexer () [inline, virtual]
Definition at line 23 of file IIndexer.h.
Member Function Documentation
virtual void indexing::IIndexer::Parse (const std::string & input, const long long paragraph) [pure virtual]
parses a text
Parameters:
input text to parse
paragraph paragraph of this text
Implemented in indexing::IndexerBase, and indexing::IndexerEx.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile().
virtual void indexing::IIndexer::ParseMeta (const std::string & input, const Dictionary::MetaInformationType & type) [pure virtual]
parses content part of a meta type
Parameters:
input content part to parse
type meta type to set
Implemented in indexing::IndexerBase, and indexing::IndexerEx.
virtual Dictionary& indexing::IIndexer::GetDictionary () [pure virtual]
gets dictionary of this indexer
Returns:
instance of this indexers dictionary
Implemented in indexing::IndexerEx, indexing::GenericWebContentIndexer, and indexing::DataminingContentIndexer.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), and indexing::ContentIndexer::TerminateWord().
The documentation for this class was generated from the following file:
Indexer/src/IIndexer.h