DeepNet: suggestserver::SuggestServerResponse Class Reference
suggestserver::SuggestServerResponse Class Reference
#include <SuggestServerResponse.h>
Public Member Functions
SuggestServerResponse (database::DatabaseHelper &dbHelper, SuggestServerRequest *request)
virtual ~SuggestServerResponse ()
virtual bool Process (FCGX_Request &request)
processes fastcgi client request.
std::string ToString ()
converts request to string
Protected Attributes
FastCGIRequest * fcgiRequest
corresponding request.
HttpHeader header
response header.
std::string content
content of response.
Private Attributes
SuggestServerRequest * suggestRequest
database::DatabaseHelper & dbHelper
Detailed Description
Definition at line 17 of file SuggestServerResponse.h.
Constructor & Destructor Documentation
suggestserver::SuggestServerResponse::SuggestServerResponse (database::DatabaseHelper & dbHelper, SuggestServerRequest * request)
Definition at line 18 of file SuggestServerResponse.cpp.
suggestserver::SuggestServerResponse::~SuggestServerResponse () [virtual]
Definition at line 25 of file SuggestServerResponse.cpp.
Member Function Documentation
bool suggestserver::SuggestServerResponse::Process (FCGX_Request & request) [virtual]
processes fastcgi client request.
Parameters:
request corresponding request.
Returns:
false on error, true on success.
Reimplemented from fastcgiserver::FastCGIResponse.
Definition at line 29 of file SuggestServerResponse.cpp.
References fastcgiserver::FastCGIResponse::content, tools::SpellChecking::GenerateProposals(), suggestserver::SuggestServerRequest::QueryParts(), fastcgiserver::FastCGIRequest::ServerThread(), fastcgiserver::FastCGIServerThread::SpellChecker(), and suggestRequest.
std::string fastcgiserver::FastCGIResponse::ToString (void) [inline, inherited]
converts request to string
Returns:
request string.
Definition at line 38 of file FastCGIResponse.h.
References fastcgiserver::FastCGIResponse::content, fastcgiserver::FastCGIResponse::header, and fastcgiserver::HttpHeader::ToString().
Referenced by fastcgiserver::FastCGIResponse::Process().
Member Data Documentation
SuggestServerRequest* suggestserver::SuggestServerResponse::suggestRequest [private]
Definition at line 26 of file SuggestServerResponse.h.
Referenced by Process().
database::DatabaseHelper& suggestserver::SuggestServerResponse::dbHelper [private]
Definition at line 27 of file SuggestServerResponse.h.
FastCGIRequest* fastcgiserver::FastCGIResponse::fcgiRequest [protected, inherited]
corresponding request.
Definition at line 44 of file FastCGIResponse.h.
HttpHeader fastcgiserver::FastCGIResponse::header [protected, inherited]
response header.
Definition at line 49 of file FastCGIResponse.h.
Referenced by fastcgiserver::FastCGIResponse::ToString().
std::string fastcgiserver::FastCGIResponse::content [protected, inherited]
content of response.
Definition at line 54 of file FastCGIResponse.h.
Referenced by queryserver::XMLQueryResponse::OutputResults(), Process(), inspectorserver::InspectorServerResponse::Process(), and fastcgiserver::FastCGIResponse::ToString().
The documentation for this class was generated from the following files:
SuggestServer/src/SuggestServerResponse.h
SuggestServer/src/SuggestServerResponse.cpp