DeepNet: caching::Cache< T, V > Class Template Reference
caching::Cache< T, V > Class Template Reference
generic thread-safe caching class.
#include <Cache.h>
Public Member Functions
Cache (size_t limit, bool deleteOnGet)
construct cache with size limit.
virtual ~Cache ()
void AddItem (const T &key, const V &value)
add an item to cache.
bool DeleteItem (const T &key, const bool locking=true)
deletes item from cache.
V GetItem (const T &key)
gets value by key.
bool GetItem (const T &key, V &value)
gets value by key.
bool GetItem (std::map< T, V > &list, const int count)
gets multiple items.
void RemoveItem (const size_t startPos, const size_t count)
removes multiple items from cache.
void ClearItems ()
removes all items from cache.
void GetMissingItems (std::map< T, V > &check, std::vector< T > &missing)
gets items from cache by key and puts missing keys (no corresponding value found) in a separate list.
void GetByValue (std::map< V, T > &check, std::vector< V > &missing) const
gets multiple items from cache by value and puts missing values (no corresponding key found) in a separate list.
bool GetByValue (const V &value, T &key) const
gets key by value.
template<class X >
bool GetByValue (const X &value, T &key) const
gets key by transformed value of type X.
size_t GetMatches () const
get current match count of cache, clearing internal match counter.
size_t GetMisses () const
get current miss count of cache, clearing internal miss counter.
size_t GetLimit () const
get current limit of cache.
void SetLimit (const size_t capacity)
set current limit of cache.
size_t GetSize () const
gets current number of entries in cache.
Private Attributes
volatile size_t limit
volatile bool deleteOnGet
size_t matches
size_t misses
threading::Mutex mutex
std::map< T, V > mapEntries
Detailed Description
template<class T, class V>
class caching::Cache< T, V >
generic thread-safe caching class.
thread-safe class for caching generic items by key/value.
Definition at line 27 of file Cache.h.
Constructor & Destructor Documentation
template<class T, class V> caching::Cache< T, V >::Cache (size_t limit, bool deleteOnGet) [inline]
construct cache with size limit.
Parameters:
limit maximum number of elements in cache.
deleteOnGet true: deletes items when read from cache (act as a stack).
Definition at line 35 of file Cache.h.
template<class T, class V> virtual caching::Cache< T, V >::~Cache () [inline, virtual]
Definition at line 42 of file Cache.h.
Member Function Documentation
template<class T, class V> void caching::Cache< T, V >::AddItem (const T & key, const V & value) [inline]
add an item to cache.
Parameters:
key key of new item.
value value of new item.
Definition at line 49 of file Cache.h.
Referenced by caching::CacheHtml::Add(), caching::CacheParsed::Add(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), caching::CacheDatabaseUrl::GetByUrl(), caching::CacheDatabaseUrl::GetByUrlID(), caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), and caching::CacheRobotsTxt::IsUrlAllowed().
template<class T, class V> bool caching::Cache< T, V >::DeleteItem (const T & key, const bool locking = true) [inline]
deletes item from cache.
Parameters:
key key to delete.
locking true if cache locks while deleting.
Returns:
false on error, true on success.
Definition at line 75 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::GetItem().
template<class T, class V> V caching::Cache< T, V >::GetItem (const T & key) [inline]
gets value by key.
Parameters:
key key for value to get.
Returns:
value of given key.
Definition at line 97 of file Cache.h.
Referenced by caching::CacheHtml::Get(), caching::CacheParsed::Get(), caching::CacheDatabaseUrl::GetByUrlID(), caching::CacheSecondLevelDomain::GetDomainBySecondLevelID(), caching::CacheSubdomain::GetDomainBySubdomainID(), and caching::CacheRobotsTxt::IsUrlAllowed().
template<class T, class V> bool caching::Cache< T, V >::GetItem (const T & key, V & value) [inline]
gets value by key.
Parameters:
key key for value to get.
value gets filled with value for given key.
Returns:
false if non-existent, true on success.
Definition at line 118 of file Cache.h.
template<class T, class V> bool caching::Cache< T, V >::GetItem (std::map< T, V > & list, const int count) [inline]
gets multiple items.
Parameters:
list filled with keys and values.
count maximum number of items to get.
Returns:
false if cache is empty, true on success.
Definition at line 142 of file Cache.h.
template<class T, class V> void caching::Cache< T, V >::RemoveItem (const size_t startPos, const size_t count) [inline]
removes multiple items from cache.
Parameters:
startPos start position to delete from.
count maximum number of items to delete.
Definition at line 172 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem().
template<class T, class V> void caching::Cache< T, V >::ClearItems () [inline]
removes all items from cache.
Definition at line 189 of file Cache.h.
Referenced by caching::CacheSecondLevelDomain::Clear(), caching::CacheSubdomain::Clear(), and caching::CacheDatabaseUrl::Clear().
template<class T, class V> void caching::Cache< T, V >::GetMissingItems (std::map< T, V > & check, std::vector< T > & missing) [inline]
gets items from cache by key and puts missing keys (no corresponding value found) in a separate list.
Parameters:
check prefilled map with keys to get values for, available values will get filled.
missing list of missing keys in cache.
Definition at line 201 of file Cache.h.
template<class T, class V> void caching::Cache< T, V >::GetByValue (std::map< V, T > & check, std::vector< V > & missing) const [inline]
gets multiple items from cache by value and puts missing values (no corresponding key found) in a separate list.
Parameters:
check prefilled map with values to get keys for, available keys will get filled.
missing list of missing values in cache.
Definition at line 222 of file Cache.h.
Referenced by caching::CacheDatabaseUrl::GetByUrl(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), and caching::CacheSubdomain::GetSubdomainIDByDomain().
template<class T, class V> bool caching::Cache< T, V >::GetByValue (const V & value, T & key) const [inline]
gets key by value.
Parameters:
value value to search for.
key gets filled with key if found.
Returns:
false if all non-existent, true on success.
Definition at line 255 of file Cache.h.
template<class T, class V> template<class X > bool caching::Cache< T, V >::GetByValue (const X & value, T & key) const [inline]
gets key by transformed value of type X.
Parameters:
value value to search for.
key gets filled with key if found.
Returns:
false if all non-existent, true on success.
Definition at line 277 of file Cache.h.
template<class T, class V> size_t caching::Cache< T, V >::GetMatches () const [inline]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 296 of file Cache.h.
Referenced by caching::CacheRobotsTxt::GetMatches(), caching::CacheSecondLevelDomain::GetMatches(), caching::CacheSubdomain::GetMatches(), caching::CacheHtml::GetMatches(), caching::CacheParsed::GetMatches(), and caching::CacheDatabaseUrl::GetMatches().
template<class T, class V> size_t caching::Cache< T, V >::GetMisses () const [inline]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 302 of file Cache.h.
Referenced by caching::CacheRobotsTxt::GetMisses(), caching::CacheSecondLevelDomain::GetMisses(), caching::CacheSubdomain::GetMisses(), caching::CacheHtml::GetMisses(), caching::CacheParsed::GetMisses(), and caching::CacheDatabaseUrl::GetMisses().
template<class T, class V> size_t caching::Cache< T, V >::GetLimit () const [inline]
get current limit of cache.
Returns:
maximum number of entries in cache.
Definition at line 308 of file Cache.h.
template<class T, class V> void caching::Cache< T, V >::SetLimit (const size_t capacity) [inline]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 314 of file Cache.h.
Referenced by caching::CacheRobotsTxt::SetCapacity(), caching::CacheSecondLevelDomain::SetCapacity(), caching::CacheSubdomain::SetCapacity(), caching::CacheHtml::SetCapacity(), caching::CacheParsed::SetCapacity(), and caching::CacheDatabaseUrl::SetCapacity().
template<class T, class V> size_t caching::Cache< T, V >::GetSize () const [inline]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 320 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), caching::CacheRobotsTxt::GetSize(), caching::CacheSecondLevelDomain::GetSize(), caching::CacheSubdomain::GetSize(), caching::CacheHtml::GetSize(), caching::CacheParsed::GetSize(), and caching::CacheDatabaseUrl::GetSize().
Member Data Documentation
template<class T, class V> volatile size_t caching::Cache< T, V >::limit [private]
Definition at line 326 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), caching::Cache< long long, CacheHtmlEntry >::GetLimit(), and caching::Cache< long long, CacheHtmlEntry >::SetLimit().
template<class T, class V> volatile bool caching::Cache< T, V >::deleteOnGet [private]
Definition at line 327 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), and caching::Cache< long long, CacheHtmlEntry >::GetItem().
template<class T, class V> size_t caching::Cache< T, V >::matches [mutable, private]
Definition at line 329 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::GetByValue(), caching::Cache< long long, CacheHtmlEntry >::GetItem(), and caching::Cache< long long, CacheHtmlEntry >::GetMatches().
template<class T, class V> size_t caching::Cache< T, V >::misses [mutable, private]
Definition at line 330 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::GetByValue(), caching::Cache< long long, CacheHtmlEntry >::GetItem(), caching::Cache< long long, CacheHtmlEntry >::GetMisses(), and caching::Cache< long long, CacheHtmlEntry >::GetMissingItems().
template<class T, class V> threading::Mutex caching::Cache< T, V >::mutex [mutable, private]
Definition at line 332 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), caching::Cache< long long, CacheHtmlEntry >::ClearItems(), caching::Cache< long long, CacheHtmlEntry >::DeleteItem(), caching::Cache< long long, CacheHtmlEntry >::GetByValue(), caching::Cache< long long, CacheHtmlEntry >::GetItem(), caching::Cache< long long, CacheHtmlEntry >::GetMissingItems(), caching::Cache< long long, CacheHtmlEntry >::GetSize(), and caching::Cache< long long, CacheHtmlEntry >::RemoveItem().
template<class T, class V> std::map<T,V> caching::Cache< T, V >::mapEntries [private]
Definition at line 333 of file Cache.h.
Referenced by caching::Cache< long long, CacheHtmlEntry >::AddItem(), caching::Cache< long long, CacheHtmlEntry >::ClearItems(), caching::Cache< long long, CacheHtmlEntry >::DeleteItem(), caching::Cache< long long, CacheHtmlEntry >::GetByValue(), caching::Cache< long long, CacheHtmlEntry >::GetItem(), caching::Cache< long long, CacheHtmlEntry >::GetMissingItems(), caching::Cache< long long, CacheHtmlEntry >::GetSize(), and caching::Cache< long long, CacheHtmlEntry >::RemoveItem().
The documentation for this class was generated from the following file:
Caching/src/Cache.h