DeepNet: inspectorserver::InspectorServerRequest Class Reference
inspectorserver::InspectorServerRequest Class Reference
#include <InspectorServerRequest.h>
Public Member Functions
InspectorServerRequest (fastcgiserver::FastCGIServerThread *serverThread)
virtual ~InspectorServerRequest ()
virtual void OnHandle (FCGX_Request &request)
const std::list< std::string > & HtmlCodes (void) const
void Handle (FCGX_Request &request)
handles a request.
bool IsComplete () const
checks if request completed.
template<class T >
bool GetParam (FCGX_Request &request, const std::string &key, T &value)
gets converted value from fastcgi request parameters.
bool GetParam (FCGX_Request &request, const std::string &key, std::string &value)
gets parameter from fastcgi request.
std::string GetClientAddress () const
gets connected endpoint as string.
FastCGIServerThread * ServerThread ()
gets originating server thread.
const std::string & UserAgent () const
gets client's user agent.
const std::string & RequestURI () const
gets requested uri.
const std::vector
< network::HttpCookie > & Cookies () const
gets cookies from current request.
Protected Member Functions
int register_namespaces (xmlXPathContextPtr xpathCtx, const xmlChar *nsList)
registers namespaces from nsList in xpathCtx.
bool Xpath (std::list< std::string > &queryparts, const char *filename, const xmlChar *xpathExpr, const xmlChar *nsList=0)
gets xpath from request contents (if contents are XML).
bool Validate (const std::string &xsdString, xmlDocPtr doc)
validates xml document against xsd.
Protected Attributes
char * rawPostData
buffer to raw post data.
char * rawQueryString
buffer to raw get data.
std::vector< std::pair
< std::string, std::string > > postParameters
parsed post parameters.
std::vector< std::pair
< std::string, std::string > > getParameters
parsed get parameters.
Private Attributes
std::list< std::string > htmlCodes
Detailed Description
Definition at line 18 of file InspectorServerRequest.h.
Constructor & Destructor Documentation
inspectorserver::InspectorServerRequest::InspectorServerRequest (fastcgiserver::FastCGIServerThread * serverThread)
Definition at line 14 of file InspectorServerRequest.cpp.
inspectorserver::InspectorServerRequest::~InspectorServerRequest () [virtual]
Definition at line 19 of file InspectorServerRequest.cpp.
Member Function Documentation
void inspectorserver::InspectorServerRequest::OnHandle (FCGX_Request & request) [virtual]
Implements fastcgiserver::FastCGIRequest.
Definition at line 23 of file InspectorServerRequest.cpp.
References htmlCodes, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, fastcgiserver::FastCGIRequest::rawPostData, and fastcgiserver::FastCGIRequest::Xpath().
const std::list<std::string>& inspectorserver::InspectorServerRequest::HtmlCodes (void) const [inline]
Definition at line 26 of file InspectorServerRequest.h.
References htmlCodes.
Referenced by inspectorserver::InspectorServerResponse::Process().
void fastcgiserver::FastCGIRequest::Handle (FCGX_Request & request) [inherited]
handles a request.
Parameters:
request raw fastcgi request.
Definition at line 33 of file FastCGIRequest.cpp.
References fastcgiserver::FastCGIRequest::clientIP, fastcgiserver::FastCGIRequest::clientPort, fastcgiserver::FastCGIRequest::completed, fastcgiserver::FastCGIRequest::GetParam(), fastcgiserver::FastCGIRequest::getParameters, fastcgiserver::FastCGIRequest::LogRequest(), fastcgiserver::FastCGIRequest::OnHandle(), fastcgiserver::FastCGIRequest::postParameters, fastcgiserver::FastCGIRequest::rawPostData, fastcgiserver::FastCGIRequest::rawQueryString, fastcgiserver::FastCGIRequest::ReadPostData(), fastcgiserver::FastCGIRequest::requestUri, fastcgiserver::FastCGIRequest::SafeGetEnv(), fastcgiserver::FastCGIRequest::SplitArguments(), and fastcgiserver::FastCGIRequest::userAgent.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
bool fastcgiserver::FastCGIRequest::IsComplete () const [inline, inherited]
checks if request completed.
Returns:
false if not completed, true if completed.
Definition at line 54 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::completed.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
template<class T > bool fastcgiserver::FastCGIRequest::GetParam (FCGX_Request & request, const std::string & key, T & value) [inline, inherited]
gets converted value from fastcgi request parameters.
Parameters:
request raw fastcgi request.
key keyname of parameter.
value gets filled with value of key.
Returns:
false if key does not exists, true if it does.
Definition at line 65 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle().
bool fastcgiserver::FastCGIRequest::GetParam (FCGX_Request & request, const std::string & key, std::string & value) [inline, inherited]
gets parameter from fastcgi request.
Parameters:
request raw fastcgi request.
key keyname of parameter.
value gets filled with value of key
Returns:
false if key does not exists, true if it does.
Definition at line 86 of file FastCGIRequest.h.
References tools::StringTools::ToLowerNP().
std::string fastcgiserver::FastCGIRequest::GetClientAddress () const [inline, inherited]
gets connected endpoint as string.
Returns:
connected endpoint as string.
Definition at line 101 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::clientIP, and fastcgiserver::FastCGIRequest::clientPort.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), and fastcgiserver::FastCGIRequest::LogRequest().
FastCGIServerThread* fastcgiserver::FastCGIRequest::ServerThread () [inline, inherited]
gets originating server thread.
Returns:
originating server thread.
Definition at line 107 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::serverThread.
Referenced by suggestserver::SuggestServerResponse::Process().
const std::string& fastcgiserver::FastCGIRequest::UserAgent () const [inline, inherited]
gets client's user agent.
Returns:
client's user agent.
Definition at line 113 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::userAgent.
const std::string& fastcgiserver::FastCGIRequest::RequestURI () const [inline, inherited]
gets requested uri.
Returns:
requested uri.
Definition at line 119 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::requestUri.
const std::vector<network::HttpCookie>& fastcgiserver::FastCGIRequest::Cookies () const [inline, inherited]
gets cookies from current request.
Returns:
cookies.
Definition at line 125 of file FastCGIRequest.h.
References fastcgiserver::FastCGIRequest::cookies.
Referenced by queryserver::XMLQueryResponse::LogQuery().
int fastcgiserver::FastCGIRequest::register_namespaces (xmlXPathContextPtr xpathCtx, const xmlChar * nsList) [protected, inherited]
registers namespaces from nsList in xpathCtx.
Parameters:
xpathCtx xpathCtx the pointer to an XPath context.
nsList nsList the list of known namespaces in "<prefix1>=<href1> <prefix2>=href2> ..." format.
Returns:
0 on success and a negative value otherwise.
Definition at line 283 of file FastCGIRequest.cpp.
Referenced by fastcgiserver::FastCGIRequest::Xpath().
bool fastcgiserver::FastCGIRequest::Xpath (std::list< std::string > & queryparts, const char * filename, const xmlChar * xpathExpr, const xmlChar * nsList = 0) [protected, inherited]
gets xpath from request contents (if contents are XML).
Parameters:
queryparts gets filled with xpath results.
filename xml content string for xpath.
xpathExpr xpath expression.
nsList list of allowed namespaces(???).
Returns:
false on error, true on success.
Definition at line 330 of file FastCGIRequest.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, and fastcgiserver::FastCGIRequest::register_namespaces().
Referenced by suggestserver::SuggestServerRequest::OnHandle(), OnHandle(), queryserver::XMLQueryRequest::ParseQuery(), queryserver::XMLQueryRequest::ParseQueryCriteria(), queryserver::XMLQueryRequest::ParseQueryGrouping(), and queryserver::XMLQueryRequest::ParseQueryLimitations().
bool fastcgiserver::FastCGIRequest::Validate (const std::string & xsdString, xmlDocPtr doc) [protected, inherited]
validates xml document against xsd.
Parameters:
xsdString string containing xsd.
doc xml document to validate.
Returns:
false on error, true on success.
Definition at line 241 of file FastCGIRequest.cpp.
Member Data Documentation
std::list<std::string> inspectorserver::InspectorServerRequest::htmlCodes [private]
Definition at line 29 of file InspectorServerRequest.h.
Referenced by HtmlCodes(), and OnHandle().
char* fastcgiserver::FastCGIRequest::rawPostData [protected, inherited]
buffer to raw post data.
Definition at line 168 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle(), suggestserver::SuggestServerRequest::OnHandle(), OnHandle(), queryserver::XMLQueryRequest::OnHandle(), fastcgiserver::FastCGIRequest::ReadPostData(), and fastcgiserver::FastCGIRequest::~FastCGIRequest().
char* fastcgiserver::FastCGIRequest::rawQueryString [protected, inherited]
buffer to raw get data.
Definition at line 173 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle().
std::vector<std::pair<std::string,std::string> > fastcgiserver::FastCGIRequest::postParameters [protected, inherited]
parsed post parameters.
Definition at line 178 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle(), and fastcgiserver::FastCGIRequest::LogRequest().
std::vector<std::pair<std::string,std::string> > fastcgiserver::FastCGIRequest::getParameters [protected, inherited]
parsed get parameters.
Definition at line 183 of file FastCGIRequest.h.
Referenced by fastcgiserver::FastCGIRequest::Handle(), and fastcgiserver::FastCGIRequest::LogRequest().
The documentation for this class was generated from the following files:
InspectorServer/src/InspectorServerRequest.h
InspectorServer/src/InspectorServerRequest.cpp