DeepNet: tools::FileTools Class Reference
tools::FileTools Class Reference
wrapper class for filesystem functionality.
#include <FileTools.h>
Public Member Functions
virtual ~FileTools ()
Static Public Member Functions
static bool FileExists (const std::string &fileName)
checks if a file exists.
static bool DeleteFile (const std::string &fileName)
deletes file by filename.
static bool ReadFile (const std::string &fileName, std::string &fileContents)
read file contents into string.
static bool ReadFile (const std::string &fileName, std::vector< std::string > &lines)
read file contents into list of lines.
static bool WriteFile (const std::string &fileName, const std::string &fileContents, const bool append)
writes string to a file.
static bool CompareFiles (const std::string &file1, const std::string &file2)
compares contents of 2 files.
static void ListDirectory (std::vector< std::string > &files, const std::string &directory, const bool onlyFiles=false)
gets list of contents of a directory.
static void ListDirectory (std::vector< std::string > &files, const std::string &directory, const std::string &matchString, const bool onlyFiles=false)
gets list of contents of a directory matching a regex.
Private Member Functions
FileTools ()
Detailed Description
wrapper class for filesystem functionality.
this class wraps all kind of file and filesystem related functionalities.
Definition at line 19 of file FileTools.h.
Constructor & Destructor Documentation
tools::FileTools::FileTools () [private]
Definition at line 18 of file FileTools.cpp.
tools::FileTools::~FileTools () [virtual]
Definition at line 21 of file FileTools.cpp.
Member Function Documentation
bool tools::FileTools::FileExists (const std::string & fileName) [static]
checks if a file exists.
Parameters:
fileName file name to check.
Returns:
true if existing, false if not existing.
Definition at line 24 of file FileTools.cpp.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), and toolbot::UnitTestSAX2HtmlParser::Test().
bool tools::FileTools::DeleteFile (const std::string & fileName) [static]
deletes file by filename.
Parameters:
fileName filename.
Returns:
false on error, true on success.
Definition at line 128 of file FileTools.cpp.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), toolbot::UnitTestIndexerEx::Run(), toolbot::UnitTestHtmlDocumentFactory::Run(), and toolbot::UnitTestSAX2HtmlParser::Test().
bool tools::FileTools::ReadFile (const std::string & fileName, std::string & fileContents) [static]
read file contents into string.
Parameters:
fileName filename.
fileContents gets filled with file contents.
Returns:
false on error, true on success.
Definition at line 33 of file FileTools.cpp.
Referenced by CompareFiles(), toolbot::UnitTestIndexerEx::HandleSingleFile(), fastcgiserver::FastCGIServer::InitDatabaseConfigs(), bot::ConfigFile::ParseConfigFile(), toolbot::UnitTestPCRERegex::ParseTestFile(), toolbot::UnitTestUrl::ReadInvalidURLFile(), htmlparser::UrlInserter::ReadURLFile(), toolbot::UnitTestHttpClientCURL::ReadURLFile(), toolbot::UnitTestUrl::ReadValidURLFile(), toolbot::UnitTestHtmlDocumentFactory::Run(), and toolbot::UnitTestSAX2HtmlParser::Test().
bool tools::FileTools::ReadFile (const std::string & fileName, std::vector< std::string > & lines) [static]
read file contents into list of lines.
Parameters:
fileName filename.
lines gets filled with lines.
Returns:
false on error, true on success.
Definition at line 45 of file FileTools.cpp.
References tools::StringTools::ReplaceString().
bool tools::FileTools::WriteFile (const std::string & fileName, const std::string & fileContents, const bool append) [static]
writes string to a file.
Parameters:
fileName filename.
fileContents content to be written.
append true if appending to file, false if file should be truncated before writing.
Returns:
false on error, true on success.
Definition at line 72 of file FileTools.cpp.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), toolbot::UnitTestHtmlDocumentFactory::Run(), and toolbot::UnitTestSAX2HtmlParser::Test().
bool tools::FileTools::CompareFiles (const std::string & file1, const std::string & file2) [static]
compares contents of 2 files.
Parameters:
file1 first file.
file2 second file.
Returns:
false if not equal, true if equal.
Definition at line 133 of file FileTools.cpp.
References ReadFile().
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), and toolbot::UnitTestSAX2HtmlParser::Test().
void tools::FileTools::ListDirectory (std::vector< std::string > & files, const std::string & directory, const bool onlyFiles = false) [static]
gets list of contents of a directory.
Parameters:
files gets filled with files in directory.
directory directory to list.
onlyFiles true if only files should be listed, if false directories are also in files lists.
Definition at line 84 of file FileTools.cpp.
Referenced by toolbot::UnitTestIndexerEx::Run(), toolbot::UnitTestHtmlDocumentFactory::Run(), toolbot::UnitTestSAX2HtmlParser::Test(), toolbot::UnitTestIndexerEx::UnitTestIndexerEx(), and toolbot::UnitTestSAX2HtmlParser::UnitTestSAX2HtmlParser().
void tools::FileTools::ListDirectory (std::vector< std::string > & files, const std::string & directory, const std::string & matchString, const bool onlyFiles = false) [static]
gets list of contents of a directory matching a regex.
Parameters:
files gets filled with files in directory.
directory directory to list.
matchString pcre compatible regex a filename must match.
onlyFiles true if only files should be listed, if false directories are also in files lists.
Definition at line 89 of file FileTools.cpp.
References tools::PCRERegex::Match().
The documentation for this class was generated from the following files:
Tools/src/FileTools.h
Tools/src/FileTools.cpp