DeepNet: database::SelectStatement Class Reference
database::SelectStatement Class Reference
implements generic sql select statement.
#include <SelectStatement.h>
Public Types
enum StatementType {
INSERT_STMT, INSERT_OR_UPDATE_STMT, UPDATE_STMT, SELECT_STMT,
DELETE_STMT
}
type of sql statement.
Public Member Functions
SelectStatement (TableDefinition *definition, const std::string &tableAlias)
construct with a table definition and a table alias.
SelectStatement (TableDefinition *definition)
construct with a table definition.
virtual ~SelectStatement ()
void SelectAllColumns ()
selects all columns of statement's table.
void SelectAddCountColumn (TableColumnDefinition *column, const std::string &tableAlias, const std::string &columnAlias)
creates a COUNT(column) column.
void SelectAddColumn (TableColumnDefinition *column)
adds single column.
void SelectAddColumn (TableColumnDefinition *column, const std::string &tableAlias, const std::string &columnAlias)
adds single column with table- and column alias.
void SelectAddColumnAlias (TableColumnDefinition *column, const std::string &columnAlias)
adds single column with column alias.
WhereCondition & Where (void)
gets where condition of this statement.
OrderByClause & OrderBy (void)
gets order by clause of this statement.
GroupByClause & GroupBy (void)
gets group by clause of this statement.
virtual InnerJoinCondition & InnerJoin (void)
gets inner join condition for this statement.
virtual std::string ToSQL (database::DatabaseConnection *db) const
gets sql equivalent of this statement.
const std::string & TableAlias (void) const
gets table alias of this statement's table.
const std::string & TableName (void) const
gets table name of this statement's table.
const std::string & DatabaseName (void) const
gets database name of this statement's table.
void SetLimit (unsigned int limit)
sets the LIMIT part of the sql statement
Protected Member Functions
std::string GetFullQualifiedTableName () const
gets the fully qualified name of this statement's table.
Protected Attributes
TableDefinition * tableDefinition
definition of this statement's table.
std::string tableAlias
table alias, empty if disabled.
unsigned int limit
maximum number of rows returned
StatementType typeStmt
type of this statement.
Private Member Functions
std::string CreateSelectColumnString () const
virtual std::string GetColumnAliasString (const std::string &columnAlias) const
Private Attributes
InnerJoinCondition innerJoin
WhereCondition whereCondition
OrderByClause orderByClause
GroupByClause groupByClause
std::vector< SelectColumn > selectColumns
Detailed Description
implements generic sql select statement.
See also:
database::MySQLSelectStatement
database::DB2SelectStatement
Definition at line 64 of file SelectStatement.h.
Member Enumeration Documentation
enum database::Statement::StatementType [inherited]
type of sql statement.
Enumerator:
INSERT_STMT
insert statement.
See also:
database::InsertStatement
INSERT_OR_UPDATE_STMT
insert or update (if duplicate).
See also:
database::InsertOrUpdateStatement
UPDATE_STMT
update statement.
See also:
database::UpdateStatement
SELECT_STMT
select statement.
See also:
database::SelectStatement
DELETE_STMT
delete statement.
See also:
database::DeleteStatement
Definition at line 28 of file Statement.h.
Constructor & Destructor Documentation
database::SelectStatement::SelectStatement (TableDefinition * definition, const std::string & tableAlias)
construct with a table definition and a table alias.
the given table definition is used in the "SELECT ... FROM <table>" part of the statement.
Parameters:
definition table definition.
tableAlias table name alias.
Definition at line 25 of file SelectStatement.cpp.
database::SelectStatement::SelectStatement (TableDefinition * definition)
construct with a table definition.
the given table definition is used in the "SELECT ... FROM <table>" part of the statement.
Parameters:
definition table definition.
Definition at line 20 of file SelectStatement.cpp.
database::SelectStatement::~SelectStatement () [virtual]
Definition at line 30 of file SelectStatement.cpp.
References selectColumns.
Member Function Documentation
void database::SelectStatement::SelectAllColumns ()
selects all columns of statement's table.
Definition at line 39 of file SelectStatement.cpp.
References database::SelectColumn::colDef, database::SelectColumn::doDelete, database::TableDefinition::GetConstColumnDefinitions(), selectColumns, database::SelectColumn::tableAlias, database::Statement::TableAlias(), and database::Statement::tableDefinition.
Referenced by parser::CommerceSearchMatchCriteria::GetAll(), database::cacherobotsTableBase::GetBy_action_time(), database::cacheurlTableBase::GetBy_action_time(), database::cachesecondleveldomainTableBase::GetBy_action_time(), database::cachehtmlTableBase::GetBy_action_time(), database::cacheparsedTableBase::GetBy_action_time(), database::cachesubdomainTableBase::GetBy_action_time(), database::logmessagesTableBase::GetBy_actiontime(), database::logmessagesTableBase::GetBy_appName(), database::documentcodeTableBase::GetBy_code(), database::urlstagesTableBase::GetBy_content_length(), database::urlstagesTableBase::GetBy_content_md5(), database::urlstagesTableBase::GetBy_content_type(), database::hyperlinksTableBase::GetBy_count(), database::locksecondleveldomainTableBase::GetBy_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetBy_CRAWLERSESSION_ID(), database::fencedsearchTableBase::GetBy_CUSTOMER_ID(), database::customersessionsTableBase::GetBy_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetBy_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetBy_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetBy_CUSTOMER_ID(), database::customerdomainsTableBase::GetBy_CUSTOMER_ID(), database::customerqueriesTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetBy_DICT_ID(), database::dockeyTableBase::GetBy_DICT_ID(), database::docmetaTableBase::GetBy_DICT_ID(), database::customerproductkeywordsTableBase::GetBy_DICT_ID(), database::dockeyposTableBase::GetBy_DOCKEY_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::dataminingblacklistTableBase::GetBy_domain(), database::customerdomainsTableBase::GetBy_domain(), database::urlstagesTableBase::GetBy_download_speed(), database::urlstagesTableBase::GetBy_download_time(), database::urlstagesTableBase::GetBy_ext_links(), database::imagesTableBase::GetBy_found_date(), database::urlsTableBase::GetBy_found_date(), database::urlstagesTableBase::GetBy_found_date(), database::customermatchcriteriagrouptypeTableBase::GetBy_groupPosition(), database::urlstagesTableBase::GetBy_html_errors(), database::crawlersessionsTableBase::GetBy_ID(), database::keywordqueryTableBase::GetBy_ID(), database::matchcriteriaTableBase::GetBy_ID(), database::schemesTableBase::GetBy_ID(), database::searchqueryTableBase::GetBy_ID(), database::secondleveldomainsTableBase::GetBy_ID(), database::subdomainsTableBase::GetBy_ID(), database::topleveldomainsTableBase::GetBy_ID(), database::fencedsearchTableBase::GetBy_ID(), database::customerproducturlsTableBase::GetBy_ID(), database::customerqueriesTableBase::GetBy_ID(), database::customersessionsTableBase::GetBy_ID(), database::latesturlstagesTableBase::GetBy_ID(), database::customersTableBase::GetBy_ID(), database::customersyncurlTableBase::GetBy_ID(), database::dataminingalertsTableBase::GetBy_ID(), database::searchquerykeywordsTableBase::GetBy_ID(), database::dataminingblacklistTableBase::GetBy_ID(), database::dataminingcriteriaTableBase::GetBy_ID(), database::dataminingcustomersessionTableBase::GetBy_ID(), database::dataminingcustomerTableBase::GetBy_ID(), database::dictTableBase::GetBy_ID(), database::customerproductimagesTableBase::GetBy_ID(), database::documentcodeTableBase::GetBy_ID(), database::customerproductkeywordsTableBase::GetBy_ID(), database::docurlTableBase::GetBy_ID(), database::hyperlinksTableBase::GetBy_ID(), database::customerdomainblacklistTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_ID(), database::customersynccrawlerTableBase::GetBy_ID(), database::metainfoTableBase::GetBy_ID(), database::dataminingcriteriaalertsTableBase::GetBy_ID(), database::dockeyposTableBase::GetBy_ID(), database::customermatchcriteriaTableBase::GetBy_ID(), database::dockeyTableBase::GetBy_ID(), database::customerproductsTableBase::GetBy_ID(), database::cachehtmlTableBase::GetBy_ID(), database::cacheparsedTableBase::GetBy_ID(), database::cachesecondleveldomainTableBase::GetBy_ID(), database::customerdomainsTableBase::GetBy_ID(), database::queryresultsTableBase::GetBy_ID(), database::customerkeywordsTableBase::GetBy_ID(), database::syncurlsTableBase::GetBy_ID(), database::cachesubdomainTableBase::GetBy_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_ID(), database::cacheurlTableBase::GetBy_ID(), database::cacherobotsTableBase::GetBy_ID(), database::docmetaTableBase::GetBy_ID(), database::logmessagesTableBase::GetBy_ID(), database::imagesTableBase::GetBy_ID(), database::urlsTableBase::GetBy_ID(), database::urlstagesTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetBy_imageUrl(), database::urlstagesTableBase::GetBy_int_links(), database::customerdomainsTableBase::GetBy_isDomainRegex(), database::customerkeywordsTableBase::GetBy_isKeywordRegex(), database::customerdomainblacklistTableBase::GetBy_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetBy_isPrimaryKey(), database::dataminingcriteriaTableBase::GetBy_keyword(), database::dictTableBase::GetBy_keyword(), database::customerkeywordsTableBase::GetBy_keyword(), database::searchquerykeywordsTableBase::GetBy_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetBy_last_change(), database::customersTableBase::GetBy_login(), database::dataminingcustomerTableBase::GetBy_login(), database::logmessagesTableBase::GetBy_loglevel(), database::customermatchcriteriaTableBase::GetBy_MATCHCRITERIA_ID(), database::cacherobotsTableBase::GetBy_matches(), database::cachesecondleveldomainTableBase::GetBy_matches(), database::cacheparsedTableBase::GetBy_matches(), database::cachehtmlTableBase::GetBy_matches(), database::cachesubdomainTableBase::GetBy_matches(), database::cacheurlTableBase::GetBy_matches(), database::logmessagesTableBase::GetBy_message(), database::cacheurlTableBase::GetBy_misses(), database::cachesecondleveldomainTableBase::GetBy_misses(), database::cacherobotsTableBase::GetBy_misses(), database::cacheparsedTableBase::GetBy_misses(), database::cachesubdomainTableBase::GetBy_misses(), database::cachehtmlTableBase::GetBy_misses(), database::dictTableBase::GetBy_occurrence(), database::dockeyTableBase::GetBy_occurrence(), database::docmetaTableBase::GetBy_occurrence(), database::queryresultsTableBase::GetBy_order_position(), database::dockeyposTableBase::GetBy_paragraph(), database::dataminingalertsTableBase::GetBy_param(), database::customersTableBase::GetBy_password(), database::dataminingcustomerTableBase::GetBy_password(), database::customerdomainblacklistTableBase::GetBy_path(), database::imagesTableBase::GetBy_path_part(), database::urlsTableBase::GetBy_path_part(), database::logmessagesTableBase::GetBy_pid(), database::imagesTableBase::GetBy_port(), database::urlsTableBase::GetBy_port(), database::dockeyposTableBase::GetBy_position(), database::urlstagesTableBase::GetBy_primary_ip(), database::urlstagesTableBase::GetBy_primary_port(), database::customerproducturlsTableBase::GetBy_PRODUCT_ID(), database::customerproductimagesTableBase::GetBy_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetBy_PRODUCT_ID(), database::customerproductsTableBase::GetBy_productBrand(), database::customerproductsTableBase::GetBy_productName(), database::customerproductsTableBase::GetBy_productNo(), database::customerqueriesTableBase::GetBy_query(), database::keywordqueryTableBase::GetBy_query_part(), database::urlstagesTableBase::GetBy_redirect_count(), database::matchcriteriaTableBase::GetBy_regex(), database::urlstagesTableBase::GetBy_response_code(), database::customerdomainsTableBase::GetBy_revisitInterval(), database::locksecondleveldomainTableBase::GetBy_schedule(), database::syncurlsTableBase::GetBy_schedule(), database::customersyncurlTableBase::GetBy_scheduled(), database::customersynccrawlerTableBase::GetBy_scheduled(), database::schemesTableBase::GetBy_scheme(), database::imagesTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_SCHEME_ID(), database::imagesTableBase::GetBy_search_part(), database::urlsTableBase::GetBy_search_part(), database::searchquerykeywordsTableBase::GetBy_SEARCHQUERY_ID(), database::queryresultsTableBase::GetBy_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetBy_session(), database::dataminingcustomersessionTableBase::GetBy_session(), database::customersessionsTableBase::GetBy_session(), database::cachesecondleveldomainTableBase::GetBy_size(), database::cachesubdomainTableBase::GetBy_size(), database::cacheparsedTableBase::GetBy_size(), database::cachehtmlTableBase::GetBy_size(), database::cacheurlTableBase::GetBy_size(), database::cacherobotsTableBase::GetBy_size(), database::subdomainsTableBase::GetBy_subdomain(), database::imagesTableBase::GetBy_SUBDOMAIN_ID(), database::urlsTableBase::GetBy_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_target(), database::imagelinksTableBase::GetBy_TARGET_URL_ID(), database::hyperlinksTableBase::GetBy_TARGET_URL_ID(), database::logmessagesTableBase::GetBy_threadName(), database::logmessagesTableBase::GetBy_tid(), database::topleveldomainsTableBase::GetBy_tld(), database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetBy_type(), database::dataminingcriteriaTableBase::GetBy_type(), database::metainfoTableBase::GetBy_type(), database::customermatchcriteriagrouptypeTableBase::GetBy_type(), database::customermatchcriteriaTableBase::GetBy_type(), database::docmetaTableBase::GetBy_type(), database::urlstagesTableBase::GetBy_upload_speed(), database::latesturlstagesTableBase::GetBy_URL_ID(), database::customersyncurlTableBase::GetBy_URL_ID(), database::customerproducturlsTableBase::GetBy_URL_ID(), database::syncurlsTableBase::GetBy_URL_ID(), database::docurlTableBase::GetBy_URL_ID(), database::queryresultsTableBase::GetBy_URL_ID(), database::urlstagesTableBase::GetBy_URL_ID(), database::imagesTableBase::GetBy_url_md5(), database::urlsTableBase::GetBy_url_md5(), database::documentcodeTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_URLSTAGE_ID(), database::latesturlstagesTableBase::GetBy_URLSTAGE_ID(), database::hyperlinksTableBase::GetBy_URLSTAGE_ID(), database::dockeyTableBase::GetBy_URLSTAGE_ID(), database::docmetaTableBase::GetBy_URLSTAGE_ID(), database::imagelinksTableBase::GetBy_URLSTAGE_ID(), database::queryresultsTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_value(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), htmlparser::TLD::Init(), queryserver::XMLQueryResponse::ProcessExistQuery(), and crawler::FencedCrawler::StartCrawler().
void database::SelectStatement::SelectAddCountColumn (TableColumnDefinition * column, const std::string & tableAlias, const std::string & columnAlias)
creates a COUNT(column) column.
Parameters:
column column of which count() should be done.
tableAlias table alias of column of which count() should be done.
columnAlias alias of column of which count() should be done.
Definition at line 71 of file SelectStatement.cpp.
References database::SelectColumn::colDef, database::SelectColumn::columnAlias, database::SelectColumn::isCountColumn, selectColumns, database::SelectColumn::tableAlias, and database::Statement::tableAlias.
Referenced by queryserver::XMLQueryResponse::ProcessExistQuery(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
void database::SelectStatement::SelectAddColumn (TableColumnDefinition * column)
adds single column.
Parameters:
column column to add.
Definition at line 50 of file SelectStatement.cpp.
References database::SelectColumn::colDef, and selectColumns.
Referenced by queryserver::XMLQueryResponse::GetPagesByDomain(), and queryserver::XMLQueryResponse::GetPageUrlStageInfo().
void database::SelectStatement::SelectAddColumn (TableColumnDefinition * column, const std::string & tableAlias, const std::string & columnAlias)
adds single column with table- and column alias.
Parameters:
column column to be added.
tableAlias table alias of column to be added.
columnAlias alias of column to be added.
Definition at line 63 of file SelectStatement.cpp.
References database::SelectColumn::colDef, database::SelectColumn::columnAlias, selectColumns, database::SelectColumn::tableAlias, and database::Statement::tableAlias.
void database::SelectStatement::SelectAddColumnAlias (TableColumnDefinition * column, const std::string & columnAlias)
adds single column with column alias.
Parameters:
column column to be added.
columnAlias alias of column to be added.
Definition at line 56 of file SelectStatement.cpp.
References database::SelectColumn::colDef, database::SelectColumn::columnAlias, and selectColumns.
WhereCondition& database::SelectStatement::Where (void) [inline]
gets where condition of this statement.
Returns:
where condition.
Definition at line 125 of file SelectStatement.h.
References whereCondition.
Referenced by database::cachehtmlTableBase::GetBy_action_time(), database::cacherobotsTableBase::GetBy_action_time(), database::cacheurlTableBase::GetBy_action_time(), database::cacheparsedTableBase::GetBy_action_time(), database::cachesecondleveldomainTableBase::GetBy_action_time(), database::cachesubdomainTableBase::GetBy_action_time(), database::logmessagesTableBase::GetBy_actiontime(), database::logmessagesTableBase::GetBy_appName(), database::documentcodeTableBase::GetBy_code(), database::urlstagesTableBase::GetBy_content_length(), database::urlstagesTableBase::GetBy_content_md5(), database::urlstagesTableBase::GetBy_content_type(), database::hyperlinksTableBase::GetBy_count(), database::locksecondleveldomainTableBase::GetBy_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetBy_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetBy_CRAWLERSESSION_ID(), database::fencedsearchTableBase::GetBy_CUSTOMER_ID(), database::customersessionsTableBase::GetBy_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetBy_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetBy_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetBy_CUSTOMER_ID(), database::customerdomainsTableBase::GetBy_CUSTOMER_ID(), database::customerqueriesTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetBy_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetBy_DICT_ID(), database::dockeyTableBase::GetBy_DICT_ID(), database::customerproductkeywordsTableBase::GetBy_DICT_ID(), database::docmetaTableBase::GetBy_DICT_ID(), database::dockeyposTableBase::GetBy_DOCKEY_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::dataminingblacklistTableBase::GetBy_domain(), database::customerdomainsTableBase::GetBy_domain(), database::urlstagesTableBase::GetBy_download_speed(), database::urlstagesTableBase::GetBy_download_time(), database::urlstagesTableBase::GetBy_ext_links(), database::imagesTableBase::GetBy_found_date(), database::urlsTableBase::GetBy_found_date(), database::urlstagesTableBase::GetBy_found_date(), database::customermatchcriteriagrouptypeTableBase::GetBy_groupPosition(), database::urlstagesTableBase::GetBy_html_errors(), database::crawlersessionsTableBase::GetBy_ID(), database::keywordqueryTableBase::GetBy_ID(), database::matchcriteriaTableBase::GetBy_ID(), database::schemesTableBase::GetBy_ID(), database::searchqueryTableBase::GetBy_ID(), database::secondleveldomainsTableBase::GetBy_ID(), database::subdomainsTableBase::GetBy_ID(), database::topleveldomainsTableBase::GetBy_ID(), database::fencedsearchTableBase::GetBy_ID(), database::customerproducturlsTableBase::GetBy_ID(), database::customerqueriesTableBase::GetBy_ID(), database::customersessionsTableBase::GetBy_ID(), database::latesturlstagesTableBase::GetBy_ID(), database::customersTableBase::GetBy_ID(), database::customersyncurlTableBase::GetBy_ID(), database::dataminingalertsTableBase::GetBy_ID(), database::searchquerykeywordsTableBase::GetBy_ID(), database::dataminingblacklistTableBase::GetBy_ID(), database::dataminingcriteriaTableBase::GetBy_ID(), database::dataminingcustomersessionTableBase::GetBy_ID(), database::dataminingcustomerTableBase::GetBy_ID(), database::dictTableBase::GetBy_ID(), database::customerproductimagesTableBase::GetBy_ID(), database::customerproductkeywordsTableBase::GetBy_ID(), database::documentcodeTableBase::GetBy_ID(), database::docurlTableBase::GetBy_ID(), database::hyperlinksTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_ID(), database::customerdomainblacklistTableBase::GetBy_ID(), database::customersynccrawlerTableBase::GetBy_ID(), database::metainfoTableBase::GetBy_ID(), database::dataminingcriteriaalertsTableBase::GetBy_ID(), database::dockeyposTableBase::GetBy_ID(), database::customermatchcriteriaTableBase::GetBy_ID(), database::dockeyTableBase::GetBy_ID(), database::customerproductsTableBase::GetBy_ID(), database::cachehtmlTableBase::GetBy_ID(), database::customerdomainsTableBase::GetBy_ID(), database::cachesecondleveldomainTableBase::GetBy_ID(), database::cacheparsedTableBase::GetBy_ID(), database::queryresultsTableBase::GetBy_ID(), database::customerkeywordsTableBase::GetBy_ID(), database::syncurlsTableBase::GetBy_ID(), database::customermatchcriteriagrouptypeTableBase::GetBy_ID(), database::cachesubdomainTableBase::GetBy_ID(), database::cacherobotsTableBase::GetBy_ID(), database::docmetaTableBase::GetBy_ID(), database::cacheurlTableBase::GetBy_ID(), database::logmessagesTableBase::GetBy_ID(), database::imagesTableBase::GetBy_ID(), database::urlsTableBase::GetBy_ID(), database::urlstagesTableBase::GetBy_ID(), database::imagelinksTableBase::GetBy_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetBy_imageUrl(), database::urlstagesTableBase::GetBy_int_links(), database::customerdomainsTableBase::GetBy_isDomainRegex(), database::customerkeywordsTableBase::GetBy_isKeywordRegex(), database::customerdomainblacklistTableBase::GetBy_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetBy_isPrimaryKey(), database::dataminingcriteriaTableBase::GetBy_keyword(), database::dictTableBase::GetBy_keyword(), database::customerkeywordsTableBase::GetBy_keyword(), database::searchquerykeywordsTableBase::GetBy_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetBy_last_change(), database::customersTableBase::GetBy_login(), database::dataminingcustomerTableBase::GetBy_login(), database::logmessagesTableBase::GetBy_loglevel(), database::customermatchcriteriaTableBase::GetBy_MATCHCRITERIA_ID(), database::cacheurlTableBase::GetBy_matches(), database::cacherobotsTableBase::GetBy_matches(), database::cachesecondleveldomainTableBase::GetBy_matches(), database::cacheparsedTableBase::GetBy_matches(), database::cachesubdomainTableBase::GetBy_matches(), database::cachehtmlTableBase::GetBy_matches(), database::logmessagesTableBase::GetBy_message(), database::cachehtmlTableBase::GetBy_misses(), database::cacheurlTableBase::GetBy_misses(), database::cacherobotsTableBase::GetBy_misses(), database::cachesecondleveldomainTableBase::GetBy_misses(), database::cacheparsedTableBase::GetBy_misses(), database::cachesubdomainTableBase::GetBy_misses(), database::dictTableBase::GetBy_occurrence(), database::dockeyTableBase::GetBy_occurrence(), database::docmetaTableBase::GetBy_occurrence(), database::queryresultsTableBase::GetBy_order_position(), database::dockeyposTableBase::GetBy_paragraph(), database::dataminingalertsTableBase::GetBy_param(), database::customersTableBase::GetBy_password(), database::dataminingcustomerTableBase::GetBy_password(), database::customerdomainblacklistTableBase::GetBy_path(), database::imagesTableBase::GetBy_path_part(), database::urlsTableBase::GetBy_path_part(), database::logmessagesTableBase::GetBy_pid(), database::imagesTableBase::GetBy_port(), database::urlsTableBase::GetBy_port(), database::dockeyposTableBase::GetBy_position(), database::urlstagesTableBase::GetBy_primary_ip(), database::urlstagesTableBase::GetBy_primary_port(), database::customerproducturlsTableBase::GetBy_PRODUCT_ID(), database::customerproductimagesTableBase::GetBy_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetBy_PRODUCT_ID(), database::customerproductsTableBase::GetBy_productBrand(), database::customerproductsTableBase::GetBy_productName(), database::customerproductsTableBase::GetBy_productNo(), database::customerqueriesTableBase::GetBy_query(), database::keywordqueryTableBase::GetBy_query_part(), database::urlstagesTableBase::GetBy_redirect_count(), database::matchcriteriaTableBase::GetBy_regex(), database::urlstagesTableBase::GetBy_response_code(), database::customerdomainsTableBase::GetBy_revisitInterval(), database::locksecondleveldomainTableBase::GetBy_schedule(), database::syncurlsTableBase::GetBy_schedule(), database::customersyncurlTableBase::GetBy_scheduled(), database::customersynccrawlerTableBase::GetBy_scheduled(), database::schemesTableBase::GetBy_scheme(), database::imagesTableBase::GetBy_SCHEME_ID(), database::urlsTableBase::GetBy_SCHEME_ID(), database::imagesTableBase::GetBy_search_part(), database::urlsTableBase::GetBy_search_part(), database::queryresultsTableBase::GetBy_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::GetBy_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetBy_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetBy_session(), database::customersessionsTableBase::GetBy_session(), database::dataminingcustomersessionTableBase::GetBy_session(), database::cacherobotsTableBase::GetBy_size(), database::cachesecondleveldomainTableBase::GetBy_size(), database::cacheparsedTableBase::GetBy_size(), database::cachesubdomainTableBase::GetBy_size(), database::cachehtmlTableBase::GetBy_size(), database::cacheurlTableBase::GetBy_size(), database::subdomainsTableBase::GetBy_subdomain(), database::urlsTableBase::GetBy_SUBDOMAIN_ID(), database::imagesTableBase::GetBy_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetBy_target(), database::imagelinksTableBase::GetBy_TARGET_URL_ID(), database::hyperlinksTableBase::GetBy_TARGET_URL_ID(), database::logmessagesTableBase::GetBy_threadName(), database::logmessagesTableBase::GetBy_tid(), database::topleveldomainsTableBase::GetBy_tld(), database::urlsTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetBy_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetBy_type(), database::dataminingcriteriaTableBase::GetBy_type(), database::metainfoTableBase::GetBy_type(), database::customermatchcriteriagrouptypeTableBase::GetBy_type(), database::customermatchcriteriaTableBase::GetBy_type(), database::docmetaTableBase::GetBy_type(), database::urlstagesTableBase::GetBy_upload_speed(), database::latesturlstagesTableBase::GetBy_URL_ID(), database::customersyncurlTableBase::GetBy_URL_ID(), database::customerproducturlsTableBase::GetBy_URL_ID(), database::docurlTableBase::GetBy_URL_ID(), database::syncurlsTableBase::GetBy_URL_ID(), database::queryresultsTableBase::GetBy_URL_ID(), database::urlstagesTableBase::GetBy_URL_ID(), database::urlsTableBase::GetBy_url_md5(), database::imagesTableBase::GetBy_url_md5(), database::documentcodeTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_URLSTAGE_ID(), database::latesturlstagesTableBase::GetBy_URLSTAGE_ID(), database::dockeyTableBase::GetBy_URLSTAGE_ID(), database::hyperlinksTableBase::GetBy_URLSTAGE_ID(), database::docmetaTableBase::GetBy_URLSTAGE_ID(), database::imagelinksTableBase::GetBy_URLSTAGE_ID(), database::queryresultsTableBase::GetBy_URLSTAGE_ID(), database::metainfoTableBase::GetBy_value(), caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), queryserver::XMLQueryResponse::GetKeywordIDs(), queryserver::XMLQueryResponse::GetPageInfoByUrlStageID(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByMeta(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), queryserver::XMLQueryResponse::ProcessExistQuery(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
OrderByClause& database::SelectStatement::OrderBy (void) [inline]
gets order by clause of this statement.
Returns:
order by clause.
Definition at line 131 of file SelectStatement.h.
References orderByClause.
Referenced by queryserver::XMLQueryResponse::GetKeywordIDs(), queryserver::XMLQueryResponse::GetPagesByContent(), queryserver::XMLQueryResponse::GetPagesByMeta(), and queryserver::XMLQueryResponse::ProcessExistQuery().
GroupByClause& database::SelectStatement::GroupBy (void) [inline]
gets group by clause of this statement.
Returns:
group by clause.
Definition at line 137 of file SelectStatement.h.
References groupByClause.
virtual InnerJoinCondition& database::SelectStatement::InnerJoin (void) [inline, virtual]
gets inner join condition for this statement.
Returns:
inner join condition.
Implements database::Statement.
Definition at line 140 of file SelectStatement.h.
References innerJoin.
std::string database::SelectStatement::ToSQL (database::DatabaseConnection * db) const [virtual]
gets sql equivalent of this statement.
Parameters:
db database connection.
Returns:
sql string.
Implements database::Statement.
Definition at line 110 of file SelectStatement.cpp.
References CreateSelectColumnString(), database::Statement::GetFullQualifiedTableName(), groupByClause, innerJoin, database::Statement::limit, orderByClause, selectColumns, database::Statement::tableAlias, THROW_EXCEPTION, database::GroupByClause::ToString(), database::WhereCondition::ToString(), database::InnerJoinCondition::ToString(), database::OrderByClause::ToString(), and whereCondition.
Referenced by database::MySQLSelectStatement::ToSQL().
std::string database::SelectStatement::CreateSelectColumnString () const [private]
Definition at line 80 of file SelectStatement.cpp.
References GetColumnAliasString(), and selectColumns.
Referenced by ToSQL().
std::string database::SelectStatement::GetColumnAliasString (const std::string & columnAlias) const [private, virtual]
Definition at line 106 of file SelectStatement.cpp.
Referenced by CreateSelectColumnString().
const std::string & database::Statement::TableAlias (void) const [inherited]
gets table alias of this statement's table.
Returns:
empty if no alias specified, otherwise alias name for this statement's table.
Definition at line 73 of file Statement.cpp.
References database::Statement::tableAlias.
Referenced by SelectAllColumns(), database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), and database::UpdateStatement::ToSQL().
const std::string & database::Statement::TableName (void) const [inherited]
gets table name of this statement's table.
Returns:
table name.
Definition at line 53 of file Statement.cpp.
References database::Statement::tableDefinition, and database::TableDefinition::TableName().
const std::string & database::Statement::DatabaseName (void) const [inherited]
gets database name of this statement's table.
Returns:
database name.
Definition at line 58 of file Statement.cpp.
References database::TableDefinition::DatabaseName(), and database::Statement::tableDefinition.
void database::Statement::SetLimit (unsigned int limit) [inherited]
sets the LIMIT part of the sql statement
Parameters:
limit maximum number of returned rows (0 to disable).
Definition at line 68 of file Statement.cpp.
References database::Statement::limit.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and database::TableBase::Update().
std::string database::Statement::GetFullQualifiedTableName () const [protected, inherited]
gets the fully qualified name of this statement's table.
i.e. database_name.table_name.
Returns:
fully qualified name.
Definition at line 63 of file Statement.cpp.
References database::TableDefinition::GetFullQualifiedTableName(), and database::Statement::tableDefinition.
Referenced by database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), database::UpdateStatement::ToSQL(), and ToSQL().
Member Data Documentation
InnerJoinCondition database::SelectStatement::innerJoin [private]
Definition at line 148 of file SelectStatement.h.
Referenced by InnerJoin(), and ToSQL().
WhereCondition database::SelectStatement::whereCondition [private]
Definition at line 149 of file SelectStatement.h.
Referenced by ToSQL(), and Where().
OrderByClause database::SelectStatement::orderByClause [private]
Definition at line 150 of file SelectStatement.h.
Referenced by OrderBy(), and ToSQL().
GroupByClause database::SelectStatement::groupByClause [private]
Definition at line 151 of file SelectStatement.h.
Referenced by GroupBy(), and ToSQL().
std::vector<SelectColumn> database::SelectStatement::selectColumns [private]
Definition at line 153 of file SelectStatement.h.
Referenced by CreateSelectColumnString(), SelectAddColumn(), SelectAddColumnAlias(), SelectAddCountColumn(), SelectAllColumns(), ToSQL(), and ~SelectStatement().
TableDefinition* database::Statement::tableDefinition [protected, inherited]
definition of this statement's table.
Definition at line 141 of file Statement.h.
Referenced by database::Statement::DatabaseName(), database::Statement::GetFullQualifiedTableName(), SelectAllColumns(), database::Statement::TableName(), and database::Statement::~Statement().
std::string database::Statement::tableAlias [protected, inherited]
table alias, empty if disabled.
Definition at line 146 of file Statement.h.
Referenced by SelectAddColumn(), SelectAddCountColumn(), database::Statement::TableAlias(), and ToSQL().
unsigned int database::Statement::limit [protected, inherited]
maximum number of rows returned
See also:
database::Statement::SetLimit
Definition at line 152 of file Statement.h.
Referenced by database::Statement::SetLimit(), database::UpdateStatement::ToSQL(), and ToSQL().
StatementType database::Statement::typeStmt [protected, inherited]
type of this statement.
Definition at line 157 of file Statement.h.
Referenced by database::InsertOrUpdateStatement::InsertOrUpdateStatement().
The documentation for this class was generated from the following files:
Database/src/SelectStatement.h
Database/src/SelectStatement.cpp