DeepNet: caching::CacheSubdomain Class Reference
caching::CacheSubdomain Class Reference
cache for subdomains.
#include <CacheSubdomain.h>
Public Member Functions
virtual ~CacheSubdomain ()
Static Public Member Functions
static void GetSubdomainIDByDomain (database::DatabaseConnection *db, const std::string &subdomain, long long &subdomainID)
gets subdomain id by string.
static void GetDomainBySubdomainID (database::DatabaseConnection *db, const long long &subdomainID, std::string &subdomain)
gets subdomain string by subdomain id.
static void Clear (void)
removes all items from cache.
static void SetCapacity (const size_t capacity)
set current limit of cache.
static size_t GetSize ()
gets current number of entries in cache.
static size_t GetMatches ()
get current match count of cache, clearing internal match counter.
static size_t GetMisses ()
get current miss count of cache, clearing internal miss counter.
Private Member Functions
CacheSubdomain (size_t limit=0)
Private Attributes
Cache< long long, std::string > idSubdomain
Static Private Attributes
static CacheSubdomain cacheInstance
Detailed Description
cache for subdomains.
Definition at line 25 of file CacheSubdomain.h.
Constructor & Destructor Documentation
caching::CacheSubdomain::CacheSubdomain (size_t limit = 0) [private]
Definition at line 18 of file CacheSubdomain.cpp.
caching::CacheSubdomain::~CacheSubdomain () [virtual]
Definition at line 23 of file CacheSubdomain.cpp.
Member Function Documentation
void caching::CacheSubdomain::GetSubdomainIDByDomain (database::DatabaseConnection * db, const std::string & subdomain, long long & subdomainID) [static]
gets subdomain id by string.
Parameters:
db database connection.
subdomain subdomain to look for.
subdomainID gets filled with corresponding subdomain id.
Definition at line 27 of file CacheSubdomain.cpp.
References caching::Cache< T, V >::AddItem(), cacheInstance, caching::Cache< T, V >::GetByValue(), idSubdomain, database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), and database::subdomainsTableBase::Set_subdomain().
Referenced by htmlparser::DatabaseUrl::InitByHttpUrl(), and parser::GenericWebHtmlParserThread::InsertImages().
void caching::CacheSubdomain::GetDomainBySubdomainID (database::DatabaseConnection * db, const long long & subdomainID, std::string & subdomain) [static]
gets subdomain string by subdomain id.
Parameters:
db database connection.
subdomainID subdomain id to look for.
subdomain gets filled with corresponding subdomain.
Definition at line 45 of file CacheSubdomain.cpp.
References caching::Cache< T, V >::AddItem(), cacheInstance, database::subdomainsTableBase::Get_subdomain(), database::subdomainsTableBase::GetBy_ID(), caching::Cache< T, V >::GetItem(), tools::PointerContainer< T >::GetIter(), idSubdomain, tools::PointerContainer< T >::ResetIter(), tools::PointerContainer< T >::Size(), and THROW_EXCEPTION.
Referenced by htmlparser::DatabaseUrl::InitByIDs().
void caching::CacheSubdomain::Clear (void) [static]
removes all items from cache.
Definition at line 72 of file CacheSubdomain.cpp.
References cacheInstance, caching::Cache< T, V >::ClearItems(), and idSubdomain.
void caching::CacheSubdomain::SetCapacity (const size_t capacity) [static]
set current limit of cache.
Parameters:
capacity maximum number of entries in cache.
Definition at line 67 of file CacheSubdomain.cpp.
References cacheInstance, idSubdomain, and caching::Cache< T, V >::SetLimit().
Referenced by bot::Bot::InitCacheConfigParams().
static size_t caching::CacheSubdomain::GetSize () [inline, static]
gets current number of entries in cache.
Returns:
current number of entries in cache.
Definition at line 70 of file CacheSubdomain.h.
References cacheInstance, caching::Cache< T, V >::GetSize(), and idSubdomain.
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheSubdomain::GetMatches () [inline, static]
get current match count of cache, clearing internal match counter.
Returns:
number of matches.
Definition at line 76 of file CacheSubdomain.h.
References cacheInstance, caching::Cache< T, V >::GetMatches(), and idSubdomain.
Referenced by bot::Bot::WatchDog().
static size_t caching::CacheSubdomain::GetMisses () [inline, static]
get current miss count of cache, clearing internal miss counter.
Returns:
number of misses.
Definition at line 82 of file CacheSubdomain.h.
References cacheInstance, caching::Cache< T, V >::GetMisses(), and idSubdomain.
Referenced by bot::Bot::WatchDog().
Member Data Documentation
CacheSubdomain caching::CacheSubdomain::cacheInstance [static, private]
Definition at line 85 of file CacheSubdomain.h.
Referenced by Clear(), GetDomainBySubdomainID(), GetMatches(), GetMisses(), GetSize(), GetSubdomainIDByDomain(), and SetCapacity().
Cache<long long,std::string> caching::CacheSubdomain::idSubdomain [private]
Definition at line 88 of file CacheSubdomain.h.
Referenced by Clear(), GetDomainBySubdomainID(), GetMatches(), GetMisses(), GetSize(), GetSubdomainIDByDomain(), and SetCapacity().
The documentation for this class was generated from the following files:
Caching/src/CacheSubdomain.h
Caching/src/CacheSubdomain.cpp