DeepNet: SuggestServer/src/main.cpp File Reference
SuggestServer/src/main.cpp File Reference
#include <iostream>
#include <csignal>
#include <libxml/parser.h>
#include <curl/curl.h>
#include "SuggestServer.h"
#include <Thread.h>
#include <DebuggingTools.h>
#include <Logging.h>
#include <Exception.h>
Functions
void SignalHandler (int signum, siginfo_t *info, void *ucontext)
bool RegisterSignalHandlers ()
int main (int argc, char **argv)
Variables
static volatile bool run = true
static threading::Mutex signalMutex
static suggestserver::SuggestServer serverSuggest
static const int catchSignals []
static const int catchSignalCount = sizeof(catchSignals) / sizeof(catchSignals[0])
Function Documentation
void SignalHandler (int signum, siginfo_t * info, void * ucontext)
Definition at line 41 of file main.cpp.
References log::Logging::GetMaxLogLength(), tools::DebuggingTools::GetSignalInfos(), tools::DebuggingTools::SignalInfos::infoText, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, run, and log::Logging::SetMaxLogLength().
bool RegisterSignalHandlers ()
Definition at line 89 of file main.cpp.
References catchSignalCount, catchSignals, and SignalHandler().
int main (int argc, char ** argv)
Definition at line 101 of file main.cpp.
References fastcgiserver::FastCGIServer::OnException(), RegisterSignalHandlers(), run, suggestserver::SuggestServer::StartServer(), and fastcgiserver::FastCGIServer::StopServer().
Variable Documentation
volatile bool run = true [static]
Definition at line 20 of file main.cpp.
Referenced by main(), and SignalHandler().
threading::Mutex signalMutex [static]
Definition at line 21 of file main.cpp.
suggestserver::SuggestServer serverSuggest [static]
Definition at line 22 of file main.cpp.
const int catchSignals[] [static]
Initial value:
{
                SIGTERM,
                SIGPIPE,
                SIGUSR1,
                SIGINT,
                SIGSEGV,
                SIGILL,
                SIGABRT,
                SIGHUP,
}
Definition at line 24 of file main.cpp.
Referenced by RegisterSignalHandlers().
const int catchSignalCount = sizeof(catchSignals) / sizeof(catchSignals[0]) [static]
Definition at line 39 of file main.cpp.
Referenced by RegisterSignalHandlers().