DeepNet: tools::HashTools Class Reference
tools::HashTools Class Reference
wrapper class for hashing algorithms.
#include <HashTools.h>
Static Public Member Functions
static std::string GetSaltedMD5 (const char *pszInput, const char *salt)
gets salted md5 string from buffer.
static std::string GetSaltedMD5 (const char *pszInput)
gets salted md5 string from buffer with a predefined salt.
static std::string GetMD5 (const std::string &input)
gets md5 string from buffer.
static std::string GetSHA512 (const std::string &input)
gets sha512 string from buffer.
Private Member Functions
HashTools ()
virtual ~HashTools ()
Static Private Attributes
static const char salt [] = "$1$6buND7vK"
Detailed Description
wrapper class for hashing algorithms.
this class wraps all kind of hashing functionalities.
Definition at line 17 of file HashTools.h.
Constructor & Destructor Documentation
tools::HashTools::HashTools () [private]
Definition at line 23 of file HashTools.cpp.
tools::HashTools::~HashTools () [private, virtual]
Definition at line 26 of file HashTools.cpp.
Member Function Documentation
std::string tools::HashTools::GetSaltedMD5 (const char * pszInput, const char * salt) [static]
gets salted md5 string from buffer.
Parameters:
pszInput input buffer.
salt salt.
Returns:
salted md5 string.
Definition at line 29 of file HashTools.cpp.
Referenced by GetSaltedMD5().
std::string tools::HashTools::GetSaltedMD5 (const char * pszInput) [static]
gets salted md5 string from buffer with a predefined salt.
Parameters:
pszInput input buffer.
Returns:
salted md5 string.
Definition at line 38 of file HashTools.cpp.
References GetSaltedMD5(), and salt.
std::string tools::HashTools::GetMD5 (const std::string & input) [static]
gets md5 string from buffer.
Parameters:
input input buffer.
Returns:
md5 string.
Definition at line 43 of file HashTools.cpp.
Referenced by crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), and htmlparser::DatabaseUrl::Store().
std::string tools::HashTools::GetSHA512 (const std::string & input) [static]
gets sha512 string from buffer.
Parameters:
input input buffer.
Returns:
sha512 string.
Definition at line 57 of file HashTools.cpp.
Referenced by toolbot::CommerceSearchTools::AddCustomer(), and toolbot::DataMiningTools::InsertDataminingUser().
Member Data Documentation
const char tools::HashTools::salt = "$1$6buND7vK" [static, private]
Definition at line 53 of file HashTools.h.
Referenced by GetSaltedMD5().
The documentation for this class was generated from the following files:
Tools/src/HashTools.h
Tools/src/HashTools.cpp