DeepNet: toolbot::UnitTestHtmlTokeniser Class Reference
toolbot::UnitTestHtmlTokeniser Class Reference
#include <UnitTestHtmlTokeniser.h>
Public Member Functions
UnitTestHtmlTokeniser (UnitTestHtmlDocumentFactory &factory)
virtual ~UnitTestHtmlTokeniser ()
bool Parse (const char *pData, const size_t &size, const bool logVerbose=false)
parses html document from a string.
uintptr_t MapToOriginalPosition (const uintptr_t &pos) const
gets position in document (before comments etc.
void GetCurLineCol (size_t &line, size_t &col) const
void InitLineVector ()
initializes internal column/line tracking
std::string GetLineColumnString () const
gets preformated column and line string for current position
Protected Member Functions
virtual void EmitCharacter (const char charToEmit)
virtual void EmitComment ()
virtual void EmitTag ()
virtual void EmitDocType ()
virtual void SwitchState (const domparser::html5::TokeniserState &newState)
virtual void ParseError () const
Protected Attributes
TokeniserState state
Static Private Member Functions
static std::string NameFromState (const domparser::html5::TokeniserState &stateIn)
Friends
class domparser::DocumentFactory
class toolbot::UnitTestHtmlTokeniser
Detailed Description
Definition at line 19 of file UnitTestHtmlTokeniser.h.
Constructor & Destructor Documentation
toolbot::UnitTestHtmlTokeniser::UnitTestHtmlTokeniser (UnitTestHtmlDocumentFactory & factory)
Definition at line 19 of file UnitTestHtmlTokeniser.cpp.
toolbot::UnitTestHtmlTokeniser::~UnitTestHtmlTokeniser () [virtual]
Definition at line 23 of file UnitTestHtmlTokeniser.cpp.
Member Function Documentation
void toolbot::UnitTestHtmlTokeniser::EmitCharacter (const char charToEmit) [protected, virtual]
Reimplemented from domparser::html5::Tokeniser.
Definition at line 26 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), and log::Logging::LogTrace().
void toolbot::UnitTestHtmlTokeniser::EmitComment () [protected, virtual]
Reimplemented from domparser::html5::Tokeniser.
Definition at line 32 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), and log::Logging::LogTrace().
void toolbot::UnitTestHtmlTokeniser::EmitTag () [protected, virtual]
Reimplemented from domparser::html5::Tokeniser.
Definition at line 39 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), and log::Logging::LogTrace().
void toolbot::UnitTestHtmlTokeniser::EmitDocType () [protected, virtual]
Reimplemented from domparser::html5::Tokeniser.
Definition at line 46 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), and log::Logging::LogTrace().
void toolbot::UnitTestHtmlTokeniser::SwitchState (const domparser::html5::TokeniserState & newState) [protected, virtual]
Reimplemented from domparser::html5::Tokeniser.
Definition at line 53 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), log::Logging::LogTrace(), NameFromState(), and domparser::html5::Tokeniser::state.
void toolbot::UnitTestHtmlTokeniser::ParseError () const [protected, virtual]
Reimplemented from domparser::html5::Tokeniser.
Definition at line 60 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::Tokeniser::GetLineColumnString(), and log::Logging::LogTrace().
std::string toolbot::UnitTestHtmlTokeniser::NameFromState (const domparser::html5::TokeniserState & stateIn) [static, private]
Definition at line 67 of file UnitTestHtmlTokeniser.cpp.
References domparser::html5::After_attribute_name_state, domparser::html5::After_attribute_value__quoted__state, domparser::html5::After_DOCTYPE_name_state, domparser::html5::After_DOCTYPE_public_identifier_state, domparser::html5::After_DOCTYPE_public_keyword_state, domparser::html5::After_DOCTYPE_system_identifier_state, domparser::html5::After_DOCTYPE_system_keyword_state, domparser::html5::Attribute_name_state, domparser::html5::Attribute_value__double_quoted__state, domparser::html5::Attribute_value__single_quoted__state, domparser::html5::Attribute_value__unquoted__state, domparser::html5::Before_attribute_name_state, domparser::html5::Before_attribute_value_state, domparser::html5::Before_DOCTYPE_name_state, domparser::html5::Before_DOCTYPE_public_identifier_state, domparser::html5::Before_DOCTYPE_system_identifier_state, domparser::html5::Between_DOCTYPE_public_and_system_identifiers_state, domparser::html5::Bogus_comment_state, domparser::html5::Bogus_DOCTYPE_state, domparser::html5::CDATA_section_state, domparser::html5::Character_reference_in_attribute_value_state, domparser::html5::Character_reference_in_data_state, domparser::html5::Character_reference_in_RCDATA_state, domparser::html5::Comment_end_bang_state, domparser::html5::Comment_end_dash_state, domparser::html5::Comment_end_state, domparser::html5::Comment_start_dash_state, domparser::html5::Comment_start_state, domparser::html5::Comment_state, domparser::html5::Data_state, domparser::html5::DOCTYPE_name_state, domparser::html5::DOCTYPE_public_identifier__double_quoted__state, domparser::html5::DOCTYPE_public_identifier__single_quoted__state, domparser::html5::DOCTYPE_state, domparser::html5::DOCTYPE_system_identifier__double_quoted__state, domparser::html5::DOCTYPE_system_identifier__single_quoted__state, domparser::html5::End_tag_open_state, domparser::html5::Markup_declaration_open_state, domparser::html5::PLAINTEXT_state, domparser::html5::RAWTEXT_end_tag_name_state, domparser::html5::RAWTEXT_end_tag_open_state, domparser::html5::RAWTEXT_less_than_sign_state, domparser::html5::RAWTEXT_state, domparser::html5::RCDATA_end_tag_name_state, domparser::html5::RCDATA_end_tag_open_state, domparser::html5::RCDATA_less_than_sign_state, domparser::html5::RCDATA_state, domparser::html5::Script_data_double_escape_end_state, domparser::html5::Script_data_double_escape_start_state, domparser::html5::Script_data_double_escaped_dash_dash_state, domparser::html5::Script_data_double_escaped_dash_state, domparser::html5::Script_data_double_escaped_less_than_sign_state, domparser::html5::Script_data_double_escaped_state, domparser::html5::Script_data_end_tag_name_state, domparser::html5::Script_data_end_tag_open_state, domparser::html5::Script_data_escape_start_dash_state, domparser::html5::Script_data_escape_start_state, domparser::html5::Script_data_escaped_dash_dash_state, domparser::html5::Script_data_escaped_dash_state, domparser::html5::Script_data_escaped_end_tag_name_state, domparser::html5::Script_data_escaped_end_tag_open_state, domparser::html5::Script_data_escaped_less_than_sign_state, domparser::html5::Script_data_escaped_state, domparser::html5::Script_data_less_than_sign_state, domparser::html5::Script_data_state, domparser::html5::Self_closing_start_tag_state, domparser::html5::Tag_name_state, and domparser::html5::Tag_open_state.
Referenced by SwitchState().
bool domparser::html5::Tokeniser::Parse (const char * pData, const size_t & size, const bool logVerbose = false) [inherited]
parses html document from a string.
Parameters:
pData raw html buffer.
size size of html buffer.
logVerbose true to produce heavily verbose output.
Returns:
false on error, true on success.
Definition at line 1939 of file Tokeniser.cpp.
References domparser::html5::Data_state, domparser::html5::Tokeniser::db, domparser::html5::Tokeniser::end, domparser::html5::Tokeniser::InitLineVector(), domparser::html5::Tokeniser::logVerbose, domparser::html5::Tokeniser::next, domparser::html5::Tokeniser::ProcessState(), domparser::html5::Tokeniser::ResetAllTokens(), domparser::html5::Tokeniser::size, domparser::html5::Tokeniser::start, and domparser::html5::Tokeniser::SwitchState().
Referenced by domparser::DocumentFactory::FromHtmlData(), and toolbot::UnitTestHtmlDocumentFactory::Run().
uintptr_t domparser::html5::Tokeniser::MapToOriginalPosition (const uintptr_t & pos) const [inherited]
gets position in document (before comments etc.
where removed)
Parameters:
pos position in "cleaned" document
Returns:
original position
void domparser::html5::Tokeniser::GetCurLineCol (size_t & line, size_t & col) const [inherited]
Definition at line 2220 of file Tokeniser.cpp.
References domparser::html5::Tokeniser::lines, domparser::html5::Tokeniser::next, and domparser::html5::Tokeniser::start.
Referenced by domparser::html5::Tokeniser::GetLineColumnString().
void domparser::html5::Tokeniser::InitLineVector () [inherited]
initializes internal column/line tracking
Definition at line 2189 of file Tokeniser.cpp.
References domparser::html5::Tokeniser::end, domparser::html5::Tokeniser::lines, and domparser::html5::Tokeniser::start.
Referenced by domparser::html5::Tokeniser::Parse().
std::string domparser::html5::Tokeniser::GetLineColumnString () const [inherited]
gets preformated column and line string for current position
Returns:
preformated column and line string
Definition at line 2239 of file Tokeniser.cpp.
References domparser::html5::Tokeniser::GetCurLineCol().
Referenced by EmitCharacter(), EmitComment(), EmitDocType(), EmitTag(), toolbot::UnitTestHtmlDocumentFactory::OnToken(), ParseError(), domparser::DocumentFactory::ParseError(), toolbot::UnitTestHtmlDocumentFactory::SwitchMode(), and SwitchState().
Friends And Related Function Documentation
friend class domparser::DocumentFactory [friend, inherited]
Definition at line 38 of file Tokeniser.h.
friend class toolbot::UnitTestHtmlTokeniser [friend, inherited]
Definition at line 39 of file Tokeniser.h.
Member Data Documentation
TokeniserState domparser::html5::Tokeniser::state [protected, inherited]
Definition at line 172 of file Tokeniser.h.
Referenced by domparser::html5::Tokeniser::OnAttributeValueDoubleQuotedState(), domparser::html5::Tokeniser::OnAttributeValueSingleQuotedState(), domparser::html5::Tokeniser::OnAttributeValueUnquotedState(), domparser::html5::Tokeniser::ProcessState(), SwitchState(), and domparser::html5::Tokeniser::SwitchState().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestHtmlTokeniser.h
DeepNetTool/src/UnitTestHtmlTokeniser.cpp