DeepNet: database::WhereConditionTableColumn Class Reference
database::WhereConditionTableColumn Class Reference
wrapper for a column in a WhereCondition
#include <WhereConditionTableColumn.h>
Public Member Functions
virtual ~WhereConditionTableColumn ()
std::string ToString (DatabaseConnection *db) const
gets sql equivalent of this operator.
const WhereConditionOperator & WhereOp () const
gets where condition operator for this column.
const
WhereConditionCompositeOperator & WhereCompOp () const
gets where condition composite operator for this column.
const std::string & ColumnAlias () const
gets alias column name.
const std::string & TableAlias () const
gets alias table name.
Static Public Member Functions
static WhereConditionTableColumn * CreateInstance (const WhereConditionTableColumnCreateParam &createParam, TableColumn *pCol)
factory function creating a new where condition column from a TableColumn value.
static WhereConditionTableColumn * CreateInstance (const WhereConditionTableColumnCreateParam &createParam, const std::vector< TableColumn * > &cols)
factory function creating a multiple where condition column from multiple values.
Private Member Functions
WhereConditionTableColumn (const WhereConditionTableColumn &copy)
WhereConditionTableColumn (const WhereConditionTableColumnCreateParam &createParam)
Private Attributes
TableColumnArrayContainer columnValues
WhereConditionTableColumnCreateParam createParam
Detailed Description
wrapper for a column in a WhereCondition
See also:
database::WhereCondition
Definition at line 22 of file WhereConditionTableColumn.h.
Constructor & Destructor Documentation
database::WhereConditionTableColumn::WhereConditionTableColumn (const WhereConditionTableColumn & copy) [private]
Definition at line 29 of file WhereConditionTableColumn.cpp.
References THROW_EXCEPTION.
Referenced by CreateInstance().
database::WhereConditionTableColumn::WhereConditionTableColumn (const WhereConditionTableColumnCreateParam & createParam) [private]
Definition at line 25 of file WhereConditionTableColumn.cpp.
database::WhereConditionTableColumn::~WhereConditionTableColumn () [virtual]
Definition at line 35 of file WhereConditionTableColumn.cpp.
Member Function Documentation
std::string database::WhereConditionTableColumn::ToString (DatabaseConnection * db) const
gets sql equivalent of this operator.
Parameters:
db connection.
Returns:
sql string.
Definition at line 60 of file WhereConditionTableColumn.cpp.
References columnValues, database::WhereConditionTableColumnCreateParam::compOp, createParam, database::EQUALS, database::TableColumn::GetColumnName(), database::TableColumnContainer::GetConstColumn(), database::TableColumn::GetConstColumnDefinition(), tools::PointerContainer< T >::GetConstIter(), database::TableColumn::GetForSQL(), database::TableColumnDefinition::GetTableName(), database::WhereConditionCompositeOperator::GetType(), database::WhereConditionOperator::GetType(), database::INITIAL_COMPOSITE_OPERATOR_TYPE, tools::PointerContainer< T >::IsIterEnd(), database::TableColumn::IsNull(), database::LIKE, tools::PointerContainer< T >::Next(), database::NOT_EQUALS, database::WhereConditionTableColumnCreateParam::op, tools::PointerContainer< T >::ResetIter(), tools::PointerContainer< T >::Size(), database::WhereConditionTableColumnCreateParam::tableNameAlias, THROW_EXCEPTION, database::WhereConditionCompositeOperator::ToString(), and database::WhereConditionOperator::ToString().
WhereConditionTableColumn * database::WhereConditionTableColumn::CreateInstance (const WhereConditionTableColumnCreateParam & createParam, TableColumn * pCol) [static]
factory function creating a new where condition column from a TableColumn value.
Parameters:
createParam create parameters.
pCol column.
Returns:
Definition at line 38 of file WhereConditionTableColumn.cpp.
References tools::PointerContainer< T >::Add(), columnValues, and WhereConditionTableColumn().
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), database::cacheparsedTableBase::GetWhereColumnsFor_action_time(), database::cacherobotsTableBase::GetWhereColumnsFor_action_time(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_action_time(), database::cachehtmlTableBase::GetWhereColumnsFor_action_time(), database::cachesubdomainTableBase::GetWhereColumnsFor_action_time(), database::cacheurlTableBase::GetWhereColumnsFor_action_time(), database::logmessagesTableBase::GetWhereColumnsFor_actiontime(), database::logmessagesTableBase::GetWhereColumnsFor_appName(), database::documentcodeTableBase::GetWhereColumnsFor_code(), database::urlstagesTableBase::GetWhereColumnsFor_content_length(), database::urlstagesTableBase::GetWhereColumnsFor_content_md5(), database::urlstagesTableBase::GetWhereColumnsFor_content_type(), database::hyperlinksTableBase::GetWhereColumnsFor_count(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::customersessionsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::customerdomainsTableBase::GetWhereColumnsFor_CUSTOMER_ID(), database::customerqueriesTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetWhereColumnsFor_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetWhereColumnsFor_DICT_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_DICT_ID(), database::dockeyTableBase::GetWhereColumnsFor_DICT_ID(), database::docmetaTableBase::GetWhereColumnsFor_DICT_ID(), database::dockeyposTableBase::GetWhereColumnsFor_DOCKEY_ID(), database::secondleveldomainsTableBase::GetWhereColumnsFor_domain(), database::dataminingblacklistTableBase::GetWhereColumnsFor_domain(), database::customerdomainsTableBase::GetWhereColumnsFor_domain(), database::urlstagesTableBase::GetWhereColumnsFor_download_speed(), database::urlstagesTableBase::GetWhereColumnsFor_download_time(), database::urlstagesTableBase::GetWhereColumnsFor_ext_links(), database::imagesTableBase::GetWhereColumnsFor_found_date(), database::urlsTableBase::GetWhereColumnsFor_found_date(), database::urlstagesTableBase::GetWhereColumnsFor_found_date(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_groupPosition(), database::urlstagesTableBase::GetWhereColumnsFor_html_errors(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::keywordqueryTableBase::GetWhereColumnsFor_ID(), database::matchcriteriaTableBase::GetWhereColumnsFor_ID(), database::schemesTableBase::GetWhereColumnsFor_ID(), database::searchqueryTableBase::GetWhereColumnsFor_ID(), database::secondleveldomainsTableBase::GetWhereColumnsFor_ID(), database::subdomainsTableBase::GetWhereColumnsFor_ID(), database::topleveldomainsTableBase::GetWhereColumnsFor_ID(), database::customersTableBase::GetWhereColumnsFor_ID(), database::dataminingalertsTableBase::GetWhereColumnsFor_ID(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_ID(), database::dataminingcustomerTableBase::GetWhereColumnsFor_ID(), database::dictTableBase::GetWhereColumnsFor_ID(), database::customerqueriesTableBase::GetWhereColumnsFor_ID(), database::customersessionsTableBase::GetWhereColumnsFor_ID(), database::customersyncurlTableBase::GetWhereColumnsFor_ID(), database::dataminingblacklistTableBase::GetWhereColumnsFor_ID(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_ID(), database::customerproductimagesTableBase::GetWhereColumnsFor_ID(), database::documentcodeTableBase::GetWhereColumnsFor_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_ID(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_ID(), database::docurlTableBase::GetWhereColumnsFor_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_ID(), database::dockeyposTableBase::GetWhereColumnsFor_ID(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_ID(), database::customersynccrawlerTableBase::GetWhereColumnsFor_ID(), database::metainfoTableBase::GetWhereColumnsFor_ID(), database::hyperlinksTableBase::GetWhereColumnsFor_ID(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_ID(), database::dockeyTableBase::GetWhereColumnsFor_ID(), database::imagelinksTableBase::GetWhereColumnsFor_ID(), database::dataminingcriteriaalertsTableBase::GetWhereColumnsFor_ID(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_ID(), database::cacheurlTableBase::GetWhereColumnsFor_ID(), database::cachehtmlTableBase::GetWhereColumnsFor_ID(), database::cachesubdomainTableBase::GetWhereColumnsFor_ID(), database::cacherobotsTableBase::GetWhereColumnsFor_ID(), database::cacheparsedTableBase::GetWhereColumnsFor_ID(), database::customerdomainsTableBase::GetWhereColumnsFor_ID(), database::queryresultsTableBase::GetWhereColumnsFor_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_ID(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_ID(), database::customerproductsTableBase::GetWhereColumnsFor_ID(), database::syncurlsTableBase::GetWhereColumnsFor_ID(), database::docmetaTableBase::GetWhereColumnsFor_ID(), database::logmessagesTableBase::GetWhereColumnsFor_ID(), database::imagesTableBase::GetWhereColumnsFor_ID(), database::urlsTableBase::GetWhereColumnsFor_ID(), database::urlstagesTableBase::GetWhereColumnsFor_ID(), database::imagelinksTableBase::GetWhereColumnsFor_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetWhereColumnsFor_imageUrl(), database::urlstagesTableBase::GetWhereColumnsFor_int_links(), database::customerdomainsTableBase::GetWhereColumnsFor_isDomainRegex(), database::customerkeywordsTableBase::GetWhereColumnsFor_isKeywordRegex(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_isPrimaryKey(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_keyword(), database::dictTableBase::GetWhereColumnsFor_keyword(), database::customerkeywordsTableBase::GetWhereColumnsFor_keyword(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetWhereColumnsFor_last_change(), database::customersTableBase::GetWhereColumnsFor_login(), database::dataminingcustomerTableBase::GetWhereColumnsFor_login(), database::logmessagesTableBase::GetWhereColumnsFor_loglevel(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_MATCHCRITERIA_ID(), database::cachehtmlTableBase::GetWhereColumnsFor_matches(), database::cacheparsedTableBase::GetWhereColumnsFor_matches(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_matches(), database::cachesubdomainTableBase::GetWhereColumnsFor_matches(), database::cacherobotsTableBase::GetWhereColumnsFor_matches(), database::cacheurlTableBase::GetWhereColumnsFor_matches(), database::logmessagesTableBase::GetWhereColumnsFor_message(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_misses(), database::cacheparsedTableBase::GetWhereColumnsFor_misses(), database::cachesubdomainTableBase::GetWhereColumnsFor_misses(), database::cachehtmlTableBase::GetWhereColumnsFor_misses(), database::cacheurlTableBase::GetWhereColumnsFor_misses(), database::cacherobotsTableBase::GetWhereColumnsFor_misses(), database::dictTableBase::GetWhereColumnsFor_occurrence(), database::dockeyTableBase::GetWhereColumnsFor_occurrence(), database::docmetaTableBase::GetWhereColumnsFor_occurrence(), database::queryresultsTableBase::GetWhereColumnsFor_order_position(), database::dockeyposTableBase::GetWhereColumnsFor_paragraph(), database::dataminingalertsTableBase::GetWhereColumnsFor_param(), database::dataminingcustomerTableBase::GetWhereColumnsFor_password(), database::customersTableBase::GetWhereColumnsFor_password(), database::customerdomainblacklistTableBase::GetWhereColumnsFor_path(), database::imagesTableBase::GetWhereColumnsFor_path_part(), database::urlsTableBase::GetWhereColumnsFor_path_part(), database::logmessagesTableBase::GetWhereColumnsFor_pid(), database::imagesTableBase::GetWhereColumnsFor_port(), database::urlsTableBase::GetWhereColumnsFor_port(), database::dockeyposTableBase::GetWhereColumnsFor_position(), database::urlstagesTableBase::GetWhereColumnsFor_primary_ip(), database::urlstagesTableBase::GetWhereColumnsFor_primary_port(), database::customerproductimagesTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetWhereColumnsFor_PRODUCT_ID(), database::customerproductsTableBase::GetWhereColumnsFor_productBrand(), database::customerproductsTableBase::GetWhereColumnsFor_productName(), database::customerproductsTableBase::GetWhereColumnsFor_productNo(), database::customerqueriesTableBase::GetWhereColumnsFor_query(), database::keywordqueryTableBase::GetWhereColumnsFor_query_part(), database::urlstagesTableBase::GetWhereColumnsFor_redirect_count(), database::matchcriteriaTableBase::GetWhereColumnsFor_regex(), database::urlstagesTableBase::GetWhereColumnsFor_response_code(), database::customerdomainsTableBase::GetWhereColumnsFor_revisitInterval(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_schedule(), database::syncurlsTableBase::GetWhereColumnsFor_schedule(), database::customersyncurlTableBase::GetWhereColumnsFor_scheduled(), database::customersynccrawlerTableBase::GetWhereColumnsFor_scheduled(), database::schemesTableBase::GetWhereColumnsFor_scheme(), database::urlsTableBase::GetWhereColumnsFor_SCHEME_ID(), database::imagesTableBase::GetWhereColumnsFor_SCHEME_ID(), database::imagesTableBase::GetWhereColumnsFor_search_part(), database::urlsTableBase::GetWhereColumnsFor_search_part(), database::searchquerykeywordsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::queryresultsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetWhereColumnsFor_session(), database::customersessionsTableBase::GetWhereColumnsFor_session(), database::dataminingcustomersessionTableBase::GetWhereColumnsFor_session(), database::cacheparsedTableBase::GetWhereColumnsFor_size(), database::cachesecondleveldomainTableBase::GetWhereColumnsFor_size(), database::cachesubdomainTableBase::GetWhereColumnsFor_size(), database::cachehtmlTableBase::GetWhereColumnsFor_size(), database::cacheurlTableBase::GetWhereColumnsFor_size(), database::cacherobotsTableBase::GetWhereColumnsFor_size(), database::subdomainsTableBase::GetWhereColumnsFor_subdomain(), database::imagesTableBase::GetWhereColumnsFor_SUBDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetWhereColumnsFor_target(), database::hyperlinksTableBase::GetWhereColumnsFor_TARGET_URL_ID(), database::imagelinksTableBase::GetWhereColumnsFor_TARGET_URL_ID(), database::logmessagesTableBase::GetWhereColumnsFor_threadName(), database::logmessagesTableBase::GetWhereColumnsFor_tid(), database::topleveldomainsTableBase::GetWhereColumnsFor_tld(), database::imagesTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::urlsTableBase::GetWhereColumnsFor_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetWhereColumnsFor_type(), database::dataminingcriteriaTableBase::GetWhereColumnsFor_type(), database::metainfoTableBase::GetWhereColumnsFor_type(), database::customermatchcriteriaTableBase::GetWhereColumnsFor_type(), database::customermatchcriteriagrouptypeTableBase::GetWhereColumnsFor_type(), database::docmetaTableBase::GetWhereColumnsFor_type(), database::urlstagesTableBase::GetWhereColumnsFor_upload_speed(), database::customersyncurlTableBase::GetWhereColumnsFor_URL_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::docurlTableBase::GetWhereColumnsFor_URL_ID(), database::customerproducturlsTableBase::GetWhereColumnsFor_URL_ID(), database::syncurlsTableBase::GetWhereColumnsFor_URL_ID(), database::queryresultsTableBase::GetWhereColumnsFor_URL_ID(), database::urlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::imagesTableBase::GetWhereColumnsFor_url_md5(), database::urlsTableBase::GetWhereColumnsFor_url_md5(), database::documentcodeTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::latesturlstagesTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::metainfoTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::hyperlinksTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::dockeyTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::imagelinksTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::docmetaTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::queryresultsTableBase::GetWhereColumnsFor_URLSTAGE_ID(), and database::metainfoTableBase::GetWhereColumnsFor_value().
WhereConditionTableColumn * database::WhereConditionTableColumn::CreateInstance (const WhereConditionTableColumnCreateParam & createParam, const std::vector< TableColumn * > & cols) [static]
factory function creating a multiple where condition column from multiple values.
Parameters:
createParam create parameters.
cols column.
Returns:
Definition at line 47 of file WhereConditionTableColumn.cpp.
References tools::PointerContainer< T >::Add(), columnValues, and WhereConditionTableColumn().
const WhereConditionOperator& database::WhereConditionTableColumn::WhereOp () const [inline]
gets where condition operator for this column.
Returns:
where condition operator.
Definition at line 64 of file WhereConditionTableColumn.h.
References database::WhereConditionTableColumnCreateParam::op.
const WhereConditionCompositeOperator& database::WhereConditionTableColumn::WhereCompOp () const [inline]
gets where condition composite operator for this column.
Returns:
where condition composite operator.
Definition at line 70 of file WhereConditionTableColumn.h.
References database::WhereConditionTableColumnCreateParam::compOp.
const std::string& database::WhereConditionTableColumn::ColumnAlias () const [inline]
gets alias column name.
Returns:
alias column name.
Definition at line 76 of file WhereConditionTableColumn.h.
References database::WhereConditionTableColumnCreateParam::columnNameAlias.
const std::string& database::WhereConditionTableColumn::TableAlias (void) const [inline]
gets alias table name.
Returns:
alias table name.
Definition at line 82 of file WhereConditionTableColumn.h.
References database::WhereConditionTableColumnCreateParam::tableNameAlias.
Member Data Documentation
TableColumnArrayContainer database::WhereConditionTableColumn::columnValues [private]
Definition at line 85 of file WhereConditionTableColumn.h.
Referenced by CreateInstance(), and ToString().
WhereConditionTableColumnCreateParam database::WhereConditionTableColumn::createParam [private]
Definition at line 86 of file WhereConditionTableColumn.h.
Referenced by ToString().
The documentation for this class was generated from the following files:
Database/src/WhereConditionTableColumn.h
Database/src/WhereConditionTableColumn.cpp