DeepNet: indexing::IndexerEx Class Reference
indexing::IndexerEx Class Reference
simple implementation of an IIndexer interface
#include <IndexerEx.h>
Public Member Functions
virtual ~IndexerEx ()
virtual void Parse (const std::string &input, const long long paragraph)
parses a text
virtual void ParseMeta (const std::string &input, const Dictionary::MetaInformationType &type)
parses content part of a meta type
virtual Dictionary & GetDictionary ()
gets dictionary of this indexer
Private Member Functions
IndexerEx (database::DatabaseConnection *database)
Private Attributes
database::DatabaseConnection * db
GenericWebDictionary dictionary
Friends
class IIndexerFactory
Detailed Description
simple implementation of an IIndexer interface
Definition at line 25 of file IndexerEx.h.
Constructor & Destructor Documentation
indexing::IndexerEx::IndexerEx (database::DatabaseConnection * database) [private]
Definition at line 19 of file IndexerEx.cpp.
indexing::IndexerEx::~IndexerEx () [virtual]
Definition at line 24 of file IndexerEx.cpp.
Member Function Documentation
void indexing::IndexerEx::Parse (const std::string & input, const long long paragraph) [virtual]
parses a text
Parameters:
input text to parse
paragraph paragraph of this text
Implements indexing::IIndexer.
Definition at line 51 of file IndexerEx.cpp.
References indexing::Dictionary::AddContent(), dictionary, tools::CharsetEncoder::GetHostCharsetName(), log::Logging::IsLogLevelTrace(), log::Logging::LogTrace(), tools::PCRERegex::Match(), and tools::StringTools::ToLowerNP().
void indexing::IndexerEx::ParseMeta (const std::string & input, const Dictionary::MetaInformationType & type) [virtual]
parses content part of a meta type
Parameters:
input content part to parse
type meta type to set
Implements indexing::IIndexer.
Definition at line 27 of file IndexerEx.cpp.
References indexing::Dictionary::AddMeta(), dictionary, tools::CharsetEncoder::GetHostCharsetName(), log::Logging::IsLogLevelTrace(), log::Logging::LogTrace(), tools::PCRERegex::Match(), and tools::StringTools::ToLowerNP().
virtual Dictionary& indexing::IndexerEx::GetDictionary () [inline, virtual]
gets dictionary of this indexer
Returns:
instance of this indexers dictionary
Implements indexing::IIndexer.
Definition at line 37 of file IndexerEx.h.
References dictionary.
Friends And Related Function Documentation
friend class IIndexerFactory [friend]
Definition at line 27 of file IndexerEx.h.
Member Data Documentation
database::DatabaseConnection* indexing::IndexerEx::db [private]
Definition at line 40 of file IndexerEx.h.
GenericWebDictionary indexing::IndexerEx::dictionary [private]
Definition at line 41 of file IndexerEx.h.
Referenced by GetDictionary(), Parse(), and ParseMeta().
The documentation for this class was generated from the following files:
Indexer/src/IndexerEx.h
Indexer/src/IndexerEx.cpp