DeepNet: toolbot::UnitTestPCRERegex Class Reference
toolbot::UnitTestPCRERegex Class Reference
#include <UnitTestPCRERegex.h>
Public Member Functions
UnitTestPCRERegex (const std::string &unitTestFile)
virtual ~UnitTestPCRERegex ()
virtual bool Run ()
virtual std::string GetName () const
Private Member Functions
void ParseTestFile (const std::string &unitTestFile)
Static Private Member Functions
static void ParseExpectedGroups (const std::string &groupsTerm, PCRERegexUnitTestEntry &entry)
static void OnError (const std::string &formatMessage, const PCRERegexUnitTestEntry &entry, const std::vector< std::string > &groups)
Private Attributes
std::vector
< PCRERegexUnitTestEntry > testEntries
Detailed Description
Definition at line 36 of file UnitTestPCRERegex.h.
Constructor & Destructor Documentation
toolbot::UnitTestPCRERegex::UnitTestPCRERegex (const std::string & unitTestFile)
Definition at line 20 of file UnitTestPCRERegex.cpp.
References ParseTestFile().
toolbot::UnitTestPCRERegex::~UnitTestPCRERegex () [virtual]
Definition at line 25 of file UnitTestPCRERegex.cpp.
Member Function Documentation
bool toolbot::UnitTestPCRERegex::Run () [virtual]
Implements toolbot::UnitTest.
Definition at line 87 of file UnitTestPCRERegex.cpp.
References tools::ContainerTools::CompareVector(), tools::PCRERegex::Match(), OnError(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, and testEntries.
virtual std::string toolbot::UnitTestPCRERegex::GetName () const [inline, virtual]
Implements toolbot::UnitTest.
Definition at line 43 of file UnitTestPCRERegex.h.
void toolbot::UnitTestPCRERegex::ParseTestFile (const std::string & unitTestFile) [private]
Definition at line 28 of file UnitTestPCRERegex.cpp.
References toolbot::PCRERegexUnitTestEntry::caseInsensitive, toolbot::PCRERegexUnitTestEntry::expectedGroups, toolbot::PCRERegexUnitTestEntry::line, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::PCRERegex::Match(), toolbot::PCRERegexUnitTestEntry::multiline, ParseExpectedGroups(), tools::FileTools::ReadFile(), toolbot::PCRERegexUnitTestEntry::regex, toolbot::PCRERegexUnitTestEntry::target, testEntries, and toolbot::PCRERegexUnitTestEntry::utf8Mode.
Referenced by UnitTestPCRERegex().
void toolbot::UnitTestPCRERegex::ParseExpectedGroups (const std::string & groupsTerm, PCRERegexUnitTestEntry & entry) [static, private]
Definition at line 66 of file UnitTestPCRERegex.cpp.
References toolbot::PCRERegexUnitTestEntry::expectedGroups, toolbot::PCRERegexUnitTestEntry::line, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::PCRERegex::Match(), and tools::StringTools::SplitBy().
Referenced by ParseTestFile().
void toolbot::UnitTestPCRERegex::OnError (const std::string & formatMessage, const PCRERegexUnitTestEntry & entry, const std::vector< std::string > & groups) [static, private]
Definition at line 119 of file UnitTestPCRERegex.cpp.
References tools::ContainerTools::DumpVector(), toolbot::PCRERegexUnitTestEntry::expectedGroups, toolbot::PCRERegexUnitTestEntry::line, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, toolbot::PCRERegexUnitTestEntry::regex, and toolbot::PCRERegexUnitTestEntry::target.
Referenced by Run().
Member Data Documentation
std::vector<PCRERegexUnitTestEntry> toolbot::UnitTestPCRERegex::testEntries [private]
Definition at line 53 of file UnitTestPCRERegex.h.
Referenced by ParseTestFile(), and Run().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestPCRERegex.h
DeepNetTool/src/UnitTestPCRERegex.cpp