DeepNet: crawler::UrlFetcherThread Class Reference
crawler::UrlFetcherThread Class Reference
generic url fetcher thread implementation.
#include <UrlFetcherThread.h>
Public Member Functions
UrlFetcherThread ()
virtual ~UrlFetcherThread ()
long long GetOldCrawlerSessionID () const
gets old crawler session id after this thread ended
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
database::DatabaseHelper & DB ()
gets the database.
bool FetchUrls (std::map< long long, htmlparser::DatabaseUrl > &urls)
fetches urls from cache/database and reserves them for crawling.
bool FetchHtmlCode (const std::map< long long, htmlparser::DatabaseUrl > &urls, std::vector< UrlFetchParam > &fetchParameters)
fetches html from given urls.
bool CommitPages (const std::vector< UrlFetchParam > &fetchParameters)
saves crawled urls and results to database.
void OnIdle ()
called when no urls are available.
virtual bool GetNextSecondLevelDomain ()=0
called when secondleveldomain id should be changed if possible.
virtual bool ReserveNextUrls (std::vector< long long > &urlIDs)=0
called when more url-ids are needed and should be reserved
virtual void OnExit ()
called when fetcher thread is going to exit.
bool GetNextCrawlerSessionID ()
called when a new crawlersession-id is needed.
bool GetUrlsFromDatabase (const std::vector< long long > &urlIDs, std::map< long long, htmlparser::DatabaseUrl > &urls)
called when url-ids are needed from database.
void RemoveCrawlerSessionID ()
removes active crawlersession-id from database.
void RemoveCrawlerReservation ()
removes pending reservations for url-ids from database.
bool GetHtmlCodeFromUrl (const long long urlID, const htmlparser::DatabaseUrl &url, network::HtmlData &htmlCode, long &httpCode, long long &urlStageID)
helper function for crawler:.UrlFetcherThread::FetchHtmlCode.
void SetThreadFunction (ThreadFunction pFunction)
Protected Attributes
long long crawlerSessionID
current crawlersession-id.
UrlFetcherThreadParam * fetcherThreadParam
parameters attached to this url fetcher thread.
Static Private Member Functions
static void * UrlFetcherThreadFunction (Thread::THREAD_PARAM *threadParam)
Private Attributes
database::DatabaseHelper databaseHelper
long long oldCrawlerSessionID
Detailed Description
generic url fetcher thread implementation.
Definition at line 35 of file UrlFetcherThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
crawler::UrlFetcherThread::UrlFetcherThread ()
Definition at line 45 of file UrlFetcherThread.cpp.
crawler::UrlFetcherThread::~UrlFetcherThread () [virtual]
Definition at line 52 of file UrlFetcherThread.cpp.
Member Function Documentation
long long crawler::UrlFetcherThread::GetOldCrawlerSessionID () const
gets old crawler session id after this thread ended
Definition at line 442 of file UrlFetcherThread.cpp.
References oldCrawlerSessionID.
void * crawler::UrlFetcherThread::UrlFetcherThreadFunction (Thread::THREAD_PARAM * threadParam) [static, private]
Definition at line 56 of file UrlFetcherThread.cpp.
References CommitPages(), crawlerSessionID, database::DatabaseHelper::CreateConnection(), crawler::CrawlerParam::databaseConfig, DB(), database::DatabaseHelper::DestroyConnection(), fetcherThreadParam, FetchHtmlCode(), FetchUrls(), GetNextCrawlerSessionID(), threading::Thread::THREAD_PARAM::instance, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, crawler::CrawlerParam::minAge, OnExit(), PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, threading::Thread::THREAD_PARAM::pParam, log::Logging::RegisterThreadID(), RemoveCrawlerReservation(), RemoveCrawlerSessionID(), and threading::Thread::ShallEnd().
database::DatabaseHelper& crawler::UrlFetcherThread::DB () [inline, protected]
gets the database.
Returns:
database helper.
Definition at line 55 of file UrlFetcherThread.h.
References databaseHelper.
Referenced by FetchHtmlCode(), GetHtmlCodeFromUrl(), GetNextCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), GetUrlsFromDatabase(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), RemoveCrawlerReservation(), RemoveCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::CommerceSearchFetcherThread::ReserveNextUrls(), and UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::FetchUrls (std::map< long long, htmlparser::DatabaseUrl > & urls) [protected]
fetches urls from cache/database and reserves them for crawling.
Parameters:
urls gets filled with url-ids and urls.
Returns:
false on error, true on success.
Definition at line 107 of file UrlFetcherThread.cpp.
References GetUrlsFromDatabase(), and ReserveNextUrls().
Referenced by UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::FetchHtmlCode (const std::map< long long, htmlparser::DatabaseUrl > & urls, std::vector< UrlFetchParam > & fetchParameters) [protected]
fetches html from given urls.
Parameters:
urls map of url-ids and urls to be crawler.
fetchParameters gets filled with info from crawled pages
Returns:
false on error, true on success.
Definition at line 120 of file UrlFetcherThread.cpp.
References DB(), fetcherThreadParam, GetHtmlCodeFromUrl(), crawler::UrlFetchParam::html, caching::CacheRobotsTxt::IsUrlAllowed(), crawler::CrawlerParam::respectRobotsTxt, crawler::UrlFetchParam::responseCode, crawler::UrlFetchParam::url, crawler::UrlFetchParam::urlID, crawler::UrlFetchParam::urlStageID, and crawler::CrawlerParam::userAgent.
Referenced by UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::CommitPages (const std::vector< UrlFetchParam > & fetchParameters) [protected]
saves crawled urls and results to database.
Parameters:
fetchParameters
Returns:
false on error, true on success.
Definition at line 141 of file UrlFetcherThread.cpp.
References caching::CacheHtml::Add(), log::Logging::IsLogLevelTrace(), log::Logging::Log(), and log::Logging::LOGLEVEL_TRACE.
Referenced by UrlFetcherThreadFunction().
void crawler::UrlFetcherThread::OnIdle () [protected]
called when no urls are available.
Definition at line 234 of file UrlFetcherThread.cpp.
References fetcherThreadParam, threading::Thread::ShallEnd(), and crawler::CrawlerParam::waitOnIdle.
Referenced by crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and crawler::CommerceSearchFetcherThread::ReserveNextUrls().
virtual bool crawler::UrlFetcherThread::GetNextSecondLevelDomain () [protected, pure virtual]
called when secondleveldomain id should be changed if possible.
Returns:
false on error, true on success.
Implemented in crawler::CommerceSearchFetcherThread, and crawler::GenericWebUrlFetcherThread.
virtual bool crawler::UrlFetcherThread::ReserveNextUrls (std::vector< long long > & urlIDs) [protected, pure virtual]
called when more url-ids are needed and should be reserved
Parameters:
urlIDs gets filled with reserved url ids.
Returns:
false on error, true on success.
Implemented in crawler::CommerceSearchFetcherThread, and crawler::GenericWebUrlFetcherThread.
Referenced by FetchUrls().
virtual void crawler::UrlFetcherThread::OnExit () [inline, protected, virtual]
called when fetcher thread is going to exit.
Reimplemented in crawler::GenericWebUrlFetcherThread.
Definition at line 103 of file UrlFetcherThread.h.
Referenced by UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::GetNextCrawlerSessionID () [protected]
called when a new crawlersession-id is needed.
result is written to UrlFetcherThread::crawlerSessionID.
Returns:
false on error, true on success.
Definition at line 164 of file UrlFetcherThread.cpp.
References crawlerSessionID, DB(), database::TableBase::Insert(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, oldCrawlerSessionID, PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::GetUrlsFromDatabase (const std::vector< long long > & urlIDs, std::map< long long, htmlparser::DatabaseUrl > & urls) [protected]
called when url-ids are needed from database.
Parameters:
urlIDs url-ids to look for.
urls gets filled with url-ids and urls.
Returns:
false on error, true on success.
Definition at line 180 of file UrlFetcherThread.cpp.
References DB(), caching::CacheDatabaseUrl::GetByUrlID(), PERFORMANCE_LOG_START, and PERFORMANCE_LOG_STOP.
Referenced by FetchUrls().
void crawler::UrlFetcherThread::RemoveCrawlerSessionID () [protected]
removes active crawlersession-id from database.
Definition at line 210 of file UrlFetcherThread.cpp.
References database::WhereCondition::AddColumns(), database::DatabaseHelper::Connection(), crawlerSessionID, database::crawlersessionsTableBase::CreateTableDefinition(), DB(), database::DatabaseConnection::Delete(), database::WhereCondition::Equals(), database::crawlersessionsTableBase::GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, and database::DeleteStatement::Where().
Referenced by UrlFetcherThreadFunction().
void crawler::UrlFetcherThread::RemoveCrawlerReservation () [protected]
removes pending reservations for url-ids from database.
Definition at line 188 of file UrlFetcherThread.cpp.
References crawlerSessionID, DB(), database::WhereCondition::Equals(), database::syncurlsTableBase::GetWhereColumnsFor_CRAWLERSESSION_ID(), database::WhereCondition::InitialComp(), database::TableBaseUpdateParam::limit, tools::TimeTools::NowUTC(), PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_schedule(), database::TableBase::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by UrlFetcherThreadFunction().
bool crawler::UrlFetcherThread::GetHtmlCodeFromUrl (const long long urlID, const htmlparser::DatabaseUrl & url, network::HtmlData & htmlCode, long & httpCode, long long & urlStageID) [protected]
helper function for crawler:.UrlFetcherThread::FetchHtmlCode.
Parameters:
urlID url-id
url parsed url.
htmlCode gets filled with html code.
httpCode returned http status code.
urlStageID urlstage-id.
Returns:
false on error, true on success.
Definition at line 240 of file UrlFetcherThread.cpp.
References crawler::CrawlerParam::clientType, database::DatabaseHelper::Connection(), crawler::CrawlerParam::connectionTimeout, crawler::CrawlerParam::connectTimeout, network::HttpResponse::contentLength, network::HttpClientFactory::CreateInstance(), DB(), network::HttpResponse::downloadSpeed, fetcherThreadParam, network::HtmlData::GetBuffer(), network::HtmlData::GetContentType(), network::HttpUrl::GetFullUrl(), tools::HashTools::GetMD5(), network::HttpResponse::html, network::HttpResponse::httpResponseCode, tools::TimeTools::InitTm(), database::TableBase::Insert(), database::TableBase::InsertOrUpdate(), log::Logging::IsLogLevelTrace(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_TRACE, tools::TimeTools::NowUTC(), PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, network::HttpResponse::primaryIP, network::HttpResponse::primaryPort, network::HttpResponse::redirectUrls, tools::MemoryContainer< T >::Release(), database::documentcodeTableBase::Set_code(), database::urlstagesTableBase::Set_content_length(), database::urlstagesTableBase::Set_content_md5(), database::urlstagesTableBase::Set_content_type(), database::urlstagesTableBase::Set_download_speed(), database::urlstagesTableBase::Set_download_time(), database::urlstagesTableBase::Set_found_date(), database::urlstagesTableBase::Set_last_change(), database::urlstagesTableBase::Set_primary_ip(), database::urlstagesTableBase::Set_primary_port(), database::urlstagesTableBase::Set_redirect_count(), database::urlstagesTableBase::Set_response_code(), database::urlstagesTableBase::Set_upload_speed(), database::latesturlstagesTableBase::Set_URL_ID(), database::urlstagesTableBase::Set_URL_ID(), database::documentcodeTableBase::Set_URLSTAGE_ID(), database::latesturlstagesTableBase::Set_URLSTAGE_ID(), crawler::CrawlerParam::speedLimitKB, tools::MemoryContainer< T >::Swap(), network::HttpResponse::totalTime, network::HttpResponse::uploadSpeed, crawler::CrawlerParam::useIPv6, network::HttpClientSettings::userAgent, and crawler::CrawlerParam::userAgent.
Referenced by FetchHtmlCode().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), OnIdle(), tools::TokenBucket::RefillThreadFunc(), and UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
long long crawler::UrlFetcherThread::crawlerSessionID [protected]
current crawlersession-id.
Definition at line 145 of file UrlFetcherThread.h.
Referenced by GetNextCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::GetNextSecondLevelDomain(), crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), RemoveCrawlerReservation(), RemoveCrawlerSessionID(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and UrlFetcherThreadFunction().
UrlFetcherThreadParam* crawler::UrlFetcherThread::fetcherThreadParam [protected]
parameters attached to this url fetcher thread.
Definition at line 150 of file UrlFetcherThread.h.
Referenced by FetchHtmlCode(), GetHtmlCodeFromUrl(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), OnIdle(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), crawler::CommerceSearchFetcherThread::ReserveNextUrls(), and UrlFetcherThreadFunction().
database::DatabaseHelper crawler::UrlFetcherThread::databaseHelper [private]
Definition at line 153 of file UrlFetcherThread.h.
Referenced by DB().
long long crawler::UrlFetcherThread::oldCrawlerSessionID [private]
Definition at line 154 of file UrlFetcherThread.h.
Referenced by GetNextCrawlerSessionID(), and GetOldCrawlerSessionID().
The documentation for this class was generated from the following files:
Crawler/src/UrlFetcherThread.h
Crawler/src/UrlFetcherThread.cpp