DeepNet: inspectorserver::InspectorServerThread Class Reference
inspectorserver::InspectorServerThread Class Reference
#include <InspectorServerThread.h>
Public Member Functions
InspectorServerThread (database::DatabaseConfig *databaseConfig, threading::Mutex *acceptMutex, const int port, const int backlog=0)
InspectorServerThread (database::DatabaseConfig *databaseConfig, threading::Mutex *acceptMutex, const std::string &filename, const int backlog=0)
virtual ~InspectorServerThread ()
database::DatabaseHelper & DB ()
tools::SpellChecking & SpellChecker ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
virtual
fastcgiserver::FastCGIRequest * CreateRequest ()
virtual
fastcgiserver::FastCGIResponse * CreateResponse (database::DatabaseHelper &dbHelper, fastcgiserver::FastCGIRequest *request)
Detailed Description
Definition at line 16 of file InspectorServerThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
inspectorserver::InspectorServerThread::InspectorServerThread (database::DatabaseConfig * databaseConfig, threading::Mutex * acceptMutex, const int port, const int backlog = 0)
Definition at line 12 of file InspectorServerThread.cpp.
inspectorserver::InspectorServerThread::InspectorServerThread (database::DatabaseConfig * databaseConfig, threading::Mutex * acceptMutex, const std::string & filename, const int backlog = 0)
Definition at line 17 of file InspectorServerThread.cpp.
inspectorserver::InspectorServerThread::~InspectorServerThread () [virtual]
Definition at line 22 of file InspectorServerThread.cpp.
Member Function Documentation
virtual fastcgiserver::FastCGIRequest* inspectorserver::InspectorServerThread::CreateRequest () [inline, private, virtual]
Implements fastcgiserver::FastCGIServerThread.
Definition at line 23 of file InspectorServerThread.h.
virtual fastcgiserver::FastCGIResponse* inspectorserver::InspectorServerThread::CreateResponse (database::DatabaseHelper & dbHelper, fastcgiserver::FastCGIRequest * request) [inline, private, virtual]
Implements fastcgiserver::FastCGIServerThread.
Definition at line 24 of file InspectorServerThread.h.
database::DatabaseHelper& fastcgiserver::FastCGIServerThread::DB () [inline, inherited]
Definition at line 30 of file FastCGIServerThread.h.
References fastcgiserver::FastCGIServerThread::dbHelper.
Referenced by fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc().
tools::SpellChecking& fastcgiserver::FastCGIServerThread::SpellChecker () [inline, inherited]
Definition at line 31 of file FastCGIServerThread.h.
References fastcgiserver::FastCGIServerThread::spellChecker.
Referenced by suggestserver::SuggestServerResponse::Process(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
The documentation for this class was generated from the following files:
InspectorServer/src/InspectorServerThread.h
InspectorServer/src/InspectorServerThread.cpp