DeepNet: database::TableDefinition Class Reference
database::TableDefinition Class Reference
class containing definition of a Tablebase.
#include <TableDefinition.h>
Public Member Functions
virtual ~TableDefinition ()
const std::string & DatabaseName () const
gets database name.
const std::string & TableName () const
gets table name.
const std::vector
< TableColumnDefinition * > & GetConstColumnDefinitions () const
gets const column definitions of this table.
std::vector
< TableColumnDefinition * > & GetColumnDefinitions ()
gets column definitions of this table.
const TableDefinitionCreateParam & GetConstCreateParam () const
gets const create parameters of this table.
TableDefinitionCreateParam & GetCreateParam ()
gets create parameters of this table.
std::string GetFullQualifiedTableName (void) const
gets fully qualified table name.
const TableColumnDefinition * GetPrimaryKeyColumnDefinition () const
gets column definition of this table's primary key.
const TableColumnDefinition * GetConstColumnDefinitionByName (const std::string &columnName) const
gets column definition by name.
Static Public Member Functions
static TableDefinition * CreateInstance (const TableDefinitionCreateParam &param)
factory function for a table definition.
Private Member Functions
TableDefinition (const TableDefinition &copy)
TableDefinition (const TableDefinitionCreateParam &param)
Private Attributes
TableDefinitionCreateParam definition
Detailed Description
class containing definition of a Tablebase.
definition used in Tablebase class.
Definition at line 20 of file TableDefinition.h.
Constructor & Destructor Documentation
database::TableDefinition::TableDefinition (const TableDefinition & copy) [private]
Definition at line 21 of file TableDefinition.cpp.
References THROW_EXCEPTION.
Referenced by CreateInstance().
database::TableDefinition::TableDefinition (const TableDefinitionCreateParam & param) [private]
Definition at line 17 of file TableDefinition.cpp.
database::TableDefinition::~TableDefinition () [virtual]
Definition at line 27 of file TableDefinition.cpp.
Member Function Documentation
TableDefinition * database::TableDefinition::CreateInstance (const TableDefinitionCreateParam & param) [static]
factory function for a table definition.
Parameters:
param create parameters.
Returns:
table definition.
Definition at line 30 of file TableDefinition.cpp.
References TableDefinition().
Referenced by database::MySQLTableBase::CreateInstance(), and database::TableBase::CreateInstance().
const std::string& database::TableDefinition::DatabaseName (void) const [inline]
gets database name.
Returns:
database name.
Definition at line 42 of file TableDefinition.h.
References database::TableDefinitionCreateParam::databaseName, and definition.
Referenced by database::Statement::DatabaseName(), GetFullQualifiedTableName(), and database::InnerJoinEntry::ToString().
const std::string& database::TableDefinition::TableName (void) const [inline]
gets table name.
Returns:
table name.
Definition at line 48 of file TableDefinition.h.
References definition, and database::TableDefinitionCreateParam::tableName.
Referenced by GetFullQualifiedTableName(), database::Statement::TableName(), and database::InnerJoinEntry::ToString().
const std::vector< TableColumnDefinition* >& database::TableDefinition::GetConstColumnDefinitions () const [inline]
gets const column definitions of this table.
Returns:
column definitions.
Definition at line 54 of file TableDefinition.h.
References database::TableDefinitionCreateParam::columnDefinitions, and definition.
Referenced by GetConstColumnDefinitionByName(), GetPrimaryKeyColumnDefinition(), database::SelectStatement::SelectAllColumns(), and database::MySQLInsertOrUpdateStatement::ToSQL().
std::vector<TableColumnDefinition*>& database::TableDefinition::GetColumnDefinitions () [inline]
gets column definitions of this table.
Returns:
column definitions.
Definition at line 60 of file TableDefinition.h.
References database::TableDefinitionCreateParam::columnDefinitions, and definition.
Referenced by database::TableBase::CreateColumns().
const TableDefinitionCreateParam& database::TableDefinition::GetConstCreateParam () const [inline]
gets const create parameters of this table.
Returns:
create parameters.
Definition at line 66 of file TableDefinition.h.
References definition.
TableDefinitionCreateParam& database::TableDefinition::GetCreateParam () [inline]
gets create parameters of this table.
Returns:
create parameters.
Definition at line 72 of file TableDefinition.h.
References definition.
std::string database::TableDefinition::GetFullQualifiedTableName (void) const
gets fully qualified table name.
Returns:
fully qualified table name.
Definition at line 35 of file TableDefinition.cpp.
References DatabaseName(), and TableName().
Referenced by database::Statement::GetFullQualifiedTableName().
const TableColumnDefinition * database::TableDefinition::GetPrimaryKeyColumnDefinition () const
gets column definition of this table's primary key.
Returns:
column definition of this table's primary key.
Definition at line 39 of file TableDefinition.cpp.
References GetConstColumnDefinitions(), and THROW_EXCEPTION.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL().
const TableColumnDefinition * database::TableDefinition::GetConstColumnDefinitionByName (const std::string & columnName) const
gets column definition by name.
Returns:
column definition.
Definition at line 52 of file TableDefinition.cpp.
References GetConstColumnDefinitions(), and THROW_EXCEPTION.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID().
Member Data Documentation
TableDefinitionCreateParam database::TableDefinition::definition [private]
Definition at line 93 of file TableDefinition.h.
Referenced by DatabaseName(), GetColumnDefinitions(), GetConstColumnDefinitions(), GetConstCreateParam(), GetCreateParam(), and TableName().
The documentation for this class was generated from the following files:
Database/src/TableDefinition.h
Database/src/TableDefinition.cpp