DeepNet: parser::GenericWebHtmlParserThread Class Reference
parser::GenericWebHtmlParserThread Class Reference
#include <GenericWebHtmlParserThread.h>
Public Member Functions
GenericWebHtmlParserThread ()
virtual ~GenericWebHtmlParserThread ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
database::DatabaseHelper & DB ()
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
virtual bool ParsePage (const HtmlParserEntry &entry, tools::Pointer< htmlparser::IHtmlParserResult > &result)
virtual void OnAfterParsePage (const HtmlParserEntry &entry, tools::Pointer< htmlparser::IHtmlParserResult > &result, const std::vector< std::string > &content, const std::vector< htmlparser::DatabaseUrl > &hyperlinks, const std::vector< network::HttpUrl > &images)
Static Private Member Functions
static void InsertImages (database::DatabaseConnection *db, const HtmlParserEntry &entry, const std::vector< network::HttpUrl > &images, tools::Pointer< htmlparser::IHtmlParserResult > &result)
static void InsertLinks (database::DatabaseConnection *db, const HtmlParserEntry &entry, const std::vector< network::HttpUrl > &hyperlinks, std::vector< htmlparser::DatabaseUrl > &dbLinks)
static void InsertMeta (database::DatabaseConnection *db, const HtmlParserEntry &entry, const std::vector< std::pair< std::string, std::string > > &meta)
static void UpdateUrlstageInfos (database::DatabaseConnection *db, const long long internLinks, const long long externLinks, const long long baseURLID)
Detailed Description
Definition at line 31 of file GenericWebHtmlParserThread.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
parser::GenericWebHtmlParserThread::GenericWebHtmlParserThread ()
Definition at line 34 of file GenericWebHtmlParserThread.cpp.
parser::GenericWebHtmlParserThread::~GenericWebHtmlParserThread () [virtual]
Definition at line 37 of file GenericWebHtmlParserThread.cpp.
Member Function Documentation
void parser::GenericWebHtmlParserThread::InsertImages (database::DatabaseConnection * db, const HtmlParserEntry & entry, const std::vector< network::HttpUrl > & images, tools::Pointer< htmlparser::IHtmlParserResult > & result) [static, private]
Definition at line 86 of file GenericWebHtmlParserThread.cpp.
References tools::Pointer< T >::Get(), database::TableBase::GetColumnByName(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), htmlparser::TLD::GetTLDIDByTLD(), htmlparser::DatabaseUrl::GetUrlID(), database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), log::Logging::LogInfo(), tools::TimeTools::NowUTC(), database::imagesTableBase::Set_found_date(), database::imagelinksTableBase::Set_IMAGE_URL_ID(), database::imagesTableBase::Set_path_part(), database::imagesTableBase::Set_port(), database::imagesTableBase::Set_SCHEME_ID(), database::imagesTableBase::Set_search_part(), database::imagesTableBase::Set_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Set_SUBDOMAIN_ID(), database::imagelinksTableBase::Set_TARGET_URL_ID(), database::imagesTableBase::Set_TOPLEVELDOMAIN_ID(), database::imagesTableBase::Set_url_md5(), database::imagelinksTableBase::Set_URLSTAGE_ID(), database::TableColumn::SetNull(), htmlparser::IHtmlParserResult::url, and parser::HtmlParserEntry::urlStageID.
Referenced by ParsePage().
void parser::GenericWebHtmlParserThread::InsertLinks (database::DatabaseConnection * db, const HtmlParserEntry & entry, const std::vector< network::HttpUrl > & hyperlinks, std::vector< htmlparser::DatabaseUrl > & dbLinks) [static, private]
Definition at line 158 of file GenericWebHtmlParserThread.cpp.
References tools::Pointer< T >::Get(), caching::CacheDatabaseUrl::GetByUrl(), database::hyperlinksTableBase::GetDefinition_count(), htmlparser::DatabaseUrl::GetSecondLevelID(), htmlparser::DatabaseUrl::GetUrlID(), database::TableBase::InsertOrUpdate(), log::Logging::IsLogLevelTrace(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_TRACE, database::hyperlinksTableBase::Set_count(), database::hyperlinksTableBase::Set_TARGET_URL_ID(), database::hyperlinksTableBase::Set_URLSTAGE_ID(), UpdateUrlstageInfos(), parser::HtmlParserEntry::url, parser::HtmlParserEntry::urlID, and parser::HtmlParserEntry::urlStageID.
Referenced by ParsePage().
void parser::GenericWebHtmlParserThread::InsertMeta (database::DatabaseConnection * db, const HtmlParserEntry & entry, const std::vector< std::pair< std::string, std::string > > & meta) [static, private]
Definition at line 220 of file GenericWebHtmlParserThread.cpp.
References database::TableBase::Insert(), database::metainfoTableBase::Set_type(), database::metainfoTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_value(), and parser::HtmlParserEntry::urlStageID.
Referenced by ParsePage().
void parser::GenericWebHtmlParserThread::UpdateUrlstageInfos (database::DatabaseConnection * db, const long long internLinks, const long long externLinks, const long long baseURLID) [static, private]
Definition at line 242 of file GenericWebHtmlParserThread.cpp.
References database::AND, database::EQUALS, database::urlstagesTableBase::GetWhereColumnsFor_URL_ID(), database::TableBaseUpdateParam::limit, database::TableBaseUpdateParam::onlyDirtyColumns, database::urlstagesTableBase::Set_ext_links(), database::urlstagesTableBase::Set_int_links(), database::TableBase::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by InsertLinks().
bool parser::GenericWebHtmlParserThread::ParsePage (const HtmlParserEntry & entry, tools::Pointer< htmlparser::IHtmlParserResult > & result) [private, virtual]
Implements parser::HtmlParserThread.
Definition at line 40 of file GenericWebHtmlParserThread.cpp.
References caching::CacheParsed::Add(), htmlparser::IHtmlParserResult::content, parser::HtmlParserThread::DB(), tools::Pointer< T >::Get(), htmlparser::IHtmlParserResult::hyperlinks, htmlparser::IHtmlParserResult::images, InsertImages(), InsertLinks(), InsertMeta(), tools::ContainerTools::MakeUniqueVector(), htmlparser::IHtmlParserResult::meta, OnAfterParsePage(), PERFORMANCE_LOG_RESTART, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, parser::HtmlParserEntry::url, parser::HtmlParserEntry::urlID, parser::HtmlParserEntry::urlStageID, and tools::ContainerTools::VectorPair2ToVector().
virtual void parser::GenericWebHtmlParserThread::OnAfterParsePage (const HtmlParserEntry & entry, tools::Pointer< htmlparser::IHtmlParserResult > & result, const std::vector< std::string > & content, const std::vector< htmlparser::DatabaseUrl > & hyperlinks, const std::vector< network::HttpUrl > & images) [inline, private, virtual]
Reimplemented in parser::CommerceSearchParserThread.
Definition at line 65 of file GenericWebHtmlParserThread.h.
Referenced by ParsePage().
database::DatabaseHelper& parser::HtmlParserThread::DB () [inline, protected, inherited]
Definition at line 35 of file HtmlParserThread.h.
References parser::HtmlParserThread::databaseHelper.
Referenced by parser::HtmlParserThread::HtmlParserThreadFunction(), parser::CommerceSearchParserThread::InitParserThread(), parser::CommerceSearchParserThread::MatchMetaCriteria(), parser::CommerceSearchParserThread::MatchUrlCriteria(), and ParsePage().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), indexing::Indexer::StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), indexing::Indexer::IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
The documentation for this class was generated from the following files:
Parser/src/GenericWebHtmlParserThread.h
Parser/src/GenericWebHtmlParserThread.cpp