DeepNet: bot::ConfigFile Class Reference
bot::ConfigFile Class Reference
class for config file processing.
#include <ConfigFile.h>
Public Member Functions
ConfigFile ()
virtual ~ConfigFile ()
bool ParseConfigFile (const std::string &fileName, std::vector< ConfigEntry > &registeredParams)
sets the filename of the config file and tries to process it.
Private Member Functions
bool ParseFile (std::vector< std::string > &fileContent, std::vector< ConfigEntry > &registeredParams)
Private Attributes
std::string fileName
Detailed Description
class for config file processing.
processes config files in the form of key=value. also accepts commentaries in config files using #'s.
Definition at line 21 of file ConfigFile.h.
Constructor & Destructor Documentation
bot::ConfigFile::ConfigFile ()
Definition at line 20 of file ConfigFile.cpp.
bot::ConfigFile::~ConfigFile () [virtual]
Definition at line 23 of file ConfigFile.cpp.
Member Function Documentation
bool bot::ConfigFile::ParseConfigFile (const std::string & fileName, std::vector< ConfigEntry > & registeredParams)
sets the filename of the config file and tries to process it.
Parameters:
fileName filename of the config file
registeredParams list of allowed parameters, will get filled if paramaters are found.
Returns:
false on error, true on success.
Definition at line 26 of file ConfigFile.cpp.
References fileName, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, ParseFile(), tools::FileTools::ReadFile(), and tools::StringTools::RemoveComments().
Referenced by bot::ConfigManager::ProcessConfigFile().
bool bot::ConfigFile::ParseFile (std::vector< std::string > & fileContent, std::vector< ConfigEntry > & registeredParams) [private]
Definition at line 44 of file ConfigFile.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, and log::Logging::LOGLEVEL_WARN.
Referenced by ParseConfigFile().
Member Data Documentation
std::string bot::ConfigFile::fileName [private]
Definition at line 39 of file ConfigFile.h.
Referenced by ParseConfigFile().
The documentation for this class was generated from the following files:
Bot/src/ConfigFile.h
Bot/src/ConfigFile.cpp