DeepNet: htmlparser::HtmlParserFactory Class Reference
htmlparser::HtmlParserFactory Class Reference
factory class for html parsers.
#include <HtmlParserFactory.h>
Public Types
enum HtmlParserType { LIBXML = 0, DOM, MAX_HTML_PARSER_TYPE }
type of html parser
Public Member Functions
virtual ~HtmlParserFactory ()
Static Public Member Functions
static void CreateInstance (const HtmlParserType &type, tools::Pointer< IHtmlParser > &client)
creates a html parser based on the given type
Private Member Functions
HtmlParserFactory ()
Detailed Description
factory class for html parsers.
Definition at line 19 of file HtmlParserFactory.h.
Member Enumeration Documentation
enum htmlparser::HtmlParserFactory::HtmlParserType
type of html parser
Enumerator:
LIBXML
using libXML based html parser
DOM
using own html5 parser implementation
MAX_HTML_PARSER_TYPE
do not use this
Definition at line 26 of file HtmlParserFactory.h.
Constructor & Destructor Documentation
htmlparser::HtmlParserFactory::HtmlParserFactory () [private]
Definition at line 15 of file HtmlParserFactory.cpp.
htmlparser::HtmlParserFactory::~HtmlParserFactory () [virtual]
Definition at line 18 of file HtmlParserFactory.cpp.
Member Function Documentation
void htmlparser::HtmlParserFactory::CreateInstance (const HtmlParserType & type, tools::Pointer< IHtmlParser > & client) [static]
creates a html parser based on the given type
Parameters:
type type of html parser
client created client instance
Definition at line 21 of file HtmlParserFactory.cpp.
References DOM, LIBXML, and tools::Pointer< T >::Set().
Referenced by parser::HtmlParserThread::ParsePages(), and toolbot::UnitTestSAX2HtmlParser::Test().
The documentation for this class was generated from the following files:
HtmlParser/src/HtmlParserFactory.h
HtmlParser/src/HtmlParserFactory.cpp