DeepNet: database::TableColumnDefinition Class Reference
database::TableColumnDefinition Class Reference
class containing definition of a TableColumn.
#include <TableColumnDefinition.h>
Public Member Functions
virtual ~TableColumnDefinition ()
TableColumnType GetColumnType (void) const
gets column type.
const std::string & GetTableName (void) const
gets table name.
const std::string & GetDatabaseName (void) const
gets database name.
const std::string & GetColumnName (void) const
gets column name.
bool IsPrimaryKey (void) const
check if column is a primary key.
bool IsAutoGenerated (void) const
checks if value for this column is generated automatically.
bool IsForeignKey (void) const
checks if column is a foreign key.
bool IsUniqueKey (void) const
checks if column is a unique key.
bool IsIndex (void) const
checks if column is an index.
bool IsNullable (void) const
checks if column is nullable.
bool HasDefaultValue (void) const
checks if column has a default value.
const
TableColumnDefinitionCreateParam & GetConstCreateParam (void) const
gets const create parameters for this column.
TableColumnDefinitionCreateParam & GetCreateParam (void)
gets create parameters for this column.
Static Public Member Functions
static TableColumnDefinition * CreateInstance (const TableColumnDefinitionCreateParam &param)
factory function for column definitions.
Private Member Functions
TableColumnDefinition (const TableColumnDefinition &copy)
TableColumnDefinition (const TableColumnDefinitionCreateParam &param)
Private Attributes
TableColumnDefinitionCreateParam definition
Detailed Description
class containing definition of a TableColumn.
column definition used in TableColumn class.
Definition at line 19 of file TableColumnDefinition.h.
Constructor & Destructor Documentation
database::TableColumnDefinition::TableColumnDefinition (const TableColumnDefinition & copy) [private]
Definition at line 17 of file TableColumnDefinition.cpp.
References THROW_EXCEPTION.
Referenced by CreateInstance().
database::TableColumnDefinition::TableColumnDefinition (const TableColumnDefinitionCreateParam & param) [private]
Definition at line 13 of file TableColumnDefinition.cpp.
database::TableColumnDefinition::~TableColumnDefinition () [virtual]
Definition at line 22 of file TableColumnDefinition.cpp.
Member Function Documentation
TableColumnType database::TableColumnDefinition::GetColumnType (void) const [inline]
gets column type.
Returns:
column type.
Definition at line 33 of file TableColumnDefinition.h.
References database::TableColumnDefinitionCreateParam::columnType, and definition.
Referenced by database::TableColumn::CleanUp(), database::TableColumn::CopyValue(), database::TableColumn::CreateInstanceFromValue(), database::TableColumn::InitFromDefinition(), and database::MySQLTableBase::SetColumnValues().
const std::string& database::TableColumnDefinition::GetTableName (void) const [inline]
gets table name.
Returns:
table name.
Definition at line 39 of file TableColumnDefinition.h.
References definition, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::WhereConditionTableColumn::ToString().
const std::string& database::TableColumnDefinition::GetDatabaseName (void) const [inline]
gets database name.
Returns:
database name.
Definition at line 45 of file TableColumnDefinition.h.
References database::TableColumnDefinitionCreateParam::databaseName, and definition.
const std::string& database::TableColumnDefinition::GetColumnName (void) const [inline]
gets column name.
Returns:
column name.
Definition at line 51 of file TableColumnDefinition.h.
References database::TableColumnDefinitionCreateParam::columnName, and definition.
Referenced by database::TableColumn::GetColumnName(), database::MySQLInsertOrUpdateStatement::ToSQL(), and database::InnerJoinEntry::ToString().
bool database::TableColumnDefinition::IsPrimaryKey (void) const [inline]
check if column is a primary key.
Returns:
false if column is not a primary key, true if it is.
Definition at line 57 of file TableColumnDefinition.h.
References definition, and database::TableColumnDefinitionCreateParam::isPrimaryKey.
bool database::TableColumnDefinition::IsAutoGenerated (void) const [inline]
checks if value for this column is generated automatically.
i.e. auto-increment id columns.
Returns:
false if column is not automatically generated, true if it is.
Definition at line 64 of file TableColumnDefinition.h.
References definition, and database::TableColumnDefinitionCreateParam::isAutoGenerated.
Referenced by database::TableColumn::InitFromDefinition().
bool database::TableColumnDefinition::IsForeignKey (void) const [inline]
checks if column is a foreign key.
Returns:
false if column is not a foreign key, true if it is.
Definition at line 70 of file TableColumnDefinition.h.
References definition, and database::TableColumnDefinitionCreateParam::isForeignKey.
bool database::TableColumnDefinition::IsUniqueKey (void) const [inline]
checks if column is a unique key.
Returns:
false if column is not a unique key, true if it is.
Definition at line 76 of file TableColumnDefinition.h.
References definition, and database::TableColumnDefinitionCreateParam::isUniqueKey.
bool database::TableColumnDefinition::IsIndex (void) const
checks if column is an index.
Returns:
false if column is not indexed, true if it is.
Definition at line 43 of file TableColumnDefinition.cpp.
References definition, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isPrimaryKey, and database::TableColumnDefinitionCreateParam::isUniqueKey.
bool database::TableColumnDefinition::IsNullable (void) const
checks if column is nullable.
Returns:
false if column is not nullable, true if it is.
Definition at line 29 of file TableColumnDefinition.cpp.
References definition, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, and database::TableColumnDefinitionCreateParam::isNullable.
bool database::TableColumnDefinition::HasDefaultValue (void) const [inline]
checks if column has a default value.
Returns:
false if column is no default value, true if it has.
Definition at line 94 of file TableColumnDefinition.h.
References definition, and database::TableColumnDefinitionCreateParam::hasDefaultValue.
const TableColumnDefinitionCreateParam& database::TableColumnDefinition::GetConstCreateParam (void) const [inline]
gets const create parameters for this column.
Returns:
create parameters for this column.
Definition at line 100 of file TableColumnDefinition.h.
References definition.
Referenced by database::TableDefinitionCreateParam::CopyColumns(), and database::TableColumn::CreateInstanceFromValue().
TableColumnDefinitionCreateParam& database::TableColumnDefinition::GetCreateParam (void) [inline]
gets create parameters for this column.
Returns:
create parameters for this column.
Definition at line 106 of file TableColumnDefinition.h.
References definition.
TableColumnDefinition * database::TableColumnDefinition::CreateInstance (const TableColumnDefinitionCreateParam & param) [static]
factory function for column definitions.
Parameters:
param column definition.
Returns:
column definition.
Definition at line 25 of file TableColumnDefinition.cpp.
References TableColumnDefinition().
Referenced by database::TableDefinitionCreateParam::CopyColumns(), and database::MySQLTableBase::CreateTableDefinition().
Member Data Documentation
TableColumnDefinitionCreateParam database::TableColumnDefinition::definition [private]
Definition at line 117 of file TableColumnDefinition.h.
Referenced by GetColumnName(), GetColumnType(), GetConstCreateParam(), GetCreateParam(), GetDatabaseName(), GetTableName(), HasDefaultValue(), IsAutoGenerated(), IsForeignKey(), IsIndex(), IsNullable(), IsPrimaryKey(), and IsUniqueKey().
The documentation for this class was generated from the following files:
Database/src/TableColumnDefinition.h
Database/src/TableColumnDefinition.cpp