DeepNet: domparser::ElementFactory Class Reference
domparser::ElementFactory Class Reference
#include <ElementFactory.h>
Public Member Functions
virtual ~ElementFactory ()
Static Public Member Functions
static Element * FromName (Document *doc, const DOMString &localName)
constructs an element by it's parent document and it's tag name
static Element * FromName (Document *doc, const DOMString *nameSpace, const DOMString &qualifiedName)
constructs an element by it's parent document and it's tag name
Private Member Functions
ElementFactory (Document *doc, const DOMString &localName)
constructs an ElementFactory object by it's parent document and tag name
Element * FromName ()
Private Attributes
Document * doc
const DOMString & localName
Detailed Description
Definition at line 17 of file ElementFactory.h.
Constructor & Destructor Documentation
domparser::ElementFactory::ElementFactory (Document * doc, const DOMString & localName) [private]
constructs an ElementFactory object by it's parent document and tag name
Parameters:
doc parent document
localName tag name
See also:
domparser::ElementFactory::FromName
Definition at line 23 of file ElementFactory.cpp.
domparser::ElementFactory::~ElementFactory () [virtual]
Definition at line 28 of file ElementFactory.cpp.
Member Function Documentation
Element * domparser::ElementFactory::FromName (Document * doc, const DOMString & localName) [static]
constructs an element by it's parent document and it's tag name
Parameters:
doc parent document
localName tag name of the element
Returns:
constructed element
Definition at line 31 of file ElementFactory.cpp.
References FromName().
Referenced by FromName().
Element * domparser::ElementFactory::FromName (Document * doc, const DOMString * nameSpace, const DOMString & qualifiedName) [static]
constructs an element by it's parent document and it's tag name
Parameters:
doc parent document
nameSpace namespace of the element
qualifiedName tag name of the element
Returns:
constructed element
Definition at line 36 of file ElementFactory.cpp.
Element * domparser::ElementFactory::FromName () [private]
Definition at line 40 of file ElementFactory.cpp.
References domparser::HTMLElement::abbrTag, domparser::HTMLElement::addressTag, domparser::HTMLElement::areaTag, domparser::HTMLElement::articleTag, domparser::HTMLElement::asideTag, domparser::HTMLElement::aTag, domparser::HTMLElement::audioTag, domparser::HTMLElement::baseTag, domparser::HTMLElement::bdiTag, domparser::HTMLElement::bdoTag, domparser::HTMLElement::blockquoteTag, domparser::HTMLElement::bodyTag, domparser::HTMLElement::brTag, domparser::HTMLElement::bTag, domparser::HTMLElement::buttonTag, domparser::HTMLElement::canvasTag, domparser::HTMLElement::captionTag, domparser::HTMLElement::citeTag, domparser::HTMLElement::codeTag, domparser::HTMLElement::colgroupTag, domparser::HTMLElement::colTag, domparser::HTMLElement::commandTag, domparser::HTMLElement::datalistTag, domparser::HTMLElement::ddTag, domparser::HTMLElement::delTag, domparser::HTMLElement::detailsTag, domparser::HTMLElement::dfnTag, domparser::HTMLElement::dialogTag, domparser::HTMLElement::divTag, domparser::HTMLElement::dlTag, doc, domparser::HTMLElement::dtTag, domparser::HTMLElement::embedTag, domparser::HTMLElement::emTag, domparser::HTMLElement::fieldsetTag, domparser::HTMLElement::figcaptionTag, domparser::HTMLElement::figureTag, domparser::HTMLElement::footerTag, domparser::HTMLElement::formTag, domparser::HTMLElement::h1Tag, domparser::HTMLElement::h2Tag, domparser::HTMLElement::h3Tag, domparser::HTMLElement::h4Tag, domparser::HTMLElement::h5Tag, domparser::HTMLElement::h6Tag, domparser::HTMLElement::headerTag, domparser::HTMLElement::headTag, domparser::HTMLElement::hgroupTag, domparser::HTMLElement::hrTag, domparser::HTMLElement::htmlTag, domparser::HTMLElement::iframeTag, domparser::HTMLElement::imgTag, domparser::HTMLElement::inputTag, domparser::HTMLElement::insTag, domparser::HTMLElement::iTag, domparser::HTMLElement::kbdTag, domparser::HTMLElement::keygenTag, domparser::HTMLElement::labelTag, domparser::HTMLElement::legendTag, domparser::HTMLElement::linkTag, domparser::HTMLElement::liTag, localName, domparser::HTMLElement::mapTag, domparser::HTMLElement::markTag, domparser::HTMLElement::menuTag, domparser::HTMLElement::metaTag, domparser::HTMLElement::meterTag, domparser::HTMLElement::navTag, domparser::HTMLElement::noscriptTag, domparser::HTMLElement::objectTag, domparser::HTMLElement::olTag, domparser::HTMLElement::optgroupTag, domparser::HTMLElement::optionTag, domparser::HTMLElement::outputTag, domparser::HTMLElement::paramTag, domparser::HTMLElement::preTag, domparser::HTMLElement::progressTag, domparser::HTMLElement::pTag, domparser::HTMLElement::qTag, domparser::HTMLElement::rpTag, domparser::HTMLElement::rtTag, domparser::HTMLElement::rubyTag, domparser::HTMLElement::sampTag, domparser::HTMLElement::scriptTag, domparser::HTMLElement::sectionTag, domparser::HTMLElement::selectTag, domparser::HTMLElement::smallTag, domparser::HTMLElement::sourceTag, domparser::HTMLElement::spanTag, domparser::HTMLElement::sTag, domparser::HTMLElement::strongTag, domparser::HTMLElement::styleTag, domparser::HTMLElement::subTag, domparser::HTMLElement::summaryTag, domparser::HTMLElement::supTag, domparser::HTMLElement::tableTag, domparser::HTMLElement::TagFromName(), domparser::HTMLElement::tbodyTag, domparser::HTMLElement::tdTag, domparser::HTMLElement::textareaTag, domparser::HTMLElement::tfootTag, domparser::HTMLElement::theadTag, domparser::HTMLElement::thTag, domparser::HTMLElement::timeTag, domparser::HTMLElement::titleTag, domparser::HTMLElement::trackTag, domparser::HTMLElement::trTag, domparser::HTMLElement::ulTag, domparser::HTMLElement::unknownTag, domparser::HTMLElement::uTag, domparser::HTMLElement::varTag, domparser::HTMLElement::videoTag, and domparser::HTMLElement::wbrTag.
Referenced by domparser::Document::createElement(), and domparser::Document::createElementNS().
Member Data Documentation
Document* domparser::ElementFactory::doc [private]
Definition at line 52 of file ElementFactory.h.
Referenced by FromName().
const DOMString& domparser::ElementFactory::localName [private]
Definition at line 53 of file ElementFactory.h.
Referenced by FromName().
The documentation for this class was generated from the following files:
DOMParser/src/ElementFactory.h
DOMParser/src/ElementFactory.cpp