DeepNet: tools::DebuggingTools Class Reference
tools::DebuggingTools Class Reference
wrapper class for debugging functionality.
#include <DebuggingTools.h>
Classes
struct sig_ucontext_t
struct SignalInfos
container for signal related information.
Public Member Functions
virtual ~DebuggingTools ()
Static Public Member Functions
static SignalInfos GetSignalInfos (int sig_num, siginfo_t *info, void *ucontext)
parses raw signal information.
static std::string GetBacktrace (void *caller=NULL)
creates a backtrace.
static void DebugBreak (bool preferBuiltinTrapToSigTrap=true)
raises a debug trap.
static void DumpThreadContext (std::string &out)
dumps current thread information to a string.
static bool DemangleFunctionName (const char *pszMangledFunctionName, std::string &demangledFunctionName)
demangles a function name.
static bool GetFileLineFromModuleAddress (const char *pszModuleName, const void *addr, std::string &file, size_t &line)
resolves an address to a source file and line.
Private Member Functions
DebuggingTools ()
Detailed Description
wrapper class for debugging functionality.
Definition at line 17 of file DebuggingTools.h.
Constructor & Destructor Documentation
tools::DebuggingTools::DebuggingTools () [private]
Definition at line 34 of file DebuggingTools.cpp.
tools::DebuggingTools::~DebuggingTools () [virtual]
Definition at line 37 of file DebuggingTools.cpp.
Member Function Documentation
DebuggingTools::SignalInfos tools::DebuggingTools::GetSignalInfos (int sig_num, siginfo_t * info, void * ucontext) [static]
parses raw signal information.
Parameters:
sig_num signal number.
info signal infos.
ucontext context
Returns:
parsed signal infos.
Definition at line 40 of file DebuggingTools.cpp.
References tools::DebuggingTools::SignalInfos::caller, GetBacktrace(), tools::DebuggingTools::SignalInfos::infoText, and tools::DebuggingTools::sig_ucontext_t::uc_mcontext.
Referenced by SignalHandler(), and bot::Bot::SignalHandler().
std::string tools::DebuggingTools::GetBacktrace (void * caller = NULL) [static]
creates a backtrace.
Parameters:
caller originating address.
Returns:
backtrace
Definition at line 64 of file DebuggingTools.cpp.
References DemangleFunctionName(), and GetFileLineFromModuleAddress().
Referenced by GetSignalInfos(), and errors::Exception::TerminateHandler().
void tools::DebuggingTools::DebugBreak (bool preferBuiltinTrapToSigTrap = true) [static]
raises a debug trap.
Parameters:
preferBuiltinTrapToSigTrap true to prefer gcc builtin trap.
Definition at line 173 of file DebuggingTools.cpp.
void tools::DebuggingTools::DumpThreadContext (std::string & out) [static]
dumps current thread information to a string.
Parameters:
out current thread information.
Definition at line 199 of file DebuggingTools.cpp.
bool tools::DebuggingTools::DemangleFunctionName (const char * pszMangledFunctionName, std::string & demangledFunctionName) [static]
demangles a function name.
Parameters:
pszMangledFunctionName mangled name.
demangledFunctionName demangled name.
Returns:
false on error, true on success.
Definition at line 133 of file DebuggingTools.cpp.
Referenced by GetBacktrace().
bool tools::DebuggingTools::GetFileLineFromModuleAddress (const char * pszModuleName, const void * addr, std::string & file, size_t & line) [static]
resolves an address to a source file and line.
Parameters:
pszModuleName module name.
addr address of code.
file gets filled with filename.
line gets filled with lineno.
Returns:
false on error, true on success.
Definition at line 154 of file DebuggingTools.cpp.
References tools::StringTools::ExecuteCommand(), tools::StringTools::SplitBy(), tools::StringTools::TransformString(), and tools::StringTools::Trim().
Referenced by GetBacktrace().
The documentation for this class was generated from the following files:
Tools/src/DebuggingTools.h
Tools/src/DebuggingTools.cpp