DeepNet: indexing::ContentIndexer Class Reference
indexing::ContentIndexer Class Reference
#include <ContentIndexer.h>
Public Types
enum WordLen { SHORT, MEDIUM, LONG }
enum IndexerType { META_CONTENT, BODY_CONTENT, URL_CONTENT }
Public Member Functions
virtual ~ContentIndexer ()
virtual void OnCharacterReference (std::string *characterReference)
virtual void OnHtmlEntity (std::string *entity)
virtual void OnWord (std::string *word)
virtual void TerminateWord (void)
virtual void Parse (const std::string &input, const long long paragraph)
parses a text
virtual void ParseMeta (const std::string &input, const Dictionary::MetaInformationType &type)
parses content part of a meta type
int Read (char *buf, int maxSize)
virtual Dictionary & GetDictionary ()=0
gets dictionary of this indexer
Public Attributes
IndexerCtx * ctx
std::string content
std::string::iterator contentIter
Protected Member Functions
ContentIndexer (database::DatabaseConnection *database, const IndexerBase::IndexerType type)
Private Member Functions
virtual void OnParse (const long long paragraph)
Private Attributes
std::string tmpWord
long long posWord
long long paragraph
Detailed Description
Definition at line 41 of file ContentIndexer.h.
Member Enumeration Documentation
enum indexing::IndexerBase::WordLen [inherited]
Enumerator:
SHORT
MEDIUM
LONG
Definition at line 56 of file IndexerBase.h.
enum indexing::IndexerBase::IndexerType [inherited]
Enumerator:
META_CONTENT
BODY_CONTENT
URL_CONTENT
Definition at line 62 of file IndexerBase.h.
Constructor & Destructor Documentation
indexing::ContentIndexer::ContentIndexer (database::DatabaseConnection * database, const IndexerBase::IndexerType type) [protected]
Definition at line 22 of file ContentIndexer.cpp.
References indexing::IndexerBase::ctx.
indexing::ContentIndexer::~ContentIndexer () [virtual]
Definition at line 29 of file ContentIndexer.cpp.
References indexing::IndexerBase::ctx.
Member Function Documentation
void indexing::ContentIndexer::OnCharacterReference (std::string * characterReference) [virtual]
Definition at line 51 of file ContentIndexer.cpp.
References tmpWord.
void indexing::ContentIndexer::OnHtmlEntity (std::string * entity) [virtual]
Definition at line 43 of file ContentIndexer.cpp.
References tmpWord.
void indexing::ContentIndexer::OnWord (std::string * word) [virtual]
Definition at line 35 of file ContentIndexer.cpp.
References tmpWord.
void indexing::ContentIndexer::TerminateWord (void) [virtual]
Definition at line 59 of file ContentIndexer.cpp.
References indexing::Dictionary::AddContent(), indexing::IIndexer::GetDictionary(), paragraph, posWord, and tmpWord.
Referenced by OnParse().
void indexing::ContentIndexer::OnParse (const long long paragraph) [private, virtual]
Implements indexing::IndexerBase.
Definition at line 67 of file ContentIndexer.cpp.
References indexing::IndexerBase::ctx, paragraph, indexing::ContentIndexerHelper::ParseFromContext(), posWord, and TerminateWord().
void indexing::IndexerBase::Parse (const std::string & input, const long long paragraph) [virtual, inherited]
parses a text
Parameters:
input text to parse
paragraph paragraph of this text
Implements indexing::IIndexer.
Definition at line 31 of file IndexerBase.cpp.
References indexing::IndexerBase::content, indexing::IndexerBase::contentIter, input(), and indexing::IndexerBase::OnParse().
void indexing::IndexerBase::ParseMeta (const std::string & input, const Dictionary::MetaInformationType & type) [virtual, inherited]
parses content part of a meta type
Parameters:
input content part to parse
type meta type to set
Implements indexing::IIndexer.
Definition at line 39 of file IndexerBase.cpp.
References indexing::IndexerBase::OnParseMeta().
int indexing::IndexerBase::Read (char * buf, int maxSize) [inherited]
Definition at line 43 of file IndexerBase.cpp.
References indexing::IndexerBase::content, and indexing::IndexerBase::contentIter.
virtual Dictionary& indexing::IIndexer::GetDictionary () [pure virtual, inherited]
gets dictionary of this indexer
Returns:
instance of this indexers dictionary
Implemented in indexing::IndexerEx, indexing::GenericWebContentIndexer, and indexing::DataminingContentIndexer.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), and TerminateWord().
Member Data Documentation
std::string indexing::ContentIndexer::tmpWord [private]
Definition at line 58 of file ContentIndexer.h.
Referenced by OnCharacterReference(), OnHtmlEntity(), OnWord(), and TerminateWord().
long long indexing::ContentIndexer::posWord [private]
Definition at line 60 of file ContentIndexer.h.
Referenced by OnParse(), and TerminateWord().
long long indexing::ContentIndexer::paragraph [private]
Definition at line 61 of file ContentIndexer.h.
Referenced by OnParse(), and TerminateWord().
IndexerCtx* indexing::IndexerBase::ctx [inherited]
Definition at line 89 of file IndexerBase.h.
Referenced by ContentIndexer(), indexing::MetaIndexer::MetaIndexer(), indexing::MetaIndexer::OnParse(), OnParse(), ~ContentIndexer(), indexing::IndexerBase::~IndexerBase(), and indexing::MetaIndexer::~MetaIndexer().
std::string indexing::IndexerBase::content [inherited]
Definition at line 91 of file IndexerBase.h.
Referenced by indexing::IndexerBase::Parse(), and indexing::IndexerBase::Read().
std::string::iterator indexing::IndexerBase::contentIter [inherited]
Definition at line 92 of file IndexerBase.h.
Referenced by indexing::IndexerBase::Parse(), and indexing::IndexerBase::Read().
The documentation for this class was generated from the following files:
Indexer/src/ContentIndexer.h
Indexer/src/ContentIndexer.cpp