DeepNet: queryserver::BackLinkEntry Class Reference
queryserver::BackLinkEntry Class Reference
#include <BackLinkEntry.h>
Public Member Functions
BackLinkEntry (const double &relevance, const double &weight, const long long urlStageID, const std::vector< htmlparser::DatabaseUrl > &backlinks)
BackLinkEntry ()
const long long UrlStageID () const
const std::vector
< htmlparser::DatabaseUrl > & BackLinks () const
bool operator== (const Relevance &rhs) const
bool operator< (const Relevance &rhs) const
Relevance operator+ (const Relevance &rhs) const
Relevance operator* (const Relevance &rhs) const
double GetWeightedRelevance (void) const
const double & GetRelevance (void) const
const double & GetWeight (void) const
void SetRelevance (const double &in)
void SetWeight (const double &in)
Private Attributes
long long urlStageID
std::vector
< htmlparser::DatabaseUrl > backlinks
Detailed Description
Definition at line 20 of file BackLinkEntry.h.
Constructor & Destructor Documentation
queryserver::BackLinkEntry::BackLinkEntry (const double & relevance, const double & weight, const long long urlStageID, const std::vector< htmlparser::DatabaseUrl > & backlinks) [inline]
Definition at line 23 of file BackLinkEntry.h.
queryserver::BackLinkEntry::BackLinkEntry () [inline]
Definition at line 28 of file BackLinkEntry.h.
Member Function Documentation
const long long queryserver::BackLinkEntry::UrlStageID () const [inline]
Definition at line 33 of file BackLinkEntry.h.
References urlStageID.
const std::vector<htmlparser::DatabaseUrl>& queryserver::BackLinkEntry::BackLinks () const [inline]
Definition at line 34 of file BackLinkEntry.h.
References backlinks.
bool queryserver::Relevance::operator== (const Relevance & rhs) const [inline, inherited]
Definition at line 38 of file Relevance.h.
References queryserver::Relevance::GetWeightedRelevance().
bool queryserver::Relevance::operator< (const Relevance & rhs) const [inline, inherited]
Definition at line 39 of file Relevance.h.
References queryserver::Relevance::GetWeightedRelevance().
Relevance queryserver::Relevance::operator+ (const Relevance & rhs) const [inline, inherited]
Definition at line 40 of file Relevance.h.
References queryserver::Relevance::GetWeightedRelevance(), queryserver::Relevance::Relevance(), and queryserver::Relevance::weight.
Relevance queryserver::Relevance::operator* (const Relevance & rhs) const [inline, inherited]
Definition at line 41 of file Relevance.h.
References queryserver::Relevance::Relevance(), queryserver::Relevance::relevance, and queryserver::Relevance::weight.
double queryserver::Relevance::GetWeightedRelevance (void) const [inline, inherited]
Definition at line 44 of file Relevance.h.
References queryserver::Relevance::GetRelevance(), and queryserver::Relevance::GetWeight().
Referenced by queryserver::Relevance::operator+(), queryserver::Relevance::operator<(), and queryserver::Relevance::operator==().
const double& queryserver::Relevance::GetRelevance (void) const [inline, inherited]
Definition at line 47 of file Relevance.h.
References queryserver::Relevance::relevance.
Referenced by queryserver::Relevance::GetWeightedRelevance().
const double& queryserver::Relevance::GetWeight (void) const [inline, inherited]
Definition at line 48 of file Relevance.h.
References queryserver::Relevance::weight.
Referenced by queryserver::Relevance::GetWeightedRelevance().
void queryserver::Relevance::SetRelevance (const double & in) [inline, inherited]
Definition at line 50 of file Relevance.h.
References queryserver::Relevance::relevance.
void queryserver::Relevance::SetWeight (const double & in) [inline, inherited]
Definition at line 51 of file Relevance.h.
References queryserver::Relevance::weight.
Member Data Documentation
long long queryserver::BackLinkEntry::urlStageID [private]
Definition at line 37 of file BackLinkEntry.h.
Referenced by UrlStageID().
std::vector<htmlparser::DatabaseUrl> queryserver::BackLinkEntry::backlinks [private]
Definition at line 38 of file BackLinkEntry.h.
Referenced by BackLinks().
The documentation for this class was generated from the following file:
QueryServer/src/BackLinkEntry.h