DISCONNECT CURRENT;
DROP   DATABASE deepnet;
CREATE DATABASE deepnet AUTOMATIC STORAGE YES  ON '/home/deepinst' DBPATH ON '/home/deepinst' USING CODESET UTF-8 TERRITORY DE COLLATE USING SYSTEM PAGESIZE 8192;
