DeepNet: workerbot::WorkerBot Class Reference
workerbot::WorkerBot Class Reference
implementation of the worker bot which is the main application of the whole DeepNet infrastructure.
#include <WorkerBot.h>
Public Member Functions
WorkerBot ()
virtual ~WorkerBot ()
bool Run (int argc, char **argv)
this function starts the application.
virtual void OnException (errors::Exception &ex)
this function is called when an uncaught exception derived from errors::Exception occurs.
virtual void OnException ()
this function is called when an uncaught exception occurs.
Protected Member Functions
virtual bool OnPreInit ()
called after registration of default parameters and before initialization.
virtual bool OnInit ()
called after bot configuration and initialization has completed.
virtual bool OnPostInit ()
called after bot and application specific configuration is initialized and validated.
virtual bool OnRun ()
called when all initialization is completed and the applications starts running.
virtual bool OnShutdown ()
called before the application is shutting down.
ConfigManager & Config ()
gets the configuration of this bot::Bot.
database::DatabaseHelper & DB ()
gets the database of this bot::Bot.
Protected Attributes
volatile bool shutdownReceived
true if application shall end.
database::DatabaseConfig * dbConfig
database configuration.
Private Member Functions
void RegisterCrawlerConfigParams ()
bool InitCrawlerConfig ()
void RegisterParserConfigParams ()
bool InitParserConfig ()
void RegisterIndexerConfigParams ()
bool InitIndexerConfigParams ()
void RegisterModeSpecificParams ()
bool InitModeConfig ()
bool CheckCleanShutdown ()
Private Attributes
tools::Pointer< crawler::Crawler > crawler
tools::Pointer
< crawler::CrawlerParam > crawlerParam
tools::Pointer
< parser::HtmlParserBase > parser
tools::Pointer
< parser::HtmlParserParam > parserParam
tools::Pointer< indexing::Indexer > indexer
tools::Pointer
< indexing::IndexerParam > indexerParam
Detailed Description
implementation of the worker bot which is the main application of the whole DeepNet infrastructure.
Definition at line 33 of file WorkerBot.h.
Constructor & Destructor Documentation
workerbot::WorkerBot::WorkerBot ()
Definition at line 41 of file WorkerBot.cpp.
workerbot::WorkerBot::~WorkerBot () [virtual]
Definition at line 45 of file WorkerBot.cpp.
Member Function Documentation
bool workerbot::WorkerBot::OnPreInit (void) [protected, virtual]
called after registration of default parameters and before initialization.
usually used to register application specific config parameters.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 119 of file WorkerBot.cpp.
References bot::Bot::Config(), RegisterCrawlerConfigParams(), bot::ConfigManager::RegisterFlag(), RegisterIndexerConfigParams(), RegisterModeSpecificParams(), and RegisterParserConfigParams().
bool workerbot::WorkerBot::OnInit () [protected, virtual]
called after bot configuration and initialization has completed.
usually used to initialize application specific config parameters.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 48 of file WorkerBot.cpp.
References crawlerParam, indexerParam, InitCrawlerConfig(), InitIndexerConfigParams(), InitParserConfig(), parserParam, and tools::Pointer< T >::Set().
bool workerbot::WorkerBot::OnPostInit () [protected, virtual]
called after bot and application specific configuration is initialized and validated.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 130 of file WorkerBot.cpp.
References InitModeConfig().
bool workerbot::WorkerBot::OnRun () [protected, virtual]
called when all initialization is completed and the applications starts running.
when this function returns, the applications does NOT exit.
Returns:
false on error, true on success.
Implements bot::Bot.
Definition at line 63 of file WorkerBot.cpp.
References crawler, crawlerParam, parser::HtmlParserParam::databaseConfig, indexing::IndexerParam::databaseConfig, crawler::CrawlerParam::databaseConfig, bot::Bot::dbConfig, tools::Pointer< T >::Get(), indexer, indexerParam, parser, parserParam, and threading::Thread::StartThread().
bool workerbot::WorkerBot::OnShutdown () [protected, virtual]
called before the application is shutting down.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 78 of file WorkerBot.cpp.
References crawler, tools::Pointer< T >::Get(), indexer, log::Logging::LogTrace(), parser, PERFORMANCE_LOG_START, PERFORMANCE_LOG_STOP, threading::Thread::SetShallEnd(), tools::PerformanceCounter::Start(), tools::PerformanceCounter::Stop(), and threading::Thread::WaitForThread().
void workerbot::WorkerBot::RegisterCrawlerConfigParams () [private]
Definition at line 135 of file WorkerBot.cpp.
References bot::Bot::Config(), bot::ConfigManager::RegisterFlag(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
bool workerbot::WorkerBot::InitCrawlerConfig () [private]
Definition at line 170 of file WorkerBot.cpp.
References crawler::CrawlerParam::clientType, bot::Bot::Config(), crawler::CrawlerParam::connectionTimeout, crawler::CrawlerParam::connectTimeout, crawlerParam, network::HttpClientFactory::CURL, tools::Pointer< T >::Get(), tools::Pointer< T >::IsNull(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, crawler::CrawlerParam::maxPerSelect, crawler::CrawlerParam::minAge, network::HttpClientFactory::OWN, crawler::CrawlerParam::respectRobotsTxt, crawler::CrawlerParam::speedLimitKB, crawler::CrawlerParam::threadCount, crawler::CrawlerParam::useIPv6, crawler::CrawlerParam::userAgent, and crawler::CrawlerParam::waitOnIdle.
Referenced by OnInit().
void workerbot::WorkerBot::RegisterParserConfigParams () [private]
Definition at line 241 of file WorkerBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
bool workerbot::WorkerBot::InitParserConfig () [private]
Definition at line 256 of file WorkerBot.cpp.
References bot::Bot::Config(), htmlparser::HtmlParserFactory::DOM, tools::Pointer< T >::Get(), tools::Pointer< T >::IsNull(), htmlparser::HtmlParserFactory::LIBXML, log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, parser::HtmlParserParam::maxPerSelect, parserParam, parser::HtmlParserParam::parserThreadCount, parser::HtmlParserParam::parserType, tools::StringTools::ToLowerIP(), and parser::HtmlParserParam::waitOnIdle.
Referenced by OnInit().
void workerbot::WorkerBot::RegisterIndexerConfigParams () [private]
Definition at line 297 of file WorkerBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
bool workerbot::WorkerBot::InitIndexerConfigParams () [private]
Definition at line 309 of file WorkerBot.cpp.
References bot::Bot::Config(), tools::Pointer< T >::Get(), bot::ConfigManager::GetValue(), indexerParam, tools::Pointer< T >::IsNull(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::IndexerParam::maxPerSelect, indexing::IndexerParam::threadCount, and indexing::IndexerParam::waitOnIdle.
Referenced by OnInit().
void workerbot::WorkerBot::RegisterModeSpecificParams () [private]
Definition at line 327 of file WorkerBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
bool workerbot::WorkerBot::InitModeConfig () [private]
Definition at line 333 of file WorkerBot.cpp.
References bot::Bot::Config(), crawler, crawlerParam, crawler::CrawlerFactory::CreateCommerceSearchCrawler(), parser::HtmlParserBaseFactory::CreateCommerceSearchParser(), crawler::CrawlerFactory::CreateDataminingCrawler(), indexing::IndexerFactory::CreateDataminingIndexer(), crawler::CrawlerFactory::CreateFencedCrawler(), crawler::CrawlerFactory::CreateGenericWebCrawler(), indexing::IndexerFactory::CreateGenericWebIndexer(), parser::HtmlParserBaseFactory::CreateGenericWebParser(), tools::Pointer< T >::Get(), indexer, indexerParam, parser, parserParam, tools::Pointer< T >::Set(), and THROW_EXCEPTION.
Referenced by OnPostInit().
bool workerbot::WorkerBot::CheckCleanShutdown () [private]
Definition at line 373 of file WorkerBot.cpp.
References bot::Bot::Config(), crawler, bot::Bot::DB(), bot::DatabaseRepair::FixUncleanShutdown(), tools::Pointer< T >::Get(), crawler::Crawler::GetOldCrawlerSessionIDs(), log::Logging::LogError(), and log::Logging::LogInfo().
bool bot::Bot::Run (int argc, char ** argv) [inherited]
this function starts the application.
it returns when the application exits.
Parameters:
argc number of commandline arguments.
argv array of commandline arguments.
Returns:
false on error, true on success.
Definition at line 213 of file Bot.cpp.
References bot::Bot::Init(), errors::Exception::InitializeExceptionHandling(), bot::Bot::PostInit(), bot::Bot::PreInit(), bot::Bot::restartAfterShutdown, bot::Bot::Run(), and bot::Bot::Shutdown().
Referenced by main().
void bot::Bot::OnException (errors::Exception & ex) [virtual, inherited]
this function is called when an uncaught exception derived from errors::Exception occurs.
Parameters:
ex exception caught by application
Definition at line 396 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by main().
void bot::Bot::OnException () [virtual, inherited]
this function is called when an uncaught exception occurs.
exceptions derived from errors::Exception are caught separately.
See also:
bot::Bot::OnException(errors::Exception&)
Definition at line 401 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
ConfigManager& bot::Bot::Config () [inline, protected, inherited]
gets the configuration of this bot::Bot.
See also:
bot::ConfigManager
Returns:
associated bot::ConfigManager.
Definition at line 75 of file Bot.h.
References bot::Bot::configManager.
Referenced by CheckCleanShutdown(), bot::Bot::Init(), bot::Bot::InitCacheConfigParams(), InitCrawlerConfig(), bot::Bot::InitDatabaseConfigs(), InitIndexerConfigParams(), bot::Bot::InitLogging(), InitModeConfig(), InitParserConfig(), bot::Bot::InitPerformanceLoggingParams(), OnPreInit(), toolbot::DeepNetToolBot::OnRun(), bot::Bot::PostInit(), toolbot::DeepNetToolBot::ProcessUnitTests(), bot::Bot::RegisterCacheConfigParams(), toolbot::DeepNetToolBot::RegisterCommerceSearchParams(), RegisterCrawlerConfigParams(), bot::Bot::RegisterDatabaseConfigParams(), toolbot::DeepNetToolBot::RegisterDatabaseRepairParams(), toolbot::DeepNetToolBot::RegisterDataminingParams(), bot::Bot::RegisterDefaultFlags(), bot::Bot::RegisterDefaultParams(), toolbot::DeepNetToolBot::RegisterHtmlClientCURLParams(), toolbot::DeepNetToolBot::RegisterHtmlDocumentFactoryParams(), toolbot::DeepNetToolBot::RegisterHtmlTestParams(), RegisterIndexerConfigParams(), toolbot::DeepNetToolBot::RegisterIndexerExParams(), RegisterModeSpecificParams(), RegisterParserConfigParams(), toolbot::DeepNetToolBot::RegisterPCRERegexTestParams(), bot::Bot::RegisterPerformanceLoggingParams(), toolbot::DeepNetToolBot::RegisterRobotTxtParams(), and toolbot::DeepNetToolBot::RegisterUrlInserterParams().
database::DatabaseHelper& bot::Bot::DB () [inline, protected, inherited]
gets the database of this bot::Bot.
See also:
database::DatabaseHelper
Returns:
associated database::DatabaseHelper.
Definition at line 82 of file Bot.h.
References bot::Bot::databaseHelper.
Referenced by CheckCleanShutdown(), bot::Bot::InitCacheConfigParams(), bot::Bot::InitDatabaseConfigs(), toolbot::DeepNetToolBot::OnRun(), toolbot::DeepNetToolBot::OnShutdown(), toolbot::DeepNetToolBot::ProcessUnitTests(), bot::Bot::Shutdown(), and bot::Bot::WatchDog().
Member Data Documentation
tools::Pointer<crawler::Crawler> workerbot::WorkerBot::crawler [private]
Definition at line 61 of file WorkerBot.h.
Referenced by CheckCleanShutdown(), InitModeConfig(), OnRun(), and OnShutdown().
tools::Pointer<crawler::CrawlerParam> workerbot::WorkerBot::crawlerParam [private]
Definition at line 62 of file WorkerBot.h.
Referenced by InitCrawlerConfig(), InitModeConfig(), OnInit(), and OnRun().
tools::Pointer<parser::HtmlParserBase> workerbot::WorkerBot::parser [private]
Definition at line 64 of file WorkerBot.h.
Referenced by InitModeConfig(), OnRun(), and OnShutdown().
tools::Pointer<parser::HtmlParserParam> workerbot::WorkerBot::parserParam [private]
Definition at line 65 of file WorkerBot.h.
Referenced by InitModeConfig(), InitParserConfig(), OnInit(), and OnRun().
tools::Pointer<indexing::Indexer> workerbot::WorkerBot::indexer [private]
Definition at line 67 of file WorkerBot.h.
Referenced by InitModeConfig(), OnRun(), and OnShutdown().
tools::Pointer<indexing::IndexerParam> workerbot::WorkerBot::indexerParam [private]
Definition at line 68 of file WorkerBot.h.
Referenced by InitIndexerConfigParams(), InitModeConfig(), OnInit(), and OnRun().
volatile bool bot::Bot::shutdownReceived [protected, inherited]
true if application shall end.
Definition at line 166 of file Bot.h.
Referenced by toolbot::DeepNetToolBot::OnRun(), bot::Bot::Run(), and bot::Bot::SignalHandler().
database::DatabaseConfig* bot::Bot::dbConfig [protected, inherited]
database configuration.
Definition at line 171 of file Bot.h.
Referenced by bot::Bot::InitDatabaseConfigs(), bot::Bot::InitLogging(), OnRun(), and bot::Bot::Shutdown().
The documentation for this class was generated from the following files:
WorkerBot/src/WorkerBot.h
WorkerBot/src/WorkerBot.cpp