DeepNet: fastcgiserver::FastCGIServer Class Reference
fastcgiserver::FastCGIServer Class Reference
implements a fastcgi server instance.
#include <FastCGIServer.h>
Public Member Functions
virtual ~FastCGIServer ()
virtual bool StartServer (int argc, char **argv)
starts fastcgi server.
virtual bool StopServer ()
stops fastcgi server.
virtual void OnException ()
generic function to catch untyped expressions.
virtual void OnException (errors::Exception &ex)
generic function to catch errors::Exception
Protected Member Functions
FastCGIServer ()
Protected Attributes
bot::ConfigManager config
server configuration.
database::DatabaseConfig * databaseConfig
database configuration.
log::Logging * logging
logging.
std::string xsdRequestContent
xsd for requests.
std::string xsdResponseContent
xsd for responses.
Private Member Functions
virtual FastCGIServerThread * CreateThreadPort (database::DatabaseConfig *databaseConfig, threading::Mutex *acceptMutex, const int port, const int backlog=0)=0
virtual FastCGIServerThread * CreateThreadSocket (database::DatabaseConfig *databaseConfig, threading::Mutex *acceptMutex, const std::string &filename, const int backlog=0)=0
virtual void RegisterConfig ()
virtual bool InitConfig ()
void RegisterSocketConfig ()
bool InitSocketConfig ()
void RegisterLoggingParams ()
void InitLoggingConfig ()
void RegisterDatabaseConfigParams (void)
bool InitDatabaseConfigs (void)
Private Attributes
threading::Mutex acceptMutex
std::vector
< FastCGIServerThread * > threads
int basePort
int threadCount
std::string dictionaryFile
std::string affixFile
std::string requestXSD
std::string responseXSD
database::DatabaseHelper dbHelper
Detailed Description
implements a fastcgi server instance.
Definition at line 30 of file FastCGIServer.h.
Constructor & Destructor Documentation
fastcgiserver::FastCGIServer::FastCGIServer () [protected]
Definition at line 31 of file FastCGIServer.cpp.
References errors::Exception::InitializeExceptionHandling().
fastcgiserver::FastCGIServer::~FastCGIServer () [virtual]
Definition at line 39 of file FastCGIServer.cpp.
Member Function Documentation
bool fastcgiserver::FastCGIServer::StartServer (int argc, char ** argv) [virtual]
starts fastcgi server.
Parameters:
argc commandline arg count.
argv commandline args.
Returns:
false on error, true on success.
Reimplemented in queryserver::QueryServer, inspectorserver::InspectorServer, and suggestserver::SuggestServer.
Definition at line 42 of file FastCGIServer.cpp.
References acceptMutex, affixFile, basePort, config, CreateThreadPort(), databaseConfig, dictionaryFile, bot::ConfigManager::Init(), InitConfig(), InitDatabaseConfigs(), InitLoggingConfig(), InitSocketConfig(), tools::SpellChecking::InitSpellChecking(), RegisterDatabaseConfigParams(), RegisterLoggingParams(), bot::ConfigManager::RegisterParam(), RegisterSocketConfig(), fastcgiserver::FastCGIServerThread::SpellChecker(), threading::Thread::StartThread(), StopServer(), threadCount, and threads.
bool fastcgiserver::FastCGIServer::StopServer () [virtual]
stops fastcgi server.
Returns:
false on error, true on success.
Definition at line 78 of file FastCGIServer.cpp.
References threads.
Referenced by main(), and StartServer().
void fastcgiserver::FastCGIServer::OnException () [virtual]
generic function to catch untyped expressions.
Definition at line 258 of file FastCGIServer.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by main().
void fastcgiserver::FastCGIServer::OnException (errors::Exception & ex) [virtual]
generic function to catch errors::Exception
Parameters:
ex exception.
Definition at line 264 of file FastCGIServer.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
virtual FastCGIServerThread* fastcgiserver::FastCGIServer::CreateThreadPort (database::DatabaseConfig * databaseConfig, threading::Mutex * acceptMutex, const int port, const int backlog = 0) [private, pure virtual]
Implemented in queryserver::QueryServer, inspectorserver::InspectorServer, and suggestserver::SuggestServer.
Referenced by StartServer().
virtual FastCGIServerThread* fastcgiserver::FastCGIServer::CreateThreadSocket (database::DatabaseConfig * databaseConfig, threading::Mutex * acceptMutex, const std::string & filename, const int backlog = 0) [private, pure virtual]
Implemented in queryserver::QueryServer, inspectorserver::InspectorServer, and suggestserver::SuggestServer.
virtual void fastcgiserver::FastCGIServer::RegisterConfig () [inline, private, virtual]
Reimplemented in queryserver::QueryServer, inspectorserver::InspectorServer, and suggestserver::SuggestServer.
Definition at line 68 of file FastCGIServer.h.
virtual bool fastcgiserver::FastCGIServer::InitConfig () [inline, private, virtual]
Reimplemented in queryserver::QueryServer, inspectorserver::InspectorServer, and suggestserver::SuggestServer.
Definition at line 69 of file FastCGIServer.h.
Referenced by StartServer().
void fastcgiserver::FastCGIServer::RegisterSocketConfig () [private]
Definition at line 166 of file FastCGIServer.cpp.
References config, and bot::ConfigManager::RegisterParam().
Referenced by StartServer().
bool fastcgiserver::FastCGIServer::InitSocketConfig () [private]
Definition at line 176 of file FastCGIServer.cpp.
References basePort, config, bot::ConfigManager::GetValue(), and threadCount.
Referenced by StartServer().
void fastcgiserver::FastCGIServer::RegisterLoggingParams () [private]
Definition at line 97 of file FastCGIServer.cpp.
References config, and bot::ConfigManager::RegisterParam().
Referenced by StartServer().
void fastcgiserver::FastCGIServer::InitLoggingConfig () [private]
Definition at line 109 of file FastCGIServer.cpp.
References config, databaseConfig, bot::ConfigManager::GetValue(), logging, log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, log::Logging::LOGLEVEL_TRACE, log::Logging::LOGLEVEL_WARN, log::FileLogging::SetAppend(), log::FileLogging::SetFileName(), log::FileLogging::SetFlush(), and log::Logging::SetLogLevel().
Referenced by StartServer().
void fastcgiserver::FastCGIServer::RegisterDatabaseConfigParams (void) [private]
Definition at line 196 of file FastCGIServer.cpp.
References config, bot::ConfigManager::RegisterParam(), requestXSD, and responseXSD.
Referenced by StartServer().
bool fastcgiserver::FastCGIServer::InitDatabaseConfigs (void) [private]
Definition at line 210 of file FastCGIServer.cpp.
References affixFile, config, database::DatabaseHelper::Connection(), database::DatabaseHelper::CreateConnection(), databaseConfig, dbHelper, database::DatabaseHelper::DestroyConnection(), dictionaryFile, bot::ConfigManager::GetValue(), htmlparser::TLD::InitTLDCache(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_WARN, tools::FileTools::ReadFile(), requestXSD, responseXSD, database::DatabaseConfig::SetDatabaseName(), database::DatabaseConfig::SetHost(), database::DatabaseConfig::SetPass(), database::DatabaseConfig::SetPort(), database::DatabaseConfig::SetUser(), xsdRequestContent, and xsdResponseContent.
Referenced by StartServer().
Member Data Documentation
bot::ConfigManager fastcgiserver::FastCGIServer::config [protected]
server configuration.
Definition at line 84 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs(), InitLoggingConfig(), InitSocketConfig(), RegisterDatabaseConfigParams(), RegisterLoggingParams(), RegisterSocketConfig(), and StartServer().
database::DatabaseConfig* fastcgiserver::FastCGIServer::databaseConfig [protected]
database configuration.
Definition at line 89 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs(), InitLoggingConfig(), and StartServer().
log::Logging* fastcgiserver::FastCGIServer::logging [protected]
logging.
Definition at line 94 of file FastCGIServer.h.
Referenced by InitLoggingConfig().
std::string fastcgiserver::FastCGIServer::xsdRequestContent [protected]
xsd for requests.
Definition at line 99 of file FastCGIServer.h.
Referenced by queryserver::QueryServer::CreateThreadPort(), queryserver::QueryServer::CreateThreadSocket(), and InitDatabaseConfigs().
std::string fastcgiserver::FastCGIServer::xsdResponseContent [protected]
xsd for responses.
Definition at line 104 of file FastCGIServer.h.
Referenced by queryserver::QueryServer::CreateThreadPort(), queryserver::QueryServer::CreateThreadSocket(), and InitDatabaseConfigs().
threading::Mutex fastcgiserver::FastCGIServer::acceptMutex [private]
Definition at line 107 of file FastCGIServer.h.
Referenced by StartServer().
std::vector<FastCGIServerThread*> fastcgiserver::FastCGIServer::threads [private]
Definition at line 108 of file FastCGIServer.h.
Referenced by StartServer(), and StopServer().
int fastcgiserver::FastCGIServer::basePort [private]
Definition at line 109 of file FastCGIServer.h.
Referenced by InitSocketConfig(), and StartServer().
int fastcgiserver::FastCGIServer::threadCount [private]
Definition at line 110 of file FastCGIServer.h.
Referenced by InitSocketConfig(), and StartServer().
std::string fastcgiserver::FastCGIServer::dictionaryFile [private]
Definition at line 111 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs(), and StartServer().
std::string fastcgiserver::FastCGIServer::affixFile [private]
Definition at line 112 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs(), and StartServer().
std::string fastcgiserver::FastCGIServer::requestXSD [private]
Definition at line 113 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs(), and RegisterDatabaseConfigParams().
std::string fastcgiserver::FastCGIServer::responseXSD [private]
Definition at line 114 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs(), and RegisterDatabaseConfigParams().
database::DatabaseHelper fastcgiserver::FastCGIServer::dbHelper [private]
Definition at line 116 of file FastCGIServer.h.
Referenced by InitDatabaseConfigs().
The documentation for this class was generated from the following files:
FastCGIServer/src/FastCGIServer.h
FastCGIServer/src/FastCGIServer.cpp