DeepNet: domparser::NodeIterator Class Reference
domparser::NodeIterator Class Reference
#include <NodeIterator.h>
Public Member Functions
virtual ~NodeIterator ()
Node * nextNode ()
Node * previousNode ()
void detach ()
Node * GetReferenceNode ()
bool IsPointerBeforeReferenceNode () const
Node * GetRoot ()
NodeFilter::Type GetWhatToShow () const
const NodeFilter * GetFilter () const
Protected Member Functions
NodeFilter::Result FilterNode (Node *node)
Protected Attributes
Node * root
NodeFilter::Type whatToShow
tools::Pointer< NodeFilter > filter
bool activeFlag
Private Types
enum Direction { NEXT, PREVIOUS }
Private Member Functions
NodeIterator (Node *root, NodeFilter::Type whatToShow, NodeFilter *filter)
Node * Traverse (const Direction dir)
Node * TraverseNext (Node *node, bool &beforeNode)
Node * TraversePrevious (Node *node, bool &beforeNode)
Node * TraverseSubstep (const Direction dir, Node *node, bool &beforeNode)
Private Attributes
Node * referenceNode
bool pointerBeforeReferenceNode
Friends
class Document
Detailed Description
Definition at line 19 of file NodeIterator.h.
Member Enumeration Documentation
enum domparser::NodeIterator::Direction [private]
Enumerator:
NEXT
PREVIOUS
Definition at line 23 of file NodeIterator.h.
Constructor & Destructor Documentation
domparser::NodeIterator::NodeIterator (Node * root, NodeFilter::Type whatToShow, NodeFilter * filter) [private]
Definition at line 15 of file NodeIterator.cpp.
domparser::NodeIterator::~NodeIterator () [virtual]
Definition at line 21 of file NodeIterator.cpp.
Member Function Documentation
Node* domparser::NodeIterator::nextNode () [inline]
Definition at line 34 of file NodeIterator.h.
References NEXT, and Traverse().
Referenced by domparser::Node::compareDocumentPosition(), and domparser::TreeWalker::NextNodeSubstep().
Node* domparser::NodeIterator::previousNode () [inline]
Definition at line 35 of file NodeIterator.h.
References PREVIOUS, and Traverse().
void domparser::NodeIterator::detach () [inline]
Definition at line 37 of file NodeIterator.h.
Node* domparser::NodeIterator::GetReferenceNode () [inline]
Definition at line 39 of file NodeIterator.h.
References referenceNode.
bool domparser::NodeIterator::IsPointerBeforeReferenceNode () const [inline]
Definition at line 40 of file NodeIterator.h.
References pointerBeforeReferenceNode.
Node * domparser::NodeIterator::Traverse (const Direction dir) [private]
Definition at line 24 of file NodeIterator.cpp.
References pointerBeforeReferenceNode, referenceNode, and TraverseSubstep().
Referenced by nextNode(), and previousNode().
Node * domparser::NodeIterator::TraverseNext (Node * node, bool & beforeNode) [private]
Definition at line 36 of file NodeIterator.cpp.
Referenced by TraverseSubstep().
Node * domparser::NodeIterator::TraversePrevious (Node * node, bool & beforeNode) [private]
Definition at line 47 of file NodeIterator.cpp.
Referenced by TraverseSubstep().
Node * domparser::NodeIterator::TraverseSubstep (const Direction dir, Node * node, bool & beforeNode) [private]
Definition at line 58 of file NodeIterator.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, domparser::Traverser::FilterNode(), NEXT, PREVIOUS, TraverseNext(), and TraversePrevious().
Referenced by Traverse().
Node* domparser::Traverser::GetRoot () [inline, inherited]
Definition at line 31 of file Traverser.h.
References domparser::Traverser::root.
Referenced by domparser::TreeWalker::parentNode(), domparser::TreeWalker::previousNode(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), domparser::TreeWalker::TraverseSiblings(), and domparser::TreeWalker::TraverseSiblingsSubstep().
NodeFilter::Type domparser::Traverser::GetWhatToShow () const [inline, inherited]
Definition at line 32 of file Traverser.h.
References domparser::Traverser::whatToShow.
const NodeFilter* domparser::Traverser::GetFilter () const [inline, inherited]
Definition at line 33 of file Traverser.h.
References domparser::Traverser::filter.
NodeFilter::Result domparser::Traverser::FilterNode (Node * node) [protected, inherited]
Definition at line 29 of file Traverser.cpp.
References domparser::Traverser::activeFlag, domparser::Traverser::filter, domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_SKIP, domparser::Node::GetNodeType(), tools::Pointer< T >::IsNull(), and domparser::Traverser::whatToShow.
Referenced by domparser::TreeWalker::NextNodeSubstep(), domparser::TreeWalker::parentNode(), domparser::TreeWalker::previousNode(), domparser::TreeWalker::TraverseChildrenSubstep(), domparser::TreeWalker::TraverseSiblingsInnerSubstep(), domparser::TreeWalker::TraverseSiblingsSubstep(), and TraverseSubstep().
Friends And Related Function Documentation
friend class Document [friend]
Definition at line 20 of file NodeIterator.h.
Member Data Documentation
Node* domparser::NodeIterator::referenceNode [private]
Definition at line 49 of file NodeIterator.h.
Referenced by GetReferenceNode(), and Traverse().
bool domparser::NodeIterator::pointerBeforeReferenceNode [private]
Definition at line 50 of file NodeIterator.h.
Referenced by IsPointerBeforeReferenceNode(), and Traverse().
Node* domparser::Traverser::root [protected, inherited]
Definition at line 39 of file Traverser.h.
Referenced by domparser::Traverser::GetRoot(), and domparser::TreeWalker::NextNodeSubstep().
NodeFilter::Type domparser::Traverser::whatToShow [protected, inherited]
Definition at line 40 of file Traverser.h.
Referenced by domparser::Traverser::FilterNode(), and domparser::Traverser::GetWhatToShow().
tools::Pointer<NodeFilter> domparser::Traverser::filter [protected, inherited]
Definition at line 41 of file Traverser.h.
Referenced by domparser::Traverser::FilterNode(), and domparser::Traverser::GetFilter().
bool domparser::Traverser::activeFlag [protected, inherited]
Definition at line 42 of file Traverser.h.
Referenced by domparser::Traverser::FilterNode().
The documentation for this class was generated from the following files:
DOMParser/src/NodeIterator.h
DOMParser/src/NodeIterator.cpp