DeepNet: domparser::DOMParser Class Reference
domparser::DOMParser Class Reference
#include <DOMParser.h>
Public Member Functions
DOMParser ()
virtual ~DOMParser ()
virtual bool Parse (const htmlparser::DatabaseUrl &url, const network::HtmlData &html, tools::Pointer< htmlparser::IHtmlParserResult > &result)
parses html and generates content result
Detailed Description
Definition at line 19 of file DOMParser.h.
Constructor & Destructor Documentation
domparser::DOMParser::DOMParser ()
Definition at line 20 of file DOMParser.cpp.
domparser::DOMParser::~DOMParser () [virtual]
Definition at line 23 of file DOMParser.cpp.
Member Function Documentation
bool domparser::DOMParser::Parse (const htmlparser::DatabaseUrl & url, const network::HtmlData & html, tools::Pointer< htmlparser::IHtmlParserResult > & result) [virtual]
parses html and generates content result
Parameters:
url url of html
html html to parse
result result containing content and info for html documents
Returns:
true if successful, false if unsuccessful
Implements htmlparser::IHtmlParser.
Definition at line 26 of file DOMParser.cpp.
References errors::Exception::DisableLogging(), domparser::DocumentFactory::FromHtmlData(), log::Logging::IsLogLevelTrace(), tools::Pointer< T >::IsNull(), and tools::Pointer< T >::Set().
The documentation for this class was generated from the following files:
DOMParser/src/DOMParser.h
DOMParser/src/DOMParser.cpp