DeepNet: indexing::IIndexerFactory Class Reference
indexing::IIndexerFactory Class Reference
factory class for IIndexer interfaces
#include <IIndexerFactory.h>
Public Types
enum IndexerType { FLEX_GENERIC, OWN_GENERIC, FLEX_DATAMINING, MAX_INDEXER_TYPE }
Public Member Functions
virtual ~IIndexerFactory ()
Static Public Member Functions
static bool CreateInstance (database::DatabaseConnection *db, const IndexerType &type, tools::Pointer< IIndexer > &indexer)
creates an instance of an IIndexer
Private Member Functions
IIndexerFactory ()
Detailed Description
factory class for IIndexer interfaces
See also:
indexing::IIndexer
Definition at line 25 of file IIndexerFactory.h.
Member Enumeration Documentation
enum indexing::IIndexerFactory::IndexerType
Enumerator:
FLEX_GENERIC
generic parser based on flex
OWN_GENERIC
own implementation of a simple parser
FLEX_DATAMINING
datamining parser based on flex
MAX_INDEXER_TYPE
do not use
Definition at line 30 of file IIndexerFactory.h.
Constructor & Destructor Documentation
indexing::IIndexerFactory::IIndexerFactory () [private]
Definition at line 17 of file IIndexerFactory.cpp.
indexing::IIndexerFactory::~IIndexerFactory () [virtual]
Definition at line 20 of file IIndexerFactory.cpp.
Member Function Documentation
bool indexing::IIndexerFactory::CreateInstance (database::DatabaseConnection * db, const IndexerType & type, tools::Pointer< IIndexer > & indexer) [static]
creates an instance of an IIndexer
Parameters:
db database connection
type indexer type
indexer created indexer
Returns:
true if successful, false if unsuccessful
Definition at line 23 of file IIndexerFactory.cpp.
References indexing::IndexerBase::BODY_CONTENT, FLEX_DATAMINING, FLEX_GENERIC, OWN_GENERIC, and tools::Pointer< T >::Set().
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile(), indexing::DataminingIndexerThread::OnCreateIndexer(), indexing::GenericWebIndexerThread::OnCreateIndexer(), and indexing::IndexerTester::Parse().
The documentation for this class was generated from the following files:
Indexer/src/IIndexerFactory.h
Indexer/src/IIndexerFactory.cpp