DeepNet: database::MySQLConnection Class Reference
database::MySQLConnection Class Reference
implementation of database::DatabaseConnection for MySQL servers
#include <MySQLConnection.h>
Public Member Functions
MySQLConnection (const bool logQuery=false)
virtual ~MySQLConnection ()
virtual bool Connect (DatabaseConfig *dbConfig)
connects to a database.
virtual bool Disconnect (void)
disconnect from database.
virtual bool Connected (void)
checks if database connection is established.
virtual void Insert (const InsertStatement &stmt)
execute an insert statement.
virtual void InsertOrUpdate (const InsertOrUpdateStatement &stmt)
execute an insert or update statement.
virtual void Update (const UpdateStatement &stmt)
execute an update statement.
virtual void Select (const SelectStatement &stmt, std::vector< TableBase * > &results)
execute select statement.
virtual void Delete (const DeleteStatement &stmt)
execute delete statement.
virtual void TransactionStart (void)
start a transaction.
virtual void TransactionCommit (void)
commits a transaction.
virtual void TransactionRollback (void)
does a transaction rollback.
virtual bool LastInsertID (long long &lastInsertID)
gets last inserted id.
virtual bool AffectedRows (long long &affectedRows)
gets the number of affected rows from last statement.
virtual bool EscapeString (std::string &inEscape)
escapes a sql string in place.
virtual void Initialize ()
called for global initialization, once per runtime.
virtual void Shutdown ()
called for global shutdown
void Select (const SelectStatement &stmt, SelectResultContainer< TableBase > &results)
execute select statements putting results into container.
template<class T >
void Select (const SelectStatement &stmt, SelectResultContainer< T > &results)
execute select statements putting results into container of type T.
const DatabaseType & GetDatabaseType (void) const
gets the database type of this connection.
Protected Member Functions
virtual void Query (const std::string &query, std::vector< TableBase * > &results)
execute an sql query.
virtual void Execute (const std::string &query)
executing an sql statement without fetching results.
Protected Attributes
bool logQuery
Private Member Functions
void Execute (const std::string &query, bool doRetry)
Private Attributes
MYSQL * mysqlConnection
MySQLDatabaseConfig * config
Detailed Description
implementation of database::DatabaseConnection for MySQL servers
Definition at line 32 of file MySQLConnection.h.
Constructor & Destructor Documentation
database::MySQLConnection::MySQLConnection (const bool logQuery = false)
Definition at line 34 of file MySQLConnection.cpp.
References THROW_EXCEPTION.
database::MySQLConnection::~MySQLConnection () [virtual]
Definition at line 44 of file MySQLConnection.cpp.
References Disconnect(), and mysqlConnection.
Member Function Documentation
bool database::MySQLConnection::Connect (DatabaseConfig * config) [virtual]
connects to a database.
Parameters:
config database config.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 51 of file MySQLConnection.cpp.
References config, Disconnect(), database::DatabaseConfig::GetDatabaseName(), database::DatabaseConfig::GetHost(), database::DatabaseConfig::GetPass(), database::DatabaseConfig::GetPort(), database::DatabaseConfig::GetUser(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, log::Logging::LOGLEVEL_INFO, log::Logging::LOGLEVEL_WARN, and mysqlConnection.
bool database::MySQLConnection::Disconnect (void) [virtual]
disconnect from database.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 95 of file MySQLConnection.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_INFO, and mysqlConnection.
Referenced by Connect(), and ~MySQLConnection().
bool database::MySQLConnection::Connected (void) [virtual]
checks if database connection is established.
Returns:
false if not established, true if established.
Implements database::DatabaseConnection.
Definition at line 105 of file MySQLConnection.cpp.
References mysqlConnection.
void database::MySQLConnection::Query (const std::string & query, std::vector< TableBase * > & results) [protected, virtual]
execute an sql query.
Parameters:
query sql statement.
results gets filled with results.
Implements database::DatabaseConnection.
Definition at line 112 of file MySQLConnection.cpp.
References database::MySQLTableBase::CreateInstance(), Execute(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, mysqlConnection, and THROW_EXCEPTION.
Referenced by Select().
void database::MySQLConnection::Execute (const std::string & query) [protected, virtual]
executing an sql statement without fetching results.
Parameters:
query sql statement.
Implements database::DatabaseConnection.
Definition at line 184 of file MySQLConnection.cpp.
Referenced by Delete(), Execute(), Insert(), InsertOrUpdate(), Query(), TransactionCommit(), TransactionRollback(), TransactionStart(), and Update().
void database::MySQLConnection::Insert (const InsertStatement & stmt) [virtual]
execute an insert statement.
Parameters:
stmt insert statement.
Implements database::DatabaseConnection.
Definition at line 189 of file MySQLConnection.cpp.
References Execute(), and database::MySQLInsertStatement::ToSQL().
void database::MySQLConnection::InsertOrUpdate (const InsertOrUpdateStatement & stmt) [virtual]
execute an insert or update statement.
Parameters:
stmt insert or update statement.
Implements database::DatabaseConnection.
Definition at line 195 of file MySQLConnection.cpp.
References Execute(), and database::MySQLInsertOrUpdateStatement::ToSQL().
void database::MySQLConnection::Update (const UpdateStatement & stmt) [virtual]
execute an update statement.
Parameters:
stmt update statement.
Implements database::DatabaseConnection.
Definition at line 201 of file MySQLConnection.cpp.
References Execute(), and database::MySQLUpdateStatement::ToSQL().
void database::MySQLConnection::Select (const SelectStatement & stmt, std::vector< TableBase * > & results) [virtual]
execute select statement.
Parameters:
stmt select statement.
results gets filled with results.
Implements database::DatabaseConnection.
Definition at line 207 of file MySQLConnection.cpp.
References Query(), and database::MySQLSelectStatement::ToSQL().
void database::MySQLConnection::Delete (const DeleteStatement & stmt) [virtual]
execute delete statement.
Parameters:
stmt delete statement
Implements database::DatabaseConnection.
Definition at line 213 of file MySQLConnection.cpp.
References Execute(), and database::DeleteStatement::ToSQL().
void database::MySQLConnection::TransactionStart (void) [virtual]
start a transaction.
Implements database::DatabaseConnection.
Definition at line 218 of file MySQLConnection.cpp.
References Execute(), and mysqlConnection.
void database::MySQLConnection::TransactionCommit (void) [virtual]
commits a transaction.
Implements database::DatabaseConnection.
Definition at line 224 of file MySQLConnection.cpp.
References Execute(), and mysqlConnection.
void database::MySQLConnection::TransactionRollback (void) [virtual]
does a transaction rollback.
Implements database::DatabaseConnection.
Definition at line 236 of file MySQLConnection.cpp.
References Execute(), and mysqlConnection.
bool database::MySQLConnection::LastInsertID (long long & lastInsertID) [virtual]
gets last inserted id.
Parameters:
lastInsertID gets filled with last inserted id.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 248 of file MySQLConnection.cpp.
References mysqlConnection.
bool database::MySQLConnection::AffectedRows (long long & affectedRows) [virtual]
gets the number of affected rows from last statement.
Parameters:
affectedRows number of affected rows.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 254 of file MySQLConnection.cpp.
References mysqlConnection.
bool database::MySQLConnection::EscapeString (std::string & inEscape) [virtual]
escapes a sql string in place.
Parameters:
inEscape string to be escaped.
Returns:
false on error, true on success.
Implements database::DatabaseConnection.
Definition at line 260 of file MySQLConnection.cpp.
References mysqlConnection.
void database::MySQLConnection::Initialize () [virtual]
called for global initialization, once per runtime.
Reimplemented from database::DatabaseConnection.
Definition at line 274 of file MySQLConnection.cpp.
References log::Logging::IsLogLevelTrace(), and log::Logging::LogTrace().
void database::MySQLConnection::Shutdown () [virtual]
called for global shutdown
Reimplemented from database::DatabaseConnection.
Definition at line 282 of file MySQLConnection.cpp.
void database::MySQLConnection::Execute (const std::string & query, bool doRetry) [private]
Definition at line 141 of file MySQLConnection.cpp.
References Execute(), log::Logging::GetLogLevel(), log::Logging::Log(), log::Logging::LOGLEVEL_WARN, database::DatabaseConnection::logQuery, mysqlConnection, and THROW_EXCEPTION.
void database::DatabaseConnection::Select (const SelectStatement & stmt, SelectResultContainer< TableBase > & results) [inline, inherited]
execute select statements putting results into container.
Parameters:
stmt select statement.
results result container.
Definition at line 173 of file DatabaseConnection.h.
References tools::PointerContainer< T >::Add(), and database::DatabaseConnection::Select().
template<class T > void database::DatabaseConnection::Select (const SelectStatement & stmt, SelectResultContainer< T > & results) [inline, inherited]
execute select statements putting results into container of type T.
type T should be derived from database::TableBase.
Parameters:
stmt select statement.
results result container.
Definition at line 190 of file DatabaseConnection.h.
References tools::PointerContainer< T >::Add(), and database::DatabaseConnection::Select().
const DatabaseType& database::DatabaseConnection::GetDatabaseType (void) const [inline, inherited]
gets the database type of this connection.
Returns:
database type.
Definition at line 165 of file DatabaseConnection.h.
References database::DatabaseConnection::databaseType.
Member Data Documentation
MYSQL* database::MySQLConnection::mysqlConnection [private]
Definition at line 69 of file MySQLConnection.h.
Referenced by AffectedRows(), Connect(), Connected(), Disconnect(), EscapeString(), Execute(), LastInsertID(), Query(), TransactionCommit(), TransactionRollback(), TransactionStart(), and ~MySQLConnection().
MySQLDatabaseConfig* database::MySQLConnection::config [private]
Definition at line 70 of file MySQLConnection.h.
Referenced by Connect().
bool database::DatabaseConnection::logQuery [protected, inherited]
Definition at line 208 of file DatabaseConnection.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
Database/MySQL/MySQLConnection.h
Database/MySQL/MySQLConnection.cpp