DeepNet: database::InsertOrUpdateStatement Class Reference
database::InsertOrUpdateStatement Class Reference
implements generic sql insert or update statement.
#include <InsertOrUpdateStatement.h>
Public Types
enum StatementType {
INSERT_STMT, INSERT_OR_UPDATE_STMT, UPDATE_STMT, SELECT_STMT,
DELETE_STMT
}
type of sql statement.
Public Member Functions
InsertOrUpdateStatement (TableBase *tableBase)
construct with existing table.
virtual ~InsertOrUpdateStatement ()
void AddSumUpColumn (TableColumnDefinition *colDef)
set values for certain columns to be summed up instead of replacing the old value.
void AddSumUpColumns (std::vector< TableColumnDefinition * > colDefs)
set values for mulitple columns to be summed up instead of replacing the old value.
virtual InnerJoinCondition & InnerJoin ()
gets inner join condition for this statement.
virtual std::string ToSQL (DatabaseConnection *db) const
gets sql equivalent of this statement.
const TableBase * GetConstTableBase () const
const std::string & TableAlias (void) const
gets table alias of this statement's table.
const std::string & TableName (void) const
gets table name of this statement's table.
const std::string & DatabaseName (void) const
gets database name of this statement's table.
void SetLimit (unsigned int limit)
sets the LIMIT part of the sql statement
Public Attributes
std::vector
< TableColumnDefinition * > sumColumns
Protected Member Functions
std::string GetFullQualifiedTableName () const
gets the fully qualified name of this statement's table.
Protected Attributes
const TableBase * tableBase
TableDefinition * tableDefinition
definition of this statement's table.
std::string tableAlias
table alias, empty if disabled.
unsigned int limit
maximum number of rows returned
StatementType typeStmt
type of this statement.
Detailed Description
implements generic sql insert or update statement.
See also:
database::MySQLInsertOrUpdateStatement
database::DB2InsertOrUpdateStatement
Definition at line 25 of file InsertOrUpdateStatement.h.
Member Enumeration Documentation
enum database::Statement::StatementType [inherited]
type of sql statement.
Enumerator:
INSERT_STMT
insert statement.
See also:
database::InsertStatement
INSERT_OR_UPDATE_STMT
insert or update (if duplicate).
See also:
database::InsertOrUpdateStatement
UPDATE_STMT
update statement.
See also:
database::UpdateStatement
SELECT_STMT
select statement.
See also:
database::SelectStatement
DELETE_STMT
delete statement.
See also:
database::DeleteStatement
Definition at line 28 of file Statement.h.
Constructor & Destructor Documentation
database::InsertOrUpdateStatement::InsertOrUpdateStatement (TableBase * tableBase)
construct with existing table.
values of existing table are inserted or replaced replaced.
Parameters:
tableBase existing table.
Definition at line 17 of file InsertOrUpdateStatement.cpp.
References database::Statement::INSERT_OR_UPDATE_STMT, and database::Statement::typeStmt.
database::InsertOrUpdateStatement::~InsertOrUpdateStatement () [virtual]
Definition at line 23 of file InsertOrUpdateStatement.cpp.
References sumColumns.
Member Function Documentation
void database::InsertOrUpdateStatement::AddSumUpColumn (TableColumnDefinition * colDef)
set values for certain columns to be summed up instead of replacing the old value.
Parameters:
colDef column definition for column to be summed up.
Definition at line 35 of file InsertOrUpdateStatement.cpp.
References sumColumns.
Referenced by database::TableBase::InsertOrUpdate().
void database::InsertOrUpdateStatement::AddSumUpColumns (std::vector< TableColumnDefinition * > colDefs)
set values for mulitple columns to be summed up instead of replacing the old value.
Parameters:
colDefs list of column definitions for columns to be summed up.
Definition at line 40 of file InsertOrUpdateStatement.cpp.
References sumColumns.
Referenced by database::TableBase::InsertOrUpdate().
InnerJoinCondition & database::InsertOrUpdateStatement::InnerJoin () [virtual]
gets inner join condition for this statement.
Returns:
inner join condition.
Reimplemented from database::InsertStatement.
Definition at line 45 of file InsertOrUpdateStatement.cpp.
References THROW_EXCEPTION.
std::string database::InsertOrUpdateStatement::ToSQL (DatabaseConnection * db) const [virtual]
gets sql equivalent of this statement.
Parameters:
db database connection.
Returns:
sql string.
Reimplemented from database::InsertStatement.
Definition at line 30 of file InsertOrUpdateStatement.cpp.
References THROW_EXCEPTION.
const TableBase* database::InsertStatement::GetConstTableBase () const [inline, inherited]
Definition at line 40 of file InsertStatement.h.
References database::InsertStatement::tableBase.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL().
const std::string & database::Statement::TableAlias (void) const [inherited]
gets table alias of this statement's table.
Returns:
empty if no alias specified, otherwise alias name for this statement's table.
Definition at line 73 of file Statement.cpp.
References database::Statement::tableAlias.
Referenced by database::SelectStatement::SelectAllColumns(), database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), and database::UpdateStatement::ToSQL().
const std::string & database::Statement::TableName (void) const [inherited]
gets table name of this statement's table.
Returns:
table name.
Definition at line 53 of file Statement.cpp.
References database::Statement::tableDefinition, and database::TableDefinition::TableName().
const std::string & database::Statement::DatabaseName (void) const [inherited]
gets database name of this statement's table.
Returns:
database name.
Definition at line 58 of file Statement.cpp.
References database::TableDefinition::DatabaseName(), and database::Statement::tableDefinition.
void database::Statement::SetLimit (unsigned int limit) [inherited]
sets the LIMIT part of the sql statement
Parameters:
limit maximum number of returned rows (0 to disable).
Definition at line 68 of file Statement.cpp.
References database::Statement::limit.
Referenced by caching::CacheDatabaseUrl::GetBySecondLevelIDSubdomainID(), and database::TableBase::Update().
std::string database::Statement::GetFullQualifiedTableName () const [protected, inherited]
gets the fully qualified name of this statement's table.
i.e. database_name.table_name.
Returns:
fully qualified name.
Definition at line 63 of file Statement.cpp.
References database::TableDefinition::GetFullQualifiedTableName(), and database::Statement::tableDefinition.
Referenced by database::InsertStatement::ToSQL(), database::DeleteStatement::ToSQL(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
Member Data Documentation
std::vector< TableColumnDefinition* > database::InsertOrUpdateStatement::sumColumns
Definition at line 54 of file InsertOrUpdateStatement.h.
Referenced by AddSumUpColumn(), AddSumUpColumns(), database::MySQLInsertOrUpdateStatement::IsSumColumn(), database::MySQLInsertOrUpdateStatement::ToSQL(), and ~InsertOrUpdateStatement().
const TableBase* database::InsertStatement::tableBase [protected, inherited]
Definition at line 43 of file InsertStatement.h.
Referenced by database::InsertStatement::GetConstTableBase(), and database::InsertStatement::ToSQL().
TableDefinition* database::Statement::tableDefinition [protected, inherited]
definition of this statement's table.
Definition at line 141 of file Statement.h.
Referenced by database::Statement::DatabaseName(), database::Statement::GetFullQualifiedTableName(), database::SelectStatement::SelectAllColumns(), database::Statement::TableName(), and database::Statement::~Statement().
std::string database::Statement::tableAlias [protected, inherited]
table alias, empty if disabled.
Definition at line 146 of file Statement.h.
Referenced by database::SelectStatement::SelectAddColumn(), database::SelectStatement::SelectAddCountColumn(), database::Statement::TableAlias(), and database::SelectStatement::ToSQL().
unsigned int database::Statement::limit [protected, inherited]
maximum number of rows returned
See also:
database::Statement::SetLimit
Definition at line 152 of file Statement.h.
Referenced by database::Statement::SetLimit(), database::UpdateStatement::ToSQL(), and database::SelectStatement::ToSQL().
StatementType database::Statement::typeStmt [protected, inherited]
type of this statement.
Definition at line 157 of file Statement.h.
Referenced by InsertOrUpdateStatement().
The documentation for this class was generated from the following files:
Database/src/InsertOrUpdateStatement.h
Database/src/InsertOrUpdateStatement.cpp