DeepNet: network::IHttpClient Class Reference
network::IHttpClient Class Reference
interface class for all http clients To instantiate use network::HttpClientFactory only
#include <IHttpClient.h>
Public Member Functions
virtual ~IHttpClient ()
virtual bool Get (const HttpUrl &url, HttpResponse &response)=0
performs http get request
virtual HttpClientSettings & Settings ()=0
returns settings of this http client
Protected Member Functions
IHttpClient ()
Detailed Description
interface class for all http clients To instantiate use network::HttpClientFactory only
Definition at line 22 of file IHttpClient.h.
Constructor & Destructor Documentation
network::IHttpClient::IHttpClient () [inline, protected]
Definition at line 25 of file IHttpClient.h.
virtual network::IHttpClient::~IHttpClient () [inline, virtual]
Definition at line 28 of file IHttpClient.h.
Member Function Documentation
virtual bool network::IHttpClient::Get (const HttpUrl & url, HttpResponse & response) [pure virtual]
performs http get request
Parameters:
url url to "GET"
response response of http GET
Returns:
true if successful, false if unsuccessful
Implemented in network::HttpClientCURL.
Referenced by caching::CacheRobotsTxt::DownloadRobotsTxt(), and inspectorserver::InspectorServerResponse::Process().
virtual HttpClientSettings& network::IHttpClient::Settings () [pure virtual]
returns settings of this http client
Returns:
settings of this http client
Implemented in network::HttpClientCURL.
Referenced by inspectorserver::InspectorServerResponse::Process().
The documentation for this class was generated from the following file:
Networking/src/IHttpClient.h