DeepNet: toolbot::DeepNetToolBot Class Reference
toolbot::DeepNetToolBot Class Reference
#include <DeepNetToolBot.h>
Public Member Functions
DeepNetToolBot ()
virtual ~DeepNetToolBot ()
bool Run (int argc, char **argv)
this function starts the application.
virtual void OnException (errors::Exception &ex)
this function is called when an uncaught exception derived from errors::Exception occurs.
virtual void OnException ()
this function is called when an uncaught exception occurs.
Protected Member Functions
virtual bool OnPreInit ()
called after registration of default parameters and before initialization.
virtual bool OnInit ()
called after bot configuration and initialization has completed.
virtual bool OnRun ()
called when all initialization is completed and the applications starts running.
virtual bool OnShutdown ()
called before the application is shutting down.
ConfigManager & Config ()
gets the configuration of this bot::Bot.
database::DatabaseHelper & DB ()
gets the database of this bot::Bot.
Protected Attributes
volatile bool shutdownReceived
true if application shall end.
database::DatabaseConfig * dbConfig
database configuration.
Private Member Functions
void RegisterRobotTxtParams ()
void RegisterDatabaseRepairParams ()
void RegisterUrlInserterParams ()
void RegisterHtmlTestParams ()
void RegisterCommerceSearchParams ()
void RegisterDataminingParams ()
void RegisterPCRERegexTestParams ()
void RegisterHtmlClientCURLParams ()
void RegisterHtmlDocumentFactoryParams ()
void RegisterIndexerExParams ()
bool ProcessUnitTests ()
Detailed Description
Definition at line 14 of file DeepNetToolBot.h.
Constructor & Destructor Documentation
toolbot::DeepNetToolBot::DeepNetToolBot ()
Definition at line 41 of file DeepNetToolBot.cpp.
toolbot::DeepNetToolBot::~DeepNetToolBot () [virtual]
Definition at line 45 of file DeepNetToolBot.cpp.
Member Function Documentation
bool toolbot::DeepNetToolBot::OnPreInit (void) [protected, virtual]
called after registration of default parameters and before initialization.
usually used to register application specific config parameters.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 151 of file DeepNetToolBot.cpp.
References RegisterCommerceSearchParams(), RegisterDatabaseRepairParams(), RegisterDataminingParams(), RegisterHtmlClientCURLParams(), RegisterHtmlDocumentFactoryParams(), RegisterHtmlTestParams(), RegisterIndexerExParams(), RegisterPCRERegexTestParams(), RegisterRobotTxtParams(), and RegisterUrlInserterParams().
bool toolbot::DeepNetToolBot::OnInit () [protected, virtual]
called after bot configuration and initialization has completed.
usually used to initialize application specific config parameters.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 48 of file DeepNetToolBot.cpp.
bool toolbot::DeepNetToolBot::OnRun () [protected, virtual]
called when all initialization is completed and the applications starts running.
when this function returns, the applications does NOT exit.
Returns:
false on error, true on success.
Implements bot::Bot.
Definition at line 53 of file DeepNetToolBot.cpp.
References toolbot::CommerceSearchTools::AddCustomer(), bot::Bot::Config(), bot::Bot::DB(), bot::DatabaseRepair::FixUncleanShutdown(), bot::ConfigManager::GetValue(), toolbot::DataMiningTools::InsertDataminingUser(), htmlparser::UrlInserter::InsertURL(), htmlparser::UrlInserter::InsertURLFile(), log::Logging::Log(), log::Logging::LogError(), log::Logging::LogInfo(), log::Logging::LOGLEVEL_INFO, ProcessUnitTests(), htmlparser::UrlInserter::ReadURLFile(), toolbot::DataMiningTools::RegisterDataminingAlert(), and bot::Bot::shutdownReceived.
bool toolbot::DeepNetToolBot::OnShutdown () [protected, virtual]
called before the application is shutting down.
Returns:
false on error, true on success.
Reimplemented from bot::Bot.
Definition at line 146 of file DeepNetToolBot.cpp.
References bot::Bot::DB(), and database::DatabaseHelper::DestroyConnection().
void toolbot::DeepNetToolBot::RegisterRobotTxtParams () [private]
Definition at line 208 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterDatabaseRepairParams () [private]
Definition at line 169 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterFlag().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterUrlInserterParams () [private]
Definition at line 178 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterHtmlTestParams () [private]
Definition at line 173 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterCommerceSearchParams () [private]
Definition at line 186 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterDataminingParams () [private]
Definition at line 194 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterPCRERegexTestParams () [private]
Definition at line 204 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterHtmlClientCURLParams () [private]
Definition at line 212 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterHtmlDocumentFactoryParams () [private]
Definition at line 217 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
void toolbot::DeepNetToolBot::RegisterIndexerExParams () [private]
Definition at line 221 of file DeepNetToolBot.cpp.
References bot::Bot::Config(), and bot::ConfigManager::RegisterParam().
Referenced by OnPreInit().
bool toolbot::DeepNetToolBot::ProcessUnitTests () [private]
Definition at line 225 of file DeepNetToolBot.cpp.
References toolbot::UnitTestManager::AddUnitTest(), bot::Bot::Config(), bot::Bot::DB(), bot::ConfigManager::GetValue(), network::HttpUrlParser::ParseURL(), and toolbot::UnitTestManager::Run().
Referenced by OnRun().
bool bot::Bot::Run (int argc, char ** argv) [inherited]
this function starts the application.
it returns when the application exits.
Parameters:
argc number of commandline arguments.
argv array of commandline arguments.
Returns:
false on error, true on success.
Definition at line 213 of file Bot.cpp.
References bot::Bot::Init(), errors::Exception::InitializeExceptionHandling(), bot::Bot::PostInit(), bot::Bot::PreInit(), bot::Bot::restartAfterShutdown, bot::Bot::Run(), and bot::Bot::Shutdown().
Referenced by main().
void bot::Bot::OnException (errors::Exception & ex) [virtual, inherited]
this function is called when an uncaught exception derived from errors::Exception occurs.
Parameters:
ex exception caught by application
Definition at line 396 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by main().
void bot::Bot::OnException () [virtual, inherited]
this function is called when an uncaught exception occurs.
exceptions derived from errors::Exception are caught separately.
See also:
bot::Bot::OnException(errors::Exception&)
Definition at line 401 of file Bot.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
ConfigManager& bot::Bot::Config () [inline, protected, inherited]
gets the configuration of this bot::Bot.
See also:
bot::ConfigManager
Returns:
associated bot::ConfigManager.
Definition at line 75 of file Bot.h.
References bot::Bot::configManager.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), bot::Bot::Init(), bot::Bot::InitCacheConfigParams(), workerbot::WorkerBot::InitCrawlerConfig(), bot::Bot::InitDatabaseConfigs(), workerbot::WorkerBot::InitIndexerConfigParams(), bot::Bot::InitLogging(), workerbot::WorkerBot::InitModeConfig(), workerbot::WorkerBot::InitParserConfig(), bot::Bot::InitPerformanceLoggingParams(), workerbot::WorkerBot::OnPreInit(), OnRun(), bot::Bot::PostInit(), ProcessUnitTests(), bot::Bot::RegisterCacheConfigParams(), RegisterCommerceSearchParams(), workerbot::WorkerBot::RegisterCrawlerConfigParams(), bot::Bot::RegisterDatabaseConfigParams(), RegisterDatabaseRepairParams(), RegisterDataminingParams(), bot::Bot::RegisterDefaultFlags(), bot::Bot::RegisterDefaultParams(), RegisterHtmlClientCURLParams(), RegisterHtmlDocumentFactoryParams(), RegisterHtmlTestParams(), workerbot::WorkerBot::RegisterIndexerConfigParams(), RegisterIndexerExParams(), workerbot::WorkerBot::RegisterModeSpecificParams(), workerbot::WorkerBot::RegisterParserConfigParams(), RegisterPCRERegexTestParams(), bot::Bot::RegisterPerformanceLoggingParams(), RegisterRobotTxtParams(), and RegisterUrlInserterParams().
database::DatabaseHelper& bot::Bot::DB () [inline, protected, inherited]
gets the database of this bot::Bot.
See also:
database::DatabaseHelper
Returns:
associated database::DatabaseHelper.
Definition at line 82 of file Bot.h.
References bot::Bot::databaseHelper.
Referenced by workerbot::WorkerBot::CheckCleanShutdown(), bot::Bot::InitCacheConfigParams(), bot::Bot::InitDatabaseConfigs(), OnRun(), OnShutdown(), ProcessUnitTests(), bot::Bot::Shutdown(), and bot::Bot::WatchDog().
Member Data Documentation
volatile bool bot::Bot::shutdownReceived [protected, inherited]
true if application shall end.
Definition at line 166 of file Bot.h.
Referenced by OnRun(), bot::Bot::Run(), and bot::Bot::SignalHandler().
database::DatabaseConfig* bot::Bot::dbConfig [protected, inherited]
database configuration.
Definition at line 171 of file Bot.h.
Referenced by bot::Bot::InitDatabaseConfigs(), bot::Bot::InitLogging(), workerbot::WorkerBot::OnRun(), and bot::Bot::Shutdown().
The documentation for this class was generated from the following files:
DeepNetTool/src/DeepNetToolBot.h
DeepNetTool/src/DeepNetToolBot.cpp