DeepNet: htmlparser::UrlInserter Class Reference
htmlparser::UrlInserter Class Reference
#include <UrlInserter.h>
Public Member Functions
virtual ~UrlInserter ()
Static Public Member Functions
static int ReadURLFile (const std::string &fileName, std::multimap< std::string, std::string > &fileContent)
static bool InsertURLFile (database::DatabaseConnection *db, const std::multimap< std::string, std::string > &fileContent)
static bool ValidateURLFile (database::DatabaseConnection *db, const std::multimap< std::string, std::string > &fileContent)
static DatabaseUrl ValidateURL (database::DatabaseConnection *db, const std::string &sDomain, const std::string &sUrl, bool dumpUrl=true)
static bool InsertURL (database::DatabaseConnection *db, const std::string &sDomain, const std::string &sUrl)
Private Member Functions
UrlInserter ()
Detailed Description
Definition at line 21 of file UrlInserter.h.
Constructor & Destructor Documentation
htmlparser::UrlInserter::UrlInserter () [private]
Definition at line 30 of file UrlInserter.cpp.
htmlparser::UrlInserter::~UrlInserter () [virtual]
Definition at line 34 of file UrlInserter.cpp.
Member Function Documentation
int htmlparser::UrlInserter::ReadURLFile (const std::string & fileName, std::multimap< std::string, std::string > & fileContent) [static]
Definition at line 111 of file UrlInserter.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::Regex::Match(), and tools::FileTools::ReadFile().
Referenced by toolbot::DeepNetToolBot::OnRun().
bool htmlparser::UrlInserter::InsertURLFile (database::DatabaseConnection * db, const std::multimap< std::string, std::string > & fileContent) [static]
Definition at line 38 of file UrlInserter.cpp.
References InsertURL(), log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by toolbot::DeepNetToolBot::OnRun().
bool htmlparser::UrlInserter::ValidateURLFile (database::DatabaseConnection * db, const std::multimap< std::string, std::string > & fileContent) [static]
Definition at line 48 of file UrlInserter.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_INFO, and ValidateURL().
DatabaseUrl htmlparser::UrlInserter::ValidateURL (database::DatabaseConnection * db, const std::string & sDomain, const std::string & sUrl, bool dumpUrl = true) [static]
Definition at line 63 of file UrlInserter.cpp.
References tools::Pointer< T >::Get(), caching::CacheDatabaseUrl::GetByUrlString(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, and log::Logging::LOGLEVEL_INFO.
Referenced by InsertURL(), and ValidateURLFile().
bool htmlparser::UrlInserter::InsertURL (database::DatabaseConnection * db, const std::string & sDomain, const std::string & sUrl) [static]
Definition at line 89 of file UrlInserter.cpp.
References tools::Pointer< T >::Get(), caching::CacheDatabaseUrl::GetByUrlString(), network::HttpUrl::GetFullUrl(), htmlparser::DatabaseUrl::GetUrlID(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, and ValidateURL().
Referenced by InsertURLFile(), and toolbot::DeepNetToolBot::OnRun().
The documentation for this class was generated from the following files:
HtmlParser/src/UrlInserter.h
HtmlParser/src/UrlInserter.cpp