DeepNet: tools::PerformanceCounter Class Reference
tools::PerformanceCounter Class Reference
precise time measurement class.
#include <PerformanceCounter.h>
Public Member Functions
PerformanceCounter ()
virtual ~PerformanceCounter ()
void Start (void)
start measurement.
double Stop (void)
stop measurement.
void Stop (timeval &duration)
stop measurement.
Static Public Member Functions
static void EnablePerformanceLog (const bool enable)
used to enable/disable PERFORMANCE_LOG_* macros at runtime
static bool IsPerformanceLogEnabled ()
checks if performance log is enabled
Private Attributes
timeval startval
timeval endval
Static Private Attributes
static bool enablePerformanceLog = true
Detailed Description
precise time measurement class.
use this class for measuring time in a high precision.
Definition at line 22 of file PerformanceCounter.h.
Constructor & Destructor Documentation
tools::PerformanceCounter::PerformanceCounter ()
Definition at line 16 of file PerformanceCounter.cpp.
tools::PerformanceCounter::~PerformanceCounter () [virtual]
Definition at line 20 of file PerformanceCounter.cpp.
Member Function Documentation
void tools::PerformanceCounter::Start (void)
start measurement.
Definition at line 24 of file PerformanceCounter.cpp.
References startval.
Referenced by workerbot::WorkerBot::OnShutdown().
double tools::PerformanceCounter::Stop (void)
stop measurement.
Returns:
duration (in seconds).
Definition at line 29 of file PerformanceCounter.cpp.
References endval, startval, and tools::TimeTools::TimevalSubtract().
Referenced by workerbot::WorkerBot::OnShutdown().
void tools::PerformanceCounter::Stop (timeval & duration)
stop measurement.
Parameters:
duration duration (in seconds).
Definition at line 40 of file PerformanceCounter.cpp.
References endval, startval, and tools::TimeTools::TimevalSubtract().
void tools::PerformanceCounter::EnablePerformanceLog (const bool enable) [static]
used to enable/disable PERFORMANCE_LOG_* macros at runtime
Parameters:
enable true to enable, false to disable
Definition at line 45 of file PerformanceCounter.cpp.
References enablePerformanceLog.
Referenced by bot::Bot::InitPerformanceLoggingParams().
bool tools::PerformanceCounter::IsPerformanceLogEnabled () [static]
checks if performance log is enabled
Returns:
true if enabled, false if disabled
Definition at line 49 of file PerformanceCounter.cpp.
References enablePerformanceLog.
Member Data Documentation
timeval tools::PerformanceCounter::startval [private]
Definition at line 59 of file PerformanceCounter.h.
Referenced by Start(), and Stop().
timeval tools::PerformanceCounter::endval [private]
Definition at line 60 of file PerformanceCounter.h.
Referenced by Stop().
bool tools::PerformanceCounter::enablePerformanceLog = true [static, private]
Definition at line 63 of file PerformanceCounter.h.
Referenced by EnablePerformanceLog(), and IsPerformanceLogEnabled().
The documentation for this class was generated from the following files:
Tools/src/PerformanceCounter.h
Tools/src/PerformanceCounter.cpp