DeepNet: domparser::Node Class Reference
domparser::Node Class Reference
basic implementation of a DOM compatible node
#include <Node.h>
Public Types
enum NodeType {
INVALID_NODE_TYPE, ELEMENT_NODE = 1, TEXT_NODE = 3, PROCESSING_INSTRUCTION_NODE = 7,
COMMENT_NODE = 8, DOCUMENT_NODE = 9, DOCUMENT_TYPE_NODE = 10, DOCUMENT_FRAGMENT_NODE = 11
}
specific type node
enum DocumentPosition {
DOCUMENT_POSITION_EQUAL = 0x00, DOCUMENT_POSITION_DISCONNECTED = 0x01, DOCUMENT_POSITION_PRECEDING = 0x02, DOCUMENT_POSITION_FOLLOWING = 0x04,
DOCUMENT_POSITION_CONTAINS = 0x08, DOCUMENT_POSITION_CONTAINED_BY = 0x10, DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC = 0x20
}
describes relationship of two nodes
Public Member Functions
virtual ~Node ()
bool hasChildNodes () const
checks if this node has child nodes
Node * insertBefore (Node *node, Node *child)
insert a node before another
Node * appendChild (Node *node)
appends node as a child to a certain node
Node * replaceChild (Node *node, Node *child)
replace a child node with another
Node * removeChild (Node *child)
removes a child node
void normalize ()
normalize DOM tree
Node * cloneNode (bool deep=true)
clones this node, optionally including all children
bool isEqualNode (Node *node)
compare two nodes for equality
DocumentPosition compareDocumentPosition (Node *other)
compares position of two DOM nodes
bool contains (Node *other)
checks if a node is a child node of this node
DOMStringPtr lookupPrefix (const DOMString &nameSpace)
DOMStringPtr lookupNamespaceURI (const DOMString &prefix)
bool isDefaultNamespace (const DOMString &nameSpace)
Node::NodeType GetNodeType () const
gets node type
DOMString GetNodeName () const
gets node name
NodeList & GetChildNodes ()
gets a list of child nodes
Node * GetParentNode ()
gets the parent node
Node * GetFirstChild ()
gets first child of this node
Node * GetLastChild ()
gets last child of this node
Node * GetPreviousSibling ()
gets previous sibling
Node * GetNextSibling ()
gets next sibling
Document * GetOwnerDocument ()
gets owning/parent document for this node
const DOMString * GetNodeValue () const
gets node (text)-value
DOMStringPtr GetTextContent () const
gets text content of this node
void SetNodeValue (const DOMString &value)
set node value
void SetTextContent (const DOMString &value)
sets text content of this node
void RegisterObserver (const MutationObserver &observer)
registers observer with this node
void addEventListener (const DOMString &type, EventListener callback, bool capture=false)
void removeEventListener (const DOMString &type, EventListener callback, bool capture=false)
bool dispatchEvent (Event &event)
Static Public Member Functions
static void QueueMutationRecord (const MutationRecord &record)
queues a mutation record for all nodes
Protected Member Functions
Node (Document *ownerDocument, NodeType type)
constructs a node from a parent document and it's type
Node * doPreInsert (Node *node, Node *child)
Node * doInsert (Node *node, Node *child, bool supressObservers=false)
Node * doPreRemoveChild (Node *child)
Node * doRemoveChild (Node *child, bool supressObservers=false)
bool doGetChildIdx (Node *node, size_t &pos)
Protected Attributes
Document * ownerDocument
Private Member Functions
virtual void OnNodeInserted (Node *)
virtual void OnNodeRemoved (Node *)
Private Attributes
DatabaseUrl * baseURI
Node::NodeType nodeType
NodeList childNodes
DOMStringPtr nodeValue
DOMStringPtr textContent
std::vector< MutationObserver > registeredObservers
Friends
class NodeFactory
Detailed Description
basic implementation of a DOM compatible node
See also:
domparser::NodeFactory
Definition at line 27 of file Node.h.
Member Enumeration Documentation
enum domparser::Node::NodeType
specific type node
Enumerator:
INVALID_NODE_TYPE
ELEMENT_NODE
TEXT_NODE
PROCESSING_INSTRUCTION_NODE
COMMENT_NODE
DOCUMENT_NODE
DOCUMENT_TYPE_NODE
DOCUMENT_FRAGMENT_NODE
Definition at line 36 of file Node.h.
enum domparser::Node::DocumentPosition
describes relationship of two nodes
Enumerator:
DOCUMENT_POSITION_EQUAL
DOCUMENT_POSITION_DISCONNECTED
DOCUMENT_POSITION_PRECEDING
DOCUMENT_POSITION_FOLLOWING
DOCUMENT_POSITION_CONTAINS
DOCUMENT_POSITION_CONTAINED_BY
DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC
Definition at line 56 of file Node.h.
Constructor & Destructor Documentation
domparser::Node::Node (Document * ownerDocument, NodeType type) [protected]
constructs a node from a parent document and it's type
Parameters:
ownerDocument parent document of this node
type type of this node
See also:
domparser::Node::NodeType
Definition at line 24 of file Node.cpp.
domparser::Node::~Node () [virtual]
Definition at line 29 of file Node.cpp.
Member Function Documentation
bool domparser::Node::hasChildNodes () const [inline]
checks if this node has child nodes
Returns:
true if it has, false if not
Definition at line 83 of file Node.h.
References childNodes, and domparser::ListImpl< T >::GetLength().
Node * domparser::Node::insertBefore (Node * node, Node * child)
insert a node before another
Parameters:
node node to insert before
child new node to insert
Returns:
inserted node
Definition at line 320 of file Node.cpp.
References doPreInsert().
Node * domparser::Node::appendChild (Node * node)
appends node as a child to a certain node
Parameters:
node node to append
Returns:
inserted node
Definition at line 324 of file Node.cpp.
Referenced by domparser::DocumentFactory::AppendComment(), domparser::DocumentFactory::AppendDocType(), domparser::DocumentFactory::InsertHtmlElement(), and domparser::DocumentFactory::OnInHeadInsertion().
Node * domparser::Node::replaceChild (Node * node, Node * child)
replace a child node with another
Parameters:
node node to insert
child node to replace
Returns:
replaced node
Definition at line 328 of file Node.cpp.
Node * domparser::Node::removeChild (Node * child)
removes a child node
Parameters:
child node to remove
Returns:
remove node
Definition at line 332 of file Node.cpp.
References doPreRemoveChild().
Referenced by domparser::Document::doAdoptNode(), and domparser::DocumentFactory::OnInBodyStartTagInsertion().
void domparser::Node::normalize ()
normalize DOM tree
Definition at line 336 of file Node.cpp.
Node * domparser::Node::cloneNode (bool deep = true)
clones this node, optionally including all children
Parameters:
deep if set to true, all children are cloned also
Returns:
cloned node
Definition at line 339 of file Node.cpp.
bool domparser::Node::isEqualNode (Node * node)
compare two nodes for equality
Parameters:
node node to compare to
Returns:
true if node is equal
Definition at line 343 of file Node.cpp.
Node::DocumentPosition domparser::Node::compareDocumentPosition (Node * other)
compares position of two DOM nodes
Parameters:
other node to compare to
Returns:
relationship of two nodes
Definition at line 282 of file Node.cpp.
References domparser::Document::createNodeIterator(), DOCUMENT_POSITION_CONTAINS, DOCUMENT_POSITION_DISCONNECTED, DOCUMENT_POSITION_EQUAL, DOCUMENT_POSITION_FOLLOWING, DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC, DOCUMENT_POSITION_PRECEDING, GetOwnerDocument(), GetParentNode(), domparser::NodeIterator::nextNode(), and domparser::NodeFilter::SHOW_ALL.
Referenced by domparser::FollowFilter::acceptNode(), domparser::FollowNodeNotFollowRootFilter::acceptNode(), and domparser::Range::ComparePoints().
bool domparser::Node::contains (Node * other)
checks if a node is a child node of this node
Parameters:
other node to check for
Returns:
true if it is child, false if not
Definition at line 347 of file Node.cpp.
Referenced by domparser::Range::ComparePoints(), doPreInsert(), doRemoveChild(), and domparser::Range::GetCommonAncestorContainer().
DOMStringPtr domparser::Node::lookupPrefix (const DOMString & nameSpace)
Definition at line 351 of file Node.cpp.
References DOMStringPtr.
DOMStringPtr domparser::Node::lookupNamespaceURI (const DOMString & prefix)
Definition at line 355 of file Node.cpp.
References DOMStringPtr.
bool domparser::Node::isDefaultNamespace (const DOMString & nameSpace)
Definition at line 359 of file Node.cpp.
Node::NodeType domparser::Node::GetNodeType () const [inline]
gets node type
Returns:
node type
Definition at line 158 of file Node.h.
References nodeType.
Referenced by domparser::Document::adoptNode(), domparser::Range::comparePoint(), doInsert(), doPreInsert(), domparser::Traverser::FilterNode(), GetNodeName(), GetNodeValue(), GetOwnerDocument(), domparser::Range::selectNodeContents(), and domparser::Range::SetBoundaryPoint().
DOMString domparser::Node::GetNodeName () const
gets node name
Returns:
node name
Definition at line 39 of file Node.cpp.
References COMMENT_NODE, DOCUMENT_FRAGMENT_NODE, DOCUMENT_NODE, DOCUMENT_TYPE_NODE, ELEMENT_NODE, GetNodeType(), PROCESSING_INSTRUCTION_NODE, and TEXT_NODE.
NodeList& domparser::Node::GetChildNodes () [inline]
gets a list of child nodes
Returns:
list of child nodes
Definition at line 170 of file Node.h.
References childNodes.
Referenced by domparser::Range::comparePoint(), domparser::Range::ComparePoints(), doGetChildIdx(), doInsert(), domparser::TreeWalker::NextNodeSubstep(), domparser::TreeWalker::previousNode(), domparser::Range::selectNode(), domparser::Range::selectNodeContents(), domparser::Range::SetBoundaryPoint(), domparser::Range::setEndAfter(), domparser::Range::setEndBefore(), domparser::Range::setStartAfter(), domparser::Range::setStartBefore(), and domparser::TreeWalker::TraverseChildrenSubstep().
Node* domparser::Node::GetParentNode () [inline]
gets the parent node
Returns:
parent node
Definition at line 176 of file Node.h.
Referenced by compareDocumentPosition(), domparser::Range::ComparePoints(), domparser::Document::doAdoptNode(), doPreRemoveChild(), doRemoveChild(), domparser::Range::GetCommonAncestorContainer(), domparser::DocumentFactory::OnInBodyStartTagInsertion(), domparser::TreeWalker::parentNode(), domparser::TreeWalker::previousNode(), domparser::Range::selectNode(), domparser::Range::setEndAfter(), domparser::Range::setEndBefore(), domparser::Range::setStartAfter(), domparser::Range::setStartBefore(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), and domparser::TreeWalker::TraverseSiblingsSubstep().
Node* domparser::Node::GetFirstChild () [inline]
gets first child of this node
Returns:
first child or null
Definition at line 182 of file Node.h.
Referenced by domparser::TreeWalker::NextNodeSubstep(), and domparser::TreeWalker::TraverseSiblingsInnerSubstep().
Node* domparser::Node::GetLastChild () [inline]
gets last child of this node
Returns:
last child or null
Definition at line 188 of file Node.h.
Referenced by domparser::TreeWalker::previousNode(), and domparser::TreeWalker::TraverseSiblingsInnerSubstep().
Node* domparser::Node::GetPreviousSibling () [inline]
gets previous sibling
Returns:
previous sibling or null
Definition at line 194 of file Node.h.
Referenced by doRemoveChild(), domparser::TreeWalker::previousNode(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), domparser::TreeWalker::TraverseSiblingsInnerSubstep(), and domparser::TreeWalker::TraverseSiblingsSubstep().
Node* domparser::Node::GetNextSibling () [inline]
gets next sibling
Returns:
next sibling or null
Definition at line 200 of file Node.h.
Referenced by doPreInsert(), doRemoveChild(), domparser::TreeWalker::TraverseChildrenInnerSubstep(), domparser::TreeWalker::TraverseSiblingsInnerSubstep(), and domparser::TreeWalker::TraverseSiblingsSubstep().
Document * domparser::Node::GetOwnerDocument ()
gets owning/parent document for this node
Returns:
parent document
Definition at line 32 of file Node.cpp.
References DOCUMENT_NODE, GetNodeType(), and ownerDocument.
Referenced by domparser::Range::compareBoundaryPoints(), compareDocumentPosition(), domparser::Range::comparePoint(), domparser::TreeWalker::NextNodeSubstep(), and domparser::Text::splitText().
const DOMString * domparser::Node::GetNodeValue () const
gets node (text)-value
Returns:
character data or null
Definition at line 72 of file Node.cpp.
References COMMENT_NODE, GetNodeType(), PROCESSING_INSTRUCTION_NODE, and TEXT_NODE.
DOMStringPtr domparser::Node::GetTextContent () const
gets text content of this node
Returns:
text content or null
Definition at line 85 of file Node.cpp.
References DOMStringPtr.
void domparser::Node::SetNodeValue (const DOMString & value)
set node value
Parameters:
value new value of this node
Definition at line 89 of file Node.cpp.
void domparser::Node::SetTextContent (const DOMString & value)
sets text content of this node
Parameters:
value value of this node
Definition at line 92 of file Node.cpp.
void domparser::Node::RegisterObserver (const MutationObserver & observer)
registers observer with this node
Parameters:
observer observer to register with this node
Definition at line 363 of file Node.cpp.
References registeredObservers.
void domparser::Node::QueueMutationRecord (const MutationRecord & record) [static]
queues a mutation record for all nodes
Parameters:
record mutation record to queue
Definition at line 367 of file Node.cpp.
Referenced by doRemoveChild().
virtual void domparser::Node::OnNodeInserted (Node *) [inline, private, virtual]
Definition at line 246 of file Node.h.
virtual void domparser::Node::OnNodeRemoved (Node *) [inline, private, virtual]
Definition at line 247 of file Node.h.
Referenced by doRemoveChild().
Node * domparser::Node::doPreInsert (Node * node, Node * child) [protected]
Definition at line 107 of file Node.cpp.
References domparser::Document::adoptNode(), COMMENT_NODE, contains(), DOCUMENT_FRAGMENT_NODE, DOCUMENT_NODE, DOCUMENT_TYPE_NODE, doInsert(), ELEMENT_NODE, GetNextSibling(), GetNodeType(), nodeType, ownerDocument, PROCESSING_INSTRUCTION_NODE, and TEXT_NODE.
Referenced by insertBefore().
Node * domparser::Node::doInsert (Node * node, Node * child, bool supressObservers = false) [protected]
Definition at line 178 of file Node.cpp.
References DOCUMENT_FRAGMENT_NODE, doGetChildIdx(), GetChildNodes(), domparser::Range::GetEndContainer(), domparser::Range::GetEndOffset(), domparser::ListImpl< T >::GetLength(), GetNodeType(), domparser::Range::GetRanges(), domparser::Range::GetStartContainer(), domparser::Range::GetStartOffset(), domparser::Range::setEnd(), and domparser::Range::setStart().
Referenced by doPreInsert().
Node * domparser::Node::doPreRemoveChild (Node * child) [protected]
Definition at line 220 of file Node.cpp.
References doRemoveChild(), and GetParentNode().
Referenced by removeChild().
Node * domparser::Node::doRemoveChild (Node * child, bool supressObservers = false) [protected]
Definition at line 230 of file Node.cpp.
References domparser::MutationRecord::addedNodes, domparser::ListImpl< T >::AppendItem(), childNodes, contains(), doGetChildIdx(), domparser::Range::GetEndContainer(), domparser::Range::GetEndOffset(), GetNextSibling(), GetParentNode(), GetPreviousSibling(), domparser::Range::GetRanges(), domparser::Range::GetStartContainer(), domparser::Range::GetStartOffset(), domparser::MutationRecord::nextSibling, OnNodeRemoved(), domparser::MutationRecord::previousSibling, QueueMutationRecord(), domparser::ListImpl< T >::RemoveItem(), domparser::Range::setEnd(), domparser::Range::setStart(), domparser::MutationRecord::target, and domparser::MutationRecord::type.
Referenced by doPreRemoveChild().
bool domparser::Node::doGetChildIdx (Node * node, size_t & pos) [protected]
Definition at line 96 of file Node.cpp.
References GetChildNodes(), and domparser::ListImpl< T >::GetLength().
Referenced by doInsert(), and doRemoveChild().
void domparser::EventTarget::addEventListener (const DOMString & type, EventListener callback, bool capture = false) [inherited]
Definition at line 21 of file EventTarget.cpp.
References domparser::EventTarget::listenEvents.
void domparser::EventTarget::removeEventListener (const DOMString & type, EventListener callback, bool capture = false) [inherited]
Definition at line 26 of file EventTarget.cpp.
References domparser::EventTarget::listenEvents.
bool domparser::EventTarget::dispatchEvent (Event & event) [inherited]
Definition at line 31 of file EventTarget.cpp.
Friends And Related Function Documentation
friend class NodeFactory [friend]
Reimplemented in domparser::Document.
Definition at line 29 of file Node.h.
Member Data Documentation
Document* domparser::Node::ownerDocument [protected]
Definition at line 260 of file Node.h.
Referenced by domparser::Document::doAdoptNode(), doPreInsert(), and GetOwnerDocument().
DatabaseUrl* domparser::Node::baseURI [private]
Definition at line 263 of file Node.h.
Referenced by domparser::NodeFactory::FromToken().
Node::NodeType domparser::Node::nodeType [private]
Definition at line 264 of file Node.h.
Referenced by doPreInsert(), and GetNodeType().
NodeList domparser::Node::childNodes [private]
Definition at line 269 of file Node.h.
Referenced by doRemoveChild(), GetChildNodes(), and hasChildNodes().
DOMStringPtr domparser::Node::nodeValue [private]
Definition at line 278 of file Node.h.
DOMStringPtr domparser::Node::textContent [private]
Definition at line 279 of file Node.h.
std::vector<MutationObserver> domparser::Node::registeredObservers [private]
Definition at line 281 of file Node.h.
Referenced by RegisterObserver().
The documentation for this class was generated from the following files:
DOMParser/src/Node.h
DOMParser/src/Node.cpp