DeepNet: queryserver::XMLQueryResponse Class Reference
queryserver::XMLQueryResponse Class Reference
#include <XMLQueryResponse.h>
Classes
class OrderedResults
Public Member Functions
XMLQueryResponse (database::DatabaseHelper &dbHelper, XMLQueryRequest *xmlQueryRequest)
virtual ~XMLQueryResponse ()
virtual bool Process (FCGX_Request &request)
processes fastcgi client request.
std::string ToString ()
converts request to string
Protected Attributes
FastCGIRequest * fcgiRequest
corresponding request.
HttpHeader header
response header.
std::string content
content of response.
Private Member Functions
bool ProcessNewQuery (std::vector< std::string > &vecKeywords)
bool ProcessExistQuery ()
bool GetResultsFromDatasources (const std::map< long long, KeywordEntry > &idKeywords, std::vector< long long > &orderedUrlStages, std::map< long long, long long > &mapUrlStageIDUrlID, std::map< long long, UrlStageEntry > &mapUrlStages)
bool GetKeywordIDs (const std::vector< std::string > &vecKeywords, std::map< long long, KeywordEntry > &idKeywords)
bool GetPagesByContent (const std::map< long long, KeywordEntry > &idKeywords, std::map< long long, std::vector< KeywordEntry > > &idUrlStage)
bool GetPagesByDomain (const std::map< long long, KeywordEntry > &idKeywords, std::map< long long, std::vector< KeywordEntry > > &idUrlStage)
bool GetPagesByMeta (const std::map< long long, KeywordEntry > &idKeywords, std::map< long long, std::vector< KeywordEntry > > &idUrlStage)
bool GetPagesByUrlPath (const std::map< long long, KeywordEntry > &idKeywords, std::map< long long, std::vector< KeywordEntry > > &idUrlStage)
bool GetPageRelevanceByBacklinks (const std::map< long long, long long > &mapUrlStageIDUrlID, std::map< long long, BackLinkEntry > &urlStageIDBackLinks)
bool GetPageInfoByUrlStageID (const std::vector< long long > &sortedUrlStages, std::map< long long, PageInfo > &mapUrlStageIDPageInfo)
bool GetPageUrlStageInfo (const std::map< long long, std::vector< KeywordEntry > > &idUrlStage, std::map< long long, long long > &mapUrlStageIDUrlID, std::map< long long, UrlStageProperties > &mapUrlStageIDMetaInfo)
bool SortResults (const std::map< long long, UrlStageEntry > &idUrlStages, const std::map< long long, BackLinkEntry > &urlStageIDBackLinks, std::vector< long long > &sortedUrlStageIDs, std::map< long long, Relevance > &urlStageRelevance)
bool GroupResults (std::map< long long, UrlStageEntry > &idUrlStages, const std::vector< long long > &sortedUrlStageIDs, OrderedResults &orderedResults)
bool OutputResults (const std::vector< long long > &sortedUrlStageIDs, const std::map< long long, long long > &mapUrlStageIDUrlID, const std::map< long long, PageInfo > &mapUrlStagePageInfo, const std::map< long long, htmlparser::DatabaseUrl > &mapUrls)
bool LogQuery (const std::vector< std::string > &vecKeywords, bool &isExistent)
bool SaveResults (const std::vector< long long > &sortedUrlStageIDs, const std::map< long long, long long > &mapUrlStageIDUrlID)
Private Attributes
XMLQueryRequest * xmlQueryRequest
database::DatabaseHelper & dbHelper
long long countResults
Detailed Description
Definition at line 34 of file XMLQueryResponse.h.
Constructor & Destructor Documentation
queryserver::XMLQueryResponse::XMLQueryResponse (database::DatabaseHelper & dbHelper, XMLQueryRequest * xmlQueryRequest)
Definition at line 33 of file XMLQueryResponse.cpp.
queryserver::XMLQueryResponse::~XMLQueryResponse () [virtual]
Definition at line 41 of file XMLQueryResponse.cpp.
Member Function Documentation
bool queryserver::XMLQueryResponse::Process (FCGX_Request & request) [virtual]
processes fastcgi client request.
Parameters:
request corresponding request.
Returns:
false on error, true on success.
Reimplemented from fastcgiserver::FastCGIResponse.
Definition at line 45 of file XMLQueryResponse.cpp.
References tools::ContainerTools::ListToVector(), LogQuery(), ProcessExistQuery(), ProcessNewQuery(), queryserver::XMLQueryRequest::QueryParts(), and xmlQueryRequest.
bool queryserver::XMLQueryResponse::ProcessNewQuery (std::vector< std::string > & vecKeywords) [private]
Definition at line 155 of file XMLQueryResponse.cpp.
References GetKeywordIDs(), GetResultsFromDatasources(), and SaveResults().
Referenced by Process().
bool queryserver::XMLQueryResponse::ProcessExistQuery () [private]
Definition at line 63 of file XMLQueryResponse.cpp.
References database::OrderByClause::AddColumn(), database::WhereCondition::AddColumns(), database::WhereCondition::And(), database::ASCENDING, database::DatabaseHelper::Connection(), countResults, database::queryresultsTableBase::CreateTableDefinition(), dbHelper, database::WhereCondition::Equals(), database::TableColumn::Get(), database::queryresultsTableBase::Get_URL_ID(), database::queryresultsTableBase::Get_URLSTAGE_ID(), caching::CacheDatabaseUrl::GetByUrlID(), database::TableBase::GetConstColumnByName(), database::queryresultsTableBase::GetDefinition_ID(), database::queryresultsTableBase::GetDefinition_SEARCHQUERY_ID(), tools::PointerContainer< T >::GetIter(), GetPageInfoByUrlStageID(), database::queryresultsTableBase::GetWhereColumnsFor_order_position(), database::queryresultsTableBase::GetWhereColumnsFor_SEARCHQUERY_ID(), database::WhereCondition::GreaterOrEqual(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), tools::ContainerTools::Map2ToVector(), queryserver::XMLQueryRequest::QueryRequestParam::MaxResults(), tools::PointerContainer< T >::Next(), database::SelectStatement::OrderBy(), OutputResults(), queryserver::XMLQueryRequest::QueryRequestParam::PageNumber(), queryserver::XMLQueryRequest::Params(), queryserver::XMLQueryRequest::QueryRequestParam::QueryID(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAddCountColumn(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), database::WhereCondition::SmallerOrEqual(), database::SelectStatement::Where(), and xmlQueryRequest.
Referenced by Process().
bool queryserver::XMLQueryResponse::GetResultsFromDatasources (const std::map< long long, KeywordEntry > & idKeywords, std::vector< long long > & orderedUrlStages, std::map< long long, long long > & mapUrlStageIDUrlID, std::map< long long, UrlStageEntry > & mapUrlStages) [private]
Definition at line 176 of file XMLQueryResponse.cpp.
References queryserver::XMLQueryRequest::CRITERIA_ALL, queryserver::XMLQueryRequest::CRITERIA_CONTENT, queryserver::XMLQueryRequest::CRITERIA_DOMAIN, queryserver::XMLQueryRequest::CRITERIA_LINKS, queryserver::XMLQueryRequest::CRITERIA_META, queryserver::XMLQueryRequest::CRITERIA_PATH, queryserver::XMLQueryRequest::CRITERIA_TITLE, queryserver::XMLQueryRequest::QueryRequestParam::CriteriaFlag(), GetPageRelevanceByBacklinks(), GetPagesByContent(), GetPagesByDomain(), GetPagesByMeta(), GetPagesByUrlPath(), GetPageUrlStageInfo(), GroupResults(), log::Logging::Log(), log::Logging::LOGLEVEL_WARN, queryserver::XMLQueryRequest::Params(), queryserver::XMLQueryResponse::OrderedResults::sortedUrlStageIDs, SortResults(), and xmlQueryRequest.
Referenced by ProcessNewQuery().
bool queryserver::XMLQueryResponse::GetKeywordIDs (const std::vector< std::string > & vecKeywords, std::map< long long, KeywordEntry > & idKeywords) [private]
Definition at line 426 of file XMLQueryResponse.cpp.
References database::OrderByClause::AddColumn(), database::WhereCondition::AddColumns(), database::DatabaseHelper::Connection(), database::dictTableBase::CreateTableDefinition(), dbHelper, database::DESCENDING, database::dictTableBase::Get_ID(), database::dictTableBase::Get_keyword(), database::dictTableBase::Get_occurrence(), database::dictTableBase::GetDefinition_occurrence(), tools::PointerContainer< T >::GetIter(), database::dictTableBase::GetWhereColumnsFor_keyword(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), database::WhereCondition::Like(), tools::PointerContainer< T >::Next(), database::SelectStatement::OrderBy(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), queryserver::KeywordEntry::UNKNOWN_KEYWORD_TYPE, and database::SelectStatement::Where().
Referenced by ProcessNewQuery().
bool queryserver::XMLQueryResponse::GetPagesByContent (const std::map< long long, KeywordEntry > & idKeywords, std::map< long long, std::vector< KeywordEntry > > & idUrlStage) [private]
Definition at line 376 of file XMLQueryResponse.cpp.
References database::OrderByClause::AddColumn(), database::WhereCondition::AddColumns(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::dockeyTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::DatabaseHelper::Connection(), queryserver::KeywordEntry::CONTENT_KEYWORD_TYPE, queryserver::XMLQueryRequest::QueryRequestParam::ContentRelevance(), database::dockeyTableBase::CreateTableDefinition(), dbHelper, database::DESCENDING, database::WhereCondition::Equals(), database::dockeyTableBase::Get_DICT_ID(), database::dockeyTableBase::Get_occurrence(), database::dockeyTableBase::Get_URLSTAGE_ID(), database::dockeyTableBase::GetDefinition_occurrence(), tools::PointerContainer< T >::GetIter(), database::dockeyTableBase::GetWhereColumnsFor_DICT_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::ContainerTools::Map1ToVector(), tools::PointerContainer< T >::Next(), database::SelectStatement::OrderBy(), queryserver::XMLQueryRequest::Params(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), database::WhereConditionTableColumnCreateParam::tableNameAlias, database::SelectStatement::Where(), and xmlQueryRequest.
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::GetPagesByDomain (const std::map< long long, KeywordEntry > & idKeywords, std::map< long long, std::vector< KeywordEntry > > & idUrlStage) [private]
Definition at line 306 of file XMLQueryResponse.cpp.
References database::WhereCondition::AddColumns(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::DatabaseHelper::Connection(), database::urlsTableBase::CreateTableDefinition(), dbHelper, queryserver::KeywordEntry::DOMAIN_KEYWORD_TYPE, queryserver::XMLQueryRequest::QueryRequestParam::DomainRelevance(), database::WhereCondition::Equals(), database::TableColumn::Get(), database::secondleveldomainsTableBase::Get_domain(), database::secondleveldomainsTableBase::Get_ID(), database::secondleveldomainsTableBase::GetBy_domain(), database::TableBase::GetConstColumnByName(), database::latesturlstagesTableBase::GetDefinition_URLSTAGE_ID(), tools::PointerContainer< T >::GetIter(), database::urlsTableBase::GetWhereColumnsFor_SECONDLEVELDOMAIN_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::ContainerTools::Map1ToVector(), tools::ContainerTools::Map2ToVector(), tools::PointerContainer< T >::Next(), queryserver::XMLQueryRequest::Params(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAddColumn(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), database::WhereConditionTableColumnCreateParam::tableNameAlias, tools::StringTools::ToLowerNP(), database::SelectStatement::Where(), and xmlQueryRequest.
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::GetPagesByMeta (const std::map< long long, KeywordEntry > & idKeywords, std::map< long long, std::vector< KeywordEntry > > & idUrlStage) [private]
Definition at line 229 of file XMLQueryResponse.cpp.
References database::OrderByClause::AddColumn(), database::WhereCondition::AddColumns(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::metainfoTableBase::AddInnerJoinLeftSideOn_URLSTAGE_ID(), database::docmetaTableBase::AddInnerJoinRightSideOn_URLSTAGE_ID(), database::WhereCondition::And(), database::DatabaseHelper::Connection(), database::docmetaTableBase::CreateTableDefinition(), queryserver::XMLQueryRequest::CRITERIA_META, queryserver::XMLQueryRequest::CRITERIA_TITLE, queryserver::XMLQueryRequest::QueryRequestParam::CriteriaFlag(), dbHelper, database::DESCENDING, database::WhereCondition::Equals(), database::docmetaTableBase::Get_DICT_ID(), database::docmetaTableBase::Get_occurrence(), database::docmetaTableBase::Get_URLSTAGE_ID(), database::docmetaTableBase::GetDefinition_occurrence(), tools::PointerContainer< T >::GetIter(), database::docmetaTableBase::GetWhereColumnsFor_DICT_ID(), database::metainfoTableBase::GetWhereColumnsFor_type(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::ContainerTools::Map1ToVector(), queryserver::KeywordEntry::META_KEYWORD_TYPE, queryserver::XMLQueryRequest::QueryRequestParam::MetaRelevance(), tools::PointerContainer< T >::Next(), database::SelectStatement::OrderBy(), queryserver::XMLQueryRequest::Params(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), database::WhereConditionTableColumnCreateParam::tableNameAlias, database::SelectStatement::Where(), and xmlQueryRequest.
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::GetPagesByUrlPath (const std::map< long long, KeywordEntry > & idKeywords, std::map< long long, std::vector< KeywordEntry > > & idUrlStage) [private]
Definition at line 719 of file XMLQueryResponse.cpp.
References database::WhereCondition::AddColumns(), database::latesturlstagesTableBase::AddInnerJoinLeftSideOn_URL_ID(), database::docurlTableBase::AddInnerJoinRightSideOn_URL_ID(), database::DatabaseHelper::Connection(), database::docurlTableBase::CreateTableDefinition(), dbHelper, database::WhereCondition::Equals(), database::TableColumn::Get(), database::TableBase::GetConstColumnByName(), tools::PointerContainer< T >::GetIter(), database::docurlTableBase::GetWhereColumnsFor_DICT_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, tools::ContainerTools::Map1ToVector(), tools::PointerContainer< T >::Next(), queryserver::XMLQueryRequest::Params(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), database::WhereConditionTableColumnCreateParam::tableNameAlias, queryserver::KeywordEntry::URL_KEYWORD_TYPE, queryserver::XMLQueryRequest::QueryRequestParam::UrlPathRelevance(), database::SelectStatement::Where(), and xmlQueryRequest.
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::GetPageRelevanceByBacklinks (const std::map< long long, long long > & mapUrlStageIDUrlID, std::map< long long, BackLinkEntry > & urlStageIDBackLinks) [private]
Definition at line 562 of file XMLQueryResponse.cpp.
References queryserver::XMLQueryRequest::QueryRequestParam::BackLinkRelevance(), database::DatabaseHelper::Connection(), dbHelper, htmlparser::DatabaseUrl::GetBackLinks(), tools::ContainerTools::Map2ToVector(), queryserver::XMLQueryRequest::Params(), and xmlQueryRequest.
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::GetPageInfoByUrlStageID (const std::vector< long long > & sortedUrlStages, std::map< long long, PageInfo > & mapUrlStageIDPageInfo) [private]
Definition at line 464 of file XMLQueryResponse.cpp.
References database::WhereCondition::AddColumns(), database::WhereCondition::And(), database::DatabaseHelper::Connection(), database::metainfoTableBase::CreateTableDefinition(), dbHelper, database::WhereCondition::Equals(), database::metainfoTableBase::Get_type(), database::metainfoTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_value(), tools::PointerContainer< T >::GetIter(), database::metainfoTableBase::GetWhereColumnsFor_type(), database::metainfoTableBase::GetWhereColumnsFor_URLSTAGE_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
Referenced by ProcessExistQuery().
bool queryserver::XMLQueryResponse::GetPageUrlStageInfo (const std::map< long long, std::vector< KeywordEntry > > & idUrlStage, std::map< long long, long long > & mapUrlStageIDUrlID, std::map< long long, UrlStageProperties > & mapUrlStageIDMetaInfo) [private]
Definition at line 512 of file XMLQueryResponse.cpp.
References database::WhereCondition::AddColumns(), database::urlstagesTableBase::AddInnerJoinRightSideOn_URL_ID(), database::DatabaseHelper::Connection(), database::urlstagesTableBase::CreateTableDefinition(), dbHelper, database::WhereCondition::Equals(), database::TableColumn::Get(), database::TableBase::GetConstColumnByName(), database::urlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), tools::PointerContainer< T >::GetIter(), database::urlstagesTableBase::GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), tools::PointerContainer< T >::IsIterEnd(), tools::ContainerTools::Map1ToVector(), tools::PointerContainer< T >::Next(), tools::PointerContainer< T >::ResetIter(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAddColumn(), database::SelectStatement::SelectAllColumns(), tools::PointerContainer< T >::Size(), database::WhereConditionTableColumnCreateParam::tableNameAlias, and database::SelectStatement::Where().
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::SortResults (const std::map< long long, UrlStageEntry > & idUrlStages, const std::map< long long, BackLinkEntry > & urlStageIDBackLinks, std::vector< long long > & sortedUrlStageIDs, std::map< long long, Relevance > & urlStageRelevance) [private]
Definition at line 579 of file XMLQueryResponse.cpp.
References queryserver::UrlStageEntry::GetTotalRelevance().
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::GroupResults (std::map< long long, UrlStageEntry > & idUrlStages, const std::vector< long long > & sortedUrlStageIDs, OrderedResults & orderedResults) [private]
Definition at line 770 of file XMLQueryResponse.cpp.
References queryserver::XMLQueryResponse::OrderedResults::groupedSecondLevelDomainIDUrlStageID, queryserver::XMLQueryRequest::GROUPING_DOMAIN, queryserver::XMLQueryRequest::QueryRequestParam::GroupingFlag(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::Params(), queryserver::UrlStageProperties::SecondLevelDomainID(), queryserver::XMLQueryResponse::OrderedResults::sortedSecondLevelDomainID, queryserver::XMLQueryResponse::OrderedResults::sortedUrlStageIDs, queryserver::UrlStageProperties::UrlStageID(), queryserver::UrlStageEntry::UrlStageProperty(), and xmlQueryRequest.
Referenced by GetResultsFromDatasources().
bool queryserver::XMLQueryResponse::OutputResults (const std::vector< long long > & sortedUrlStageIDs, const std::map< long long, long long > & mapUrlStageIDUrlID, const std::map< long long, PageInfo > & mapUrlStagePageInfo, const std::map< long long, htmlparser::DatabaseUrl > & mapUrls) [private]
Definition at line 629 of file XMLQueryResponse.cpp.
References fastcgiserver::FastCGIResponse::content, countResults, queryserver::PageInfo::Description(), network::HttpUrlParser::EncodeUrl(), network::HttpUrl::GetFullUrl(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::QueryRequestParam::PageNumber(), queryserver::XMLQueryRequest::Params(), queryserver::XMLQueryRequest::QueryRequestParam::QueryID(), queryserver::PageInfo::Title(), tools::StringTools::VectorToString(), and xmlQueryRequest.
Referenced by ProcessExistQuery().
bool queryserver::XMLQueryResponse::LogQuery (const std::vector< std::string > & vecKeywords, bool & isExistent) [private]
Definition at line 806 of file XMLQueryResponse.cpp.
References database::DatabaseHelper::Connection(), fastcgiserver::FastCGIRequest::Cookies(), dbHelper, network::HttpCookieHelper::GetCookieByKey(), network::HttpCookie::GetValue(), database::TableBase::Insert(), database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::Params(), queryserver::XMLQueryRequest::QueryRequestParam::QueryID(), queryserver::XMLQueryRequest::QueryRequestParam::queryID, database::searchquerykeywordsTableBase::Set_KEYWORDQUERY_ID(), database::keywordqueryTableBase::Set_query_part(), database::searchquerykeywordsTableBase::Set_SEARCHQUERY_ID(), database::searchqueryTableBase::Set_session(), and xmlQueryRequest.
Referenced by Process().
bool queryserver::XMLQueryResponse::SaveResults (const std::vector< long long > & sortedUrlStageIDs, const std::map< long long, long long > & mapUrlStageIDUrlID) [private]
Definition at line 850 of file XMLQueryResponse.cpp.
References database::DatabaseHelper::Connection(), countResults, dbHelper, database::TableBase::Insert(), log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, queryserver::XMLQueryRequest::Params(), queryserver::XMLQueryRequest::QueryRequestParam::QueryID(), database::queryresultsTableBase::Set_order_position(), database::queryresultsTableBase::Set_SEARCHQUERY_ID(), database::queryresultsTableBase::Set_URL_ID(), database::queryresultsTableBase::Set_URLSTAGE_ID(), and xmlQueryRequest.
Referenced by ProcessNewQuery().
std::string fastcgiserver::FastCGIResponse::ToString (void) [inline, inherited]
converts request to string
Returns:
request string.
Definition at line 38 of file FastCGIResponse.h.
References fastcgiserver::FastCGIResponse::content, fastcgiserver::FastCGIResponse::header, and fastcgiserver::HttpHeader::ToString().
Referenced by fastcgiserver::FastCGIResponse::Process().
Member Data Documentation
XMLQueryRequest* queryserver::XMLQueryResponse::xmlQueryRequest [private]
Definition at line 117 of file XMLQueryResponse.h.
Referenced by GetPageRelevanceByBacklinks(), GetPagesByContent(), GetPagesByDomain(), GetPagesByMeta(), GetPagesByUrlPath(), GetResultsFromDatasources(), GroupResults(), LogQuery(), OutputResults(), Process(), ProcessExistQuery(), and SaveResults().
database::DatabaseHelper& queryserver::XMLQueryResponse::dbHelper [private]
Definition at line 118 of file XMLQueryResponse.h.
Referenced by GetKeywordIDs(), GetPageInfoByUrlStageID(), GetPageRelevanceByBacklinks(), GetPagesByContent(), GetPagesByDomain(), GetPagesByMeta(), GetPagesByUrlPath(), GetPageUrlStageInfo(), LogQuery(), ProcessExistQuery(), and SaveResults().
long long queryserver::XMLQueryResponse::countResults [private]
Definition at line 120 of file XMLQueryResponse.h.
Referenced by OutputResults(), ProcessExistQuery(), and SaveResults().
FastCGIRequest* fastcgiserver::FastCGIResponse::fcgiRequest [protected, inherited]
corresponding request.
Definition at line 44 of file FastCGIResponse.h.
HttpHeader fastcgiserver::FastCGIResponse::header [protected, inherited]
response header.
Definition at line 49 of file FastCGIResponse.h.
Referenced by fastcgiserver::FastCGIResponse::ToString().
std::string fastcgiserver::FastCGIResponse::content [protected, inherited]
content of response.
Definition at line 54 of file FastCGIResponse.h.
Referenced by OutputResults(), suggestserver::SuggestServerResponse::Process(), inspectorserver::InspectorServerResponse::Process(), and fastcgiserver::FastCGIResponse::ToString().
The documentation for this class was generated from the following files:
QueryServer/src/XMLQueryResponse.h
QueryServer/src/XMLQueryResponse.cpp