DeepNet: network::HttpUrlParser Class Reference
network::HttpUrlParser Class Reference
parser class for URLs
#include <HttpUrlParser.h>
Public Member Functions
virtual ~HttpUrlParser ()
Static Public Member Functions
static void SetTopLevelDomains (const std::vector< std::string > &tldVec)
sets local top level domain cache
static void ParseURL (const std::string &sBaseUrl, const std::string &sUrl, HttpUrl &url)
parses url from string and base url
static void ParseURL (const std::string &sUrl, HttpUrl &url)
parses url from string
static void ParseURL (const HttpUrl &baseUrl, const std::string &sUrl, HttpUrl &url)
parses url from string and base url
static void DecodeUrl (std::string &url)
url decode string
static void EncodeUrl (std::string &url)
url encode string
static void NormalizePath (const std::string &pathIn, std::string &pathNormalized)
normalized path
Private Types
enum DOMAIN_TYPE { UNKNOWN, DOMAIN, DOCUMENT }
Private Member Functions
HttpUrlParser ()
Static Private Member Functions
static bool ValidateDomain (const std::string &domainTLD, std::string &domain, std::string &tld, DOMAIN_TYPE &typeDomain)
static void ParseScheme (const HttpUrl &baseUrl, const std::string &url, size_t &schemeEnd, std::string &scheme)
static void ParseAuthentication (const HttpUrl &baseUrl, const std::string &url, size_t &schemeEndIn_AuthEndOut, std::string &user, std::string &pass)
static void ParseDomain (const HttpUrl &baseUrl, const std::string &url, size_t &authEndIn_DomainEndOut, std::string &domain, std::string &tld, std::string &port)
static void ParsePath (const HttpUrl &baseUrl, const std::string &url, size_t &domainEndIn_PathEndOut, std::string &path, std::string &document)
static void ParseQuery (const HttpUrl &baseUrl, const std::string &url, size_t &pathEndIn_QueryEndOut, std::vector< std::string > &queryParam)
static void ParseFragment (const HttpUrl &baseUrl, const std::string &url, size_t &queryEndIn, std::string &fragment)
static void SplitPathDocument (const std::string &pathdocument, std::string &path, std::string &document)
static bool IsValidDocumentExtension (const std::string &extension)
static void TrimSlashes (std::string &in)
Static Private Attributes
static std::vector< std::string > tlds
Detailed Description
parser class for URLs
Definition at line 19 of file HttpUrlParser.h.
Member Enumeration Documentation
enum network::HttpUrlParser::DOMAIN_TYPE [private]
Enumerator:
UNKNOWN
DOMAIN
DOCUMENT
Definition at line 22 of file HttpUrlParser.h.
Constructor & Destructor Documentation
network::HttpUrlParser::HttpUrlParser () [private]
Definition at line 34 of file HttpUrlParser.cpp.
network::HttpUrlParser::~HttpUrlParser () [virtual]
Definition at line 37 of file HttpUrlParser.cpp.
Member Function Documentation
static void network::HttpUrlParser::SetTopLevelDomains (const std::vector< std::string > & tldVec) [inline, static]
sets local top level domain cache
Parameters:
tldVec available top level domains
Definition at line 39 of file HttpUrlParser.h.
References tlds.
Referenced by bot::Bot::InitCacheConfigParams().
void network::HttpUrlParser::ParseURL (const std::string & sBaseUrl, const std::string & sUrl, HttpUrl & url) [static]
parses url from string and base url
Parameters:
sBaseUrl base url of document (for relative links)
sUrl url to parse
url parsed url
Definition at line 531 of file HttpUrlParser.cpp.
Referenced by caching::CacheRobotsTxt::DownloadRobotsTxt(), libxmlparser::HtmlSAX2Parser::endElement(), caching::CacheDatabaseUrl::GetByUrlString(), ParseURL(), inspectorserver::InspectorServerResponse::Process(), toolbot::DeepNetToolBot::ProcessUnitTests(), toolbot::UnitTestHttpClientCURL::ReadURLFile(), toolbot::UnitTestUrlParser::TestInvalidUrls(), toolbot::UnitTestCacheUrl::TestSingleEntry(), and toolbot::UnitTestUrlParser::TestValidUrls().
void network::HttpUrlParser::ParseURL (const std::string & sUrl, HttpUrl & url) [static]
parses url from string
Parameters:
sUrl url to parse
url parsed url
Definition at line 525 of file HttpUrlParser.cpp.
References ParseURL().
void network::HttpUrlParser::ParseURL (const HttpUrl & baseUrl, const std::string & sUrl, HttpUrl & url) [static]
parses url from string and base url
Parameters:
baseUrl base url of document (for relative links)
sUrl url to parse
url parsed url
Definition at line 40 of file HttpUrlParser.cpp.
References network::HttpUrl::auth_pass, network::HttpUrl::auth_user, network::HttpUrl::CalculateFullUrl(), network::HttpUrl::domain, network::HttpUrl::fragment_part, network::HttpUrl::fullUrl, ParseAuthentication(), ParseDomain(), ParseFragment(), ParsePath(), ParseQuery(), ParseScheme(), network::HttpUrl::path_part, network::HttpUrl::port, network::HttpUrl::scheme, network::HttpUrl::search_part, THROW_EXCEPTION, network::HttpUrl::tld, and tools::StringTools::VectorToString().
void network::HttpUrlParser::DecodeUrl (std::string & url) [static]
url decode string
Parameters:
url url decoded string
Definition at line 474 of file HttpUrlParser.cpp.
References THROW_EXCEPTION.
Referenced by EncodeUrl(), and inspectorserver::InspectorServerResponse::Process().
void network::HttpUrlParser::EncodeUrl (std::string & url) [static]
url encode string
Parameters:
url url encoded string
Definition at line 501 of file HttpUrlParser.cpp.
References DecodeUrl(), and THROW_EXCEPTION.
Referenced by indexing::Dictionary::DumpXML(), and queryserver::XMLQueryResponse::OutputResults().
void network::HttpUrlParser::NormalizePath (const std::string & pathIn, std::string & pathNormalized) [static]
normalized path
Parameters:
pathIn path to normalize
pathNormalized normalized path
Definition at line 592 of file HttpUrlParser.cpp.
Referenced by ParsePath().
bool network::HttpUrlParser::ValidateDomain (const std::string & domainTLD, std::string & domain, std::string & tld, DOMAIN_TYPE & typeDomain) [static, private]
Definition at line 543 of file HttpUrlParser.cpp.
References DOCUMENT, DOMAIN, THROW_EXCEPTION, tlds, tools::StringTools::ToLowerNP(), and UNKNOWN.
Referenced by ParseDomain().
void network::HttpUrlParser::ParseScheme (const HttpUrl & baseUrl, const std::string & url, size_t & schemeEnd, std::string & scheme) [static, private]
Definition at line 94 of file HttpUrlParser.cpp.
References network::HttpUrl::scheme, THROW_EXCEPTION, and tools::StringTools::ToLowerNP().
Referenced by ParseURL().
void network::HttpUrlParser::ParseAuthentication (const HttpUrl & baseUrl, const std::string & url, size_t & schemeEndIn_AuthEndOut, std::string & user, std::string & pass) [static, private]
Definition at line 138 of file HttpUrlParser.cpp.
Referenced by ParseURL().
void network::HttpUrlParser::ParseDomain (const HttpUrl & baseUrl, const std::string & url, size_t & authEndIn_DomainEndOut, std::string & domain, std::string & tld, std::string & port) [static, private]
Definition at line 167 of file HttpUrlParser.cpp.
References DOMAIN, network::HttpUrl::domain, network::HttpUrl::fullUrl, tools::StringTools::IsNumeric(), network::HttpUrl::port, THROW_EXCEPTION, network::HttpUrl::tld, tools::StringTools::ToLowerNP(), UNKNOWN, and ValidateDomain().
Referenced by ParseURL().
void network::HttpUrlParser::ParsePath (const HttpUrl & baseUrl, const std::string & url, size_t & domainEndIn_PathEndOut, std::string & path, std::string & document) [static, private]
Definition at line 253 of file HttpUrlParser.cpp.
References NormalizePath(), network::HttpUrl::path_part, SplitPathDocument(), and TrimSlashes().
Referenced by ParseURL().
void network::HttpUrlParser::ParseQuery (const HttpUrl & baseUrl, const std::string & url, size_t & pathEndIn_QueryEndOut, std::vector< std::string > & queryParam) [static, private]
Definition at line 324 of file HttpUrlParser.cpp.
References network::HttpUrl::fullUrl, tools::StringTools::SplitBy(), and THROW_EXCEPTION.
Referenced by ParseURL().
void network::HttpUrlParser::ParseFragment (const HttpUrl & baseUrl, const std::string & url, size_t & queryEndIn, std::string & fragment) [static, private]
Definition at line 401 of file HttpUrlParser.cpp.
References network::HttpUrl::fullUrl, and THROW_EXCEPTION.
Referenced by ParseURL().
void network::HttpUrlParser::SplitPathDocument (const std::string & pathdocument, std::string & path, std::string & document) [static, private]
Definition at line 426 of file HttpUrlParser.cpp.
References IsValidDocumentExtension().
Referenced by ParsePath().
bool network::HttpUrlParser::IsValidDocumentExtension (const std::string & extension) [static, private]
Definition at line 421 of file HttpUrlParser.cpp.
Referenced by SplitPathDocument().
void network::HttpUrlParser::TrimSlashes (std::string & in) [static, private]
Definition at line 462 of file HttpUrlParser.cpp.
Referenced by ParsePath().
Member Data Documentation
std::vector< std::string > network::HttpUrlParser::tlds [static, private]
Definition at line 141 of file HttpUrlParser.h.
Referenced by SetTopLevelDomains(), and ValidateDomain().
The documentation for this class was generated from the following files:
Networking/src/HttpUrlParser.h
Networking/src/HttpUrlParser.cpp