DeepNet: tools::CharsetEncoder Class Reference
tools::CharsetEncoder Class Reference
charset specific functions this class is mainly a wrapper for libicu and libiconv.
#include <CharsetEncoder.h>
Classes
struct DetectMatch
contains information about detected charsets.
Public Member Functions
CharsetEncoder ()
virtual ~CharsetEncoder ()
Static Public Member Functions
static bool Convert (const char *pszBuffer, const int len, const std::string &inEnc, std::string &sOutput)
converts buffer to host charset.
static bool Detect (const char *pszBuffer, const int len, DetectMatch &match)
detects charset of buffer
static bool IsValidEncodingName (std::string &encodingName)
checks if string is a valid encoding/charset name.
static bool IsCharsetAlias (const char *name1, const char *name2)
checks if two string are aliases of the same charset.
static std::string GetHostCharsetName ()
gets charset name of current host system.
static bool EncodeHtmlEntities (const unsigned char *pszIn, const int inSize, std::string &out)
converts characters to their html-entity equivalents.
static bool EncodeHtmlEntities (const std::string &in, std::string &out)
converts characters to their html-entity equivalents.
Detailed Description
charset specific functions this class is mainly a wrapper for libicu and libiconv.
it can convert and detect numerous character set encodings.
Definition at line 19 of file CharsetEncoder.h.
Constructor & Destructor Documentation
tools::CharsetEncoder::CharsetEncoder ()
Definition at line 19 of file CharsetEncoder.cpp.
tools::CharsetEncoder::~CharsetEncoder () [virtual]
Definition at line 23 of file CharsetEncoder.cpp.
Member Function Documentation
bool tools::CharsetEncoder::Convert (const char * pszBuffer, const int len, const std::string & inEnc, std::string & sOutput) [static]
converts buffer to host charset.
Parameters:
pszBuffer input buffer.
len size of input buffer.
inEnc encoding/charset name.
sOutput gets filled with converted string.
Returns:
false on error, true on success. this function also zero terminates the string.
Definition at line 170 of file CharsetEncoder.cpp.
References IsCharsetAlias().
Referenced by network::HtmlData::ConvertToHostCharset().
bool tools::CharsetEncoder::Detect (const char * pszBuffer, const int len, DetectMatch & match) [static]
detects charset of buffer
Parameters:
pszBuffer input buffer.
len size of input buffer.
match gets filled with information about buffer.
Returns:
false on error, true on success.
Definition at line 27 of file CharsetEncoder.cpp.
References tools::CharsetEncoder::DetectMatch::encodingConfidence, tools::CharsetEncoder::DetectMatch::encodingHint, tools::CharsetEncoder::DetectMatch::encodingHintCorrect, tools::CharsetEncoder::DetectMatch::encodingName, IsCharsetAlias(), and tools::CharsetEncoder::DetectMatch::language.
Referenced by network::HtmlData::DetectCharset().
bool tools::CharsetEncoder::IsValidEncodingName (std::string & encodingName) [static]
checks if string is a valid encoding/charset name.
Parameters:
encodingName charset/encoding name.
Returns:
false if invalid name, true if valid name.
Definition at line 123 of file CharsetEncoder.cpp.
References IsCharsetAlias().
Referenced by network::HtmlData::ConvertToHostCharset(), and tools::MimeType::GetCharsetFromMimeString().
bool tools::CharsetEncoder::IsCharsetAlias (const char * name1, const char * name2) [static]
checks if two string are aliases of the same charset.
Parameters:
name1 charset/encoding name.
name2 charset/encoding name.
Returns:
false if they are not aliases, true if they are.
Definition at line 160 of file CharsetEncoder.cpp.
Referenced by Convert(), Detect(), and IsValidEncodingName().
std::string tools::CharsetEncoder::GetHostCharsetName () [static]
gets charset name of current host system.
Returns:
charset name of current host system.
Definition at line 165 of file CharsetEncoder.cpp.
Referenced by indexing::IndexerEx::Parse(), and indexing::IndexerEx::ParseMeta().
bool tools::CharsetEncoder::EncodeHtmlEntities (const unsigned char * pszIn, const int inSize, std::string & out) [static]
converts characters to their html-entity equivalents.
Parameters:
pszIn input buffer.
inSize size of input buffer.
out gets filled with html encoded string.
Returns:
false on error, true on success.
Definition at line 257 of file CharsetEncoder.cpp.
References log::Logging::Log(), and log::Logging::LOGLEVEL_ERROR.
Referenced by htmlparser::IHtmlParserResult::DumpXML(), and EncodeHtmlEntities().
bool tools::CharsetEncoder::EncodeHtmlEntities (const std::string & in, std::string & out) [static]
converts characters to their html-entity equivalents.
Parameters:
in input buffer.
out gets filled with html encoded string.
Returns:
false on error, true on success.
Definition at line 253 of file CharsetEncoder.cpp.
References EncodeHtmlEntities().
The documentation for this class was generated from the following files:
Tools/src/CharsetEncoder.h
Tools/src/CharsetEncoder.cpp