DeepNet: toolbot::UnitTestSAX2HtmlParser Class Reference
toolbot::UnitTestSAX2HtmlParser Class Reference
#include <UnitTestSAX2HtmlParser.h>
Public Member Functions
UnitTestSAX2HtmlParser (database::DatabaseConnection *db, const std::string &unitBaseDir)
virtual ~UnitTestSAX2HtmlParser ()
virtual bool Run ()
virtual std::string GetName () const
Private Member Functions
bool Test (const htmlparser::DatabaseUrl &baseUrl)
Private Attributes
database::DatabaseConnection * db
std::string unitBaseDir
std::vector< std::string > contentFiles
Detailed Description
Definition at line 26 of file UnitTestSAX2HtmlParser.h.
Constructor & Destructor Documentation
toolbot::UnitTestSAX2HtmlParser::UnitTestSAX2HtmlParser (database::DatabaseConnection * db, const std::string & unitBaseDir)
Definition at line 26 of file UnitTestSAX2HtmlParser.cpp.
References contentFiles, and tools::FileTools::ListDirectory().
toolbot::UnitTestSAX2HtmlParser::~UnitTestSAX2HtmlParser () [virtual]
Definition at line 32 of file UnitTestSAX2HtmlParser.cpp.
Member Function Documentation
bool toolbot::UnitTestSAX2HtmlParser::Run () [virtual]
Implements toolbot::UnitTest.
Definition at line 35 of file UnitTestSAX2HtmlParser.cpp.
References db, tools::Pointer< T >::Get(), caching::CacheDatabaseUrl::GetByUrlString(), and Test().
virtual std::string toolbot::UnitTestSAX2HtmlParser::GetName () const [inline, virtual]
Implements toolbot::UnitTest.
Definition at line 32 of file UnitTestSAX2HtmlParser.h.
bool toolbot::UnitTestSAX2HtmlParser::Test (const htmlparser::DatabaseUrl & baseUrl) [private]
Definition at line 50 of file UnitTestSAX2HtmlParser.cpp.
References tools::MemoryContainer< T >::Append(), tools::FileTools::CompareFiles(), contentFiles, htmlparser::HtmlParserFactory::CreateInstance(), tools::FileTools::DeleteFile(), htmlparser::IHtmlParserResult::DumpXML(), tools::FileTools::FileExists(), tools::Pointer< T >::Get(), htmlparser::HtmlParserFactory::LIBXML, tools::FileTools::ListDirectory(), log::Logging::Log(), log::Logging::LogError(), log::Logging::LogInfo(), log::Logging::LOGLEVEL_WARN, htmlparser::IHtmlParser::Parse(), tools::FileTools::ReadFile(), tools::MemoryContainer< T >::Release(), network::HtmlData::SetContentType(), unitBaseDir, and tools::FileTools::WriteFile().
Referenced by Run().
Member Data Documentation
database::DatabaseConnection* toolbot::UnitTestSAX2HtmlParser::db [private]
Definition at line 38 of file UnitTestSAX2HtmlParser.h.
Referenced by Run().
std::string toolbot::UnitTestSAX2HtmlParser::unitBaseDir [private]
Definition at line 39 of file UnitTestSAX2HtmlParser.h.
Referenced by Test().
std::vector<std::string> toolbot::UnitTestSAX2HtmlParser::contentFiles [private]
Definition at line 40 of file UnitTestSAX2HtmlParser.h.
Referenced by Test(), and UnitTestSAX2HtmlParser().
The documentation for this class was generated from the following files:
DeepNetTool/src/UnitTestSAX2HtmlParser.h
DeepNetTool/src/UnitTestSAX2HtmlParser.cpp