DeepNet: domparser::TreeWalker Class Reference
domparser::TreeWalker Class Reference
#include <TreeWalker.h>
Public Member Functions
virtual ~TreeWalker ()
Node * parentNode ()
Node * previousNode ()
Node * nextNode ()
Node * firstChild ()
Node * lastChild ()
Node * previousSibling ()
Node * nextSibling ()
Node * GetCurrentNode ()
void SetCurrentNode (Node *cur)
Node * GetRoot ()
NodeFilter::Type GetWhatToShow () const
const NodeFilter * GetFilter () const
Protected Member Functions
NodeFilter::Result FilterNode (Node *node)
Protected Attributes
Node * root
NodeFilter::Type whatToShow
tools::Pointer< NodeFilter > filter
bool activeFlag
Private Types
enum ChildType { FIRST, LAST }
enum SiblingType { PREVIOUS, NEXT }
Private Member Functions
TreeWalker (Node *root, NodeFilter::Type whatToShow, NodeFilter *filter)
Node * TraverseChildren (const ChildType type)
Node * TraverseChildrenSubstep (Node *node, const ChildType type)
Node * TraverseChildrenInnerSubstep (Node *node, const ChildType type)
Node * TraverseSiblings (const SiblingType type)
Node * TraverseSiblingsSubstep (Node *node, const SiblingType type)
Node * TraverseSiblingsInnerSubstep (Node *node, Node **pSibling, const SiblingType type)
Node * NextNodeSubstep (Node *node, NodeFilter::Result &result)
Private Attributes
Node * currentNode
Friends
class Document
Detailed Description
Definition at line 19 of file TreeWalker.h.
Member Enumeration Documentation
enum domparser::TreeWalker::ChildType [private]
Enumerator:
FIRST
LAST
Definition at line 24 of file TreeWalker.h.
enum domparser::TreeWalker::SiblingType [private]
Enumerator:
PREVIOUS
NEXT
Definition at line 29 of file TreeWalker.h.
Constructor & Destructor Documentation
domparser::TreeWalker::TreeWalker (Node * root, NodeFilter::Type whatToShow, NodeFilter * filter) [private]
Definition at line 19 of file TreeWalker.cpp.
References SetCurrentNode().
domparser::TreeWalker::~TreeWalker () [virtual]
Definition at line 25 of file TreeWalker.cpp.
Member Function Documentation
Node * domparser::TreeWalker::parentNode ()
Definition at line 28 of file TreeWalker.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, domparser::Traverser::FilterNode(), GetCurrentNode(), domparser::Node::GetParentNode(), domparser::Traverser::GetRoot(), and SetCurrentNode().
Node * domparser::TreeWalker::previousNode ()
Definition at line 188 of file TreeWalker.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_REJECT, domparser::Traverser::FilterNode(), domparser::Node::GetChildNodes(), GetCurrentNode(), domparser::Node::GetLastChild(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetParentNode(), domparser::Node::GetPreviousSibling(), domparser::Traverser::GetRoot(), and SetCurrentNode().
Node * domparser::TreeWalker::nextNode ()
Definition at line 226 of file TreeWalker.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, GetCurrentNode(), and NextNodeSubstep().
Node* domparser::TreeWalker::firstChild () [inline]
Definition at line 43 of file TreeWalker.h.
References FIRST, and TraverseChildren().
Node* domparser::TreeWalker::lastChild () [inline]
Definition at line 44 of file TreeWalker.h.
References LAST, and TraverseChildren().
Node* domparser::TreeWalker::previousSibling () [inline]
Definition at line 46 of file TreeWalker.h.
References PREVIOUS, and TraverseSiblings().
Node* domparser::TreeWalker::nextSibling () [inline]
Definition at line 47 of file TreeWalker.h.
References NEXT, and TraverseSiblings().
Node* domparser::TreeWalker::GetCurrentNode () [inline]
Definition at line 49 of file TreeWalker.h.
References currentNode.
Referenced by nextNode(), parentNode(), previousNode(), TraverseChildren(), TraverseChildrenInnerSubstep(), and TraverseSiblings().
void domparser::TreeWalker::SetCurrentNode (Node * cur) [inline]
Definition at line 50 of file TreeWalker.h.
References currentNode.
Referenced by NextNodeSubstep(), parentNode(), previousNode(), TraverseChildrenSubstep(), TraverseSiblingsInnerSubstep(), and TreeWalker().
Node * domparser::TreeWalker::TraverseChildren (const ChildType type) [private]
Definition at line 41 of file TreeWalker.cpp.
References GetCurrentNode(), and TraverseChildrenSubstep().
Referenced by firstChild(), and lastChild().
Node * domparser::TreeWalker::TraverseChildrenSubstep (Node * node, const ChildType type) [private]
Definition at line 50 of file TreeWalker.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_SKIP, domparser::Traverser::FilterNode(), FIRST, domparser::Node::GetChildNodes(), domparser::ListImpl< T >::GetItem(), domparser::ListImpl< T >::GetLength(), LAST, SetCurrentNode(), and TraverseChildrenInnerSubstep().
Referenced by TraverseChildren().
Node * domparser::TreeWalker::TraverseChildrenInnerSubstep (Node * node, const ChildType type) [private]
Definition at line 87 of file TreeWalker.cpp.
References FIRST, GetCurrentNode(), domparser::Node::GetNextSibling(), domparser::Node::GetParentNode(), domparser::Node::GetPreviousSibling(), domparser::Traverser::GetRoot(), and LAST.
Referenced by TraverseChildrenSubstep().
Node * domparser::TreeWalker::TraverseSiblings (const SiblingType type) [private]
Definition at line 113 of file TreeWalker.cpp.
References GetCurrentNode(), domparser::Traverser::GetRoot(), and TraverseSiblingsSubstep().
Referenced by nextSibling(), and previousSibling().
Node * domparser::TreeWalker::TraverseSiblingsSubstep (Node * node, const SiblingType type) [private]
Definition at line 122 of file TreeWalker.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, domparser::Traverser::FilterNode(), domparser::Node::GetNextSibling(), domparser::Node::GetParentNode(), domparser::Node::GetPreviousSibling(), domparser::Traverser::GetRoot(), NEXT, PREVIOUS, and TraverseSiblingsInnerSubstep().
Referenced by TraverseSiblings().
Node * domparser::TreeWalker::TraverseSiblingsInnerSubstep (Node * node, Node ** pSibling, const SiblingType type) [private]
Definition at line 150 of file TreeWalker.cpp.
References domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_REJECT, domparser::Traverser::FilterNode(), domparser::Node::GetFirstChild(), domparser::Node::GetLastChild(), domparser::Node::GetNextSibling(), domparser::Node::GetPreviousSibling(), NEXT, PREVIOUS, and SetCurrentNode().
Referenced by TraverseSiblingsSubstep().
Node * domparser::TreeWalker::NextNodeSubstep (Node * node, NodeFilter::Result & result) [private]
Definition at line 233 of file TreeWalker.cpp.
References domparser::Document::createNodeIterator(), domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_REJECT, domparser::Traverser::FilterNode(), domparser::Node::GetChildNodes(), domparser::Node::GetFirstChild(), domparser::ListImpl< T >::GetLength(), domparser::Node::GetOwnerDocument(), domparser::NodeIterator::nextNode(), domparser::Traverser::root, SetCurrentNode(), and domparser::NodeFilter::SHOW_ALL.
Referenced by nextNode().
Node* domparser::Traverser::GetRoot () [inline, inherited]
Definition at line 31 of file Traverser.h.
References domparser::Traverser::root.
Referenced by parentNode(), previousNode(), TraverseChildrenInnerSubstep(), TraverseSiblings(), and TraverseSiblingsSubstep().
NodeFilter::Type domparser::Traverser::GetWhatToShow () const [inline, inherited]
Definition at line 32 of file Traverser.h.
References domparser::Traverser::whatToShow.
const NodeFilter* domparser::Traverser::GetFilter () const [inline, inherited]
Definition at line 33 of file Traverser.h.
References domparser::Traverser::filter.
NodeFilter::Result domparser::Traverser::FilterNode (Node * node) [protected, inherited]
Definition at line 29 of file Traverser.cpp.
References domparser::Traverser::activeFlag, domparser::Traverser::filter, domparser::NodeFilter::FILTER_ACCEPT, domparser::NodeFilter::FILTER_SKIP, domparser::Node::GetNodeType(), tools::Pointer< T >::IsNull(), and domparser::Traverser::whatToShow.
Referenced by NextNodeSubstep(), parentNode(), previousNode(), TraverseChildrenSubstep(), TraverseSiblingsInnerSubstep(), TraverseSiblingsSubstep(), and domparser::NodeIterator::TraverseSubstep().
Friends And Related Function Documentation
friend class Document [friend]
Definition at line 21 of file TreeWalker.h.
Member Data Documentation
Node* domparser::TreeWalker::currentNode [private]
Definition at line 64 of file TreeWalker.h.
Referenced by GetCurrentNode(), and SetCurrentNode().
Node* domparser::Traverser::root [protected, inherited]
Definition at line 39 of file Traverser.h.
Referenced by domparser::Traverser::GetRoot(), and NextNodeSubstep().
NodeFilter::Type domparser::Traverser::whatToShow [protected, inherited]
Definition at line 40 of file Traverser.h.
Referenced by domparser::Traverser::FilterNode(), and domparser::Traverser::GetWhatToShow().
tools::Pointer<NodeFilter> domparser::Traverser::filter [protected, inherited]
Definition at line 41 of file Traverser.h.
Referenced by domparser::Traverser::FilterNode(), and domparser::Traverser::GetFilter().
bool domparser::Traverser::activeFlag [protected, inherited]
Definition at line 42 of file Traverser.h.
Referenced by domparser::Traverser::FilterNode().
The documentation for this class was generated from the following files:
DOMParser/src/TreeWalker.h
DOMParser/src/TreeWalker.cpp