DeepNet: indexing::GenericWebDictionary Class Reference
indexing::GenericWebDictionary Class Reference
#include <GenericWebDictionary.h>
Public Types
enum MetaInformationType {
META_UNKNOWN = 0, META_TITLE = 1, META_DESCRIPTION = 2, META_KEYWORDS = 3,
META_AUTHOR = 4, META_COPYRIGHT = 5, META_TYPE_MAX
}
Public Member Functions
GenericWebDictionary (database::DatabaseConnection *database)
virtual ~GenericWebDictionary ()
virtual bool CommitMeta (void)
virtual bool CommitContent (void)
bool AddContent (const std::string &word, const std::pair< long long, long long > &paragraphPosition)
bool AddContent (const std::string &word)
bool AddMeta (const std::string &word, const MetaInformationType &type)
void SetUrlID (const long long urlID, const long long urlStageID)
void SetTestMode (const bool testMode)
void Dump (std::string &dictDump) const
void DumpXML (std::string &dictDump, tools::SpellChecking &spellChecker) const
size_t ContentSize (void) const
size_t MetaSize (void) const
Protected Attributes
int limit
database::DatabaseConnection * database
std::set< Word > wordContent
std::map< MetaInformationType,
std::set< Word > > wordMeta
long long urlID
long long urlStageID
bool testMode
Detailed Description
Definition at line 14 of file GenericWebDictionary.h.
Member Enumeration Documentation
enum indexing::Dictionary::MetaInformationType [inherited]
Enumerator:
META_UNKNOWN
META_TITLE
META_DESCRIPTION
META_KEYWORDS
META_AUTHOR
META_COPYRIGHT
META_TYPE_MAX
Definition at line 30 of file Dictionary.h.
Constructor & Destructor Documentation
indexing::GenericWebDictionary::GenericWebDictionary (database::DatabaseConnection * database)
Definition at line 18 of file GenericWebDictionary.cpp.
indexing::GenericWebDictionary::~GenericWebDictionary () [virtual]
Definition at line 22 of file GenericWebDictionary.cpp.
Member Function Documentation
bool indexing::GenericWebDictionary::CommitMeta (void) [virtual]
Implements indexing::Dictionary.
Definition at line 106 of file GenericWebDictionary.cpp.
References indexing::Dictionary::database, database::dictTableBase::GetDefinition_occurrence(), database::docmetaTableBase::GetDefinition_occurrence(), database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_WARN, database::docmetaTableBase::Set_DICT_ID(), database::dictTableBase::Set_keyword(), database::dictTableBase::Set_occurrence(), database::docmetaTableBase::Set_occurrence(), database::docmetaTableBase::Set_type(), database::docmetaTableBase::Set_URLSTAGE_ID(), indexing::Dictionary::testMode, database::DatabaseConnection::TransactionCommit(), database::DatabaseConnection::TransactionRollback(), database::DatabaseConnection::TransactionStart(), indexing::Dictionary::urlStageID, and indexing::Dictionary::wordMeta.
bool indexing::GenericWebDictionary::CommitContent (void) [virtual]
Implements indexing::Dictionary.
Definition at line 25 of file GenericWebDictionary.cpp.
References indexing::Dictionary::database, database::dictTableBase::GetDefinition_occurrence(), database::dockeyTableBase::GetDefinition_occurrence(), indexing::Word::GetOccurrences(), indexing::Word::GetPositions(), indexing::Word::GetString(), database::TableBase::Insert(), database::TableBase::InsertOrUpdate(), database::DatabaseConnection::LastInsertID(), log::Logging::Log(), log::Logging::LOGLEVEL_WARN, database::dockeyTableBase::Set_DICT_ID(), database::dockeyposTableBase::Set_DOCKEY_ID(), database::dictTableBase::Set_keyword(), database::dictTableBase::Set_occurrence(), database::dockeyTableBase::Set_occurrence(), database::dockeyposTableBase::Set_paragraph(), database::dockeyposTableBase::Set_position(), database::dockeyTableBase::Set_URLSTAGE_ID(), indexing::Dictionary::testMode, database::DatabaseConnection::TransactionCommit(), database::DatabaseConnection::TransactionRollback(), database::DatabaseConnection::TransactionStart(), indexing::Dictionary::urlStageID, and indexing::Dictionary::wordContent.
bool indexing::Dictionary::AddContent (const std::string & word, const std::pair< long long, long long > & paragraphPosition) [inherited]
Definition at line 34 of file Dictionary.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::Dictionary::testMode, indexing::Dictionary::urlID, and indexing::Dictionary::wordContent.
Referenced by indexing::IndexerEx::Parse(), and indexing::ContentIndexer::TerminateWord().
bool indexing::Dictionary::AddContent (const std::string & word) [inherited]
Definition at line 51 of file Dictionary.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::Dictionary::testMode, indexing::Dictionary::urlID, and indexing::Dictionary::wordContent.
bool indexing::Dictionary::AddMeta (const std::string & word, const MetaInformationType & type) [inherited]
Definition at line 67 of file Dictionary.cpp.
References log::Logging::Log(), log::Logging::LOGLEVEL_ERROR, indexing::Dictionary::testMode, indexing::Dictionary::urlID, and indexing::Dictionary::wordMeta.
Referenced by indexing::IndexerEx::ParseMeta().
void indexing::Dictionary::SetUrlID (const long long urlID, const long long urlStageID) [inherited]
Definition at line 85 of file Dictionary.cpp.
References indexing::Dictionary::urlID, indexing::Dictionary::urlStageID, indexing::Dictionary::wordContent, and indexing::Dictionary::wordMeta.
void indexing::Dictionary::SetTestMode (const bool testMode) [inline, inherited]
Definition at line 60 of file Dictionary.h.
References indexing::Dictionary::testMode.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile().
void indexing::Dictionary::Dump (std::string & dictDump) const [inherited]
Definition at line 93 of file Dictionary.cpp.
References indexing::Dictionary::wordContent, and indexing::Dictionary::wordMeta.
void indexing::Dictionary::DumpXML (std::string & dictDump, tools::SpellChecking & spellChecker) const [inherited]
Definition at line 115 of file Dictionary.cpp.
References network::HttpUrlParser::EncodeUrl(), tools::SpellChecking::GenerateProposals(), tools::StringTools::VectorToString(), indexing::Dictionary::wordContent, and indexing::Dictionary::wordMeta.
Referenced by toolbot::UnitTestIndexerEx::HandleSingleFile().
size_t indexing::Dictionary::ContentSize (void) const [inline, inherited]
Definition at line 63 of file Dictionary.h.
References indexing::Dictionary::wordContent.
size_t indexing::Dictionary::MetaSize (void) const [inline, inherited]
Definition at line 64 of file Dictionary.h.
References indexing::Dictionary::wordMeta.
Member Data Documentation
int indexing::Dictionary::limit [protected, inherited]
Definition at line 67 of file Dictionary.h.
database::DatabaseConnection* indexing::Dictionary::database [protected, inherited]
Definition at line 68 of file Dictionary.h.
Referenced by CommitContent(), and CommitMeta().
std::set<Word> indexing::Dictionary::wordContent [protected, inherited]
Definition at line 69 of file Dictionary.h.
Referenced by indexing::Dictionary::AddContent(), indexing::DataminingDictionary::Commit(), CommitContent(), indexing::Dictionary::ContentSize(), indexing::Dictionary::Dump(), indexing::Dictionary::DumpXML(), and indexing::Dictionary::SetUrlID().
std::map<MetaInformationType,std::set<Word> > indexing::Dictionary::wordMeta [protected, inherited]
Definition at line 70 of file Dictionary.h.
Referenced by indexing::Dictionary::AddMeta(), CommitMeta(), indexing::DataminingDictionary::CommitMeta(), indexing::Dictionary::Dump(), indexing::Dictionary::DumpXML(), indexing::Dictionary::MetaSize(), and indexing::Dictionary::SetUrlID().
long long indexing::Dictionary::urlID [protected, inherited]
Definition at line 72 of file Dictionary.h.
Referenced by indexing::Dictionary::AddContent(), indexing::Dictionary::AddMeta(), and indexing::Dictionary::SetUrlID().
long long indexing::Dictionary::urlStageID [protected, inherited]
Definition at line 73 of file Dictionary.h.
Referenced by CommitContent(), CommitMeta(), and indexing::Dictionary::SetUrlID().
bool indexing::Dictionary::testMode [protected, inherited]
Definition at line 75 of file Dictionary.h.
Referenced by indexing::Dictionary::AddContent(), indexing::Dictionary::AddMeta(), indexing::DataminingDictionary::Commit(), CommitContent(), CommitMeta(), and indexing::Dictionary::SetTestMode().
The documentation for this class was generated from the following files:
Indexer/src/GenericWebDictionary.h
Indexer/src/GenericWebDictionary.cpp