DeepNet: indexing::Indexer Class Reference
indexing::Indexer Class Reference
#include <Indexer.h>
Public Member Functions
virtual ~Indexer ()
bool StartThread (void *pParam=NULL)
starts the thread.
bool WaitForThread ()
blocks till thread has ended.
bool SetShallEnd (bool shallEnd=true)
set end of thread.
bool ShallEnd () const
checks if thread should end.
bool IsRunning () const
checks if thread is running.
Static Public Member Functions
static bool ShallEnd (THREAD_PARAM *threadParam)
checks if thread should end by thread parameters.
Protected Types
typedef void *(* ThreadFunction)(THREAD_PARAM *)
type for user defined thread function.
Protected Member Functions
Indexer (const IndexerParam *param)
void SetThreadFunction (ThreadFunction pFunction)
Private Member Functions
bool StartIndexer ()
bool StopIndexer ()
bool WatchDog ()
virtual IndexerThread * CreateIndexerThread ()=0
Static Private Member Functions
static void * IndexerThreadFunc (threading::Thread::THREAD_PARAM *threadParam)
Private Attributes
const IndexerParam * indexerParam
std::map< IndexerThread
*, IndexerThread::IndexerThreadParam * > indexerThreads
Detailed Description
Definition at line 21 of file Indexer.h.
Member Typedef Documentation
typedef void*(* threading::Thread::ThreadFunction)(THREAD_PARAM *) [protected, inherited]
type for user defined thread function.
Parameters:
thread's parameters.
Definition at line 27 of file Thread.h.
Constructor & Destructor Documentation
indexing::Indexer::Indexer (const IndexerParam * param) [protected]
Definition at line 12 of file Indexer.cpp.
indexing::Indexer::~Indexer () [virtual]
Definition at line 18 of file Indexer.cpp.
Member Function Documentation
bool indexing::Indexer::StartIndexer () [private]
Definition at line 44 of file Indexer.cpp.
References CreateIndexerThread(), indexing::IndexerParam::databaseConfig, indexerParam, indexerThreads, indexing::IndexerParam::maxPerSelect, threading::Thread::StartThread(), indexing::IndexerParam::threadCount, threading::Thread::threadParam, and indexing::IndexerParam::waitOnIdle.
Referenced by IndexerThreadFunc().
bool indexing::Indexer::StopIndexer () [private]
Definition at line 61 of file Indexer.cpp.
References indexerThreads.
Referenced by IndexerThreadFunc().
bool indexing::Indexer::WatchDog () [private]
Definition at line 80 of file Indexer.cpp.
References indexerThreads.
Referenced by IndexerThreadFunc().
virtual IndexerThread* indexing::Indexer::CreateIndexerThread () [private, pure virtual]
Implemented in indexing::DataminingIndexer, and indexing::GenericWebIndexer.
Referenced by StartIndexer().
void * indexing::Indexer::IndexerThreadFunc (threading::Thread::THREAD_PARAM * threadParam) [static, private]
Definition at line 21 of file Indexer.cpp.
References threading::Thread::THREAD_PARAM::instance, log::Logging::RegisterThreadID(), threading::Thread::ShallEnd(), StartIndexer(), StopIndexer(), and WatchDog().
bool threading::Thread::StartThread (void * pParam = NULL) [inherited]
starts the thread.
Parameters:
pParam user defined parameters.
Returns:
false on error, true on success.
Definition at line 26 of file Thread.cpp.
References threading::Thread::autoDelete, threading::Thread::THREAD_PARAM::instance, threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::pParam, threading::Thread::SetShallEnd(), threading::Thread::thread, threading::Thread::threadAttr, threading::Thread::THREAD_PARAM::threadFunction, threading::Thread::threadParam, and threading::Thread::WaitForThread().
Referenced by workerbot::WorkerBot::OnRun(), tools::TokenBucket::Start(), crawler::FencedCrawler::StartCrawler(), crawler::GenericWebCrawler::StartCrawler(), crawler::DataminingCrawler::StartCrawler(), crawler::CommerceSearchCrawler::StartCrawler(), StartIndexer(), parser::GenericWebHtmlParser::StartParser(), parser::CommerceSearchParser::StartParser(), and fastcgiserver::FastCGIServer::StartServer().
bool threading::Thread::WaitForThread () [inherited]
blocks till thread has ended.
Returns:
false on error, true on success.
Definition at line 64 of file Thread.cpp.
References threading::Thread::thread.
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::SetShallEnd (bool shallEnd = true) [inherited]
set end of thread.
Parameters:
shallEnd true if thread should end.
Returns:
false on error, true on success.
Definition at line 55 of file Thread.cpp.
References threading::Mutex::IsLocked(), threading::Mutex::Lock(), threading::Thread::THREAD_PARAM::shallEnd, threading::Thread::threadParam, and threading::Mutex::Unlock().
Referenced by workerbot::WorkerBot::OnShutdown(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and threading::Thread::~Thread().
bool threading::Thread::ShallEnd () const [inline, inherited]
checks if thread should end.
Returns:
false if thread should not end, true if thread should end.
Definition at line 96 of file Thread.h.
References threading::Mutex::IsLocked(), threading::Thread::THREAD_PARAM::shallEnd, and threading::Thread::threadParam.
Referenced by crawler::Crawler::CrawlerThreadFunc(), fastcgiserver::FastCGIServerThread::FastCGIServerThreadFunc(), parser::HtmlParserBase::HtmlParserThreadFunc(), parser::HtmlParserThread::HtmlParserThreadFunction(), IndexerThreadFunc(), indexing::IndexerThread::IndexerThreadFunc(), parser::HtmlParserThread::OnIdle(), indexing::IndexerThread::OnIdle(), crawler::UrlFetcherThread::OnIdle(), tools::TokenBucket::RefillThreadFunc(), and crawler::UrlFetcherThread::UrlFetcherThreadFunction().
static bool threading::Thread::ShallEnd (THREAD_PARAM * threadParam) [inline, static, inherited]
checks if thread should end by thread parameters.
Parameters:
threadParam thread parameters.
Returns:
false if thread should not end, true if thread should end.
Definition at line 110 of file Thread.h.
References threading::Mutex::IsLocked(), and threading::Thread::THREAD_PARAM::shallEnd.
bool threading::Thread::IsRunning () const [inline, inherited]
checks if thread is running.
Returns:
false if not running, true if running.
Definition at line 102 of file Thread.h.
References threading::Thread::thread.
Referenced by tools::TokenBucket::RemoveTokens(), threading::Thread::SetThreadFunction(), threading::Thread::StartThread(), tools::TokenBucket::Stop(), and tools::TokenBucket::TryRemoveTokens().
void threading::Thread::SetThreadFunction (ThreadFunction pFunction) [inline, protected, inherited]
Definition at line 113 of file Thread.h.
References threading::Thread::IsRunning(), threading::Thread::THREAD_PARAM::threadFunction, and threading::Thread::threadParam.
Member Data Documentation
const IndexerParam* indexing::Indexer::indexerParam [private]
Definition at line 40 of file Indexer.h.
Referenced by StartIndexer().
std::map<IndexerThread*,IndexerThread::IndexerThreadParam*> indexing::Indexer::indexerThreads [private]
Definition at line 41 of file Indexer.h.
Referenced by StartIndexer(), StopIndexer(), and WatchDog().
The documentation for this class was generated from the following files:
Indexer/src/Indexer.h
Indexer/src/Indexer.cpp