DeepNet: database::logmessagesTableBase Class Reference
database::logmessagesTableBase Class Reference
wrapper class for database table logmessages
#include <logmessagesTableBase.h>
Public Member Functions
logmessagesTableBase ()
virtual ~logmessagesTableBase ()
void Get_ID (long long &out) const
gets value of ID.
void Set_ID (const long long &in)
sets value of ID.
void Get_loglevel (long long &out) const
gets value of loglevel.
void Set_loglevel (const long long &in)
sets value of loglevel.
void Get_message (std::string &out) const
gets value of message.
void Set_message (const std::string &in)
sets value of message.
void Get_actiontime (struct tm &out) const
gets value of actiontime.
void Set_actiontime (const struct tm &in)
sets value of actiontime.
void Get_pid (long long &out) const
gets value of pid.
void Set_pid (const long long &in)
sets value of pid.
void Get_tid (long long &out) const
gets value of tid.
void Set_tid (const long long &in)
sets value of tid.
void Get_appName (std::string &out) const
gets value of appName.
void Set_appName (const std::string &in)
sets value of appName.
void Get_threadName (std::string &out) const
gets value of threadName.
void Set_threadName (const std::string &in)
sets value of threadName.
const TableDefinition * GetConstTableDefinition () const
gets const table definition.
TableDefinition * GetTableDefinition ()
gets table definition.
const TableColumn * GetConstColumnByName (const std::string &columnName) const
finds column by it's name.
TableColumn * GetColumnByName (const std::string &columnName)
finds column by it's name.
std::vector< TableColumn * > & GetColumns ()
gets list of columns.
const std::vector< TableColumn * > & GetConstColumns () const
gets const list of columns.
void SetTableAlias (const std::string &tableAlias)
sets alias name.
const std::string & GetTableAlias () const
gets alias name.
void Insert (DatabaseConnection *db)
inserts this table.
void InsertOrUpdate (DatabaseConnection *db)
inserts or updates this table.
void InsertOrUpdate (DatabaseConnection *db, TableColumnDefinition *sumColumn)
inserts or updates this table adding SUM()-type columns.
void InsertOrUpdate (DatabaseConnection *db, const std::vector< TableColumnDefinition * > &sumColumn)
inserts or updates this table adding SUM()-type columns.
void Update (DatabaseConnection *db, const TableBaseUpdateParam &param) const
updates this table.
void CopyColumns (const TableBase *base)
copies column definitions and values from another table.
Static Public Member Functions
static TableDefinition * CreateTableDefinition ()
factory function for logmessages's table definition.
static void GetBy_ID (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of ID.
static void GetBy_ID (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of ID.
static void GetBy_loglevel (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of loglevel.
static void GetBy_loglevel (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of loglevel.
static void GetBy_message (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of message.
static void GetBy_message (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of message.
static void GetBy_actiontime (DatabaseConnection *db, const struct tm &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of actiontime.
static void GetBy_actiontime (DatabaseConnection *db, const std::vector< struct tm > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of actiontime.
static void GetBy_pid (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of pid.
static void GetBy_pid (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of pid.
static void GetBy_tid (DatabaseConnection *db, const long long &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of tid.
static void GetBy_tid (DatabaseConnection *db, const std::vector< long long > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of tid.
static void GetBy_appName (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of appName.
static void GetBy_appName (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of appName.
static void GetBy_threadName (DatabaseConnection *db, const std::string &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by a value of threadName.
static void GetBy_threadName (DatabaseConnection *db, const std::vector< std::string > &fieldValue, SelectResultContainer< logmessagesTableBase > &results)
gets rows by multiple values of threadName.
static void GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of ID.
static void GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of ID.
static void GetWhereColumnsFor_loglevel (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of loglevel.
static void GetWhereColumnsFor_loglevel (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of loglevel.
static void GetWhereColumnsFor_message (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of message.
static void GetWhereColumnsFor_message (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of message.
static void GetWhereColumnsFor_actiontime (const WhereConditionTableColumnCreateParam &createParam, const struct tm &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of actiontime.
static void GetWhereColumnsFor_actiontime (const WhereConditionTableColumnCreateParam &createParam, const std::vector< struct tm > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of actiontime.
static void GetWhereColumnsFor_pid (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of pid.
static void GetWhereColumnsFor_pid (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of pid.
static void GetWhereColumnsFor_tid (const WhereConditionTableColumnCreateParam &createParam, const long long &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of tid.
static void GetWhereColumnsFor_tid (const WhereConditionTableColumnCreateParam &createParam, const std::vector< long long > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of tid.
static void GetWhereColumnsFor_appName (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of appName.
static void GetWhereColumnsFor_appName (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of appName.
static void GetWhereColumnsFor_threadName (const WhereConditionTableColumnCreateParam &createParam, const std::string &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for a value of threadName.
static void GetWhereColumnsFor_threadName (const WhereConditionTableColumnCreateParam &createParam, const std::vector< std::string > &fieldValue, std::vector< WhereConditionTableColumn * > &container)
creates where condition for multiple values of threadName.
static TableColumnDefinition * GetDefinition_ID ()
create a column definition for column ID.
static TableColumnDefinition * GetDefinition_loglevel ()
create a column definition for column loglevel.
static TableColumnDefinition * GetDefinition_message ()
create a column definition for column message.
static TableColumnDefinition * GetDefinition_actiontime ()
create a column definition for column actiontime.
static TableColumnDefinition * GetDefinition_pid ()
create a column definition for column pid.
static TableColumnDefinition * GetDefinition_tid ()
create a column definition for column tid.
static TableColumnDefinition * GetDefinition_appName ()
create a column definition for column appName.
static TableColumnDefinition * GetDefinition_threadName ()
create a column definition for column threadName.
static TableBase * CreateInstance (const TableDefinitionCreateParam &param)
factory function for this class.
Protected Member Functions
void CreateColumns ()
creates columns according to database::TableBase::definition.
Private Member Functions
logmessagesTableBase (const TableBase &base)
Detailed Description
wrapper class for database table logmessages
Definition at line 17 of file logmessagesTableBase.h.
Constructor & Destructor Documentation
database::logmessagesTableBase::logmessagesTableBase (const TableBase & base) [private]
Definition at line 29 of file logmessagesTableBase.cpp.
References THROW_EXCEPTION.
database::logmessagesTableBase::logmessagesTableBase ()
Definition at line 25 of file logmessagesTableBase.cpp.
database::logmessagesTableBase::~logmessagesTableBase () [virtual]
Definition at line 33 of file logmessagesTableBase.cpp.
Member Function Documentation
TableDefinition * database::logmessagesTableBase::CreateTableDefinition () [static]
factory function for logmessages's table definition.
Returns:
table definition.
Definition at line 36 of file logmessagesTableBase.cpp.
References database::TableBase::CreateInstance().
Referenced by GetBy_actiontime(), GetBy_appName(), GetBy_ID(), GetBy_loglevel(), GetBy_message(), GetBy_pid(), GetBy_threadName(), and GetBy_tid().
void database::logmessagesTableBase::Get_ID (long long & out) const
gets value of ID.
Parameters:
out value.
Definition at line 43 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_ID (const long long & in)
sets value of ID.
Parameters:
in value.
Definition at line 47 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
void database::logmessagesTableBase::Get_loglevel (long long & out) const
gets value of loglevel.
Parameters:
out value.
Definition at line 51 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_loglevel (const long long & in)
sets value of loglevel.
Parameters:
in value.
Definition at line 55 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::Get_message (std::string & out) const
gets value of message.
Parameters:
out value.
Definition at line 59 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_message (const std::string & in)
sets value of message.
Parameters:
in value.
Definition at line 63 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::Get_actiontime (struct tm & out) const
gets value of actiontime.
Parameters:
out value.
Definition at line 67 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_actiontime (const struct tm & in)
sets value of actiontime.
Parameters:
in value.
Definition at line 71 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::Get_pid (long long & out) const
gets value of pid.
Parameters:
out value.
Definition at line 75 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_pid (const long long & in)
sets value of pid.
Parameters:
in value.
Definition at line 79 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::Get_tid (long long & out) const
gets value of tid.
Parameters:
out value.
Definition at line 83 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_tid (const long long & in)
sets value of tid.
Parameters:
in value.
Definition at line 87 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::Get_appName (std::string & out) const
gets value of appName.
Parameters:
out value.
Definition at line 91 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_appName (const std::string & in)
sets value of appName.
Parameters:
in value.
Definition at line 95 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::Get_threadName (std::string & out) const
gets value of threadName.
Parameters:
out value.
Definition at line 99 of file logmessagesTableBase.cpp.
References database::TableColumn::Get(), and database::TableBase::GetConstColumnByName().
void database::logmessagesTableBase::Set_threadName (const std::string & in)
sets value of threadName.
Parameters:
in value.
Definition at line 103 of file logmessagesTableBase.cpp.
References database::TableBase::GetColumnByName(), and database::TableColumn::Set().
Referenced by log::DatabaseLogging::OnLog().
void database::logmessagesTableBase::GetBy_ID (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of ID.
Parameters:
db database connection.
fieldValue value of ID.
results contains results.
Definition at line 112 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_ID (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of ID.
Parameters:
db database connection.
fieldValue values of ID.
results contains results.
Definition at line 129 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_ID(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_loglevel (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of loglevel.
Parameters:
db database connection.
fieldValue value of loglevel.
results contains results.
Definition at line 146 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_loglevel(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_loglevel (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of loglevel.
Parameters:
db database connection.
fieldValue values of loglevel.
results contains results.
Definition at line 163 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_loglevel(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_message (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of message.
Parameters:
db database connection.
fieldValue value of message.
results contains results.
Definition at line 180 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_message(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_message (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of message.
Parameters:
db database connection.
fieldValue values of message.
results contains results.
Definition at line 197 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_message(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_actiontime (DatabaseConnection * db, const struct tm & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of actiontime.
Parameters:
db database connection.
fieldValue value of actiontime.
results contains results.
Definition at line 214 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_actiontime(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_actiontime (DatabaseConnection * db, const std::vector< struct tm > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of actiontime.
Parameters:
db database connection.
fieldValue values of actiontime.
results contains results.
Definition at line 231 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_actiontime(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_pid (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of pid.
Parameters:
db database connection.
fieldValue value of pid.
results contains results.
Definition at line 248 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_pid(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_pid (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of pid.
Parameters:
db database connection.
fieldValue values of pid.
results contains results.
Definition at line 265 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_pid(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_tid (DatabaseConnection * db, const long long & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of tid.
Parameters:
db database connection.
fieldValue value of tid.
results contains results.
Definition at line 282 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_tid(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_tid (DatabaseConnection * db, const std::vector< long long > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of tid.
Parameters:
db database connection.
fieldValue values of tid.
results contains results.
Definition at line 299 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_tid(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_appName (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of appName.
Parameters:
db database connection.
fieldValue value of appName.
results contains results.
Definition at line 316 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_appName(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_appName (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of appName.
Parameters:
db database connection.
fieldValue values of appName.
results contains results.
Definition at line 333 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_appName(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_threadName (DatabaseConnection * db, const std::string & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by a value of threadName.
Parameters:
db database connection.
fieldValue value of threadName.
results contains results.
Definition at line 350 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_threadName(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetBy_threadName (DatabaseConnection * db, const std::vector< std::string > & fieldValue, SelectResultContainer< logmessagesTableBase > & results) [static]
gets rows by multiple values of threadName.
Parameters:
db database connection.
fieldValue values of threadName.
results contains results.
Definition at line 367 of file logmessagesTableBase.cpp.
References database::WhereCondition::AddColumns(), CreateTableDefinition(), database::WhereCondition::Equals(), GetWhereColumnsFor_threadName(), database::WhereCondition::InitialComp(), database::DatabaseConnection::Select(), database::SelectStatement::SelectAllColumns(), and database::SelectStatement::Where().
void database::logmessagesTableBase::GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of ID.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 394 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_ID().
Referenced by GetBy_ID().
void database::logmessagesTableBase::GetWhereColumnsFor_ID (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of ID.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 406 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_ID().
void database::logmessagesTableBase::GetWhereColumnsFor_loglevel (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of loglevel.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 418 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_loglevel().
Referenced by GetBy_loglevel().
void database::logmessagesTableBase::GetWhereColumnsFor_loglevel (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of loglevel.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 430 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_loglevel().
void database::logmessagesTableBase::GetWhereColumnsFor_message (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of message.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 442 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_message().
Referenced by GetBy_message().
void database::logmessagesTableBase::GetWhereColumnsFor_message (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of message.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 454 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_message().
void database::logmessagesTableBase::GetWhereColumnsFor_actiontime (const WhereConditionTableColumnCreateParam & createParam, const struct tm & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of actiontime.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 466 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_actiontime().
Referenced by GetBy_actiontime().
void database::logmessagesTableBase::GetWhereColumnsFor_actiontime (const WhereConditionTableColumnCreateParam & createParam, const std::vector< struct tm > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of actiontime.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 478 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_actiontime().
void database::logmessagesTableBase::GetWhereColumnsFor_pid (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of pid.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 490 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_pid().
Referenced by GetBy_pid().
void database::logmessagesTableBase::GetWhereColumnsFor_pid (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of pid.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 502 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_pid().
void database::logmessagesTableBase::GetWhereColumnsFor_tid (const WhereConditionTableColumnCreateParam & createParam, const long long & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of tid.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 514 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_tid().
Referenced by GetBy_tid().
void database::logmessagesTableBase::GetWhereColumnsFor_tid (const WhereConditionTableColumnCreateParam & createParam, const std::vector< long long > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of tid.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 526 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_tid().
void database::logmessagesTableBase::GetWhereColumnsFor_appName (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of appName.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 538 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_appName().
Referenced by GetBy_appName().
void database::logmessagesTableBase::GetWhereColumnsFor_appName (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of appName.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 550 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_appName().
void database::logmessagesTableBase::GetWhereColumnsFor_threadName (const WhereConditionTableColumnCreateParam & createParam, const std::string & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for a value of threadName.
Parameters:
createParam create parameter.
fieldValue field value.
container adds newly created where condition.
Definition at line 562 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstanceFromValue(), and GetDefinition_threadName().
Referenced by GetBy_threadName().
void database::logmessagesTableBase::GetWhereColumnsFor_threadName (const WhereConditionTableColumnCreateParam & createParam, const std::vector< std::string > & fieldValue, std::vector< WhereConditionTableColumn * > & container) [static]
creates where condition for multiple values of threadName.
Parameters:
createParam create parameter.
fieldValue field values.
container adds newly created where conditions.
Definition at line 574 of file logmessagesTableBase.cpp.
References database::WhereConditionTableColumn::CreateInstance(), database::TableColumn::CreateInstancesFromValues(), and GetDefinition_threadName().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_ID () [static]
create a column definition for column ID.
Returns:
column definition.
Definition at line 591 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_ID().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_loglevel () [static]
create a column definition for column loglevel.
Returns:
column definition.
Definition at line 607 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_loglevel().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_message () [static]
create a column definition for column message.
Returns:
column definition.
Definition at line 623 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_VARCHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_message().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_actiontime () [static]
create a column definition for column actiontime.
Returns:
column definition.
Definition at line 639 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_TIMESTAMP, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_actiontime().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_pid () [static]
create a column definition for column pid.
Returns:
column definition.
Definition at line 655 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_pid().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_tid () [static]
create a column definition for column tid.
Returns:
column definition.
Definition at line 671 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_INTEGER, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_tid().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_appName () [static]
create a column definition for column appName.
Returns:
column definition.
Definition at line 687 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_VARCHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_appName().
TableColumnDefinition * database::logmessagesTableBase::GetDefinition_threadName () [static]
create a column definition for column threadName.
Returns:
column definition.
Definition at line 703 of file logmessagesTableBase.cpp.
References database::TableColumnDefinitionCreateParam::columnName, database::TableColumnDefinitionCreateParam::columnType, database::TableBase::CreateInstance(), database::TableColumnDefinitionCreateParam::databaseName, database::DB_TYPE_VARCHAR, database::TableColumnDefinitionCreateParam::hasDefaultValue, database::TableColumnDefinitionCreateParam::isAutoGenerated, database::TableColumnDefinitionCreateParam::isForeignKey, database::TableColumnDefinitionCreateParam::isIndex, database::TableColumnDefinitionCreateParam::isNullable, database::TableColumnDefinitionCreateParam::isPrimaryKey, database::TableColumnDefinitionCreateParam::isUniqueKey, and database::TableColumnDefinitionCreateParam::tableName.
Referenced by database::logmessagesTableDefinitionCreateParam::CreateColumnDefinitions(), and GetWhereColumnsFor_threadName().
const TableDefinition * database::TableBase::GetConstTableDefinition () const [inherited]
gets const table definition.
Returns:
table definition.
Definition at line 81 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::definition.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL().
TableDefinition * database::TableBase::GetTableDefinition () [inherited]
gets table definition.
Returns:
table definition.
Definition at line 87 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::definition.
const TableColumn * database::TableBase::GetConstColumnByName (const std::string & columnName) const [inherited]
finds column by it's name.
Parameters:
columnName column name.
Returns:
NULL if not found, column otherwise.
Definition at line 93 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, and THROW_EXCEPTION.
Referenced by database::TableBase::CopyColumns(), database::cacherobotsTableBase::Get_action_time(), database::cachesecondleveldomainTableBase::Get_action_time(), database::cachehtmlTableBase::Get_action_time(), database::cacheurlTableBase::Get_action_time(), database::cacheparsedTableBase::Get_action_time(), database::cachesubdomainTableBase::Get_action_time(), Get_actiontime(), Get_appName(), database::documentcodeTableBase::Get_code(), database::urlstagesTableBase::Get_content_length(), database::urlstagesTableBase::Get_content_md5(), database::urlstagesTableBase::Get_content_type(), database::hyperlinksTableBase::Get_count(), database::locksecondleveldomainTableBase::Get_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Get_CRAWLERSESSION_ID(), database::syncurlsTableBase::Get_CRAWLERSESSION_ID(), database::fencedsearchTableBase::Get_CUSTOMER_ID(), database::customersessionsTableBase::Get_CUSTOMER_ID(), database::customerdomainsTableBase::Get_CUSTOMER_ID(), database::dataminingblacklistTableBase::Get_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Get_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Get_CUSTOMER_ID(), database::customerproductsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerqueriesTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Get_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Get_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Get_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Get_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Get_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Get_DICT_ID(), database::docmetaTableBase::Get_DICT_ID(), database::docurlTableBase::Get_DICT_ID(), database::customerproductkeywordsTableBase::Get_DICT_ID(), database::dockeyposTableBase::Get_DOCKEY_ID(), database::secondleveldomainsTableBase::Get_domain(), database::customerdomainsTableBase::Get_domain(), database::dataminingblacklistTableBase::Get_domain(), database::urlstagesTableBase::Get_download_speed(), database::urlstagesTableBase::Get_download_time(), database::urlstagesTableBase::Get_ext_links(), database::imagesTableBase::Get_found_date(), database::urlsTableBase::Get_found_date(), database::urlstagesTableBase::Get_found_date(), database::customermatchcriteriagrouptypeTableBase::Get_groupPosition(), database::urlstagesTableBase::Get_html_errors(), database::secondleveldomainsTableBase::Get_ID(), database::subdomainsTableBase::Get_ID(), database::syncurlsTableBase::Get_ID(), database::dataminingcriteriaalertsTableBase::Get_ID(), database::cachesubdomainTableBase::Get_ID(), database::searchquerykeywordsTableBase::Get_ID(), database::dataminingblacklistTableBase::Get_ID(), database::dataminingcriteriaTableBase::Get_ID(), database::dataminingcustomersessionTableBase::Get_ID(), database::customermatchcriteriagrouptypeTableBase::Get_ID(), database::urlstagesTableBase::Get_ID(), database::dataminingcustomerTableBase::Get_ID(), database::topleveldomainsTableBase::Get_ID(), database::urlsTableBase::Get_ID(), database::cacherobotsTableBase::Get_ID(), database::dockeyTableBase::Get_ID(), database::customerproductimagesTableBase::Get_ID(), database::cacheurlTableBase::Get_ID(), database::docmetaTableBase::Get_ID(), database::cachehtmlTableBase::Get_ID(), database::dictTableBase::Get_ID(), database::customermatchcriteriaTableBase::Get_ID(), database::fencedsearchTableBase::Get_ID(), database::docurlTableBase::Get_ID(), database::customerproductsTableBase::Get_ID(), database::hyperlinksTableBase::Get_ID(), database::crawlersessionsTableBase::Get_ID(), database::documentcodeTableBase::Get_ID(), database::customerproductkeywordsTableBase::Get_ID(), database::customerdomainblacklistTableBase::Get_ID(), database::imagesTableBase::Get_ID(), database::cacheparsedTableBase::Get_ID(), database::customerqueriesTableBase::Get_ID(), database::customersessionsTableBase::Get_ID(), database::dockeyposTableBase::Get_ID(), database::customerproducturlsTableBase::Get_ID(), database::imagelinksTableBase::Get_ID(), database::customerdomainsTableBase::Get_ID(), database::latesturlstagesTableBase::Get_ID(), database::customersTableBase::Get_ID(), Get_ID(), database::customersynccrawlerTableBase::Get_ID(), database::keywordqueryTableBase::Get_ID(), database::cachesecondleveldomainTableBase::Get_ID(), database::metainfoTableBase::Get_ID(), database::queryresultsTableBase::Get_ID(), database::customerkeywordsTableBase::Get_ID(), database::dataminingalertsTableBase::Get_ID(), database::schemesTableBase::Get_ID(), database::matchcriteriaTableBase::Get_ID(), database::customersyncurlTableBase::Get_ID(), database::searchqueryTableBase::Get_ID(), database::imagelinksTableBase::Get_IMAGE_URL_ID(), database::customerproductimagesTableBase::Get_imageUrl(), database::urlstagesTableBase::Get_int_links(), database::customerdomainsTableBase::Get_isDomainRegex(), database::customerkeywordsTableBase::Get_isKeywordRegex(), database::customerdomainblacklistTableBase::Get_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Get_isPrimaryKey(), database::dataminingcriteriaTableBase::Get_keyword(), database::dictTableBase::Get_keyword(), database::customerkeywordsTableBase::Get_keyword(), database::searchquerykeywordsTableBase::Get_KEYWORDQUERY_ID(), database::urlstagesTableBase::Get_last_change(), database::customersTableBase::Get_login(), database::dataminingcustomerTableBase::Get_login(), Get_loglevel(), database::customermatchcriteriaTableBase::Get_MATCHCRITERIA_ID(), database::cachesubdomainTableBase::Get_matches(), database::cacherobotsTableBase::Get_matches(), database::cachesecondleveldomainTableBase::Get_matches(), database::cachehtmlTableBase::Get_matches(), database::cacheparsedTableBase::Get_matches(), database::cacheurlTableBase::Get_matches(), Get_message(), database::cacherobotsTableBase::Get_misses(), database::cachesubdomainTableBase::Get_misses(), database::cacheurlTableBase::Get_misses(), database::cachehtmlTableBase::Get_misses(), database::cacheparsedTableBase::Get_misses(), database::cachesecondleveldomainTableBase::Get_misses(), database::dictTableBase::Get_occurrence(), database::dockeyTableBase::Get_occurrence(), database::docmetaTableBase::Get_occurrence(), database::queryresultsTableBase::Get_order_position(), database::dockeyposTableBase::Get_paragraph(), database::dataminingalertsTableBase::Get_param(), database::customersTableBase::Get_password(), database::dataminingcustomerTableBase::Get_password(), database::customerdomainblacklistTableBase::Get_path(), database::imagesTableBase::Get_path_part(), database::urlsTableBase::Get_path_part(), Get_pid(), database::imagesTableBase::Get_port(), database::urlsTableBase::Get_port(), database::dockeyposTableBase::Get_position(), database::urlstagesTableBase::Get_primary_ip(), database::urlstagesTableBase::Get_primary_port(), database::customerproducturlsTableBase::Get_PRODUCT_ID(), database::customerproductimagesTableBase::Get_PRODUCT_ID(), database::customerproductkeywordsTableBase::Get_PRODUCT_ID(), database::customerproductsTableBase::Get_productBrand(), database::customerproductsTableBase::Get_productName(), database::customerproductsTableBase::Get_productNo(), database::customerqueriesTableBase::Get_query(), database::keywordqueryTableBase::Get_query_part(), database::urlstagesTableBase::Get_redirect_count(), database::matchcriteriaTableBase::Get_regex(), database::urlstagesTableBase::Get_response_code(), database::customerdomainsTableBase::Get_revisitInterval(), database::locksecondleveldomainTableBase::Get_schedule(), database::syncurlsTableBase::Get_schedule(), database::customersyncurlTableBase::Get_scheduled(), database::customersynccrawlerTableBase::Get_scheduled(), database::schemesTableBase::Get_scheme(), database::imagesTableBase::Get_SCHEME_ID(), database::urlsTableBase::Get_SCHEME_ID(), database::imagesTableBase::Get_search_part(), database::urlsTableBase::Get_search_part(), database::queryresultsTableBase::Get_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Get_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Get_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Get_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Get_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Get_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Get_session(), database::dataminingcustomersessionTableBase::Get_session(), database::customersessionsTableBase::Get_session(), database::cachehtmlTableBase::Get_size(), database::cachesecondleveldomainTableBase::Get_size(), database::cacherobotsTableBase::Get_size(), database::cacheparsedTableBase::Get_size(), database::cachesubdomainTableBase::Get_size(), database::cacheurlTableBase::Get_size(), database::subdomainsTableBase::Get_subdomain(), database::imagesTableBase::Get_SUBDOMAIN_ID(), database::urlsTableBase::Get_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Get_target(), database::hyperlinksTableBase::Get_TARGET_URL_ID(), database::imagelinksTableBase::Get_TARGET_URL_ID(), Get_threadName(), Get_tid(), database::topleveldomainsTableBase::Get_tld(), database::imagesTableBase::Get_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Get_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Get_type(), database::metainfoTableBase::Get_type(), database::customermatchcriteriagrouptypeTableBase::Get_type(), database::dataminingcriteriaTableBase::Get_type(), database::customermatchcriteriaTableBase::Get_type(), database::docmetaTableBase::Get_type(), database::urlstagesTableBase::Get_upload_speed(), database::customersyncurlTableBase::Get_URL_ID(), database::syncurlsTableBase::Get_URL_ID(), database::urlstagesTableBase::Get_URL_ID(), database::latesturlstagesTableBase::Get_URL_ID(), database::docurlTableBase::Get_URL_ID(), database::queryresultsTableBase::Get_URL_ID(), database::customerproducturlsTableBase::Get_URL_ID(), database::imagesTableBase::Get_url_md5(), database::urlsTableBase::Get_url_md5(), database::documentcodeTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_URLSTAGE_ID(), database::hyperlinksTableBase::Get_URLSTAGE_ID(), database::dockeyTableBase::Get_URLSTAGE_ID(), database::docmetaTableBase::Get_URLSTAGE_ID(), database::latesturlstagesTableBase::Get_URLSTAGE_ID(), database::queryresultsTableBase::Get_URLSTAGE_ID(), database::imagelinksTableBase::Get_URLSTAGE_ID(), database::metainfoTableBase::Get_value(), queryserver::XMLQueryResponse::GetPagesByDomain(), queryserver::XMLQueryResponse::GetPagesByUrlPath(), queryserver::XMLQueryResponse::GetPageUrlStageInfo(), htmlparser::DatabaseUrl::InitByTable(), queryserver::XMLQueryResponse::ProcessExistQuery(), bot::DatabaseRepair::ValidateCrawlerSessionTable(), bot::DatabaseRepair::ValidateSecondLevelLockTable(), and bot::DatabaseRepair::ValidateSyncUrlTable().
TableColumn * database::TableBase::GetColumnByName (const std::string & columnName) [inherited]
finds column by it's name.
Parameters:
columnName column name.
Returns:
NULL if not found, column otherwise.
Definition at line 105 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, and THROW_EXCEPTION.
Referenced by parser::GenericWebHtmlParserThread::InsertImages(), database::cacheparsedTableBase::Set_action_time(), database::cachehtmlTableBase::Set_action_time(), database::cacherobotsTableBase::Set_action_time(), database::cachesecondleveldomainTableBase::Set_action_time(), database::cachesubdomainTableBase::Set_action_time(), database::cacheurlTableBase::Set_action_time(), Set_actiontime(), Set_appName(), database::documentcodeTableBase::Set_code(), database::urlstagesTableBase::Set_content_length(), database::urlstagesTableBase::Set_content_md5(), database::urlstagesTableBase::Set_content_type(), database::hyperlinksTableBase::Set_count(), database::locksecondleveldomainTableBase::Set_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::Set_CRAWLERSESSION_ID(), database::syncurlsTableBase::Set_CRAWLERSESSION_ID(), database::customerdomainsTableBase::Set_CUSTOMER_ID(), database::customersessionsTableBase::Set_CUSTOMER_ID(), database::dataminingblacklistTableBase::Set_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::Set_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::Set_CUSTOMER_ID(), database::fencedsearchTableBase::Set_CUSTOMER_ID(), database::customerqueriesTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::Set_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::Set_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::Set_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::Set_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::Set_DATAMININGCRITERIA_ID(), database::dockeyTableBase::Set_DICT_ID(), database::docmetaTableBase::Set_DICT_ID(), database::docurlTableBase::Set_DICT_ID(), database::customerproductkeywordsTableBase::Set_DICT_ID(), database::dockeyposTableBase::Set_DOCKEY_ID(), database::secondleveldomainsTableBase::Set_domain(), database::customerdomainsTableBase::Set_domain(), database::dataminingblacklistTableBase::Set_domain(), database::urlstagesTableBase::Set_download_speed(), database::urlstagesTableBase::Set_download_time(), database::urlstagesTableBase::Set_ext_links(), database::imagesTableBase::Set_found_date(), database::urlsTableBase::Set_found_date(), database::urlstagesTableBase::Set_found_date(), database::customermatchcriteriagrouptypeTableBase::Set_groupPosition(), database::urlstagesTableBase::Set_html_errors(), database::cacherobotsTableBase::Set_ID(), database::customermatchcriteriagrouptypeTableBase::Set_ID(), database::dataminingcriteriaTableBase::Set_ID(), database::urlsTableBase::Set_ID(), database::dataminingcustomersessionTableBase::Set_ID(), database::secondleveldomainsTableBase::Set_ID(), database::dataminingcriteriaalertsTableBase::Set_ID(), database::urlstagesTableBase::Set_ID(), database::dictTableBase::Set_ID(), database::cacheurlTableBase::Set_ID(), database::dockeyposTableBase::Set_ID(), database::dockeyTableBase::Set_ID(), database::customermatchcriteriaTableBase::Set_ID(), database::dataminingcustomerTableBase::Set_ID(), database::documentcodeTableBase::Set_ID(), database::cacheparsedTableBase::Set_ID(), database::customerproductsTableBase::Set_ID(), database::docurlTableBase::Set_ID(), database::topleveldomainsTableBase::Set_ID(), database::subdomainsTableBase::Set_ID(), database::customerproductkeywordsTableBase::Set_ID(), database::docmetaTableBase::Set_ID(), database::hyperlinksTableBase::Set_ID(), database::fencedsearchTableBase::Set_ID(), database::customerdomainblacklistTableBase::Set_ID(), database::customerproducturlsTableBase::Set_ID(), database::imagelinksTableBase::Set_ID(), database::crawlersessionsTableBase::Set_ID(), database::customerproductimagesTableBase::Set_ID(), database::customerqueriesTableBase::Set_ID(), database::customerdomainsTableBase::Set_ID(), database::customersessionsTableBase::Set_ID(), database::keywordqueryTableBase::Set_ID(), database::customersTableBase::Set_ID(), database::customerkeywordsTableBase::Set_ID(), database::cachesecondleveldomainTableBase::Set_ID(), database::imagesTableBase::Set_ID(), database::matchcriteriaTableBase::Set_ID(), database::customersynccrawlerTableBase::Set_ID(), database::customersyncurlTableBase::Set_ID(), database::metainfoTableBase::Set_ID(), database::cachehtmlTableBase::Set_ID(), database::latesturlstagesTableBase::Set_ID(), Set_ID(), database::dataminingalertsTableBase::Set_ID(), database::schemesTableBase::Set_ID(), database::dataminingblacklistTableBase::Set_ID(), database::searchquerykeywordsTableBase::Set_ID(), database::searchqueryTableBase::Set_ID(), database::cachesubdomainTableBase::Set_ID(), database::queryresultsTableBase::Set_ID(), database::syncurlsTableBase::Set_ID(), database::imagelinksTableBase::Set_IMAGE_URL_ID(), database::customerproductimagesTableBase::Set_imageUrl(), database::urlstagesTableBase::Set_int_links(), database::customerdomainsTableBase::Set_isDomainRegex(), database::customerkeywordsTableBase::Set_isKeywordRegex(), database::customerdomainblacklistTableBase::Set_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::Set_isPrimaryKey(), database::dataminingcriteriaTableBase::Set_keyword(), database::dictTableBase::Set_keyword(), database::customerkeywordsTableBase::Set_keyword(), database::searchquerykeywordsTableBase::Set_KEYWORDQUERY_ID(), database::urlstagesTableBase::Set_last_change(), database::customersTableBase::Set_login(), database::dataminingcustomerTableBase::Set_login(), Set_loglevel(), database::customermatchcriteriaTableBase::Set_MATCHCRITERIA_ID(), database::cachesubdomainTableBase::Set_matches(), database::cacheparsedTableBase::Set_matches(), database::cachesecondleveldomainTableBase::Set_matches(), database::cachehtmlTableBase::Set_matches(), database::cacherobotsTableBase::Set_matches(), database::cacheurlTableBase::Set_matches(), Set_message(), database::cacheparsedTableBase::Set_misses(), database::cachesecondleveldomainTableBase::Set_misses(), database::cachesubdomainTableBase::Set_misses(), database::cachehtmlTableBase::Set_misses(), database::cacheurlTableBase::Set_misses(), database::cacherobotsTableBase::Set_misses(), database::dictTableBase::Set_occurrence(), database::dockeyTableBase::Set_occurrence(), database::docmetaTableBase::Set_occurrence(), database::queryresultsTableBase::Set_order_position(), database::dockeyposTableBase::Set_paragraph(), database::dataminingalertsTableBase::Set_param(), database::dataminingcustomerTableBase::Set_password(), database::customersTableBase::Set_password(), database::customerdomainblacklistTableBase::Set_path(), database::imagesTableBase::Set_path_part(), database::urlsTableBase::Set_path_part(), Set_pid(), database::imagesTableBase::Set_port(), database::urlsTableBase::Set_port(), database::dockeyposTableBase::Set_position(), database::urlstagesTableBase::Set_primary_ip(), database::urlstagesTableBase::Set_primary_port(), database::customerproducturlsTableBase::Set_PRODUCT_ID(), database::customerproductimagesTableBase::Set_PRODUCT_ID(), database::customerproductkeywordsTableBase::Set_PRODUCT_ID(), database::customerproductsTableBase::Set_productBrand(), database::customerproductsTableBase::Set_productName(), database::customerproductsTableBase::Set_productNo(), database::customerqueriesTableBase::Set_query(), database::keywordqueryTableBase::Set_query_part(), database::urlstagesTableBase::Set_redirect_count(), database::matchcriteriaTableBase::Set_regex(), database::urlstagesTableBase::Set_response_code(), database::customerdomainsTableBase::Set_revisitInterval(), database::locksecondleveldomainTableBase::Set_schedule(), database::syncurlsTableBase::Set_schedule(), database::customersyncurlTableBase::Set_scheduled(), database::customersynccrawlerTableBase::Set_scheduled(), database::schemesTableBase::Set_scheme(), database::imagesTableBase::Set_SCHEME_ID(), database::urlsTableBase::Set_SCHEME_ID(), database::imagesTableBase::Set_search_part(), database::urlsTableBase::Set_search_part(), database::queryresultsTableBase::Set_SEARCHQUERY_ID(), database::searchquerykeywordsTableBase::Set_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::Set_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::Set_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::Set_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::Set_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::Set_session(), database::customersessionsTableBase::Set_session(), database::dataminingcustomersessionTableBase::Set_session(), database::cacherobotsTableBase::Set_size(), database::cacheparsedTableBase::Set_size(), database::cacheurlTableBase::Set_size(), database::cachesubdomainTableBase::Set_size(), database::cachesecondleveldomainTableBase::Set_size(), database::cachehtmlTableBase::Set_size(), database::subdomainsTableBase::Set_subdomain(), database::imagesTableBase::Set_SUBDOMAIN_ID(), database::urlsTableBase::Set_SUBDOMAIN_ID(), database::customerkeywordsTableBase::Set_target(), database::imagelinksTableBase::Set_TARGET_URL_ID(), database::hyperlinksTableBase::Set_TARGET_URL_ID(), Set_threadName(), Set_tid(), database::topleveldomainsTableBase::Set_tld(), database::imagesTableBase::Set_TOPLEVELDOMAIN_ID(), database::urlsTableBase::Set_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::Set_type(), database::metainfoTableBase::Set_type(), database::dataminingcriteriaTableBase::Set_type(), database::customermatchcriteriagrouptypeTableBase::Set_type(), database::customermatchcriteriaTableBase::Set_type(), database::docmetaTableBase::Set_type(), database::urlstagesTableBase::Set_upload_speed(), database::syncurlsTableBase::Set_URL_ID(), database::customersyncurlTableBase::Set_URL_ID(), database::latesturlstagesTableBase::Set_URL_ID(), database::urlstagesTableBase::Set_URL_ID(), database::customerproducturlsTableBase::Set_URL_ID(), database::docurlTableBase::Set_URL_ID(), database::queryresultsTableBase::Set_URL_ID(), database::urlsTableBase::Set_url_md5(), database::imagesTableBase::Set_url_md5(), database::documentcodeTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_URLSTAGE_ID(), database::docmetaTableBase::Set_URLSTAGE_ID(), database::latesturlstagesTableBase::Set_URLSTAGE_ID(), database::hyperlinksTableBase::Set_URLSTAGE_ID(), database::dockeyTableBase::Set_URLSTAGE_ID(), database::queryresultsTableBase::Set_URLSTAGE_ID(), database::imagelinksTableBase::Set_URLSTAGE_ID(), database::metainfoTableBase::Set_value(), database::MySQLTableBase::SetColumnValues(), and htmlparser::DatabaseUrl::Store().
std::vector< TableColumn * > & database::TableBase::GetColumns () [inherited]
gets list of columns.
Returns:
list of columns.
Definition at line 69 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::columns.
const std::vector< TableColumn * > & database::TableBase::GetConstColumns () const [inherited]
gets const list of columns.
Returns:
list of columns.
Definition at line 75 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::TableBase::columns.
Referenced by database::MySQLInsertOrUpdateStatement::ToSQL(), database::InsertStatement::ToSQL(), and database::UpdateStatement::ToSQL().
void database::TableBase::SetTableAlias (const std::string & tableAlias) [inline, inherited]
sets alias name.
Parameters:
tableAlias table name alias.
Definition at line 123 of file TableBase.h.
References database::TableBase::tableAlias.
const std::string& database::TableBase::GetTableAlias () const [inline, inherited]
gets alias name.
Returns:
tableAlias table name alias.
Definition at line 129 of file TableBase.h.
References database::TableBase::tableAlias.
void database::TableBase::Insert (DatabaseConnection * db) [inherited]
inserts this table.
Parameters:
db database connection.
Definition at line 161 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), and database::DatabaseConnection::Insert().
Referenced by toolbot::CommerceSearchTools::AddCustomer(), indexing::GenericWebDictionary::CommitContent(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), crawler::UrlFetcherThread::GetNextCrawlerSessionID(), toolbot::DataMiningTools::InsertDataminingUser(), parser::GenericWebHtmlParserThread::InsertMeta(), queryserver::XMLQueryResponse::LogQuery(), log::DatabaseLogging::OnLog(), toolbot::DataMiningTools::RegisterDataminingAlert(), queryserver::XMLQueryResponse::SaveResults(), and bot::Bot::WatchDog().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db) [inherited]
inserts or updates this table.
Parameters:
db database connection.
Definition at line 169 of file TableBase.cpp.
Referenced by indexing::GenericWebDictionary::CommitContent(), indexing::GenericWebDictionary::CommitMeta(), crawler::UrlFetcherThread::GetHtmlCodeFromUrl(), caching::CacheSecondLevelDomain::GetSecondLevelIDByDomain(), caching::CacheSubdomain::GetSubdomainIDByDomain(), parser::GenericWebHtmlParserThread::InsertImages(), parser::GenericWebHtmlParserThread::InsertLinks(), queryserver::XMLQueryResponse::LogQuery(), crawler::CommerceSearchFetcherThread::ReserveNextUrls(), parser::CommerceSearchProduct::Store(), and htmlparser::DatabaseUrl::Store().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db, TableColumnDefinition * sumColumn) [inherited]
inserts or updates this table adding SUM()-type columns.
Parameters:
db database connection.
sumColumn columns to replace with sum instead of new value.
Definition at line 174 of file TableBase.cpp.
References database::InsertOrUpdateStatement::AddSumUpColumn(), database::TableBase::CheckInitialization(), and database::DatabaseConnection::InsertOrUpdate().
void database::TableBase::InsertOrUpdate (DatabaseConnection * db, const std::vector< TableColumnDefinition * > & sumColumn) [inherited]
inserts or updates this table adding SUM()-type columns.
Parameters:
db database connection.
sumColumn columns to replace with sum instead of new value.
Definition at line 185 of file TableBase.cpp.
References database::InsertOrUpdateStatement::AddSumUpColumns(), database::TableBase::CheckInitialization(), and database::DatabaseConnection::InsertOrUpdate().
void database::TableBase::Update (DatabaseConnection * db, const TableBaseUpdateParam & param) const [inherited]
updates this table.
Parameters:
db database connection.
param update parameters.
Definition at line 196 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBaseUpdateParam::limit, database::TableBaseUpdateParam::onlyDirtyColumns, database::TableBaseUpdateParam::orderCols, database::Statement::SetLimit(), database::DatabaseConnection::Update(), and database::TableBaseUpdateParam::whereCols.
Referenced by crawler::CommerceSearchFetcherThread::GetNextSecondLevelDomain(), crawler::FencedUrlFetcherThread::LockNextSecondLevelDomain(), crawler::GenericWebUrlFetcherThread::LockNextSecondLevelDomain(), crawler::UrlFetcherThread::RemoveCrawlerReservation(), crawler::GenericWebUrlFetcherThread::RemoveSecondLevelReservation(), crawler::GenericWebUrlFetcherThread::ReserveNextUrls(), and parser::GenericWebHtmlParserThread::UpdateUrlstageInfos().
TableBase * database::TableBase::CreateInstance (const TableDefinitionCreateParam & param) [static, inherited]
factory function for this class.
Parameters:
param table definition creation parameter.
Returns:
NULL on error, table base on success.
Definition at line 64 of file TableBase.cpp.
References database::TableDefinition::CreateInstance(), and database::TableBase::TableBase().
Referenced by database::TableBase::CreateColumns(), database::cachehtmlTableBase::CreateTableDefinition(), database::dataminingblacklistTableBase::CreateTableDefinition(), database::customermatchcriteriaTableBase::CreateTableDefinition(), database::urlsTableBase::CreateTableDefinition(), database::schemesTableBase::CreateTableDefinition(), database::dictTableBase::CreateTableDefinition(), database::docurlTableBase::CreateTableDefinition(), database::customerproductkeywordsTableBase::CreateTableDefinition(), database::searchquerykeywordsTableBase::CreateTableDefinition(), database::crawlersessionsTableBase::CreateTableDefinition(), database::cacherobotsTableBase::CreateTableDefinition(), database::documentcodeTableBase::CreateTableDefinition(), database::metainfoTableBase::CreateTableDefinition(), database::customersTableBase::CreateTableDefinition(), database::fencedsearchTableBase::CreateTableDefinition(), database::queryresultsTableBase::CreateTableDefinition(), database::searchqueryTableBase::CreateTableDefinition(), database::imagesTableBase::CreateTableDefinition(), database::imagelinksTableBase::CreateTableDefinition(), database::cacheurlTableBase::CreateTableDefinition(), database::dockeyposTableBase::CreateTableDefinition(), database::customersessionsTableBase::CreateTableDefinition(), database::keywordqueryTableBase::CreateTableDefinition(), database::customerproductimagesTableBase::CreateTableDefinition(), database::cachesecondleveldomainTableBase::CreateTableDefinition(), database::matchcriteriaTableBase::CreateTableDefinition(), database::secondleveldomainsTableBase::CreateTableDefinition(), database::urlstagesTableBase::CreateTableDefinition(), database::cacheparsedTableBase::CreateTableDefinition(), database::customerproductsTableBase::CreateTableDefinition(), database::latesturlstagesTableBase::CreateTableDefinition(), database::customerdomainsTableBase::CreateTableDefinition(), database::customerproducturlsTableBase::CreateTableDefinition(), database::dataminingcustomersessionTableBase::CreateTableDefinition(), database::dataminingalertsTableBase::CreateTableDefinition(), database::docmetaTableBase::CreateTableDefinition(), database::customerqueriesTableBase::CreateTableDefinition(), database::syncurlsTableBase::CreateTableDefinition(), database::topleveldomainsTableBase::CreateTableDefinition(), database::customerkeywordsTableBase::CreateTableDefinition(), database::customermatchcriteriagrouptypeTableBase::CreateTableDefinition(), database::customersyncurlTableBase::CreateTableDefinition(), database::dataminingcustomerTableBase::CreateTableDefinition(), CreateTableDefinition(), database::dockeyTableBase::CreateTableDefinition(), database::dataminingcriteriaalertsTableBase::CreateTableDefinition(), database::hyperlinksTableBase::CreateTableDefinition(), database::customerdomainblacklistTableBase::CreateTableDefinition(), database::cachesubdomainTableBase::CreateTableDefinition(), database::dataminingcriteriaTableBase::CreateTableDefinition(), database::customersynccrawlerTableBase::CreateTableDefinition(), database::subdomainsTableBase::CreateTableDefinition(), database::locksecondleveldomainTableBase::CreateTableDefinition(), database::cacheurlTableBase::GetDefinition_action_time(), database::cacherobotsTableBase::GetDefinition_action_time(), database::cachesecondleveldomainTableBase::GetDefinition_action_time(), database::cacheparsedTableBase::GetDefinition_action_time(), database::cachesubdomainTableBase::GetDefinition_action_time(), database::cachehtmlTableBase::GetDefinition_action_time(), GetDefinition_actiontime(), GetDefinition_appName(), database::documentcodeTableBase::GetDefinition_code(), database::urlstagesTableBase::GetDefinition_content_length(), database::urlstagesTableBase::GetDefinition_content_md5(), database::urlstagesTableBase::GetDefinition_content_type(), database::hyperlinksTableBase::GetDefinition_count(), database::locksecondleveldomainTableBase::GetDefinition_CRAWLERSESSION_ID(), database::customersynccrawlerTableBase::GetDefinition_CRAWLERSESSION_ID(), database::syncurlsTableBase::GetDefinition_CRAWLERSESSION_ID(), database::customersessionsTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingblacklistTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingcustomersessionTableBase::GetDefinition_CUSTOMER_ID(), database::fencedsearchTableBase::GetDefinition_CUSTOMER_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_CUSTOMER_ID(), database::customerdomainsTableBase::GetDefinition_CUSTOMER_ID(), database::customerqueriesTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerdomainblacklistTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customersynccrawlerTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customermatchcriteriaTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerproductsTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customerkeywordsTableBase::GetDefinition_CUSTOMERDOMAIN_ID(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_CUSTOMERMATCHCRITERIA_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_DATAMININGALERT_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_DATAMININGCRITERIA_ID(), database::docurlTableBase::GetDefinition_DICT_ID(), database::customerproductkeywordsTableBase::GetDefinition_DICT_ID(), database::dockeyTableBase::GetDefinition_DICT_ID(), database::docmetaTableBase::GetDefinition_DICT_ID(), database::dockeyposTableBase::GetDefinition_DOCKEY_ID(), database::secondleveldomainsTableBase::GetDefinition_domain(), database::dataminingblacklistTableBase::GetDefinition_domain(), database::customerdomainsTableBase::GetDefinition_domain(), database::urlstagesTableBase::GetDefinition_download_speed(), database::urlstagesTableBase::GetDefinition_download_time(), database::urlstagesTableBase::GetDefinition_ext_links(), database::imagesTableBase::GetDefinition_found_date(), database::urlsTableBase::GetDefinition_found_date(), database::urlstagesTableBase::GetDefinition_found_date(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_groupPosition(), database::urlstagesTableBase::GetDefinition_html_errors(), database::crawlersessionsTableBase::GetDefinition_ID(), database::keywordqueryTableBase::GetDefinition_ID(), database::matchcriteriaTableBase::GetDefinition_ID(), database::schemesTableBase::GetDefinition_ID(), database::searchqueryTableBase::GetDefinition_ID(), database::secondleveldomainsTableBase::GetDefinition_ID(), database::subdomainsTableBase::GetDefinition_ID(), database::topleveldomainsTableBase::GetDefinition_ID(), database::dataminingcustomerTableBase::GetDefinition_ID(), database::dictTableBase::GetDefinition_ID(), database::customersTableBase::GetDefinition_ID(), database::dataminingcriteriaTableBase::GetDefinition_ID(), database::dataminingalertsTableBase::GetDefinition_ID(), database::customerproductimagesTableBase::GetDefinition_ID(), database::documentcodeTableBase::GetDefinition_ID(), database::customerqueriesTableBase::GetDefinition_ID(), database::customersessionsTableBase::GetDefinition_ID(), database::customersyncurlTableBase::GetDefinition_ID(), database::dataminingblacklistTableBase::GetDefinition_ID(), database::dataminingcustomersessionTableBase::GetDefinition_ID(), database::customerproductkeywordsTableBase::GetDefinition_ID(), database::docurlTableBase::GetDefinition_ID(), database::fencedsearchTableBase::GetDefinition_ID(), database::customerproducturlsTableBase::GetDefinition_ID(), database::latesturlstagesTableBase::GetDefinition_ID(), database::searchquerykeywordsTableBase::GetDefinition_ID(), database::dockeyposTableBase::GetDefinition_ID(), database::customerdomainblacklistTableBase::GetDefinition_ID(), database::customersynccrawlerTableBase::GetDefinition_ID(), database::metainfoTableBase::GetDefinition_ID(), database::dockeyTableBase::GetDefinition_ID(), database::hyperlinksTableBase::GetDefinition_ID(), database::customermatchcriteriaTableBase::GetDefinition_ID(), database::imagelinksTableBase::GetDefinition_ID(), database::dataminingcriteriaalertsTableBase::GetDefinition_ID(), database::cacheurlTableBase::GetDefinition_ID(), database::cachehtmlTableBase::GetDefinition_ID(), database::cacheparsedTableBase::GetDefinition_ID(), database::cachesecondleveldomainTableBase::GetDefinition_ID(), database::cachesubdomainTableBase::GetDefinition_ID(), database::cacherobotsTableBase::GetDefinition_ID(), database::customerproductsTableBase::GetDefinition_ID(), database::customerdomainsTableBase::GetDefinition_ID(), database::customerkeywordsTableBase::GetDefinition_ID(), database::queryresultsTableBase::GetDefinition_ID(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_ID(), database::docmetaTableBase::GetDefinition_ID(), database::syncurlsTableBase::GetDefinition_ID(), GetDefinition_ID(), database::imagesTableBase::GetDefinition_ID(), database::urlsTableBase::GetDefinition_ID(), database::urlstagesTableBase::GetDefinition_ID(), database::imagelinksTableBase::GetDefinition_IMAGE_URL_ID(), database::customerproductimagesTableBase::GetDefinition_imageUrl(), database::urlstagesTableBase::GetDefinition_int_links(), database::customerdomainsTableBase::GetDefinition_isDomainRegex(), database::customerkeywordsTableBase::GetDefinition_isKeywordRegex(), database::customerdomainblacklistTableBase::GetDefinition_isPathRegex(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_isPrimaryKey(), database::dictTableBase::GetDefinition_keyword(), database::dataminingcriteriaTableBase::GetDefinition_keyword(), database::customerkeywordsTableBase::GetDefinition_keyword(), database::searchquerykeywordsTableBase::GetDefinition_KEYWORDQUERY_ID(), database::urlstagesTableBase::GetDefinition_last_change(), database::dataminingcustomerTableBase::GetDefinition_login(), database::customersTableBase::GetDefinition_login(), GetDefinition_loglevel(), database::customermatchcriteriaTableBase::GetDefinition_MATCHCRITERIA_ID(), database::cacherobotsTableBase::GetDefinition_matches(), database::cacheurlTableBase::GetDefinition_matches(), database::cacheparsedTableBase::GetDefinition_matches(), database::cachehtmlTableBase::GetDefinition_matches(), database::cachesecondleveldomainTableBase::GetDefinition_matches(), database::cachesubdomainTableBase::GetDefinition_matches(), GetDefinition_message(), database::cacherobotsTableBase::GetDefinition_misses(), database::cacheurlTableBase::GetDefinition_misses(), database::cachehtmlTableBase::GetDefinition_misses(), database::cacheparsedTableBase::GetDefinition_misses(), database::cachesecondleveldomainTableBase::GetDefinition_misses(), database::cachesubdomainTableBase::GetDefinition_misses(), database::dictTableBase::GetDefinition_occurrence(), database::dockeyTableBase::GetDefinition_occurrence(), database::docmetaTableBase::GetDefinition_occurrence(), database::queryresultsTableBase::GetDefinition_order_position(), database::dockeyposTableBase::GetDefinition_paragraph(), database::dataminingalertsTableBase::GetDefinition_param(), database::dataminingcustomerTableBase::GetDefinition_password(), database::customersTableBase::GetDefinition_password(), database::customerdomainblacklistTableBase::GetDefinition_path(), database::imagesTableBase::GetDefinition_path_part(), database::urlsTableBase::GetDefinition_path_part(), GetDefinition_pid(), database::urlsTableBase::GetDefinition_port(), database::imagesTableBase::GetDefinition_port(), database::dockeyposTableBase::GetDefinition_position(), database::urlstagesTableBase::GetDefinition_primary_ip(), database::urlstagesTableBase::GetDefinition_primary_port(), database::customerproductimagesTableBase::GetDefinition_PRODUCT_ID(), database::customerproductkeywordsTableBase::GetDefinition_PRODUCT_ID(), database::customerproducturlsTableBase::GetDefinition_PRODUCT_ID(), database::customerproductsTableBase::GetDefinition_productBrand(), database::customerproductsTableBase::GetDefinition_productName(), database::customerproductsTableBase::GetDefinition_productNo(), database::customerqueriesTableBase::GetDefinition_query(), database::keywordqueryTableBase::GetDefinition_query_part(), database::urlstagesTableBase::GetDefinition_redirect_count(), database::matchcriteriaTableBase::GetDefinition_regex(), database::urlstagesTableBase::GetDefinition_response_code(), database::customerdomainsTableBase::GetDefinition_revisitInterval(), database::locksecondleveldomainTableBase::GetDefinition_schedule(), database::syncurlsTableBase::GetDefinition_schedule(), database::customersyncurlTableBase::GetDefinition_scheduled(), database::customersynccrawlerTableBase::GetDefinition_scheduled(), database::schemesTableBase::GetDefinition_scheme(), database::imagesTableBase::GetDefinition_SCHEME_ID(), database::urlsTableBase::GetDefinition_SCHEME_ID(), database::imagesTableBase::GetDefinition_search_part(), database::urlsTableBase::GetDefinition_search_part(), database::searchquerykeywordsTableBase::GetDefinition_SEARCHQUERY_ID(), database::queryresultsTableBase::GetDefinition_SEARCHQUERY_ID(), database::locksecondleveldomainTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::fencedsearchTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::syncurlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::urlsTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::imagesTableBase::GetDefinition_SECONDLEVELDOMAIN_ID(), database::searchqueryTableBase::GetDefinition_session(), database::customersessionsTableBase::GetDefinition_session(), database::dataminingcustomersessionTableBase::GetDefinition_session(), database::cacherobotsTableBase::GetDefinition_size(), database::cachesecondleveldomainTableBase::GetDefinition_size(), database::cacheparsedTableBase::GetDefinition_size(), database::cachesubdomainTableBase::GetDefinition_size(), database::cacheurlTableBase::GetDefinition_size(), database::cachehtmlTableBase::GetDefinition_size(), database::subdomainsTableBase::GetDefinition_subdomain(), database::imagesTableBase::GetDefinition_SUBDOMAIN_ID(), database::urlsTableBase::GetDefinition_SUBDOMAIN_ID(), database::customerkeywordsTableBase::GetDefinition_target(), database::hyperlinksTableBase::GetDefinition_TARGET_URL_ID(), database::imagelinksTableBase::GetDefinition_TARGET_URL_ID(), GetDefinition_threadName(), GetDefinition_tid(), database::topleveldomainsTableBase::GetDefinition_tld(), database::urlsTableBase::GetDefinition_TOPLEVELDOMAIN_ID(), database::imagesTableBase::GetDefinition_TOPLEVELDOMAIN_ID(), database::dataminingalertsTableBase::GetDefinition_type(), database::dataminingcriteriaTableBase::GetDefinition_type(), database::metainfoTableBase::GetDefinition_type(), database::customermatchcriteriaTableBase::GetDefinition_type(), database::customermatchcriteriagrouptypeTableBase::GetDefinition_type(), database::docmetaTableBase::GetDefinition_type(), database::urlstagesTableBase::GetDefinition_upload_speed(), database::customersyncurlTableBase::GetDefinition_URL_ID(), database::latesturlstagesTableBase::GetDefinition_URL_ID(), database::docurlTableBase::GetDefinition_URL_ID(), database::customerproducturlsTableBase::GetDefinition_URL_ID(), database::syncurlsTableBase::GetDefinition_URL_ID(), database::queryresultsTableBase::GetDefinition_URL_ID(), database::urlstagesTableBase::GetDefinition_URL_ID(), database::urlsTableBase::GetDefinition_url_md5(), database::imagesTableBase::GetDefinition_url_md5(), database::documentcodeTableBase::GetDefinition_URLSTAGE_ID(), database::latesturlstagesTableBase::GetDefinition_URLSTAGE_ID(), database::metainfoTableBase::GetDefinition_URLSTAGE_ID(), database::hyperlinksTableBase::GetDefinition_URLSTAGE_ID(), database::dockeyTableBase::GetDefinition_URLSTAGE_ID(), database::imagelinksTableBase::GetDefinition_URLSTAGE_ID(), database::docmetaTableBase::GetDefinition_URLSTAGE_ID(), database::queryresultsTableBase::GetDefinition_URLSTAGE_ID(), and database::metainfoTableBase::GetDefinition_value().
void database::TableBase::CopyColumns (const TableBase * base) [inherited]
copies column definitions and values from another table.
Parameters:
base table to copy from.
Definition at line 117 of file TableBase.cpp.
References database::TableBase::CheckInitialization(), database::TableBase::columns, database::TableColumn::CopyValue(), and database::TableBase::GetConstColumnByName().
void database::TableBase::CreateColumns () [protected, inherited]
creates columns according to database::TableBase::definition.
Definition at line 55 of file TableBase.cpp.
References database::TableBase::columns, database::TableBase::CreateInstance(), database::TableColumn::CreateInstance(), database::TableBase::definition, and database::TableDefinition::GetColumnDefinitions().
Referenced by database::TableBase::TableBase().
The documentation for this class was generated from the following files:
Database/generated/logmessagesTableBase.h
Database/generated/logmessagesTableBase.cpp