DeepNet: indexing::DataminingNotifierEmail Class Reference
indexing::DataminingNotifierEmail Class Reference
#include <DataminingNotifierEmail.h>
Public Types
enum DataminingNotifierType { NOTIFY_TYPE_UNKNOWN = 0, NOTIFY_TYPE_EMAIL = 1 }
Public Member Functions
DataminingNotifierEmail (const std::string &emailAddress, const std::string &emailSubject)
virtual ~DataminingNotifierEmail ()
void AddAlert (DataminingCriteria *alert)
Protected Member Functions
const std::vector
< DataminingCriteria * > & GetAlerts () const
Private Member Functions
virtual void OnNotify ()
Private Attributes
std::string emailAddress
std::string emailSubject
Detailed Description
Definition at line 15 of file DataminingNotifierEmail.h.
Member Enumeration Documentation
enum indexing::DataminingNotifier::DataminingNotifierType [inherited]
Enumerator:
NOTIFY_TYPE_UNKNOWN
NOTIFY_TYPE_EMAIL
Definition at line 17 of file DataminingNotifier.h.
Constructor & Destructor Documentation
indexing::DataminingNotifierEmail::DataminingNotifierEmail (const std::string & emailAddress, const std::string & emailSubject)
Definition at line 13 of file DataminingNotifierEmail.cpp.
References emailAddress, emailSubject, and tools::StringTools::ReplaceString().
indexing::DataminingNotifierEmail::~DataminingNotifierEmail () [virtual]
Definition at line 30 of file DataminingNotifierEmail.cpp.
Member Function Documentation
void indexing::DataminingNotifierEmail::OnNotify () [private, virtual]
Reimplemented from indexing::DataminingNotifier.
Definition at line 34 of file DataminingNotifierEmail.cpp.
References emailAddress, emailSubject, tools::StringTools::ExecuteCommand(), and indexing::DataminingNotifier::GetAlerts().
void indexing::DataminingNotifier::AddAlert (DataminingCriteria * alert) [inline, inherited]
Definition at line 27 of file DataminingNotifier.h.
References indexing::DataminingNotifier::vecAlert.
const std::vector<DataminingCriteria*>& indexing::DataminingNotifier::GetAlerts () const [inline, protected, inherited]
Definition at line 33 of file DataminingNotifier.h.
References indexing::DataminingNotifier::vecAlert.
Referenced by OnNotify().
Member Data Documentation
std::string indexing::DataminingNotifierEmail::emailAddress [private]
Definition at line 24 of file DataminingNotifierEmail.h.
Referenced by DataminingNotifierEmail(), and OnNotify().
std::string indexing::DataminingNotifierEmail::emailSubject [private]
Definition at line 25 of file DataminingNotifierEmail.h.
Referenced by DataminingNotifierEmail(), and OnNotify().
The documentation for this class was generated from the following files:
Indexer/src/DataminingNotifierEmail.h
Indexer/src/DataminingNotifierEmail.cpp